### ISSUE TITLE
Question about scrollbars

### ISSUE THREAD

**Issue by madjake45** [jgthms/bulma#100]
Is there a reason why the y scrollbar is forced on bulma as this seems to be strange behavior for something like the hero content where from the looks of it the design is intended for use cases where the content is designed to be scroll free?

**Comment by jgthms** [comment]
It's to prevent the page from "jumping" when you navigate from a page with a scrollbar to a page without one.

I agree that there should be an option to hide that on the `html` element.

**Comment by marvinroger** [comment]
@jgthms I was not able to find any option for that. Am I missing something?

**Comment by emalihin** [comment]
@jgthms closed? just decided to use bulma in my vuejs SPA project and the first thing I saw was the horizontal and vertical scrollbars. :(
