### ISSUE TITLE
Uppercase helpers

### ISSUE THREAD

**Issue by matteomanf** [jgthms/bulma#1001]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.0]

This is a **Sass** issue: I'm using version [0.5.0]
I am sure this issue is **not a duplicate**

### Description

Is it possible to add a simple typography helper for all lowercase/uppercase, `.is-lowercase`, `is-uppercase`?

It's simple and easy but would be great not needing to write it every project!

**Comment by Wikiki** [comment]
+1

**Comment by jgthms** [comment]
Please don't `+1` but rather use reactions.
