### ISSUE TITLE
Multi-word label wraps on horizontal form

### ISSUE THREAD

**Issue by cringer** [jgthms/bulma#1004]
### Overview of the problem

This is about the Bulma **CSS framework**

My **browser** is: Google Chrome

### Description

When using horizontal forms with multi-word labels, the label field wraps.

### Steps to Reproduce

1. Create a horizontal form
2. Make sure the label has multiple words (In my case "Redirect URL")
2. View in the browser

### Expected behavior

I would expect that the label would stay on one line.  If it is because of a container limitation I would think the input field would shorten instead of wrapping the label.

### Actual behavior

The label text wraps to the next line.

**Comment by jgthms** [comment]
This is intentional to keep the inputs alignment,  which is more important.

**Comment by cringer** [comment]
Wrapping a multi-word label when there is tons of space where the input boxes are is intentional?  The form looks horrendous when your wrapping a label when the input box fills up 3/4th the row.

With that being said, is there a way to force the input boxes to take up a specific amount of space?  That way the label wont have to wrap?

**Comment by jks211** [comment]
Also having the issue, plenty of space to the right of the input but labels wrapping very badly.

**Comment by alphapseudo** [comment]
@cringer  A potential workaround would be using a non-breaking space (e.g. `Redirect&nbsp;URL`) to prevent the wrapping.

**Comment by bitvilag** [comment]
I can confirm. @alphapseudo -s solution works.

**Comment by airblade** [comment]
This works for me:

```css
.field-label {
  flex-grow: 1.5;
}
```
