### ISSUE TITLE
[Question] How to disable menu item?

### ISSUE THREAD

**Issue by gyzerok** [jgthms/bulma#1006]
Hello everyone!

I am using a `menu` component on my page. Under some circumstances some of the menu items should be disabled. Is there a way to achieve this behaviour?

**Comment by carlosqsilva** [comment]
you could make a class like:

.is-disable{
	pointer-events: none;
	opacity: .65;
}

**Comment by gyzerok** [comment]
Should there be such feature in Bulma itself? Does it sound like a thing from which other Bulma users can benefit? Is there original reason why such modifier was not included?

**Comment by Wikiki** [comment]
I agree with you @gyzerok.
It would be nice to have the possibility to disable a menu item uysing Bulma core.

**Comment by gyzerok** [comment]
It might even be "lets have a way to be able to disable any clickable element". For example currently I need to disable menu items and tabs both. For now using "hack" described here.

**Comment by gyzerok** [comment]
It looks like nothing is happening about this issue, closing it.

**Comment by cameronelliott** [comment]
This is my favorite issue of all time.
