### ISSUE TITLE
Suggestion: Simple image gallery

### ISSUE THREAD

**Issue by skysteve** [jgthms/bulma#1008]
### Overview of the problem

This is about the Bulma **CSS framework** 

I am sure this issue is **not a duplicate**

### Description

It would be nice to have a simple image gallery. Maybe something like https://codepen.io/oknoblich/pen/ELfzd (not my work)

**Comment by jgthms** [comment]
I feel a good gallery to work well requires proper JS interactions. Providing only styling makes little sense.

Photoswipe is my favourite.
