### ISSUE TITLE
[Question/Suggestion] - Pricing Component

### ISSUE THREAD

**Issue by lsbyerley** [jgthms/bulma#1009]
### Overview of the problem

This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**?

### Description

Curious if there is any plans to introduce a pricing component to the framework? 

I don't mind to develop one on my own, however, also curious what components you think would be best to build them from.

**Comment by jgthms** [comment]
I believe a pricing component is too specific, and too big to fit this framework.

If you build one, you can add it to the extensions page: http://bulma.io/extensions/
