### ISSUE TITLE
How to use both has-addons and is-grouped together?

### ISSUE THREAD

**Issue by prashant-saxena** [jgthms/bulma#1011]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.0]
I am sure this issue is **not a duplicate**?

Description of the bug, enhancement, or question

First of all, now I see a reason to say bye-bye to bootstrap and give a serious try to bulma. Right now I'm
only interested in nothing but horizontal forms, as I'm redesigning a CMS. The only things that I was not able to do is this:

```
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">From</label>
  </div>
  <div class="field-body">
    <div class="field is-grouped">
      <div class="control is-expanded">
        <input class="input" type="text" placeholder="Name">
      </div>
      <div class="control">
        <button type="button" class="button is-primary">
          <span class="icon is-small">
            <i class="fa fa-image"></i>
          </span>
        </button>
      </div>
      <div class="control">
        <button type="button" class="button is-primary">
          <span class="icon is-small">
            <i class="fa fa-trash"></i>
          </span>
        </button>
      </div>
    </div>
    <p class="help is-danger">I need help</p>
  </div>
</div>
```
I want to use fa-image icon as if I have used **has-addons** and fa-trash as I have used **is-grouped**.
Second thing when you use either of them how and where you should place help messages correctly. In the above code it's appearing at far right where as the correct place is exactly below input field.

Cheers and Good Luck for v1.0...

**Comment by jgthms** [comment]
`.field-body` already groups fields together. You don't need `.is-grouped`.

Example: https://codepen.io/jgthms/pen/LjbKrw
