### ISSUE TITLE
is-toggle : tabs not equal

### ISSUE THREAD

**Issue by melTr** [jgthms/bulma#1012]
Is it about Bulma
 Is it a bug/feature/question 
I'm using Bulma **version** [0.5.0]
 am sure this issue is **not a duplicate**? -->

### Description

Tabs are not equal

### Steps to Reproduce

use exactly the code from docs : http://bulma.io/documentation/components/tabs/

### Expected behavior

1st tab is not equal
![selection_184](https://user-images.githubusercontent.com/1063951/28952864-20729d62-78a2-11e7-9c83-c25a4ba58d94.png)

(gets same behavior for my own code in my project)
![selection_186](https://user-images.githubusercontent.com/1063951/28952923-939cddf2-78a2-11e7-8f90-0444ff215ffd.png)

**Comment by jgthms** [comment]
I can't reproduce this. Do you have a Codepen?

**Comment by melTr** [comment]
Found the responsible : <div class='content'> but don't know why:
https://codepen.io/mel47/pen/oeZzaL

**Comment by VizuaaLOG** [comment]
It seems to be the margin top applied within the `content.sass` file on line `21`.

```css
.content li + li {
    margin-top: 0.25em;
}
```

The first tab will not match this so does not get the margin.
