### ISSUE TITLE
Ability to set page width

### ISSUE THREAD

**Issue by tomick** [jgthms/bulma#103]
Hi,

It will be great if grid would be more customizable. For example if I need container width to set 1150px. It can be done, for example, via variables file. Default setting can be still 960px, but Bulma might be more easier to maintain.

**Comment by jgthms** [comment]
Yeah, I should turn the breakpoints into variables, and maybe add a `$widescreen` one.

**Comment by tomick** [comment]
@jgthms As I can see it now, it's only change .container max-width from 960px to `$widescreen` value? Because it uses max-width property for +desktop mixin, am I right?

**Comment by jgthms** [comment]
Yes absolutely. It was there at some point but I removed it because it made the website too wide to be readable.

**Comment by FrankFang** [comment]
Why close this issue?
I like this feature.
