### ISSUE TITLE
AMP-compatible mini CSS?

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#1037]
Is it possible to for you @jgthms to generate a minimal, content-only stylesheet that's compatible with Accelerated Mobile Pages (AMP) https://www.ampproject.org/?

It will be generic enough it I think it's worth it for bulma to cater to it. AMP is basically a content-only, barebones, mobile page.

https://www.ampproject.org/docs/guides/responsive/style_pages

Situation: I use bulma on https://devel.tech, and I want to provide nice fonts/styling/spacing. The issue is the AMP standard has limitations.

It must be inside a `<style>` tag, no external CSS is allowed.

There is also [prohibited css](https://www.ampproject.org/docs/guides/responsive/style_pages#disallowed-styles), such as no ``!important``, ``behavior``, or ``filter``.

As it stands, I'm doing what you'd expect, taking pieces of bulma and copying it in. I think it'd be a worthwhile thing to have a `dist/bulma-amp.css`. Or a base .scss that would only build the stuff needed in barebones AMP styles w/ bulma.

**Comment by jgthms** [comment]
Since AMP is about including the bare minimum a page needs, it wouldn't make sense to build a package where 90% of the CSS wouldn't be used.

Just import what is required by your page. It's right there in their docs:

> When using preprocessors, pay special attention to what you include; load only what your pages use.

**Comment by tony** [comment]
>  it wouldn't make sense to build a package where 90% of the CSS wouldn't be used.

If the rest of the 10% looks the same for pretty much everyone, then it could be helpful. But basically yes, a lot of stuff gets chucked out when using AMP. Including JavaScript. I still feel shell-shocked having to start from scratch with the CSS.

A lot of the pain comes from build utilities and is out of the scope of this.

> Just import what is required by your page. It's right there in their docs:

I've been trying various things out. There are various snaggles. But in general I'm using variables I have set for bulma and start from there building my own mini-css file.

**Comment by jgthms** [comment]
Feel free to create a `bulma-amp` extension for people to use. But it's not something I want to maintain as part of Bulma.

**Comment by tony** [comment]
Yes. I'm still making great gains with your framework. Thanks for it

**Comment by richardboydnz** [comment]
Has anyone figured out how to make Bulma compatible with AMP yet - 286 !important rules is a killer. As there is still no bulimia-amp, do we just need to manually take out all the !important modifiers and hope that it works the same?

**Comment by advaith1** [comment]
https://cristianpb.github.io/blog/bulma-amp
