### ISSUE TITLE
Modal is not in middle center on IE11

### ISSUE THREAD

**Issue by oraclebox** [jgthms/bulma#1038]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.5.1] 
My **browser** is: IE-11

### Description

Modal not in middle center on IE11.

### Steps to Reproduce

1. First Step
I just follow in code in bulma doc.
```
<div class="modal is-active">
  <div class="modal-background"></div>
  <div class="modal-content">
    <p class="image is-4by3">
      <img src="http://bulma.io/images/placeholders/1280x960.png">
    </p>
  </div>
  <button class="modal-close is-large"></button>
</div>
```

2. Also, sample in an official website
http://bulma.io/documentation/components/modal/

### Actual behavior

(Unexpected) Under IE 11 
![IE 11](https://farm5.staticflickr.com/4357/36392407906_fdac46e033_b.jpg)

**Comment by scottwernervt** [comment]
Duplicate #460

**Comment by jgthms** [comment]
Thanks @scottwernervt
