### ISSUE TITLE
Placeholders for display while loading data

### ISSUE THREAD

**Issue by KaRkY** [jgthms/bulma#1041]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Would it be posible to get styles for placeholders? Something similar to [this](https://rawgit.com/buildo/react-placeholder/master/examples/build/index.html). I would like to have this placeholders in table so I can display them while data is loading.

**Comment by jgthms** [comment]
Quite difficult to implement, since it requires to know exactly how the actual content is laid out. Could be an extension.

**Comment by KaRkY** [comment]
Just so if anybody is interested I partialy solved this for tables it is not perfect. Basicaly I used background-clip.

Example:
https://jsfiddle.net/ngfLwed3/1/
