### ISSUE TITLE
Where can I check the summary of new features or bug fixes when Bulma is upgraded?

### ISSUE THREAD

**Issue by re-fort** [jgthms/bulma#1044]
### Overview of the problem
Where can I check the summary of new features or bug fixes when Bulma is upgraded?

### Description
I checked Bulma docs and the release note on github, but I can't find summary.

**Comment by jgthms** [comment]
https://github.com/jgthms/bulma/blob/master/CHANGELOG.md

**Comment by re-fort** [comment]
Thanks.
I've missed that.
