### ISSUE TITLE
Front page multple redraws causing high CPU load

### ISSUE THREAD

**Issue by kmare** [jgthms/bulma#1046]
### Overview of the problem
I'm not sure if it's only me, but I've noticed that problem with a few different machines. The bulma.io front page is causing a constant CPU load that shouldn't happen. Checked the performance tab under developer tools and it seems like there are many "Recalculate Style", "CC Graph Reduction" and "Cycle Collection" lines. Figured it should be caused by the section with the twitter widgets. With a simple "display: none" on that section, the cpu load went down instantly and indeed that was it.

This is about the Bulma **Website**

My **browser** is: Firefox 54, Chrome 60. Linux and Windows tested.

### Steps to Reproduce
Simply visit the home page.

### Expected behavior
No CPU load should be there.

### Actual behavior
1 CPU core at 100% (25% of the CPU on an i5 and 12% on an i7 with 8 threads)

**Comment by jgthms** [comment]
That is an issue. I'll fix that.

**Comment by craftyguy** [comment]
This still seems to be happening on bulma.io, with Firefox 66. There is also a large number of "Recalculate Style", "CC Graph Reduction" and "Cycle Collection" lines when running the Performance analysis.
