### ISSUE TITLE
title design variation

### ISSUE THREAD

**Issue by sottar** [jgthms/bulma#105]
I'm trying to make title design variation.
Adding contents .is-bar-left and .is-bar-bottom elements to the titles.sass

looks like these
<img width="500" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8223003/12934699/dbcaaeb6-cfd3-11e5-9162-d09bd469fdfe.png">

Regards.

**Comment by jgthms** [comment]
Hi @sottar 

Thanks for contributing but these types of classes are too specific. I don't want to bloat the code with opinionated styles.
