### ISSUE TITLE
is-loading doesn't work on input type="submit"

### ISSUE THREAD

**Issue by pinzonjulian** [jgthms/bulma#1053]
### Overview of the problem
`is-loading` doesn't work on form input submit buttons

This is about the Bulma **Docs**

### Description

CSS spec doesn't allow `:after` elements on input tags such as a `input[type="button"]`. Bulma could add a disclaimer explaining this behaviour in the button docs and an alternative solution could be added such as a  addon to the button with the preloader.

**Comment by VizuaaLOG** [comment]
Out of curiosity is there any reason you are using an input over just using buttons?

**Comment by pinzonjulian** [comment]
I'm using Bulma with Rails and the standard for submitting a form in rails is using the input type "submit"

**Comment by VizuaaLOG** [comment]
@pinzonjulian Ah okay. Not familiar with rails, as never used it but I would probably not stick to that standard if I was using it ;).
