### ISSUE TITLE
Add sticky navbar modifiers

### ISSUE THREAD

**Issue by jgerbes** [jgthms/bulma#1055]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Some work was done to add a sticky navbar modifier to the now deprecated `.nav` component - see #367. 

There were some disagreements around sticky behaviour on mobile devices. The new  `.navbar` component was released and #367 was closed.

Could you please re-visit this request and look into adding this functionality to the new component?

As a suggestion to solve the dispute about sticky/non-stick on mobile, you could give multiple sticky modifier options that can be added to the `.navbar`:

- `.is-sticky` - sticky at all sizes.
- `.is-sticky-mobile` - sticky on mobile only.
- `.is-sticky-touch` - sticky on mobile and tablet.
- `.is-sticky-tablet` - sticky on tablet and larger.
- `.is-sticky-desktop` - sticky on desktop and larger.
- `.is-sticky-widescreen` - sticky on widescreen and larger.
- `.is-sticky-fullhd` - sticky on fullhd only.

**Comment by jgthms** [comment]
#46
