### ISSUE TITLE
Font-weight changes for elements nested in title

### ISSUE THREAD

**Issue by princjef** [jgthms/bulma#106]
When adding a `.title` to a page, the font-weight is set to `300`. However, if you add a generic element (such as a `span`) inside of the `.title`, the font-weight changes to `normal`, making the text look different. This seems like undesirable behavior.

**Renders with `font-weight: 300`**
```HTML
<h4 class="title is-4">Weight is 300</h4>
```

**Renders with `font-weight: normal`**
```HTML
<h4 class="title is-4">
  <span>Weight is</span>
  <span>normal</span>
</h4>
```

**Comment by jgthms** [comment]
Ah yes, this comes from the `reset.sass` where all elements (including spans) are reset to `400`.

I should put these title weights in variables as well.
