### ISSUE TITLE
Section spacing

### ISSUE THREAD

**Issue by stibay** [jgthms/bulma#1060]
This is about the Bulma **Docs**
From the [section documentation](http://bulma.io/documentation/layout/section/):
`You can use the modifiers is-medium and is-large to change the spacing.`

I am pretty new to bulma but I asume this is classes you can add to change the spacing between the sections?

Nothing happends if I add that class to a section and from all I can see when you f.ex add it to the content section it sets a different font-size. `font-size: 1.25rem;`

**Comment by jgthms** [comment]
It changes the padding of the section. Example: https://codepen.io/jgthms/pen/vJZoGP

More info on modifiers: http://bulma.io/documentation/modifiers/syntax/
