### ISSUE TITLE
 Use of the word touch to indicate styles which are phone/tablet is a little funky.

### ISSUE THREAD

**Issue by ctolkien** [jgthms/bulma#1061]
### Overview of the problem

 This is about the Bulma **CSS framework** 

I'm using Bulma **version** 0.5.1

### Description

Use of the word *touch* to indicate styles which are phone/tablet is a little funky. A lot of devices these days (like the one I'm on now) are touch capable which are not phone/tablets.

Excepting Mac hardware, almost all other mid/high-end laptops these days are touch capable. It seems inevitable that eventually, everything will be touch.

Changing this is obviously a big breaking change - but easier to do now before touch proliferates further.

With that said, I don't really have a better term to use as its replacement at this point in time.

**Comment by jgthms** [comment]
That's a fair criticism. Naming things is hard! `mobile-and-tablet` is the most accurate but quite long. And as you said, it would be a big breaking change.

I'm open to suggestions though.

**Comment by jpsc** [comment]
I think if its well documented the name does not really bother.
