### ISSUE TITLE
family-primary customisation in create-react-app not working

### ISSUE THREAD

**Issue by kaihendry** [jgthms/bulma#1063]
### Overview of the problem

This is about the Bulma **Docs** 
 I'm using Bulma **version** [0.5.1] 
This is a **Sass** issue: I'm using "node-sass-chokidar": "0.0.3"

### Description

When trying to combine https://github.com/facebookincubator/create-react-app with http://bulma.io/documentation/overview/customize/ I am stuck with not being able to override the font family.

### Steps to Reproduce

1. git clone git@github.com:kaihendry/bulma-react-bug.git
2. cd bulma-react-bug/
3. npm i
4. npm run build-css
5. npm run start

### Expected behavior

[$family-primary](https://github.com/kaihendry/bulma-react-bug/blob/d8ecc1f92a70a19cb1fa0b19b2fab3fd8d89a6dd/src/App.sass#L20) to be changed like that in http://bulma.io/documentation/overview/customize/

### Actual behavior

Only font color changed.

**Comment by jgthms** [comment]
Try removing `!default'

**Comment by kaihendry** [comment]
No dice. https://github.com/kaihendry/bulma-react-bug/commit/937e5c53d659609244e5fe69e51cf74b693f37b1

**Comment by jgthms** [comment]
Oh I know why. There was a name change. Sorry about that. Will fix asap.

**Comment by kaihendry** [comment]
Don't you need to do a release now, else how do I get to use the fix? Sorry, bit of a JS newb here.
