### ISSUE TITLE
is-loading doesn't work on pagination-previous / pagination-next

### ISSUE THREAD

**Issue by drake7707** [jgthms/bulma#1069]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

is-loading doesn't work on pagination-previous / pagination-next, even though they look like buttons. I'd like to put a loading in there while the next page is fetched with ajax. Adding the button class makes it work but overrides the text color

### Steps to Reproduce
Create pagination and add is-loading to the pagination-previous / pagination-next "buttons"

### Expected behavior

The is-loading works in the same way as with buttons

### Actual behavior

No loading is shown

**Comment by jpsc** [comment]
Wouldn't this mean that all links styled as `button` should support icons inside?

**Comment by drake7707** [comment]
If I style the pagination with the `.button` class it works fine but it loses the foreground color so it looks different from the other pagination elements.
