### ISSUE TITLE
Tabs component alignment and small screens

### ISSUE THREAD

**Issue by thebigmunch** [jgthms/bulma#107]
Center aligned tabs can end up with their leftmost item cut off. Right aligned tabs get no scrollbar.

![2016-02-27_16-54-00](https://cloud.githubusercontent.com/assets/118418/13375644/4aeb66d0-dd73-11e5-844d-1ed8e0080533.png)

**Comment by jgthms** [comment]
Mmh, that's an interesting one. Let me check that. Thanks for reporting.
