### ISSUE TITLE
Help needed : scriollable table

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#1082]
Hi,

I'm trying to make a table with fixed header and a scrollable body using this code:
```
&.is-scrollable
    tbody
      overflow-y: scroll
      width: 100%
      position: absolute
      background-color: $white
```

This require to add the height attribute to the body tag in order to apply scroll.

Unfortunately I identified 2 issues:
1. I have to put the body background color in my code because it lost the bulma one when applying the class is-scrollable

2. The body or header cells mess up

See demo here: https://codepen.io/wikiki/pen/JyMYLd

Can you please help me to implement this functionality ?

Regards

**Comment by jgthms** [comment]
Using `overflow` and `position` on any table element is not recommend. You're better off having 2 tables, and a a div to scroll.

```
table-head
div
  table-content
```
