### ISSUE TITLE
How can I get Bulma 0.5.2?

### ISSUE THREAD

**Issue by aarohmankad** [jgthms/bulma#1086]
I need to change the gaps between columns in my application. I see it's labelled as experimental for 0.5.2 but I don't see it on [cdnjs](https://cdnjs.com/libraries/bulma) and it's not installed through npm/yarn either.

How can I get 0.5.2 into my app?

**Comment by jgthms** [comment]
You can try pulling `master` for now. Next release should be this weekend.
