### ISSUE TITLE
Colums has no gap

### ISSUE THREAD

**Issue by denizgedik** [jgthms/bulma#1088]
I am trying to create columns but everytime i create them they just doesn't have any gap. I never modified anything and I gave them a class with only added colors. Also the column at the end always has width bigger than all of them. Also I can't change the size no matter what I do. Sorry for my english.

**Comment by jgthms** [comment]
What's your markup? Provide a Codepen.

**Comment by denizgedik** [comment]
nvm, now i use style="margin-left:10px;" and style="height:48px;" so it works for me. also i wrongly mentioned that "Also the column at the end always has width bigger than all of them." but that was false. I was going to say height not width.

**Comment by denizgedik** [comment]
<div class="columns">
  <div class="column notification is-primary" style="margin-right: 10px;">
    First column
  </div>
  <div class="column notification is-primary" style="height:48px;">
    Second column
    </div></div>
            <div class="columns">
  <div class="column notification is-primary" style="margin-right: 10px; height:50px;">
    Third column
  </div>
  <div class="column notification is-primary" style="height:50px;">
    Fourth column
  </div>
</div> 

so i've written this code to fix my problem and not it looks like this, also this is a column in a tile:
http://imgur.com/a/pRYE0
before it was like this:
http://imgur.com/a/KMtE0

and this is what i was talking about first, this is without any tiles or containers or anything. 
code:
<div class="columns">
  <div class="column notification is-danger">
   a
  </div>
  <div class="column notification is-warning">
    b
  </div>
  <div class="column notification is-primary">
    c
  </div>
</div>
not fixed:
http://imgur.com/a/5tUo0
fixed: http://imgur.com/a/M3YGk

**Comment by denizgedik** [comment]
http://www.writeurl.com/text/ulrvl5e1hoh1kj2r9b2w/22xlfci1bwx52bt057z4
