### ISSUE TITLE
Navbar size problems

### ISSUE THREAD

**Issue by xlcrr** [jgthms/bulma#1089]
`<nav class="navbar" style="height: 100px;">` // looks fine, centers nicely

`<div class="navbar-burger burger" style="height: 100px;">` // when collapsed, looks fine, brand + burger button centers nicely

However when you expand the navbar-burger when the navbar is not default, eg height: 100px, it introduces errors
1. the Narbar-burger is made transparent. This can be overcome with style background-color=color;
2. Any text below the 'transparent' navbar-burger is overlaid and the user cannot select things where there is an overlap

Also, when I expand the navbar-burger, it pushes code below it out of the way. Is this expected?

Would love a fix on this as the default navbar is way too small for my pref

Thanks!

**Comment by jgthms** [comment]
Can you post a Codepen?

**Comment by delphinas** [comment]
I change navbar size through the variables in my custom.sass file, for example, I change the $navbar-height and it works fine.

**Comment by xlcrr** [comment]
@jgthms Codepen is buggy. For example, style="height: 100px;" only gets applied to navbar after I add 
`
   <a class="navbar-item" style="margin-left: 3em;">
     <h4 class="title is-4">My App</h4>
   </a>
`
to navbar brand 
https://codepen.io/xlcrr/pen/GvGKEx

**Comment by jgthms** [comment]
The `$navbar-height` is a variable that you can customize directly if you build from the Sass source files.
