### ISSUE TITLE
Navbar Class `is-transparent` Not Working for Mobile

### ISSUE THREAD

**Issue by stephendolan** [jgthms/bulma#1094]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.1]
My **browser** is: Chrome 59.0.3071.115
I am sure this issue is **not a duplicate**

### Description

Given the navbar element `<nav class="navbar is-transparent">`, the hover effects are turned off for desktop screens and larger, but is left on for mobile screen sizes (tablet and phone).

### Steps to Reproduce

1. Go to the official documentation [here](http://bulma.io/documentation/components/navbar/#transparent-navbar)
2. Make sure you are on the "Transparent Navbar" section
3. Adjust the screen size using dev tools or window resizing.
4. Note that when the screen is desktop size or larger, there is no hover behavior.
5. Note that when the screen is tablet size or smaller, there is still hover behavior.

### Expected behavior

`is-transparent` should function the same on all screen sizes.

### Actual behavior

`is-transparent` functions differently on desktop and larger screens than on tablet and smaller screens.

**Comment by jgthms** [comment]
The transparent modifier is for navbar items to not have any background when active. On mobile, that background is required to differentiate them.
