### ISSUE TITLE
Modifiers: is-fixed-on-top, is-fixed-on-bottom, is-is-fixed-on-left, is-is-fixed-on-tight

### ISSUE THREAD

**Issue by skycult** [jgthms/bulma#1096]
### Question / Help wanted

Hi,
how I can add some modifier to an element (like container, navbar, hero, ...) to fix it on top, bottom, left or right? I need to create a layout with a navbar, a tabbar and a sidebar, with scrollable content, like an Android app.
Thank you in advance.
Beste regards

**Comment by jgthms** [comment]
Check out `absolute` and `fixed` positioning: http://marksheet.io/css-position.html
