### ISSUE TITLE
Icon colors

### ISSUE THREAD

**Issue by gyzerok** [jgthms/bulma#1097]
Hi there!

Would it make a good addition to Bulma to be able to use modifiers like `is-success`, `is-danger` and so on for icons?

In my case I do use font-awesome icons to represent statuses of entities on my page. To make it more clear I'd like to color them: green if status is OK and red if status is ERROR. So I was thinking that it could work nicely with default Bulma colors which are used for other places like buttons and messages.

For example:

```html
<span class="icon is-medium is-success">
  <i class="fa fa-check" />
</span>
```

**Comment by jgthms** [comment]
Just use `has-text-success`.

**Comment by gyzerok** [comment]
Thanks!
