### ISSUE TITLE
card-header or card-header-title is not being centered with has-text-centered

### ISSUE THREAD

**Issue by tanmay-das** [jgthms/bulma#1101]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.1]
My **browser** is: Mozilla Firefox 55.0.2

### Description

The typography helper class has-text-centered does not affect the card header or the card header title

### Steps to Reproduce

```
<header class="card-header has-text-centered">
          <p class="card-header-title">
               This text is always left-aligned
          </p>
</header>
```

### Expected behavior

Text inside card-header-title to be centered

### Actual behavior

Text inside card-header-title is not centered

**Comment by smusman437** [comment]
text inside card-header-tile is now being centered 
 <div className="card-header  is-4">
              <p className="card-header-title is-centered"> User Detail</p>
            </div>
