### ISSUE TITLE
pagination is-right shows next/prev links on the left in tab view

### ISSUE THREAD

**Issue by connectkushal** [jgthms/bulma#1106]
Expected behaviour for `pagination is-right` is that the next/previous links stay on the right when viewed on tab, but they move to the left.

https://codepen.io/connectkushal/pen/prKNGo?editors=1010

Using Bulma **5.1**
Checked it on Chrome(v60) and Mozilla(v55)

**Comment by jgthms** [comment]
For spacing reasons, the alignment is only possible on wider screens.
