### ISSUE TITLE
Receiving support?

### ISSUE THREAD

**Issue by Francolpm** [jgthms/bulma#111]
Hi there!
This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because I want to give some of money to bulma, but there is no donate button o something like that.
I love the name and the color of the logo. (Its reminds me to DBZ)
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like Bulma. 

Thanks for this work!

**Comment by jgthms** [comment]
A donate button is in the footer. 😉
