### ISSUE TITLE
bulma.io: Partners Section breaking

### ISSUE THREAD

**Issue by sternmd** [jgthms/bulma#1112]
On the bulma.io website, the blue "Bulma Partners: Check out their products!" section above the footer breaks if screen size is between 768px and 1068px.

![screen shot 2017-08-24 at 3 11 41 pm](https://user-images.githubusercontent.com/16902621/29686458-a0675f2a-88de-11e7-9a33-4bf676cfc394.png)

**Comment by jgthms** [comment]
https://github.com/jgthms/bulma/issues/973 😉
