### ISSUE TITLE
Component Media Object with image is16by9 => not appearing

### ISSUE THREAD

**Issue by rdehouss** [jgthms/bulma#1114]
Bug about Bulma

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.1]
My **browser** is: Firefox 56
I am pretty sure this issue is **not a duplicate** (searched with 16by9 keyword)

### Steps to Reproduce
Checkout this https://jsfiddle.net/bthzssmq/

### Expected behavior

The image appears correctly

### Actual behavior

The 16by9 image does not appear

**Comment by ColinFrick** [comment]
Either set the size on the parent container or on the .image element.
```html
<figure class="media-left" style="width: 160px;">
or
<p class="image is-16by9" style="width: 160px;">
```

In the example for this, the table column have a explicit width of 320px:
```css
#images tr td:nth-child(2) {
  width: 320px;
}
```
see https://github.com/jgthms/bulma/blob/master/docs/css/bulma-docs.css#L10357

**Comment by rdehouss** [comment]
Ok, good point!
