### ISSUE TITLE
How to modify Menu and main containers background color?

### ISSUE THREAD

**Issue by Bondifrench** [jgthms/bulma#1115]
This is about Bulma

Question and need of help in order to modify some background colors

### Overview of the problem

Bulma version 0.5.0
My **browser** is: Chrome 60.0

I am sure this issue is **not a duplicate**

### Description

It doesn't seem to me that currently we can modify the background color of the side menu or from the main container to emphasize tiles or cards.

### Steps to Reproduce
I am trying to do a variation of this design:
https://dribbble.com/shots/1315388-Dashboard-Web-App-Product-UI-Design-Job-Summary/attachments/184703

so side menu has a background color of #31475A and the main container has a slightly greyish background color of #f0f2f1

What is the best way to achieve that design with Bulma?
or should new variables be implemented?

**Comment by Wikiki** [comment]
Hi,

background color for menu is not customizable currently.
To change it I've added this code:

```
.menu
  &.is-invert
    background-color: $menu-invert-background
    .menu-label
      color: findColorInvert( $menu-invert-background )
    .menu-list
      a
        color: findColorInvert( $menu-invert-background )
        &:hover
          color: $menu-invert-background
    .menu-item
      color: findColorInvert( $menu-invert-background )
```

Where $menu-invert-background is the variable for the wanted background color.

I hope this will help you.

**Comment by Bondifrench** [comment]
Thanks for your help, that's helpful but I think this looks like a temporary solution.
I believe, having a feature/variable to be able to modify the `background-color` of a `menu` or from a `section` or `container` would be useful.
For instance, given a section containing tiles or cards, which have a white background-color, giving a slightly darker background-color to the encompassing container/section will help put emphasis on the tiles, so there is an accentuated contrast like in the example I showed above.

**Comment by Wikiki** [comment]
You're right it's a temporary solution for my need.

I agree it should be managed by Bulma core.

**Comment by jgthms** [comment]
`section` and `container` are layout elements. Their main purpose is spacing, not styling. Having a background color would be confusing.

As for the menu, since there's no padding, having a background color doesn't work either.

Simply overriding `.menu` is what's expected here.
