### ISSUE TITLE
Extensions: Fable.Elmish.Bulma

### ISSUE THREAD

**Issue by MangelMaxime** [jgthms/bulma#1116]
Hello, 
as you accepted [bulma.io-axure](github.com/Code-Mine-Development/Bulma.io-axure) on the extensions pages.

I am wondering if you would accept [Fable.Elmish.Bulma](https://mangelmaxime.github.io/Fable.Elmish.Bulma/#home) project. It's a library for [Fable](http://fable.io) (a F# to JavaScript transpiler) wrapping all Bulma components into [Elmish](https://fable-elmish.github.io/elmish/) (Elm-like abstractions for F# apps).

For example:

```fs
Button.button [ ] [ str "Button" ]
```

is equivalent to something like

```fs
div [ ClassName "button" ]
    [ str "Button" ]
```

So we are winning intellisense, type safety, etc.

**Comment by jgthms** [comment]
Just add it to the README.
