### ISSUE TITLE
Font Awesome icon(s) doesn't have enough space in a button

### ISSUE THREAD

**Issue by csk157** [jgthms/bulma#112]
![screen shot 2016-03-06 at 21 44 44](https://cloud.githubusercontent.com/assets/2392131/13556914/57689f0e-e3e5-11e5-8575-91a25fcfb889.png)

```html
<a class="button">
  <i class="fa fa-object-ungroup"></i> fa-object-ungroup
</a>
```

**Comment by ncksllvn** [comment]
I agree that this seems off but the following HTML will give you the expected result:

    <a class="button">
        <span class="icon is-small">
            <i class="fa fa-object-ungroup"></i>
        </span> 
        fa-object-ungroup
    </a>

**Comment by csk157** [comment]
Thanks! It does look better :smile:

**Comment by jgthms** [comment]
This is tricky one. Because most icons will look good:

![screen shot 2016-03-12 at 1 27 08 pm](https://cloud.githubusercontent.com/assets/1254808/13723218/36877aa6-e856-11e5-9f07-65603436e41d.png)

But @ncksllvn has provided a very good solution.

**Comment by mnpenner** [comment]
This is still rendering improperly for me...

![image](https://user-images.githubusercontent.com/1112998/29148078-0e3d4e6c-7d20-11e7-9d61-ae9b98898705.png)

```html
<button class="button"><span class="icon"><i class="fa fa-plus"></i></span><!-- react-text: 73 --> Add Instruction<!-- /react-text --></button>
```

Even if I make the button small (`<span class="icon is-small">`):

![image](https://user-images.githubusercontent.com/1112998/29148072-047d44e0-7d20-11e7-8fae-403aabceec8d.png)

**Comment by thomhickey** [comment]
button > svg {
        margin-right: 8px;
    }

**Comment by mclaudt** [comment]
@mnpenner, solution is to wrap your anonymous text block in span:
```html
<button class="button">
   <span class="icon"><i class="fa fa-plus"></i></span>
   <span>Add Instruction</span>
</button>

**Comment by williamabbott** [comment]
@mclaudt not working for me
