### ISSUE TITLE
How to get cards with same height in columns ?

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#1121]
Hi,

I have columns with cards in them and I'm trying to get those cards having the same height (the full-height of the column actually).

Do you now how to handle that ? Currently the card's height is based on its content.

Regards,

**Comment by matteomanf** [comment]
I had the same exact problem yesterday, if you move to tiles they span the whole height while maintaining the same width possibilities.

Of course you could probably set height to 100% on the cards, but I haven't tested it.

**Comment by Wikiki** [comment]
Thanks for the hint.

Using tile make card fullheight but unfortunately it's missing some code to card component to always keep footer at bottom.
I had to add the following code to get it work:

```
.card
  display: flex
  flex-direction: column

.card-footer
  margin-top: auto
```

**Comment by matteomanf** [comment]
You could assign a .card class to the .tile.is-child without problems inheriting all the properties of the card component.

**Comment by Wikiki** [comment]
You're right its fixing the width: 100% and flex display

but I still need the following code for card-footer
```
.card
  display: flex
  flex-direction: column

.card-footer
  margin-top: auto
```

**Comment by matteomanf** [comment]
Let me get to a computer, 30 minutes or so and I’ll try it! From the phone it’s complicated writing the proposed solution in full.

**Comment by matteomanf** [comment]
Nevermind, I checked and I see the problem you have. You can just do:

```
.tile.is-anchestor
  .tile
    .tile.is-child.card
      .card-header
      .card-content
      .card-footer
```

You would have to handle the footer not sticking to the bottom, but some custom code should do...

**Comment by Wikiki** [comment]
I don't see any difference with the .tile added.

@jgthms : Is it possible to add the following part of code on card component to set the footer always on bottom event hen using card in tile ?
```
.card
  display: flex
  flex-direction: column

.card-footer
  margin-top: auto
```

**Comment by matteomanf** [comment]
The second .tile is there just to follow Bulma's website examples. Adding the .card to the .tile allows the tiles to be the same height.

**Comment by Wikiki** [comment]
Thanks for the explanation

**Comment by jgthms** [comment]
The flex-direction column can be tricky in some contexts. I'd rather not add if it's not necessary.

**Comment by nedjo** [comment]
For the original question:

```scss
.column
  .card
    height: 100%
```
Or to allow an optional `is-fullheight` modifier on cards:

```scss
.card
  &.is-fullheight
    height: 100%
```

**Comment by ctolkien** [comment]
The above will make the card full height, but the card footer will not be stuck to the bottom.

**Comment by stuartcusackie** [comment]
I found using tiles instead of columns made my cards equal heights automatically (bulma 0.7.2)

```
<div class="tile is-ancestor">
     <div class="tile is-parent">
          <div class="tile is-child card">
          #Card Stuff
          </div>
     </div>
     <div class="tile is-parent">
          <div class="tile is-child card">
           #Card Stuff
          </div>
     </div>
</div>
```

The only issue was the card-footer, but switching to display flex with the following setup fixed that issue:

```
.tile.is-child.card {
    flex-direction: column;
    display: flex;
    justify-content: space-between;
}
```

**Comment by J-tt** [comment]
I'd recommend doing this with the above example

```css
.tile.is-child.card {
     .card-footer {
         margin-top: auto;
    }
    display: flex;
    flex-direction: column;
} 
```

Otherwise you'll get some weird spacing around the body of the card.

**Comment by noraj** [comment]
duplicate of #218
