### ISSUE TITLE
level-right does not work in the menu

### ISSUE THREAD

**Issue by bingo-ingo** [jgthms/bulma#1122]
I am using the newest Version of Bulma 0.5.1. The example has a menu "More" with a list-entry "Extensions" with a icon. The icon is not on the right side of the menu (like it should be because of level-right) like the Bulma Website. If i use the bulma-docs.css it works fine. But i do not find any differences.

**Comment by suchmaske** [comment]
It would be helpful if you could post a code snippet.

**Comment by jgthms** [comment]
You need `level is-mobile` and [`#moreDropdown`](https://github.com/jgthms/bulma/blob/master/docs/_sass/header.sass#L26) has some custom styles.
