### ISSUE TITLE
Fun to use, but I'd like to add a smaller size as the lowest viewport size.

### ISSUE THREAD

**Issue by roni-estein** [jgthms/bulma#1127]
Are there any plans to put the breakpoints and mixins in 1 accessable place and use variables so to add a smaller breakpoint you would just add it to an array, instead of modifying much of the source?

Thanks.
-Roni

**Comment by jgthms** [comment]
It's a bit tricky since mixins are named like the variables. Each breakpoint would need its own mixin. And the core components would have more breakpoint logic.

I think it would be too complicated to have the number of breakpoints customisable. You can still define the breakpoint values.
