### ISSUE TITLE
Dropdown inside Message/Notification have underlined items

### ISSUE THREAD

**Issue by rafaelpimpa** [jgthms/bulma#1130]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.5.1

I am sure this issue is **not a duplicate**

### Description

Dropdown inside Message/Notification have underlined items.

### Steps to Reproduce

https://codepen.io/anon/pen/KvrLGX

### Expected behavior

Links to not have underline inside dropdown.

### Actual behavior

Links have underline.

**Comment by msforbes09** [comment]
Also <table> -> <a> tags inside message is underlining
