### ISSUE TITLE
Add modifier '.is-right' to the 'navbar-dropdown' class

### ISSUE THREAD

**Issue by Vortelf** [jgthms/bulma#1131]
This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.1] 

### Description

> bulma/sass/components/navbar.sass **@** 109 

Add modifier '.is-right' to the 'navbar-dropdown' class identical to the '.dropdown' modifier
```sass
&.is-right
  left: auto;
  right: 0;
```

I did it myself but probably someone else would like to use it at somepoint.

**Comment by njgingrich** [comment]
I was looking at this to see if it still needed to be completed and it appears it's implemented now & referenced in the docs, fixed in e06a098d.

**Comment by Vortelf** [comment]
Few days back I updated to 0.6.0 and it's working as intended. Issue may be closed.
