### ISSUE TITLE
Navbar not resizing on touch

### ISSUE THREAD

**Issue by DevoidCoding** [jgthms/bulma#1132]
Problem is about Bulma.

### Overview of the problem

**CSS framework**
I'm using Bulma **version** [0.5.1]
My **browser** is: Chrome 60.0.3112.113
I am sure this issue is **not a duplicate**?

### Description

I got a problem using the Navbar componenets with the last version. Everything was fine and now it doesn't resize on touch screen (http://i.imgur.com/B6PYkR7.png) expected behavior : (http://i.imgur.com/aSBVYPn.png)

### Steps to Reproduce

Just used the first example in the navbar doc
```html
<nav class="navbar ">
    <div class="navbar-brand">
        ...
    </div>

    <div id="navMenubd-example" class="navbar-menu">
        <div class="navbar-start">
            ...
        </div>

        <div class="navbar-end">
            ...
        </div>
    </div>
</nav>
```

### Expected behavior

This : http://i.imgur.com/aSBVYPn.png

### Actual behavior

This : http://i.imgur.com/B6PYkR7.png

EDIT : 
Was missing meta
``` html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Everuthing is okay...

**Comment by proehlen** [comment]
@DevoidCoding

> EDIT :
Was missing meta

Oh, wow.  Was going nuts with this.  Thank you for posting the solution.
