### ISSUE TITLE
Have typography scale down for mobile or be able to not include in sass

### ISSUE THREAD

**Issue by packytagliaferro** [jgthms/bulma#1133]
Bulma - Question

### Overview of the problem

This is a **Sass** issue: I'm using version [0.5.1] 

### Description

Basically I am trying to figure out the typography part. I like all my fonts to be bigger on desktop and scale down for mobile. I know there are helpers like `is-size-4` I can add to the font class but then it doesn't scale down to a smaller font on mobile. 

I guess my only options are, if possible, not include the fonts from Bulma Sass so I dont have to over write everything or maybe you guys make the standard font size for mobile and if you add something like `is-size-4` to a font class that only applies to desktop or something.

**Comment by jgthms** [comment]
The majority of elements are using `rem`. You could try out setting a different font size on `HTML` for larger viewports.
