### ISSUE TITLE
Question: container class does not center like in example?

### ISSUE THREAD

**Issue by sebstr1** [jgthms/bulma#1136]
Im trying to reproduce first example for the .container. I copy paste the code and it does center but not as much as the example output on bulma page. How do I fix that?

I am sorry but Im learning and I do not understand why It does not center as much as the example..

Thanks for your time!

**Comment by jgthms** [comment]
What's your code?

**Comment by sebstr1** [comment]
I'm just using a single html file to test things out (great work with bulma :) ) 

First time writing on github so failing to get the entire code in this comment so I used a pastebin aswell

[https://pastebin.com/fZiBPDeS](url)

`<!DOCTYPE html>

<html lang=en>

<head>
	
	
	<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.css"

</head>


<body>
	
		<div class="container">
			<div class="notification">
				This container is <strong>centered</strong> on desktop.
			</div>
		</div>
	
</body>



</html>`

**Comment by jgthms** [comment]
Your markup is wrong. The link should be:

```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.css">
```

You should read http://marksheet.io/
