### ISSUE TITLE
Columns stacked on tablet by default when they should be columns 

### ISSUE THREAD

**Issue by packytagliaferro** [jgthms/bulma#1138]
Bulma - Bug

### Overview of the problem

This is a Sass and CSS issue: I'm using version 0.5.1 

### Description

In the docs it states "by default, columns are only activated from tablet onwards." currently on the Bulma site and any site I have used it on, columns are stacked on tablet when they should be columns.

### Steps to Reproduce

1.) add 
```
<div class="columns">
  <div class="column">
    First column
  </div>
  <div class="column">
    Second column
  </div>
  <div class="column">
    Third column
  </div>
  <div class="column">
    Fourth column
  </div>
</div>
```

2.) test in chrome on ipad

### Expected behavior

On iPad have columns not stacked divs

### Actual behavior

On iPad they are stacked

**Comment by jgthms** [comment]
In portrait or landscape?

**Comment by packytagliaferro** [comment]
Portrait 
<img width="477" alt="screen shot 2017-08-31 at 2 44 40 pm" src="https://user-images.githubusercontent.com/1316850/29946677-16a4fe3c-8e5b-11e7-91ab-a3208ed7f49f.png">

**Comment by jgthms** [comment]
Yes that's expected. `+tablet` is for 769px and up.

**Comment by olance** [comment]
I hope you won't mind my digging up of this issue; puzzled by the behaviour as well I stumbled upon that issue looking for clues on Google.

If you really need your columns not to stack up below `769px`, you can add the `is-flex-mobile` class to your `columns` container.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/314079/59148040-6bd27380-8a03-11e9-9aae-e3eadd96f507.png">

**Comment by alessandropolverino** [comment]
you can download the bulma css with tablet breakpoint set to 768 (ipad friendly) to https://github.com/alessandropolverino/bulma-tablet-columns/tree/master
