### ISSUE TITLE
Footer Example 'is-centered' class should be 'is-text-centered'

### ISSUE THREAD

**Issue by AntonRand** [jgthms/bulma#114]
The example code for footer looks wrong to me: http://bulma.io/documentation/layout/footer/

The class should be 'is-text-centered' and not 'is-centered'

**Comment by madjake45** [comment]
This is due to the fact that an older version of bulma used is-centered and
as such the docs are out of date

On Mon, Mar 7, 2016 at 4:33 PM, Anton Rand <notifications@github.com> wrote:

> The example code for footer looks wrong to me:
> http://bulma.io/documentation/layout/footer/
>
> The class should be 'is-text-centered' and not 'is-centered'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgthms/bulma/issues/114>.
>



-- 
-------
Jake

**Comment by AntonRand** [comment]
Thanks Jake,

I will close the issue and raise over there.
