### ISSUE TITLE
Notification close button looks broken on mobile devices(6s plus, 10.3.2, safari)

### ISSUE THREAD

**Issue by kirqe** [jgthms/bulma#1141]
This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.5.1
My **browser** is: ios 10.3.2 default safari browser
I am sure this issue is **not a duplicate**?

### Description

Look at the screenshots. The delete button looks broken.
**It works normal in desktop version.**

**code**

```ruby
<% flash.each do |k, v| %>
  <% if k == "notice" || "info" %>
    <%= content_tag :div, class: "notification is-info" do %>
      <%= button_tag "", class: "delete" %>
      <%= v %>
    <% end %>
  <% elsif k == "error" %>
    <%= content_tag :div, class: "notification is-danger" do %>
      <%= button_tag "", class: "delete" %>
      <%= v %>
    <% end %>
  <% end %>
<% end %>

```

**screenshots**

portrait

![img_1731](https://user-images.githubusercontent.com/5272402/29982550-e2b98812-8f5a-11e7-8eb7-5094cf321128.PNG)

landscape

![img_1732](https://user-images.githubusercontent.com/5272402/29982549-e2b8ef06-8f5a-11e7-9a07-509e19efe096.PNG)

**Comment by jgthms** [comment]
Duplicate I believe.
