### ISSUE TITLE
Container do not center on Chrome mobile version + padding to the right

### ISSUE THREAD

**Issue by LicorneArcEnCiel** [jgthms/bulma#1149]
### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** 0.5.1
My **browser** is: Chrome v60.0.3112.107 on Android 7.1

### Description

On mobile version, the container in both my menu and content adds a strange padding to the right of the screen. The content is no longer centered and the navbar don't go through all screen.
Does show on the Chrome mobile version, but not on the Safari one.

### Steps to Reproduce

1. Have some content wrap into a container div
2. Open on mobile Chrome browser

### Expected behavior
As show on the screen shot : content centered, navbar going on all screen.
(The container are removed here)
![screenshot_20170903-143320](https://user-images.githubusercontent.com/15120579/30002974-4bd23404-90b7-11e7-84b9-d6c6f0d77cc8.png)

### Actual behavior
As shown on the screenshot: content is not center (due to the padding on the right)
![screenshot_20170903-141231](https://user-images.githubusercontent.com/15120579/30002976-4ff78de0-90b7-11e7-841e-e81ea378de8c.png)

**Comment by jgthms** [comment]
You probably need a `<section class="section">`.
