### ISSUE TITLE
Text alignment for table head / foot

### ISSUE THREAD

**Issue by cbeulke** [jgthms/bulma#115]
It would be great if we could align the text in the `thead` and `tfoot` sections of a `table`, e.g. as `.is-text-right` for currency or other numeric values.

**Comment by jgthms** [comment]
You should be able to use `has-text-right` on the cell.

**Comment by dobromir-bogatev** [comment]
Well it doesnt work. There is the more concrete condition in bulma .table th which overwrites almost anything.

**Comment by DaxChen** [comment]
using `.has-text-right` on `th` or `td` works for me

**Comment by seigel** [comment]
using ```.is-right`` now seems to be the thing
