### ISSUE TITLE
A bug: text on button invisible in active table cell

### ISSUE THREAD

**Issue by UnrulyNatives** [jgthms/bulma#1150]
In an active row of table (class `is-active`, greenish color) the text inside any button with no color declaration becomes invisible. The problem disappears if the text color is declared with `has-text-danger` or similar class.

Component: table (http://bulma.io/documentation/elements/table/)

Screenshot: https://www.dropbox.com/s/yjw3hdxcmipr0nk/screenshot-dev-2017-09-04-06-00-48.png?dl=0

Thx

**Comment by hunzaboy** [comment]
Temporarily, you can use <button> instead of <a> if the elements are not anchors.

**Comment by bodograumann** [comment]
I encountered the same issue. @hunzaboy, your suggestion is not visible, could you try using code markup?
