### ISSUE TITLE
dropdown direction

### ISSUE THREAD

**Issue by acornejo** [jgthms/bulma#1151]
### Dropdown has no configurable direciton (always down)

This is about the Bulma **CSS framework**

If the dropdown trigger button is already close to the bottom of the screen, one would expect the dropdown to open upwards. I.e. the dropdown directional should be configurable, even better if it is automatically chose based on available screen space with respect to the dropdown trigger button.

Screenshot with problem:

![screenshot 2017-09-03 at 10 52 16 pm](https://user-images.githubusercontent.com/83786/30013351-dd51175e-90fa-11e7-982b-9f195acb8938.png)

The screenshot was taken from the bulma documentation place. The dropdown content is truncated and not usable.

**Comment by hunzaboy** [comment]
Bulma.io doesn't come with JS. You need to implement the js according to your needs.

**Comment by jgthms** [comment]
The dropdown only goes down. You can scroll however.
