### ISSUE TITLE
Modal from inside article inherits background

### ISSUE THREAD

**Issue by sausin** [jgthms/bulma#1154]
## Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.1]
My **browser** is: Chromium

### Description

If there is a modal component inside (modal-card in my case) then the background properties are inherited.

This causes text to appear wrongly on a white background of the modal.

### Steps to Reproduce

1. Create an element like:
```html
<article class="notification is-dark">
..
    <div class="modal">
     <div class="modal-background"></div>
     <div class="modal-card">
   ....
   </div>
...
</article>
```

2. Inside the `modal-card-body` have some `label` text below a form control element or 
```html
<h3 class="title is-3">
  Some text
</h3>
```
3. The text will appear in white.

### Expected behavior

Since the modal content background does not inherit the class properties of the element it's being called in, the elements inside the modal shouldn't inherit anything either.

The text should appear in black.

### Actual behavior

Screenshot of the problem below:

![screenshot from 2017-09-04 20-47-15](https://user-images.githubusercontent.com/11542923/30036312-5d370cf0-91b2-11e7-94b1-02f5c4510699.png)

There is white text near the switch. Other labels appear correctly.

Note that it's not a switch issue as I get white text for the `h3` element.

If there is a workaround, I would appreciate knowing about that :+1: 

Thanks!
Saurabh

**Comment by jgthms** [comment]
The modal should be a direct child of the root element `<html>`, ideally just before the closing `</body>` tag. Otherwise, you're gonna run into z-index and other issues.

**Comment by aocneanu** [comment]
Hi @jgthms 

This behaviour limits us when we try to create dedicated (Vue) components with their own modal(s). Is there any workaround for this?

Thank you!

**Comment by aocneanu** [comment]
Hello again :)

I created https://github.com/laravel-enso/enso with Bulma, VueJs and Laravel.

The project is pretty much polished and I would like to start using it in my business projects.

But I still have this one last problem. I have a dedicated modal component that is reused in other components, and the modal not showing correctly in this situation. I feel it's too much of limiting factor to have to put the modal directly into `<body>...</body>`, and it seems that it affects others too.

Besides the modal background showing funny, the div below the modal is scrollable while the modal is showing.

Maybe there is a solution, or maybe you can suggest another approach. 

This is a screenshot with a dedicated vue component for forms

![image](https://user-images.githubusercontent.com/16073274/32824795-10a78830-c9eb-11e7-82fe-fa8d8d568c1d.png)

Here is another one from a documents component

![image](https://user-images.githubusercontent.com/16073274/32824877-6251742a-c9eb-11e7-999e-35979a50d138.png)

Thank you in advance!
