### ISSUE TITLE
how to make dropdown near hamburger in navbar when collapse 

### ISSUE THREAD

**Issue by zeing** [jgthms/bulma#1156]
how to make dropdown near hamburger in navbar when collapse 

i try edit  in PUG.js

   ```
    nav.navbar
            .navbar-brand
              .navbar-item.has-dropdown.is-hoverable
                        a.navbar-link.is-active(href='/documentation/overview/start/')
                            | Docs
                        .navbar-dropdown
                            a.navbar-item(href='#')
                                | Overview
                .navbar-burger.burger(data-target='navMenuExample')
                    span
                    span
                    span
            #navMenuExample.navbar-menu
            . . . .
```

thank you

**Comment by jgthms** [comment]
The navbar burger should be a direct child of navbar brand, not of a navbar item.

**Comment by zeing** [comment]
sorry for my Tab 

this is my code 
![image](https://user-images.githubusercontent.com/20161393/30050451-c55acfce-9248-11e7-9ce0-c00b7ea5a506.png)
i try to logout within monchai@ooca.co  when navbar collapse 

![image](https://user-images.githubusercontent.com/20161393/30050497-e8ec68a8-9248-11e7-8014-6f6dacbbe258.png)
