### ISSUE TITLE
Dropdown Menu not displaying on click

### ISSUE THREAD

**Issue by kerranm** [jgthms/bulma#1157]
This is about the Bulma 0.5.1 CSS framework, tested across Firefox, Safari and Chrome on Mac OSX. I have also tested this on the CDN version (from the template provided on the 'Start' documentation page and the SASS version.

The dropdown menu doesn't dropdown. The hover works but the on click doesn't.

**Comment by Wikiki** [comment]
Hi,

To get the onclick working you need javascript.
Only is-hoverable is pure CSS.
