### ISSUE TITLE
Navbar burger not reponsive on mobile and navbar not responsive on home page

### ISSUE THREAD

**Issue by RageItalic** [jgthms/bulma#1159]
### Overview of the problem
The Navbar burger is not responsive on the app I'm working on. I even copied the exact navbar code from the bulma site and pasted it inside my body tag. The navbar burger still does not work... although it works on the bulma site. 

Also, the navbar in general is not responsive on mobile on the home page. It is responsive on every other page on mobile, but just not the home page and I do not know why. I am using the same navbar on every page.

 This is about the Bulma **CSS framework** 
 This is about the Bulma **Docs**

**Comment by jgthms** [comment]
Do you have the meta viewport tag from the starter template?

**Comment by RageItalic** [comment]
I didnt have that.. added it and now its responsive. Thank you so much!! but the burger still does not work

**Comment by jgthms** [comment]
You need to implement the Javascript toggle yourself. But there's an example provided: http://bulma.io/documentation/components/navbar/

**Comment by RageItalic** [comment]
It finally works!! Thank you so much!
