### ISSUE TITLE
Accept donations

### ISSUE THREAD

**Issue by 3noch** [jgthms/bulma#116]
You just *might* get some...

**Comment by jgthms** [comment]
Haha thanks. I've never thought about it this way.

Bulma is still in early development so I don't think it would be fair to accept any donation for it.

But there's a donate button for my other project, [MarkSheet](http://marksheet.io/), which I think is way more valuable than Bulma :smile:

**Comment by jgthms** [comment]
I've added a PayPal donate button in the footer.
