### ISSUE TITLE
Changing color of the arrow in the navbar dropdown

### ISSUE THREAD

**Issue by RonMelkhior** [jgthms/bulma#1162]
### Overview of the problem

This is about the Bulma **CSS framework**  

I'm using Bulma **version** [0.5.1]

I am sure this issue is **not a duplicate**

### Description

At the moment, it seems like the arrow is generated in the same way no matter if the dropdown is active etc, which is a bit of a pain in my case since when the dropdown is marked as  `is-active`, the arrow's color becomes too bright (since the background is white).

Is there a way to reliably change it's color when it's active? Simply re-setting the border like so:

```sass
.navbar-item
    &.has-dropdown
        &.is-active
            .navbar-link
                color: #000
                &::after
                    border: 1px solid black
```

Causes an effect like this:

![Screenshot](https://i.clouds.tf/ot29/5jqw.png)

Any help would be appreciated.

**Comment by jgthms** [comment]
Just use `border-color`.
