### ISSUE TITLE
Text color issues with links in tags 

### ISSUE THREAD

**Issue by nedjo** [jgthms/bulma#1163]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.5.1
My **browser** is: Firefox 55.0.2 on Linux
I am _pretty_ sure this issue is **not a duplicate**

### Description
* Links inside of `tag is-primary` elements are invisible (have primary color).
* Links inside of tags of other colors may have poor contrast.

### Steps to Reproduce
```html
<div class="tags">
  <span class="tag is-primary">Primary</span>
  <span class="tag is-primary"><a href="#">Primary</a></span>
  <span class="tag is-info">Info</span>
  <span class="tag is-info"><a href="#">Info</a></span>
</div>
```

### Expected behavior
Probably, text is the same color as without a link (for `is-primary`, white).

This leaves the problem that there is no visual difference between link and no link.

### Actual behavior
Text in link is the default for links, the primary color.

Screenshot for the HTML given in the "Steps to Reproduce":
![tags-with-link](https://user-images.githubusercontent.com/295958/30141341-c470a268-932f-11e7-9b58-c67645c7498a.png)

Something like the following is a hack for just the `.is-primary` case:

```
.tag
  &.is-primary
    a
      color: #fff;
      &:hover
        color: #000;
```

**Comment by jgthms** [comment]
Why not make the tag itself a link, like here: https://github.com/jgthms/bulma/blob/master/docs/_includes/meta.html

**Comment by nedjo** [comment]
@jgthms 

Thanks, that does it, and it's an improvement anyway (the whole tag is clickable).
