### ISSUE TITLE
How to make dropdown menu near hamburger bar in navbar when collapse

### ISSUE THREAD

**Issue by zeing** [jgthms/bulma#1164]
### Overview of the problem

I'm using Bulma **version** [0.5.1]
My **browser** is: chrome  60.0.3112.113

### Steps to Reproduce
1.   code my navbar  in Pugjs
![image](https://user-images.githubusercontent.com/20161393/30195696-58bc2d56-9485-11e7-8dc9-291c2a410ea5.png)
2. i try when navbar is collapse will show  navbar-brand ,  menu test@hotmail.com  dropdown ( child is logout ) 
3. it is don't work it is show dropdown menu test@hotmail.com  before collapse

### Expected behavior
![image](https://user-images.githubusercontent.com/20161393/30195774-f302c44c-9485-11e7-97cb-6550b43d0dae.png)
when collapse navbar have 3 item ( logo , test@hotmail.com(and have logout submenu) , hamburger )

### Actual behavior
before collapse it have double test@hotmail.com menu 
![image](https://user-images.githubusercontent.com/20161393/30195802-22239c42-9486-11e7-84d4-27c1d1f326f5.png)
after collapse   logout submenu don't within test@hotmail.com
![image](https://user-images.githubusercontent.com/20161393/30195811-3e533490-9486-11e7-9eb3-81d60d44a383.png)

**Comment by jgthms** [comment]
Try putting the `navbar-burger` after the `navbar-item` in `navbar-brand`.

**Comment by zeing** [comment]
![image](https://user-images.githubusercontent.com/20161393/30214211-c5bca43a-94d5-11e7-854f-3b20bd02a151.png)
 don't work
