### ISSUE TITLE
Change desktop breakpoint to 720p (half HD)

### ISSUE THREAD

**Issue by gw0** [jgthms/bulma#1165]
### Overview of the problem

This is about the Bulma **CSS framework**.  Change request to fix an unpleasant behavior.

I'm using Bulma **version** [v0.5.0]

### Description

Most desktop screens and TVs have full HD (1920x1080) resolution, so there is finally enough room to open two windows simultaneously (one on the left half of the screen, another on the right half). Even modern OSes have support for sticking windows to left and right halves, so people use this more than ever. The width of each half window is therefore 960px, if we subtract an average scroll bar we come to **935px** of browser content width.

Unfortunately, the responsive CSS breakpoint for `desktop` is set to **1008px**, consequently all half-screen windows are rendered as `tablet` and the `navbar` component is collapsed into the navigation burger. The solution would be to move the `desktop` responsive CSS breakpoint to **935px**.

### Steps to Reproduce

1. Change screen resolution to 1920x1080.
2. Open any Bulma page with `navbar` (eg. <http://bulma.io/documentation/overview/start/>).
3. Stick your browser window to the left or right half of the screen (changes window width to 960px, content width is 935px).

### Expected behavior

The `navbar` on `desktop` should berendered completely, as there is enough space left.

### Actual behavior

Notice how the `navbar` on `desktop` collapses into the navigation burger.

**Comment by jgthms** [comment]
The breakpoint is actually `960px` (because it's divisible by 12 and 16) `+ (2 * $gap)` which is `2 * 32px = 64px` by default. So the breakpoint is at `1024px`. You can customize it by using a negative `$gap` value.

**Comment by gw0** [comment]
Ok, but wouldn't it be better if this would be the default? So that two browser windows could be simultaneously visible and rendered as `desktop` on a full HD monitor (1920x1080)?

**Comment by frederikhors** [comment]
Any news on this, @gw0?
