### ISSUE TITLE
Does Bulma has collapsed list ?

### ISSUE THREAD

**Issue by NuruddinBadawi** [jgthms/bulma#1166]
I need to add to my list ability to collabs and expand like in the Bootstrap collapsed list.

**Comment by jgthms** [comment]
Can you post an example?

**Comment by thecodechef** [comment]
@jgthms @nuruddinXbadawi 

i believe what he is talking about is the menu component:

``` html
<ul class="menu-list">
    <li><a>Team Settings</a></li>
    <li>
      <a class="is-active">Manage Your Team</a>
      <ul>
        <li><a>Members</a></li>
        <li><a>Plugins</a></li>
        <li><a>Add a member</a></li>
      </ul>
    </li>
    <li><a>Invitations</a></li>
    <li><a>Cloud Storage Environment Settings</a></li>
    <li><a>Authentication</a></li>
  </ul>
```

Currently bulma does not provide a way to easily collapse the list on the inside of the menu list item that i know of anyway.

**Comment by nuruddinXbadawi** [comment]
@jgthms yes like above example.

anyway to collapse them?

**Comment by ctolkien** [comment]
Perhaps look at the [Details / Summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) elements?

**Comment by geirmarius** [comment]
@nuruddinXbadawi If you want to do it with only html/css, it can easily be achieved with a checkbox: https://jsfiddle.net/5bzasdcr/
If you don't want the checkbox to be visible, just hide it with `display: none;`

**Comment by efendijr** [comment]
You can add display none  on list which u want  can expand and remove display none if u want to expand.. reevaluate using JS

**Comment by MethaTrader** [comment]
Check my solution: [](https://jsfiddle.net/MethaTrader/5c1neao2/) 
Only bulma.io and umbrellaJs framework. 
U can use native JS.
