### ISSUE TITLE
Bulma html background color unable to be customized

### ISSUE THREAD

**Issue by pbmarcano** [jgthms/bulma#1170]
### Overview of the problem

- This is about the Bulma **CSS framework**
- I'm using Bulma **version** [0.5.1]
 
### Description

I spent a little while trying to change the html background color of bulma through the customization steps in the docs. 

Eventually, I noticed that the [white background color](https://github.com/jgthms/bulma/blob/2bda5fccc615142f441d20be59b8164b546adf37/sass/base/generic.sass#L1) is hard coded into sass/base/generic.sass and can't seem to be changed through the customization steps.

Would it make sense to change `$body-background-color: #fff !important` to `$body-background-color: $background !important` (or a different customizable variable) so that people importing via npm can change the background color globally?

---

**EDIT**: I am an idiot that overcomplicated things, please ignore all of this. I could just change the `$body-background-color` with the traditional customization instructions.

**Comment by bstashio** [comment]
@jgthms Any particular reason to keep it hard coded? It seems to me the only exception.  I think we're better off setting to `$body-background-color: $white !default`. What do you think?
