### ISSUE TITLE
Container overflowing hero-body

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#1172]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.5.1]

I am sure this issue is **not a duplicate**?

### Description
I feel like I'm missing something here but for some reason, a container inside a full height hero is not working properly. Here's a screenshot to better illustrate : https://imgur.com/a/pZlLM

### Steps to Reproduce

```
<body>
  	<div class="columns is-desktop">
  		<div class="column is-5">
	              <div class="hero is-dark is-bold is-fullheight">
			    <div class="hero-body">
				    <div class="container">
			            <h1>fdsfoew fewofiew foewiof ewofeow foiewfoiweofioewfiewofoewfoiewoifiewofiewiofewiofioewifiewfioewiofiewfoiewoifioewfioewiofiew fiewifewiofioewifiewfioewiof ewfwe</h1>
				    </div>
				</div>
			</div>
		</div>
	  	<div class="column is-7">
	  	</div>
	</div>   
  </body>

```
### Expected behavior

For the container width to fit the hero-body width

### Actual behavior

Container overflows when the text inside is long enough

**Comment by MarioCares** [comment]
Use the fluid container:
`<div class="container is-fluid">
</div>`

**Comment by rsalunga29** [comment]
@MarioCares doesn't work for me. is there other way around this?
