### ISSUE TITLE
Table overflow in mobile/small screen 

### ISSUE THREAD

**Issue by Ehco1996** [jgthms/bulma#1174]
### Overview of the problem
I found that table overflow on small screen

### Description
you can check the problem here: <http://bulma.io/documentation/elements/table/>
by using  the chrome dev  mobile mode 

i take some pic to show this :

![](http://opj9lh0x4.bkt.clouddn.com/17-9-11/68039033.jpg)

![](http://opj9lh0x4.bkt.clouddn.com/17-9-11/10877308.jpg)

### Steps to Reproduce

1. open web in mobile or other small screen device
2. look up the table which width overflow...

**Comment by jgthms** [comment]
#1080
