### ISSUE TITLE
Typography helpers text weight css classes was missed in v0.5.1 source code

### ISSUE THREAD

**Issue by Folyd** [jgthms/bulma#1175]
### Overview of the problem

 I'm using Bulma **version** [0.5.1]
 I am sure this issue is **not a duplicate**

### Description

Bulma v0.5.1 source code misses those text weight helper classes.

Class | Weight
-- | --
.has-text-weight-light | Transforms text weight to light
.has-text-weight-normal | Transforms text weight to normal
.has-text-weight-semibold | Transforms text weight to semi-bold
.has-text-weight-bold | Transforms text weight to bold

## How to reproduce

Referring to doc [Text weight](http://bulma.io/documentation/modifiers/typography-helpers/#text-weight), there are four different text weight classes, but it cannot find in [v0.5.1 cdn source code](https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.css)

**Comment by jgthms** [comment]
It's in `0.5.2`.

**Comment by Folyd** [comment]
When `v0.5.2` get released?
