### ISSUE TITLE
Documentation states is-size-1-{breakpoint} _only_ applies to one breakpoint

### ISSUE THREAD

**Issue by middric** [jgthms/bulma#1176]
### Overview of the problem
This is about the Bulma **Docs**
I'm using Bulma **version** 0.5.1

### Description
The documentation stats that the `.is-size-1-{breakpoint}` classes can be used to change the font size and that this change _only_ applies to the breakpoint defined, e.g. 

Class | MobileUp to 768px | TabletBetween 769pxand 1007px | DesktopBetween 1008pxand 1199px | WidescreenBetween 1200pxand 1391px | FullHDAbove 1392px
-- | -- | -- | -- | -- | --
is-size-1-tablet | unchanged | 3rem | unchanged | unchanged | unchanged

However as the breakpoint mixins only use a min-width and no max-width the font sizes apply to all the breakpoints at higher width too.

### Steps to Reproduce
Add `.is-size-1-tablet` to an element.
View at tablet and desktop breakpoints

### Expected behavior
If documentation is correct:
Font size should be 3 rems in tablet breakpoint
Font size should be the default in desktop breakpoint

If documentation is incorrect:
Docs need to be updated

### Actual behavior
Font size is 3 rems in both breakpoints

**Comment by jgthms** [comment]
Yes `tablet` means `for tablet and more`. If you want table only, try `is-size-1-tablet-only`.

**Comment by middric** [comment]
ah cool - not clear from the docs, could probably do with updating. My team is just starting to use bulma for a project and the recurring feedback seems to be that bulma is great but the docs are confusing which is creating quite a bit of frustration.

**Comment by middric** [comment]
Actually just tried this an tablet-only is applying to tablet and below: `@media screen and (max-width: 1007px)` - is that intentional?

**Comment by middric** [comment]
Apologies - thats my code having that affect!

**Comment by jgthms** [comment]
For more information about the naming conventions, check out http://bulma.io/documentation/overview/responsiveness/
