### ISSUE TITLE
Strange css property: `--columnGap`

### ISSUE THREAD

**Issue by skyghis** [jgthms/bulma#1181]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.2]

### Description

The provided css contains a strange key: `--columnGap` @ [bulma.css:8849](https://github.com/jgthms/bulma/blob/0.5.2/css/bulma.css#L8849)

My IDE (Netbeans) complains about it.  
I'm not a css expert but this seem strange to me too.

If this key is expected sorry for the false report.

This value was added by PR [Variable columns #1073](https://github.com/jgthms/bulma/commit/6fe43b8f945b2e714fe3e1f9a098f79ac710c52e#diff-137ef0f5e3de878e27d30916c1415c9aR322)

**Comment by jgthms** [comment]
It's a CSS Variable: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by skyghis** [comment]
Ok, sorry I didn't know this css feature.

It's the first variable used in bulma. Why use a variable in this case and not directly the expected value as usual ?

I also note that css variables are note as `experimental` by MDN.

**Comment by jgthms** [comment]
Variable gap is noted as experimental: http://bulma.io/documentation/columns/gap/#variable-gap

**Comment by skyghis** [comment]
Sorry I didn't see that :disappointed: .
Thanks for taking time to reply.

**Comment by jgthms** [comment]
CSS Variables are way more convenient as it only requires to change the variable value to have different layouts: https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L319

**Comment by skyghis** [comment]
I get your point, but this would also be true for many other parts of Bulma who doesn't use variables.

Why use variable for some parts of the code only ?

**Comment by PTcampbell** [comment]
Shopify parses .scss on the server and it won't compile due to this error, for what it's worth.
