### ISSUE TITLE
[readonly] styles for read-only form fields

### ISSUE THREAD

**Issue by schmod** [jgthms/bulma#1189]
### Overview of the problem

This is about the Bulma **CSS framework**
 I am sure this issue is **not a duplicate**?

### Description

Would it be possible to add styles for the [`readonly`](https://html.spec.whatwg.org/multipage/input.html#the-readonly-attribute) attribute on `<input>` and `<textarea>` elements?  

This attribute [is currently supported](https://v4-alpha.getbootstrap.com/components/forms/#readonly-inputs) by Bootstrap v4.

Read-only `<input>`s are meant to function similarly to a "normal" `<input>` with the sole exception that they may not accept input -- they may be focused, do not trigger a `disabled` cursor, have their values included in a form POST, etc.  

However, it would be helpful to style these elements with some kind of visual cue that distinguishes them from an editable `<input>`, or provide a class for developers to be able to opt-in to certain aspects of the `disabled` styling of an `<input>` without actually adding a `disabled` attribute.

**Comment by jgthms** [comment]
Yes that's a good idea.

**Comment by quoyi** [comment]
not include select tag ?
