### ISSUE TITLE
is-overlay is bigger than its parent

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#1191]
Bug

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.2]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

When using a div with the `is-overlay` class inside a columns.is-centered div with a nested column, the overlay div fits the 'columns' div instead of the 'column' one

### Steps to Reproduce

https://codepen.io/aocneanu/pen/Naqwwv

### Expected behavior

I'm expecting that the overlay div should fit its direct parent.

**Comment by jgthms** [comment]
Add `position: relative` to the box.

**Comment by aocneanu** [comment]
Thank you!
