### ISSUE TITLE
Color modifiers do not work for Navbar

### ISSUE THREAD

**Issue by artemkovalyov** [jgthms/bulma#1192]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.5] 
My **browser** is: Chrome, FF
I am sure this issue is **not a duplicate**?

### Description

Color modifiers are not applied to Navbar item

### Steps to Reproduce

1. Add color modifier like "is-primary" like this ```<nav class="navbar is-primary">...</nav>```
2. Navbar stays white coloured.

### Expected behavior

Navbar change color to a primary color. No classes defined in bulma.css to accommodate .navbar.<modifier>. In css used on docs site, such classes are present.

### Actual behavior
Doesn't apply the desired modifier.

**Comment by moshemo** [comment]
I'm having the same problem when using the sass version.  When I tried a linked version to the cdn cs, I did NOT have the problem.

**Comment by moshemo** [comment]
I updated to version 0.5.2 of Bulma and now it works as it should.

**Comment by artemkovalyov** [comment]
Hey, thanks for comments. With CDN I also had issues so will try 0.5.2.

**Comment by OGhawsi** [comment]
I have the same problem with 0.5.3 
So as you said I should go back to 0.5.2 or What?
It is expected to work with all the latest versions

**Comment by shigg1120** [comment]
same here as soon as I upgraded to 0.5.3 . My navbar lost its font color

**Comment by dimensi0n** [comment]
Same

**Comment by dimensi0n** [comment]
I updated to the last version and it works now for me

**Comment by Shigeki1120** [comment]
stfu
