### ISSUE TITLE
Bulma columns overlapping with tables with long content inside.

### ISSUE THREAD

**Issue by Cosbgn** [jgthms/bulma#1194]
I'm using the latest version of bulma 5.0.2.

The issue appears when I'm trying to put two tables one near the other. I use `column is-6` I also tried with `column is-half` and I tried to remove particular table properties like `is-narrow` but no luck so far.

When the table content has spaces bulma correctly displays the content in multiple lines, but with something like a url it just overlaps the next column. 

Ideally I would like to have a horizontal scroller to check the rest of the url. But I think Bulma should automatically break it in multiple lines.

This is a live example https://codepen.io/anon/pen/LzVrbd

**Comment by jgthms** [comment]
This is tricky because there's no way to detect long strings. You could use `word-break: break-all` on those.

**Comment by Cosbgn** [comment]
`word-break: break-all` works perfectly. I've updated the pen for the others who find this question.
https://codepen.io/anon/pen/LzVrbd

Thank you very much!
