### ISSUE TITLE
Gulp-sass doesnt recognize variables

### ISSUE THREAD

**Issue by mathvbarone** [jgthms/bulma#1196]
I have been trying many different ways to import the framework to my project, either using  npm, or importing the whole library to my src folder.

Doesn't matter what I do, my gulp-sass cannot find the variables as you can see at those images below:

[Gulp error](http://prntscr.com/glm81a)

[Sass import](http://prntscr.com/glm8cb)

[Gulp, Gulp-sass and Bulma versions](http://prntscr.com/glm8nh)

I need to modularize my CSS, thats why I want to use the SASS version of the project, instead of just call the full CSS version.

Am I doing anything wrong, or is it a gulp, or gulp-sass problem?

**Comment by TemaSM** [comment]
**Confirm that**, but with **Webpack** and **Bulma 0.5.2**
I just updated Bulma from **0.5.1** to **0.5.2** and got problem: `Undefined variable: "$container-offset"`
### Versions:
Webpack: 3.6.0
Bulma: 0.5.2
sass-loader: 6.0.6
### Screenshot:
![image](https://user-images.githubusercontent.com/5501615/30502400-b7065e92-9a6e-11e7-88d9-1b0f63190e90.png)

After downgrade from 0.5.2 to 0.5.1 everything works fine

**Comment by jgthms** [comment]
`$container-offset` is not in the source code anymore. Where is it called from?

**Comment by TemaSM** [comment]
@jgthms I' using this var in my own Bulma theme (sass file), to implement some responsive classes for it.
Do we have any alternative to `$container-offset` in 0.5.2 or probably in next releases?

**Comment by jgthms** [comment]
Sorry! `$container-offset` ended up being redundant, since the `$gap` variable already existed.

Basically, `$container-offset` is twice the value of `$gap`, so you can use `2 * $gap` if needed.

**Comment by TemaSM** [comment]
@jgthms Okay, thanks for explanation, will declare in my theme for better compatibility:
`$container-offset: 2 * $gap`

**Comment by mathvbarone** [comment]
What about my error?
