### ISSUE TITLE
Inconsistent active states between anchor tags and buttons

### ISSUE THREAD

**Issue by adevade** [jgthms/bulma#1197]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.2]
My **browser** is: Chrome 60 on Windows 10
I am sure this issue is **not a duplicate**

### Description
Clicking on anchor tags with button class leaves no active state.
However, clicking on button tag or input submit/reset does.

![2017-09-16_01-13-11](https://user-images.githubusercontent.com/1066486/30506608-9ebbbc9c-9a7d-11e7-8674-060eed65c877.gif)

### Steps to Reproduce
1. [Go to the docs](http://bulma.io/documentation/elements/button/).
2. Click on "Anchor" button in the second snippet.
3. Click on "Button" button next to it.

**Comment by jgthms** [comment]
That's how browsers behave unfortunately. `button`s keep an `active` state even after clicked.
