### ISSUE TITLE
Checkbox checked and disabled 

### ISSUE THREAD

**Issue by ComplX1** [jgthms/bulma#120]
When a checkbox is Checked and Disabled, its going white on hover.

This is because bulma.css line 894
.checkbox input[disabled], .menu-checkbox input[disabled], .radio input[disabled], .checkbox input[disabled]:hover, .menu-checkbox input[disabled]:hover, .radio input[disabled]:hover {
  background: #f5f7fa;
  border-color: #d3d6db;
}

This wouldn't be what i expect, im not sure if this is intended. it may be better to remove the disabled:hover class so it doesn't change on hover

**Comment by jgthms** [comment]
Mmmh, I don't seem to have that issue. Could you record a gif or video of the problem?

**Comment by ComplX1** [comment]
I cant get you a gif on my work pc. but on the bulma documentation http://bulma.io/documentation/elements/form/ make the checkbox checked and add a disabled property to the input button and you'll see the hover issue

**Comment by jgthms** [comment]
Nice catch. It's a weird bug.

**Comment by jgthms** [comment]
Fixed
