### ISSUE TITLE
`.tag` and `.number` are used by code highlighting tools

### ISSUE THREAD

**Issue by znck** [jgthms/bulma#1201]
### Overview of the problem

This is about the Bulma **CSS framework**

### Steps to Reproduce

```
<pre>
   <span class="token tag">foo</span>
   <span class="token number">12</span>
</pre>
```

### Expected behavior

Should not override highlight style.

**Comment by jgthms** [comment]
That's tricky to do, since there's no way of knowing what a highlighter's CSS classes are. The only way is to include everything except the tags and numbers.
