### ISSUE TITLE
Documentation links to source files

### ISSUE THREAD

**Issue by maurobringolf** [jgthms/bulma#1205]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.5.2]

### Description

I am using Bulma through sass modules and import only the ones I need. I looked through documentation and found the **level** component, but couldnt find an immediate link or hint as to what file I should import to use it. It is documented under layout, but its source is under components. Why is that?

I would suggest adding a link to sass source files for each documentation page, so users can immediately see what modules they need to import.

**Comment by jgthms** [comment]
Yes I moved it in the documentation as I realised it's more of a layout component. I might move it in the source but it might break builds.

**Comment by maurobringolf** [comment]
Okay and what do you think of providing a link/ sass include path for each module directly on the doc pages?

**Comment by jgthms** [comment]
yes why not
