### ISSUE TITLE
Offsets at breakpoints

### ISSUE THREAD

**Issue by ChaseGiunta** [jgthms/bulma#121]
Is there a way to designate offsets at different breakpoints?
`column is-10-tablet is-offset-1-tablet is-8-desktop is-offset-2-desktop`

**Comment by jgthms** [comment]
Yes, your code should work actually. Do you have an example?

**Comment by ChaseGiunta** [comment]
:confused: You're right, this is working. I must have overlooked something initially. Apologies!

**Comment by jgthms** [comment]
I'm glad it works! It's one of the hardest parts of Bulma to get right :sweat_smile:
