### ISSUE TITLE
Rails Integrations

### ISSUE THREAD

**Issue by rush-skills** [jgthms/bulma#122]
Any plans on integrating bulma to Ruby on Rails, like the "twitter-bootstrap-rails" gem offers? 
I had a few things in mind for that as listed here:
https://github.com/rush-skills/bulma-css#todo

**Comment by jgthms** [comment]
That looks good! I could add it to the documentation when you finish it.

**Comment by jvanbaarsen** [comment]
A gem for rails has been created by @joshuajansen: https://github.com/joshuajansen/bulma-rails
