### ISSUE TITLE
Container is-fullhd does not fill the entire screen resolution 1366x768

### ISSUE THREAD

**Issue by mardonedias** [jgthms/bulma#1221]
bulma: 0.5.3

The largest container is-fullhd = 1452px it will have the maximum width of 1344px. generates a small defect in the layout on screens with 1366x768 resolution, there is a white border on the left side. Is there a forecast to implement a width that fills the entire screen?

**Comment by mardonedias** [comment]
![image](https://user-images.githubusercontent.com/1024457/30727566-68d3faae-9f28-11e7-8657-03518c0af423.png)

**Comment by jgthms** [comment]
Have you tried `container is-fluid`?

**Comment by mardonedias** [comment]
Good Morning,

I've already tried. But, the result I want is for the baner to fill the entire width of the screen depending on the size of the screen. From what I saw in Bulma's documentation the closest feature is is-fullhd getting a white border.

## This is how the container will behave:

* on $ desktop + $ container-offset => = 1068px it will have the maximum width of 960px and will be horizontally centered.
* on $ widescreen + $ container-offset => = 1260px it will have the maximum width of 1152px.
* on $ fullhd + $ container-offset => = 1452px it will have the maximum width of 1344px.
The $ gap variable has a default value of 24px but can be modified.

![sem titulo-3](https://user-images.githubusercontent.com/1024457/30748518-f104bb8a-9f86-11e7-9860-ba72766793c8.jpg)

I appreciate it

**Comment by mardonedias** [comment]
Good Morning,

I really appreciate your help. I got a way to do using the `component hero` it fills the entire screen.

It was my mistake.

I hope to be able to contribute to this excellent project soon.

**Comment by mardonedias** [comment]
Bom dia,

Good Morning,

I've already tried. But, the result I want is for the baner to fill the entire width of the screen depending on the size of the screen. From what I saw in Bulma's documentation the closest feature is is-fullhd getting a white border.

### This is how the container will behave:

* on $ desktop + $ container-offset => = 1068px it will have the maximum width of 960px and will be horizontally centered.
* on $ widescreen + $ container-offset => = 1260px it will have the maximum width of 1152px.
* on $ fullhd + $ container-offset => = 1452px it will have the maximum width of 1344px.
The $ gap variable has a default value of 24px but can be modified.

![sem titulo-3](https://user-images.githubusercontent.com/1024457/30750311-7f90ce0c-9f8c-11e7-901b-b2b37087dcd8.jpg)

**Comment by jgthms** [comment]
Why do you need a container?

**Comment by mardonedias** [comment]
First thank you very much for your attention.

In fact analyzing here, I'm actually walking in circles does not need a container. Can I put it inside a div. I tried in many ways, less, just use a div.

Please forgive this noob.
