### ISSUE TITLE
Clarify what file to create/edit in Step 2 in Customize Doc

### ISSUE THREAD

**Issue by kslstn** [jgthms/bulma#1223]
This is about the Bulma **Docs**
I'm using Bulma **version**0.5.3

### Description

Step 2 in the document bulma/docs/documentation/overview/customize.html does not describe in what file those changes are supposed to be made. My assumption was a new file, but as a run into css building issues, I'm not so sure.

**Comment by Croxy** [comment]
I'd like to second this. 

I'm attempting to figure out which file to modify, but it seems not matter which file it is I cannot get the same results as the example at http://bulma.io/documentation/overview/customize/.

Thanks!

**Comment by bstashio** [comment]
I agree, the [customize docs](http://bulma.io/documentation/overview/customize/) may be kind of confusing and feels incomplete.  Until it gets updated, please share your `sass` code so we can try helping you out.

You may also want to check #1251 as it might already have a solution for you.

**Comment by Croxy** [comment]
Hi bstashio! Thanks for the reply. 

I simply copied the code from the customize example and pasted it into the bulma.saas file under the first 8 lines. 

`// 1. Import the initial variables
@import "../sass/utilities/initial-variables"

// 2. Set your own initial variables
// Update blue
$blue: #72d0eb
// Add pink and its invert
$pink: #ffb3b3
$pink-invert: #fff
// Add a serif family
$family-serif: "Merriweather", "Georgia", serif

// 3. Set the derived variables
// Use the new pink as the primary color
$primary: $pink
$primary-invert: $pink-invert
// Use the existing orange as the danger color
$danger: $orange
// Use the new serif family
$family-primary: $family-serif

// 4. Import the rest of Bulma
@import "../bulma"`

**Comment by bstashio** [comment]
Hi Croxy!  Sorry I couldn't reply earlier.

> and pasted it into the bulma.saas file under the first 8 lines

You need to add the code before not after.

**Comment by dikaio** [comment]
Wouldnt editing the initial-variables and derived-variables affect future updates by potentially overwriting any custom css?

Would it be better to just create a overrides file or similar that contains custom variables and imports of specific overrides e.g.

```scss
@import "scss/overrides";
@import "scss/utilities/all";
@import "scss/base/all";
@import "scss/elements/all";
@import "scss/components/all";
@import "scss/grid/all";
@import "scss/layout/all";
```

**Comment by bstashio** [comment]
No one is saying that you should directly edit any source file, be it `initial-variables` or `derived-variables`, and yes, if you prefer so, you can place all your custom variables in a file and call it `overrides`, or any other relevant name, and then import it your main `sass`.

**Comment by ericgrosse** [comment]
I figured it out thanks to this [blog post](https://medium.com/@tylermalone/customizing-bulma-in-your-cra-app-91ea1fdba6a3).

(To clarify, my project setup uses React)

**index.js** (webpack entrypoint)

```
import 'bulma/css/bulma.css';
import 'styles/app.scss';
...
```

**app.scss**

```
@import '~bulma/sass/utilities/initial-variables.sass';

$newColor: #333;
$info: $newColor;

@import '~bulma/bulma.sass';
```

You might not need the `~` on the import, that might  be specific to my webpack setup.
