### ISSUE TITLE
Feature Request: Namecard Component

### ISSUE THREAD

**Issue by cedewey** [jgthms/bulma#1225]
A style for showing a namecard/teaser of a person would be helpful. I'm not sure if that makes sense directly here in the Bulma project or as an extension, but figured I would start with my request here.

**Comment by cedewey** [comment]
A component that shows a teaser view of a person, for example with a
profile picture, name, title, short bio.

**Comment by TheRandomMelon** [comment]
You could possibly do that with current Bulma cards.

**Comment by jgthms** [comment]
@TheRandomMelon is right. A namecard would be too specific, but you can use the Bulma card to achieve that already, with some tweaks.
