### ISSUE TITLE
Problem with Icon in Text Field Inside Navbar

### ISSUE THREAD

**Issue by moshemo** [jgthms/bulma#1226]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.3]

### Description

I have added an input text field to the navbar with a left-icon.  The icon, though, is not showing properly.  The same code, though, works as it should when it is not inside the navbar.  Here is a screenshot:  

![image](https://user-images.githubusercontent.com/13052314/30784452-edeadd48-a15d-11e7-8ceb-84e6f7dc5972.png)

NOTE:  The screen shot shows both the input fieldin the navbar, and another one below the navbar. 

### Expected behavior

The icon align properly within the navbar

### Actual behavior

The icon is out moved to the top left.

NOTE:  I think the issue is with the navbar-item padding.  I can compensate for that padding via css, but I am wondering if there is a built-in solution.

**Comment by jgillich** [comment]
This works fine for me:

```html
        <div class="navbar-menu">
          <div class="navbar-item field has-addons">
            <div class="control has-icons-left">
              <input class="input" type="email" placeholder="Search">
              <span class="icon is-small is-left">
                <i class="fa fa-search"></i>
              </span>
            </div>
          </div>
        </div>
```
