### ISSUE TITLE
Consider removing docs/versions folder from releases

### ISSUE THREAD

**Issue by fatihacet** [jgthms/bulma#1227]
Latest release size is 43.3 MB and it's because of the older versions in docs folder. If you remove them release size would be around 7.7MB which is way much better. 

Please consider removing old versions from releases to save some bandwidths and keep it ♻️ .

**Comment by jruizsulime** [comment]
Yes! I think this would be nice, we could read doc in the website proyect, it is not necessary to have them on the zip.

**Comment by jgthms** [comment]
Sorry, I didn't realise it was in the release zip as well. It's ignored in npm but not in the tagged branches.
