### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by julisse** [jgthms/bulma#123]
Just very strange for me, how it works now. 
I need to make [those blocks](http://imagec1s.bget.ru/new/7.html) for example tree or four at the row, but classes from documentation doesn`t work as needed. Also it is needed [here](http://imagec1s.bget.ru/new/6.html) and [here](http://imagec1s.bget.ru/new/8.html)
Could you please take a look at my case?

**Comment by jgthms** [comment]
Rename the `is-3-mobile` on every `column` because it means "Is 3 _only_ on mobile".

You need something like:
```
<div class="columns is-mobile is-multiline">
  <div class="column is-3 is-flex hair" id="h1">
    <!-- ... -->
  </div>
  <div class="column is-3 is-flex hair" id="h2">
    <!-- ... -->
  </div>
</div>
```
