### ISSUE TITLE
Date picker z position is wrong on iPad

### ISSUE THREAD

**Issue by vasily-kirichenko** [jgthms/bulma#1232]
![img_2142](https://user-images.githubusercontent.com/873919/30846743-7ec434d8-a2a1-11e7-8971-a0dfbb3cc783.PNG)

**Comment by MangelMaxime** [comment]
This issue should go under [Fulma repo](https://github.com/MangelMaxime/Fulma/issues). As the date picker is not provided by Bulma.

**Comment by vasily-kirichenko** [comment]
Ah! Sorry. Done https://github.com/MangelMaxime/Fulma/issues/56
