### ISSUE TITLE
Rename modifier from is-selected to is-active on TR

### ISSUE THREAD

**Issue by seb3s** [jgthms/bulma#1237]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.3]

### Description

Hi, would you considerer renaming is-selected to is-active for TR elements ?
It would be more consistent with other parts of bulma plus the css variable names are already based on active : 

$table-row-active-background-color 
$table-row-active-color

We can also keep the is-selected modifier to avoid breaking existing code, or not. 
What do you think ? 

Cheers,
Sébastien.

**Comment by jgthms** [comment]
Usually active elements also have a hover and focus states. The active class is also usually combined with the :active pseudo-class.

In the case of the selected row state, it’s not really combined with any other pseudo class, hence the different name.

**Comment by seb3s** [comment]
Ok I see, 
I think that in that case I still would have renamed the css variable names to 

$table-row-selected-background-color
$table-row-selected-color

Cheers
