### ISSUE TITLE
[Suggestion] Colored blockquotes in `.content`?

### ISSUE THREAD

**Issue by shirohana** [jgthms/bulma#1239]
### Overview of the problem

This is about the Bulma **CSS framework**

I think it's cool and useful, what about your thinks?

If you think it can make Bulma more awesome, I can implement it and make a pull request (๑ơ ω ơ)

### Description

https://codepen.io/shirohana/pen/VMbjjw?editors=1100

![2017-09-28 10 00 28](https://user-images.githubusercontent.com/11359892/30946001-1284db98-a3c7-11e7-89c5-b3979f0ad0a0.png)

**Comment by jgthms** [comment]
Why not use a `.notification` or `.message`?

**Comment by shirohana** [comment]
The main reason: They are different semantics.

For example, use `blockquote.is-danger` to remind users where's easy to make a mistake in a document page.

The second reason: `blockquote` is easier to integrate with `markdown` syntax.

Most `markdown` parser wrap `blockquote` syntax to `<blockquote>`, it helps a lot on writing `markdown` documentations.

For example, you can do this when using [markdown-it][md] with [markdown-it-decorator][md-decorator]:

```markdown
> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
>
> Duis eget nulla bibendum, tincidunt quam in, hendrerit purus.
<!-- {blockquote:.is-danger} -->
```

[md]: https://www.npmjs.com/package/markdown-it
[md-decorator]: https://www.npmjs.com/package/markdown-it-decorate

**Comment by jgthms** [comment]
If we're talking semantics, then `blockquote` is wrong, since the content is supposed to be a [long quotation](http://htmlreference.io/element/blockquote/), which it most probably won't.

As for the markdown syntax, why not just write `<!-- {blockquote:.notification.is-danger} -->` then?

**Comment by shirohana** [comment]
You give me a lesson... sorry for misusing (˘̩̩̩ ω ˘̩ƪ)

If we write markdown with Bulma, we should put them in a `.content` block or we'll lost basic styling, but `.content blockquote` also has its styles...

https://codepen.io/shirohana/pen/jGYBRG?editors=1100

![2017-10-05 9 06 41](https://user-images.githubusercontent.com/11359892/31228773-41be40d8-a9a4-11e7-91af-6f86011cff5c.png)

**Comment by shirohana** [comment]
Excuse me 😓
