### ISSUE TITLE
[Feature Request] Need background color helpers for elements

### ISSUE THREAD

**Issue by prahladyeri** [jgthms/bulma#1240]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.3]

### Description

[As per the docs,](http://bulma.io/documentation/modifiers/typography-helpers/) bulma.io has typography helpers for changing the font-color (such as `has-text-white` and `has-text-primary`), but doesn't have it for changing the background-color of an element. Ideally, we need classes like `has-bg-white` or `has-bg-primary`. Bootstrap already have these (they are called `bg-primary`, `bg-danger`, etc) and thus using this naming convention also makes the transition of existing bootstrap projects quite easier.

### Expected behavior

This is a feature request.

**Comment by JeremiasPHP6** [comment]
Thinking the same but with the transitions

**Comment by chasegiunta** [comment]
Was about to create an issue for panel/panel-heading colors, but maybe a more utility-based approach like this could help prevent repetitive bloat for panels & other components that don't rely on states. @jgthms what are your thoughts on this? If we know that this is solid idea, then myself or someone could move towards a PR.

**Comment by mydnic** [comment]
👍  we need this :)

**Comment by christopherdupont** [comment]
I need it too ! 👍

**Comment by mayognaise** [comment]
@prahladyeri You can use `has-background-primary` 😄 
https://github.com/jgthms/bulma/blob/master/sass/base/helpers.sass#L111-L112
