### ISSUE TITLE
Unable to alter $primary variable

### ISSUE THREAD

**Issue by swthate** [jgthms/bulma#1242]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.5.3
My **browser** is: Chrome

### Description

First off I apologize and feel slightly guilty as this issue seems so trivial and simple. But I cannot override the `$primary` variable! I've read through as many other questions similar to this that I can, but nothing is working. I am however, able to modify the `$links` variable?? I'm really confused.

### Steps to Reproduce

I blew away Bulma and reinstallved via `npm` just to make sure I was working with everything correctly.

Here is how I am trying to do this:

```
@import '../node_modules/bulma/sass/utilities/_all.sass';

$primary: red;                 # this does nothing
$link: blue;                   # this does change links to blue!
$primary: orange !important;   # even this does nothing

@import '../node_modules/bulma/bulma';
```

### Expected behavior

Trying to customize some simple variables.

### Actual behavior

The `$primary` variable, at least, does not change according to my instructions.

**Comment by bstashio** [comment]
Try setting the variables before importing `./sass/utilities/_all.sass`.

**Comment by swthate** [comment]
Oh. My. Gosh.

I felt convinced I tried that... but apparently not? Welp, it worked! Thanks 👍

**Comment by bstashio** [comment]
Great!

Please close this issue if you consider it resolved.
