### ISSUE TITLE
'fullhd' mixin has the wrong breakpoint when compiled

### ISSUE THREAD

**Issue by jordanranson** [jgthms/bulma#1244]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.3]

### Description

In both the docs and in variables.sass, it lists the $fullhd variable as 1392px. However, in the compiled CSS, the media query has a min-size of 1408px.

### Steps to Reproduce

1. Write some SASS and wrap it in the +fullhd mixin
2. Compile the SASS into CSS
3. Notice the incorrect breakpoint in the compiled output

### Expected behavior

@media screen and (min-width: 1392px) {
  /* css */
}

### Actual behavior

@media screen and (min-width: 1408px) {
  /* css */
}

**Comment by jgthms** [comment]
See #1252
