### ISSUE TITLE
Suggestion: align buttons to the bottom 

### ISSUE THREAD

**Issue by sigfrid** [jgthms/bulma#1246]
### Overview of the problem

 This is about the Bulma **CSS framework** 

 I'm using Bulma **version** 0.5.3 

### Description

When multiple buttons are placed one after the other

```
<div class='field is-grouped'>
  <a class="button is-small">Small</a>
  <a class="button">Normal</a>
  <a class="button is-medium">Medium</a>
  <a class="button is-large">Large</a>
</div>
```
they are aligned to the top.
I think it looks better if they would align to the bottom.
 
### Expected behavior

![screen shot 2017-09-30 at 8 59 23 am](https://user-images.githubusercontent.com/3609259/31040750-c5259140-a550-11e7-8d26-db6019fd06fe.png)

### Actual behavior

![screen shot 2017-09-30 at 8 59 04 am](https://user-images.githubusercontent.com/3609259/31040746-ba6cea78-a550-11e7-8115-3c276711c240.png)

**Comment by jgthms** [comment]
The vertical align top prevents having a 1px gap underneath when using a single button.

**Comment by dann1609** [comment]
There is no way to align to bottom?
