### ISSUE TITLE
Suggestion: Two colors of progress bar

### ISSUE THREAD

**Issue by ArneAnka** [jgthms/bulma#1250]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.1]

### Description

So wouldn't it be awesome if there was an easy option to change the "second" color from grey to another color on the progress bar? Lets say that you are comparing two values, and the progress bar is not really showing progress, instead it's showing the difference between to values. So you could have `is-success` and `is-danger` as the second color, or something like that.

**Comment by doatech** [comment]
@jgthms do you have any suggestions for naming the `-webkit-progress-bar` background color modifier class? 

My suggestions: 
- `bar-primary`, `bar-success `etc
- `bgr-primary`, `bgr-success` etc
- `fill-primary`, `fill-success ` etc

The `is-*` classes are used for progress value.

**Comment by scottydelta** [comment]
was this ever implemented?
