### ISSUE TITLE
Variable overrides compile but do not render/output

### ISSUE THREAD

**Issue by invisibletype** [jgthms/bulma#1251]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.3]
My **browser** is: Chrome

I am sure this issue is **not a duplicate**
Several issues have been submitted and resolved, but following the instructions within each raised issue does not resolve
Most recent issue https://github.com/jgthms/bulma/issues/1242 addresses the same, but still does not resolve

### Description

Variable overrides compile, but do not render

### Steps to Reproduce

1. Create sass overrides file (following issue https://github.com/jgthms/bulma/issues/1242)
2. Variable $black set with new value #263238
3. File compiles
4. CSS does not reflect variable change
5. All references maintain the default #a0a0a0 (example:  .is-black still compiles as the default)

### Expected behavior

All instances of variable would be replaced by the new value

### Actual behavior

No variable update, all values remain default

**Comment by bstashio** [comment]
Please provide the `sass` code.

**Comment by invisibletype** [comment]
I tried the following:
```
@import 'bulma/sass/utilities/_all.sass';

$black: #263238

@import 'bulma/bulma';
```

```
$black: #263238
@import 'bulma/sass/utilities/_all.sass';

@import 'bulma/bulma';
```

And as explained in the docs:

```
@import 'bulma/sass/utilities/initial-variables.sass';

$black: #263238

@import 'bulma/bulma';
```

**Comment by bstashio** [comment]
Your issue may be caused by using a semicolon ";" instead of end of line, which results in an error when `sass` is compiling a `.sass` file.

Try the following:

```
$black: #263238

@import 'bulma/bulma'
```

If that doesn't work, try using [bulma customizer](https://bulma-customizer.bstash.io/?id=84f516d83848ecaebca0765710a316bf); I've preset it with a custom `config` file that includes your variable, all you need to do is simply download the bundle and then take a look at `src\bulma.sass` and see how the custom variable is set.  If all you care about is the compiled `css` file, then simply unselect the "Download Bundle" option.

**Comment by invisibletype** [comment]
Thanks for the response. I've tried both updating the sass with end of line instead of ";"
Still compiles, but not correct output.

Same thing with the custom config. I updated the file paths to be correct. Compiling works, but doesn't reflect in the output. The config file has the correct reference:
```
    "variables": {
        "bulma": {
            "utilities/initial-variables.sass": {
                "$black": "#263238"
            }
        }
    }
```
The custom bulma.sass has the variable reference:
```
@charset "utf-8"
/*! bulma.io v0.5.3 | MIT License | github.com/jgthms/bulma */
/*! Generated by Bulma Customizer v0.1.0 | https://github.com/bstashio/bulma-customizer */

// -----------------------------------------------------------------------------
// Bulma SASS Files
// -----------------------------------------------------------------------------

// Custom variables related to utilities/initial-variables.sass
$black: #263238

@import "sass/utilities/initial-variables.sass"
```
but the initial-variables.sass file does not have the customization, nor does the css output.

**Comment by bstashio** [comment]
`initial-variables.sass` would not change in any way, the only change you'll see is in the compiled `bulma.css`.

Here's how my [downloaded file looks like](https://gist.github.com/bstashio/a7c39628267cd328edaf633b70c7c6e1#file-bulma-css-L1284); as an example, you can see that the color `#263238` has been set to `.button.is-black`.

**Comment by invisibletype** [comment]
Makes me think there's something up with my compiler. Time to dig into that. Thanks.

**Comment by bstashio** [comment]
Is this related to your [av2017](https://github.com/invisibletype/av2017)? If that's the case, it looks like your [bulma stylesheet](https://github.com/invisibletype/av2017/blob/d27f71f110e97fc9645363199324079c9f8957d3/index.html#L10) is set to bulma's cdn instead of your custom `css` file.

**Comment by invisibletype** [comment]
Yes it's relative to that site, but I haven't pushed my last local changes.

**Comment by invisibletype** [comment]
Figured it out. The compile path was strange.  From /bulma/bulma.sass to /bulma/docs/bulma-docs.sass
Once I updated the stylesheet link to reflect that path, everything started working.
