### ISSUE TITLE
Why are there two different set of breakpoints?

### ISSUE THREAD

**Issue by chhuang** [jgthms/bulma#1252]
Why are there 8px difference for `desktop`, `widescreen` and `fullhd`?

In the [docs](http://bulma.io/documentation/overview/responsiveness/):
![screen shot 2017-10-03 at 9 20 01 pm](https://user-images.githubusercontent.com/78710/31120587-a87e580a-a880-11e7-930f-600c121553a5.png)

In [`variables.sass`](https://github.com/jgthms/bulma/blob/0f94e971d8a147a434d0e0a7c61dd0c647606898/sass/utilities/variables.sass#L52-L58)
![screen shot 2017-10-03 at 9 20 36 pm](https://user-images.githubusercontent.com/78710/31120605-c0bfc73c-a880-11e7-9987-9b11e5aabef6.png)

**Comment by jgthms** [comment]
It's just a problem with the docs.

**Comment by chhuang** [comment]
Got it. In this case, should tablet: 769 be 768 instead since it's the only number that can't be divided by 8/12/16?

**Comment by jgthms** [comment]
So `768` is used because it's the width of a table in portrait mode.

**Comment by kylane** [comment]
But, 768 isnt used?

**Comment by chhuang** [comment]
What's the reasoning of adding `$gap` to the breakpoints? Why `$tablet` don't have the same treatment?

https://github.com/jgthms/bulma/blob/8724ea375df93f6732bb3a1e4d8bb40bd9322827/sass/utilities/initial-variables.sass#L48-L57

@jgthms
