### ISSUE TITLE
long text in button outside of the screen

### ISSUE THREAD

**Issue by jaroslaw-weber** [jgthms/bulma#1258]
so when i put a very long text in button and make screen narrower, or open it on mobile, my text is too long to display so it just goes outside the screen. is there a way to make button wider if text it too long?

**Comment by jgthms** [comment]
Screenshot? Codepen?

**Comment by ezetojo** [comment]
add .is-clipped ?

**Comment by jaroslaw-weber** [comment]
Sorry for late reply. Can you reopen the issue?
https://codepen.io/anon/pen/BwqVPG
I don't want the text to be cut, I want it to resize the button.
is-clipped not changing anything
