### ISSUE TITLE
Sizing issues with form controls when using only form module

### ISSUE THREAD

**Issue by hgezim** [jgthms/bulma#1260]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [master from github]
My **browser** is: Safari Version 11.0 (12604.1.38.1.7)

I am sure this issue is **not a duplicate**?
Yes

### Description

There are sizing issues of `input` controls when using only `form` module.

### Steps to Reproduce

1. Create a sass file as follows:

```sass
@import "../../../../../../node_modules/bulma/sass/utilities/_all";
//@import "../../../../../../node_modules/bulma/sass/base/_all";
@import "../../../../../../node_modules/bulma/sass/elements/form";
@import "../../../../../../node_modules/bulma/sass/grid/columns";

```

2. Build file using sass. For reference, this is relevant snipper of my gulp task:

```js
return gulp.src(path + 'assets/sass/*.scss')
            .pipe(sass({
                includePaths: [modules],
                outputStyle: 'compressed'
            }).on('error', sass.logError))
            .pipe(gulp.dest(path + 'styles'));
```

3. Create a small HTML section as follows:

```html
<div class="columns">
                    <div class="column">
                        <div class="field">
                            <label for="recipe_title" class="label">Title</label>
                            <div class="control">
                                <input class="input is-small" type="text" id="recipe_title" name='recipe_title' value='{{ recipe_title }}' placeholder="Recipe title">
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <label>Image</label>
                    </div>
                </div>
```

### Expected behavior

This is what I get when I uncomment `//@import "../../../../../../node_modules/bulma/sass/base/_all";` from the sass file.

<img width="661" alt="localhost_8080_wp-admin_media-upload_php_recipe_post_id_292_type_z_recipe_tab_amd_zlrecipe_tb_iframe_true_width_640_height_523_and_web_inspector_ _localhost_ _media-upload_php_and_web_inspector_ _localhost_ _post_php" src="https://user-images.githubusercontent.com/124675/31190407-397ac736-a8f8-11e7-9c01-f8641b6cabf2.png">

### Actual behavior

<img width="635" alt="localhost_8080_wp-admin_media-upload_php_recipe_post_id_292_type_z_recipe_tab_amd_zlrecipe_tb_iframe_true_width_640_height_523_and_web_inspector_ _localhost_ _media-upload_php_and_web_inspector_ _localhost_ _post_php" src="https://user-images.githubusercontent.com/124675/31190455-5c752f88-a8f8-11e7-8a46-da23472f703c.png">

**Comment by jgthms** [comment]
What's your CSS output?
