### ISSUE TITLE
$body-background variable is unused !

### ISSUE THREAD

**Issue by Fatih90** [jgthms/bulma#1262]
Hi

i think this variable is wrong
https://github.com/jgthms/bulma/blob/cb53fcf842852019dc90ead0491b11d0c25e1298/sass/utilities/variables.sass#L47

because `$body-background` variable is not used anywhere in the code

should it not be `$body-background-color` variable instead ?

**Comment by bstashio** [comment]
`sass/utilities/variables.sass` is deprecated #769

**Comment by Fatih90** [comment]
@bstashio Thx
