### ISSUE TITLE
The navbar-burger hover background color remains

### ISSUE THREAD

**Issue by aaronbeaton** [jgthms/bulma#1265]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** 0.5.2
My **browser** is: Mobile Safari (latest)

I am sure this issue is **not a duplicate**

### Description

When the navbar-burger is closed, the hover background color remains.

### Steps to Reproduce

1. Open bulma.io in a window small enough to make the mobile nav active.
2. Tap the burger
3. Tap close

### Expected behavior

The background color disappears

### Actual behavior

The background color does not disappear

Should the hover be attached to .navbar-burger.is-active instead?

**Comment by choonggg** [comment]
This seems like a standard for mobile, you'll need javascript to fix that. Look up `sticky hover`.

**Comment by aaronbeaton** [comment]
Thanks for the tip.
I had already moved the background-colour to .navbar-burger.is-active:hover and it works as I'd expect.
