### ISSUE TITLE
100vh in iOS larger than viewable window for .fullheight

### ISSUE THREAD

**Issue by sswany** [jgthms/bulma#1267]
In iOS, the `hero.is-fullheight` expands past the viewable portion of the Safari window and adds a scrollbar.  

I've used https://github.com/Hiswe/vh-check in the meantime with a css variable to fix it for now, but wondering if it could be built into Bulma via media queries instead?  Or something that didn't require JS.

Thanks!

**Comment by georgfranz** [comment]
vh-check works great, tx for the info!
