### ISSUE TITLE
List index is 2 but list is only 1 item long for `nth'

### ISSUE THREAD

**Issue by chhuang** [jgthms/bulma#1268]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.3]

This is a **Sass** issue: I'm using version [0.5.3]

### Description
When trying to compile the Sass files, I get this error traced from [`button.sass:105`](https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L105).

**Comment by jgthms** [comment]
Did you customise `$colors`?

**Comment by chhuang** [comment]
Nop. I'm just trying to import them so I can customise it.

**Comment by jgthms** [comment]
What's your code?

**Comment by chhuang** [comment]
Solved. I was importing the [bootstrap variables](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L48) which has `$colors` defined. Thanks for your help and sorry about that.
