### ISSUE TITLE
Table "is-hoverable" effect is on by default

### ISSUE THREAD

**Issue by guillecro** [jgthms/bulma#1269]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.3]
My **browser** is: Firefox on Ubuntu, Chromium on ubuntu
I am sure this issue is **not a duplicate**? Sure.

### Description

So, a simple `<table class="table">` has the `.is-hoverable` effect on by default.

### Expected behavior

It should not be hoverable by defect

### Actual behavior

It's hoverable by defect

**Comment by jgthms** [comment]
I forgot to add the version. It's coming in the next one.
