### ISSUE TITLE
Lazy loading select list doesn't fully expand items.

### ISSUE THREAD

**Issue by jeremy-addy** [jgthms/bulma#1275]
This is about **Bulma**.

It is a bug.

### Overview of the problem

This is about the Bulma **CSS framework**

My **browser** is: Chrome

I am sure this issue is **not a duplicate**

### Description

When lazy loading a select list, the items in the list are not fully displayed.

### Steps to Reproduce
http://jsfiddle.net/addyjj/vt71wydt/2/

1. Create a select list.
2. After clicking on the list. Load 20 or so items into the list after a 2 sec delay. 
3. The list is not fully expanded.

### Expected behavior

I expect to see the full list of items expanded.

### Actual behavior
Only one item is displayed.
![bulma_select](https://user-images.githubusercontent.com/16001179/31352455-7a805584-acf4-11e7-8f9f-52b3d98e03ef.gif)

**Comment by jgthms** [comment]
It's a browser bug, but it's a normal behavior tbh. In Chrome, the list is repainted when it changes. Edge/IE doesn't seem to do that. It's not an issue with Bulma.
