### ISSUE TITLE
Keep the nav element.

### ISSUE THREAD

**Issue by neoneosa** [jgthms/bulma#1276]
I wont follow the instructions, as i havent really got much time to write this.
My issue is the new navbar element. I dont like it. It seems like a downgrade from the nav element. I really hope you implement more of the old nav features, and add simmilar class names. Also, why have you switched to using navbar? In my opinion, the old nav is perfectly fine.

**Comment by mstinis** [comment]
Unfortunately, I have to agree with @neoneosa... I've been having issues using this new navbar element as well. For example, I'm following the documentation to a tee and it's hiding my navbar items, the hamburger on screen reduction also doesn't seem to work or appear.

**Comment by jgthms** [comment]
The `.nav` had a few issues:

* `.nav-center` was causing lots of problems (search for issues)
* you could only have left and right nav items, unlike the new navbar where you have `brand` on the left, `menu` on the right, but `start` and `end` in `menu` itself
* the `.nav` could not be easily resized
* it couldn't support any **dropdown** menu

The last one is the most important one, and one of the most requested features.
