### ISSUE TITLE
Feature: Input type "number" has no styling

### ISSUE THREAD

**Issue by aaronovz1** [jgthms/bulma#1277]
This is about **Bulma**.

It is a feature request.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.1]
My **browser** is: Chrome

### Description

Is it possible style some of the other HTML5 input types? Specifically "number"

**Comment by jgthms** [comment]
You can just use the `<input type="number" class="input">` and you will still have the arrows in Chrome.
