### ISSUE TITLE
is-selected for table columns

### ISSUE THREAD

**Issue by Cosbgn** [jgthms/bulma#1278]
I understand that this might be complicated and probably would require js so won't be part of bulma. But is there an easy way to add "is-selected" to columns in a table, in a similar way we can add "is-selected" to rows?

**Comment by rafaelrenanpacheco** [comment]
The `is-selected` could be available to cells as well, this way you would choose which cells should be marked as selected.

If your request does't make into bulma's souce, you can create your own css in your project very easily.
