### ISSUE TITLE
[SASS warning] Sass 3.6 will change the way CSS variables are parsed 

### ISSUE THREAD

**Issue by guillecro** [jgthms/bulma#1283]
This is about **Bulma | the Docs**.

### Overview of the problem

This is a **Sass** issue: I'm using version [3.5^] (I guess) 
I am sure this issue is **not a duplicate**? 

### Description

So I got this warning message when i was doing `compass watch`, thought you might want to know it

```
DEPRECATION WARNING on line 328 of /home/mapache/www/residencias-culturales-2018/bower_components/bulma/sass/grid/columns.sass:
Sass 3.6 will change the way CSS variables are parsed. Instead of being parsed as
normal properties, they will not allow any Sass-specific behavior other than #{}.
For forwards-compatibility, use #{}:

  --variable: #{$i * 0.25rem};
```

Ok bye!

**Comment by jgthms** [comment]
Thanks for the heads up. The only instance is `--columnGap` for now. I'll update that.

**Comment by ADTC** [comment]
Am I right to say that this is not applicable to Sass variables?

**Comment by jgthms** [comment]
Works with Sass 3.5.3.
