### ISSUE TITLE
SPA Admin Panel using VueJs, Bulma and Laravel

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#1285]
This is about Bulma and it's not a bug:)

We recently migrated our main project from a conventional Bootstrap (AdminLTE) frontend to a SPA built with Bulma, VueJS and Laravel. Is there any way that I could send you a link with the repo / online demo and maybe get a quick feedback if you have the time? The code is open source of course, and it's loaded with lots of goodies.

Thank you!

**Comment by Log1x** [comment]
Perhaps do a PR in README for projects using Bulma?

**Comment by jgthms** [comment]
Make a PR to add the project to the README if you want to share it with the community.

**Comment by aocneanu** [comment]
Perfect. This is what I will do. Thank you!
