### ISSUE TITLE
New helpers

### ISSUE THREAD

**Issue by oleksiipotiekhin** [jgthms/bulma#1287]
This is about **Bulma**

It is a **feature**

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.0]
I am sure this issue is **not a duplicate**

### Description
When I was implementing the login form I faced a situation that the form was resizing after the error labels were shown/hidden. So i was forsed to add my own **helpers** which will just show/hide an elements and will not remove them from the DOM. 

Is there any chance to add those classes to the Bulma **CSS framework** to be available out of the box?

![Example](https://user-images.githubusercontent.com/30025319/31428699-fbd6710e-ae6b-11e7-8114-8c6cf196c40c.png)

### Expected behavior

![Animation](https://user-images.githubusercontent.com/30025319/31429807-475d4e92-ae6f-11e7-957c-27b2202519b4.gif)

### Actual behavior

![Error Animation](https://user-images.githubusercontent.com/30025319/31430752-209d9ade-ae72-11e7-87f9-6a8ec0fc4693.gif)

**Comment by jgthms** [comment]
Good idea! Make a PR if you want.
