### ISSUE TITLE
Showcase page?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [jgthms/bulma#129]
Hi there!

Will bulma have a showcase page for production ready webpages/apps?

I already have a webpage running in production, build with bulma. If you plan to publish showcases, let me know :+1:

**Comment by jgthms** [comment]
Why not! That's a good idea.

If people use Bulma, they have something to showcase. And if new users see the showcase, they might use Bulma as well!

**Comment by jgthms** [comment]
Btw, this is more something for the website repo: https://github.com/jgthms/bulma-website

**Comment by rafael-renan-pacheco** [comment]
Hi @jgthms!

I didn't know about bulma-website repo, will open a new issue there to suggest this feature.

Thanks!
