### ISSUE TITLE
Media Object Support for Hoverable and Selected 

### ISSUE THREAD

**Issue by mrkirchner** [jgthms/bulma#1292]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Feature to add 'is-hoverable' and 'is-selected' to the media object.  

### Expected behavior

Work similar to how the table handles both 'is-hoverable' and 'is-selected'.

**Comment by jgthms** [comment]
The media object is a layout component, not really a “styled” one. I don’t really see how it would work.

**Comment by mrkirchner** [comment]
Maybe we are just using that component wrong, but since it allows nesting we are kind of using it as a list/tree.  Each media object can be clicked on to open.  Do you have any better suggestions?  We could possibly throw the media object into the table but would need to figure out the nesting.

**Comment by jgthms** [comment]
I see what you mean. That seems like a edge case though, but I believe it could work as an extension, where media object could be hoverablr and collapsible, with an active state as well?

**Comment by Gamadril** [comment]
I tried simply changing background colour on active elements, but since the padding/margin is set by the following media object, so the background is not filling the space between the separator lines...
