### ISSUE TITLE
Why does the html tag have an always visible vertical scroll?

### ISSUE THREAD

**Issue by AWulkan** [jgthms/bulma#1293]
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.0

### Overview of the problem
By default the html tag has `overflow-y: scroll;`. This causes a vertical scroll to appear on all pages even though it is not needed. What is the design decision behind this and why would you need an inactive scroll on pages?

### Expected behavior
No scroll bar on pages that can't be scrolled.

### Actual behavior
All pages have a scroll bar, even if it can't be used.

**Comment by jgthms** [comment]
It's to prevent a "jump" when you navigate from a page that needs it to a page that doesn't.

**Comment by AWulkan** [comment]
Okey, at least there's a valid reason then, even though I personally disagree with the idea of it.

**Comment by terenceng2010** [comment]
For future bulma users, you can override the behavior by setting ```$body-overflow-y: auto;``` if you are using  scss to customize bulma.

**Comment by bkarlson** [comment]
Just stumbled upon this, was unable to apply positon: sticky to any div because of overflow-y: scroll set by default.
