### ISSUE TITLE
Add a toggle switch

### ISSUE THREAD

**Issue by wb9688** [jgthms/bulma#130]
Can you please add a toggle switch? At the moment I'm using the one in [this Codepen](http://codepen.io/anon/pen/PNpbKx)...

**Comment by jgthms** [comment]
I want to keep Bulma very simple. A toggle switch is not a standard UI element. It's too opinionated.

**Comment by acrodrig** [comment]
I do understand the rationale for keeping Bulma simple. However it would be nice maybe as an example outside of core Bulma, for people who are interested in extending it in their own ways. An example from the framework creator shows the inner workings of extensibility points and provides a best-practices example of extensions.

I for one would be very interested in hearing your thoughts about how to go about creating a toggle switch.

**Comment by acidjazz** [comment]
BULMA+

**Comment by jneuendorf** [comment]
Wikiki's documentation URL has changed: https://wikiki.github.io/form/switch/
