### ISSUE TITLE
Column gap and colors not working in React

### ISSUE THREAD

**Issue by narulakeshav** [jgthms/bulma#1300]
This is about **Bulma**.

### Overview of the problem

I believe the problem is related to either the framework or the exact way I'm implementing the framework with my React app.

### Description
I tried to follow directions from the site and this is how I'm using it:
```
yarn add bulma
```
Then I navigated to my main `index.js` file and add:
```js
import 'bulma/css/bulma.css';
import './scss/styles.scss';
```
Then I tried to remove the `import` for bulma and tried the Bulma CDN in my `index.html` file and I got the same result.

### Steps to Reproduce

```jsx
return (
    <div className="column is-center">
      <div className="columns">
        <div className="column is-3 is-info">
          <p className="bd-notification is-info">First column</p>
        </div>
        <div className="column is-3 is-success">
          <p className="bd-notification is-success">Second column</p>
        </div>
        <div className="column is-3 is-warning">
          <p className="bd-notification is-warning">Third column</p>
        </div>
        <div className="column is-3 is-danger">
          <p className="bd-notification is-danger">Fourth column</p>
        </div>
      </div>
    </div>
  );
```

### Expected behavior
![screen shot 2017-10-12 at 9 38 10 am](https://user-images.githubusercontent.com/9926270/31507888-2177a188-af31-11e7-84a5-b4184227c3c0.png)

I copied the code from the docs and that was the example on the site. I inspected the DOM and copied that snippet.

![screen shot 2017-10-12 at 9 47 23 am](https://user-images.githubusercontent.com/9926270/31508287-6bcd9d54-af32-11e7-9793-0489bb3340a7.png)

### Actual behavior
![screen shot 2017-10-12 at 9 38 23 am](https://user-images.githubusercontent.com/9926270/31507892-29f25a56-af31-11e7-9fc3-3459270f9621.png)

The colors are not working properly and the text isn't centered. The `is-danger`, `is-info`, etc. not working either.

Since the colors weren't working, I decided to debug and I added this class in my `scss` file:
```
.column {
  background: red;
}
```
And this is the result I'm getting; columns without the gap and colors.
![screen shot 2017-10-12 at 9 50 27 am](https://user-images.githubusercontent.com/9926270/31508478-0e18dc72-af33-11e7-805e-8a77e8b3ca68.png)

**Comment by jgthms** [comment]
You should use `notification` not `bd-notification` since all `bd-` classes are only meant for the documentation website (`bd` stands for `bulma documentation`).

Also, `column` doesn't support colors like `is-info`. You can use `notification is-info` though.
