### ISSUE TITLE
default font choice destroys SVG performance

### ISSUE THREAD

**Issue by DarkMarmot** [jgthms/bulma#1301]
**Bulma**

*Feature*

### Default Font is not animation friendly

This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**

### Description

Using D3 SVG animations, I noticed adding the default bulma.css dropped my framerate from 60fps to like 5fps.

It made me immediately wary of the framework for no reason.

It turned out that the default font choices are devastatingly bad (on OSX at least) for performance.

I recommend at least adding some SVG friendly fonts -- 

svg { 
    font-family: arial, helvetica, etc.
}

to your defaults

Thanks!

**Comment by jgthms** [comment]
What is the explanation behind this?
