### ISSUE TITLE
Why was the "nav" class deprecated? 

### ISSUE THREAD

**Issue by ThisNameWasTaken** [jgthms/bulma#1302]
Why was the "nav" class deprecated? Using "nav-left" "nav-center" and "nav-right" felt like one of the most readable, easy to understand and versatile ways of building a navbar. What was wrong with it?

Also why did you chose to change the naming to "navbar-start " and "navbar-end" since the other components use the naming convention of "element-left" and "element-right" (eg "level-left", "level-right", "media-left", "media-right") ?

**Comment by jgthms** [comment]
See https://github.com/jgthms/bulma/issues/1276#issuecomment-335397979
