### ISSUE TITLE
跟着官网修改主题，一直报 Argument `$color` of `darken($color, $amount)` must be a color

### ISSUE THREAD

**Issue by gaoting2** [jgthms/bulma#1303]
This is about **Bulma | the Docs**.

### Overview of the problem
跟着官网替换主题色失败

### Steps to Reproduce
1、@import "~bulma/sass/utilities/variables"，这里和官网说的不一样，sass文件里面没有initial-variables文件，
2、代码重现：
@import "~bulma/sass/utilities/variables"

////////////////////////////////////////////////
////////////////////////////////////////////////
// 2. Set your own initial variables
// Update blue
$blue: #72d0eb
// Add pink and its invert
$pink: #ffb3b3
$pink-invert: #fff
// Add a serif family
$family-serif: "Merriweather", "Georgia", serif

// 3. Set the derived variables
// Use the new pink as the primary color
$primary: $pink
$primary-invert: $pink-invert
// Use the existing orange as the danger color
$danger: $orange
// Use the new serif family
$family-primary: $family-serif

// 4. Import the rest of Bulma
@import "~bulma"

然后运行，
错误呈现：Module build failed: 
          background-color: darken($color-invert, 5%)
                           ^
      Argument `$color` of `darken($color, $amount)` must be a color

Backtrace:
	node_modules/bulma/sass/elements/button.sass:154, in function `darken`

**Comment by jgthms** [comment]
The file `variables` is deprecated. Use `initial-variables` or `derived-variables`.

**Comment by gaoting2** [comment]
我提高了我bulma版本后，找到了initial-variables文件，可是新的问题来了，
代码呈现：
// 1. Import the initial variables
@import "~bulma/sass/utilities/initial-variables"

////////////////////////////////////////////////
////////////////////////////////////////////////
// 2. Set your own initial variables
// Update blue
$blue: #72d0eb
// Add pink and its invert
$pink: #ffb3b3
$pink-invert: #fff
// Add a serif family
$family-serif: "Merriweather", "Georgia", serif

// 3. Set the derived variables
// Use the new pink as the primary color
$primary: $pink
$primary-invert: $pink-invert
// Use the existing orange as the danger color
$danger: $orange
// Use the new serif family
$family-primary: $family-serif




// 4. Import the rest of Bulma
@import "~bulma"

错误呈现：
Module build failed: 
@import '~bulma/sass/utilities/variables';
^
      File to import not found or unreadable: ~bulma/sass/utilities/variables.

问题描述：
我点击"~bulma/sass/utilities/initial-variables" 路径可以进入bulma文件，所以路径是对的，可是现在报错称找不到
