### ISSUE TITLE
Header items broken on IE11

### ISSUE THREAD

**Issue by EZTEQ** [jgthms/bulma#131]
On Internet Explorer 11 the header-items are broken. They don't get displayed next to each other.
The 'header-tab' elements work as expected.

![image](https://cloud.githubusercontent.com/assets/1516205/13919555/6de482fe-ef6e-11e5-9af2-5c1a0d94be8b.png)

Bulma Version: v0.0.16 Alpha
Browser Version: IE 11.162.10586.0 (11.0.29) on Windows 10

**Comment by ncksllvn** [comment]
I think this is something with the way it's handling `display: flex` on the `.header-item`.

![image](https://cloud.githubusercontent.com/assets/1915775/13921806/18002ffa-ef50-11e5-9aec-c2177f0887da.png)
