### ISSUE TITLE
Feature: Justify-content and align-items class?

### ISSUE THREAD

**Issue by choonggg** [jgthms/bulma#1315]
Seems like there's already an issue but was left unanswered.

https://github.com/jgthms/bulma/issues/386

Having to manually add `justify-content` and `align-items` manually on containers, I'm wondering if we could have a class for that?

Suggesting to use 
- `is-justified-center`
- `is-justified-start`
- `is-justified-end`
- `is-justified-around`
- `is-justified-between`
- `is-aligned-start`
- `is-aligned-center`
- `is-aligned-end`
- `is-aligned-stretch`
- `is-aligned-baseline`

**Comment by jgthms** [comment]
I'm not sure if it's essential. It goes against the idea of separating content and styles. There are already quite a few helper classes that style directly, but this might lead to having `marign-top-10` classes, and then you're basically styling in the HTML.

**Comment by choonggg** [comment]
true, guess it's best to keep it small without too many utility classes. Thanks! @jgthms

**Comment by AurelianSpodarec** [comment]
Any updates?
