### ISSUE TITLE
Broken link to documentation of older versions within older version's documentation

### ISSUE THREAD

**Issue by alrik** [jgthms/bulma#1321]
### Overview of the problem

This is about the Bulma **Docs**

### Description

Broken link of old version's docs

### Steps to Reproduce

* Open https://versions.bulma.io/0.5.3/ in your browser 
* Click on `All Versions`

### Expected behavior

See older version docs

### Actual behavior

**404 - Error**

---

![bulma v0 5 3 a modern css framework based on flexbox](https://user-images.githubusercontent.com/1223498/31617274-17d43676-b28f-11e7-8019-c0990a9f1c57.png)

**Comment by jgthms** [comment]
https://github.com/jgthms/bulma-versions 😉
