### ISSUE TITLE
[IDEA] What about using SassDoc

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#1322]
Hi,

What do you think about using http://sassdoc.com/ to generate SASS documentation ?
I just discovered this tool and thought it is ideal for projects like Bulma (SASS files are the world of Bulma).

regards,

**Comment by jgthms** [comment]
It only seems to support mixins and functions, which is not really useful for Bulma?

**Comment by Wikiki** [comment]
You're right it seems to only work with function and mixins :-(
