### ISSUE TITLE
Full width columns?

### ISSUE THREAD

**Issue by denn1s** [jgthms/bulma#133]
This is more of an enhancement than an issue, but I'll leave it to your criteria.

I think that a 

```
.column.is-full {
    flex: none;
    width: 100%;
}
```
class would be useful for the grid since columns can be used as rows. I could, for example, sandwich several columns in a small layout table or use a column as a separator in a multiline grid:

```
    <div class="columns is-gapless is-multiline">
      <div class="column is-quarter">4</div>
      <div class="column is-quarter">4</div>
      <div class="column is-quarter">4</div>
      <div class="column is-quarter">4</div>
      <div class="column is-full">12</div>
      <div class="column is-half">6</div>
      <div class="column is-half">6</div>
    </div>
```

Of course, one might be able to do those by closing the columns div so I'm leaving it to discussion. 

Nice job with the framework so far. It's been both fun and useful.

**Comment by jgthms** [comment]
Added
