### ISSUE TITLE
Can't copy code samples from the docs

### ISSUE THREAD

**Issue by Johnathan** [jgthms/bulma#1338]
### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: Version 61.0.3163.100 (Official Build) (64-bit) on OSX

### Description

Not able to copy and paste code examples from the docs. When I highlight the code it shows as below
![Screenshot](https://i.imgur.com/DVC2hIO.png)

When I paste it somewhere it comes out like

```
<
div
class
="card"
>

  
<
div
class
="card-content"
>

    
<
p
class
="title"
>

      “There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.”
    
</
p
>

    
<
p
class
="subtitle"
>

      Jeff Atwood
    
</
p
>

  
</
div
>

  
<
footer
class
="card-footer"
>

    
<
p
class
="card-footer-item"
>

      
<
span
>

        View on 
<
a
href
="https://twitter.com/codinghorror/status/506010907021828096"
>
Twitter
</
a
>

      
</
span
>

    
</
p
>

    
<
p
class
="card-footer-item"
>

      
<
span
>

        Share on 
<
a
href
="#"
>
Facebook
</
a
>

      
</
span
>

    
</
p
>

  
</
footer
>

</
div
>
```

Looks like the syntax highlighting plugin isn't being applied for some reason. I've turned my adblocker off in case it was blocking something. No errors in the console.

**Comment by SimplyThomas** [comment]
Have you tried to press the yellow "Copy" button at the top right of the field you copied from?

**Comment by Johnathan** [comment]
I have yea, that’s what I used to get the above.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SimplyThomas** [comment]
I'm not seeing the same result on Version 62.0.3202.62 (Official Build) (64-bit) on OSX. I don't think it's a browser update issue, though.

What program/application are you trying to paste it into? When I paste into PHPStorm or Sublime Text, it works fine for me.

**Comment by Johnathan** [comment]
PhpStorm, Atom and TextEdit.

After a little more investigating it must be a browser plugin. Copying from
a porn window with no plugins enabled it's completely fine. Can close this
now I suppose. Will update if I find out what the issue is.

Thanks
