### ISSUE TITLE
Progress bar styling is inconsistent in IE11

### ISSUE THREAD

**Issue by rafeememon** [jgthms/bulma#1340]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.0
My **browser** is: IE11
I am sure this issue is **not a duplicate**? Yes

### Description

The progress bar styling in IE11 is inconsistent with that in Chrome and Firefox.  Namely, there is a black line at the end of the progress bar in IE11.

Screenshot from IE11:

![progress_ie](https://user-images.githubusercontent.com/1829450/31777382-cb65b2d6-b4a2-11e7-9e4b-acd883f6f089.png)

Screenshot from Chrome:

![progress_chrome](https://user-images.githubusercontent.com/1829450/31777446-ecf0302a-b4a2-11e7-9669-97e607d99116.png)

### Steps to Reproduce

The following HTML reproduces the issue:

```
<progress class="progress is-success" value="60" max="100">60%</progress>
```

The issue is also visible by viewing the docs at https://bulma.io/documentation/elements/progress/.

### Expected behavior

The progress bar has consistent styling in Chrome, Firefox, and IE.

### Actual behavior

The progress bar has an erroneous black line in IE.

PR incoming to fix the issue.

**Comment by jgthms** [comment]
Merged.

**Comment by rafeememon** [comment]
@jgthms to be clear, this is a different issue than #1333.  I have another PR open for this issue: #1342.  Please take a look!
