### ISSUE TITLE
Question: How to center form with control inside column

### ISSUE THREAD

**Issue by Laraveldeep** [jgthms/bulma#1346]
This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help?

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.0]

### Description

I am trying to center the form with "field has-addons" inside the column but it is aligned left. How to center the form?

### Steps to Reproduce

`<div class="section">

    <div class="columns is-centered">

        <div class="column is-half" style="border: 1px solid black">

            <form class="searchform" action="" method="post">

                <div class="field has-addons">
                    <div class="control">
                        <input class="input" type="text" name="search" value="" placeholder="Search">
                    </div>

                    <div class="control">
                        <div class="select">
                            <select>
                                // loop from district data
                                <option value="">All</option>
                                <option value="">XXXX</option>
                            </select>
                        </div>
                    </div>

                    <div class="control">
                        <button class="button is-primary" type="submit" name="button">Search</button>
                    </div>
                </div>

            </form>

        </div>

    </div>
</div>
`

### Expected behavior

Form supposed to be centered inside column.

### Actual behavior

It is not centered.
Also is there a way to extend the length of input for joined elements like this?

![form_centering](https://user-images.githubusercontent.com/22372048/31818391-a49c1eae-b5b7-11e7-8c69-5b7cbd70f91c.jpg)

**Comment by Laraveldeep** [comment]
Sorry `is-expanded` on input solved the problem.

**Comment by rocchidavide** [comment]
Where do you put is-expanded? I am in the same your condition but still not working

**Comment by snaphuman** [comment]
In the case that your field has addons yo should use the class selector `field has-addons has-addons-centered`.

**Comment by icicaf** [comment]
Gracias it is work...!
