### ISSUE TITLE
Feature, can you make the colors modifier available everywhere ?

### ISSUE THREAD

**Issue by nuruddinXbadawi** [jgthms/bulma#1348]
What do you think if you make the colors like "is-primary" used in any item to change color?

**Comment by jgthms** [comment]
Which components are you thinking about?

**Comment by nuruddinXbadawi** [comment]
HTML tag like <a> <p> ...

**Comment by jgthms** [comment]
Just use typography color helpers: https://bulma.io/documentation/modifiers/typography-helpers/#colors
