### ISSUE TITLE
Navbar burger color doesn't follow the navbar original assigned color looking weird

### ISSUE THREAD

**Issue by jfcalvo** [jgthms/bulma#1350]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.0
My **browser** is: Google Chrome v.61.0.3163.100 and Safari v.11.0.
I am sure this issue is **not a duplicate**? Not sure, there are other two issues related with navbar color but I think are not directly related with this one. The two issues are: https://github.com/jgthms/bulma/issues/1265 https://github.com/jgthms/bulma/issues/753

### Description

Using `is-link` class in a navbar when the burger is showed the color used is white looking strange and not following the original color assigned to the navbar:

![wrong](https://user-images.githubusercontent.com/446497/31850486-bafd898a-b652-11e7-8f71-4c4f877a3960.png)

I'm not sure if this is a bug or a feature but I'm my own opinion this should be change to show a color respecting the navbar color (including changing color to the bars too), something like the following:

![fine](https://user-images.githubusercontent.com/446497/31850488-cff959fe-b652-11e7-9878-533c163d0645.png)

### Steps to Reproduce

Use a navbar with `is-link` (but I think the problem remains is for all the rest of classes) and resize screen until burger is showed.

### Expected behavior

As showed in the second image.

### Actual behavior

As showed in the first image.

**Comment by jnsdrtlf** [comment]
Do you want to add the `is-link` class to the `navbar` like this:
```html
<nav class="navbar is-link">
. . .
</nav>

Or on an other element? I don't understand why you want to do that.

**Comment by jfcalvo** [comment]
> Do you want to add the is-link class to the navbar like this:

Sure, exactly like that, only to change the color as mentioned in Bulma documentation. I'm only trying to notice that the generated burger doesn't has the correct color too.

**Comment by jnsdrtlf** [comment]
> change the color as mentioned in Bulma documentation

Sorry, my fault. I've looked into it and found what you've meant.

I've just tried it in
 - Chrome 62.0.3202.62 (64-Bit) 
 - Firefox 57.0b11 (64-Bit) 
 - Safari 11.0 (12604.1.38.1.7)  

and none of them showed a similar result. Can you share your code?

**Comment by jfcalvo** [comment]
I'm not doing anything special tough:

```html
<nav class="navbar is-primary is-link has-shadow">
  <div class="navbar-brand">
    <a class="navbar-item is-size-4" href="/">
      <span class="icon">
        <i class="fa fa-dot-circle-o"></i>
      </span>
      APP NAME
    </a>

    <!-- Navbar buger necessary to show menu in mobile -->
    <button class="button navbar-burger" data-target="navMenu">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
  <div class="navbar-menu" id="navMenu">
    <div class="navbar-start">
      <a class="navbar-item is-active" href="/events">Events</a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          User name
          <img class="avatar rounded" src="https://www.gravatar.com/avatar/2ba0f30a45158e350a386d4aa76a5395">
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/settings/auth">Settings</a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="#">Logout</a>
        </div>
      </div>
    </div>
  </div>
</nav>
```

For the JS I'm using the snippet provided in Bulma docs:

```javascript
document.addEventListener('DOMContentLoaded', function () {
  // Get all "navbar-burger" elements
  var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach(function ($el) {
      $el.addEventListener('click', function () {

        // Get the target from the "data-target" attribute
        var target = $el.dataset.target;
        var $target = document.getElementById(target);

        // Toggle the class on both the "navbar-burger" and the "navbar-menu"
        $el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }
});
```

And still showing the white button instead of the blue one.

**Comment by matthewdarwin** [comment]
I ended overwriting it to make it work: 

.navbar-burger:hover
        background-color: $blue

.navbar-burger.burger.is-active
        background-color: $blue
        span
                background-color: $white

.navbar-burger
        span
                background-color: $white

**Comment by axah** [comment]
replace
`<button class="button navbar-burger" data-target="navMenu">`
with
` <div class="navbar-burger" data-target="navMenu">`

**Comment by jfcalvo** [comment]
I think that @axah solution is the correct one. Thanks to all.
