### ISSUE TITLE
Question: how to split screen in two columns with one of them scrollable?

### ISSUE THREAD

**Issue by jfcalvo** [jgthms/bulma#1351]
My idea is to split the screen in two different columns (full width and height) so the column in the left occupy the half of the screen and the column in the right occupy the other half.

The column in the left should show some static content (a logo or something like that) and the column in the right should be scrollable to show content bigger than the screen.

Something like the following:

![mockup](https://user-images.githubusercontent.com/446497/31850641-0f615cd8-b656-11e7-92c1-955ba8fa7c08.png)

I have tried to do something like this with Bulma (v.0.6.0) in a clean and elegant way and I have only failed.

Does anyone have any idea how this can be done?

Thanks in advance.

**Comment by jgthms** [comment]
Try the variable gap columns and set it to zero. For the full height, try using something like height: 100vh with overflow: auto.

**Comment by richardkmichael** [comment]
@jfcalvo I'm working on this exact layout with bulma today as well. :-)  I'm not sure if there are bulma helpers for the centring (it doesn't seem so for `.column`).

You'll have to experiment carefully as you make this layout more complex (for example if you perhaps add a `.container`, etc.) because AFAIK in block layout `overflow: auto;` needs height on the parent, and flex layout (`display: flex;`) can change interpretation of properties.

```html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="bulma.css" />
  </head>

  <body>
    <style>
      html {
        height: 100vh;
        width: 100vw;
      }

      body {
        height: 100%;
        width: 100%;
      }

      .columns {
        height: 100%;
      }

      .column.no-scroll {
        overflow: auto;
      }

      .column.logo {
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .placeholder {
        background-color: cyan;
        margin: 2rem;
        height: 250px;
      }
    </style>

    <div class="columns">

      <div class="column logo">
        <p>This is text.</p>
      </div>

      <div class="column no-scroll">
        <div class="placeholder">
        </div>
        <div class="placeholder">
        </div>
        <div class="placeholder">
        </div>
        <div class="placeholder">
        </div>
      </div>

    </div>

  </body>
</html>
```

**Comment by chhuang** [comment]
This is how I've done it: https://jsbin.com/mevawolejo/edit?html,css,output

```
<div class="wrap">
  <div class="left">
    <h1>Not scrollable content</h1>
  </div>
  <div class="right">
    <div style="height: 1800px;">
      Very long content
    </div>
  </div>
</div>

.wrap {
  display: flex;
  min-height: 100vh;
}

.left {
  background: red;
  flex-basis: 20%;
}

.right {
  background: green;
  flex-basis: 80%;
  
  height: 100vh; 
  overflow: auto;
}
```

**Comment by jfcalvo** [comment]
I have solved it using @richardkmichael solution and adding some additional styles to the columns:

```html
<div class="columns is-gapless" style="height: 100%; margin-top: 0; margin-bottom: 0;">
  <div class="column is-5" style="min-height: 500px;">
    <!-- First column content -->
  </div>

  <div class="column" style="overflow: auto;">
    <!-- Second column content -->
  </div>
</div>
```
Thanks to everybody.

**Comment by tweed** [comment]
Sorry for not knowing.
Can anyone tell me how to set this up without affecting the entire HTML page? (one-page sites)
My ignorance is how to achieve this in the most elegant simple/flexible way  - while not having 
the CSS alter either bulma's CSS, or the forcing the entire page to adhere to this code.

`html {
        height: 100vh;
        width: 100vw;
      }

      body {
        height: 100%;
        width: 100%;
      }`

**Comment by dhirajbajaj** [comment]
This works too. Scrolling is default; no need of overflow, only you need to make sure the leftarea/sidebar remains sticky; 

```
<div class="columns">
  <div class="column is-one-fifth" style="height:90vh; position: sticky; top: 3.2rem;">
    <!-- sticky sidebar in my case -->
  </div>

  <div class="column">
    <!-- Second column content -->
  </div>
</div>
```

**Comment by theoutlander** [comment]
@dhirajbajaj Thanks! How did you handle responsiveness for this? Did you disable this one for mobile and show a different column instead?
