### ISSUE TITLE
First navbar-item should align left

### ISSUE THREAD

**Issue by clint326** [jgthms/bulma#1352]
This is about **Bulma**.

Not sure if this is a bug in Bulma, a feature request, or if I need help :-)

### Overview of the problem

This is about the Bulma **CSS framework**.

I'm using Bulma **version** 0.6.0, and Firefox 56.0 (64-bit).

### Description

I think most users would like the first item in a navbar to be aligned left so it lines up with the rest of the items on the page. This should be the default action or at least an option using a CSS class.

Currently, when using text links in a navbar-item, all links are centered within the nav-bar item. This results in a visual lack of alignment with other items on the page as seen below: 

![image](https://user-images.githubusercontent.com/857617/31851320-0cd20be8-b629-11e7-8da5-0b74e422a6f4.png)

### Steps to Reproduce

1. Create a page with a navbar using Bulma 0.6.0 and the navbar class
2. Add the first item to the navbar using the navbar-brand and navbar-item classes
3. Add any text below the navbar
4. Notice that the left edge of the first navbar item does not align with the left edge of the other items on the page.

### Expected behavior

I would expect there would be a way to align the left edges of the first navbar item with the left edge of other items on the page.

### Actual behavior

The left edge of the first navbar item does not align with the left edge of other items on the page because the text of the first navbar-item is centered within its navbar-item.

**Comment by jgthms** [comment]
The navbar brand does move left on desktop. It doesn’t on touch screens otherwise the text would be touching the edges.

See #1347

**Comment by clint326** [comment]
The screenshot above was taken on a desktop. Not sure what I'm doing wrong that the items don't align on left edge.

**Comment by clint326** [comment]
Nevermind, I figured it out. The order of the container and the navbar divs matters. This works:

`
<nav class="container">
  <div class="navbar">
    <div class="navbar-brand">
      <a class="navbar-item" href="#">APPNAME</a>
      <button class="button navbar-burger">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </div>
</nav>
`
