### ISSUE TITLE
Warning --columnGap ! Lack of consistency in var...

### ISSUE THREAD

**Issue by jimblue** [jgthms/bulma#1355]
This is about **Bulma**.

It's a bug, but not in browser

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.0]
My **browser** is: google chrome
This is a **Sass** issue: I'm using version [3.5.2]
I am sure this issue is **not a duplicate*#

### Description

While trying to compile a custom version of Bulma by following the documentation step I'm getting warning in the console about `--columnGap` in `columns.sass`. This append because this var is not scoped to the top-level `:root`.

My question is why you're not using classic SASS variable here. This place using a different writing for var in all Bulma...

Can you replace `--columnGap` with `$columnGap` this will work the same.

Thank you

**Comment by jgthms** [comment]
It’s a CSS variable. It makes it easier to update the variable value for the variable gap feature. 

It shouldn’t be scoped to the root level. I believe there was another issue mentioning his, but it’s not really an issue since CSS variables are supposed to be used that way.

**Comment by jimblue** [comment]
Hi @jgthms and thank for answering that fast!

I know this is a CSS variable, it's even more the only one in all Bulma. That's why I was asking...

Keep everything working with the same way is always better.
Actually without going inside Bulma architecture it's impossible to know about this CSS variable in initial-variables as root. Also it's not document.

I hope you understand my point 😄

**Comment by jimblue** [comment]
The warning happen in a really classic configuration (webpack - sass - postcss - cssnext - cssnano).

HEre is the log message:

```bash
 warning  in ./src/scss/build/global_style.scss

(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/jim/Sites/jimblue/node_modules/bulma/sass/grid/columns.sass:328:6: Custom property ignored: not scoped to the top-level :root element (.columns.is-variable.is-5 { ... --columnGap: ... })
```
So I'm was wondering what's your configuration, do you have this warning too?
(it's pretty annoying when refreshing)

**Comment by jimblue** [comment]
As you can see it's a lot of warning, pretty disturbing !

<img width="1920" alt="screen shot 2017-10-23 at 15 58 50" src="https://user-images.githubusercontent.com/10623367/31893213-4820fac2-b80b-11e7-9004-8fcfbade7b87.png">

**Comment by jimblue** [comment]
Finally found a way to hide the warning, all good. tks

**Comment by juanpmarin** [comment]
Hi, @jimblue how do you hide the warning ?

**Comment by jimblue** [comment]
Really simplte @jgthms !

In your webpack-config you must look for cssnext plugin and add this option:

```js
cssnext({
  features: {
    customProperties: {
      warnings: false
    }
  }
})
```
