### ISSUE TITLE
bower is deprecated

### ISSUE THREAD

**Issue by jnsdrtlf** [jgthms/bulma#1359]
This is about **the Docs**.

### Problem
Bower is still maintained, however the team behind bower recommends switching in their [blog](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

### Solution
I would suggest adding a notice to the documentation that it is suggested to switch from bower to `yarn` or `webpack`.

**Comment by jnsdrtlf** [comment]
I just noticed, that the docs don't include bower anymore. The `README.md` still does.

**Comment by jgthms** [comment]
Team I was thinking of removing bower but I don’t want to penalise people who still do.

Nevertheless I recommend npm and yarn on the readme and website already.

I’ll probably remove bower when it’s no longer working at all.
