### ISSUE TITLE
Problem with adding more padding to elements with .button class (WITH SOLUTION)

### ISSUE THREAD

**Issue by hunter-isaiah96** [jgthms/bulma#1361]
I am on the latest version of Bulma using sass.

I found a bug where if you add padding to one of these elements the height remains fixed but will expand the width making the text look uncentered.
I figured out that it is due to the height property of .button being set to 2.25em.
The way I fixed the issue was by setting the height property of .button to auto;

**Comment by jgthms** [comment]
It’s not really a bug since it’s how it’s supposed to behave. You can however update the button height variable.
