### ISSUE TITLE
[mobile] Modal closing buttons displayed oddly on modal cards

### ISSUE THREAD

**Issue by alea12** [jgthms/bulma#1367]
This is about **Bulma**.
There seems to be a bug on displaying closing mark (x) with modal cards, in mobile environments.

### Overview of the problem

This is about the Bulma **CSS framework**.
I'm using Bulma **version** `6.0.0`.
My **browser** is: Chrome `61.0` on iOS `11.0.2`.

### Description

Modal closing buttons (x) displayed on the top right corner of the modal **cards** are displayed oddly.

### Steps to Reproduce

It is reproducible with the official doc, displayed in iOS environments.
[Modal \| Bulma: a modern CSS framework based on Flexbox](https://bulma.io/documentation/components/modal/)

### Expected behavior

Closing buttons within modal cards being displayed like this:

![screenshot 2017-10-25 13 10 00](https://user-images.githubusercontent.com/1287191/31980205-dcd00c0a-b985-11e7-971c-96b61cb95a12.png)

### Actual behavior

Closing buttons being displayed oddly:

* PNG

![screenshot 2017-10-25 13 13 06](https://user-images.githubusercontent.com/1287191/31980264-4b0df1fa-b986-11e7-932a-3781fd6f5489.png)

* GIF

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1287191/31980254-2f45fe40-b986-11e7-8a2b-f6713fe2993d.gif)

**Comment by jgthms** [comment]
It’s been solved this week and will go out in `0.6.1`!

**Comment by alea12** [comment]
Sweet, thanks!

**Comment by drdan18** [comment]
I am getting this problem.  I am using bulma.io v0.7.0.  Is there something I need to do to prevent this?
