### ISSUE TITLE
Button properties (is-centered ...)

### ISSUE THREAD

**Issue by edmBernard** [jgthms/bulma#1368]
This is about **Bulma and the Docs**.

There miss properties on button class

### Overview of the problem

The `is-centered`  option on button class don't work with the regular `bulma/css/bulma.css`
It is describe in the doc here https://bulma.io/documentation/elements/button/#list-of-buttons

After a small css inspection lots of button properties miss between the css use in doc website and the regular bulma.css
for example the following button properties is missing in regular css.
```
.buttons.is-centered {
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
}
```

**Comment by jgthms** [comment]
It's tagged as `0.6.1` and coming soon! 😉
