### ISSUE TITLE
Add a contributing.md file with information regarding contributing to the project

### ISSUE THREAD

**Issue by julianorafael** [jgthms/bulma#137]
I'm new to contributing to open source projects and it would be appreciated if there were a file with instructions on how to contribute to the project. Things like should I make a branch for the feature or how should I name the commit are really useful.

**Comment by jgthms** [comment]
Yeah I'm gonna add issue an PR templates, and some guidelines.

Best thing would be to run some automated tests as well but I'm not sure how to set it up.
