### ISSUE TITLE
bulma npm package is not last version

### ISSUE THREAD

**Issue by jimblue** [jgthms/bulma#1371]
This is about Bulma.
This is about bug.
This is not a browser bug.

I'm using Bulma version [6.0.0]

Description

The new `buttons` class found in the Bulma documentation corresponding to this class:

https://github.com/jgthms/bulma/blob/8792984f8e5956ad74aab2db51e5b765d6e6ab0a/sass/elements/button.sass#L203

can not be used while using SASS version of Bulma as the npm package seems older.

**Comment by jgthms** [comment]
Coming soon 😉

**Comment by jimblue** [comment]
@jgthms haha ok tks 😄
