### ISSUE TITLE
Ability to disable/change "touch" breakpoint for navbar-menu

### ISSUE THREAD

**Issue by mofahead** [jgthms/bulma#1377]
_This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.0].
My **browser** is Chrome 62 (OSX).
I am sure this issue is **not a duplicate**._

Currently navbar-menu seems to disappear/collapse when width is less than 1024px. Even with quite a few items in the navbar, there is still plenty of space for all the elements at that breakpoint, so it's pretty annoying when the navbar needlessly collapses.

A quick mockup in Bootstrap 4 didn't appear to have this issue, but I'd prefer to use Bulma. ;)

How about a way to change the breakpoint to something smaller, or even disable the collapsing behavior entirely (for a more desktop oriented site?) Or have the nav-menu collapse when there's actually no more room, rather than at a hardcoded width?

Also, is there any workaround for now?

Thanks for the work on Bulma!  it's been a joy to work with, especially considering it's early days.

**Comment by jgthms** [comment]
#1042

**Comment by Ellarddekoeijer** [comment]
"Also, is there any workaround for now?"
