### ISSUE TITLE
where is 0.6.1 version ?

### ISSUE THREAD

**Issue by nuruddinXbadawi** [jgthms/bulma#1382]

**Comment by jgthms** [comment]
Coming soon!

**Comment by nuruddinXbadawi** [comment]
but I don't understand why you add 0.6.1 new features in the documentation, and the version not released yet?

**Comment by VizuaaLOG** [comment]
It's because of how Github pages work. The docs are within your master branch so as you add documentation for unreleased features it updates the live documentation. Don't know if Github has a way around this but tbh I don't mind. If you want the latest feature just use the master branch :)

**Comment by nuruddinXbadawi** [comment]
Thanks for the clarification. 👍
