### ISSUE TITLE
Title/Subtitle modifiers

### ISSUE THREAD

**Issue by mgesmundo** [jgthms/bulma#1388]
This is a question/suggestion about **Bulma**.

### Overview of the problem

 This is about the Bulma **CSS framework** 

### Description

First of all thank you for your awesome work! I've a simple question about the title modifiers. I see that Title and Subtitle can be modified using is-1, is-2, etc. modifiers. Why you do not use is-size-1, is-size-2, etc. like in the typography modifiers?

All the best!

**Comment by jgthms** [comment]
They were defined before the helpers actually. It’s simply a shortcut!
