### ISSUE TITLE
What's the recommended way to set vertical spacing between columns when in Mobile size?

### ISSUE THREAD

**Issue by lukecwilliams** [jgthms/bulma#1392]
Chrome Latest
 Yes

### Description

The columns mechanic works very well, I'm impressed with Bulma.

I need to have side-by-side columns that stack with very little padding when vertical.  So far Bulma seems to always add significant vertical space, even with `is-0` or `is-1`.  What's the recommended way to reduce the vertical gaps?

Even `is-gapless` does not eliminate the vertical gaps; and we have different needs for the vertical gaps when the columns are stacked vertically, than for the horizontal gaps when columns are laid out horizontally.

### Steps to Reproduce

1. Add a `columns` object with `is-gapless` and two `column` children.
2. Reduce size of screen so columns stack vertically

### Expected behavior

Be able to change vertical gap between "column" items

### Actual behavior

Cannot find a way to change this gap.  So far we are just hacking around it by setting something like "marginTop: -25" on every column item.

Thank you!

**Comment by lukecwilliams** [comment]
I believe the issue here was that I was applying `subtitle` formatting, which was causing unwanted vertical gap.

`is-gapless` and `is-0` are working great.

**Comment by clockwiser** [comment]
There are spacing helpers. For example, my-3 means vertically set margin to value 3 for both top and bottom.

https://bulma.io/documentation/helpers/spacing-helpers/

Use case: 
           <div class='columns is-centered my-3'>
           </div>
