### ISSUE TITLE
Button active background color

### ISSUE THREAD

**Issue by focussing** [jgthms/bulma#1397]
As I click a button, the color changes for example from white to black.
How can I change the background-color when clicked?

**Comment by jgthms** [comment]
I’m not sure what you mean. Any screenshots?

**Comment by focussing** [comment]
![schermafbeelding 2017-11-01 om 10 17 01](https://user-images.githubusercontent.com/26736152/32268096-dea6b426-beed-11e7-9335-7626f1ce0614.png)

like this; when clicked, I would like to have the color changed to black, and the border-color removed

**Comment by alzearafat** [comment]
Can you share your button CSS codes?

You can use `:active` selector. Please try : 
```
.my-button-class:active {
  background-color: #000000;
  border: none;
}

@focussing
