### ISSUE TITLE
No Search option on the site ? No breakpoint defintion  ?

### ISSUE THREAD

**Issue by Epistol** [jgthms/bulma#1403]
This is about  the Docs / Feature

Hey, I've been using Bulma for a while and, out of the github, the website looks great but, how does it haven't a search bar yet ? 

Second problem : the doc is great but there's some breakpoint that are not mentionned as the .json does in github, is it possible to explain them in the doc ? 

Thank's :)

**Comment by jgthms** [comment]
Which breakpoint are you talking about?

**Comment by InstanceOfMichael** [comment]
Search would be great!

**Comment by Epistol** [comment]
The breakpoints in :  bulma/docs/_data/breakpoints.json
They are not mentioned anywhere :/

**Comment by jgthms** [comment]
The breakpoints are used every time `site.data.breakpoints.` is called within the documentation website.
