### ISSUE TITLE
multi-level menu

### ISSUE THREAD

**Issue by dailycommit** [jgthms/bulma#1404]
Does Bulma have multi-level menu support for navbar ?

**Comment by jgthms** [comment]
No it doesn't. I don't think it will, but it could be built as an extension!

**Comment by TheYakuza** [comment]
is there some extension?

**Comment by sakthig** [comment]
@TheYakuza  this may help https://codepen.io/sakthig/pen/RvwVYM?editors=1100

**Comment by TheYakuza** [comment]
> @TheYakuza @dailycommit this may help https://codepen.io/sakthig/pen/RvwVYM?editors=1100

nice!! it's works for me this way

**Comment by zzeni** [comment]
One alternative implementation which has a vertical expansion and works nicer on mobile devices (small viewport size):
https://codepen.io/jenie/pen/mdrzpdG

**Comment by phreda4** [comment]
I make this code for make a submenu item, 
`
     <p class="navbar-item">
<div class="dropdown" onclick="$(this).toggleClass('is-active');">
  <div class="dropdown-trigger mx-2">
	Submenu 1&nbsp;&nbsp;&nbsp;<i class="fas fa-angle-right"></i>
  </div>
  <div class="dropdown-menu" role="menu" style="top:-15px;margin-left:100%;">
    <div class="dropdown-content">
      <a href="#" class="dropdown-item">coso 2</a>
      <a href="#" class="dropdown-item">coso</a>
      <a href="#" class="dropdown-item">cosito</a>
    </div>
  </div>
</div>
	</p>
`

**Comment by Khvoretskiy** [comment]
Little bit minimized and improved version if @sakthig's pin:

[https://codepen.io/khvoretskiy/pen/jOVEYeO]

**Comment by lublak** [comment]
My own solution but it is based on navbar-dropdown: https://codepen.io/lublak/pen/mdmEdKN
Can probably be optimised.

**Comment by katkins99** [comment]
mine isn't interactive but looks neat on both mobile and desktop -> https://codepen.io/katkins99/pen/jOZJOYW
