### ISSUE TITLE
Feature: Flow text

### ISSUE THREAD

**Issue by iplanwebsites** [jgthms/bulma#1405]
This is about the Bulma **CSS framework** - feature request.

A flow-text typography helper would be very helpful for readability.
It has very simple logic in Sass.

Example: http://materializecss.com/typography.html

**Comment by jgthms** [comment]
Just had a look. There’s like 22 breakpoints! This is an overkill. I want to stick to the 5 breakpoints we have. You can already resize the text with the responsive typography helpers.
