### ISSUE TITLE
Following "Setup your Custom Colors" instructions in docs leads to compilation error

### ISSUE THREAD

**Issue by mofahead** [jgthms/bulma#1406]
On the [customize page](https://bulma.io/documentation/overview/customize/) of docs, in the _Setup your Custom Colors_ example, there is this line:

`$colors: map-merge($colors, $addColors)`

However, this raises a compilation error since $colors is undefined (the only import at this point is the _initial-variables_ file). Is there another import statement I'm missing? I tried importing _derived-variables_ as well but that got me into some other trouble.

**Comment by Fival85** [comment]
Hello,

i have the same problem. I want to have my own color definitions like this:
`// 1. Import the initial variables
@import "sass/utilities/initial-variables"
@import "sass/utilities/derived-variables"
$modal-content-margin-mobile: 2px !default
$modal-content-spacing-mobile: 2px !default
$modal-content-spacing-tablet: 5px !default


$green2: #94D42B
$green2-invert: #1D2A08
$addColors: ( "green2":($green2, $green2-invert))
$colors: map-merge($colors, $addColors)

$primary: $green2
$primary: $green
$info: $green
// 5. Import the rest of Bulma
@import "bulma"`

So, but when i "compile" the sass files with:
`sass-convert shopi_green.sass shopi_green.scss
sass shopi_green.scss shopi_green.css
`
the following error appears:
`Error: $color: "findColorInvert(#00d1b2)" is not a color for `darken'
        on line 134 of sass/elements/button.sass
        from line 4 of sass/elements/_all.sass
        from line 5 of bulma.sass
        from line 19 of shopi_green.scss
  Use --trace for backtrace.`

I don't use the color "#00d1b2"...

**Comment by Fival85** [comment]
One Solutation is to set the $primary and $info color directly like here:
`// 1. Import the initial variables
@import "sass/utilities/initial-variables"
$modal-content-margin-mobile: 2px !default
$modal-content-spacing-mobile: 2px !default
$modal-content-spacing-tablet: 5px !default
$primary: #F14F2B
$primary-invert: #782715
$info: $green
// 5. Import the rest of Bulma
@import "bulma"`

But this isn't a solution for every requirement

**Comment by jgthms** [comment]
#1409

**Comment by wishinghand** [comment]
Following the docs in 0.6.2 still results in a Sass compilation error.

When trying to add custom colors I added this block of code before importing Bulma:

```
// Setup your Custom Colors
$linkedin: #0077b5;
$linkedin-invert: findColorInvert($linkedin);
$google: #db4437;
$google-invert: findColorInvert($google);
$facebook: #4267B2;
$facebook-invert: findColorInvert($facebook);

// Add new color variables to the color map.
@import "~bulma/sass/utilities/initial-variables.sass";
@import "~bulma/sass/utilities/functions.sass";
@import "~bulma/sass/utilities/derived-variables.sass";
$addColors: ( "google":($google, $google-invert), "linkedin": ($linkedin, $linkedin-invert), "facebook": ($facebook, $facebook-invert));
$colors: map-merge($colors, $addColors);
```

And I get this error:

```
ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed:
          background-color: darken($color-invert, 5%)
                           ^
      Argument `$color` of `darken($color, $amount)` must be a color
```

**Comment by karanrajpal14** [comment]
@wishinghand were you able to resolve the issue? I seem to be facing it now despite following all the instructions on the website.

**Comment by ajay481** [comment]
Yeh me too. So very keen to hear from anyone that's sorted this.

**Comment by wishinghand** [comment]
Oof sorry, I don't recall if I resolved this or not. I do know that in other projects, having `node-sass` and `sass-loader` installed resolved some of the sass issues I was having, but I don't recall if that applied here.

**Comment by ajay481** [comment]
So for me, I realised this was a late coding school boy error...

Using the code sample above as an example:
```
// Setup your Custom Colors
$linkedin: #0077b5;
$linkedin-invert: findColorInvert($linkedin);
$google: #db4437;
$google-invert: findColorInvert($google);
$facebook: #4267B2;
$facebook-invert: findColorInvert($facebook);

// Add new color variables to the color map.
@import "~bulma/sass/utilities/initial-variables.sass";
@import "~bulma/sass/utilities/functions.sass";
@import "~bulma/sass/utilities/derived-variables.sass";
$addColors: ( "google":($google, $google-invert), "linkedin": ($linkedin, $linkedin-invert), "facebook": ($facebook, $facebook-invert));
$colors: map-merge($colors, $addColors);
```

The `$linkedin-invert` variable was being set to the string **findColorInvert($linkedin)** . This is  is simply because `@import "~bulma/sass/utilities/functions.sass";` needs to be called _before_ using the findColorInvert function and not _after_ as is the case in this example.
