### ISSUE TITLE
using word-break: break-word

### ISSUE THREAD

**Issue by jbailey4** [jgthms/bulma#1410]
This is about **Bulma **.

This is a question about a potential browser bug.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

The `.title` and `.subtitle` classes were given a `word-break: break-word` styling, https://github.com/jgthms/bulma/commit/b7fb0b9ed37a802244dd36eb0686cb57de5dc2d6#diff-ee20aa3c8228e5783e0890fcdd0f3768R5

Looking at the possible [valid values](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#Values) for `word-wrap`, `break-word` is an [unofficial value supported only by Safari, Chrome, and other Webkit/Blink browsers](https://caniuse.com/#search=word-break).

Any reason for choosing `break-word`? I believe using `word-break: break-all` would accomplish the same thing and cover more browsers.

**Comment by jgthms** [comment]
`break-word` prevents cutting a word at any location. `break-all` would just put a line break between any 2 characters, which is quite useless.

It's not a critical feature. If `break-word` is available, I'd rather use it. If it's not there, then I'd rather keep the word uncut.
