### ISSUE TITLE
Automatic wrap doesn't work when "has-addons" is added

### ISSUE THREAD

**Issue by tanhs** [jgthms/bulma#1411]
This is about Bulma.

### Overview of the problem
This is about the Bulma CSS framework

I'm using Bulma version [0.6.0]

### Description
The "has-addons" does not push the input to the next line when size change to mobile screen size.
If I take away the "has-addons" it works again.

    <div class="field is-horizontal is-pulled-left">
                  <div class="field-body">
                    <div class="field-label is-normal">
                      <label class="label">DOB</label>
                    </div>
                    <div class="field has-addons">
                      <p class="control">
                        <input class="input" type="text" size="15" placeholder="DOB" disabled v-model="dob">
                      </p>
                      <p class="control">
                        <a class="button is-static">@{{ age }}</a>
                      </p>
                    </div>    

### Steps to Reproduce

1. add in the "has-addons" into <div class="field has-addons">, it doesn't push input to next
2. remove the "has-addons", it will drop to next line

### Expected behavior
It should look like this
DOB
2017-01-09 1yrs2mth

### Actual behavior
DOB  2017-01-09 1yrs2mth

**Comment by jgthms** [comment]
Yes the `has-addons` keeps everything on a single line. That's the expected behavior.
