### ISSUE TITLE
docs jekyll Invalid argument @ rb_sysopen error on windows

### ISSUE THREAD

**Issue by ArashAlikhani** [jgthms/bulma#1412]
This is about **the Docs**.
I need help

### Overview of the problem

This is about the Bulma **Docs**

### Description

`Invalid argument @ rb_sysopen` error after trying to serve with jekyll 

### Steps to Reproduce

I installed ruby ruby 2.4.2p198 (2017-09-14 revision 59899) on windows 10 and after installing jekyll (gem install jekyll) and changing docs configuration according to README try to run it with
`jekyll serve --incremental --config _config.local.yml`

### Expected behavior

I expected it to compile and  be able to serve it on http://localhost:4000/

### Actual behavior

but get the following error
```
Configuration file: _config.local.yml
            Source: D:/GITHUB/bulma/docs
       Destination: D:/GITHUB/bulma/docs/_site
 Incremental build: enabled
      Generating...
jekyll 3.6.2 | Error:  Invalid argument @ rb_sysopen - D:/GITHUB/bulma/docs/images/expo/br?jula-tur?stica-1344x840.jpg
```

**Comment by jgthms** [comment]
Did you create the file `_config.local.yml`?

**Comment by ArashAlikhani** [comment]
yes, and only changed url value to `localhost:4000`.

this is content of my `_config.local.yml` file:

```

# Meta

title:         "Bulma: a modern CSS framework based on Flexbox"
description:   "Bulma is an open source CSS framework based on Flexbox and built with Sass. It's 100% responsive, fully modular, and available for free."
env:           "production"

# Build

markdown:      kramdown
permalink:     pretty
url:           http://localhost:4000
exclude:       ['icons', 'node_modules', 'templates', '.babelrc', 'bulma-docs.sass', 'docker-compose.yml', 'package.json', 'yarn.lock']

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

# Variables

documentation: "/documentation/overview/start/"
download:      https://github.com/jgthms/bulma/releases/download/0.6.0/bulma-0.6.0.zip
github:        https://github.com/jgthms/bulma
twitter:       https://twitter.com/jgthms
version:       0.6.0
vernum:        60

```

**Comment by jgthms** [comment]
What happens if you just run `jekyll serve`?

**Comment by ArashAlikhani** [comment]
same error when trying with `git bash` , `powershell` and `cmd` :
```
$ jekyll serve                                                                                                        
Configuration file: D:/GITHUB/bulma/docs/_config.yml                                                                  
            Source: D:/GITHUB/bulma/docs                                                                              
       Destination: D:/GITHUB/bulma/docs/_site                                                                        
 Incremental build: disabled. Enable with --incremental                                                               
      Generating...                                                                                                   
jekyll 3.6.2 | Error:  Invalid argument @ rb_sysopen - D:/GITHUB/bulma/docs/images/expo/br?jula-tur?stica-1344x840.jpg
```

**Comment by urin** [comment]
I could avoid it after I removed 2 files from `docs/images/expo`.
 - brújula-turística-672x420.jpg
 - brújula-turística-1344x840.jpg

**Comment by nbarbettini** [comment]
This seems to happen when the file name/path contains characters that are invalid on Windows.

In my case, there was a stray quote `"` that shouldn't have been in the file path.

**Comment by ArashAlikhani** [comment]
I tried @urin solution and my problem solved, thanks 👍

**Comment by sheikhzaid** [comment]
I am having the same error while serving locally, I tried @urin method of deleting the file but when i served again it got generated by itself in "_site" folder


jekyll 3.6.2 | Error:  Invalid argument @ rb_sysopen - C:/xampp/htdocs/Mysite/_site/wp-content/themes/bic-custom/assets/jplayer/jplayer.min.js?ver=12.2

**Comment by hjavadish** [comment]
As I prefer to use Unicode file name for SEO issues, I migrated to Linux environment and the problem was solved there.

**Comment by dasarpai** [comment]
I deleted all the files of _site folder and run the bundle command and then this problem is resolved for me.
