### ISSUE TITLE
$navbar-background-color does not work after upgrading from 0.5.2 to 0.6.0

### ISSUE THREAD

**Issue by matthewdarwin** [jgthms/bulma#1413]
This is about Bulma

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma 0.6.0
My **browser** is: Firefox 56
### Description

Trying to change the navbar dropdown background color for all elements.  the saas file that works perfectly fine in 0.5.2 no longer works in 0.6.0

The bolded part was added to make it work.

@import "sass/utilities/initial-variables"

$blue: #336699
$navbar-background-color: $blue
$navbar-dropdown-background-color: $blue
$navbar-item-hover-background-color: $blue
$navbar-dropdown-item-hover-background-color: $blue
$navbar-dropdown-item-active-background-color: $blue

$navbar-dropdown-color: $white
$navbar-dropdown-arrow: $white
$navbar-item-color: $white
$navbar-dropdown-item-hover-color: #00FFFF
$navbar-item-hover-color: #00FFFF

$primary: $blue;
$title-color: $blue

@import "bulma"

**.navbar-menu**
x>        **background-color: $blue**

.navbar-burger:hover
x>        background-color: $blue

.navbar-burger.burger.is-active
x>        background-color: $blue
x>        span
xx>                background-color: $white

.navbar-burger
 x>       span
xx>                background-color: $white

Note: "x>" and "xx>" is used to show indentation

**Comment by jgthms** [comment]
What is the expected outcome?

**Comment by matthewdarwin** [comment]
The background color of the pulldown should be changed to the color provided in $navbar-dropdown-background-color as it did in Bulma 0.5.2.

**Comment by Carl-Foster** [comment]
The `.navbar-menu` class has been updated in `navbar.sass` to use the `$white` variable instead of the `$navbar-background-color` variable. This is a very breaking change for my team.

**Comment by Carl-Foster** [comment]
I think the issue that I'm fixing was introduced in this commit: https://github.com/jgthms/bulma/commit/83892a21e3f4888b64f8a4a5fa25f978393e8e40

I'm guessing that this issue relates to something else.
