### ISSUE TITLE
Using sass: responsiveness works by dragging desktop windows, but not on actual mobile browsers

### ISSUE THREAD

**Issue by beauvais** [jgthms/bulma#1416]
This is about **Bulma**.

### Overview of the problem

I'm using Bulma **version** [0.6.0]
My **browser** is:

* Chrome: 62.0.3202.75
* Firefox Quantum: 57.0b14 (64-bit)
* iOS Safari: 11.0.3 (15A432)
This is a **Sass** issue: I'm using version [0.6.0]
I am sure this issue is **not a duplicate**?

### Description

The elements which should stack up vertically (columns and tiles) do so when dragging the corners of a desktop browser window.

On an actual mobile phone, however, (I'm using iOS primarily – but same on Android's Google Chrome), it just renders a tiny version of the desktop layout. I don't know if it's a bug, or if I'm misusing the framework.

This is a Hugo-generated project, with the theme using the latest Bulma Sass directories. It's all hosted on Github in the [woodfromtrees repository](https://github.com/beauvais/woodfromtrees/tree/943dd940afedce91c286b27f276d5d0c36f46987/themes/wood_theme)

![iphone-shot1](https://user-images.githubusercontent.com/724619/32417360-69d6561a-c226-11e7-9347-766e0671b949.png)
![iphone-shot](https://user-images.githubusercontent.com/724619/32417361-69e347da-c226-11e7-8ad4-8caef8779873.png)

### Steps to Reproduce
1. Open either localhost version of site, or hosted at [https://woodfromtrees.com](https://woodfromtrees.com) in a desktop browser.
2. Drag corners to resize – elements stack up beautifully
3. Open same in iOS Safari – elements are arranged like Desktop with tiny text and no column or tile stacking

### Expected behavior

I expect the columns and tiles to stack vertically.

### Actual behavior

The columns and tiles stay horizontal, as if on Desktop

**Comment by jgthms** [comment]
You're missing `<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by beauvais** [comment]
Many thanks!
