### ISSUE TITLE
Landscape mode for mobile, tablet breakpoint and tablet-only breakpoint

### ISSUE THREAD

**Issue by Isa79** [jgthms/bulma#1420]
### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.5.3]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

There is three issues. 1. There is no landscape mode for mobile. 2. Tablets in portrait mode are counted as mobile. An iPad in portrait mode is 768px but the tablet breakpoint starts at 769px. 3. Tablet-only breakpoint ends at 1023px but landscape mode for tablets starts at 1024px.

### Expected behavior

The tablet breakpoint should start at 768px, not 769px. There should be a landscape mode for mobile. And the tablet-only breakpoint should end at 1024px not 1023px. 

### Help for a solution

I am very new to Bulma and SASS. Is there a solution for my problem? Like adding `is-4-mobile-landscape` and changing the `tablet` and 'tablet-only' breakpoints.

**Comment by donreeco** [comment]
Also, columns are not activated on iPad in portrait mode, because they don't work until 769px.

**Comment by donreeco** [comment]
Also, columns are not activated on iPad in portrait mode, because they don't work until 769px.

**Comment by donreeco** [comment]
Also, columns are not activated on iPad in portrait mode, because they don't work until 769px.

**Comment by eheiser** [comment]
Agreed with issue 2. from lsa79 - but you can easily change this value in initial-variables.sass
But having an extra breakpoint around the 576px mark would be a great addition.

**Comment by drdreo** [comment]
I would also like the standard tablet breakpoint to be -1px due to iPads. 
Like that example ( i have no clue if the sandbox page is only available temporarily, sorry ) https://01p3v87qv0.codesandbox.io/ 
IPad should not break this awkwardly. iPad pro is fine, iphone X in landscape is fine. iphone 5 in landscape not fine.

**Comment by tribakzero** [comment]
I subscribe, this issue has been 'solved' on other threads with the "it's a tablet landscape breakpoint" but neither vertical nor horizontal iPad fits those breakpoints, I mean the =tablet-only mixin. But that's not the case.

**Comment by lukepighetti** [comment]
Was surprised to see portrait tablet firing the mobile breakpoint in testing today.

**Comment by lukepighetti** [comment]
correct me if im wrong but shouldn't we be

mobile – portrait phone
tablet – landscape phone, portrait tablet
laptop – landscape tablet, laptop
desktop
widescreen

instead of

mobile - phone portrait, phone landscape, tablet portrait
tablet - tablet landscape
desktop - takes up half my laptop
widescreen - takes up most my laptop
full-hd - desktop

**Comment by devzsolt** [comment]
Now it's as easy to fix it as defining the following variable *before* including the Bulma sass:

```scss
  $tablet: 768px;
```

**Comment by AccessViolator** [comment]
There's still no variable for mobile portrait/landscape breakpoint

**Comment by harveychow** [comment]
I agree with @lukepighetti.
Bootstrap has this in v4: https://getbootstrap.com/docs/4.1/layout/grid/

**Comment by paulhuisman** [comment]
Any updates on this? Would love a var for tablet portrait.

**Comment by juliomotol** [comment]
Any news on this?

**Comment by AurelianSpodarec** [comment]
So?

**Comment by harveychow** [comment]
I gave up and moved to [tailwind](https://github.com/tailwindcss). Not regretting this.

**Comment by AurelianSpodarec** [comment]
One thing to notice, Tailwind isn't the solution to everything, its deffo good, but and alternate for something else would be good to have.

**Comment by hapiben** [comment]
Any updates?
