### ISSUE TITLE
Delete button misaligned

### ISSUE THREAD

**Issue by alqu** [jgthms/bulma#1425]
This is about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is:
- Chrome 62 / MacOS
- Safari 11.0.1
- Firefox 56.0.2 / MacOS

I am sure this issue is **not a duplicate**.

### Steps to Reproduce
Go to the URLs below and check for yourself.

### Expected behavior
In Bulma v0.6.0 the delete button was properly aligned in Notifications, see
https://versions.bulma.io/0.6.0/documentation/elements/notification/

### Actual behavior
But in Bulma v0.6.1 the margin is missing:
https://bulma.io/documentation/elements/notification/

![bulma-v0 6 1-misaligned-delete-button](https://user-images.githubusercontent.com/12250845/32504415-080da8dc-c3e0-11e7-91ad-dc27ed4b49ab.png)

**Comment by jgthms** [comment]
Ah yes I noticed that. It’s because we fixed the safari bug with `font-size: 0` but the positioning uses `em` instead of `rem`.

**Comment by alqu** [comment]
@jgthms changing `em` to `rem` works for me. What do you think?

**Comment by jgthms** [comment]
Yes that's the fix.
