### ISSUE TITLE
Overflow on media causes scroll bar

### ISSUE THREAD

**Issue by darrenmothersele** [jgthms/bulma#1428]
This is about Bulma (master branch)

### Overview of the problem

 * I'm using Bulma **master branch**
 * Chromium on Linux
 * Sass

### Description

Scrollbar appears on media item 

### Steps to Reproduce

```
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">{{ user.name }}</p>
                            <p class="subtitle is-6">@{{ user.username }}</p>
                        </div>
                    </div>
                </div>
            </div>
```

### Expected behavior

No scrollbar to be visible

### Actual behavior

https://github.com/jgthms/bulma/commit/f17975d0ffae539977337945b6ac53e3035d5b92

![bulma-master-media](https://user-images.githubusercontent.com/230337/32548935-7800f1d6-c47f-11e7-9bbd-0310c8a9f8bd.png)
![bulma-0 6 0-media](https://user-images.githubusercontent.com/230337/32548936-781892be-c47f-11e7-8e2f-ddd2aa0b50f2.png)

**Comment by oleksiipotiekhin** [comment]
This is because the `overflow: auto;` property from the `.media-content` class. I've checked it on **Windows** in **Chrome** browser.
![default media-content](https://user-images.githubusercontent.com/30025319/32631086-6c6f2c04-c59f-11e7-91d7-7233d80f283b.gif)

**Comment by glococo** [comment]
Same happend to me. Please, remove overflow or replace auto -> hidden

**Comment by turbopixel** [comment]
Same here

**Comment by neetso** [comment]
I have the same issue with media-content. I want to add a list or group of buttons inside a media-content div.
![screen shot 2018-10-21 at 11 20 30](https://user-images.githubusercontent.com/97903/47265142-9a0e4c00-d523-11e8-8d54-ce09c417f436.png)

**Comment by ekrister** [comment]
This is still a problem with Bulma 0.9.1. You can also see it on the official documentation page of the card component.

**Comment by svdHero** [comment]
Same problem here. Please re-open.

**Comment by SnowpawStudios** [comment]
This is still an issue in 2022 using bulma v0.9.4 in Chrome, Edge, and Firefox (tested using the sample code for making cards on the Bulma website). 

Note that the scrollbars only appear when you increase the zoom and narrow the width of the window. For example in Chrome, the scrollbars appear at a zoom of 150% and window width of about 650px.

**Comment by gschurck** [comment]
I still have the issue, but only on Chromium browsers, not on Firefox.

**Comment by gschurck** [comment]
Here is the v0.9.4 `bulma.min.css` without the scrollbar issue if someone needs it : 
https://gist.github.com/gschurck/e804ba78225f158d4008e61f458c1dc7
