### ISSUE TITLE
How to add space between two `columns` tag

### ISSUE THREAD

**Issue by noisytoken** [jgthms/bulma#1429]
https://jsfiddle.net/ppat/k5khas1z/ 

As you can see In the fiddle, the second column starts immediately after the first. How do I add some margin between the two ?

**Comment by jgthms** [comment]
The `<figure class="image is-128x128">` should only have an `<img>` tag, no `<p>`.

https://jsfiddle.net/k5khas1z/1/

**Comment by noisytoken** [comment]
One more thing if I do this the whole page page losses it's responsiveness.
