### ISSUE TITLE
Grid align issue on small screens

### ISSUE THREAD

**Issue by ozgureffe** [jgthms/bulma#143]
Hi, 
![screenshot 2016-03-29 14 58 35](https://cloud.githubusercontent.com/assets/515248/14107173/288eaaac-f5bf-11e5-9196-5765ef5c7250.png)
...

**Comment by lostm1nd** [comment]
Hello,
Could you provide further information since I cannot reproduce this issue.
OS, screen resolution, browser tab width for starters will be great.

**Comment by ozgureffe** [comment]
**It happens somewhere between 768px and 855px**
```
OS: Win10 Pro
Browser: Chrome 49.xx
Screen Resolution : 1920 x 1080
Browser tab size : 768px <  855px
```
And the screencast : https://youtu.be/UBMqNgB4JKQ

**Comment by jgthms** [comment]
Yeah it's just a website issue. This has been fixed.
