### ISSUE TITLE
Bulma [QUESTION]

### ISSUE THREAD

**Issue by delphinas** [jgthms/bulma#1437]
Is it a bug/feature/question or do you need help?

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

How can I make regular columns behave like tiles, dynamically. Here is an example of what I want to achieve.

Suppose I have **three** columns like this on full screen/desktop

[  1  ]    [   3  ]
----    [ 3 ]
[  2 ]    [   3  ]

On tablet mode I would like to have something like this

[1]       [2]
[  3 ]

And then mobile:

[1]
[2]
[3]

Now I always get mobile version (stack of columns) whenever the screen is small etc. 
I know how to achieve this with html and hidden/visible css helpers. But is it possible in any other without creating hidden/visible columns on separate break points?

Thank you, I think I'm missing something.

**Comment by jgthms** [comment]
The layout changes too much between breakpoints and is not possible with Bulma. You’d need very specific CSS, probably with CSS Grid I believe.

**Comment by delphinas** [comment]
Thank you, that's what I thought but just wanted to clarify. Anyhow, Bulma CSS is super awesome, I'm using it for a few major project and so far it's been great. Please keep the dev and support of this CSS framework:)
