### ISSUE TITLE
.hero-video

### ISSUE THREAD

**Issue by oleksiipotiekhin** [jgthms/bulma#1438]
This is about the Bulma **Docs**
I'm using Bulma **version** [0.6.1]
It was mentioned in this issue https://github.com/jgthms/bulma/issues/374 in 2016

### Description
I've found `.hero-video` class in the _bulma.css_ file, but there are no examples how to use it in the documentation https://bulma.io/documentation/layout/hero/

![Video](https://user-images.githubusercontent.com/30025319/32728514-eb9acc2a-c880-11e7-97cc-f358b6068223.png)
### Question
The documentation wasn't added for purpose? Or I can help by updating it? I've tried to do something like this inside the `<section class="hero is-success is-fullheight">`. Is this the way it should be used?

![Example](https://user-images.githubusercontent.com/30025319/32729520-60148a34-c884-11e7-9678-73ad1ceab150.png)
### Result
![Result](https://user-images.githubusercontent.com/30025319/32729611-ae77308c-c884-11e7-8b67-0d19e0f68838.png)

**Comment by oleksiipotiekhin** [comment]
@jgthms maybe `.hero-video` is deprecated?

**Comment by Dragnucs** [comment]
Who knows?

**Comment by daniely** [comment]
Why is this closed without any answers? Either the hero video feature is removed or it is not. But right now reading through this or linked issues I cannot tell.
