### ISSUE TITLE
is-hidden-touch bug

### ISSUE THREAD

**Issue by Yllelder** [jgthms/bulma#1439]
This is about **Bulma

This is a bug
This is NOT a browser bug

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.1]
My **browser** is: Firefox 56.0.2 (64bits) in Windows 10

I am not sure this issue is **not a duplicate**

### Description

The `is-hidden-touch` class that should hide the elements in screens between 768px and 1023px (included), in 1023px does **NOT hide the elements**, but does it from 1022px.

![screen bug](https://user-images.githubusercontent.com/6941502/32758708-0365cdfe-c8e6-11e7-8ede-29a95d216e85.jpg)

The yellow column has the `is-hidden-touch` class and should be hidden in 1023px, but it does so from 1022px.

![bulma bug](https://user-images.githubusercontent.com/6941502/32758721-1a3d2a5e-c8e6-11e7-99f4-140256d53c31.gif)

This is the code I have used for this example:

```
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>

	<link rel="stylesheet"  href="bulma.css">
	<link rel="stylesheet"  href="style.css">
</head>
<body>
	<div class="columns is-mobile">
		<div class="column">
			<p class="bd-notification is-info">Blue</p>
		</div>
		<div class="column">
			<p class="bd-notification is-success">Green</p>
		</div>
		<div class="column is-hidden-touch">
			<p class="bd-notification is-warning">Yellow</p>
		</div>
		<div class="column">
			<p class="bd-notification is-danger">Red</p>
		</div>
	</div>
</body>
</html>
```

**Comment by Malvoz** [comment]
[Are you sure it's not a browser bug?](http://damienclarke.me/code/posts/those-1px-gaps-between-media-queries-can-be-a-problem)

**Comment by Yllelder** [comment]
Oh, I said it wasn't a browser bug because I did the same test on Google Chrome and Firefox browsers, and it was the same thing.

Thanks for the information. I didn't know about this common problem.

**Comment by Yllelder** [comment]
After googling a little bit looking for a solution, it seems that adding **half a pixel** to the media query, works correctly. Like this:

```
@media screen and (max-width: 1023.5px) {
  .is-hidden-touch {
    display: none !important;
  }
}
```
