### ISSUE TITLE
Fixed navbar is on top of overlays

### ISSUE THREAD

**Issue by rafaelpimpa** [jgthms/bulma#1440]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.1

### Description

Fixed navbar is on top of overlays, I think it's not intended.

### Steps to Reproduce

See documentation Modal page: https://bulma.io/documentation/components/modal/
Scroll up to see the navbar and open modal.

### Expected behavior

Overlay to be on top of everything.

### Actual behavior

Navbar on top.

**Comment by reddysridhar53** [comment]
Can I take this up @jgthms ?

**Comment by jgthms** [comment]
This has been fixed.

**Comment by jamauro** [comment]
I'm seeing this behavior in version 0.7.1. Any ideas?

**Comment by nmonty9** [comment]
```
.navbar {
    background-color: white;
    min-height: 3.25rem;
    position: relative;
    z-index: auto;
}
```

**Comment by mgmgpyaesonewin** [comment]
> My error was to have a `section` following a `nav` without `class="section"`. This also resulted in overlapping behavior.

Yes, having both section and container is nicer. Containers do not have top and bottom padding. Section does.
