### ISSUE TITLE
Problem when the modal is not a direct child of html/body

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#1444]
Hello,

This is about **Bulma**, and is a bug/feature/question :)

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome
The issue is related to #1154

### Description

I created https://github.com/laravel-enso/enso with Bulma, VueJs and Laravel.

The project is pretty much polished and I would like to start using it in my business projects.

But I still have this one last problem. I have a dedicated modal component that is reused in other components, and the modal not showing correctly in this situation. I feel it's too much of limiting factor to have to put the modal directly into `<body>...</body>`, and it seems that it affects others too.

Besides the modal background showing funny, the div below the modal is scrollable while the modal is showing.

Maybe there is a solution, or maybe you can suggest another approach. 

This is a screenshot with a dedicated vue component for forms

![image](https://user-images.githubusercontent.com/16073274/32824795-10a78830-c9eb-11e7-82fe-fa8d8d568c1d.png)

Here is another one from a documents component

![image](https://user-images.githubusercontent.com/16073274/32824877-6251742a-c9eb-11e7-999e-35979a50d138.png)

Thank you in advance!

**Comment by jgthms** [comment]
Since the `modal` is using `position: fixed`, it should work with a proper `z-index`. Have you tried increasing it?

**Comment by aocneanu** [comment]
Yes, first thing.

If you like, you can try the online demo and play in the console, maybe something else is wrong.

Thanks.

**Comment by jgthms** [comment]
2 of your 3 siblings are positioned:

![image](https://user-images.githubusercontent.com/1254808/32837784-b2d3ab78-ca06-11e7-81e9-760ee359d62e.png)

`.navbar` and `.aside` are fixed with a high `z-index`. The `.main-content` is not positioned and has no `z-index`, but it contains the modal.

Just add:

```
.main-content {
    position: relative;
    z-index: 2000;
}
```

**Comment by aocneanu** [comment]
I really need to learn CSS.

Thank you !
