### ISSUE TITLE
Horizontal navbar on mobile

### ISSUE THREAD

**Issue by philippeluickx** [jgthms/bulma#1445]
This is about **Bulma **.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**? - checked issues

### Description

Enhancement request.

### Steps to Reproduce

Implement navbar as in the docs.

### Expected behavior

I am able to show menu items in mobile view, as defined with navbar-start and navbar-end. It should be possible to either stack them vertically or have them shown horizontally.
My use case is to mimick mobile apps behaviour: add an action on the right and a back button on the left.

### Actual behavior

All menu-items are stacked vertically, even if there is enough space to show them horizontally. It is not possible to have a horizontal menu on mobile (like in everything from desktop and up).

**Comment by donreeco** [comment]
Agreed It would be nice to make some menu items always visible horizontally

**Comment by philippeluickx** [comment]
This is the css you need to make it work on mobile just like on tablet and up.
```
.navbar-item {
  display: flex;
}

.navbar,
.navbar-menu,
.navbar-start,
.navbar-end {
  align-items: stretch;
  display: flex;
  padding: 0;
}

.navbar-menu{
  flex-grow: 1;
  flex-shrink: 0;
}
.navbar-start{
  justify-content: flex-start;
  margin-right: auto;
}
.navbar-end{
  justify-content: flex-end;
  margin-left: auto;
}
```

**Comment by Eldair** [comment]
I agree we should have is-mobile modifier same as for level

**Comment by northamerican** [comment]
in addition to @philippeluickx's rules, these rules will keep all content in the same line on the navbar:
```
  .navbar .container {
    display: flex;
  }
  .navbar-item {
    display: flex;
    align-items: center;
  }
```

**Comment by bfioca** [comment]
This is cool but it doesn't work for dropdowns

**Comment by frederikhors** [comment]
@philippeluickx it doesn't work if we use dropdown. Also @northamerican.

**Comment by jcdacampo** [comment]
We need for dropdown!

**Comment by guategeek** [comment]
I also agree that I could really use this but need it to work for drop-downs

**Comment by otonielguajardo** [comment]
+1

**Comment by williamabbott** [comment]
+1

**Comment by chkrishnatej** [comment]
+1

**Comment by philippeluickx** [comment]
Looks like we have $navbar-breakpoint now, thanks!
Just add this to your scss file:
`$navbar-breakpoint: 0;`
Closing ticket.

**Comment by sookoll** [comment]
Not anybody use scss for development. Stylus is far better and it is sad, that I have to switch to scss, because I have to hack bulma all the time. This should be configurable via class.

**Comment by codeofsumit** [comment]
I also think this should be a class, because I have two navbars on my site and only want one to be the same on mobile and desktop. The other one is fine to collapse

**Comment by karipov** [comment]
`$navbar-breakpoint: 0` introduces a styling error on mobile whereby on the right side of the screen there is extra white space
