### ISSUE TITLE
navbar: is-fixed-top and is-active modifiers mess up mobile view

### ISSUE THREAD

**Issue by philippeluickx** [jgthms/bulma#1448]
This is about **Bulma **.

Bug report

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.1
My **browser** is: Chrome
I am sure this issue is **not a duplicate**? Checked the issues

### Description

Navbar covers content in mobile view.

### Steps to Reproduce

Implement navbar as in the docs.
Add the is-fixed-top modifier
Add the is-active modifier

### Expected behavior

Content displays under the menu in mobile.

### Actual behavior

The navbar is hiding the content.

**Comment by Rajan** [comment]
+1 Facing the same issue.

**Comment by pip36** [comment]
@philippeluickx Did you put the 'has-navbar-fixed-top' class on the page <html> tag?

**Comment by philippeluickx** [comment]
Yes I did. The issue is that it adds a 3.25rem padding, but when in mobile
the menu stacks vertically and might be higher than that.

**Comment by pip36** [comment]
I'd assume it's intentional, as when a user opens the hamburger menu, you would want the menu to display on top?

**Comment by philippeluickx** [comment]
That is actually a fair point. The is-active modifier as the state of the menu, not being the default. Closing this then...
