### ISSUE TITLE
Themes / Templates

### ISSUE THREAD

**Issue by Miserlou** [jgthms/bulma#145]
Hello!

Awesome job with Bulma - really looking forward to giving it a whirl!

As a heavy Bootstrap user, I was expecting to be able to find some pre-made templates and themes to build on top of using Bulma best practices, like Bootstrap provides. It seems like you don't have any yet, so I thought I'd open an Issue with the suggestion.

Thanks!

**Comment by jgthms** [comment]
Yeah some basic templates are coming. Be patient :-)

**Comment by tweed** [comment]
Sooo wonderful !!! -- thank you

**Comment by infacq** [comment]
trending now: map layout

**Comment by jgthms** [comment]
@infacq Do you have an example?

**Comment by infacq** [comment]
I have now but I need to add custom css to properly arrange it like [foursquare](https://foursquare.com/explore?cat=food&mode=url&near=Kuala%20Lumpur%2C%20Malaysia&nearGeoId=72057594039663097) does

**Comment by gbourgneuf** [comment]
Are coming basic templates will include an "administration" template ?

**Comment by ShaggyDude** [comment]
I would say -1 on templates. Or at least make it optional. That is another problem with Semantic UI a heavy theme system..

**Comment by tweed** [comment]
was hoping for a responsive grid only template - and the 3rd template not working
http://bulma.io/templates/welcome.html

whatever happens i love BULMA
i can fumble together a grid page to use by deleting from the website pages though a nice clean
header/grid/footer primarily template would be terrific for many of us i bet.

**Comment by dansup** [comment]
@Miserlou I made some [templates](https://dansup.github.io/bulma-templates/), they are not all finished yet. I'd like to clone all the bootstrap templates :smile:

**Comment by tweed** [comment]
dansup!!!  WOW WOW WOW  just checked back - there's a TON more templates.
https://dansup.github.io/bulma-templates/
REALLY terrific. 
no reply need to this of course - just thrilled.
Helps a lot of people I'm sure.

**Comment by jenil** [comment]
Hello, 

I am excited to share with you'll [Bulmaswatch](https://jenil.github.io/bulmaswatch) — Basically, it is Bootswatch for Bulma. As of now, it has 20 themes.

Try it. Test it. Use it. Share it. 💯

**Comment by jruizsulime** [comment]
Nice work with templates friends !

**Comment by maarteNNNN** [comment]
Very nice
Thanks!

**Comment by roccomuso** [comment]
Thank you!
These templates should found a place on the official website.

**Comment by jenil** [comment]
Hello peeps! 

I just launched a Kickstarter as a part of my summer project this year, it's based on Bulma and Bulmaswatch and I think a lot of folks here can benefit from it!
It is a premium and extended version on @dansup's Bulma templates.
Go check out [TemplateNest](https://www.kickstarter.com/projects/924867762/templatenest-templates-to-make-a-website-in-15-min) on Kickstarter

**Comment by boyombo** [comment]
Hi all,

Very nice templates and really stellar work with bulma. I just learnt about bulma about 3 days ago and am really blown away

**Comment by timacdonald** [comment]
@Miserlou or @jgthms As these user contributed themes and templates are now listed in the readme could probably close this issue.

**Comment by Miserlou** [comment]
Rogerroger
