### ISSUE TITLE
Initial variables, gap typo?

### ISSUE THREAD

**Issue by nandordudas** [jgthms/bulma#1453]
I think `32px` - the gap size below - is double of the body's font size.
https://github.com/jgthms/bulma/blob/5801d57029375bccd3b0a6ac6d732db1b2fc7bdc/sass/base/generic.sass#L2
https://github.com/jgthms/bulma/blob/5801d57029375bccd3b0a6ac6d732db1b2fc7bdc/sass/base/generic.sass#L21-L23
And `2 * gap = 2 * 2 * 1rem = 4rem` not `3rem`.
https://github.com/jgthms/bulma/blob/5801d57029375bccd3b0a6ac6d732db1b2fc7bdc/sass/utilities/initial-variables.sass#L48-L57
Am I right?

**Comment by jgthms** [comment]
Indeed, thanks!

**Comment by nandordudas** [comment]
This is really nothing, I thank you!
