### ISSUE TITLE
.is-marginless & .is-paddingless

### ISSUE THREAD

**Issue by oleksiipotiekhin** [jgthms/bulma#1454]
This is about the Bulma **CSS framework**.
I'm using Bulma **version** [6.0.1].
My **browser** is: Google Chrome.
I am sure this issue is **not a duplicate**, but something similar was in https://github.com/jgthms/bulma/issues/942 https://github.com/jgthms/bulma/pull/943.

### Description

By modifying `.is-marginless` & `.is-paddingless` helpers Bulma **CSS framework** will gain additional functionality that is missing at the moment.

### SASS
![Example](https://user-images.githubusercontent.com/30025319/32908207-2b35a196-cb03-11e7-90b3-b712134bad96.png)
### CSS
![Result](https://user-images.githubusercontent.com/30025319/32908212-2cf029fc-cb03-11e7-8585-4a63f8b5767a.png)

**Comment by jgthms** [comment]
I think that’s a bit too much, as I don’t want to encourage people to design in the HTML code.

**Comment by AurelianSpodarec** [comment]
Considering that the columns add negative margin-top and horizontal, I think this would be good to offset it.
