### ISSUE TITLE
IE11 , Can't have siblings 'is-vertical' tiles. 

### ISSUE THREAD

**Issue by martinlanglois** [jgthms/bulma#1455]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.3]
My **browser** is: IE11
I am sure this issue is **not a duplicate**? 

### Description

Tiles seem to work well in IE 11.
however, in the case where you want 2 "is-vertical" tiles next to each other 
it all breaks. ( the provided snippet doesnt not have all the is-child , is-parent classes, but please take my word that is has nothing to do with it )

### Steps to Reproduce

```
<div class="tile">
                <!-- left section : has 2 vertically aligned tiles -->
                <div class="tile is-vertical is-parent">
                    <div class="tile notification is-warning">
                        <p class="content">
                            {{--assume content--}}
                        </p>
                    </div>
                    <div class="tile notification is-warning">
                        <p class="content">
                            {{--assume content--}}
                        </p>
                    </div>
                </div>
                <!-- right section : has 2 vertically aligned tiles -->
                <div class="tile is-vertical is-parent">
                    <div class="tile notification is-warning">
                        <p class="content">
                            {{--assume content--}}
                        </p>
                    </div>
                    <div class="tile notification is-warning">
                        <p class="content">
                            {{--assume content--}}
                        </p>
                    </div>
                </div>
            </div>
```

### Expected behavior

![screen shot 2017-11-16 at 8 00 41 pm](https://user-images.githubusercontent.com/3316781/32924121-28c76c2c-cb09-11e7-859b-14085f766610.png)

### Actual behavior

<img width="1368" alt="screen shot 2017-11-16 at 8 00 48 pm" src="https://user-images.githubusercontent.com/3316781/32924131-33988f1e-cb09-11e7-8daa-51c4a015fb9f.png">

Might be worth pointing out that if you remove the second 'is-vertical' class
the tiles a lot closer to what you would expect. 

<img width="1364" alt="screen shot 2017-11-16 at 8 01 10 pm" src="https://user-images.githubusercontent.com/3316781/32924189-60778382-cb09-11e7-9314-47a9e16f7f3a.png">

**Comment by thecristen** [comment]
Was playing around with this in IE 11 today and noticed the `.tile` class under `.is-vertical` gets `-ms-flex-preferred-size: 0px` instead of the normal tile's `-ms-flex-preferred-size: auto`. Not sure if that helps but just wanted to note this observation.

**Comment by librien** [comment]
Thanks @thecristen.  Works for IE10 too.

**Comment by joeyhage** [comment]
The suggestion above worked for me in IE but not in Firefox or Edge. The code below worked for me in all browsers:

```css
.tile {
    flex-basis: auto;
}
```

**Comment by digifa** [comment]
In some cases this causes also trouble (with mixed tiles like a fullwidth one and three tile-columns below it does not center the three columns)
I fixed this with:

```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  .tile {
    flex-basis: auto;
    width: 100%;
  }
}
```
that is not my preferred solution but works.

**Comment by geejay81** [comment]
thanks @digifa your solution has solved my issue

**Comment by adamdehaven** [comment]
> The suggestion above worked for me in IE but not in Firefox or Edge. The code below worked for me in all browsers:
> 
> ```css
> .tile {
>     flex-basis: auto;
> }
> ```

For my use case to support IE 11, I had to modify as shown here:

```css
.tile {
    width: 100%;
    max-width: 100%;
    flex-basis: auto;
}
```
