### ISSUE TITLE
Columns position inverted

### ISSUE THREAD

**Issue by christopherkade** [jgthms/bulma#1457]
This is about **Bulma**.
Bug report.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.1]
My **browser** is: Mozilla Firefox 58.0

### Description

When using Bulma's `columns` feature, the order of the columns is inverted.

### Steps to Reproduce

```html
  <div class="columns">
    <div class="column">
      First column
    </div>
    <div class="column">
      Second column
    </div>
    <div class="column">
      Third column
    </div>
    <div class="column">
      Fourth column
    </div>
  </div>
```

### Expected behavior

Columns should follow the order of their definition

### Actual behavior

![example](https://user-images.githubusercontent.com/15229355/32955516-18d4cc24-cbae-11e7-9610-92b2412797df.png)

Note that when I inspect the elements, the HTML tags order do not match the display.

Thank you for your work ! 🥇

**Comment by jgthms** [comment]
I can't reproduce. It must come from your setup.
