### ISSUE TITLE
Hidden/Show in mobile won't work as expected (768px breakpoint iPad vertically oriented)

### ISSUE THREAD

**Issue by seergiue** [jgthms/bulma#1458]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework*

I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome

### Description

I'm wondering why the Hide/Show class have the mobile breakpoint up to 768px, because an iPad (for example) vertically oriented has a resolution of 768 x 1024 px. So if I want to use the hidden class only for mobile, it also affects an iPad.

### Steps to Reproduce

Add the class `is-hidden-mobile` on any div and then change the resolution with Chrome Dev Tools to an iPad (768 x 1024 px). The div will disappear.

### Expected behavior

I think the breakpoint should be 767px. (As Bootstrap states)

### Actual behavior

The div is hidden.

**Comment by jgthms** [comment]
There’s been a few discussions about this already. It is the expected behaviour since “tablet” means “landscape tablet”

**Comment by atif089** [comment]
@jgthms would there be an easy way to override this?

**Comment by smvv** [comment]
@atif089 you can use:
```
$tablet: 768px;
@import '~bulma/bulma.sass';
```
to overwrite tablet's default value of 769px.

See also: https://github.com/jgthms/bulma/blob/565af6ddd9a5607aba117dc8124f82e3dae36b3b/sass/utilities/initial-variables.sass for other variables.
