### ISSUE TITLE
Email Template with Bulma

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#1461]
Hi,

Does anyone know how to create an email template based on Bulma ?
Email templates require inline CSS and is Bulma compatible with major email clients (online / offline) ?
How can I inline CSS of classes used in the template (and only this not all Bulma system) ?

Regards

**Comment by jimblue** [comment]
Bulma is absolutely not made for this purpose...
Easiest way to create html email: [MJML](https://mjml.io/) !

**Comment by Wikiki** [comment]
Thanks for the link
