### ISSUE TITLE
Feature request: support for ultra widescreen ratio ( is-21by9 )

### ISSUE THREAD

**Issue by synergico** [jgthms/bulma#1462]
Show image in ultra widescreen ration (21:9)

**Comment by jgthms** [comment]
Do you have a use case? Also, can you be more descriptive in your issue? Thank you.

**Comment by synergico** [comment]
Hi, 
When design a simple card, the 16by9 ratio IMO takes more screen estate (vertically) than then 21by9. I think in most cases, 21by9 shows enough information, again just my opinion

take Medium.com for example.  (I think they went with 30by9 in this case)
![image](https://user-images.githubusercontent.com/24478917/33019550-c1bca3f2-cdf2-11e7-97f0-65c631dff809.png)

Btw, I just want to add that the css `object-fit: cover` help me fixed many images scaling issue. I'm not even sure if this is relevant, but did not see it in bulma core.

Another excellent design from medium is the horizontal card with 9by16 i think.

<img width="518" alt="screen shot 2017-11-20 at 13 02 30" src="https://user-images.githubusercontent.com/24478917/33019837-e5fb2530-cdf3-11e7-9f10-a5dc09ed6b8c.png">
