### ISSUE TITLE
[Request] Additional Tags for Image Element

### ISSUE THREAD

**Issue by Laraveldeep** [jgthms/bulma#1463]
Requesting additional conditional resize tags for image element

like `is-128x128-destop`, `is-64x64-mobile` etc.

Currently I need to resize image based on the screen size and orientation to optimieze the image element. Specially need to reduce the size from 128px desktop to 64px on mobile but clueless about how to do that using currently available tags. It is not resizing on mobile taking up too much space.

Thanks!

**Comment by jgthms** [comment]
That would be a lot of code. I think your best option is to add a `max-width` to your image.
