### ISSUE TITLE
[SOLVED] Issue with Bulma on WordPress loop

### ISSUE THREAD

**Issue by alzearafat** [jgthms/bulma#1464]
### Overview of the problem
 
I'm using Bulma **version** [0.6.1] 
My **browser** is: Firefox 57

### Description

Bulma doesn't create grid correctly in the WP loop. Please see screenshots below. I'm sure I use `columns` and `column` correctly.

### Steps to Reproduce

**index.php**
```
<div id="primary" class="content-area">
		<main id="main" class="site-main zs-site-main">
            <div class="container">
                <div class="columns">
                    <?php                   
		                /* Start the Loop */
		                while ( have_posts() ) : the_post();
			                get_template_part( 'template-parts/content-index', get_post_format() );
		                endwhile;
	            endif; ?>
                </div>
            </div>
		</main><!-- #main -->
	</div><!-- #primary -->
```

**content-index.php**
```
<div class="column is-4">
	<div class="zs-article-wrapper">
		<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
			<div class="zs-card card--resource not-visible"> <!--Resource-->
				<div class="zs-card-hero" style="background: url(<?php the_post_thumbnail_url( 'full' ); ?>) no-repeat center center; background-size: cover;">
				</div>
				<div class="zs-card-body">
					<div class="zs-card-title">
						<h2><a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>"><?php the_title(); ?></a></h2>
					</div>
				</div>
			</div>
		</article><!-- #post-<?php the_ID(); ?> -->
	</div>
</div>
```

### Expected behavior

If I'm using Bootstrap 4

![alt text](http://i.pi.gy/xk335.png)

### Actual behavior

When I'm using Bulma

![alt text](http://i.pi.gy/0PQQj.png)

---

Any help would be greatly appreciated!
Thank you.

**Comment by Wikiki** [comment]
Hi,

You forgot <code>is-multiline</code> class on your <code>columns</code> div

**Comment by alzearafat** [comment]
@Wikiki 

Thanks! Works great! 😸 

I miss the option. I think it should be moved to `basic` tab. So, no one will miss it again like me. Most people skip the `option` when they just started. They don't aware this modifier is very important.

Thank you
