### ISSUE TITLE
Scroll to fragment links offset by "is-fixed-top" navbar

### ISSUE THREAD

**Issue by tsilcher** [jgthms/bulma#1465]
This is about **Bulma**. Bug report.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.1
My **browser** is: Google Chrome / Firefox / Safari
I am sure this issue is **not a duplicate**? I am sure.

### Description

When using a sticky navbar ("is-fixed-top") the navbar height offset affects the scroll position links that point to a fragment or id on the same page ("scroll to fragment" links).

### Steps to Reproduce

1. Implement a **navbar** adding the **is-fixed-top** modifier
2. Add the **has-navbar-fixed-top** to the html element
4. Add a section with a title and some text with **id="target"**
5. Add a href="#target" link somewhere
6. Click on the link

### Expected behavior

The website should scroll to the position where the target fragment starts and be visible.
### Actual behavior

The website scrolls and the target fragment start is hidden below the fixed navbar.
(Normally it is a title which is now hidden below the navbar)

**Comment by jgthms** [comment]
This is a docs issue. The anchors should use padding instead of margin.

**Comment by jgthms** [comment]
Actually it's not a docs issue, because the navbar hides itself on scroll down. So if you click an anchor, you will be able to view the target anchor.

You need to add some `padding-top` if you want to circumvent that issue, but it's not a Bulma issue.

**Comment by Niek** [comment]
I'm also experiencing this issue. I haven't found a workaround yet - setting ``padding-top`` on the anchor or not really a solution since you only want to have this padding when someone links to the anchor.

**Comment by pnts-se** [comment]
I also has this problem. Has anyone come across a solution?
