### ISSUE TITLE
Bulma : Feature request : Add an extra-small size for some UI elements

### ISSUE THREAD

**Issue by Lucassifoni** [jgthms/bulma#1471]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]

### Description

Hi Jeremy, and thanks for your work.
What would you think of adding a smaller size for buttons & other UI elements ?
(I think it should be accompanied of an accessibility warning, though.)

I've rebuilt a portion of the docs with my changes : 

![buttons-xsmall](https://user-images.githubusercontent.com/11858475/33183850-e118f780-d079-11e7-9c40-b51ad412688d.png)
![buttons-xsmall](https://user-images.githubusercontent.com/11858475/33183853-e30b6f46-d079-11e7-8b61-2e3e4762ab31.png)

Anyway, I'm okay with just maintaining my own fork if this is too specific to my usecase or detrimental to accessibility.

Have a nice day !

**Comment by oleksiipotiekhin** [comment]
@Lucassifoni what is the purpose of using such a small `font-size`? Anyway I think it's better to call it `is-tiny`, it will be more readable.

**Comment by Lucassifoni** [comment]
@oleksiipotiekhin too-specific use-cases I suppose, I sometimes need to build UIs that fit a single screen height and look a bit like this : ![mixing table](https://user-images.githubusercontent.com/11858475/33602273-1506a28e-d9af-11e7-9cd6-d6fba5dd6f54.jpg).
Not that I'm building virtual mixing consoles, but sometimes a specific system benefits from compacity more than readibility, because the person using it needs to see everything at a quick glance.

You're right about the name !
I'll maintain my own fork, It won't be useful enough to justify adding it.
