### ISSUE TITLE
IE11 does not support 'unset'

### ISSUE THREAD

**Issue by grehovm** [jgthms/bulma#1473]
### Overview of the problem

This is about the Bulma CSS framework
I'm using Bulma version [0.6.1]
My browser is: IE11
I did not find a duplicate.

### Description

`.textarea[rows] {
  height: unset;
}`

IE11 does not support 'unset', maybe we could use 'auto'?

### Steps to Reproduce

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.css">
</head>

<body>
    <div class="container">
        <div class="section">
            <textarea class="textarea" cols="30" rows="10"></textarea>
        </div>
    </div>
</body>

</html>
```

### Expected behavior
ie11 honor textarea's 'rows' attribute

### Actual behavior
ie11 squeeze textarea to size of standard input 2.25em

PS: it may be worth changing other uses of 'unset' too.

**Comment by siegfried** [comment]
IE does not support `initial` either.

https://developer.mozilla.org/en-US/docs/Web/CSS/initial

**Comment by siegfried** [comment]
In our Ember project, we cannot set `rows=2` on IE11. It just doesn't appear in the tag, while other `rows` value are ok. The `min-height` and `max-height` prevents the default `rows=2` being used.

https://github.com/jgthms/bulma/blob/4499432926b4735cec1a64bd2026f6313d8459c2/sass/elements/form.sass#L123
