### ISSUE TITLE
hero head navbar dropdown text has no color

### ISSUE THREAD

**Issue by makstr** [jgthms/bulma#1474]
HI

This is about Bulma, and is a bug/feature/question :)

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.1]
My **browser** is:  Chrome / Safari

### Steps to Reproduce

- create a section with hero class
- place a navbar with dropdown item inside hero-head 

### Actual behavior

- the dropdown items have no color

![screen shot 2017-11-24 at 15 53 24](https://user-images.githubusercontent.com/10668265/33203272-7123bed0-d13a-11e7-82f3-509b9d31e395.png)

**Comment by jgthms** [comment]
#680

**Comment by yoanthiebault** [comment]
This bug still exist in 0.7.2.

**Comment by ilya-merkushin** [comment]
bulma@0.8.0 bug still exist
[https://codepen.io/Om108/pen/WNNKdBW?editors=1000#0](url)

**Comment by gragland** [comment]
@jgthms Seems like a pretty critical bug. Would you accept a pull-request that fixes this?

**Comment by ianchildress** [comment]
still exists. dropdown from hero navbar would be beautiful if it worked.

**Comment by codingcatgirl** [comment]
Still persist. Heyo, anyone reading this? :D
