### ISSUE TITLE
Pure CSS Mobile-compatible Responsive Dropdown Menu

### ISSUE THREAD

**Issue by noraj1337** [jgthms/bulma#1476]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** v0.6.1

My **browser** is: Firefox 57.0, Opera 49.0.2725.34

### Description & Actual behavior

This is an enhancement request.

Let's read the doc first.

> `navbar` > `navbar-brand` > `navbar-burger` the hamburger icon, which toggles the navbar menu on touch devices.
>
> The `navbar-burger` is a hamburger menu that only appears on mobile.
>
> The `navbar-menu` is hidden on touch devices < 1024px . You need to add the modifier class `is-active` to display it. 
>
> The Bulma package **does not come with any JavaScript**.
> Here is however an implementation example, which toggles the class is-active on both the `navbar-burger` and the targeted `navbar-menu`.

The target here is mobile devices. So on mobile devices for toggling the menu you need the `is-active` class **AND** some external/custom CSS.

So to get a responsive drowpdown menu on mobile Bulma can't work alone and this force you to use JS.

### Enhancement & Expected behavior

I found a way to do this in pure CSS without using JS!

+ Author: Andor Nagy
+ Name: _Pure CSS Mobile-compatible Responsive Dropdown Menu_
+ Description: A pure CSS responsive menu that automatically changes to a toggleable dropdown menu at a specified breakpoint based on CSS3 media queries.
+ How: It uses checkbox & label technique to toggle sub menus.
+ [Article](https://www.cssscript.com/pure-css-mobile-compatible-responsive-dropdown-menu/)
+ [CodePen](https://codepen.io/andornagy/pen/RNeydj?editors=1100)
+ [Demo](https://www.cssscript.com/demo/pure-css-mobile-compatible-responsive-dropdown-menu/)

I tested it and it works very well. I wish there is a way to adapt and include this trick inside Bulma in order to have something similar to `is-active` but without JS.

**Comment by jgthms** [comment]
I know this technique but it feels like a dirty hack to me, because it uses a checkbox for the wrong reason.

The docs do provide a JS snippet to handle the navbar burger.
