### ISSUE TITLE
[Feature Request] Full-screen modal

### ISSUE THREAD

**Issue by zsobral** [jgthms/bulma#1479]
A full screen modal

<img src="https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3MDdSZ0Rnd1pKeWM/components-dialogs-fullscreen1.png"  width="250">

**Comment by CAYdenberg** [comment]
Secondary request: full-screen-mobile etc..

**Comment by jordanranson** [comment]
Yeah would be nice to have a 'is-full-screen-mobile' etc.
