### ISSUE TITLE
Disable "Vertical by default" feature to allow horizontal scrolling

### ISSUE THREAD

**Issue by onsombal** [jgthms/bulma#1481]
I have a use case where horizontal scrolling is required for columns. Is there any way to disable the default behavior of vertically stacking the columns?

Thanks... Jim

**Comment by Log1x** [comment]
`<div class="columns is-mobile">` might be what you're looking for.

**Comment by onsombal** [comment]
I tried both "is-mobile", which does prevent the columns from stacking vertically, but there is no horizontal scrolling capability -- i.e. the columns to the right disappear as the screen size shrinks.

**Comment by onsombal** [comment]
I now have horizontal scrolling working by using the Flexbox method described in a blog. It works well given Bulma is built upon Flexbox:
  https://codepen.io/colinlord/post/horizontal-scrolling-containers

The HTML and CSS code is shown below:
   HTML 
      <div class="columns scrolling-wrapper-flexbox">
  CSS -- BTW, I did make a couple of minor edits to the code shown in the blog. 
     <style>
    .scrolling-wrapper-flexbox {
      display: flex;
      flex-wrap: nowrap;
      overflow-x: auto;
    }
    .scrolling-wrapper-flexbox {
      width: 100%;
      -webkit-overflow-scrolling: touch;
      &::-webkit-scrollbar {
      }
    }
    </style>
