### ISSUE TITLE
$colors variable name

### ISSUE THREAD

**Issue by stewwan** [jgthms/bulma#1482]
any chance to change $colors variable name?

I love bulma and like to use with other libraries, but I got conflicts when using bulma with Ionic for eg. because they also use this variable name. I ended up by forking and modifying manually to $bulma-colors, but not sure if this is the best way.

thx

**Comment by jgthms** [comment]
You might be able to reset `$colors` in between your imports.

```
@import "ionic";

$colors: ("white": ($white, $black), "black": ($black, $white), "light": ($light, $light-invert), "dark": ($dark, $dark-invert), "primary": ($primary, $primary-invert), "link": ($link, $link-invert), "info": ($info, $info-invert), "success": ($success, $success-invert), "warning": ($warning, $warning-invert), "danger": ($danger, $danger-invert));

@import "bulma";
```
