### ISSUE TITLE
When to use Tiles vs Columns?

### ISSUE THREAD

**Issue by toymachiner62** [jgthms/bulma#1483]
This is about **Bulma**.

Question

### Overview of the problem

I'm trying to figure out when I should be using tiles vs when i should be using columns.

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome

### Description

Tiles and Columns seem to basically do the same thing, except they have different visual styles (borders, etc) built into bulma. Is there a reason or a use case of when I should use one over the other?

**Comment by jgthms** [comment]
Tiles are more for a 2-dimensional layout, where all cells are aligned on a grid.

Columns are usually for a single line of items, but can be multiline as well.

I would say that columns are overall easier to use. Tiles are a tidy bit more experimental and less flexible, but can provide more interesting and complex layouts.

**Comment by doncatnip** [comment]
This doesn't make much sense to me. What can tiles do what nested columns can't ? The original question was not answered. Having 2 technologies doing pretty much the same thing is what makes me hesitate using Bulma.

**Comment by doncatnip** [comment]
Perhaps it isn't the best reason, however .. since there are so many choices, one have to look for reasons somewhere, and this does perhaps show a little insight into an overarching design philosophie.

**Comment by doncatnip** [comment]
Alright, I suppose you'd use Tiles when you want your containers to be stretched vertically to the same height as the highest neighbouring tile(set).
