### ISSUE TITLE
I am trying to add a bulma page in another html page but it conflicts with normal css of the page.(e.g box-sizing:inherit in bulma gets applied every where in that html page)

### ISSUE THREAD

**Issue by sonam-yadav** [jgthms/bulma#1484]
This is about **Bulma | the Docs**.

**Comment by jgthms** [comment]
Please describe your problem in depth.

**Comment by sonam-yadav** [comment]
I have two pages, one page running on client side and second one running on my end.client page is build on html and css , and my page is build on html and bulma.I have  embed my page in client page through javascript which is running fine. The only issue I am facing is there is css in bulma (
*{box-sizing:inhert} ) which gets applied to client page as well that causes client page to get break .

**Comment by jgthms** [comment]
You can choose to import only what you need. See https://bulma.io/documentation/overview/modular/
