### ISSUE TITLE
.field.is-grouped content goes over borders (wrap issue)

### ISSUE THREAD

**Issue by PassTheMayo** [jgthms/bulma#1495]
This is about **Bulma**.

Is it about Bulma or about the Docs? Bulma
Is it a bug/feature/question or do you need help? Bug
If it's a bug, is it a browser bug? No

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.6.0
My **browser** is: Google Chrome

I am sure this issue is **not a duplicate**? I am pretty sure, but it is hard to track down if it was already posted.

### Description

If you have two columns, with an `<article>` with the `media` class, and have a div with `field is-grouped` classes, and the browser width is small enough, it causes the buttons on the group to go off the box and not wrap on a new line. This can easily be solved by adding `flex-wrap: wrap;` to `.field.is-grouped`. Here is the problem:
![image](https://user-images.githubusercontent.com/16949253/33535750-254ac93a-d875-11e7-967c-297f49fa0d58.png)
As you can see, the text goes over the inherited borders

### Steps to Reproduce

See description for details

### Expected behavior

I expected inner-content to wrap onto a new line.

### Actual behavior

The text and buttons went over the edge of the article.

**Comment by jgthms** [comment]
Add is-grouped-multiline or just the buttons class.
