### ISSUE TITLE
Full size 2 row columns with image on one side.

### ISSUE THREAD

**Issue by delphinas** [jgthms/bulma#1496]
This is not an issue but rather a question to see whether it is possible to achieve this type of layout with Bulma CSS.

My goal is to achieve this: https://imgur.com/a/rrCD9

I can achieve similar thing with 2 columns, image on one and text on the other. However:
* How to make image in the column full width (with no spacing around) ? Is there an easy workaround or built in feature within the framework?

Thank you

**Comment by jgthms** [comment]
It's tricky, but try a fluid container with nested columns.
