### ISSUE TITLE
Change input size

### ISSUE THREAD

**Issue by ak77pl** [jgthms/bulma#1498]
hi im using bulma v 0.61

I made the input field with the icon and the field is short instead of being on the entire width of the div field class.

https://images83.fotosik.pl/928/39ef6e6678869c75.jpg
How to change to fullwidth input size?

`<div class="field has-addons"><p class="control"><span class="icon is-small"><span class="fa fa-map-marker fa-fw"></span></span></p><p class="control"><input class="input is-small" type="text"  name="address" value=""></p></div>`

**Comment by oleksiipotiekhin** [comment]
## Code
```html
<div class="field">
    <div class="control has-icons-left">
        <input class="input is-small" type="text" placeholder="Address" value="Address">
        <span class="icon is-small is-left">
            <i class="fa fa-map-marker "></i>
        </span>
    </div>
</div>
```
## Result
![Example](https://user-images.githubusercontent.com/30025319/33601138-a272d5d8-d9ab-11e7-8c8f-0abd2a573b82.png)

**Comment by ak77pl** [comment]
No, no icon in the pen, just next to the left, and preferably like it looks like this:
![input-example](https://user-images.githubusercontent.com/33711778/33629476-73867d66-da04-11e7-848c-14a273fcf074.jpg)
but with the only bottom border i can handle

**Comment by jgthms** [comment]
Add “is-expanded” on the second control. Also add “is-fullwidth” on the input.
