### ISSUE TITLE
How to avoid columns being resized during browser resize 

### ISSUE THREAD

**Issue by AriPal** [jgthms/bulma#1499]
This is about **the Docs**.

### Overview of the problem
This is about the Bulma **CSS framework**

### Description
I have two columns centered on the page, the column to the left shows a number with large font size, and the column to the right is just bullet text.  

### Expected behavior
When I resize the page, I want the columns to be in static size, but still following responsive approach. 

### Actual behavior
The problem occurs when I try to resize the page, what happens is that both columns overwrite each other because of the size of the column changes, the column shrinks. 

### Here is the code
https://gist.github.com/AriPal/3d4d5f955df7a1f94e2fe417f5e6b06b

**Comment by jgthms** [comment]
> I want the columns to be in static size, but still following responsive approach

I don’t understand this.

**Comment by AriPal** [comment]
What happens is that I have a large subtitle inside a column, and when I resize the browser, the subtitle exceeds a few centimeters outside the boundary of the column. What I want is a column that has a fixed width and height. I found a way to solve this by manually changing the width and size using: 

`style="width:400px; height:400px"`

Perhaps not the best solution, but it works :)

**Comment by jgthms** [comment]
Ah yes if you need specific dimensions you need to write it yourself. A framework can not contain all possibilities!
