### ISSUE TITLE
My sass doesnt work in project

### ISSUE THREAD

**Issue by ROBERTATSU** [jgthms/bulma#1507]
Hi, i've created file mystyles.scss and it's watching, compile but changes doesnt appear on page, so Im confused. That's the code:

`@import "../sass/utilities/initial-variables";
@import "../sass/utilities/functions";

// Add pink and its invert
$pink: #ffb3b3;
$pink-invert: #fff;

$primary: $pink;
$primary-invert: $pink-invert;

@import "../bulma";`

**Comment by jgthms** [comment]
What’s your HTML code?

**Comment by ROBERTATSU** [comment]
`
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>RobIT</title>
    <link rel="stylesheet" href="css/mystyles.css">
    <link rel="stylesheet" href="css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
        

        <nav class="navbar is-primary container is-transparent">
            <div class="navbar-brand">
                <a href="#" class="navbar-item navbarg">RobIT</a>
            </div>
            <button class="button navbar-burger" id="burger">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div class="navbar-menu" id="burger">
                <div class="navbar-end">
                <a href="#" class="navbar-item">aa</a>
                <a href="#" class="navbar-item">aa</a>
                <a href="#" class="navbar-item">aa</a>
            </div>
            </div>
        </nav>
    
    <script src="js/main.js"></script>
</body>
</html>
`

**Comment by jgthms** [comment]
Are you linking your CSS file at all??
