### ISSUE TITLE
 overflow-y: scroll

### ISSUE THREAD

**Issue by oleksiipotiekhin** [jgthms/bulma#1508]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is: Google Chrome
Similar: https://github.com/jgthms/bulma/issues/1293

### Description

Can `overflow-y: scroll` be moved to `body` instead of `html` tag? Because when you are using `.is-clipped` in your `body` tag, it doesn't work the way you expect it to work. It restrict us from removing scroll bar from the `body`.

![html](https://user-images.githubusercontent.com/30025319/33718104-99e0eee8-db5c-11e7-8043-b15bb06f9e96.png)

### Expected behavior
![Scroll](https://user-images.githubusercontent.com/30025319/33718460-be772d98-db5d-11e7-91d3-cd5b9030bad7.gif)

**Comment by jgthms** [comment]
Why not use is-clipped on the html element?
