### ISSUE TITLE
Unstyled lists

### ISSUE THREAD

**Issue by jbrooksuk** [jgthms/bulma#151]
Can we have a `ul` class which will remove bullet points from lists?

**Comment by TroyAlford** [comment]
That seems a bit less semantic than one or more classes which use `ul` + a `class` name to create a specific effect.

Something like `ul.menu.flyout` or `ul.tabs` - which would both remove the bullet points, for example, but also create a specific type of component styling.

Is there a specific semantic type of component which this would fit? `unstyled-list` or something similar?

**Comment by jbrooksuk** [comment]
I was thinking `ul.is-unstyled` or similar?

**Comment by TroyAlford** [comment]
Sounds like it would be something like:
```
ul.is-unstyled {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

**Comment by jbrooksuk** [comment]
Yeah.

**Comment by jgthms** [comment]
By default, lists are unstyled. I'm not sure what is needed here.

**Comment by jbrooksuk** [comment]
Ah it may be in the .content class.

**Comment by jgthms** [comment]
If you need a container that only adds a margin at the bottom, but without styling anything, use `class="block"`.

**Comment by jbrooksuk** [comment]
Thanks!

**Comment by gdude2002** [comment]
If lists are unstyled by default, is there a class included to add bullets/numbering back?

**Comment by tompec** [comment]
@gdude2002 Yes you just need to put your `<ul>` into a `<div class="content">`.

**Comment by gdude2002** [comment]
Directly? What if I have inside, eg, a `message`?

Or, wait, am I meant to put a `content` inside those as well?

**Comment by tompec** [comment]
```html
<div class="content">
   <ul>
      <li></li>
   </ul>
</div>
```

More info here: http://bulma.io/documentation/elements/content/

**Comment by gdude2002** [comment]
Yeah, I knew that, I was just wondering whether it's appropriate to put within another container, eg:

```html
<article class="message">
  <div class="message-header">
    <p>Hello World</p>
    <button class="delete"></button>
  </div>
  <div class="message-body">
    <div class="content">
      <ul>
        <li>...</li>
      </ul>
    </div>
  </div>
</article>
```

**Comment by tompec** [comment]
yes!

You could even get rid of that extra div like that I guess
```html
<article class="message">
  <div class="message-header">
    <p>Hello World</p>
    <button class="delete"></button>
  </div>
  <div class="message-body content">
    <ul>
      <li>...</li>
    </ul>
  </div>
</article>
```
