### ISSUE TITLE
Css Grid

### ISSUE THREAD

**Issue by khuzemakanore** [jgthms/bulma#1511]
This is about **Bulma | the Docs**.

Question

Is it possible to use css grid instead of flex box?

**Comment by oleksiipotiekhin** [comment]
Do you know that those are two different things? **CSS grid** is not replacing **FLEX box** and vise versa.

**Comment by jgthms** [comment]
Why?

**Comment by WisdomCorp** [comment]
I know that they are both different that's why the question. 

For why, we have some base design made on css grid. So need to keep using css grid.

**Comment by jgthms** [comment]
I’m not sure what you’re asking for here. 

You can use CSS grid and flexbox at the same time, since they do different things.

How is Bulma’s use of flexbox hindering you?

**Comment by WisdomCorp** [comment]
Bulma is excellent, it was just a question related css-grid uses with bulma. thanks
