### ISSUE TITLE
Support is better than advertised!

### ISSUE THREAD

**Issue by danjford** [jgthms/bulma#152]
On the README the support says the following, taking statistics from caniuse:

![image](https://cloud.githubusercontent.com/assets/7963046/14181460/e189a9a8-f75e-11e5-95d3-6f805bce3b17.png)

But, if you click show all, you can see that support for flexbox goes even further back:

![image](https://cloud.githubusercontent.com/assets/7963046/14181476/f1390006-f75e-11e5-9ecb-6ee7def3a74a.png)

![image](https://cloud.githubusercontent.com/assets/7963046/14181451/d2351dd4-f75e-11e5-906a-a4a813577e00.png)

**Comment by jgthms** [comment]
Thanks! I removed the versions, apart for IE.
