### ISSUE TITLE
Discoverability of features is difficult in the docs

### ISSUE THREAD

**Issue by theoutlander** [jgthms/bulma#1530]
This is about the Bulma **Docs**

### Description

It appears that navigating through all the elements in the documentation is very slow because the page sends a request to fetch data for each tab or sub-tab that is clicked. It would be nice if the hierarchy of the components is not hidden like it is today. 

Could the documentation be changed to a one-pager or could an overview section be added so we can easily navigate to what we're looking for?

**Comment by jgthms** [comment]
> It would be nice if the hierarchy of the components is not hidden like it is today.

What do you mean?

**Comment by fariasfrancisco** [comment]
I believe he means that he wants the second line that appears when you toggle a tab to alway be visible. Like, for example, when you click on `Form` you can then see that it's components are 

- `General`
- `Input`
- `Textarea`
- `Select`
- `Checkbox`
- `Radio`
- `File`

And he wants to know they are ther before clicking on `Form`.

I don't agree with him but I would like some sort of quick access index for each component. I'm often going into form to view how `field is-grouped` or `is-horizontal` works, and to do that I have to scroll down to that point.

**Comment by theoutlander** [comment]
Thanks for clarifying @fariasfrancisco. I think the quick access index is probably the best solution (and what I meant by an overview page).

As a new user of Bulma, I'm not certain how items are organized. I've used it for a couple of months now, on and off, but still run into the same problem where I keep clicking most of the tabs and subsections to find what I'm looking for. 

As an alternate solution, the docs menu item on the top bar could have sub-menus that correspond to the documentation hierarchy.

Also, a search box with auto-suggest might be a good feature to include in the docs.

**Comment by mrbudlong23** [comment]
Yup. That's been my problem too. Docs are difficult to sort through/read.
