### ISSUE TITLE
[advice] Reorder columns on mobile stack

### ISSUE THREAD

**Issue by cyrilchapon** [jgthms/bulma#1536]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Hello :)

I'm struggling at finding how to accomplish this :

*Desktop*
```
|¯¯¯¯¯¯¯¯¯|
| block a |
|_________|    |¯¯¯¯¯¯¯¯¯|
               | block c |
|¯¯¯¯¯¯¯¯¯|    |_________|
| block b |
|_________|
```

*Mobile* (notice order)
```
|¯¯¯¯¯¯¯¯¯|
| block a |
|_________|
|¯¯¯¯¯¯¯¯¯|
| block c |
|_________|
|¯¯¯¯¯¯¯¯¯|
| block b |
|_________|
```

Is that even possible out of the box ?

Thanks :)

**Comment by jgthms** [comment]
Out of the box no, but since they are flexbox items you can play around with the `order` CSS property!
