### ISSUE TITLE
Button with "is-small" size not use sass variable $radius.

### ISSUE THREAD

**Issue by AlexZayats** [jgthms/bulma#1538]
This is about **Bulma**.

### Description

Button with "is-small" size not use sass variable $radius.
![screenshot_1](https://user-images.githubusercontent.com/2835213/34096307-e8bf3df8-e3e5-11e7-9899-911efa38140e.png)

### Steps to Reproduce

1. Set sass variable $radius to 0.
2. Add button with class "button is-small".

### Expected behavior

Button with 0 radius.

### Actual behavior

Button with default radius (2px).

**Comment by feute** [comment]
Actually, there is a separate variable for the radius of small buttons.

[https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/utilities/initial-variables.sass#L62-L64](https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/utilities/initial-variables.sass#L62-L64)

It is used here:
[https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/elements/button.sass#L29-L32](https://github.com/jgthms/bulma/blob/fdeba5d111f8a7e695de4fc7a70966348daeeb03/sass/elements/button.sass#L29-L32)

Changing `$radius-small` to 0 should do the trick. In your case, to avoid repetition, you could do:
```sass
$radius: 0
$radius-small: $radius
```

**Comment by AlexZayats** [comment]
@feute Thanks for information. I did not know about it.
