### ISSUE TITLE
Don't force Font Awesome

### ISSUE THREAD

**Issue by jbrooksuk** [jgthms/bulma#154]
Rather than baking in `.fa` classes, maybe use `.icon` so that you can use any icon type you want.

**Comment by TroyAlford** [comment]
I'd strongly advocate this, too - as it allows the framework to be less opinionated about which font glyph set to use. For instance - supporting [Fontello](http://fontello.com) would be great, as it super-sets Font Awesome - but also allows great customization.

**Comment by jbrooksuk** [comment]
Likewise, I use Ionicons :)

**Comment by jgthms** [comment]
Problem is that every icon font has an optimized font-size by which it's more readable. I'd rather handle one case perfectly (Font Awesome) then all cases poorly.

**Comment by jbrooksuk** [comment]
You could add overrides for the popular ones? Not just font awesome?

**Comment by TroyAlford** [comment]
My thought was that we would still optimize for FA, because it's the most
widely used, but use a more generalized name for the classes.

All very minor though. I'm using Fontello right now with Bulma and it works
fine - not sure there's any reason to make a change, other than to loosen a
seemingly tight pairing and perhaps shrink files a bit.

Neither is a hugely compelling need in my mind.

**Comment by jgthms** [comment]
There's already a `.icon` container for the `.fa` elements.

Most people will use Font Awesome. And for those who don't, just override the `.icon` and `.fa` styling.

**Comment by RXminuS** [comment]
@jgthms Actually that doesn't quite work. For instance if you're trying to add an icon to an input then there's styling in place that specifically targets .fa classes not .icon classes. Should be a relatively easy fix by swapping out all references to .fa with .icon though

**Comment by alex996** [comment]
I used these for Ionicons:

```css
.icon .ion {
  font-size: 21px;
}

.icon.is-small .ion {
  font-size: 14px;
}

.icon.is-medium .ion {
  font-size: 28px;
}

.icon.is-large .ion {
  font-size: 42px;
}
```
