### ISSUE TITLE
$radius-rounded is missing

### ISSUE THREAD

**Issue by flaviolivolsi** [jgthms/bulma#1541]
Hello,

the variable `$radius-rounded` is missing from the file `initial-variables.sass`, while `$radius`, `$radius-small` and `$radius-large` are there.

I have the version `0.6.1` installed via NPM.

**Comment by jgthms** [comment]
Ah yes it's coming in `0.6.2`.

**Comment by ishitatsuyuki** [comment]
It has been kind of long time since `0.6.1`, do you have ETAs for `0.6.2`?

**Comment by viki53** [comment]
Same here: the docs show features that aren't public yet.

Maybe you shouldn't make these docs public until the version is published?
