### ISSUE TITLE
Bulma SVG logo

### ISSUE THREAD

**Issue by toymachiner62** [jgthms/bulma#1542]
I'm looking for an SVG version of the Bulma logo to be uploaded to https://worldvectorlogo.com/ so that I can use it in a presentation at my job.

Do you have one available that I can use?

**Comment by Anomnimel** [comment]
I think it's need to close this issue. Files has been available [here](https://github.com/jgthms/bulma/tree/master/docs/_includes/svg) since 31 July 2017.
