### ISSUE TITLE
Change number of columns (without columns) by display width - Fluid Grid 

### ISSUE THREAD

**Issue by smarek** [jgthms/bulma#1543]
This is about **Bulma**

This is probably not documented, or not built-in by Bulma platform. Is it possible to use cards/boxes/tiles in standard float:left manner (ie. overflowing by rows, not by columns), and have Bulma decide the width of each card/box/tile depending on the screen width?

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** [0.6.3]
I am sure this issue is **not a duplicate**?

### Description

Standard use-case would be to use something like

```html
<div class="section is-clearfix">
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
  <div class="box" style="width: 300px; float: left;"> Box content </div>
</div>
```

Where amount of boxes in rows will change depending on display width.

However if one wants to have `5-column-fullhd 4-column-widescreen 3-column-desktop 2-column-tablet 1-column-mobile` there is no Bulma-way to achieve this.

Using columns is wrong, as we're talking rows. Using boxes/tiles/cards with fixed width is wrong, as its not responsive. using `is-6` in 12-grid is for columns, using `is-one-quarter-widescreen` is also for columns.

What I'd expect is something like:
```html
<div class="section is-clearfix">
  <div class="box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd"> Box content </div>
  <div class="box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd"> Box content </div>
  <div class="box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd"> Box content </div>
  <div class="box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd"> Box content </div>
  <div class="box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd"> Box content </div>
</div>
```

Is it achievable with Bulma by default, or do I need to extend myself? Thank you!

**Comment by jgthms** [comment]
Have you tried multiline columns?

**Comment by smarek** [comment]
@jgthms jesus, did not realize from the Docs, that this feature is for flex grids.

Sure `column box is-full-mobile is-half-tablet is-one-third-desktop is-one-quarter-widescreen is-one-fifth-fullhd is-pulled-left` works pretty nicely out-of-the-box.

Maybe add an mention of flex/grid keywords or provide some kind of example? Feel free to use this ticket as reference and/or source of docs snippets.

**Comment by mrbudlong23** [comment]
So glad I saw this! Been trying to figure it out for a while now. 

The next problem I can't seem to get is-vertical to get rid of the gaps with boxes like how they do with tiles.
