### ISSUE TITLE
"is-italic" typography helper is missing

### ISSUE THREAD

**Issue by candlerb** [jgthms/bulma#1546]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

The [typography helpers](https://bulma.io/documentation/modifiers/typography-helpers/#text-transformation) page in the documentation says there is an "is-italic" class, but it does not exist.

### Steps to Reproduce

~~~
<p class="is-italic">foo</p>
~~~

The word "italic" appears only in one place in bulma.css:

~~~
$ grep -i1 italic css/bulma.css
.content figure figcaption {
  font-style: italic;
}
~~~

### Expected behavior

Font in italic

### Actual behavior

Font unchanged

**Comment by richardkmichael** [comment]
@candlerb Looks like #1452 implements this, has been merged, and will be included in [`0.6.3`](CHANGELOG.md).
