### ISSUE TITLE
Fluid Container horizontal margins

### ISSUE THREAD

**Issue by lorlab** [jgthms/bulma#1552]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The example for the Fluid Container states (emphasis mine):

_This container is fluid: it will have a 32px gap on either side, **on any viewport size**._

However, the gaps disappear below 1024px (`$desktop` breakpoint).

### Steps to Reproduce

Resize the browser window to below 1024px.

### Expected behavior

The 32px gaps on either side should always be present.

### Actual behavior

The gaps disappear.

**Comment by kiwanska** [comment]
Leaving  my support here, the actual behaviour is very different from expected behaviour, really strange.
