### ISSUE TITLE
Unused $input-radius variable

### ISSUE THREAD

**Issue by feute** [jgthms/bulma#1553]
This is about **Bulma & the Docs**.

Related to #1422.

### Overview of the problem
I was looking for changing the radius of input elements, so I headed to the documentation of `input` element inside `form`, and looked at the variables. I saw `$input-radius` and I thought that it would change the radius of `input` and `textarea` (that was the expected behaviour for me). I tried to change it but nothing happened.

I inspected the source code and I found that this variable is not being used anywhere. In 0.6.1 it is used in `.field .has-addons`:

```sh
$ grep -R "\$input-radius" sass/*
sass/elements/form.sass:$input-radius: $radius !default
sass/elements/form.sass:          border-bottom-left-radius: $input-radius
sass/elements/form.sass:          border-top-left-radius: $input-radius
sass/elements/form.sass:          border-bottom-right-radius: $input-radius
sass/elements/form.sass:          border-top-right-radius: $input-radius
```

In this case, `$input-radius` is not very descriptive.

From the git version, it is not being used anywhere (the border variables above are zero):

```sh
$ grep -R "\$input-radius" sass/
sass/elements/form.sass:$input-radius: $radius !default
```

I think this should be used for input elements with `.textarea` and `.input` classes, or just remove any reference to `$input-radius` from the source and documentation, and just reference to the global `$radius` variable or something; but it would be nice to have separate radius for each set of elements.

I propose, if this variable is going to be used, that the initial value for `$input-radius` should be `$radius`. This way, we don't alter the current behaviour (`$radius` change the radius of every element) and provide `$input-radius` for input elements.

**Comment by mikerockett** [comment]
Just bumped into this as well. Thing is, I'm so sure it worked before. That said, I just found $control-radius a second ago. This seems to be chosen for consistency between buttons and controls, in the case that they're linked via has-addons?

**Comment by stevenkkim** [comment]
I am trying to customize $input-radius and it is not working for me. Looking at form.sass, I also can confirm that $input-radius is not being used. (Using Bulma 0.7.1 via npm)

+1 for having a separate $input-radius and $textarea-radius (in addition to $control-radius and $radius).

But if the decision is to not have separate radius variables for input and textarea, then at least these should be removed from documentation.

**Comment by douglasppaz** [comment]
Continue in 0.7.2 and master branch code:
https://github.com/jgthms/bulma/blob/ff8c4c18accf2c0094aa77945b1d2180ac927159/sass/elements/form.sass#L26
