### ISSUE TITLE
$panel-block-background-color variable

### ISSUE THREAD

**Issue by swamikevala** [jgthms/bulma#1556]
This is about **Bulma**.

This is a feature request

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1] 
My **browser** is: Chrome 58.0.3029.81 (64-bit) on Ubuntu

### Description

There is no convenient variable to set the background color of a panel-block. Suggest introducing new $panel-block-background-color variable

Current workaround:
.panel-block
  background-color: #cfeef8

**Comment by rumblefrog** [comment]
Sorry to necro-post, but I'm also looking for something like to be added to Bulma.

**Comment by velu76** [comment]
Hi, I also think bulma should have the ability to change background of all components via similar variables.
