### ISSUE TITLE
Add own colors ?

### ISSUE THREAD

**Issue by roukmoute** [jgthms/bulma#156]
Hi,

I would like to know if a concatenation is possible to add our colors to your variable `$colors` ?

Like this: `$colors: $colors + (blue: ($blue, $blue-invert))`

**Comment by jgthms** [comment]
I'm not sure concatenation is possible in Sass. But you could just copy/paste the `$colors` array and append any color you want.

**Comment by roukmoute** [comment]
Yeah of course, it was only to keep your variables and not missing your new variables in the future.
Thanks

**Comment by whawker** [comment]
@roukmoute you could use `map_merge`. 

```sass
$new-colors: ("blue": ($blue, $blue-invert));
$colors: map_merge($colors, $new-colors);
```

**Comment by roukmoute** [comment]
Uho it's been a long time!
Thanks ;)
