### ISSUE TITLE
Columns causing horizontal scroll on mobile

### ISSUE THREAD

**Issue by mrbudlong23** [jgthms/bulma#1561]
Is it about Bulma or about the Docs? **Bulma**
Is it a bug/feature/question or do you need help? **Bug**

### Description

When adding the columns div, it causes a horizontal scroll on mobile devices.
![eevyjo8](https://user-images.githubusercontent.com/34051218/34343150-2d7af93e-e97a-11e7-88de-8443f307c6f6.jpg)

### Steps to Reproduce
This is my code:
https://pastebin.com/YPTAPm6c (had to use pastebin, github wasn't letting me post the html)

### Expected behavior

There shouldn't be a horizontal scroll on mobile.

### Actual behavior

There is a horizontal scroll on mobile.

**Comment by jimblue** [comment]
same as #1540

**Comment by mrbudlong23** [comment]
Similar but I'm not using the "is-variable" class.

**Comment by mrbudlong23** [comment]
FIGURED IT OUT!

For anyone else experiencing this. Edit your `.columns`

It's going to have a left and right margin of "-0.75rem".

Remove those and the problem will be fixed.

**Comment by tirprox** [comment]
The .columns fix breaks the whole responsive column system though. I found that it would be easier to limit the mobile viewport to 100% with meta tag.

<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />

**Comment by zihotki** [comment]
> The .columns fix breaks the whole responsive column system though. I found that it would be easier to limit the mobile viewport to 100% with meta tag.
> 
> `<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no" />`

Although it didn't make any difference on desktop for me (bulma 0.7.4, chrome latest).

**Comment by alexboots** [comment]
Please think before adding `user-scalable=no` is it the user experience you want? Probably not. 

It's better to add `body { overflow-x: hidden }`

**Comment by erquhart** [comment]
@tirprox cross posting this comment from https://github.com/jgthms/bulma/issues/776#issuecomment-512955559:

Unfortunately that solution is not great for accessibility: https://a11yproject.com/posts/never-use-maximum-scale/

> By setting maximum-scale=1.0, you are disabling the functionality to use pinch zoom on certain mobile devices, forcing people to view your page a certain way.

> The attribute is set as user-scalable="yes" by default, which means that people are able to control the zoom setting for the page they’re visiting. Changing it to user-scalable="no" would prevent zoom settings from working on both mobile and desktop devices.

**Comment by mimidotsuser** [comment]
setting  `.columns` margin to zero only removed horizontal scroll. I had to set the box-sizing of all elements to border box and `.columns:last-child` to zero.

```
*{
    box-sizing: border-box
}
.columns,
.columns:last-child {
    margin: 0
}
```

**Comment by StanBright** [comment]
Unfortunately, the last fix suggested by @mimidotsuser opens other unexpected issues :/

**Comment by smarwei** [comment]
[This](https://stackoverflow.com/questions/49642824/bulma-columns-mobile-overflowing-bod) solved it for me:
`<meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no">`
instead of
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by johannesE** [comment]
Why is this closed? All workarounds provide more issues.

Disabling the pinching is not the solution as @erquhart mentioned.

> By setting maximum-scale=1.0, you are disabling the functionality to use pinch zoom on certain mobile devices, forcing people to view your page a certain way.

I think the only valid option is to remake the columns. That negative margin on `.columns` just so that we can have positive margins on `.column`... 🤔 I'd rather work with `:last-child` css selectors to make sure the last column does not receive a `margin-right` (and the first column a `margin-left`).

**Comment by StanBright** [comment]
I tried the `maximum-scale=1.0` option but it doesn't seem to work for some reason. Although that's not a good solution, this horizontal scroll is so annoying I decided I will make the compromise. However, it didn't work. You can see here https://www.saashub.com. I've set `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />` but the horizontal scroll is still there on mobile ¯\_(ツ)_/¯.

**Comment by HarryChristianR** [comment]
I did replace the default **overflow-y: scroll** to **overflow-y:hidden** found on bulma.css

**Comment by StanBright** [comment]
@HarryChristianR I just tried that and the whole website lost the mobile view. So, that didn't work for me. Was that in addition to the mete[viewport] tag?

**Comment by TupleTechnologies** [comment]
Can we know why is this closed? This is a very nagging issue and is very irritating to see the white gaps to the right scrolling makes it worse as the page seems to wobble and move up and down. Can we have a proper fix for this please?

**Comment by antwake** [comment]
> I did replace the default **overflow-y: scroll** to **overflow-y:hidden** found on bulma.css

If you do that, you won't be able to have sticky elements on your page  though

**Comment by StanBright** [comment]
It seems this is a somewhat inherent flow/issue that cannot be fixed easily. Otherwise, with so many people experiencing this issue it should have been fixed already ¯\_(ツ)_/¯

**Comment by erikobox** [comment]
Really! This is the biggest issue of this project!

**Comment by schumskie** [comment]
Hey guys another fix is to use `p-3` class on the parent element, like so:
```html
<div class="container p-3">
    <div class="columns">
       ...
   </div>
</div>
```

Explanation:
By adding `p-3` it automatically set padding to `0.75rem` that gets zeroed out with columns negative margin.

**Comment by Entalpi** [comment]
@schumskie solution did solve the issue with the horizontal scrolling on mobile devices but the desktop view does become more cramped. 🤷

**Comment by melcarthus** [comment]
Combined with anothor issue I had with this project, the lack of on ``until-dektop`` breakpoint I added a modifier class to fix this issue. That way it's only applied to the mobile and tablet breakpoits as we do not need this fix on every breakpoint from desktop and up.

#### The extra mixin from mixins.sass (or where ever your mixins are in your project written in SASS)

```=until-desktop
  @if $widescreen-enabled
    @media screen and (max-width: $desktop - 1px)
      @content```
```
#### the modifier class (bem style)
```
.container--outer
  +until-desktop
    padding-left: 0.75rem
    padding-right: 0.75rem
```
