### ISSUE TITLE
Column size still applied on tablet mode with the is-desktop class

### ISSUE THREAD

**Issue by mydnic** [jgthms/bulma#1562]
Is it about Bulma or about the Docs?
This is about Bulma.

Is it a bug/feature/question or do you need help?
It's a bug/question - not sure

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome

### Description

I'm trying to stack two fullwidth columns on tablet and mobile.
On desktop and above, the two columns needs to be half-sized.
When using `is-desktop` class on the `columns` div,  the two columns stack correctly on top of each other (on tablet and mobile), but the column that has the `is-half` class remains half-sized in tablet mode.

### Steps to Reproduce

Visit this fiddle : https://jsfiddle.net/mydnic/wtprmwsh/
Resize the output window to be on tablet size.

### Expected behavior

I expect to see, on tablet, two fullwidth columns

### Actual behavior

The first column with the class `is-half` is still half-sized

--
I'm not sure if this is expected or if its a bug?? I got a solution from this stackoverflow post : 
https://stackoverflow.com/questions/47977919/bulma-is-desktop-columns-not-stacking-properly-in-tablet

But this seems odd.. when using `is-desktop`, I expect that below the desktop point, columns are not columns anymore.
Or maybe I'm wrong ??

**Comment by is-shining** [comment]
It's not a bug. That's the expected behaviour.

Below the desktop point columns are not columns anymore. That's right. But that doesn't mean that the class `.is-half` has no effect. 

https://stackoverflow.com/questions/47977919/bulma-column-size-is-half-still-applied-on-tablet-mode-with-the-is-desktop-cla/47980030#

**Comment by mydnic** [comment]
Thanks a lot for the clarification :)
