### ISSUE TITLE
level inside panel not working correctly

### ISSUE THREAD

**Issue by swamikevala** [jgthms/bulma#1563]
This is about **Bulma**.

Is it a bug

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome Version 58.0.3029.81 (64-bit)

### Description

Elements inside a level-right element are not right-aligned when the level is within a panel-block

### Steps to Reproduce
```
<div class="box">
    <div class="panel">
      <p class="panel-heading">Some heading</p>
      <div class="panel-block">
        <div class="level">
          <div class="level-right">
            <div class="level-item">
              <p>some content</p>
            </div>
          </div>
        </div>
     </div
```

### Expected behavior

"some content" should be right-aligned

### Actual behavior

It is left-aligned

**Comment by hpello** [comment]
I experienced the same behavior and think it might be related to #812.
In my case, the `.level` was not taking the full width of the `.panel-block`.

A workaround is to add the style `display: block` to your `.panel-block`.
Moreover, you may need to add an empty `.level-left` before your `.level-right`.

Hope this helps!

**Comment by romikforest** [comment]
Than it's a problem with text-overflow. Text doesn't fit the container

**Comment by jameslafa** [comment]
add `is-flex-grow-1` class on the level made it work as well. I find this solution better than transforming a flex element into a box.
