### ISSUE TITLE
How to override variables when using Angular?

### ISSUE THREAD

**Issue by omrico** [jgthms/bulma#1568]
This is a question about Bulma / SASS - how to override variables in Angular projects.
### Overview of the problem

I'm using Bulma **version** [0.6.1]
My **browser** is: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
This is a **Sass** issue: I'm using version [0.6.1]

### Description

I'm trying to override the variables for the navbar component. I am using Angular 4.2.4 and the loading of the CSS files is done by .angular-cli.json under:
```
"styles": [
        "styles.scss",
        "../node_modules/bulma/css/bulma.css",
        "../node_modules/font-awesome/css/font-awesome.min.css"
]
```
I tried to override a variable, and updated styles.scss files like this:
```
@import "../node_modules/bulma/sass/utilities/initial-variables";
@import "../node_modules/bulma/sass/utilities/functions";

$navbar-height: 5rem;
$navbar-background-color: blue;
```

### Expected behavior

The navbar should have been updated with the above values

### Actual behavior
Nothing changed

**Comment by feute** [comment]
Did you import Bulma itself with `@import "../node_modules/bulma/bulma";`?

It is an odd way to import Bulma like you're doing, because you're using the CSS and SCSS (not quite). I would remove the CSS from the "styles" array and import Bulma from `styles.scss`; this way you'll have your customised Bulma CSS file. To sumarise:

```diff
 "styles": [
         "styles.scss",
-        "../node_modules/bulma/css/bulma.css",
         "../node_modules/font-awesome/css/font-awesome.min.css"
 ]
```

```diff
 @import "../node_modules/bulma/sass/utilities/initial-variables";
 @import "../node_modules/bulma/sass/utilities/functions";

 $navbar-height: 5rem;
 $navbar-background-color: blue;

+@import "../node_modules/bulma/bulma";
```

**Comment by omrico** [comment]
@feute your solution worked. Thank you very much!

**Comment by danieldaeschle** [comment]
Maybe adding documentation like: "How to use it with angular"?
