### ISSUE TITLE
grid.sass - @for $i from 1 through 11

### ISSUE THREAD

**Issue by kvanlierop** [jgthms/bulma#157]
I've found some edge cases where the `grid.sass` isn't complete. In some instances there's a need to use `is-12` (or `is-12-mobile`) and it doesn't exist currently.

Currently `grid.sass` only contains the following:

    @for $i from 1 through 11

suggesting that any use of the above line be changed to:

    @for $i from 1 through 12

to help support edge cases.

*****

While its a site on a development server, the issue is as follows.

I have a `is-multiline` & `is-mobile` grid layout. When it drops to mobile screens `is-half-mobile` works where I want it to, however, if I don't specify a size for mobile (on a specific column) it defaults to showing as if I included `is-half-mobile` regardless of what I might change. 

The closest (and no where near ideal) 'solution' I've found with the current code is to is `is-11-mobile`, but for obvious reasons that doesn't span 100% of the width. 

For the time being I've modified my `grid.sass` file to compensate for this but it would be great if it could be integrated.

*****

Two final things:

1. I'm not an advanced Github user (or know much about it at all) so if there was a better way to request a change like this I just don't know what that is.
2. It could be that I've set something up wrong, however, given this seems to be an edge case and I haven't come across any other issues with the columns I'm not sure what it would be.

**Comment by jgthms** [comment]
Actually it makes sense. It's a quick fix.

**Comment by jgthms** [comment]
Added
