### ISSUE TITLE
Copy button in form documentation copies code with "Copy" appended

### ISSUE THREAD

**Issue by aaronang** [jgthms/bulma#1570]
This is about **the Docs**

### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Description

Clicking the `Copy` button in the code examples on the [form controls' documentation](https://bulma.io/documentation/form/general/) copies the code example with "Copy" appended to the clipboard.

### Steps to Reproduce

1. Go to https://bulma.io/documentation/form/general/#form-field
1. Click the `Copy` button
1. Paste anywhere

### Expected behavior

```html
<div class="field">
  <label class="label">Label</label>
  <div class="control">
    <input class="input" type="text" placeholder="Text input">
  </div>
  <p class="help">This is a help text</p>
</div>
```

### Actual behavior

```html
<div class="field">
  <label class="label">Label</label>
  <div class="control">
    <input class="input" type="text" placeholder="Text input">
  </div>
  <p class="help">This is a help text</p>
</div>
Copy

```

**Comment by Ding-Fan** [comment]
Same in https://bulma.io/documentation/components/message/
