### ISSUE TITLE
Importing "utilities" add some global code

### ISSUE THREAD

**Issue by cyrilchapon** [jgthms/bulma#1573]
### Overview of the problem

This is about the Bulma **CSS framework**
This is a **Sass** issue

### Description

One would expect importing 

```
@import "~bulma/sass/utilities/_all";
```

to only import variables and mixins.

### Steps to Reproduce

I'm in a case where I need to build :

- a bulma.css file
- a mystyle.css file

Both using bulma variables.

So I've got 

**_variables.scss**

```
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";

$gap: 200px;

@import "~bulma/sass/utilities/_all";
```

**bulma.scss**

```
@import "./_variables";
@import "~bulma/bulma"
```

**mystyle.scss**

```
@import "./_variables";
//some code
```

### Expected behavior

I'd expect `mystyle.css` export not to contain anything from bulma

### Actual behavior

It contains almost nothing, but actually still :

```
@keyframes spinAround {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(359deg);
  }
}
```

**Comment by cyrilchapon** [comment]
(To clarify, I find it misleading, and think the fact to *define* an animation globally, is not what one would call an utility)

**Comment by jgthms** [comment]
Unfortunately, that's how CSS animations work: they have to live in the global namespace to be accessible from anywhere.

This animation is in the utilities folder because it's used by the loading spinner, which is a utility.
