### ISSUE TITLE
Buttons with 'navbar-burger' have border radius.

### ISSUE THREAD

**Issue by ek1506** [jgthms/bulma#1580]
This is about **Bulma**.

### Overview of the problem
Button elements with the class combination of 'button' and 'navbar-burger' have border radius.

### Description
This was discussed in #1515, but their workaround was to remove the 'button' class and use a &lt;div&gt; tag. This workaround is not sufficient for all cases, because you lose access to modifiers like 'is-primary'.

A solution is to remove the border radius from 'navbar-burger', so it can be safely used in combination with 'button'.

### Expected behavior
![image1](https://user-images.githubusercontent.com/29785364/34466691-06994cae-ee92-11e7-91e9-4d11393d21ae.png)

### Actual behavior
![image2](https://user-images.githubusercontent.com/29785364/34466700-31a07990-ee92-11e7-893b-3a22954ba956.png)

**Comment by feute** [comment]
I never thought about colour modifiers like `is-primary` on the hamburger. Good point.

Maybe you could use the modifier `is-radiusless` as a workaround. I agree that `navbar-burger` shouldn't have a radius (or border) if it's a button.
