### ISSUE TITLE
class card looks broken.

### ISSUE THREAD

**Issue by Forbidden-Duck** [jgthms/bulma#1585]
This is about **Bulma** bug.

This is about the Bulma **CSS framework**
I'm using Bulma **0.6.1**
My **browser** is: Google Chrome (Also tested on Microsoft Edge)

When using `class="card"` with `class="card-image"` and `class="card-content"` It extends the width of the screen and sticks everything to the side of the screen

What it actually did
https://i.imgur.com/28S1oca.png

What I was expecting
https://i.imgur.com/RJMikZP.jpg

**Comment by domcorvasce** [comment]
IMHO the current behavior which is: the component inherits the parent width could be considered like a _feature_ rather than a bug.

**Comment by jgthms** [comment]
Yes the card takes the whole wider available.
