### ISSUE TITLE
Rounded Tabs aren't rounded

### ISSUE THREAD

**Issue by ericgrosse** [jgthms/bulma#1588]
This is about **Bulma**

### Overview of the problem

This is a **Sass** issue: I'm using version 0.6.1
I am sure this issue is **not a duplicate**

### Description

The [Tabs ](https://bulma.io/documentation/components/tabs/) page includes an example of rounded tabs. However, when I copy the example into my project, the tabs don't get rounded at the edges.

### Steps to Reproduce

- Create a React application with `create-react-app`
- `yarn add bulma` -> `"bulma": "^0.6.1",` in the `package.json` file
- In `index.js`, add `import 'bulma/css/bulma.css';`
- A separate stylesheet (imported afterwards) changes one of the default variables:

```
@import '~bulma/sass/utilities/initial-variables.sass';

$footer-background-color: $cyan;

@import '~bulma/bulma.sass';

```

- Copy paste the example into `App.js`, replacing `class` with `className`

### Expected behavior

![expected-behavior](https://user-images.githubusercontent.com/6740888/34599425-33fa0aea-f1c0-11e7-9730-8fa8348bb7d0.PNG)

### Actual behavior

![actual-behavior](https://user-images.githubusercontent.com/6740888/34599439-477143f4-f1c0-11e7-9fef-f4c2688f7f35.PNG)

PS: As far as I can tell, the `.is-toggle-rounded` class responsible for rounding the edges is completely absent from the source code.

**Comment by jgthms** [comment]
It's coming in `0.6.2`!
