### ISSUE TITLE
[Feature/Idea] Searchable Documentation

### ISSUE THREAD

**Issue by DougBeney** [jgthms/bulma#1595]
This is about **the Docs**.

### Description

I think it would be very useful to add a search feature to the documentation.

I've heard good things about Algolia with Jekyll: https://community.algolia.com/jekyll-algolia

**Comment by monaye** [comment]
It's a great idea and must have feature and I can work on this. 
Do you have any thoughts on where the search field should be located?

**Comment by angelocordon** [comment]
Yes please! 

Navbar seems like a good spot?

**Comment by DougBeney** [comment]
My concern with the navbar is that it doesn't look like there is going to be room without removing stuff.

[What about something like this?](https://i.imgur.com/zEnrhh2.png)

**Comment by jgthms** [comment]
#1325
