### ISSUE TITLE
How to customize bulma? Instruction in docs is weird.

### ISSUE THREAD

**Issue by brachkoff** [jgthms/bulma#1599]
I have installed bluma (by npm) and base knowledge of sass, but I can't understand how to customize bulma.

**Comment by jgthms** [comment]
Where do you get stuck?

**Comment by matryer** [comment]
On [the customize page](https://bulma.io/documentation/overview/customize/) it explains that you should create a `.sass` file but doesn't explain where to put it or what to do with it. Once the file is created and put into the right place, is there a build step that will output the new styles?

For people unfamiliar with this workflow, a complete explanation would be awesome.

**Comment by maarteNNNN** [comment]
Depending on the project what you're working on for instance a VueJS project by installing `node-sass` and `sass-loader` you can just make a `my-styles.sass`

Define your styles and add `@import '~bulma'` behind it. Then in your `App.vue` you just add:
```sass
<style lang="sass">
  @import '@/assets/my-styles.sass
</style>
```

Or without Vue, use Gulp/Webpack to compile it.

**Comment by matryer** [comment]
Thanks @maarteNNNN 

I wonder if some basic tutorials would be a good idea, with whichever the authors think is the best approach for new projects. Literally from create a folder, add package.json, use these tools, put the file here, run this, add single css import, etc. 

After all, we're selecting Bulma because of the good taste the creators have.

**Comment by maarteNNNN** [comment]
@matryer Gulp should be very straight-forward. [gulp-sass](https://www.npmjs.com/package/gulp-sass)
[This should get you started](https://css-tricks.com/gulp-for-beginners/)

It's a lot simpler than it sounds. Think of Gulp as a processing pipe sass goes in gets processed (compiled) and comes out in css. You can automate this using nodemon that watches all files. Once one gets updated gulp will automatically compile for you. If you run in any problem feel free to mention me.

**Comment by maarteNNNN** [comment]
@matryer 
alternatively [buma-start](https://github.com/jgthms/bulma-start)
