### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by darol100** [jgthms/bulma#16]
This is a great project a that still not have a v1. And I was wondering when you guys are planing on releasing v1? In order for other projects like WordPress and Drupal to use this as theme they will need a major/stable release.

Maybe in the future I build Drupal base theme but without a major/stable version does not make sense to build base on IMO.

I propose to create a issues in Github base on the new features/improvements/bugs to the framework and add milestone to it. Base on the next version that feature might be include it.

**Comment by wolfika** [comment]
Coming up with a roadmap would indeed be great, since there are many contributors who could then be able to help improve this awesome project.

**Comment by arthurkirsz** [comment]
In the wiki ? or maybe a Public Trello would do the job ?

**Comment by jgthms** [comment]
Public Trello sounds good actually.

**Comment by darol100** [comment]
@jgthms There is also https://waffle.io/.

**Comment by arthurkirsz** [comment]
@darol100  I love waffle but I believe mixing github issues and a project roadmap won't do any good to clarify what's going on in the project. Better split these into two different tools, right ?

**Comment by jgthms** [comment]
Agreed. Anyone can write issues, and that's not how a roadmap should work.

**Comment by darol100** [comment]
@jgthms , Ok.

**Comment by DimitarChristoff** [comment]
are there any plans to use `.scss` or port / accept PRs that port to other flavours like `.less` or `.styl`?

**Comment by ncksllvn** [comment]
Bump - was there ever a verdict on this? Or a list of what needs to be added or fixed before a v1 release?

**Comment by jgthms** [comment]
Ok I set up one: https://trello.com/b/5Lzqejo3/bulma-roadmap

I'll add a link to the readme and the documentation.

**Comment by ncksllvn** [comment]
Thank you! Really great job with this btw! Hopefully I can help out.

**Comment by mesqueeb** [comment]
Hey i would love some tooltips like in bootstrap. You could leave gradient buttons for v 1.1

**Comment by jgthms** [comment]
@mesqueeb Problem with tooltips is that they require javascript, which Bulma doesn't provide.

**Comment by Frisbeetarian** [comment]
Heya, is there a roadmap to 1.0 I could find?

**Comment by DevDymLB** [comment]
Why is the roadmap not updated ? When is version v1.0 coming ?

**Comment by TupleTechnologies** [comment]
When will Bulma v1.0 release? How does the release roadmap for Bulma look like? Having this information will give everyone the confidence to adopt Bulma in new and large projects.
