### ISSUE TITLE
bluma with nextjs

### ISSUE THREAD

**Issue by Tankerxyz** [jgthms/bulma#1601]
This is about **Bulma.

Who has any thoughts on how to use all the features of Bluma (variables, etc.) With the nextjs framework?

**Comment by jnsdrtlf** [comment]
This should work perfectly without any hustle. You just download `bulma.css` and put it in your `/static` folder. You can then add the styles to your app by including them in your head: [nextjs docs](https://github.com/zeit/next.js#populating-head)

You can apply the styles to any item just like in html.

**Comment by jgthms** [comment]
Thanks @jnsdrtlf

**Comment by InstanceOfMichael** [comment]
What about if you want to include editing your SASS variables and tree-shaking?

**Comment by jnsdrtlf** [comment]
@InstanceOfMichael I would copy the bulma source code into a project folder, edit the sass variables and sass code as needed, and use something like gulp or your existing build tool to bundle it to css, then import it in your head.

**Comment by jvarness** [comment]
Here's an example of how I did it using `@zeit/next-sass` and `bulma` npm packages: https://github.com/jvarness/next-with-bulma

**Comment by jeffryang24** [comment]
It is not working when using `cssModules` config enabled for both `next-sass` or `next-css` plugin. How to make it work while enabling cssModules? :bowing_man:

**Comment by fullstackwebdev** [comment]
it doesn't work.

**Comment by Loque18** [comment]
BLUMA XD

**Comment by Loque18** [comment]
i know this is close and all, but BLUMA XDD
