### ISSUE TITLE
Bulma doesn't work well with Markdown

### ISSUE THREAD

**Issue by patrykkalinowski** [jgthms/bulma#1603]
Markdown uses `#` for headings, ex: `# This is H1`, `## This is H2`.

The problem is that Bulma doesn't style headings based on HTML tags, but classes. Markdown generated file is `<h1>This is H1</h1>`, but you need to use `<h1 class="title is-1">This is H1</h1>` to make it *look* like heading.

Currently it's impossible to use markdown - headings dont work.

**Comment by robbinfellow** [comment]
Use **content**:
https://bulma.io/documentation/elements/content/

> A single class to handle WYSIWYG generated content, where only HTML tags are available

```html
<div class="content">
    <!-- Generated markdown here -->
</div>
```

**Comment by jgthms** [comment]
Thanks @robbinfellow
