### ISSUE TITLE
scroll issue with tile

### ISSUE THREAD

**Issue by semmiverian** [jgthms/bulma#1605]
This is about **Bulma**.

### Description

Tile is being pushed when have a long text inside our tile

So i'm trying to create a scroll view inside a tile with is-4. It works fine when i only have short text inside the scroll view, but when i add more text to the scroll view. the tile is push depend on the length of the text. But, when i use column layout which will stay  same (fixed) even when we have short or long text inside our scroll view.

Here i put a link to my codepen regarding this issue https://codepen.io/semmiverian/pen/PEdJqm

thanks for you help 

Regards Semmi Verian

**Comment by futurethang** [comment]
This has been a real headache for me as well. So far nothing I've tried has taken hold and the tile stay stubbornly full height.
