### ISSUE TITLE
Feature Request - Circular Image

### ISSUE THREAD

**Issue by Piero87** [jgthms/bulma#1609]
This is about **Bulma**.

### Description

Hi,
I want know if there is a way to have circular image, thanks

**Comment by stern-shawn** [comment]
That's just a css property: `border-radius: 50%` for fully circular, or if you want just rounded corners you could use a smaller value.

You could either provide your own custom class or override the Bulma `image` class where you [customize it](https://bulma.io/documentation/overview/customize/).

**Comment by jnsdrtlf** [comment]
Extending @stern-shawn answer:

If you use images like this:
```html
<figure class="image is-128x128">
  <img src="https://bulma.io/images/placeholders/128x128.png">
</figure>
```
you have to apply `border-radius: 50%;` to the `<img>` tag:
```html
<figure class="image is-128x128">
  <img style="border-radius:50%" src="https://bulma.io/images/placeholders/128x128.png">
</figure>

<!-- or -->

<style>
.is-circular {
    border-radius: 50%;
}
</style>

<figure class="image is-128x128">
  <img class="is-circular" src="https://bulma.io/images/placeholders/128x128.png">
</figure>
```

**Comment by Piero87** [comment]
Thank you all for the answer but `border-radius: 50%;` doesn't cover all the cases and the problem that can happens with various resolution of image, like portrait or landscape. I think this could be a more proper solution:

```
<div class="rounded-img-container">
  <img class="rounded-img" src="https://hypb.imgix.net/image/2017/08/bryan-cranston-toxic-relationship-breaking-bad-performance-twtr.jpg?w=960&q=90&fit=max&auto=compress%2Cformat"/>
</div>
```

```
.rounded-img-container {
  display: inline-block;
  width: 250px;
  height: 250px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}
```

**Comment by Wikiki** [comment]
Hi,

here is my code to do it:
```sass
.image
  &.is-rounded
    img
      object-fit: cover
      object-position: center center
      height: 100%
      width: 100%
      border-radius: 250983px
```

used like that:
```html
<figure class="image is-96x96 is-rounded">
   <img src="https://images.unsplash.com/photo-1506919258185-6078bba55d2a?dpr=1&auto=format&fit=crop&w=1000&q=80&cs=tinysrgb">
</figure>
```

and also for icon:
```sass
.icon
  &.is-rounded
    border-radius: 250983px
```

**Comment by jnsdrtlf** [comment]
@Piero87 this could be accieved with the 'is-square' class. Much simpler.

**Comment by diomed** [comment]
why is this still not an option???
other frameworks have this option by default.

**Comment by darkylmnx** [comment]
it exists but not in the docs
![image](https://user-images.githubusercontent.com/1426357/39044051-552d5592-448f-11e8-862a-617d6cde6291.png)

@jgthms this is missing in the docs, wonder if I should create a seperate issue for this or not ?

**Comment by bravohex** [comment]
I use as below:

` <figure class="image is-128x128  ">
                <img class="is-rounded" src="https://bulma.io/images/placeholders/256x256.png">
              </figure>`

**Comment by santm** [comment]
The `image class="is-rounded"` only works if the image is square; for other image it does not work. But the same feature is there in bootstrap as `class="rounded-circle"` and that works perfectly.
