### ISSUE TITLE
Add `.is-bold` and `.is-$color` to any block elements?

### ISSUE THREAD

**Issue by koddr** [jgthms/bulma#1610]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]
My **browser** is: Safari 11.0.2

### Expected behavior

We can add `.is-bold` and `.is-$color` to any block elements (like `.box` or `.column`) and get beauty view without make specific background pattern in Photoshop or else.

### Actual behavior

Only `.hero` [can use](https://bulma.io/documentation/layout/hero/) `.is-bold` and `.is-$color`.

**Comment by angelocordon** [comment]
Commenting to follow this thread :)

**Comment by angelocordon** [comment]
As per my comment in #1611, happy to submit a PR for this but want to make sure that this is needed. 

My edge case scenario is that I need sections with different background colors so customizing the section’s background color variable won’t be enough. 

Semantically speaking, not sure if it makes sense to have more than one hero section in a given page, and while I can make my own custom helper class, it may beneficial to the framework itself.

**Comment by zimonline** [comment]
+1 for is-$color, is-bold not to be bound to anything in particular.
<div class="is-primary is-bold">Foo</div> should work

**Comment by koddr** [comment]
@zimonline `.is-bold` is a gradient (experimental). By adding the `is-bold` modifier, you can generate a subtle gradient, like this:

<img width="1440" alt="screen shot 2018-01-21 at 11 40 30" src="https://user-images.githubusercontent.com/11155743/35192290-f40565dc-fe9f-11e7-918a-3dd088139b5a.png">

**Comment by faheel** [comment]
From v0.7 onwards you can set the background color using the [`has-background-$color` class](https://bulma.io/documentation/modifiers/color-helpers/#background-color). But this does not set the appropriate text color, you will need to set that using the [`has-text-$color` class](https://bulma.io/documentation/modifiers/color-helpers/#text-color).
Eg. for a dark section with light text:
```html
<section class="section has-background-dark has-text-light">
  ...
</section>
```
