### ISSUE TITLE
Nested columns not working as expected

### ISSUE THREAD

**Issue by toymachiner62** [jgthms/bulma#1612]
This is about **Bulma**.

### Overview of the problem
Bug related to nested columns

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.6.2]

### Description

I have a codepen example here https://codepen.io/toymachiner62/pen/aEPzyy which has nested columns. What i would expect is that when you make your browser window smaller, the text in the red box should be truncated with ellipsis. That is not actually happening. Instead when you shrink your browser the right most column of buttons is just hidden and the text that should be truncated is not.

### Steps to Reproduce
Go to this  https://codepen.io/toymachiner62/pen/aEPzyy codepen example and shrink your browser window

### Expected behavior

The text to truncate should be truncated with ellipsis

Example: https://snag.gy/KDLQrI.jpg

### Actual behavior

The text to truncate and right most column with buttons are being hidden

Example: https://snag.gy/QLZtaq.jpg

**Comment by jgthms** [comment]
You need some `overflow: hidden;` on 2 columns to get the ellipsis to work: https://codepen.io/jgthms/pen/ppqLex

**Comment by toymachiner62** [comment]
Worked like a charm!
