### ISSUE TITLE
Bottom spacing at fields

### ISSUE THREAD

**Issue by hamzayoussef** [jgthms/bulma#1615]
### Overview of the problem

This is about the Bulma CSS framework
I'm using Bulma version 0.6.1
My browser is: Firefox

### Description

I have a big spacing at the bottom of the field.

### Code
Check my code here: (sorry for that because the formatting of my code here was horrible)
http://pasted.co/79fbadf9

### Actual behavior

![image](https://user-images.githubusercontent.com/22435038/35168089-9b7410b8-fd4f-11e7-9224-718006737bd9.png)

**Comment by ronaldlong46** [comment]
Try changing this:
`                                        <div class="field has-addons">
                                            <p class="control">
                                                <a class="button is-static">
                                                    #
                                                </a>
                                            </p>
                                            <p class="control is-expanded">
                                                <input class="input" type="text" name="ref" placeholder="Référence" value="{{ old('ref') }}">
                                            </p>
                                        </div>
                                        @if($errors->has('ref'))
                                            <p class="help is-danger">{{$errors->first('ref')}}</p>
                                        @endif
                                        <p class="help">Do not enter the first zero</p>
                                    </div>
`

To this:
`                                    <div class="field has-addons">
                                            <p class="control">
                                                <a class="button is-static">
                                                    #
                                                </a>
                                            </p>
                                            <p class="control is-expanded">
                                                <input class="input" type="text" name="ref" placeholder="Référence" value="{{ old('ref') }}">
                                            </p>
                                            @if($errors->has('ref'))
                                                <p class="help is-danger">{{$errors->first('ref')}}</p>
                                            @endif
                                                <p class="help">Do not enter the first zero</p>
                                        </div>
`

I could be totally wrong, but I think placing the "Do not enter the first zero" outside of the field div is causing it to add the 0.75em bottom-margin from the field class causing that weird spacing you are talking about. Again, someone please correct me if I'm wrong.
