### ISSUE TITLE
navbar-burger Color Modifiers

### ISSUE THREAD

**Issue by danieljharrin** [jgthms/bulma#1616]
This is about the Bulma **CSS framework**

When I use color modifiers on `navbar`, `navbar-burger` doesn't change color and looks ugly.

Instead, I issued...
```
.navbar-burger {
    background: transparent;
    border: none;
}
```
to fix the issue.

I have just seen that in the [documentation](https://bulma.io/documentation/components/navbar/#colors) the toggle button is the correct style. I have a fresh version of Bulma... why is this the case?

I have posted my code [here](https://jsfiddle.net/hLuahasq/) (without the fix) so that you can see what is happening.

Daniel

**Comment by robbinfellow** [comment]
Remove the **button** class modifier from **navbar-burger**.

**Change this:**
`<div class="button navbar-burger" data-target="navMenu">`

**To this:**
`<div class="navbar-burger" data-target="navMenu">`

Working example:
https://codepen.io/robbinfellow/pen/goqGJP

**Comment by danieljharrin** [comment]
@robbinfellow thank you 😄
