### ISSUE TITLE
is-fluid below 1024

### ISSUE THREAD

**Issue by timurxyz** [jgthms/bulma#1618]
.container.is-fluid modifier is defined only for 
@media screen and (min-width: 1024px)
thus the below is not true
"This container is fluid: it will have a 32px gap on either side, *on any viewport size*."
v0.6.2

**Comment by dennis-digital** [comment]
I confirm. But I'm using v0.7.1 and there is 1088px breakpoint (1024 + 32 *2).

![image](https://user-images.githubusercontent.com/21360822/39954107-2ff6c9e0-55c2-11e8-929a-963b1e95fe8a.png)

**Comment by billkremer** [comment]
#1552

**Comment by jgthms** [comment]
More discussion here #2062
