### ISSUE TITLE
Feature request - portrait ratios for images

### ISSUE THREAD

**Issue by pieterjandesmedt** [jgthms/bulma#1623]
This is about **Bulma**.

Thank you for this great framework!

Can we support portrait ratios corresponding the existing landscape ratios for images?
I'm thinking `is-3by4`, `is-2by3`, `is-9by16`, `is-1by2`.

Maybe add `is-5by4` and `is-4by5` too as it's also a [common aspect ratio](https://en.wikipedia.org/wiki/Aspect_ratio_(image)#Still_photography)?

I'll create a PR if you want.

**Comment by yusufbicer** [comment]
Adding all these features will bloat Bulma, please use custom CSS file.

**Comment by pieterjandesmedt** [comment]
Hmmm... Seems a bit arbitrary to only include landscape aspect ratios. Lots of sites (thinking e-commerce, portfolios, etc) use portrait ratios.

Also, adding this increases the css file size by a mere 611 bytes from 223.188 bytes to 223.799 bytes (less than 0.3%).

**Comment by jnsdrtlf** [comment]
@yusufbicer I agree to @pieterjandesmedt. Landscape aspect ratios are already included. Why not portrait aspect ratios

**Comment by eppfel** [comment]
I also think this should be, does bulma provide this feature or not. And if so, then of course portrait should be supported.
