### ISSUE TITLE
All header tag sizes are being overrided.

### ISSUE THREAD

**Issue by baibhavprdn** [jgthms/bulma#1627]
This is about **Bulma **.

I'm pretty sure it's a bug. 

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]
My **browser** is: Google Chrome latest.

### Description
Basically, all my header tags are showing up the same size. Upon inspection, I found the font-size:100% in the minireset.sass file was overriding the initial font sizes of the headers.  Is this supposed to be normal??

### Expected behavior
Different header sizes for different header tags.

### Actual behavior
All the tags show the uniform header sizes.

**Comment by jgthms** [comment]
Check out #1603

You need to use the the `content` class: https://bulma.io/documentation/elements/content/

**Comment by baibhavprdn** [comment]
Hey thanks! I kept thinking it was a bug and not a deliberate design decision! I've been trying out Bulma and I love it so far.
