### ISSUE TITLE
Substitute for header-center

### ISSUE THREAD

**Issue by linkyndy** [jgthms/bulma#163]
I've seen you've removed `header-center` in the latest versions. Why is that? And how can I mimic the same behaviour?

Thanks and keep up the good work!

**Comment by jgthms** [comment]
`.header-center` was a bit dodgy to be honest. It was using transform to be centered, and was absolutely positioned. So it was prone to lots of errors.

Check out any version before 0.0.16 to see how it works!

**Comment by linkyndy** [comment]
I've seen its implementation and I agree with you. But I used to have a search box centered in my header; now I can't achieve this anymore. That's why I've asked if there's some other approach to do this.

**Comment by jgthms** [comment]
Do you have a jsfiddle so I can take a look?

**Comment by linkyndy** [comment]
No, I don't, but here's the relevant snippet I had in my app:

```
<header class="header">
  <div class="container">

    <div class="header-left">
      <div class="header-item">
        <%= link_to 'Home', root_path, class: "is-active" %>
      </div>
    </div>

    <% if local_assigns[:search] %>
      <div class="header-center">
        <div class="header-item">
          <%= render 'search' %>
        </div>
      </div>
    <% end %>

    <div class="header-right header-menu">
      <span class="header-item">
        <%= link_to 'Menu item', menu_item_path %>
      </span>
    </div>

  </div>
</header>
```
