### ISSUE TITLE
Q: Better sidebar support

### ISSUE THREAD

**Issue by rogeralsing** [jgthms/bulma#1630]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework** 

### Description
Question:

Are there any plans to add better support for sidebars ?
I've seen a few different examples, the most obvious ones are using "column is-2" to set the size of the sidebar.
This however makes the sidebar width change with the size of the window, which is not really what you want for such an element.
Expected behavior is likely fixed width until it change shape in order to be responsive.

It just seems to be such an fundamental part of many types of websites.

This question seems to be related to #1051 and #860.
But my question is, are we getting this baked in, in the framework?

**Comment by My1** [comment]
you can do one of 2 things:

1) set fitting widths for each breakpoint: 
https://bulma.io/documentation/columns/responsiveness/#different-column-sizes-per-breakpoint

or you can use a narrow column and define the needed size inside. that way the n-col will stay on its size while the rest of the page can do as needed.
https://bulma.io/documentation/columns/sizes/#narrow-column

**Comment by jgthms** [comment]
@My1 is right: you can use a narrow column with a fixed width.

The width itself can't be baked in the framework since you can't set an arbitrary value like that, it wouldn't make sense.
