### ISSUE TITLE
For using panel in Bulma

### ISSUE THREAD

**Issue by stevenxvii** [jgthms/bulma#1631]
This is about the Bulma **Docs**
I need help

Hello,

I am working on how to use the Panel, I read the Doc and example but I couldnt see how to filter the tabs.

How can I filter the items in each active panel-tab? I couldnt found any instruction for that, how can I add tab group for each item?

Thanks

**Comment by jgthms** [comment]
Bulma doesn't provide any JavaScript. But implementing tabs is quite simple. Check out [this tutorial](https://www.w3schools.com/howto/howto_js_tabs.asp) or use [jQuery UI](https://jqueryui.com/tabs/).
