### ISSUE TITLE
 "new feature" Buttons size without change font size.

### ISSUE THREAD

**Issue by NuruddinBadawi** [jgthms/bulma#1632]
### Description

someplace I want to make a large button but without effect to the font inside it, is it possible to increase button padding without change font size to make a large button?

I suggest this name: "button is-large-padding".

**Comment by timacdonald** [comment]
@nuruddinXbadawi I think you could achieve this already with:

```html
<a class="button is-large is-size-6">
    Large button w/ regular size text 👍
</a>
```

Check out the [typography helpers](https://bulma.io/documentation/modifiers/typography-helpers/#size) for more guidance.

**Comment by timacdonald** [comment]
Here is a quick demo: https://codepen.io/timacdonald/pen/oEWyJO
