### ISSUE TITLE
Feature request: input and label on same line ('inline form')

### ISSUE THREAD

**Issue by kfrn** [jgthms/bulma#1634]
This is about **Bulma**.

Is it a bug/feature/question or do you need help?  **feature request**

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.6.1

I've looked but didn't find such a request already.

### Description

It would be nice if the Bulma form controls included the ability to have an `input` and its `label` on the same line, i.e. as inline elements.

Bootstrap seems to have something like this, they call it an [inline form](https://getbootstrap.com/docs/4.0/components/forms/#inline).

### Expected behavior

something that looks like this:

```
email [________]
```

### Actual behavior

From the [Form Controls](https://bulma.io/documentation/form/general/) docs:  
<img width="642" alt="bulma-form-field" src="https://user-images.githubusercontent.com/16832997/35492496-0b9716a0-0512-11e8-8160-364f6c4a0b89.png">

**Comment by Wikiki** [comment]
Hi @kfrn,

I think you're looking for Horizontal form : https://bulma.io/documentation/form/general/#horizontal-form

**Comment by kfrn** [comment]
@Wikiki - thank you so much! I was searching for "inline" and so on, but I still can't believe I missed that. Cheers.
