### ISSUE TITLE
[question] Are the fonts used in Bulma available to use commercially?

### ISSUE THREAD

**Issue by AustinHatem** [jgthms/bulma#1636]
I see Bulma uses a version of Helvetica, I was under the impression Helvetica based fonts need special licenses. Are we allowed to use the standard Bulma fonts in commercial projects?

**Comment by LucyI** [comment]
Helvetica is a default system font on Macs. The Bulma font stack is calling the system font; users without Helvetica installed on their system will see the next font in the stack. 

You could purchase and load the Helvetica webfont if you want all visitors to see Helvetica.

**Comment by jgthms** [comment]
Thanks @Lucyl
