### ISSUE TITLE
Q: Change inputs size and keep center in cointainer and adapt box margins

### ISSUE THREAD

**Issue by moige** [jgthms/bulma#1640]
This is a question about Bulma.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]
My **browser** is: Chromium 64.0.3282.119 (64 bits)

### Description

How I can center inputs, with wdth change, inside an `.section.is-medium` -> `.container` -> `.box` and adapt `.box` margins to new positions of inputs?

### Steps to Reproduce

```html
<section class="section is-medium" id="root">
    <div class="box container">
        <form method="POST">
            <div class="field">
                <div class="control has-icons-left">
                   <input type="text" class="input" name="username" placeholder="Username">
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                </div>
            </div>
            ... #All others fields
        </form>
    </div>
</section>
```
```css
.input {
    width: 500px;
}

```
### Expected behavior

![export](https://user-images.githubusercontent.com/15069486/35692093-c7489546-0750-11e8-8e7f-57e5f35b6b38.png)

### Actual behavior

![2018-02-01-125816_1465x360_scrot](https://user-images.githubusercontent.com/15069486/35691769-c159630a-074f-11e8-83ed-2fe13cb72872.png)

**Comment by moige** [comment]
UPDATE: I already move inputs to center with `.has-addons .has-addons-centered`. But I can't still adapt the margins of `.box` to centered inputs. I try changing the width of `.container`, but this is recursive and affect al others `.container`.

**Comment by bcarneiro** [comment]
Try this:

`<section class="section is-medium" id="root">
			<div class="container">
				<div class="columns is-centered">
					<div class="column is-narrow">
						<div class="box">
							<form method="POST">
								<div class="field">
									<div class="control has-icons-left">
										<input type="text" class="input" name="username" placeholder="Username">
										<span class="icon is-small is-left">
											<i class="fas fa-user"></i>
										</span>
									</div>
								</div>
								... #All others fields
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>`

**Comment by moige** [comment]
![screenshot_4](https://user-images.githubusercontent.com/15069486/36063086-d2265e76-0e4e-11e8-985d-3d89d76e32e9.png)
Seems don't work. Get that.

**Comment by bcarneiro** [comment]
Did you change anything on the bulma files? I've just tried with the original files and worked just fine in Mac OS X 10.13.3 64-bit on Firefox 58.0.2 (64-bit),  Chrome 63.0.3239.132, Safari 11.0.3 and Opera 51.0.2830.26.
