### ISSUE TITLE
[Feature Request] - Mobile Sidebar Menu

### ISSUE THREAD

**Issue by Yard8** [jgthms/bulma#1645]
It would be great if we could have the option of adding a sidebar that scrolls out from the left or right when we hit the hamburger button. :)

**Comment by jgthms** [comment]
That's a bit tricky, since it can't be responsive like the current navbar menu. But it could exist as a Bulma extension!

**Comment by Wikiki** [comment]
Hi @Yard8,

you can use my <a href="https://wikiki.github.io/components/quickview/">quickview</a> extension to handle that.
I did it in one of my projects.

**Comment by VizuaaLOG** [comment]
@Wikiki Nice! Is there anything you haven't created an extension for :P
