### ISSUE TITLE
Strong tags are sometimes too dark

### ISSUE THREAD

**Issue by jbrooksuk** [jgthms/bulma#165]
For example, `.message-header` with a `strong` tag:

![image](https://cloud.githubusercontent.com/assets/246103/14324503/f5cd10d6-fc1c-11e5-89ac-2a8461fbf156.png)

**Comment by jgthms** [comment]
Ah yes, `strong` should inherit the colour in some cases.

**Comment by jgthms** [comment]
Fixed
