### ISSUE TITLE
How to set a variable for default Table style?

### ISSUE THREAD

**Issue by tsilcher** [jgthms/bulma#1658]
### Overview of the problem

This is about the Bulma **Docs**

### Description

I'd like to know **how to set a default style for tables** in Bulma.
I couldn't find any SASS [variable](https://bulma.io/documentation/overview/variables/) declarations for this. I'd like to set all of my **tables** to be of [class](https://bulma.io/documentation/elements/table/#modifiers) `is-striped` by default. I cannot even add this manually as my website is rendered from _Markdown_ files and adding html in there breaks the table.

If its not possible to set the style via a variable then I'd like you to consider this as a feature request.
Thanks!

**Comment by rcubitto** [comment]
You are trying to use Bulma but you can't implement CSS classes at all?

**Comment by tsilcher** [comment]
Please read carefully what I wrote before commenting. Thanks.

**Comment by rcubitto** [comment]
Sorry if my question sounded a bit offensive, I was trying to understand the context.

If you can't edit your markup, but you do have a sass file where you import Bulma, you could try injecting the css classes you require, into each element.

```scss
table {
    @extend .table;
    @extend .is-striped;
}
```
