### ISSUE TITLE
column with is-overlay has wrong height

### ISSUE THREAD

**Issue by Budy-Love** [jgthms/bulma#1659]
This is about **Bulma**.
### Overview of the problem

I'm using Bulma **version** [0.6.2] 
My **browser** is: Chrome 65

### Description

Hello,

i have a probem with my columns. i use the following structure
```html
<div class="columns">
    <div class="column">My Side Menu</div>
    <div class="column">My Content</div>
    <div class="column is-4 is-overlay is-offset-8>My Notifications (toggleable)</div>
</div>
```
### Steps to Reproduce

[codepen](https://codepen.io/budy/pen/wyqZBq)

### Expected behavior

I expect the same height across all columns

### Actual behavior

The is-overlay column has it's own height.

**Comment by jgthms** [comment]
The `is-overlay` class simply makes the target element the first positioned ancestor. In this case, it's the page itself.

**Comment by jordilanctot** [comment]
Also you are missing a closed quotation mark.
You wrote in the example above:
`<div class="column is-4 is-overlay is-offset-8>`
and it should be instead
`<div class="column is-4 is-overlay is-offset-8">`
You should check if the issue in your code may be caused by this typo
