### ISSUE TITLE
More options for panel tabs

### ISSUE THREAD

**Issue by dominikmayer** [jgthms/bulma#166]
Is there a way to play with the panel tabs? Like having a separator?

I want to put a link into the row with the panel tabs but have it pulled right. `is-pulled-right` seems not to work.

**Comment by julianorafael** [comment]
Well, If all you want to do it is pulling it to the right, you can do it with `order: 1` (it can be anything higher than 0) property applied direct to the link. Regarding the separator, I don't what would be the best approach. A pipe?

**Comment by dominikmayer** [comment]
I played around with the `order` property but it only changes the position of the one tab relative to the others.

Now I have:

`|.........A B C.........|`

What I want to achieve:

`|.........A B .........C|`

**Comment by julianorafael** [comment]
One way to achieve this is to add a `position: relative` to `.panel-tabs`. Then you add `position: absolute; right: 0` to the element you want on the right.

**Comment by TroyAlford** [comment]
The more flexboxy way would be to assign C `margin-left: auto`

**Comment by julianorafael** [comment]
> The more flexboxy way would be to assign C `margin-left: auto`

But that pulls all the other tabs to the left.

**Comment by dominikmayer** [comment]
The `position` trick works. Thanks, everyone.

@julianorafael, should I close this issue? I still think it would be a great addition to bulma if `is-pulled-right` worked.

**Comment by julianorafael** [comment]
@dominikmayer, I believe we should find a scalable solution to this problem and add it to bulma. The position trick works only to one link. I think we need a div that pulls all the links inside it to the right or left of the nav-tabs.

**Comment by RX14** [comment]
Why was this closed? Is this possible now?

**Comment by Nicolasome** [comment]
^ I think adding this feature should be further looked into.
