### ISSUE TITLE
Color of hero-head or footer

### ISSUE THREAD

**Issue by melTr** [jgthms/bulma#1662]
Tell me if I'm wrong, but I couldn't easily change color of hero-head (not hero) or footer by adding _is-primary_?
Thanks!
Mel

**Comment by jgthms** [comment]
That is correct. It only applies to hero itself!

**Comment by melTr** [comment]
Euh ok, so how I changed them? Only by custom.css?

**Comment by octoshrimpy** [comment]
@melTr if yo're using scss/sass and not just the compiled css, you can use this as a mixin to include bulma's `is-color` into any component:

```@mixin bulma-is {
  @each $name, $pair in $colors {
    $color: nth($pair, 1);
    $color-invert: nth($pair, 2);

    &.is-#{$name} {
      background-color: $color;
      border-color: transparent;
      color: $color-invert;
    }
  }
}
```
