### ISSUE TITLE
Browser's validity message is not visible for `file` input.

### ISSUE THREAD

**Issue by kornicameister** [jgthms/bulma#1664]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]
My **browser** is: `Chromium Version 62.0.3202.94 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)`

### Description

I'd expect that for file input we will be able to see browser validity error, similar to what we can see in plain `input` or `select` even if enriched with Bulma's `input` or/and `select` classes. However the validity message from the browser is not visible.

### Steps to Reproduce

```
<div className="file has-name is-small">
        <label className="file-label" htmlFor="file">
          <span className="file-cta">
            <span className="file-icon">
              <i className="fa fa-upload" />
            </span>
            <span className="file-label">Upload file</span>
          </span>
          <span className="file-name">Some file</span>
        </label>
        <input
          id="file"
          className="file-input"
          type="file"
          name="file"
          required
        />
</div>
```

### Expected behavior

The browser's validity message is visible near to the field

### Actual behavior

The browser's validity message is not visible at all

**Comment by jgthms** [comment]
Yes for the file input to work, the browser input needs to be reduced to a very small size. It’s because the file input is impossible to style, so you need to use a hack like this. 

The solution here is to use a regular file input. Or handle the error with JS.

In any case, the documentation should mention this limitation. Could you make a PR?

**Comment by kornicameister** [comment]
Ah, I was thinking that maybe there's some magical way to bring this up to the surface even though it's for the, let's say `hidden`, file input.

I cannot promise to make the PR, certainly I cannot do it now ;(.
I might have time in the evening though.

**Comment by kornicameister** [comment]
@jgthms I've created, finally, the little doc PR. No idea if that's how you do the stuff and if the explanation is really sufficient. Let me know in the PR, I will reply and update if necessary in there.
