### ISSUE TITLE
Columns is not flex

### ISSUE THREAD

**Issue by atilkan** [jgthms/bulma#1667]
**columns**  is not flex by default. 
So this won't work -> **.columns.is-vcentered**
Adding **is-desktop** or **is-mobile** etc makes it flex. I think this is fundamentally wrong.

**Comment by jgthms** [comment]
By default, columns are only activated from tablet onwards. This means columns are stacked on top of each other on mobile. 
If you want columns to work on mobile too, just add the is-mobile modifier on the columns container.
See https://bulma.io/documentation/columns/responsiveness/

**Comment by atilkan** [comment]
So i can arrange flex order if i add **is-mobile**? Flexbox has options to act like block. This is not a good reason to use block on mobile. I am not there yet but i guess bulma doesn't have source-ordering.
