### ISSUE TITLE
index out of bounds 

### ISSUE THREAD

**Issue by stewwan** [jgthms/bulma#1668]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.2]
This is a **Sass** issue: I'm using latest Ionic

### Description

just cant run with Ionic

### Steps to Reproduce

1. setup an ionic environment with a sample app
2. npm install --save bulma
3. on `app.scss` import bulma

@import "node_modules/bulma/sass/utilities/_all";
@import "node_modules/bulma/sass/grid/columns";
@import "node_modules/bulma/sass/layout/hero";
@import "node_modules/bulma/sass/elements/progress";
@import "node_modules/bulma/sass/components/modal";

4. run ionic serve

### Expected behavior

compile

### Actual behavior

index out of bounds for `nth($list, $n)`

![screen shot 2018-02-16 at 1 36 34 pm](https://user-images.githubusercontent.com/719763/36315708-7cdf24cc-131f-11e8-887f-d7bd066444ef.png)

**Comment by jgthms** [comment]
What’s in your $colors variable map?

**Comment by stewwan** [comment]
what comes with ionic.
`variables.scss`

```sass
$colors: (
  primary:    #2a7dc2,
  secondary:  #32db64,
  danger:     #f53d3d,
  dark:       #222,
  white:    #fff,
  light: (
    base: #242424,
    contrast: #f4f4f4
  )
);
```

**Comment by stewwan** [comment]
it would be great if bulma had your own color variable name..

**Comment by stewwan** [comment]
https://github.com/jgthms/bulma/issues/1482

**Comment by miliodas** [comment]
@stewwan  did u figure out how to use it

**Comment by EresDev** [comment]
Similar issue. 

`ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/sty
les.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                  ^
      Index out of bounds for `nth($list, $n)`
      in E:\Google Drive\PhpStorm\Projects\EresNote\src\styles\bulma\sass\elements\button.sass (line 113, column 20)
`

**Comment by EresDev** [comment]
My problem is solved. I also accidentally included bootstrap with bulma in scss (because I was working with bootstrap before bulma). When I removed bootstrap scss, I am not getting this error anymore.

**Comment by hsu-w** [comment]
to solve this problem you have to edit [`sass/utilities/derived-variables.sass`](https://github.com/jgthms/bulma/blob/master/sass/utilities/derived-variables.sass)

`$colors: mergeColorMaps(("white": ($white, $black), "black": ($black, $white), "light": ($light, $light-invert), "dark": ($dark, $dark-invert), "primary": ($primary, $primary-invert), "link": ($link, $link-invert), "info": ($info, $info-invert), "success": ($success, $success-invert), "warning": ($warning, $warning-invert), "danger": ($danger, $danger-invert)), $custom-colors) !default;`
to
`$colors-pre: mergeColorMaps(("white": ($white, $black), "black": ($black, $white), "light": ($light, $light-invert), "dark": ($dark, $dark-invert), "primary": ($primary, $primary-invert), "link": ($link, $link-invert), "info": ($info, $info-invert), "success": ($success, $success-invert), "warning": ($warning, $warning-invert), "danger": ($danger, $danger-invert)), $custom-colors) !default;`

`$colors: $colors-pre;`

problem solved!

**Comment by mfranzke** [comment]
As the solution targets overwriting the `$colors` SCSS "array", that has been defined in ionics files (or in other words: out of bulma), which wouldn't happen due to bulmas correct usage of the `!default` declaration, it seems like another solution w/o editing the bulma library files directly (would harm updates etc.), you could even also use the following declaration before including the bulma.scss file within your project:
`$colors: null;`
