### ISSUE TITLE
Input type="search" with .is-loading class

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#1671]
This is about **Bulma**.

I'm not sure if it's a bug or black magic.

### Overview of the problem

This is about the Bulma **CSS framework** and maybe **the Docs**

I'm using Bulma **version** 0.6.2

My **browser** is: Google Chrome

### Description

I often use `<input type"search">` because a clear control appears when hovering / focusing the input and that's really useful to have with no extra logic. I don't know how this happens but I like it:). I didn't found this documented. Before 0.6.2 the `type=search` input was always rounded, but since 0.6.2 this can be controlled to, and that's very good.

It would be nice to be able to use this "feature" together with `.is-loading` class. Now the clear control is placed over the spinner.

I tried to fix this by myself, because I can't wait to have an actual contribution on Bulma, but I couldn't understand how the clear control appears in the first place :).

### Steps to Reproduce

```
<div class="control is-loading">
      <input class="input" type="search">
</div>
```

### Expected behavior

The spinner and the delete button should appear one next to another.

I think that this should be documented because it's really useful.

### Actual behavior

The spinner and the delete control overlap.

![image](https://user-images.githubusercontent.com/16073274/36350814-38460770-14a7-11e8-9f0d-5411b87ae4e8.png)

### Workaround

Using vue, and controlling `.is-active` with a `loading` flag I am able to do `:type="loading ? 'text' : 'search'` and that works ok.

**Comment by jgthms** [comment]
The clear control is defined by the browser.

What you could do is create an “control is-loading is-loading-search” and move the spinner left a bit. But since the clear icon is browser-specific, and the position is not defined in css, it can’t be included in Bulma core but only in your setup if you want.
