### ISSUE TITLE
Tablet breakpoints are strange

### ISSUE THREAD

**Issue by samburgers** [jgthms/bulma#1672]
Currently, breakpoints are

```
mobile: up to 768px
tablet: from 769px
desktop: from 1024px
widescreen: from 1216px
fullhd: from 1408px
```

Obviously there are many sized "tablets" on the market, but a standard ipad screen width is either 1024px wide (landscape) or 768px wide (portrait)... the above breakpoints mean that iPad in landscape would inherit the `desktop` breakpoints, and in portrait mode would inherit the `mobile` breakpoints. 

So tablet breakpoints wouldn't even be shown at all on a regular ipad. Or am i missing something?

should it be changed to something like this?

```
tablet: from 768px to 1024px;
desktop: from 1025px
```

**Comment by atilkan** [comment]
I think the numbers are not important at all. They should be something easy to remember like 700, 1000, 1200, 1400.

**Comment by jgthms** [comment]
There’s the tablet variable that defines the breakpoint. And there’s the tablet mixin that means “from tablet breakpoint onwards”, in landscape mode. 

You can easily change the breakpoint value since it’s a Sass variable. This would actually update the mixin as well.

**Comment by lukepighetti** [comment]
This is what I use on all my Bulma projects. With these breakpoints, I wish they were named

```
is-mobile
is-tablet
is-laptop
is-desktop
is-widescreen
```

```
//$gap: 32px;
$tablet:	568px;
$desktop:	896px + (2 * $gap);
//$widescreen:	1152px + (2 * $gap);
//$fullhd:	1344px + (2 * $gap);
```

**Comment by isaumya** [comment]
I also have no idea why bulma does this wired thing out of the box and why this still hasn't been fixed in the out of the box version. This was the only reason we always hesitated to use bulma on our live projects despite loving it. I think these breakpoints should be fixed ASAP and also more breakpoints should be provided like bootstrap. I really like the bootstrap breakpoints.
