### ISSUE TITLE
columns naming

### ISSUE THREAD

**Issue by atilkan** [jgthms/bulma#1673]
I liked Bulma, a lot. Thanks for this. 
Reasons to change columns to row.
- columns is very similar to column, hard on eyes to distinguish. 
- columns is actually row. 
- row is shorter, cleaner.

**Comment by jgthms** [comment]
Most users actually like the naming conventions. And columns can have multiple rows so it wouldn’t work and would break a lot of setups.

**Comment by atilkan** [comment]
Not a good reason since the version already indicates that.
