### ISSUE TITLE
Use flex properly, Remove floats.

### ISSUE THREAD

**Issue by izzygld** [jgthms/bulma#1675]
### Overview of the problem

This is about the Bulma **CSS framework** 

### Description

Use Flex properly, In your template [https://dansup.github.io/bulma-templates/templates/forum.html#] (https://dansup.github.io/bulma-templates/templates/forum.html#) you are using the `pull-right` class to float right the comment icon.
It should really be inside the flex container and added `margin-left: auto;`.

**Comment by jgthms** [comment]
Wrong repo. It’s here: https://github.com/dansup/bulma-templates
