### ISSUE TITLE
Delete buttons on tags

### ISSUE THREAD

**Issue by mauriciosoares** [jgthms/bulma#168]
Hey! great work on Bulma :)

This issue is more like a question, I think the close button on [tags](http://bulma.io/documentation/elements/tags/), when I'm hovering it, the color should be similar to the color of the [notifications](http://bulma.io/documentation/elements/notifications/). It keeps the same color, but makes it a little bit darker.

It's kinda strange to show a red inside a yellow/blue/green button... What you think?

![download](https://cloud.githubusercontent.com/assets/2321259/14436220/115c8d08-fff2-11e5-820c-bb06a67288f1.png)

**Comment by jgthms** [comment]
That's a fair point. Calculating a readable color can be tricky sometimes, that's why I kept the default one. But this could be improved.

**Comment by mauriciosoares** [comment]
Totally, maybe you could play with opacity, `1` for unhovered and `.7` for hovered. I think that would be a smooth color transition.

Just an idea though.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jgthms** [comment]
Fixed in 0.0.19

**Comment by mauriciosoares** [comment]
cool!

that looks better IMO.
