### ISSUE TITLE
navbar vertical?

### ISSUE THREAD

**Issue by vortechron** [jgthms/bulma#1684]
hi @jgthms , i love your css framework. it will be great if u could add navbar vertical so that user can create navbar for their admin panel. (: just feature suggestion

**Comment by tiberiur** [comment]
I think the menu component is what you want https://bulma.io/documentation/components/menu/

**Comment by jgthms** [comment]
Indeed!

**Comment by GraceAdams** [comment]
the difference is that navbar is setup to fill the width of the screen, and has the navbar-start and navbar-end structure. Menu works ok, but doesn't seem to have the option to fill the vertical space of the screen, and doesn't have a way to place things at the bottom of the screen.
