### ISSUE TITLE
strage behaviour on button with "is-outlined" and "is-loading"

### ISSUE THREAD

**Issue by roti** [jgthms/bulma#1686]
This is about **Bulma.

It is a Bug, but I'm not sure if it's in Bulma. It may be related to Fontawesome, or even the Browser.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.6.2]
My **browser** is: Chomium  64.0.3282.167, Firefox 58.0.2
I am sure this issue is **not a duplicate**

### Description

I have a strange behaviour with "is-loading" and "is-outlined" on a button.

### Steps to Reproduce

I am using Bulma with React.JS. 
Initial state: `<button class = "button is-primary is-outlined" >Clickme</button>`
After click, the rendered element is `<button class = "button is-primary is-outlined is-loading" >Clickme</button>`

### Expected behavior

The button is primary, outlined and the loader is visible.

### Actual behavior

The button is primary, not outlined and neither the loader not the label are visible (button is green and empty). 

In Chrome, when hiding the browser window (alt-tab), and then displaying it again, the button is shown correctly as long as the alt key is still pressed. When the alt key is released button is shown incorrectly again. After pressing the "Select element" in Developer Tools (ctrl-shift-c) the button is displayed correctly and stays that way.

The behaviour is ok when "is-outlined" is not part of the css classes of the button. "is-loading" also works correctly for `<input/>`

Common sense would indicate that it would be a browser bug, but it's still strange that it occurs in both Chrome and Firefox. I'm raising this issue in the hope of finding at least a workaround, should that be the case.

**Comment by ptescayola** [comment]
@roti Yes, it seems that bulma have a weird behavior with buttons that have class 'is-outlined' and the 'is-loading'.

My solution at moment has been modify the loading when button has a different state.

```
.button.is-outlined.is-loading
    &:hover, &:focus, &:active, &:visited
        &::after
            border-color: transparent transparent #fff #fff !important
```
I hope it helps.

**Comment by sokoji** [comment]
I have the same problem. Solution from @ptescayola and @codeofsumit works fine. What about to add it to the source code?

**Comment by codeofsumit** [comment]
This issue should not be closed as the bug is still open
