### ISSUE TITLE
Customize Navbar burger dropdown background color

### ISSUE THREAD

**Issue by timqian** [jgthms/bulma#1688]
Looked into the doc, seems user is not able to modify the background color of navbar burger dropdown, it is always white. It will be helpful to add this feature.
<img width="401" alt="screen shot 2018-02-25 at 1 55 19 pm" src="https://user-images.githubusercontent.com/5512552/36638581-a107265e-1a33-11e8-9f02-8755c08e7d4f.png">

**Comment by FlorKaucic** [comment]
@timqian hey, I think you can modify it by setting a value for `$navbar-background-color` before you import bulma.
More info on how to customize variables [here](https://bulma.io/documentation/overview/customize/)

**Comment by timqian** [comment]
@FlorKaucic Thanks, this works for me.
