### ISSUE TITLE
is-info does not change color when setting new color in sass file

### ISSUE THREAD

**Issue by barohatoum** [jgthms/bulma#169]
Thanks for helping out! 😇

### Prerequisites

If it's a bug on the **website**, submit an issue on the appropriate repository: [https://github.com/jgthms/bulma-website](https://github.com/jgthms/bulma-website)

* [x] Is this about Bulma the **CSS framework** and **not** about the Bulma website?
* [0.0.19] Which **version** of Bulma are you using?
* [Google Chrome] Which **browser** are you using?
* [ ] If it's a **Sass** issue, which version of Sass are you using?
* [x] Are you sure this issue is not a **duplicate**?

### Description

When i set the color of $info in my imports.scss file right below the generated-variables.sass file, the change doesn't apply
[Please tag accordingly]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

_Expected behavior:_ the color of is-info class to reflect the new color
_Actual behavior:_ nothing
<img width="1450" alt="capture" src="https://cloud.githubusercontent.com/assets/1402924/14449436/eddefe02-0040-11e6-9a71-71cbc5e2c6cf.PNG">
<img width="699" alt="capture1" src="https://cloud.githubusercontent.com/assets/1402924/14449437/eddf1b8a-0040-11e6-984b-50262cecb802.PNG">

**Screenshots** are more than welcome!

**Comment by jgthms** [comment]
You need to set the `$colors` array again: https://github.com/jgthms/bulma/blob/master/bulma/config/generated-variables.sass#L16
