### ISSUE TITLE
Feature request: small container

### ISSUE THREAD

**Issue by danieldaeschle** [jgthms/bulma#1692]
### Description

Can you please provide a `small-container`?
An example ist: `width: 80%; max-width: 600px; `
And on mobile `width: 100%`.

**Comment by jgthms** [comment]
Why not use sized columns?

**Comment by danieldaeschle** [comment]
Because it is a ugly workaround.

**Comment by VizuaaLOG** [comment]
I think columns are the best use case for this. If you want to instead have a custom container then that should be specific to your project and not in the core.

**Comment by danieldaeschle** [comment]
There is no column which has a max with of 600px and with 80%.
I need to use 3 columns to center one.
Why i have to implement a small container to every project?
There are many websites which have a small container. I think you can implement it in the core.

**Comment by VizuaaLOG** [comment]
You can use column offsetting. So you have a single column that will then be positioned where you want it. The way you implement it is up to you, for example as an extension that you can pull in to the projects that need it. Bulma is a component/helper library, something you use as a starting point. It should be added to for every niche feature users need. That would make it way too bloated and potentially confusing.

**Comment by VizuaaLOG** [comment]
To expand on my reply. If a. Container that's 80% wide was added. Why not add 90%, 70%, 60% etc. It'll add too much bloat.

Also, if I'm not mistaken I believe there is a SASS variable to change the container width. I could be wrong though.
