### ISSUE TITLE
Responsive form addons

### ISSUE THREAD

**Issue by dsernst** [jgthms/bulma#1694]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.6.2]

I didn't find any **duplicate issues**.

### Description

I have a text input with an addon submit button.

On a normal sized desktop screen it looks great:

<img width="607" alt="screen shot 2018-03-01 at 2 23 41 am" src="https://user-images.githubusercontent.com/6340841/36839890-216a1f6a-1cf8-11e8-80d4-27273d372ff9.png">

But on a smaller screen — here's an iPhone 5 (width 320px) — the addon button almost completely covers the input field:

<img width="319" alt="screen shot 2018-03-01 at 2 25 16 am" src="https://user-images.githubusercontent.com/6340841/36839943-478fee5e-1cf8-11e8-8d06-9cf0b0800b55.png">

### Expected behavior

This is what I want it to look like for smaller screens:

<img width="318" alt="screen shot 2018-03-01 at 2 33 06 am" src="https://user-images.githubusercontent.com/6340841/36840211-0b815c9e-1cf9-11e8-83ba-b927252ecf53.png">

I manually did this for this screenshot by removing `has-addons` from the `.field` container, and adding `.is-fullwidth` to the button. 

Some sort of responsive addons helper class, e.g. `has-addons-desktop`, would be great.

### Actual behavior

I'll probably manually hack over it with media queries.

But I wanted to raise this issue in case Bulma already has a way to accomplish this that I'm missing, or if this is something you're willing to add.

**Comment by dsernst** [comment]
So I got this working in a hacky way by writing the appropriate code twice:

```html
<div class="is-hidden-touch">
  <div class="field has-addons">
     ..old code..
  </div>
</div>

<div class="is-hidden-desktop">
  <div class="field">
     ..modified code..
  </div>
</div>
```

This seems to be working, although it required a lot of duplicated code — there's a lot more logic than visible in the screenshots.

I'm going to close this issue since it's no longer pressing for me. 

Writing it up helped me realize this solution. `¯\_(ツ)_/¯`

**Comment by dsernst** [comment]
Actually this isn't so great because now there are two `<input>`s, so if the page is resized the content is lost. Maybe could hook up their data to be bound together.

But wish there was a simpler solution.

**Comment by dsernst** [comment]
Eh, wasn't able to quickly achieve the effect I was going for without a ton of extra logic. 

So I've settled on this simpler compromise for now:


```html
<div class="control">
  <div class="is-hidden-touch">
    <button class="button is-info" type="submit"><strong>Create Account</strong></button>
  </div>
  <div class="is-hidden-desktop">
    <button class="button is-info" type="submit"><strong>Join</strong></button>
  </div>
</div>
```

Just shortening the button text when on small screens. 

<img width="312" alt="screen shot 2018-03-01 at 11 39 39 pm" src="https://user-images.githubusercontent.com/6340841/36888362-0519eedc-1daa-11e8-85bc-c30d3aecf1c6.png">

Not ideal, but it works.

**Comment by hostis912** [comment]
You can do something like:

@include until($desktop) {
.field.has-addons.has-addons--desktop {
display: block;

 .control {
 &:not(:last-child) {
margin-bottom: 0.75rem;
}

button {
width: 100%;
 }
 }
 }
}

**Comment by codeofsumit** [comment]
@fvcproductions works like a charm 👍
