### ISSUE TITLE
Icon only tab rendered incorrectly

### ISSUE THREAD

**Issue by obates** [jgthms/bulma#1695]
This is about **Bulma**.

This is a bug with Bulma

### Overview of the problem

I'm using Bulma **version** [0.6.2]
My **browser** is: Chrome 64.0.3282.119
I am sure this issue is **not a duplicate**

### Description
Multiple rendering issues when using boxed/toggle tabs when a tab contains only an icon (no text).

![eg1](https://user-images.githubusercontent.com/5786673/36848632-bf8aad48-1d59-11e8-9528-7f867dc4a725.PNG)
![eg2](https://user-images.githubusercontent.com/5786673/36848630-bf6df3a6-1d59-11e8-8dd3-a1a853d9c840.PNG)
![eg3](https://user-images.githubusercontent.com/5786673/36848629-bf51048a-1d59-11e8-8022-b6c96f6d34e6.PNG)

### Steps to Reproduce

```
<div class="tabs is-toggle">
  <ul>
    <li class="is-active">
      <a>
        <span class="icon is-small"><i class="fas fa-image"></i></span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-music"></i></span>
        <span>Music</span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-film"></i></span>
        <span>Videos</span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-file-alt"></i></span>
        <span>Documents</span>
      </a>
    </li>
  </ul>
</div>
```

### Expected behavior

Correct rendering of the tabs

### Actual behavior

Offending tab's height appears to be too small, resulting in the rendering issues shown above

**Comment by aelharrak** [comment]
Hi @obates : You should to remove the **is-small** class when you don't have a text into link

`<div class="tabs is-toggle">
  <ul>
    <li class="is-active">
      <a>
        <span class="icon"><i class="fas fa-image"></i></span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-music"></i></span>
        <span>Music</span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-film"></i></span>
        <span>Videos</span>
      </a>
    </li>
    <li>
      <a>
        <span class="icon is-small"><i class="fas fa-file-alt"></i></span>
        <span>Documents</span>
      </a>
    </li>
  </ul>
</div>`

**Comment by obates** [comment]
Whilst that does fix the tab rendering issues, the icon becomes disproportionately sized compared to the others

![eg4](https://user-images.githubusercontent.com/5786673/37086223-f39e51ae-21ee-11e8-89f8-fe7edce2ce71.PNG)
