### ISSUE TITLE
Form rendering is off within a `summary` section

### ISSUE THREAD

**Issue by yatesco** [jgthms/bulma#1696]
This is about Bulma.
### Description
Forms rendered inside a `<details>` inside a `<nav>` don't render correctly. If I remove the `<details>` and `<summary>` tag then the form renders correctly. Specifically, the broken form extends past the right hand side of the containing `div`.

In the screenshot you can see both a working and non-working form:

![screen shot 2018-03-02 at 21 57 18](https://user-images.githubusercontent.com/181469/36923956-cf983f5a-1e64-11e8-81d9-221475973b6e.png)

The broken form is configured:
```html
<nav className="panel">
    <details open>
        <summary className="panel-heading">Forms look good inside collapsible panels</summary>
        <p className="panel-header">
            <div className="panel-block">
                <form>...</.form>
            </div>
        </p>
    </details>
</nav>
```

The working form is configured:

```html
<nav className="panel">
    <p className="panel-heading">Forms look good inside static panels</p>
    <p className="panel-header">
        <div className="panel-block">
            <form>...</.form>
        </div>
    </p>
</nav>
```

**Comment by yatesco** [comment]
The original issue shows `<input type="text"...`, however the rendering is much worse for `select` items:
![screen shot 2018-03-02 at 22 26 33](https://user-images.githubusercontent.com/181469/36925049-e972d792-1e68-11e8-8a00-96ce9abc9be3.png)

**Comment by aelharrak** [comment]
Hello @yatesco  : i was create an new pull request for this issue :)

BR,
Amine

**Comment by dailycommit** [comment]
@aelharrak Thank you for the fixes but you should also add
``box-sizing: border-box`` to ``.control``class

see: https://www.dropbox.com/s/ribss13dei8l0n8/bulma-box-sizing.mp4?dl=0
