### ISSUE TITLE
what is the motivation for this project?

### ISSUE THREAD

**Issue by aleksey-bykov** [jgthms/bulma#17]

**Comment by jgthms** [comment]
A few things:

* **simpler markup**: flexbox doesn't require as much nesting and as many tweaks like clearfixes or min-heights
* **new features**: flexbox allows to things that were almost impossible without any JavaScript
* **easy modifier classes**: I prefer having a base class like `button` and modify the style on top of that, by using a pre-determined syntax, which is that every modifier class should start with `is-`
* **learning**: this project has taught me a lot about flexbox, its pros and cons

**Comment by mrcsmcln** [comment]
Did Dragon Ball have anything to do with naming it?

**Comment by jgthms** [comment]
Absolutely.

Initially, the project was supposed to be a **theme generator** named **Trunks** but trunks.io was unavailable.

I imagined dividing the generator into _"capsules"_ that you would choose a selection from to generate the theme you want. That's where the name **Bulma** came into mind, as her father founded Capsule Corp.

Then the project became a CSS framework instead, but the name stayed.

**Comment by jenius** [comment]
What are the thoughts on browser support?

**Comment by MelchnerRoman** [comment]
Which browsers are supported?

**Comment by joearcher** [comment]
http://caniuse.com/#feat=flexbox

**Comment by iJaack** [comment]
Do you have other implementations in mind? If so, which?

**Comment by stur86** [comment]
I love this. I thought the reference must be there because the combination of name + colour scheme definitely seemed too much. That hair colour is way too distinct :smile: .

**Comment by slidenerd** [comment]
Well atleast the project is not called "Super Saiyan God Super Saiyan Ultra Instinct Kaoiken Times 20"
