### ISSUE TITLE
[question] Make child div in modal on top this modal

### ISSUE THREAD

**Issue by vystepanenko** [jgthms/bulma#1700]
hello!
Here i have modal https://jsfiddle.net/4c0feb89/8/ 
Inside this modal i have child component. When I show him it increase size of modal.
Is there any way to make my red div on top of rhe modal?

Something like this:
![default](https://user-images.githubusercontent.com/22811452/36983101-2de4a756-209a-11e8-8983-e3097be9f083.png)

**Comment by jgthms** [comment]
You need another modal with a higher z-index.
