### ISSUE TITLE
Website layout bug

### ISSUE THREAD

**Issue by atilkan** [jgthms/bulma#1701]
<img width="811" alt="screen shot 2018-03-05 at 22 38 10" src="https://user-images.githubusercontent.com/1254613/36995818-377dc640-20c6-11e8-9232-044edbb2ff43.png">

**Comment by jgthms** [comment]
Disable your ad blocker 😉

**Comment by VizuaaLOG** [comment]
I had this issue a few months back. @jgthms is worthy of my ad blocker whitelist 😉

**Comment by atilkan** [comment]
ok, thanks.
