### ISSUE TITLE
Navbar-menu hidden on touch by default

### ISSUE THREAD

**Issue by justjoolz** [jgthms/bulma#1702]
This is about **Bulma **.
I'm using Bulma **version** [0.6.2] 

### Description

Quick question/feature request. 

Is there an easy way to override the default settings for the navbar component. In particular I want to have a usermenu on the right instead of the burger menu button. And override the default that move menu items below the brand section on touch devices.

I think it's very common to have a avatar with pull down menu in the top right corner and it would be good to have some support for this 'out of the box'

**Comment by aelharrak** [comment]
Hello justjoolz,

Could you please attach a simple file example to know more about this issue.

BR,

**Comment by justjoolz** [comment]
Made this quickly to illustrate the scenario.

https://codepen.io/j00lz/pen/oEKeGY?editors=1000#0
https://s.codepen.io/j00lz/debug/oEKeGY/vWMRwndwWGWr#

**Comment by tunnckoCore** [comment]
@jgthms it's still an issue. Any ideas?

**Comment by aelharrak** [comment]
Hello,

The pull request is not yet merged by owner !

BR,
Amine

**Comment by tunnckoCore** [comment]
Which pull request? Why it isn't linking this issue?

**Comment by munrocket** [comment]
@aelharrak which pull request?

**Comment by kalenpw** [comment]
Similarly an option to have permanently available options on the right hand side would be nice, ie have an option to override the automatic hiding over `.navbar-menu`

**Comment by tunnckoCore** [comment]
Ping pong.

**Comment by tunnckoCore** [comment]
Nah.

**Comment by tunnckoCore** [comment]
Aaah.
