### ISSUE TITLE
Repatitive Modal Property Written

### ISSUE THREAD

**Issue by arvindkalra** [jgthms/bulma#1703]
This is about **Bulma Bug**.

### Overview of the problem

I'm using Bulma **version** [0.6.2] 
There is non required css written. 

### Description

The CSS written for the modal class has position property written twice once its value is absolute though it is overidden again with value fixed. Both of them are written in same file under the same selector. So it is redundant so should be removed.
Please Assign me this issue.

![123456](https://user-images.githubusercontent.com/29686907/37031023-35a64e3a-2163-11e8-97fd-0910634bd483.png)

**Comment by jgthms** [comment]
It’s because it uses the overlay mixin.
