### ISSUE TITLE
`.navbar-item.is-tab.is-active` doesn't honor parent class of `is-info, is-warning, is-error etc`

### ISSUE THREAD

**Issue by TheHandsomeCoder** [jgthms/bulma#1705]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

This may be because I'm using the framework incorrectly but I will flag it just in case.
I have styles my navbar using is-error and have noticed that the active tab border-bottom-color will always stay blue rather than switch to an appropriate inverse. 

### Steps to Reproduce

``` html
<div><nav class="navbar is-warning" role="navigation" aria-label="main navigation"><div class="container"><div class="navbar-brand"><a class="navbar-item" href="#">Header</a></div></div></nav><nav class="is-warning" role="navigation" aria-label="secondary navigation"><div class="container"><div class="navbar-brand"><a class="navbar-item is-tab is-active" href="#">DOCUMENTS</a><a class="navbar-item" href="#">MAPS</a></div></div></nav></div>
```

### Expected behaviour

The underline is an appropriate color depending on what the navbar background color is
### Actual behaviour

The underline remains blue regardless of the color

**Comment by aelharrak** [comment]
Hello @TheHandsomeCoder ,

I think this is not a bug, you need just to override with your custom **color** and **border-bottom-color** on the following lines :

.navbar-item.is-tab.is-active.is-info { .... } 
.navbar-item.is-tab.is-active.is-warning { .... } 
.navbar-item.is-tab.is-active.is-error{ .... } 
....etc

BR,
Amine

**Comment by TheHandsomeCoder** [comment]
@aelharrak I'm not using a custom colour, I'm using the Bulma defaults.

**Comment by aelharrak** [comment]
@TheHandsomeCoder : Fix done but i'm waiting for a pull request
