### ISSUE TITLE
`has-text-centered` - Possibly an error in online documentation.

### ISSUE THREAD

**Issue by alex-kovac** [jgthms/bulma#171]
http://bulma.io/documentation/navbar/ -> Centered navbar

The code example on the website shows class `has-text-centered`
Could this be perhaps `is-text-centered`? I am unable to find `has-text-centered` in the stylesheets.
Then again, I might be wrong...

Thanks for making Bulma!

**Comment by jbrooksuk** [comment]
Are you using the latest version?

**Comment by alex-kovac** [comment]
Now, that was fast!

Oh... wait no. 0.0.17!
I will update... 
I... failed... at... the... basics :) the shame...
