### ISSUE TITLE
I cannot use "columns" property

### ISSUE THREAD

**Issue by baeharam** [jgthms/bulma#1715]
I can use other property but columns don't adapted.... 
In .ejs file head code is below.

```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hello Bulma!</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
```
What I can do?

**Comment by jgthms** [comment]
Use the starter template and save it as a “index.html” file: https://bulma.io/documentation/overview/start/#starter-template

**Comment by baeharam** [comment]
Where I have to include that file? I'm making web application by node.js
