### ISSUE TITLE
Greek alphabet in content

### ISSUE THREAD

**Issue by diegocatalao** [jgthms/bulma#1721]
Hi. 
I have a question about greek alphabet in content.

### Expected behavior
![2018-03-12-214112_1366x768_scrot](https://user-images.githubusercontent.com/4960606/37316474-1be04e80-263e-11e8-98b5-bdcb3c836c63.png)

### Actual behavior
![2018-03-12-214321_1366x768_scrot](https://user-images.githubusercontent.com/4960606/37316533-68969c52-263e-11e8-9c75-06a5b563b9da.png)

This is normal or i need translate the text to hexcode?

This is my code:
`
						<div class="content">
							ἄνδρα μοι ἔννεπε, μοῦσα, πολύτροπον, ὃς μάλα πολλὰ<br>
							πλάγχθη, ἐπεὶ Τροίης ἱερὸν πτολίεθρον ἔπερσεν:<br>
							πολλῶν δ᾽ ἀνθρώπων ἴδεν ἄστεα καὶ νόον ἔγνω,<br>
							πολλὰ δ᾽ ὅ γ᾽ ἐν πόντῳ πάθεν ἄλγεα ὃν κατὰ θυμόν,<br>
							ἀρνύμενος ἥν τε ψυχὴν καὶ νόστον ἑταίρων.<br>
							ἀλλ᾽ οὐδ᾽ ὣς ἑτάρους ἐρρύσατο, ἱέμενός περ:<br>
							αὐτῶν γὰρ σφετέρῃσιν ἀτασθαλίῃσιν ὄλοντο,<br>
							νήπιοι, οἳ κατὰ βοῦς Ὑπερίονος Ἠελίοιο<br>
							ἤσθιον: αὐτὰρ ὁ τοῖσιν ἀφείλετο νόστιμον ἦμαρ.<br>
							τῶν ἁμόθεν γε, θεά, θύγατερ Διός, εἰπὲ καὶ ἡμῖν.<br>
						</div>
					</div>
					<div class="column has-text-left">
						<div class="content">
							ἄνδρα μοι ἔννεπε, μοῦσα, πολύτροπον, ὃς μάλα πολλὰ<br>
							πλάγχθη, ἐπεὶ Τροίης ἱερὸν πτολίεθρον ἔπερσεν:<br>
							πολλῶν δ᾽ ἀνθρώπων ἴδεν ἄστεα καὶ νόον ἔγνω,<br>
							πολλὰ δ᾽ ὅ γ᾽ ἐν πόντῳ πάθεν ἄλγεα ὃν κατὰ θυμόν,<br>
							ἀρνύμενος ἥν τε ψυχὴν καὶ νόστον ἑταίρων.<br>
							ἀλλ᾽ οὐδ᾽ ὣς ἑτάρους ἐρρύσατο, ἱέμενός περ:<br>
							αὐτῶν γὰρ σφετέρῃσιν ἀτασθαλίῃσιν ὄλοντο,<br>
							νήπιοι, οἳ κατὰ βοῦς Ὑπερίονος Ἠελίοιο<br>
							ἤσθιον: αὐτὰρ ὁ τοῖσιν ἀφείλετο νόστιμον ἦμαρ.<br>
							τῶν ἁμόθεν γε, θεά, θύγατερ Διός, εἰπὲ καὶ ἡμῖν.<br>
						</div>
					</div>
`

**Comment by Log1x** [comment]
Your screenshots appear to be the same.

Are you setting the proper charset in your `<head>`?

**Comment by diegocatalao** [comment]
@Log1x Yeap. <meta charset="UTF-8">

**Comment by jgthms** [comment]
Not sure what you’re asking.

**Comment by diegocatalao** [comment]
@jgthms The width of the first column changes if I put letters of the greek alphabet

**Comment by jgthms** [comment]
It’s all your br’s the problem. Remove them.
