### ISSUE TITLE
[SOLVED] Must the modal be ONLY 640px wide? Is it because of responsiveness? I need MAX width - tnx

### ISSUE THREAD

**Issue by tweed** [jgthms/bulma#1722]
Bulma: 0.6.2

Currently going back to using modals and struggling to find the most elegant minimalist way
to allow content to be both just about full-width AND hopefully responsive.

I am mainly needing to overcome the 640px width and make it as wide and as full as possible.

Firstly: is there any reason why 640px is max width? Is it something to do with 
break-points/responsiveness etc.?

I wish the modal to open up, have mobile-view (and desktop) scroll-able content which can also be
close with the 'X' in the right corner.

Thanks for considering my request here  - quite a puzzle for me.

**Comment by jgthms** [comment]
Try the image modal. It’s fuullwidth.

**Comment by tweed** [comment]
WOW - thank you CAPTAIN :-)

**Comment by tweed** [comment]
**I know it's me (so i know some things :-)**

I feel I'm getting closer. I'm trying to pull in entire HTML page into which works ok, somewhat.

Anyone tell why I still get **scroll-bars along the bottom and side** -- at about **640px wide**?

` <div class="container">

		      <div class="columns is-centered ">
		        <div class="column is-4">

<p>
<a class="button is-primary is-large modal-button" data-target="modal-bis">Launch image modal</a></p>

</div>


<div id="modal-bis" class="modal">
  <div class="modal-background"></div>
  <div class="modal-content is-fullwidth">
		<div id="text">
		
		<button onclick="loadTitle()">Load Title</button>
		</div>

		<script>
		function loadTitle() {
		$("#text").load("http://mysitetest/testing-full.html");
		}
		</script>
`

> `  </div>
  <button class="modal-close is-large"></button>
</div>`

**Comment by tweed** [comment]
HOW I missed the **VARIABLES** I'll never know !!!
Thanks for the great documentation and super-helpful assists here.

https://bulma.io/documentation/components/modal/
https://github.com/jgthms/bulma/blob/master/sass/components/modal.sass#L1,L29

**Comment by jgthms** [comment]
No problem

**Comment by filt3rek** [comment]
Hej !

Is there a way to change width using a helper something like is-wide ?
I mean, I want to have it 640px many times but sometimes a larger one, how to achieve that in a clean way please ?
Thanks !

**Comment by Lesterdor** [comment]
I have the same use case as @filt3rek. Is there any bulma way to change the width for individuell modal windows instead of global variable?

**Comment by JimCook57** [comment]
I am interested in this as well.  A way to adjust the size of an individual modal window.

**Comment by leadiville** [comment]
try add the lg sm xl to the modal class, "modal-xl, modal-sm..."

**Comment by d3jv** [comment]
> Try the image modal. It’s fuullwidth.

Is it though? The modal class has this style: `--bulma-modal-content-width: 40rem;`, limiting the width to 40rem.
