### ISSUE TITLE
Card height

### ISSUE THREAD

**Issue by imjack** [jgthms/bulma#1723]
This is about **Bulma**.

### Overview of the problem

 This is about the Bulma **CSS framework** 
I'm using Bulma **version** 0.6.2
My **browser** is: >= IE 11

### Description
I have a columns div containing 2 column at half side each. Inside the columns are cards which heights don't match. I added the style height of 100% but the card footer doesn't float to the bottom as shown in my image. 

![image](https://user-images.githubusercontent.com/4912609/37338417-49f54728-26af-11e8-8f7a-bc61485ecf79.png)

This issue https://github.com/jgthms/bulma/issues/218 reccomends setting the footers style to margin-top: auto; which doesn't seem to work.

**Comment by jgthms** [comment]
It’s the normal behaviour. You need JS for that.

**Comment by imjack** [comment]
@jgthms Would would be the recommended fix for this? Since it's done with javascript

**Comment by lukepighetti** [comment]
Also running into this problem.

**Comment by lukepighetti** [comment]
This appears to have solved it.

Given `<div id="team" class="columns is-multiline">`


```
#team .column .card{
  height: 100%;
  display: flex;
  flex-direction: column;
}

#team .column .card-footer{
  margin-top: auto;
}
```
