### ISSUE TITLE
Feature request elevation / shadow

### ISSUE THREAD

**Issue by danieldaeschle** [jgthms/bulma#1725]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]

### Description

Classes like `elevation-[1-5]` or something similar to provide shadow to components and elements.

### Expected behavior

Include it in the library

### Actual behavior

Isn't included in the library

**Comment by jgthms** [comment]
I don’t think it’s essential.

**Comment by danieldaeschle** [comment]
Wat, why?

**Comment by aneesshameed** [comment]
Wat, why?
