### ISSUE TITLE
[JUST A QUESTION] Bug or feature? .modal-card-title has flex-shrink: 0

### ISSUE THREAD

**Issue by raniesantos** [jgthms/bulma#1729]
What is the purpose of adding `flex-shrink: 0` [here](https://github.com/jgthms/bulma/blob/9094eff30a0efc938fc921911da8426288e2b1b6/sass/components/modal.sass#L51)?

On small screens the modal card title overflows and doesn't break to the next line.

Is this intentional or is it a bug?

**Comment by jgthms** [comment]
Not sure about this one.

**Comment by raniesantos** [comment]
@jgthms For reference:

![](https://i.imgur.com/ImuSqMT.jpg)

When I remove `flex-shrink` in the devtools, the title no longer overflows, it breaks to the next line, and the title area grows in height to fit the text.

**Comment by raniesantos** [comment]
Here's the commit where you added it in.

https://github.com/jgthms/bulma/commit/9094eff30a0efc938fc921911da8426288e2b1b6#diff-a45c8f59ffab6624ecea0fa76db0e970

**Comment by monstermudder78** [comment]
I am having the same issue with the `.level-item` class.

**Comment by raniesantos** [comment]
I'm closing this. If anyone still has issues with this ask jgthms to reopen it.
