### ISSUE TITLE
Fallback to 

### ISSUE THREAD

**Issue by mesqueeb** [jgthms/bulma#173]
Just found a flexbox guide that generates fallbacks to any flexbox property with more conservative css properties.
http://kyusuf.com/post/almost-complete-guide-to-flexbox-without-flexbox
Maybe this could be added as a fallback?
Feel free to close this thread if it's ridiculous, just wanted to bring it up and see your opinions.

An example to create flexbox's "space-between":
```
.container {
	text-align: justify;
}

.container:after {
	content: '';
	display: inline-block;
	width: 100%;
}

.item {
	display: inline-block;
}
```

**Comment by jgthms** [comment]
Ah that's neat, but the purpose of Bulma is to actually use flexbox.

This fallback:
* would be hard to maintain
* requires a different markup
* doesn't support all flexbox features
