### ISSUE TITLE
Height of svg

### ISSUE THREAD

**Issue by melTr** [jgthms/bulma#1730]
This is about **Bulma**.

### Overview of the problem

 Maybe https://github.com/jgthms/bulma/issues/268

### Description
SVG image is not resizing correctly when in column in chrome. 

### Steps to Reproduce
```
<div class="hero-body container"><div class="img-overlay-wrap"><img  src="site/assets/files/1071/multi-6.1104x250.jpg" ><div class="forme-vert column is-10 is-offset-1">
<div class="columns"><img class="column is-1 is-mobile" src="/site/templates/styles/design/OFF.svg"><div class="column is-8">
	<h2>Ateliers de démonstrations - Quand la science trouve le Nord!</h2>
		<p class="has-text-white"> Côte-Nord · Sept-Iles</p>
					</div>
			</div>
					</div> 
<div><p>Activité <span class="has-text-weight-bold">Grand public</span></p></div></div></div>
```

### Expected behavior
Resize correctly (as in firefox)
On Firefox
![image](https://user-images.githubusercontent.com/1063951/37441677-fcec2714-27d8-11e8-8d75-ff112cbb99aa.png)

### Actual behavior
On Chrome
![image](https://user-images.githubusercontent.com/1063951/37441662-f05ac3fc-27d8-11e8-83f5-d19292a72222.png)

Need to specify a height to override this
 img {  (generic sass:85
    height: auto;
    max-width: 100%;
}
but only in Chrome (I don't know why). But screw up responsive resizing if add a height.

**Comment by Come2Daddy** [comment]
Have you tryed using a container as column to wrap your SVG ?

**Comment by Come2Daddy** [comment]
Could be related to #268
