### ISSUE TITLE
Broken link on site.

### ISSUE THREAD

**Issue by cldershem** [jgthms/bulma#1731]
The [link to zea.space](https://github.com/jgthms/bulma/blob/12af6c567b518d6c8693198a9f75b952022a02ac/docs/expo.html#L20) in the Expo section is broken. It's especially noticeable because it's at the very top of the page.

**Comment by emanwebdev** [comment]
approximated alternatives could be:
https://www.behance.net/alzea
https://www.behance.net/gallery/60249075/Single-product-page

https://dribbble.com/alzea
