### ISSUE TITLE
Typography docs

### ISSUE THREAD

**Issue by benjaminapetersen** [jgthms/bulma#1734]
I found some confusion using the built in `text-heading` and `text-subheading` classes, then using raw `h1`, `h2`, etc headings on the same page. The classes cause the headings to shrink substantially against raw headings (not just adjust line height).  In addition, default `h4`, `h5` and `h6` sizes are actually smaller than default body content size (`p`), which doesn't seem to make sense.

The docs are somewhat light on typographic direction, though there are a number of helpers.  It's not quite clear if Bulma intends to provide a comprehensive typographic style, a foundation, or just a sprinkling of helpers. It's tempting to start sprinkling `is-size*` helpers around to try to adjust, but that would definitely lead to inconsistencies.

The current typography is under modifiers -> typography helpers, heading me to think they are intentionally just helpers, but helpers without a baseline also seems confusing.

This issue is mostly to request elaboration via the docs on typography intent. If it is common to roll your own, or use something else for type foundation, that would be very helpful to know (and avoid bloat).

Perhaps just the `h4-h6` default vars need a font size tweak and it would be perfectly fine as is?

Thanks!

**Comment by jgthms** [comment]
> `text-heading` and `text-subheading` classes 

These classes don't exist.

> In addition, default h4, h5 and h6 sizes are actually smaller than default body content size

That's not true. Where do you see that?

It seems your setup includes something that's conflicting with Bulma.?

**Comment by benjaminapetersen** [comment]
My bad, `title` and `subtitle`.

The above were my classes just to swap fonts.  Let me take a screenshot quick & post here.

**Comment by benjaminapetersen** [comment]
Ah, my bad, I did have a font reset still included, thx.  Removed, back to vanilla && I have basically this if I drop a variety of text on the page:

<img width="931" alt="screen shot 2018-03-16 at 1 43 16 pm" src="https://user-images.githubusercontent.com/280512/37536243-622c5174-2920-11e8-9c60-c2df74395960.png">

So `is-size-1` is still the largest, but I was expecting `title` and `subtitle` to probably be top level in font sizes.  I'm guessing the intention of these is a tad different.  `title` === `is-size-3` in terms of `font-size`.  `subtitle` === `is-size-4`, the main difference is the tigher margins.  

Curious why `title` & `subtitle` to be midline font-sizes w/margin adjustments, vs doing a set of numbered `1,2,3,4,5,6,7` `margin` classes to match the heading sizes.  Or perhaps I'm getting hung up on the sematic names `title`,`subtitle`, where `is-size-*` is a bit more abstract (I don't have an issue w/the generic names, just trying to suss out the intent). 

Thx!  Appreciate it.

**Comment by benjaminapetersen** [comment]
So perhaps my question is, are these proposed as sufficient typography, is it encouraged to override the variables in your own stylesheet, or encouraged to load up an additional reset OR go crazy with your own custom fonts?  

Totally get that anyone can CSS all they like, just trying to gather the intended scope of the typography helpers.  Thx!

**Comment by jgthms** [comment]
`title` and `subtitle` were created before the helpers. `title` and `subtitle` are closer in size to body text, hence why you can use them straight away and the visual balance is maintained.

`size-1` is more for lonely headings, if you really need it.
