### ISSUE TITLE
to-top

### ISSUE THREAD

**Issue by diomed** [jgthms/bulma#1735]
This is about the Bulma **CSS framework**

### Description

based on this:
https://bulma.io/documentation/elements/delete/
it would be good to create to-top button with chevron up,
instead of x

**Comment by jgthms** [comment]
Try a icon button: https://bulma.io/documentation/elements/button/

**Comment by diomed** [comment]
If the button only contains an icon, Bulma will make sure the button remains **square**

and I want circle 😕
