### ISSUE TITLE
UI issue in iphone

### ISSUE THREAD

**Issue by KailashPatil** [jgthms/bulma#174]
There is a issue with tab menus in documentation page, tabs seems to be overlapping one on the other, not able to click on the tab menu at all. Working fine in android but issue is in iphone 6.

**Comment by jgthms** [comment]
Do you have a screenshot?

**Comment by KailashPatil** [comment]
![tabmenu](https://cloud.githubusercontent.com/assets/6229606/14599640/2027bd38-0576-11e6-92ff-d33a5b5e0026.png)
Here is the attached screenshot.

**Comment by jgthms** [comment]
Might be the same issue as https://github.com/jgthms/bulma/issues/175

**Comment by danielbayerlein** [comment]
Does anyone have a workaround?
