### ISSUE TITLE
integration with "table" components

### ISSUE THREAD

**Issue by jaguarxii** [jgthms/bulma#1745]
Hello, I am starting a new web project and found your framework which is amazing.
I usually use one of these grid components to show data and offer user interaction (selection, sorting, editing)

[http://js-grid.com/](url)
[http://tabulator.info/](url)
[https://datatables.net/](url)

My questions are: 

- Do you have any plan to support any of these grids (perhaps not the listed ones but others)?
- Is it possible to have an extension to bulma that makes the styling of the grid components easier?

Regards (saludos :)

**Comment by kigiri** [comment]
Sorting require some JS so this is out of the scope of bulma I think
