### ISSUE TITLE
Safari flex-wrap does  not work

### ISSUE THREAD

**Issue by fundon** [jgthms/bulma#175]
Enable the `is-multiline is-mobile` for `columns` container.
But `flex-wrap` no effect.

Then I added 

```
// https://github.com/Modernizr/Modernizr/issues/1414
.column {
  flex-shrink: 1;
  flex-basis: auto;
}
```

The `flex-wrap`  is working now.

**Comment by tquetano-r7** [comment]
Could this have something to do with it?

https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items
