### ISSUE TITLE
Feature request: calendar form input

### ISSUE THREAD

**Issue by pkbarbiedoll** [jgthms/bulma#1750]
This is about **Bulma**.

### Overview of the problem

Addition of form option to input dates, with easy way to navigate across months and years (rather than only forward/backward from a set date)
 

This is about the Bulma **CSS framework**

I'm using Bulma **0.6.2**  

### Description

The form inputs look great, though I didn't see an existing calendar input.   Would like to see this added as a form input.  This input would display the current month's days with controls at the top to separately navigate year and month (as well as controls to simply move forward and backward from the current year/month).

**Comment by Come2Daddy** [comment]
There is a bulma-calendar extension for this purpose. I invite you to take a [look here](https://wikiki.github.io/components/calendar/).
