### ISSUE TITLE
Keep column width regardless browsers width

### ISSUE THREAD

**Issue by NelsonMedinaSilva** [jgthms/bulma#1752]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the **Bulma**
I'm using Bulma **version** [5.7.1] 
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

I have a layout with rows, each row has a title and a group of thumbnails, and this two components (using react) are in-line. I set my title as "column is-2" and my thumbnail group as "column" inside a div "columns". My question is, when I change my browser width, the columns change so each one of them use half of the total width and I dont want this to happen, I want the column with the title to keep its width. I believe this is a media query thing, is happens when I get to the mobiles width (?), but I've tried and dont know how to proper overwrite it from bulma.  Also, is this the best way to deal with such a layout ?

### Expected behavior

The title column should keep the size defined by the "is-2" modifier.
![captura de tela 2018-03-25 11 31 17](https://user-images.githubusercontent.com/22938153/37875296-9a1dabb2-3034-11e8-9cb0-a2303ef2929d.png)

### Actual behavior

The titles column width changes as the thumbnail group so each one fit half the screen.
![captura de tela 2018-03-25 11 31 57](https://user-images.githubusercontent.com/22938153/37875298-a703bba0-3034-11e8-8fa3-7e0ec70dd6f1.png)

**Comment by jgthms** [comment]
You can use `column is-narrow` on your title column. But you need to specify a width if you want one, since all columns in bulma are relatively, not absolutely sized.

For columns on mobile too, use `columns is-mobile`.

**Comment by NelsonMedinaSilva** [comment]
@jgthms  Awesome, thanks a lot ! It's my first project with bulma, still getting used to it. Cheers !
