### ISSUE TITLE
First Expo DNS not working

### ISSUE THREAD

**Issue by jppope** [jgthms/bulma#1754]
This is about the Docs

### Overview of the problem
link to www.zea.space not rendering (guessing DNS issue?)

This is about the Bulma **Docs** 

### Description

link to www.zea.space not rendering (guessing DNS issue?)

### Steps to Reproduce

Its the first site in EXPO

### Expected behavior

the site to be there

### Actual behavior

the site wasn't there

**Comment by jgthms** [comment]
Fixed!
