### ISSUE TITLE
Clarifying helpers is-small vs is-size-*

### ISSUE THREAD

**Issue by benjaminapetersen** [jgthms/bulma#1755]
This is about the Bulma **CSS framework** and/or the Bulma **Docs** (TBD)

### Description

I noticed that `is-small` has no effect on `<p>` paragraph text.  I then went back looking for another helper & found the `is-size-*` set.  This is more of a clarification, should `is-small` work for `<p>`, does it expect a parent class to apply, or are the `is-size-*` helpers always better to use (for style consistency). 

Thanks!

**Comment by jgthms** [comment]
`is-small` is specific to each component. Not all of them have that modifier.

The helpers like `is-size-*` always work, no matter the context.

**Comment by benjaminapetersen** [comment]
Great thx!  I'm obviously new to Bulma, & opening issues as I work through the docs (even if fairly trivial, like this).  If the feedback is helpful, great. If not, feel free to close (I def don't want to spam).

**Comment by benjaminapetersen** [comment]
Definitely reading it, just a question of gathering the mental model!  

Happy to close this one & will def check that gitter. thx
