### ISSUE TITLE
Clarify -bis & -ter suffix in helpers

### ISSUE THREAD

**Issue by benjaminapetersen** [jgthms/bulma#1756]
This is about **the Docs**.

There are helpers `has-text-black-ter`, `has-text-white-bis`, etc.  I'm not sure what `-ter` and `-bis` mean.  This would be helpful to add to the [Colors](https://bulma.io/documentation/modifiers/typography-helpers/#colors) section.

**Comment by jgthms** [comment]
It's just the second and third variations of white.

https://tex.stackexchange.com/questions/254149/french-section-numbering-using-bis-ter-etc

**Comment by johnpuddephatt** [comment]
I find this very confusing.

**Comment by sshaw** [comment]
> I find this very confusing.

`$black-bis`, you know, like the candy: 

![bis_black](https://user-images.githubusercontent.com/17570/88251857-278f4a80-cc7a-11ea-9adc-c07197d13721.jpg)


(Though personally I'd prefer something from Cacau Show)
