### ISSUE TITLE
Question: Setting Max Container size to 1024

### ISSUE THREAD

**Issue by fieldingtron** [jgthms/bulma#1759]
Hello I am relatively new to CSS, Sass, mixins, etc but not to programming. My question is what is the best practice for setting a container size of 1024 max. I understand that there are 5 breakpoints however I only would like to have a max size of 1024.  I could set a css rule for the container max-width to be 1024px but is this the correct way to accomplish this ? Or should I be adjusting a sass variables. Any thoughts on best practices ?  I have limited information on my homepage and it just doesnt look good at 1216 px or 1408 px

5 breakpoints mentioned on the documentation site

mobile: up to 768px
tablet: from 769px
desktop: from 1024px
widescreen: from 1216px
fullhd: from 1408px

**Comment by tomkeysers** [comment]
And how to actually achieve this? Have you found it?

I'm playing around with sass variables but can't seem to accomplish it.
