### ISSUE TITLE
dropdown-trigger doesn't exist

### ISSUE THREAD

**Issue by ahstro** [jgthms/bulma#1760]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

[The docs](https://bulma.io/documentation/components/dropdown/) mention a `dropdown-trigger`, but it doesn't exist when searching in [the CSS](https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css).

### Steps to Reproduce

1. Read the docs
2. Look in CSS
3. Be confused

### Expected behavior

Either `dropdown-trigger` should exist in the CSS, or it should not be mentioned in the docs.

### Actual behavior

`dropdown-trigger` is mentioned, but does not exist.

**Comment by Come2Daddy** [comment]
Don't know if it was a placeholder for some features or not. For now it's not even required for the dropdown to perform well as far as I saw.

**Comment by ahstro** [comment]
Can confirm it's not needed. Removed mine, and things work fine :)

**Comment by jgthms** [comment]
@Come2Daddy is right: it was a placeholder for some features. It might be used at some point.

**Comment by Come2Daddy** [comment]
As it stands in the docs, `.dropdown-trigger` looks mandatory so people are using it by default. It must be considered for the features to be implemented that they shouldn't change the current behavior of the dropdown component. This aside, I don't see any reason to delete it from the docs.
