### ISSUE TITLE
Default values for select and radio buttons don't work

### ISSUE THREAD

**Issue by wonder95** [jgthms/bulma#1762]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [6.1] 
My **browser** is: Chrome Mac 65, also tried FF 58.0.2 and Opera 51.

### Description

When using radio button and select inputs, setting selected/checked values in form doesn't work; no value is selected.

### Steps to Reproduce

1. Add form elements
```
    <div class="field is-horizontal">
      <div class="field-label">
        <label class="label">Type</label>
      </div>
      <div class="field-body">
        <div class="field">
            <label class="radio">
              <input v-model="nodeType" type="radio" name="nodeType" value="article">Article</label>
            <label class="radio">
              <input v-model="nodeType" type="radio" name="nodeType" value="document">Document</label>
            <label class="radio">
              <input v-model="nodeType" type="radio" name="nodeType" value="video">Video</label>
            <label class="radio">
              <input v-model="nodeType" type="radio" name="nodeType" value="product_display" checked>Product</label>
        </div>
      </div>
    </div>
```
    <div class="control has-icons-left">
      <label class="label">Language</label>
      <div class="select">
        <select v-model="language" class="is-focused">
          <option selected value="en-us">English (US)</option>
          <option value="de-de">German</option>
          <option value="fr-fr">French</option>
        </select>
      </div>

2. Display form

### Expected behavior

For select list, item with `selected` is selected (I tried both `selected` and `selected="selected"`); for radio button, item with `checked` is selected. 

### Actual behavior

No default value is selected.

**Comment by Come2Daddy** [comment]
Does work for me.
Seems not related to Bulma, attributes behavior is not style dependent.

**Comment by jgthms** [comment]
It seems a Vue implementation problem, not a Bulma one.
