### ISSUE TITLE
Want to add a picture to my fullheight hero, what is not working

### ISSUE THREAD

**Issue by AlTrAugsburg** [jgthms/bulma#1769]
This is about Bulma and I need help.

### Description

I added a picture to my section class="hero is-fullwidth" in a container, but I can't see it. The path of the picture is correct. You can see it under <a href="http://admiral-pflegedienst.de">admiral-pflegedienst.de</a>. 

### Steps to Reproduce

First created a hero with a centered container. Added then a picture and some text to the container. Text is visible and there is some gap for the picture, where it should it be, but it's not there. Controlled the picture source but it's correct. You can the picture in small version in the upper left corner.

### Expected behavior

I expected a picture in the container of the hero.

### Actual behavior

There's no picture

 ### The Bulma version I used

I used Bulma from the source https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css
and https://use.fontawesome.com/releases/v5.0.6/js/all.js.

### Browsers I used

I used Firefox and Chrome, but both aren't working. In Chrome there is only a white border around the not existent picture.

I'm grateful about every help about this topic.

**Comment by FlorKaucic** [comment]
Hi @AlTrAugsburg 
Correct me if I'm wrong, but I think your code looks like this:
`<img class="image" source="assets\logo.jpg" height="100%" width="100%" style="height: 20vh; width: 10vw; z-index:1;">`

And there's a couple of issues with that. For starters, the attribute to declare a source path is `src`. Also, the file extension is `png`, not `jpg`, according to the website sources. So your code should look like this:
`<img class="image" src="assets\logo.png" height="100%" width="100%" style="height: 20vh; width: 10vw; z-index:1;">`

Hope that helps!

**Comment by AlTrAugsburg** [comment]
Thanks, it was my fault😅. Always this typos...
