### ISSUE TITLE
CSS not in bower.json file

### ISSUE THREAD

**Issue by metal3d** [jgthms/bulma#177]
Hi,

I wanted to use bower + wiredep to install bulma and I discovered you set main file to bulma.sass.

I don't need sass (I'm not using it) and because I'm using wiredep to inject css files, bulma is not added.

Note that I'm not using node project. 

Is this possible to set main file to a min.css file in bower configuration please ?

Thanks !

**Comment by jgthms** [comment]
I'm not sure what you mean. The css files are included when you install bulma via bower.

**Comment by metal3d** [comment]
Yes, but "wiredep" doesn't append the css file because the "main" file is a sass file. You may add  "css/bulma.min.css" to the main array or replace "main.sass" by "css/bulma.min.css".

To set "sass" file as "main" file is only useful when using grunt or gulp or any node module that can compile it. But when you want to build a simple index.html page, and only use wiredep to integrate bower_components, bulma is not automatically included in the index.html file.

Exemple: `bower install bootstrap && wiredep -s index.html` works, it includes the bower.min.css file inside

```
<!-- bower:css --!>
<!-- endbower --!>
```

**Comment by metal3d** [comment]
Wooow my bad... bootstrap doesn't include css in mainfile, and wiredep doesn't include css file. That was different before...

So, maybe I will check how I can force css inclusion with wiredep. Sorry

**Comment by metal3d** [comment]
https://github.com/yeoman/generator-angular/issues/1116 => actually it worked before and bootstrap does the same as you. They removed CSS files from "main" directive.

https://github.com/yeoman/generator-angular/issues/1116#issuecomment-154395390 explains how to override behavior.

**Comment by metal3d** [comment]
Ok, I edited my project bower.json:
```json
  "overrides": {
    "bulma": {
      "main": [
        "css/bulma.min.css"
      ]
    }
  }
```

wiredep append bulm css file in my index.html file.

Sorry for that bad issue :)

**Comment by jgthms** [comment]
No problem.
