### ISSUE TITLE
Fade in a Box effect

### ISSUE THREAD

**Issue by arturplo** [jgthms/bulma#1770]
Hi, I created this code
https://jsfiddle.net/e5tz1wLg/
How to get this effect with the help of CSS Bulma?
https://www.w3schools.com/css/tryit.asp?filename=trycss_css_image_overlay_opacity

**Comment by jgthms** [comment]
Key part is this:

```
.middle {
  transition: .5s ease;
  opacity: 0;
}

.container:hover .image {
  opacity: 0.3;
}
```

You put a transition on the opacity. Learn more here: https://www.w3schools.com/css/css3_transitions.asp
