### ISSUE TITLE
Disable tab

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#1772]
This is about **Bulma**.

Is a feature/question

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.6.2]
My **browser** is: Chrome
I think this issue is **not a duplicate**?

### Description

When using tabs, there is no way to make a disabled tab right now. Maybe this can be a good addition.

### Expected behavior

Showing visually that a tab is disabled, similat to a button. Do not allow pressing it.

**Comment by jgthms** [comment]
#1685

**Comment by aocneanu** [comment]
Jeremy, and some feedback pls?

**Comment by nuthingman** [comment]
Hi Jeremy,

Any comment/feedback? Even something like "won't fix" is valuable.

**Comment by amaeva911** [comment]
Hello, thanks for Bulma. Please reopen this task, feature with disabled tabs will be very useful.
Or please will give a hint in the documentation of how we can do it without this new class.

**Comment by amaeva911** [comment]
Some example with using class="has-text-grey-light"
<li>
    <a>
        <span class="icon is-small has-text-grey-light">
            <i class="far fa-file-alt" aria-hidden="true"></i>
        </span>
        <span class="has-text-grey-light">Tab1</span>
    </a>
</li>

**Comment by jgthms** [comment]
This task is still open but is a duplicate of #1685. Please refer to that issue.
