### ISSUE TITLE
Cursor shows outside input on modal on mobile device

### ISSUE THREAD

**Issue by freeman-g** [jgthms/bulma#1774]
This is bug about Bulma - it may be an iOS safari bug - I'm not sure.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.6.2
My **browser** is: iOS Safari on an iPhone 7
I am sure this issue is **not a duplicate**

### Description

I have a small form with a few inputs in a modal. On my mobile phone, when I click in the inputs, the cursor jumps to about 50px below the input so that it seems like the cursor is not even in the input.

I have reproduced this issue on the following codepen. You might want to look at the debug version to view it in a full page on a phone.

https://codepen.io/freeman-g/pen/jzMJzG
https://s.codepen.io/freeman-g/debug/jzMJzG/xJkjOWobpdOM

Here is a screenshot from my phone.

![image](https://user-images.githubusercontent.com/495886/38343111-2254e77a-3850-11e8-836b-1c7002325066.png)

Thanks!

**Comment by theguywithglasses** [comment]
Same here, with chrome and firefox for iOS on iphone 6SE

**Comment by freeman-g** [comment]
There's a similar discussion here related to bootstrap. Per that discussion, I just upgraded to iOS 11.3 and it fixed the issue. So it was an iOS issue.

https://github.com/twbs/bootstrap/issues/24835
