### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by BenSapiens** [jgthms/bulma#1779]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: all of them

I am sure this issue is **not a duplicate**?

### Steps to Reproduce

1. Go to a page on the docs.

### Expected behavior

1. I expect to find details on specifically implementing the excellent Bulma framework.

### Actual behavior

1. I am assaulted by that "give me your email, buy my ebook, whatever" popup.

### Description

Thanks, but I've already seen that thing like 50 times, I've been bothered by it 50 times, and seeing it for a 51st time is obviously not changing my mind.

I am sufficiently irritated to be writing this.

**Comment by jgthms** [comment]
It should only appear once if you close it. What’s your setup?

**Comment by BenSapiens** [comment]
My apologies for the lack of reply. I use a generically configured Safari. I would estimate that I see the message on somewhere between one-fifth and one-tenth of all page loads. It's probably unreproducible, but it isn't a big deal, really. After this comment I'll re-close this if I am able.

**Comment by BenSapiens** [comment]
Disregard the last sentence; the issue stayed closed.
