### ISSUE TITLE
Question: floating vertical scrolling column ?

### ISSUE THREAD

**Issue by joeblew99** [jgthms/bulma#178]
Thanks for helping out! 😇

### Prerequisites

If it's a bug on the **website**, submit an issue on the appropriate repository: [https://github.com/jgthms/bulma-website](https://github.com/jgthms/bulma-website)

* [ ] Is this about Bulma the **CSS framework** and **not** about the Bulma website? yes
* [ ] Which **version** of Bulma are you using? latest
* [ ] Which **browser** are you using? chrome
* [ ] If it's a **Sass** issue, which version of Sass are you using? no.
* [x] Are you sure this issue is not a **duplicate**? not a dup. i looked

### Description

[Description of the bug, enhancement, or question]
[Please tag accordingly]
Question:
I am wanting to make a panel that scrolls independently of the main page.
This is exactly what i want:
http://rollupjs.org/guide/
Notice how the main page scrolls and the left nav stays put.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

_Expected behavior:_ [What you expected to happen]

_Actual behavior:_ [What actually happened]

**Screenshots** are more than welcome!

Can someone give me an example of this ?

**Comment by jgthms** [comment]
You just need regular CSS to do that. It's difficult to put that into a framework because you need a specific width, a specific height, specific margins or positioning for the sibling elements.

It's just too specific.

**Comment by joeblew99** [comment]
your right..
Its was pretty easy though... The column that i needed to be vertical scrolling is "left-container"
Because i have a header section, above is i need to allow for it when i size the left container vertically.
Lastly, i added it to fire on page ready.

So, for others see below:

````   
 <style type="text/css" media="screen">

    #left-container{
        overflow: scroll; 
        width: 100%;
    }
    </style>

    
    <script>

    // resize header-container' behaviour
    function resizeLeft() {
        // calculate top nav height
        console.log("resize left")
        var headerHeight = $('#header-container').outerHeight();

        return $('#left-container').height($(window).height()-headerHeight);
    };
    //listen for changes
    $(window).resize(resizeLeft);
    //set initially
    $(resizeLeft);
   
    </script>

```
