### ISSUE TITLE
Docs 404 error on CSS

### ISSUE THREAD

**Issue by RobinPrette** [jgthms/bulma#1780]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Website**

### Description

Hi, am I the unique person to have no CSS loaded on your [docs](https://bulma.io) ?

I'm from France if that can help you (CDN problems?).

![image](https://user-images.githubusercontent.com/12173101/38467440-e9d5a5ba-3b38-11e8-8330-3a66d57e1199.png)

**Comment by jgthms** [comment]
Fixed! Thanks for reporting it.
