### ISSUE TITLE
Default documentation pointing to version not yet released.

### ISSUE THREAD

**Issue by LasseHaslev** [jgthms/bulma#1782]
### Overview of the problem

This is about the Bulma **Docs**

The default documentation (0.6.2) is showing information about the not yet released version 0.7.0.
I know you are preparing a new version of bulma, but this was quite confusing.

#### [Default documentation](https://bulma.io/documentation/elements/button/#variables)

The default documentation is showing variables that does not yet exists.
![image](https://user-images.githubusercontent.com/3670799/38526924-9126bef6-3c58-11e8-8c5d-90f45653ddeb.png)

#### [Version 0.6.2 documentation](https://versions.bulma.io/0.6.2/documentation/elements/button/#variables)
If we are setting the version number in the documentation, it contains the expected variables.
![image](https://user-images.githubusercontent.com/3670799/38527064-33074f42-3c59-11e8-814d-bf64ec95d717.png)

### Expected behaviour

Make the default documentation point to 0.6.2, until new version release.

**Comment by jgthms** [comment]
Indeed, I need to put it behind a flag.

**Comment by jgthms** [comment]
Fixed!
