### ISSUE TITLE
Box Class displays an inconsistent height for same content

### ISSUE THREAD

**Issue by drdan18** [jgthms/bulma#1788]
This is question about **Bulma**.

### Description

I am following along in the book Create Interfaces with Bulma.  Currently finished page 47 regarding responsive grids.  I have created six "books" in my page.  For some reason the last book displayed has a box that is is taller than all the other boxes.   They are all using the same box class and they all have the same picture and data. 

### Steps to Reproduce

Follow the lesson in the book. 

### Expected behavior

I expected them to be the same size for every box. 

### Actual behavior

If there are three columns then the box will be taller if it ends in the second or third column.  If a two column wrap the last box is taller in the second column.  It only affects the very last box displayed.  If a single column it isn't a problem, the last box is the same height as the others. 

![image](https://user-images.githubusercontent.com/6642337/38762196-9fcfb424-3f57-11e8-91db-41c60c664650.png)

**Comment by jgthms** [comment]
That's weird. It might be due to some error in the markup. Can you share your code?

**Comment by drdan18** [comment]
Here is the code: 

            <div class="columns is-multiline">
              @for($i=6;$i>0;$i--)
              <article class="box" style="margin-right: 20px;">
                <div class="media">
                  <aside class="media-left">
                    <img src="images/shawshank.jpg" alt="shawshank.jpg" width=80>
                  </aside>
                  <div class="media-content">
                    <p class="title is-5 is-spaced is-marginless">
                      <a href="edit-book.html">
                        Shawshank Redemtion
                      </a>
                    </p>
                    <p class="subtitle is-marginless">
                      $22.99
                    </p>
                    <div class="content is-small">
                      270 pages
                      <br>
                      ISBN: 9781939902351
                      <br>
                      <a href="edit-book.html">Edit</a>
                      <span>·</span>
                      <a>Delete</a>
                    </div>
                  </div>
                </div>
              </article>
              @endfor
            </div>

**Comment by jgthms** [comment]
There should be a `<div class="column">` to wrap the `<article class="box">`.

**Comment by drdan18** [comment]
Thanks.  That makes sense to me now.  Onward...
