### ISSUE TITLE
New Background Colors Missing

### ISSUE THREAD

**Issue by tbonz** [jgthms/bulma#1789]
This is about Bulma

### Overview of the problem

I'm using Bulma **version** [0.7.0]

### Description

Tried using .has-background-grey

### Steps to Reproduce

Place .has-background-grey onto any element

### Expected behavior

the background-color should be applied

### Actual behavior

no background-color was applied

**Comment by jgthms** [comment]
Ah yes the shades of grey are not present. Only the Colors.

**Comment by maticrivo** [comment]
Hi @jgthms, when can we expect a new release with this fix? a version 0.7.1 maybe?
