### ISSUE TITLE
[Question]: How do I add a transition or animation to Bulma navbar menu dropdown?

### ISSUE THREAD

**Issue by chanlito** [jgthms/bulma#1790]
This is a question about **Bulma**.

### Overview of the problem

I'm using Bulma **version** [0.7.0]

When I click on  the navbar-burger button, why the dropdown menu list doesn't have any transition or animation by default?

And how would I go and add a dropdown transition?

**Comment by jgthms** [comment]
It requires JavaScript. You can use jQuery: http://api.jquery.com/animate/

**Comment by NullVoxPopuli** [comment]
I'd prefer a CSS-only transition. No need for JavaScript.

**Comment by MrJacz** [comment]
@jgthms please reopen this. I would absolutely love this!
also, it doesn't require JS IIRC. it's completely possible without js

**Comment by jimpsson** [comment]
@MrJacz Agree. I've been testing some things myself but have not yet got it to fully work. For now I could only get it working going from closed to opened.

**Comment by carlosavira** [comment]
@jimpsson Can you show us how you made the open and closing transition of navbar

**Comment by alvarotf** [comment]
Could someone give some hint on how to do it css-only?

**Comment by hiNigel** [comment]
`.navbar` class is using display property which cannot be transitioned. If it can be replaced with some other transition-able property, it would be really easy to implement with only css.

**Comment by kminardo** [comment]
This isn't a perfect solution as it requires a fixed height, but I was able to get a bit of animation on the dropdown by adding this to my customization scss

```
.navbar-menu.is-active {
    animation: navAnim .2s ease-in-out;
}

@keyframes navAnim {
  0% {
    display: none;
    opacity: 0;
    height: 0;
  }
  1% {
    display: block;
    opacity: 0;
  }
  100% {
    opacity: 1;
    height: 396px;
  }
}
```

**Comment by Kuchiriel** [comment]
@kminardo Work flawless, how to do the same effect when you click again to hide the menu?

**Comment by atharvajava** [comment]
I modified @kminardo code a little that code was clutterish

.navbar-menu {
    animation: navAnimOpen .2s ease-in-out;
}

@keyframes navAnimOpen {
  0% {display: none;opacity: 0;max-height: 0;}
  1% {display: block;opacity: 0;}
  100% {opacity: 1;max-height: 396px;}
}

well here max height need not be 396px you may set it to anything bigger then the original height but i am not able to make the close animation work

**Comment by Paperfeed** [comment]
If you don't want to hardcode a height you could just use transforms and transitions, like so:

```
.navbar-menu {
    display: block;
    opacity: 0;

    position: absolute;   /* or float: left; width: 100%;*/
    left: 0;
    right: 0;

    transform: translateY(-50%);
    transition: all .4s ease-in-out;
    pointer-events: none;
}

.navbar-menu.is-active {
    opacity: 1;
    transform: none;
    pointer-events: auto;
}
```

Change the attributes until you have a transition you like (from the left, top, bottom, w/e)...

**Comment by eltel** [comment]
@Paperfeed That's fantastic!!

**Comment by rsalunga29** [comment]
> If you don't want to hardcode a height you could just use transforms and transitions, like so:
> 
> ```
> .navbar-menu {
>     display: block;
>     opacity: 0;
> 
>     position: absolute;   /* or float: left; width: 100%;*/
>     left: 0;
>     right: 0;
> 
>     transform: translateY(-50%);
>     transition: all .4s ease-in-out;
>     pointer-events: none;
> }
> 
> .navbar-menu.is-active {
>     opacity: 1;
>     transform: none;
>     pointer-events: auto;
> }
> ```
> 
> Change the attributes until you have a transition you like (from the left, top, bottom, w/e)...

This messes up the nav menu on desktop version but works seamlessly fine for mobile

**Comment by ItsIrv** [comment]
> > If you don't want to hardcode a height you could just use transforms and transitions, like so:
> > ```
> > .navbar-menu {
> >     display: block;
> >     opacity: 0;
> > 
> >     position: absolute;   /* or float: left; width: 100%;*/
> >     left: 0;
> >     right: 0;
> > 
> >     transform: translateY(-50%);
> >     transition: all .4s ease-in-out;
> >     pointer-events: none;
> > }
> > 
> > .navbar-menu.is-active {
> >     opacity: 1;
> >     transform: none;
> >     pointer-events: auto;
> > }
> > ```
> > 
> > 
> > Change the attributes until you have a transition you like (from the left, top, bottom, w/e)...
> 
> This messes up the nav menu on desktop version but works seamlessly fine for mobile

If combined with the answer found here: https://github.com/jgthms/bulma/issues/1818#issuecomment-383429940 which explains the bulma breakpoint system you can come up with this great solution:

`@include until($desktop) {
  .navbar-menu {
    display: block;
    opacity: 0;

    position: absolute;   /* or float: left; width: 100%;*/
    left: 0;
    right: 0;

    transform: translateY(-50%);
    transition: all .4s ease-in-out;
    pointer-events: none;
  }

  .navbar-menu.is-active {
    opacity: 1;
    transform: none;
    pointer-events: auto;
  }
}`

**Comment by alghvzali** [comment]
Wow this is great. Bulma need to add default transition.

**Comment by bymathias** [comment]
> > > If you don't want to hardcode a height you could just use transforms and transitions, like so:
> > > ```
> > > .navbar-menu {
> > >     display: block;
> > >     opacity: 0;
> > > 
> > >     position: absolute;   /* or float: left; width: 100%;*/
> > >     left: 0;
> > >     right: 0;
> > > 
> > >     transform: translateY(-50%);
> > >     transition: all .4s ease-in-out;
> > >     pointer-events: none;
> > > }
> > > 
> > > .navbar-menu.is-active {
> > >     opacity: 1;
> > >     transform: none;
> > >     pointer-events: auto;
> > > }
> > > ```
> > > 
> > > 
> > > Change the attributes until you have a transition you like (from the left, top, bottom, w/e)...
> > 
> > 
> > This messes up the nav menu on desktop version but works seamlessly fine for mobile
> 
> If combined with the answer found here: [#1818 (comment)](https://github.com/jgthms/bulma/issues/1818#issuecomment-383429940) which explains the bulma breakpoint system you can come up with this great solution:
> 
> ```
> @include until($desktop) {
>   .navbar-menu {
>     display: block;
>     opacity: 0;
> 
>     position: absolute;   /* or float: left; width: 100%;*/
>     left: 0;
>     right: 0;
> 
>     transform: translateY(-50%);
>     transition: all .4s ease-in-out;
>     pointer-events: none;
>   }
> 
>   .navbar-menu.is-active {
>     opacity: 1;
>     transform: none;
>     pointer-events: auto;
>   }
> }
> ```

Works great thx. But, the menu slide down/up over the navbar (is-fixed-top). The navbar is z-index: 30, background: $white, but even when the navbar-menu is z-index: 0, it keeps slide down/up over the navbar. Can't find how to fix that.

**Comment by DaniG2k** [comment]
I'm having a bit of a hard time with this. I have my Bulma menu set up as in the documentation:

```slim
nav.navbar.is-fixed-top#navbar-shadow role="navigation" aria-label="main navigation"
  .navbar-brand
    a.has-text-primary.has-text-weight-bold.navbar-item href="/" Some website
    a.navbar-burger.burger role="button" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
      span aria-hidden="true"
      span aria-hidden="true"
      span aria-hidden="true"

  #navbarBasicExample.navbar-menu
    .navbar-start
      a.navbar-item Documentation

      .navbar-item.has-dropdown.is-hoverable
        a.navbar-link More

        .navbar-dropdown.animated-ease
          a.navbar-item About
          a.navbar-item Jobs
          a.navbar-item Contact
          hr.navbar-divider
          a.navbar-item Report an issue
```

When someone hovers over the `More` link, I want the menu to fade in and out with some other fancy effects.

I added that `.animated-ease` class but it doesn't seem to be doing the trick:

```scss
@keyframes fxAnimatedEase {
  from {
    opacity: 0;
    transform: translateY(-5px);
  }
  to {
    opacity: 1;
    transform: translateY(0px);
  }
}

.animated-ease {
  animation-duration: 0.3s;
  animation-name: fxAnimatedEase;
}
```

The initial hover triggers the animation, but as soon as the menu loses focus the menu does not ease out (it immediately disappears). Is there some documentation on how to add effects to the dropdowns that I've missed?
Thanks!

**Comment by Wil-Quispe** [comment]
how to add animate css in navbar is-active

**Comment by AmanZx4** [comment]
@kminardo code breaks the desktop version so i tried using media queries and it is working fine:

`@media only screen and (max-width: 1000px) {
    .navbar-menu {
        display: block;
        opacity: 0;
        position: relative; /* or float: left; width: 100%;*/
        left: 0;
        right: 0;

        transform: translateY(-50%);
        transition: all 0.4s ease-in-out;
        pointer-events: none;
    }

    .navbar-menu.is-active {
        opacity: 1;
        transform: none;
        pointer-events: auto;
    }
}
`

**Comment by Crandy9** [comment]
What about a slide from right to left or left to right? I tried this but it didn't work:

`    .navbar-menu.is-active {
        transform: translateX(100%) !important;
        transition: transform 450ms ease-out !important;

    }`

**Comment by csicsi2000** [comment]
I tried to further improve it. It gives a nice animation 

```
@media only screen and (max-width: 1000px) {
  .navbar-menu {
      display: block;
      opacity: 0;
      position: relative;
      padding: 0;
      left: 0;
      right: 0;
      max-height: 0px;
      transition: all 0.4s ease-in-out;
      pointer-events: none;
      overflow: hidden;
  }

  .navbar-menu.is-active {
    max-height: 200px;
    padding: .5rem .75rem;
      opacity: 1;
      transform: none;
      pointer-events: auto;
  }
}
```
