### ISSUE TITLE
modal not having vertical scroll

### ISSUE THREAD

**Issue by william-jay** [jgthms/bulma#1794]
Expected behavior
modal-content should have vertical scrollbar when content is long but have fixed footer

Actual behavior

![untitled](https://user-images.githubusercontent.com/38004080/38774935-06d84150-40a6-11e8-9d0c-6b348dd7c0d1.png)

here is my code. I am using vuejs as my javascript framework

	<div :class="{ modal: true, 'is-active': del.modal }">
		<div class="modal-background" v-on:click="del.modal = false"></div>
		<div class="modal-card">
			<div v-if="del.loading">
	  			<section class="modal-card-body">
	  				<p>Checking if selected class has record in other modules ...</p>
	  			</section>
	  		</div>
	  		<div v-else>
	  			<header class="modal-card-head bg-white">
		      		<p class="modal-card-title"><span class="icon has-text-warning"><i :class="modalIcon"></i></span>{{del.header}}</p>
		      		<button class="delete" aria-label="close" v-on:click="del.modal = false"></button>
		    	</header>
		   		<section class="modal-card-body">
		   			<div class="content">
		   				<p>
			     		 	{{del.msg}}
			     		</p>
			     		<div v-if="del.safe">
			     		 	<hr>
			     		 	<table>
			     		 		<tr>
			     		 			<td><b>Term:</b></td>
			     		 			<td>{{ del.term }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Subject:</b></td>
			     		 			<td>{{ del.subject }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Description:</b></td>
			     		 			<td>{{ del.description }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Day:</b></td>
			     		 			<td>{{ del.day }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Time:</b></td>
			     		 			<td>{{ del.time }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Room:</b></td>
			     		 			<td>{{ del.room }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Faculty:</b></td>
			     		 			<td>{{ del.faculty }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Section:</b></td>
			     		 			<td>{{ del.section }}</td>
			     		 		</tr>
			     		 	</table>
			     		 	<table>
			     		 		<tr>
			     		 			<td><b>Term:</b></td>
			     		 			<td>{{ del.term }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Subject:</b></td>
			     		 			<td>{{ del.subject }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Description:</b></td>
			     		 			<td>{{ del.description }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Day:</b></td>
			     		 			<td>{{ del.day }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Time:</b></td>
			     		 			<td>{{ del.time }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Room:</b></td>
			     		 			<td>{{ del.room }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Faculty:</b></td>
			     		 			<td>{{ del.faculty }}</td>
			     		 		</tr>
			     		 		<tr>
			     		 			<td><b>Section:</b></td>
			     		 			<td>{{ del.section }}</td>
			     		 		</tr>
			     		 	</table>
			     		</div>
		   			</div>
		     		 
		    	</section>
			    <footer class="modal-card-foot" style="justify-content: flex-end;">
			    	<div v-if="del.safe">
			    		<button class="button">No</button>
			      		<button class="button is-danger">Yes</button>
			    	</div>
			    	<div v-else>
			    		<button class="button">Ok</button>
			    	</div>
			    </footer>
	  		</div>
	  	</div>
	</div>

**Comment by Come2Daddy** [comment]
Please, avoid JS dependent syntax...

You wrapped `.modal-card-*` in a div inside `.modal-card` 

`<div v-else>` is your problem.

**Comment by dsbert** [comment]
Is this issue only happening in IE?

**Comment by samiggapps** [comment]
I seem to be having this same issue on IE11
when the height of the view-port is less than the height of the modal
instead of the footer remaining fixed and a scroll bar appearing on the modal
there is no scroll bar and the footer disappears
