### ISSUE TITLE
Documentation - broken link on `modifiers`

### ISSUE THREAD

**Issue by adambair** [jgthms/bulma#18]
I really like what you're doing with this project (I was making a second pass at reading the docs and happened to notice the link).

(Broken link in documentation -- "5 main colors")
![](http://cl.ly/0L3p0h2K1P3t/Image%202016-01-29%20at%206.58.34%20PM.png)

http://bulma.io/documentation/modifiers

**Comment by jgthms** [comment]
Thanks @adambair. Btw, there's a repo for the docs as well: https://github.com/jgthms/bulma-website

**Comment by adambair** [comment]
Ah cool -- I didn't realize. I'll close these out and move them to the docs repo after I finish making a pot of coffee :)

**Comment by adambair** [comment]
https://github.com/jgthms/bulma-website/issues/4
