### ISSUE TITLE
navbar-link displays dropdown icon when on its own

### ISSUE THREAD

**Issue by indiealexh** [jgthms/bulma#1802]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.0]

### Description

The `.navbar-link` class renders a drop down icon without being under an element with `.navbar-item` or a `.has-dropdown`

### Steps to Reproduce

Add an element with a navbar-link to the navbar:
```html
<div class="navbar-menu" [class.is-active]="navBarMenuIsOpen" id="navMenu">
        <div class="navbar-start">
            <div class="navbar-link">test3</div>
        </div>
</div>
```

![image](https://user-images.githubusercontent.com/1066212/38892021-f1da77be-423a-11e8-93a3-9391d2d3eab5.png)

### Expected behavior

An item added to the navbar **without** a dropdown icon.

### Actual behavior

An item added to the navbar **with** a dropdown  icon.

### Proposed fixes

Change:
```sass
.navbar-link
  padding-right: 2.5em
  &::after
    +arrow($navbar-dropdown-arrow)
    margin-top: -0.375em
    right: 1.125em
```

to

```sass
.navbar-item > .navbar-link
  padding-right: 2.5em
  &::after
    +arrow($navbar-dropdown-arrow)
    margin-top: -0.375em
    right: 1.125em
``` 

or move the code to under `.has-dropdown`

```sass
.navbar-item.has-dropdown > .navbar-link
  padding-right: 2.5em
  &::after
    +arrow($navbar-dropdown-arrow)
    margin-top: -0.375em
    right: 1.125em
```

**Comment by Come2Daddy** [comment]
While we are here, it's more a 'label' for the dropdown than a 'link'. I do agree with @indiealexh. Could we consider `.navbar-label` as an alias for future deprecation of `.navbar-link` ?

**Comment by indiealexh** [comment]
I'm trying to use `.navbar-link` in a custom html element since I cant make the element an `a` element.

@Come2Daddy It should likely remain a link because you can click on it instead of clicking on a drop-down item. Typically labels aren't also links.

**Comment by jgthms** [comment]
The `navbar-link` is meant to be used only with a dropdown as sibling.

Why not use the `navbar-item` as link?

```html
<a class="navbar-item bd-navbar-item-documentation  " href="/documentation">
  <span>Documentation</span>
</a>
```

**Comment by indiealexh** [comment]
@jgthms My original point remains, but if you are confirming it should only be used with a dropdown, then it should reflect that.

And in relation to what I am doing, I am using a custom element to make a navbar item, so it acts like div.navbar-item, where as sometimes I want it to act like a.navbar-item (Hoverable, Clickable etc.)

**Comment by jgthms** [comment]
> I am using a custom element to make a navbar item

What do you mean?

**Comment by indiealexh** [comment]
@jgthms like this

```dart
@Component(
  selector: 'nav-bar-item',
  templateUrl: 'nav_bar_item_component.html',
  directives: const [coreDirectives],
  providers: const [],
)
class NavBarItemComponent {
  @Input()
  NavBarItem navBarItem;

  bool get isDropDownMenu => navBarItem.subItems.isNotEmpty;

  Map<String, bool> get elementClasses => {
        "navbar-item": isDropDownMenu,
        "navbar-link": !isDropDownMenu,
        "has-dropdown": isDropDownMenu,
        "is-hoverable": isDropDownMenu
      };

  @HostBinding('class')
  String get classes {
    String classString = "";
    elementClasses.forEach((cssClass, use) {
      if (use) classString += "$cssClass ";
    });
    return classString;
  }
}
```
```html
<template [ngIf]="isDropDownMenu">
        <a class="navbar-link">
            {{navBarItem.text}}
        </a>

        <div class="navbar-dropdown">
            <a *ngFor="let subMenuItem of navBarItem.subItems" href="#" class="navbar-item">
                {{subMenuItem.text}}
            </a>
        </div>
</template>
<template [ngIf]="!isDropDownMenu">
        {{navBarItem.text}}
</template>
```
```html
<div class="navbar-menu" [class.is-active]="navBarMenuIsOpen" id="navMenu">
        <div class="navbar-start">
            <nav-bar-item *ngFor="let startMenuItem of startMenuItems" [navBarItem]="startMenuItem"></nav-bar-item>
        </div>
        <div class="navbar-end"></div>

    </div>
```

**Comment by indiealexh** [comment]
I have a better solution for this problem.

**Comment by jgthms** [comment]
Yeah `navbar-item` is different if it's an `<a>` element. If you can't specify the HTML tag, you need to write your own CSS rules by extending `a.navbar-item`.

**Comment by indiealexh** [comment]
Working on solving my a link problem now

```html
<div class="navbar-start">
            <template ngFor let-startMenuItem [ngForOf]="startMenuItems" [ngSwitch]="startMenuItem?.emotion">
                <template ></template>
                <a class="navbar-item" href="">{{startMenuItem.text}}</a>
            </template>
        </div>
```
