### ISSUE TITLE
SubTitle file name mismatch (v3.0)

### ISSUE THREAD

**Issue by jitcoder** [jgthms/bulma#1808]
This is about **Bulma**.

Bug

Not browser bug
### Overview of the problem

I'm using Bulma **version** [3.0.0] 
Chrome

### Description

Failed to compile.
./node_modules/reactbulma/lib/components/index.js
Module not found: `****/packages/client/node_modules/reactbulma/lib/components/Title/Subtitle.js` does not match the corresponding path on disk `SubTitle.js`.
### Steps to Reproduce

1. create-react-app 
2. yarn add reactbulma
3. import { SubTitle } from 'reactbulma'

### Expected behavior

Successful compilation

### Actual behavior

```
Failed to compile.
./node_modules/reactbulma/lib/components/index.js
Module not found: `****/packages/client/node_modules/reactbulma/lib/components/Title/Subtitle.js` does not match the corresponding path on disk `SubTitle.js`.
```

**Comment by jitcoder** [comment]
please note this issue is not occuring in v1.1.1

**Comment by Come2Daddy** [comment]
[Wrong repo, you should head over here.](https://github.com/kulakowka/react-bulma)

**Comment by jitcoder** [comment]
oh my goodness, how did I not notice that. So sorry!
