### ISSUE TITLE
Question - do we really need 12 html lines to make a simple horizontal form row?

### ISSUE THREAD

**Issue by kpion** [jgthms/bulma#1809]
This is about **Bulma**.

It's a question.

### Overview of the problem
I'm using Bulma **version** 0.7.1
This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**? I did my best.

A lot of typing to create only a simple horizontal row of label + input in a form.

### Description

I tried to make a simple horizontal form, and found out, that according to the docs, I need 12 html lines to create just one simple row in a form, with label + input:  

```
<form class = 'form'>

  <!-- ONE label + input starts here... --> 
  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label class = 'label'>label</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input type = 'text' class = 'text'   value = 'blah' >
        </div>
      </div>
    </div>
  </div>	
  
  <!-- If we want another ONE label + input   then again 
  <div class="field is-horizontal">.....
  --> 
  
</form>
```

Here it is: https://jsfiddle.net/cp8u7s1m/10/ - why so many? Why not 4, like here - https://codepen.io/rstrahl/pen/rxmjgL ? I mean, I believe there must be a reason, but what would that be? 

Or maybe I'm doing something wrong?

I based this code on https://bulma.io/documentation/form/general/#horizontal-form

p.s. 
In pure css it's also 4 lines:  https://purecss.io/forms/#aligned-form
Same in uikit - https://codepen.io/anon/pen/RyNwQa

But I prefer bulma for other reasons :)

**Comment by konradpapala** [comment]
> If you can cover all theses features with less code, you are welcome to PR

@Come2Daddy - it sounds sarcastic, and I'm not sure what did I do to deserve it o.O I thought it's quite clear from my question, than I'm not a CSS guy. So I can't make a PR, I can only ask questions.  

I do understand that Bulma is very feature-rich, and I only touched the top of it.  But there is something like https://en.wikipedia.org/wiki/Convention_over_configuration and I just expected that a single form row will take ~4 lines, and then **when and if** I'll want to add more stuff, and I'll obviously have to.... hmmm.... add more stuff :).  if it really has to be many more from the start - then fine. 

Thanks for the answer.

**Comment by Come2Daddy** [comment]
@konradpapala, no jeering at all, if you can improve something you are welcome to do so. No need to be a CSS guru, I do believe anyone can help with bulma.

That's bulma now, some of its features are nested instead of having too much case specific classes.

**Comment by konradpapala** [comment]
OK, fair enough :)
