### ISSUE TITLE
Bug with scrollable modal (on Chrome)

### ISSUE THREAD

**Issue by vanlong441** [jgthms/bulma#181]
OS: Linux
I clicked on scrollable modal in the documentation [here](http://bulma.io/documentation/components/modal/)

Result in Chrome 50.0.2661.75

![deepinscreenshot20160418205818](https://cloud.githubusercontent.com/assets/1689356/14606695/8175155e-05a8-11e6-93c1-ffaef1bb87ae.png)

Result in Firefox 45.0.1

![deepinscreenshot20160418210026](https://cloud.githubusercontent.com/assets/1689356/14606722/9e0ca1e6-05a8-11e6-8a9d-98645e2eca62.png)

**Comment by madjake45** [comment]
![Chrome scrollable media](https://cloud.githubusercontent.com/assets/6642527/14607030/c6d16c6e-0577-11e6-9068-e649e218fd59.png) Mine appears to work fine, I'm on Version 50.0.2661.75 m

**Comment by vanlong441** [comment]
so I disabled Overlay scrollbar option in chrome://flags and everything is fine now.

**Comment by jgthms** [comment]
Thanks.
