### ISSUE TITLE
is-awesome

### ISSUE THREAD

**Issue by diomed** [jgthms/bulma#1812]
@jgthms 

since it's awesome, **bulma** should have awesomelist ![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)

list of repositories and sites that collect in one place everything that one can make use of with it,
and is made with bulma and for bulma. [extensions / themes etc]

would you make this list as official repo?

**Comment by Dragnucs** [comment]
Please see the [related projects](https://github.com/jgthms/bulma#related-projects) in the readme.

**Comment by diomed** [comment]
I saw related projects.
Still think there should be more comprehensive standalone list for bulma resources.
