### ISSUE TITLE
Missing colors

### ISSUE THREAD

**Issue by zaydek** [jgthms/bulma#1814]
Is it about Bulma or about the Docs?

### Overview of the problem

 This is about the Bulma **Docs**

### Description

The CDN version of Bulma has no trace of `.has-background-grey-*`, see https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.0/css/bulma.min.css

### Steps to Reproduce

1. Open the CDN link, confirm absense of colors
2. Add colors to CDN source
2. OR remove those colors from documentation

### Expected behavior

Expect to see colors in source or not see those colors in the documentation

### Actual behavior

No such colors exist

**Comment by mm98** [comment]
Try using the 0.7.1 version. 
https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css

**Comment by zaydek** [comment]
It's working in 0.7 now. Either it was added or I did something wrong? Either way this can be closed.
