### ISSUE TITLE
Progress bar within Card

### ISSUE THREAD

**Issue by realimpat** [jgthms/bulma#1816]
This is about **a bug**.

### Overview of the problem

 This is about the Bulma **CSS framework** 

 My **browser** is:  Chrome, Firefox

 I am sure this issue is **not a duplicate**?

### Description

Description of the bug, enhancement, or question 
Within a card, progress bars appear small; they do not stretch to fill the with of the card. 

### Steps to Reproduce

1. First Step

div class="card"
2. Second Step
    div class="card-content"
3. and so on...
       progress /progress
/div
/div

### Expected behavior

The progress bar should behave within the card as it does within a box, or outside other elements. 

### Actual behavior

The progress bar is small and smushed.

**Comment by emkajeej** [comment]
Can't reproduce this, here's a pen

https://codepen.io/anon/pen/NLbYEo

Do you have any additional information regarding this issue?
