### ISSUE TITLE
Bulma Docs: Missing 404 Page

### ISSUE THREAD

**Issue by fvcproductions** [jgthms/bulma#1817]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The website is missing a 404 page.

### Steps to Reproduce

1. Go to https://bulma.io/404

### Expected behavior

Show custom 404 page that shows link to go back to homepage.

### Actual behavior

Shows GitHub pages 404 page with no buttons to go to homepage.

**Comment by jgthms** [comment]
I don’t think it’s possible with Github Pages.

**Comment by fvcproductions** [comment]
I found some resources online that indicate otherwise.

- https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/
- https://jekyllrb.com/tutorials/custom-404-page/

Looks like you just need to create a `404.html` page at the root level.
