### ISSUE TITLE
select with "multiple" outlook but allow single selection

### ISSUE THREAD

**Issue by chiu0602** [jgthms/bulma#1821]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.0]

This is a feature request

### Description

With "Multiple select" setting, the "select" element displayed with a list instead of a dropdown box and multiple select is allowed. It is good if this outlook can be chosen with only one option can be selected at a time.

**Comment by jgthms** [comment]
It's the browser's default design. Bulma only customizes it a bit. It would be misleading to the user to have a multiple select design with only one single option selectable.
