### ISSUE TITLE
[Feature Request] Theme independent SASS

### ISSUE THREAD

**Issue by thepra** [jgthms/bulma#1823]
This is about **Bulma**.

Is it about Bulma or about the Docs? **Bulma** 
Is it a bug/feature/question or do you need help? **Feature**

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.0]
My **browser** is: FF,Chrome,Vivaldi,Mobile
I am sure this issue is **not a duplicate**? Yes

### Description

Been using Bulma for a while on my personal project, great overall, but I have designed the webpages around custom themes(more than 1), which isn't easy/comfortable to handle/style because of the many default colours. There's a way for you guys to have a version of bulma without any colours applied?

**Comment by CreativeBulma** [comment]
Hi,

we have created a boilerplate for Bulma.io custom development available in the develop branch in our repository at https://github.com/CreativeBulma/Boilerplate.

Feel free to use it.
W'll update to the last version tonight

**Comment by CreativeBulma** [comment]
Hi @gonzofish,

yes, as I mentioned it's currently in the develop branch. ;-)

**Comment by jgthms** [comment]
You could set `$colors` and `$shades` to empty Sass maps.
