### ISSUE TITLE
No visual difference between link and text inside Hero element having background color.

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#1828]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.1
My **browser** is: Firefox 59.0.2 on linux.
I am sure this issue is **not a duplicate**.

### Description

* Links inside hero with background color is same as text.

### Steps to Reproduce

```html
<div class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <p>This is text and this is <a href="#">link</a></p>
    </div>
  </div>
</div>
```

### Expected behavior

The link should be of different color other than text. They should have visual difference.

### Actual behavior

Link shows up as normal text.

**Comment by northamerican** [comment]
Still an existing issue +1

**Comment by johns10** [comment]
Still an issue.
