### ISSUE TITLE
Improve docs on overriding derived variables

### ISSUE THREAD

**Issue by benjaminapetersen** [jgthms/bulma#1829]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** ["0.7.0]

### Description

Knowing "the Bulma way" for overriding derived variables would be extremely helpful, including several examples. Often truly adopting a framework means learning the idomatic way to do a number of things.  At present, the docs are light on a number of topics (such as overriding derived variables) that would reduce the friction that comes with adopting a framework & leveraging it to do non-trivial things.

Would love to see improved docs on development leveraging the `sass` features aside from using the components!

**Comment by tutuca** [comment]
There is no central variable declaration (a-la bootstrap). So I can't track where the issues come from.
I'm currently shooting on my foot trying to get the carousel to run:

```
    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js!./node_modules/bulma-carousel/dist/bulma-carousel.sass
    Module build failed: 
    $carousel-nav-background: rgba($white, 0.7) !default

```

I have `$white` defined on my top-most style sheet. But it just doesn't pick that up.

**Comment by benjaminapetersen** [comment]
Ah great, then agree entirely.  I'm currently looking at `class-foo` and then go `grep -ri class-foo node_modules/bulma/sass` to find the occurances (if the class name is not generated, otherwise adjust), then see if I can derive the proper way to use a `$var` to adjust the style output before I default to manually overriding the class in vanilla `css`.  

Documenting a better workflow would be extremely beneficial.
