### ISSUE TITLE
when is version 1 ready?

### ISSUE THREAD

**Issue by vanlong441** [jgthms/bulma#183]
when is version 1 ready?

**Comment by jbrooksuk** [comment]
When it's ready :)

**Comment by rajibahmed** [comment]
ha ha, why do you need version 1.0. Just lock whatever version on bower and work with. Looks like to me bumla is using sensible naming conventions, should not break too much.

And we are using it on production already :)

**Comment by jgthms** [comment]
There are still some unstable stuff:

* the `.panel` element is a bit messy
* when you combine elements like a `.card` within a `.hero`, it's not that straightforward
* i want to add toggle options, like button border, button gradients
* need to fix how font-weight is set across the styles
* need some kind of list as well
* `.table` is a bit messy
* `.tabs` could have some improvement as well

And lots of other things.

**Comment by tquetano-r7** [comment]
So taking this is a slightly different direction ...

"why do you need version 1.0" 

You don't ... but semantic versioning should be maintained. There has been changes between the 0.0.x versions that has caused a change in behavior or has added new features, which at bare minimum would result in a minor version change. semver exists not just as a tool to update package managers, it communicates to developers whether the changes can safely be added to my project or requires regression analysis. It also communicates the intended stability of the library, and 0.0.x does not convey a strong stance. 

Understandable that you don't feel comfortable making a 1.x.x vresion yet, its very common that 0.x.x libraries exist in the web world ... but to say that minor version changes don't apply is eschewing semver entirely.

**Comment by jgthms** [comment]
There's a few breaking changes every now and then, so that's why I don't want a v1 yet, as the library is not stable enough.

As soon as it is, I'll switch to proper semver.

**Comment by hyunbinseo** [comment]
Bulma 1.0.0 is here! https://github.com/jgthms/bulma/releases/tag/1.0.0

**Comment by suterma** [comment]
> As soon as it is, I'll switch to proper semver.

Having 0.x is proper semver already. It just indicates that the project is still in it's "settling" phase.
