### ISSUE TITLE
Remove arrow in Navbar items

### ISSUE THREAD

**Issue by Ana06** [jgthms/bulma#1833]
It would be nice to have a class to remove the arrow in the items of the Navbar, something like:

`<a class="navbar-link without-arrow">`

**Comment by Ana06** [comment]
@jgthms I wanted to send a PR. I have modified sass/components/navbar.sass, but using `<link rel="stylesheet" href="css/bulma.css">` in my html I am not able to see my changes. I think I am missing something. Can you please tell me what should I do? :smile:

**Comment by marovargovcik** [comment]
It's most likely because of caching. You made changes but your css file is being served from cache memory. 

See https://superuser.com/a/512833

**Comment by jgthms** [comment]
You need to rebuild the CSS with `npm run build`.
