### ISSUE TITLE
[Feature request] Limit container width to specific breakpoint

### ISSUE THREAD

**Issue by carlotrimarchi** [jgthms/bulma#1834]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I often myself limiting the container width to a specific breakpoint. For example, if I'm using the `.is-widescreen`, I also limit the container to the `$widescreen` breakpoint.

Would it be possible to add classes like `.is-widescreen-only` or something similar? 

```
.is-widescreen-only {
    max-width: $widescreen - (2 * $gap);
}
```

**Comment by jgthms** [comment]
You can disabled breakpoints if you want: https://bulma.io/documentation/overview/responsiveness/#disabling-breakpoints

**Comment by carlotrimarchi** [comment]
But that would prevent one from having a widescreen container in the whole website, for example. What I mean is that in specific circumstances I don't want a container to grow beyond a certain breakpoint
