### ISSUE TITLE
Q: Bulma altering default heading font-size and font-weight

### ISSUE THREAD

**Issue by marovargovcik** [jgthms/bulma#1836]
This is about **Bulma**.

It is a **question**.

Why is Bulma altering default **font-size** and **font-weight** of **heading (h1-h6)** elements?

I decided to use Bulma in my administration panel where user can write their profile bios or projects READMEs in WYSIWIG editor. All styling is default or inline.

So if user create his profile bio as following
```
<h1>My life</h1>
<h2>Childhood</h2>
```

It's all the same size because of Bulma's altering default values.

Is there any reason for this?

**Comment by thatnini** [comment]
Have you  tried adding `<div class="content">` to get the font size and font weight to change?

ie 
```html
<div class="content">
	<h1>My life</h1>
	<h2>Childhood</h2>
</div>
```

See [https://bulma.io/documentation/elements/content/](https://bulma.io/documentation/elements/content/) for more details

**Comment by marovargovcik** [comment]
Thanks, i did not know about `.content` class. I serves me well for my needs.

I still see this as workaround. Imagine not having an option to add class `.content` to some kind of textarea generated by various kinds of wysiwyg/markdown editors. 

That's for now only one thing that comes to my mind where it might be useful to keep default styles of headings.
If there isn't really a good reason for altering default styles of headings, I would love to see this change.

**Comment by yxngl** [comment]
I am new to Bulma and was surprised by this behavior too. I think it is the design concept and explained [here](https://bulma.io/documentation/overview/classes/).

> Because Bulma solely comprises CSS classes, the HTML code you write has no impact on the styling of your page. 

Then there are title classes to do proper styling, like.
`<h1 class="title is-1">Title 1</h1>`

**Comment by thatnini** [comment]
Maybe its worth mentioning in the docs that a [CSS reset](https://github.com/jgthms/bulma/blob/master/sass/base/minireset.sass) is being used to ensure consistency across all browsers?

**Comment by jmarca** [comment]
This issue has bitten me as well.  I'm using Bulma with Hugo.  Hugo's markdown parser (blackfriday) appears to stick to the "just make HTML" spirit of markdown (but maybe that will change---https://github.com/russross/blackfriday/issues/181) which means you can't add styling tags to markdown.  Thus there is no way to generate HTML `<h1>` etc tags with class="title is-1". (well, obviously it is markdown and I can just use plain html...but sometimes I want my markdown source to feed latex as well.)

The easiest solution for me is to switch to using pandoc as my markdown processor inside of Hugo.  Then something like:

```
# Work products {.title}
```

will get converted into 

```
<h1 id="work-products" class="title">Work products</h1>
```

But I've also been re-reading the HTML5 spec to get some knowledge and insights.  There are some interesting items.  The sections part of the spec (http://w3c.github.io/html/sections.html#headings-and-sections) to my reading basically says that the semantic purpose of the h1, h2, etc tags is to imply that what follows is a new section of content with a hierarchy based on the heading level.  It also says *not* to use `<h2>` etc to specify subheads---something I've always done!  Instead the spec links to another section discussing how to set up subtitles: 
(http://w3c.github.io/html/common-idioms-without-dedicated-elements.html#common-idioms-without-dedicated-elements).  There are a number of ways to achieve title and subtitle formatting using the `<header>` tag to wrap an `<hN>` tag and either `<p>` or `<span>` tags.  *But...* ironically, `<header>` tags and `<section>` tags aren't part of markdown!  So for me, the best way to mix content and style in markdown is to use pandoc with bulma and do something like:

```
# Work products {.title}

Stuff we've done {.subtitle}

We are strong believers in the power of open data,
```

which pandoc renders as:

```
<h1 id="work-products" class="title">Work products</h1>
<p>Stuff we’ve done {.subtitle}</p>
<p>We are strong believers in the power of open data,
```

**Comment by mbwhite** [comment]
I was also struggling with this issue; it was the one thing that I didn't quite like that it removed the html concepts.  In the case where this is most trouble to me was where I didn't have much control over the generated html - come from markdown via markdown-it. (and it wasn't immediately possible to add in the classes needed)

The `content` class solved the issue;  though I would prefer to use a customisation approach.  Having used scss to change a few other colours - it seems natural to try and say.   'apply all the is-text-1 to h1' tags.  Thought I could do this with @  extend in scss but couldn't get that to work.

Not tried this yet - but if I alter the style of `is-size-1` how much will be reflected in the h1's style?

**Comment by mkstix6** [comment]
I have more experience with Bootstrap so let me know if I'm missing the point here, but,

It feels to me like `$heading-color` and `$heading-weight` would be nice additions to this list of [Generic variables](https://bulma.io/documentation/customize/variables/#generic-variables) so we can quickly set a general heading style up front.

I have a site where all the h1, h2 etc… are weight 800 everywhere. I'd like to avoid having to drop `.has-text-weight-bold` on every heading by default.

**Comment by roncarino** [comment]
> Thanks, i did not know about `.content` class. It serves me well for my needs.
> 
> I still see this as workaround. Imagine not having an option to add class `.content` to some kind of textarea generated by various kinds of wysiwyg/markdown editors.
> 
> That's for now only one thing that comes to my mind where it might be useful to keep default styles of headings.
> If there isn't really a good reason for altering default styles of headings, I would love to see this to change.

This is exactly what it is happening to be unfortunately. Using "https://editorjs.io/" and "header" tool. Bulma overrides its css and I am not entirely sure of how to solve it honestly.

**Comment by hairypalm** [comment]
I'm having trouble because of this as well.  The .content class is fine, but the styles under .content are different than the corresponding Bulma classes.  Example, class of 'title is-1' seems like it should match .content <h1>, but it does not.  As such I now need to build a translator for rich-text content so that it matches the rest of my site, or pull out Bulma.  Disappointing because I'm pretty far into my project and I never would have gone for Bulma had I known that I can't use a rich text editor.

You should probably document that on the Bulma landing page so that nobody accidentally gets into if they intend to rely on standard html concepts like headers.

**Comment by joallard** [comment]
Related to #433

**Comment by laurensV** [comment]
> but the styles under .content are different than the corresponding Bulma classes.

This indeed is the biggest problem. class `title is-1` should be exactly the same as `h1` under the `content` class. 

Also, the presedence is really strange if you want to combine the two. For example:
I have the `content` class wrapped around my entire app, but then if you mix `h1.content`  with the class `subtitle is-3`, the font-size of is-3 gets the precedence (so the text becomes smaller which is what I suspected and want), but the font-weight is not the font-weight of `.subtitle` (`font-weight: 400;`) but the font-weight of `.content h1` (`font-weight: 600;`)

**Comment by zhqu1148980644** [comment]
The same problem.

**Comment by turtle-stack** [comment]
This seems to solve the issue for me.
```css
@import "~bulma/bulma";

h1, h2, h3, h4, h5, h6 {
  @extend .title;
}

h1 {
  @extend.is-1;
}

h2 {
  @extend.is-2;
}

h3 {
  @extend.is-3;
}

h4 {
  @extend.is-4;
}

h5 {
  @extend.is-5;
}

h6 {
  @extend.is-6;
}
```

**Comment by vovanrew** [comment]
I had the same problem with editorjs. Heading wasn't actually changed when I was picking any heading value (h1, h3 etc). specifying `content` class helped to resolve the issue:
`<div id="editorjs" class="content"></div>`

**Comment by marovargovcik** [comment]
I think this issue can be closed now. Use `.content` class that will make sure your HTML looks sick just as with Bulma classes 🥇
