### ISSUE TITLE
Question: Minified bulma build size

### ISSUE THREAD

**Issue by sattalk** [jgthms/bulma#1844]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.7.1 

### Description

Compiled a very basic bulma integration consisting of:
- a theme file with just one is_primary color
- an index file with a button using the is_primary color
- build a react app using webpack

This generated a css file of size  **156 kB**

Is this an expected size or can it be reduced further?

This is my webpack setup (rules section)
```
module: {
        rules: [
            {
                test: /\.(scss|sass)$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {
                            loader: 'css-loader',
                            options: { minimize: true }
                        },
                        {
                            loader: "sass-loader",
                            query: {
                                localIdentName: '[name]__[local]__[hash:base64:5]',
                            },
                        }
                    ]})
            },
            {test: /\.(js|jsx)$/, exclude: /node_modules/, use: ["babel-loader"]},
            {test: /\.css$/, loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {loader: 'css-loader',
                            query: {
                                minimize: true,
                                modules: true,
                                localIdentName: '[name]__[local]__[hash:base64:5]',
                            } }
                    ]}) }
        ]
    },
    plugins: [
        new ExtractTextPlugin('admin.min.css'),
   ]
```

**Comment by ayushsharma82** [comment]
The Size can be further reduced by enabling gzip on server.

**Comment by sattalk** [comment]
Thanks @ayushsharma82 

I intend to do that. However, I wanted to verify if this is an expected build size.

**Comment by VizuaaLOG** [comment]
It would be if you're including everything. In most cases this is not required and so you should only include the modules required via sass/scss.

I've also had good results with pruifycss I think it's called, that will further reduce your bundle sizes as it will remove CSS that is not used in your html pages.
