### ISSUE TITLE
Sticky parts... no class or modifiers or helpers for this?

### ISSUE THREAD

**Issue by tofanelli** [jgthms/bulma#1854]
This is about **Bulma | the Docs**.

 Is it about Bulma or about the Docs?  Yes, a missing part (maybe)
Is it a bug/feature/question or do you need help?  Feature / question help needed

### Overview of the problem

This is about the Bulma **CSS framework**  - Yes
This is about the Bulma **Docs**  - Yes
I'm using Bulma **version** [0.7.1] 
My **browser** is: Chrome 65

I am sure this issue is **not a duplicate**?  Yes

### Description

What is the class name to make some parts sticky like in the docs? There is no class or helpers or modifiers to this in the docs to do this and I really would love to implement this.

Cheers =)

**Comment by jgthms** [comment]
It's not part of Bulma. It's only in the Bulma docs CSS. It also requires JS to work, but feel free to dig in the source code!
