### ISSUE TITLE
Cannot import sass/utilities/mixins

### ISSUE THREAD

**Issue by sarink** [jgthms/bulma#1862]
Usage:
```
// my_file.scss
@import "bulma/sass/utilities/mixins";
```
Error:
```
Undefined variable: "$border".
```
Because of this line: https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L240

**Comment by events-jonas-chrisw** [comment]
same here....

**Comment by alqu** [comment]
I had the same problem.

What I did before in one of my css files:
```scss
@import "~bulma";
@import "~buefy/src/scss/buefy";
// ...
```
Error like above: `Undefined variable: "$border".`

I Adjusted it to:
```scss
@import "~bulma/bulma.sass";
@import "~buefy/src/scss/buefy";
// ...
```
And voilà, it worked. I guess that automatically the "style"-entry of Bulma's `package.json` is being used for inclusion by default.

**Comment by jacquescrocker** [comment]
I'm running into this everywhere also. Are we not supposed to use Bulma mixins on its own?

**Comment by jacquescrocker** [comment]
My workaround was to create my own mixins file that looks something like this:
```
$border: 0
@import "~bulma/sass/utilities/mixins";
```

Probably need to add more variables there

**Comment by alqu** [comment]
Forget my comment [above](#issuecomment-392075080)

@jacquescrocker is right here. Get your includes right and then it works. I only had to follow the readme [here](https://bulma.io/documentation/overview/customize/).

Sorry for that mess.

**Comment by jesprider** [comment]
The same here. Fixed with `$border=0`

**Comment by derushio** [comment]
fixed wiith

```
@import '~bulma/sass/utilities/initial-variables';
@import '~bulma/sass/utilities/derived-variables';
@import '~bulma/sass/utilities/mixins';
```

**Comment by Log1x** [comment]
Ran into this issue just now. Would like to do a PR for it, but would like to know how @jgthms wants to handle it? Should `$border` be moved to `initial-variables.sass` since its being `@import`ed in `mixins.sass`? Any preference here?

**Comment by jgthms** [comment]
Change `$border` to `$grey-lighter`.
