### ISSUE TITLE
Update default value of $gap in doc

### ISSUE THREAD

**Issue by yxngl** [jgthms/bulma#1864]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The default value of $gap in the doc is [32px,](https://github.com/jgthms/bulma/blob/master/docs/_data/variables/utilities/initial-variables.json#L182) while it is now [64px.](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass#L49)

**Comment by dylanitorium** [comment]
I was justing checking to see if there was an issue about this - I think the docs are right. The sass is wrong. 

The breakpoint variables say that they should be `+ 4rem`. The REM set by bulma is `16px` which means `64px` is `4rem` but the breakpoint variables are adding `2 * $gap` which would be 128px or 8rem!

**Comment by corford** [comment]
I'm also confused by this. Either the docs and comments on the breakpoint variables are wrong or the sass is wrong.

@jgthms $gap was increased from 32px to 64px on this commit: https://github.com/jgthms/bulma/commit/6b53425544cd15bb848750fb8eac3cd0cf8c71bd#diff-542e9110810d7ce528d80036280f411a

**Comment by corford** [comment]
Working on the assumption that the sass is wrong, I've created a PR to fix it here: https://github.com/jgthms/bulma/pull/2039

**Comment by Dalisra** [comment]
Was trying to test Bulma but documentation has some mistakes:
https://bulma.io/documentation/layout/container/

> This container is fluid: it will have a 32px gap on either side, on any viewport size.

But it css on large devices changes to:
`
@media screen and (min-width: 1088px)
.container.is-fluid {
    margin-left: 64px;
    margin-right: 64px;
`

And from 770px up to arround 1085px another CSS kicks in removing the gap eintirely:

`
.container {
    margin: 0 auto;
    position: relative;
}
`
