### ISSUE TITLE
Content inside a column and "position: fixed;"

### ISSUE THREAD

**Issue by NachoNav** [jgthms/bulma#1866]
![captura de pantalla 2018-05-12 a las 14 45 32](https://user-images.githubusercontent.com/22047808/39957416-2c9cba1c-55f3-11e8-8f7d-6302f4e27549.png)

This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help? 

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I have two columns. Inside one of them, I have a content div. When I set this div position: fixed, it overlays the column.

### Steps to Reproduce

1. Create a column.
2. Create a content div inside it.
3. Give it the "position: fixed;" style.

### Expected behavior

I expected it to be fixed and inside the column.

### Actual behavior

The text goes over the column.

**Comment by jgthms** [comment]
By adding `position: fixed` the element is out of the flow, and is positioned relatively to the viewport.

Read more: https://cssreference.io/property/position/ https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by lukepighetti** [comment]
Hi @jgthms this definitely works correctly, I agree, however, I do wonder what the best way is to fix a column in place. 

This example shows a menu on the left which is located within a column and it would be nice if I could fix it in place.

![screen shot 2018-05-23 at 7 27 54 pm](https://user-images.githubusercontent.com/666539/40456446-7356d1de-5ebf-11e8-95cc-18235899a384.png)

**Comment by finestpixels** [comment]
I think what you're looking for is:
  `position: sticky;
    top: 0;`

**Comment by maxailloud** [comment]
Sticky is not supported by IE so maybe not the best.

**Comment by oxavibes** [comment]
> Sticky is not supported by IE so maybe not the best.

Who cares about IE? 😆
