### ISSUE TITLE
AMP Support! Worth it?

### ISSUE THREAD

**Issue by AdsonCicilioti** [jgthms/bulma#1868]
Hello guys!

I want to add something important here that can help or help me learn and participate in the scenery in a quiet way.

See: https://www.ampstart.com/templates

Choose some templates and navigate. Try on a mobile device as well.

In this case they use BassCSS as a base + an own library + particularities of each model.
What is incredible and admirable is that they have been able to create rich and beautiful pages in the AMP standard.
There is only one task in the project's Gulpfile that removes `! Importat`'s, adapting BassCSS to AMP compatibility! The SpectreCSS also make your version https://github.com/niutech/amp-spectre...  PureCSS Leave a recommendation, just by removing some `! Important`'s...  It did not even hurt!
I do not know what adaptations would be needed for Bulma, but it's not a seven-headed creature.

Another thing I did in a Node.js project that uses a Template Engine on server side was the use of the Shaking Tree concept, where a task runs through all the views and generates a clean css containing only the CSS of the classes present in the html of each page.

I really like BULMA and believed that they could give more attention to AMP. I know that Google is very pretentious and presumptuous, but his intentions are noble, but they are very willing to invest in this new standard.

The internet will always be subject to circus polarities as regions that have connections limited mainly to mobile.
And good that most of us have an excellent connection in their regions, but we have the cost factor of resource use in servers, which in my humble opinion, is very vital for the existence and evolution of the internet.

How good Google thinks about these things. Merit them if they are a great company.

I know that BULMA is already a complete and relatively light library ... And it is because I like and admire the project that I leave my opinion in evaluating the monitoring and adherence to the AMP very carefully!

It would be great to be able to use BULMA on even Accelerated Mobile Pages.

@jgthms , Please think about it .. I promise to help with my pennies. 

I would like to hear your thoughts

Hugs!

**Comment by AdsonCicilioti** [comment]
Right @jgthms , I've seen some of your considerations on other issues.

As ampstart shows an AMP site can use well over 10% of a library.
The dependencies of Bulma to JavaScript is not so great (that's fine). I think I'll start working on this `bulma-amp` version.

**Comment by cekvenich** [comment]
Is there an AMP compatible version of Bulma anywhere?

**Comment by turbopixel** [comment]
```
Feel free to create a bulma-amp extension for people to use. But it's not something I want to maintain as part of Bulma.
```
by @jgthms at https://github.com/jgthms/bulma/issues/1037#issuecomment-320900518

------
I think we should start a own bulma-amp version. Can you make a repository or bulma organization for us?

**Comment by cristianpb** [comment]
@AdsonCicilioti @turbopixel  There is no need to have a dedicated bulma-amp extension. You can create AMP pages with bulma using something like purifycss to remove all the classes that you don't use in your html. There is an article about how to do it [here](https://cristianpb.github.io/blog/bulma-amp).
