### ISSUE TITLE
[JUST A QUESTION] Is it possible to make Modal shrink upon Mobile Browser tool bar pop up? 

### ISSUE THREAD

**Issue by Scarittagle** [jgthms/bulma#1874]
When I using iOS Safari to open a relatively large modal and bottom tool bar pop up it won't able to shrink top and bottom for a bit. As a result the tool bar will block a portion of the modal footer and header, make it difficult to tap the buttons on header or footer.

<img width="393" alt="wx20180516-103131 2x" src="https://user-images.githubusercontent.com/11699179/40126065-6d5856e2-58fa-11e8-84ef-abcbdfea4e41.png">

**Comment by jgthms** [comment]
I've got this:

![image](https://user-images.githubusercontent.com/1254808/40445702-2d2d9efa-5ecd-11e8-8d51-07aa697f8abf.png)

The `max-height` is set as:

```sass
max-height: calc(100vh - #{$modal-content-spacing-mobile})
```

You can customize that.
