### ISSUE TITLE
Feature request – "is-color"

### ISSUE THREAD

**Issue by lukepighetti** [jgthms/bulma#1876]
Bulma has some defined colors beyond primary, light, white, black, link, info, success, warning, danger

They are described here https://bulma.io/documentation/overview/variables/

I would like to be able to access them with "is-purple", "is-orange", "is-red" etc.

Thank you

**Comment by jgthms** [comment]
Bulma comes with semantic color names like `info`, `success`, `danger`… which use the blue, green, red… colors.

You can however define a `$custom-colors` Sass map to add your own named colors.

**Comment by lukepighetti** [comment]
I see that, I am asking for it to be included by default. Thank you.

**Comment by ystoneman** [comment]
@jgthms I see on your personal website, you combined a `shadow` class with an `is-{$customColor or bulmaColor}` class. How did you combine those two? Could you share how you created a map, or two maps, to loop through both the Bulma colors and custom colors like purple? And how you then added those to a box-shadow? :blush: :innocent:

<img width="1010" alt="box-shadow-purple" src="https://user-images.githubusercontent.com/20830609/49666847-227e7880-fa0e-11e8-94e7-44e5a2725435.png">
