### ISSUE TITLE
Change padding for Footer

### ISSUE THREAD

**Issue by dustinmichels** [jgthms/bulma#1878]
This is a feature request about **Bulma**.

### Overview of the problem

I'm using Bulma **version** [0.7.1]

### Description

The [`Footer` layout element](https://bulma.io/documentation/layout/footer/) comes with a lot of padding, which doesn't appear to be customizable. I would like it if I could set the padding, perhaps using a css class like `is-small` or else using SASS variables.

### Steps to Reproduce

You can use the example footer demonstrated in the docs [here](https://bulma.io/documentation/layout/footer/)

**Comment by i--fixedit** [comment]
you fuck

**Comment by webuxmotion** [comment]
We need this feature

**Comment by Chrisx84** [comment]
yes badly, and possible option to fix it to the very bottom of the site

**Comment by cgonzalezp91** [comment]
In the mean time you can add the `!important` to your own css modifying the footer element
```css
footer{
    padding: 2rem 1rem 4rem !important;
}
```
