### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#188]
I'm having some trouble compiling the sass files. I'm getting a segmentation fault. 
```
jc@mbp ~/ $ node-sass -v 
node-sass	3.5.3	(Wrapper)	[JavaScript]
libsass  	3.3.5	(Sass Compiler)	[C/C++]

jc@mbp ~/ $ node -v
v5.4.1

jc@mbp ~/ $ npm -v
3.5.3

jc@mbp ~/ $ node-sass node_modules/bulma/bulma.sass
[1]    11195 segmentation fault  node-sass node_modules/bulma/bulma.sass
```

I've tried importing the source files one by one, to see how far in the process it gets. Utilities, base, elements and components, compiles just fine. But when reaching `node_modules/bulma/sass/layout/hero` in the layout folder it dies.

Are any of you experiencing the same?

**Comment by jeppech** [comment]
Okay, so this is not a issue with Bulma. It seems to be an issue with newer versions of [node-sass](https://github.com/dlmanning/gulp-sass/issues/475), specifically the `3.5.x` tags.

I've hardcoded v3.4.2 of node-sass in my packages.json file, and re-installed the dependencies. Everything works again :)

**Comment by crodriguez1a** [comment]
👍  I had the same issue and this fix also worked for me.
