### ISSUE TITLE
input fa-icon onClick function not working

### ISSUE THREAD

**Issue by ScriptWorld-git** [jgthms/bulma#1883]
This is about **Bulma**.

This is a Bug regarding the Input / fa-icon right or left.

### Overview of the problem

I got an Input with a font awesome icon on the right side.
I want to implement an onClick handler on the span of this icon, but it is never firing. 
I use React.js.

### Steps to Reproduce

```jsx
<span
    class="icon is-small is-right"
    onClick={e => {
        console.log('test');
         }}
>
    <i
      class={classnames('fas', {
           'fa-eye': this.state.passwordVisible,
           'fa-eye-slash': !this.state.passwordVisible
                })}
     />
</span>
```

The icon displaying is correct.

### Expected behavior

console logs 'test' when I click the icon.

### Actual behavior

nothing happens, not even an error.

**Comment by jgthms** [comment]
This seems to be a React issue, not a Bulma one.
