### ISSUE TITLE
Reopen -> How to set background image from user on card ?

### ISSUE THREAD

**Issue by karolv4** [jgthms/bulma#1885]
This is about **Bulma | the Docs**.

 Is it a bug/feature/question

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma (0.7.1)
My **browser** is: Google chromium version 66.0.3359.139

 I am sure this issue is **not a duplicate**
### Description

Some time ago I added a thread about how to set the background of the card (https://imgur.com/a/lpsvFw1) for a photo that will be put on the form by gem carieerwave from the Ruby On Rails framework. I mean instead of white color. I did not get help and the topic was closed so I add it again. 

### Steps to Reproduce

1. First Step Create card
```
<div class="card">
  <div class="card-content">
    <p class="title">
      “There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.”
    </p>
    <p class="subtitle">
      Jeff Atwood
    </p>
  </div>
  <footer class="card-footer">
    <p class="card-footer-item">
      <span>
        View on <a href="https://twitter.com/codinghorror/status/506010907021828096">Twitter</a>
      </span>
    </p>
    <p class="card-footer-item">
      <span>
        Share on <a href="#">Facebook</a>
      </span>
    </p>
  </footer>
</div>
```
2. Second Step That's all - how to set background image on this card?

Expected behavior

Photo from form carieerwave from user (ruby on rails)  instead of a white background

Actual behavior
![39531381-4abb0ff0-4e2b-11e8-803a-7c04b24076ed](https://user-images.githubusercontent.com/38893118/40441262-d0764c40-5ec0-11e8-9795-9b221026adec.png)

**Comment by jgthms** [comment]
Just use plain CSS:

```css
.card {
  background-image: url(path/to/image.png);
}
```
