### ISSUE TITLE
Problem with tags on mobile device? 

### ISSUE THREAD

**Issue by karolv4** [jgthms/bulma#1886]
This is about **Bulma | the Docs**.

Is it a bug/feature/question

Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma (0.7.1)
My browser is: Google chromium version 66.0.3359.139
I am sure this issue is not a duplicate

**Description**

I wanted to use bulma tags, but when minimizing the window / on the phone tags are falling apart and overlapping each other:

### Steps to Reproduce

1. First Step
![screenshot from 2018-05-23 19-49-59](https://user-images.githubusercontent.com/38893118/40441856-83ee5eec-5ec2-11e8-857a-f10feec0dffd.png)

### Expected behavior

I want the tags to be set up like on a PC when scaling / on the phone so that they do not overlap

### Actual behavior

![screenshot from 2018-05-23 19-42-48](https://user-images.githubusercontent.com/38893118/40441708-1b43ec9a-5ec2-11e8-8d49-7b6f27185d0a.png)

**Comment by jgthms** [comment]
Did you add padding to the tags?

**Comment by karolv4** [comment]
@jgthms  
![40441856-83ee5eec-5ec2-11e8-857a-f10feec0dffd 1](https://user-images.githubusercontent.com/38893118/40775528-97a0e912-64c8-11e8-9861-779fd81c008d.png)

**Comment by jgthms** [comment]
What’s your markup? What’s your CSS?
