### ISSUE TITLE
Thoughts on Google font usage 

### ISSUE THREAD

**Issue by MartijnCuppens** [jgthms/bulma#1889]
### Overview of the problem
This is about the Bulma **Docs**

### Description

On the homepage, in the customize section, Google fonts are imported with `@import`. This disables parallel downloading of the css files.

Also, `Nunito` uses a serif fallback while it's a sans-serif font.

### Steps to Reproduce

1. visit https://bulma.io/#customize

**Comment by jgthms** [comment]
Good point.

I built it rather quickly. I could load it on demand like I did here: https://jgthms.com/web-design-in-4-minutes/

**Comment by MartijnCuppens** [comment]
The sans-serif issue is quickly fixed with #1893.

For the google font, maybe we can mention some thing above the code? Or just use a system font?

**Comment by patrickabkarian** [comment]
Google Fonts CDN checks for the 'local' version of the font first.
If you only have a bold version of the font installed it will only use that one, even if the website defines font-weight:normal;

I'on think that's good.
