### ISSUE TITLE
Webpack compilation

### ISSUE THREAD

**Issue by jeffijoe** [jgthms/bulma#190]
### Checklist

* [ ] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [ ] I'm using Bulma **version** [0.0.24]
* [ ] My **browser** is: Chrome
* [ ] This is a **Sass** issue: I'm using version [3.5.3]

### Description

In order to get Bulma *0.0.17* working, we had to use something like:

```sass
@import "~bulma/bulma/utilities/utilities";
@import "~bulma/bulma/config/variables";

@import "~bulma/bulma/config/generated-variables";
@import "~bulma/bulma/base/base";
@import "~bulma/bulma/elements/elements";
@import "~bulma/bulma/components/components";
@import "~bulma/bulma/layout/layout";
```

When using Bulma *0.0.24* which [supposedly had fixed the webpack issue](https://github.com/jgthms/bulma/issues/28), we should be able to simply `@import "~bulma/bulma"`, but this gives sass compilation issues, presumably because the imports are not working correctly - some `$color`s are undefined.

Manually importing every single file does not work either.

### Steps to Reproduce

1. Set up Webpack with sass-loader
3. Import bulma

_Expected behavior:_ It should work

_Actual behavior:_ It does not.

**Comment by combsco** [comment]
I've recently updated to Bulma 0.0.24 and also using Webpack + SASS Loader. Haven't experienced any problems with the basic `@import "~bulma/bulma";` inside `custom.scss`

Webpack:
```
      {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader']
      }
```

Site currently using Bulma and Webpack - https://beta.pinellas911.co/

What problems do you run into?

**Comment by jeffijoe** [comment]
@combsco I will try updating node-sass from 3.5, give me a few.

**Comment by jeffijoe** [comment]
@combsco Didnt work, here's the error I get when compiling:

```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader?sourceMap!./~/sass-loader?sourceMap&outputStyle=expanded!./client/components/App/App.scss
Module build failed:
undefined
                         ^
      Argument `$color` of `rgba($color, $alpha)` must be a color

Backtrace:
        node_modules/bulma/sass/components/media.sass:35, in function `rgba`
        node_modules/bulma/sass/components/media.sass:35
```

**Comment by combsco** [comment]
If I do ...
`require('css-loader?sourceMap!postcss-loader?sourceMap!sass-loader?sourceMap&outputStyle=expanded!./custom.scss')` Like your error shows I still don't get any build failures but Bulma doesn't load. I have to add `style-loader` to that require for Bulma to load properly.

**Comment by jeffijoe** [comment]
I have style loader too, the output just does not show it

**Comment by jeffijoe** [comment]
This is my loader config:

```js
      {
        test: /\.(s?[ac]ss)$/,
        loaders: [
          'style?sourceMap',
          'css?sourceMap',
          'postcss?sourceMap',
          'sass?sourceMap&outputStyle=expanded'
        ]
      }
```

**Comment by jeffijoe** [comment]
Oh god..

Yeah, so I found the issue. I had this:

```
$border: 'red';
```

That's not valid - quotes screwed it up.

**Comment by jeffijoe** [comment]
Can I still customize variables when importing like this though?

**Comment by combsco** [comment]
I would assume so but I haven't tried.

http://bulma.io/documentation/overview/variables/

**Comment by jeffijoe** [comment]
So set them before importing, got it.. So the first variable-setter wins? Bulma won't override them?

**Comment by thatdoorsajar** [comment]
I am having the same error as @jeffijoe with SASS compilation if I follow the Bulma docs to register variables then `@import "bulma"` afterwards.

However, if I remove the Bulma variables file from the Bulma NPM installation and create my own exact copy of variables in my local resources folder then import Bulma like this:
`@import "node_modules/bulma/sass/utilities/utilities"
@import "variables"
@import "node_modules/bulma/sass/base/base"
@import "node_modules/bulma/sass/elements/elements"
@import "node_modules/bulma/sass/components/components"
@import "node_modules/bulma/sass/layout/layout"` 

It works fine. This suggests it's not an issue with `node-sass` etc. but with the order of compilation!?
