### ISSUE TITLE
Modal doesn't center in IE11

### ISSUE THREAD

**Issue by eduardoarandah** [jgthms/bulma#1902]
Use IE11.48

Reproduce:
https://bulma.io/documentation/components/modal/

Click "launch example modal", it goes to the right

I know Browser Support says IE partially supported, however IE11 is used more than safari (7%)

(Works perfect in Edge)

![bulma](https://user-images.githubusercontent.com/4065733/40740614-e21653b6-640e-11e8-9cc1-e14769ae51aa.png)

**Comment by patrickabkarian** [comment]
https://github.com/jgthms/bulma/pull/1905
