### ISSUE TITLE
[question] use Bootstrap reboot.css instead of minireset.css?

### ISSUE THREAD

**Issue by jimblue** [jgthms/bulma#1912]
Hi there!

I was wondering what do you think about using Bootstrap 4 **reboot.css** instead of **minireset.css**?

There is plenty of advantages like the mobile fast click hack that speed up any delay that might exist for touch users.

Cheers

**Comment by jimblue** [comment]
Hey,

This is a nice reading about reboot CSS.
On point 3 the talk about the mobile fast click hack.

**Comment by jgthms** [comment]
In that case, I'd rather include it in minireset which is very lightweight: https://github.com/jgthms/minireset.css

**Comment by jimblue** [comment]
Good idea!

**Comment by jimblue** [comment]
Hey @jgthms !

You've closed this issue without updating minireset.css !

Did you change your mind?

Cheers
