### ISSUE TITLE
how to customize different fonts for headlines and paragraphs in content 

### ISSUE THREAD

**Issue by juh2** [jgthms/bulma#1915]
### Overview of the problem

This is about the Bulma **CSS framework** 

This is a **Sass** issue: I'm using version 0.6.2 

### Description

I could not find a simple customization of different fonts for headlines and paragraphs in the content div. 

In the sass files I found: $body-family and $code-family but not something like $headline-family

Is there an easy way to define different fonts?

**Comment by jgthms** [comment]
Ah yeah there’s another issue for that.

**Comment by juh2** [comment]
I would like to follow the other issue but can't find the one you refer to. Can you point to the issue in question? Thanks a lot.

**Comment by LucyI** [comment]
@juh2 it's here:
https://github.com/jgthms/bulma/issues/349
