### ISSUE TITLE
A combination of .container and .section?

### ISSUE THREAD

**Issue by mgenware** [jgthms/bulma#1917]
Not an issue, but a suggestion.

From what i read from the source code:
`.container` is horizontally centerred, and has a max width on wide screens.
`.section` provides additional paddings.

In bootstrap and foundation, people use `.container` (`.row` in foundation) extensively, and they behave like a combination of bulma's `.container` and `.section`. For me, i use `.section`+`.container` and `.section` quite a lot, and i never use `.container` without `.section`.

So i ended up with much boilerplate like this:
```html
  <section class="section">
    <div class="container">
      ...
    </div>
  </section>
```

Possible to have a combination of `.section` and `.container`, just like bootstrap's `.container`?

Anyway, thanks for this great framework.

**Comment by emkajeej** [comment]
Without `.section`, you would never be able to have a background colour or image spanning the entire viewport width with only `.container`. (Mostly used to break up the page design.)

One could argue that `.section` doesn't need the paddings though, in that case just use a classless `section`.

**Comment by jgthms** [comment]
You can try using the fluid container.
