### ISSUE TITLE
'Non Responsive' Navigation Bar?

### ISSUE THREAD

**Issue by nodediggity** [jgthms/bulma#1918]
This is about **Bulma**.
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]

### Description
I have a use case for the navigation bar, in which I do not want it to be responsive. I **do not** want the hamburger menu and need to keep the top level menu as is.

Reading the docs I cannot find a class / helper for this and google is not my friend also.

I *believe* something is going on with the ```navbar-dropdown``` class when Bulma goes below a particular breakpoint. 

How can I override this behaviour please?

**Comment by nodediggity** [comment]
I was able to achieve this by adding some additional classes to my component and overriding the default behaviour 👍

**Comment by TempleOfTemplar** [comment]
> I was able to achieve this by adding some additional classes to my component and overriding the default behaviour 👍

cool, but can you share you solution?

**Comment by Greenscreener** [comment]
Oh pleeease. This is the most evil thing you can dooo. I want slution PLZ.

**Comment by k3bra** [comment]
I would like to know the solution for this too

**Comment by Chipplayer** [comment]
My navbar is not responsive please help I have copied all the correct code form Bulma Docs but still it is not working

**Comment by Greenscreener** [comment]
@Chipplayer This is very unrelated to this issue. 

Put these two lines into your html file if you haven't already: https://bulma.io/documentation/overview/start/#code-requirements

**Comment by oliveradria** [comment]
If this helps anyone, I set `$navbar-breakpoint: 0;` so the navbar doesn't get a chance to become responsive. (v0.7.4)
