### ISSUE TITLE
Dropdown Button?

### ISSUE THREAD

**Issue by taylorotwell** [jgthms/bulma#192]
Is there any baked in way to do a "dropdown button" similar to this: http://v4-alpha.getbootstrap.com/components/button-dropdown/

Basically looking for a dropdown like construct I can put in a top navbar for account settings, etc.

**Comment by SEAPUNK** [comment]
Is something like this possible without Javascript?

**Comment by tquetano-r7** [comment]
Far as I can tell, there is no "dropdown" construct (at least I can't find it in the documentation), however in reality the only difference between it and a card would be z-index and potentially a box-shadow. The construct you're looking for could be put together with a few lines of CSS:
```
.dropdown {
  box-shadow: 0 0 8px #777;
  display: none;
  left: 0;
  position: absolute;
  top: 100%;
  z-index: 1000;
}

.dropdown.is-open {
  display: block;
}
```
And a little JS:
```
const button = document.querySelector('.button');
const dropdown = document.querySelector('.dropdown');

button.addEventListener('click', () => {
  dropdown.classList.toggle('is-open');
});
```
with your HTML as such:
```
<div class="control">
  <button class="button" type="button">
    Toggle me yo
  </button>

  <div class="card dropdown">
    <div class=card-content">
      I iz a dropdown.
    </div>
  </div>
</div>
```
This is totally spitballing, but something close to this should work. It would be handy to have that `dropdown` class pre-built into things, though.

**Comment by TroyAlford** [comment]
I think the intent of Bulma is to avoid the JS piece entirely. If you did
:hover rather than a js based onclick, though, it would be all CSS.

**Comment by SEAPUNK** [comment]
The problem with `:hover` is that it isn't all that good UX: It's better to manually specify when an element should show the dropdown, and if not, to have a debounce delay.

**Comment by tquetano-r7** [comment]
Oh agreed about the no-js thing ... that would need to be something managed by the app, not by Bulma. If you REALLY wanted to make it pure CSS it could be done, where u make the button basically a checkbox styled like a regular button and then do something like `.button:active + .dropdown` for the open state. But that is REAL hacky.

I still think, though, that having the CSS pieces (dropdown styles for both standard and open) is within the scope, with the caveat that the scope of how to dynamically apply those styles (aka JS) is outside the scope.

**Comment by lucasduarte** [comment]
You can try something with :not(:target) and :target than use z-index to show or hide content

**Comment by SimonJ** [comment]
needing this too :D

**Comment by marick** [comment]
I'd like this, too. I'd also like a combobox or datalist-look-alike that works on Safari. Willing to pay money for someone to implement this/these and create a pull request. marick@exampler.com

**Comment by RicardoEmpre** [comment]
As with the modal, it would be great if the framework had the css classes to make a dropdown, leaving the toggling of that classes to the user using the js that he wants.

**Comment by nerijunior** [comment]
I'm doing a library with pure javascript for bulma addons, look at: 
[BulmaJs](https://github.com/nerijunior/bulmajs)
(https://github.com/nerijunior/bulmajs)

**Comment by hassanazimi** [comment]
Use nav `is-active` hamburger and  Vue.js like this 

in your app.js:

```javascript
new Vue({
    el : '#app',
    data : {
        nav : false,
    },
});
```
then set a button in your view
```html
<span class="nav-toggle" @click="nav = ! nav"><span>
<div :class="[ nav ? 'nav-right nav-menu is-active' : 'nav-right nav-menu' ]">
    <!--content-->
</div>
```

**Comment by nordborn** [comment]
Here is the implementation without Javascript

```
<style>
  /* wrapper */
  .is-dropable input[type="checkbox"] {
    display: none;
  }

  .is-dropable input[type="checkbox"]:checked ~ .dropdown {
    display: block;
  }

  /* dropdown basic */
  .dropdown {
    display: none;
    position: absolute;
    z-index: 9999;
  }

  .dropdown.is-open {
    display: block;
  }

  /* dropdown optional styling */
  .dropdown li:hover {
    background-color: #eee;
    cursor: pointer;
  }

</style>
```

layout

```
<div class="is-dropable">
  <input type="checkbox" id="ch1">   <!-- note: id -->
  <button class="button" type="button">
    <label for="ch1">Click me</label>  <!-- note: for -->
  </button>

  <div class="box dropdown">
    <ul>
      <li><a>Action 1</a></li>
      <li><a>Action 2</a></li>
    </ul>
  </div>
</div>
```

The main point is to use hidden `input type="checkbox"` to toggle dropdown

**Comment by xlcrr** [comment]
nice work @nordborn 
How can I close the dropdown with a click event outside elsewhere?

**Comment by nordborn** [comment]
Hello @xlcrr 
You should use JS event listener for this. 
And here is the dirty hack for you ;)

```
<script>
  function closeDropdownsIfOuterClick(ev) {
    'use strict';

    // classes of current and all parent elements
    var classes = function (el) {
      var c = '';
      while (el) {
          c += ' '+ el.className;
          el = el.parentNode;
      }
      return c;
    };

    var t =  ev.target || ev.srcElement;

    // click on any dropdown list? return
    // note: leading space is necessary
    if (classes(t).indexOf(' dropdown') !== -1) {
      return true;
    }

    // close all dropdowns except of current button
    document.querySelectorAll('.has-dropdown input[type="checkbox"]').forEach(function (chb) {
      // click on current button? don't close (handle label and checkbox bubbling)
      if (chb.id === t.id || chb.id === t.getAttribute('for'))  {
        return true;
      }
      chb.checked = false;
    });

    return true;
  }

  document.querySelector('body').addEventListener('click', closeDropdownsIfOuterClick)
</script>
```


BTW, I've changed example above to fix FF behavior (tag `button` was fully replaced with `<label class="button">`).

**Comment by xlcrr** [comment]
@nordborn copied and pasted that into a script in my nav template, works perfectly. Cheers!!

**Comment by sausin** [comment]
@tquetano-r7 thanks for the css! One issue that comes up: when these 'dropdowns' are supposed to appear in the mobile hamburger, they come on top of menu items that are below in the list. 

Is there something that can be done so that the 'lower' menu items shift down when these dropdowns appear?

**Comment by ShaggyDude** [comment]
You can use a hidden checkbox to control a dropdown. I didn't read the whole thread but I am starting to code that way so javascript can focus on loading and showing json data. I would be happy to build a non js dropdown if there is any need

**Comment by keevitaja** [comment]
here's my take on it!

https://gist.github.com/keevitaja/088fadbf0f12f9c2f4b98b09bfa71007

**Comment by mattkoch614** [comment]
What about something like this?

http://jsbin.com/telowuz/edit?html,output

**Comment by ShaggyDude** [comment]
:hover is not going to work well on mobile.

**Comment by evertramos** [comment]
@jgthms @taylorotwell I think we can close that now as of version 0.5.0:

[http://bulma.io/documentation/components/navbar/](http://bulma.io/documentation/components/navbar/)

Thanks!

**Comment by hassanazimi** [comment]
Could you please update new version 0.5.0 in npm as well.

**Comment by KonradDeskiewicz** [comment]
So there is dropdown for nav section, but what about buttons with addons outside nav? 
For example: In admin panels it's common practice to put "cog" button with "caret-down" addon that display actions menu below. 
Is there a way to achieve such thing in Bulma at this stage?

**Comment by helmerdavila** [comment]
This need to be closed?

**Comment by jgthms** [comment]
Shipped!

**Comment by giapdien1804** [comment]
I usually do this, when I click outside or into the item, the class is-active.
`let last_drop_open = undefined;
        document.addEventListener('click', function (el) {
            let target = el.target;
            if (target.closest('.dropdown-trigger')) {
                last_drop_open = target.closest('.dropdown');
                last_drop_open.classList.toggle('is-active');
            } else {
                if (last_drop_open)
                    last_drop_open.classList.remove('is-active');
            }
        })`
