### ISSUE TITLE
fixed sidebar using columns -> problem with width

### ISSUE THREAD

**Issue by 3tlam** [jgthms/bulma#1921]
I have a two column layout and would like to fix the sidebar (left column, `is-3`) to be fixed once scrolled to the element. But then the width is all wrong and I don't really know how to let it have the same width as a non `position: fixed` style

Any tips or help?
Thank you!

**Comment by jgthms** [comment]
The width is defined by the context of the `columns` parent. As soon as you use `position: fixed`, you're taking the column out of its context.

Solution is to either define a fixed width to your column, or capture that width in JS and apply it.
