### ISSUE TITLE
CSS Grid issue with cards

### ISSUE THREAD

**Issue by karanrajpal14** [jgthms/bulma#1922]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Google Chrome v66
I am sure this issue is **not a duplicate**

### Description

I'm trying to use CSS grid along with some cards but the height of the cards are being extended as much as the largest card. I'm aware that Bulma has it's own (amazing) columns system but I'd still prefer to use CSS grid as I am trying to learn to use it. 

If I've made some mistake in implementing it, then please do let me know.

### Steps to Reproduce

Have a look at my [codepen](https://codepen.io/karanrajpal14/pen/eKzbaw/)

### Expected behavior

The bottom edge of the card shouldn't extend as far the the bottom edge of the largest card

### Actual behavior

All cards should be as tall as the content

Thank you!

**Comment by patrickabkarian** [comment]
.card {
height:max-content;
}

https://codepen.io/anon/pen/qKNvjy

**Comment by karanrajpal14** [comment]
@patrickabkarian wow, guess I have a lot to learn. Thank you! :)
Out of curiosity, is there any particular reason why this isn't the default behavior for a card?

**Comment by jgthms** [comment]
Bulma doesn't add unnecessary properties until it's required for a component to work out of the box.

In this case, it's only needed in some particular context, so writing your own CSS is the way to go.

**Comment by patrickabkarian** [comment]
https://github.com/jgthms/bulma/issues/1723

I mean it causes issues within Bulma's own components, that's basically a bugged component imo.

**Comment by jgthms** [comment]
Yeah it was specific too. Having different column heights is the natural behaviour of a page's layout.

Forcing `height:max-content;` by default is styling the combination for a particular use case. If it was implemented as the default height for _all_ cards, it could break other setups we don't know about.

It's not a bug since it's the intended (and natural) behaviour.

**Comment by karanrajpal14** [comment]
That makes sense. Thank you for the explanation @jgthms 
Appreciate it :D
