### ISSUE TITLE
Step Wizard?

### ISSUE THREAD

**Issue by chobo2** [jgthms/bulma#1924]
Hi

I see there are 2 step wizard in the extensions area but I am having problems with both, I also don't know which one to choice as I am not sure if they are actually supported.

I try to do in my reactjs/webpack project

import  "../../node_modules/bulma/bulma.sass";
import "../../node_modules/bulma-steps/dist/bulma-steps.sass";

I get:  Undefined variable: "$grey-light".

I don't know why it would not be defined.

**Comment by jgthms** [comment]
You should ask in the corresponding repo: either https://github.com/wikiki/bulma-extensions or https://github.com/aramvisser/bulma-steps
