### ISSUE TITLE
 This is about the Bulma **Docs** > Why can't you search the docs? 

### ISSUE THREAD

**Issue by ANorseDude** [jgthms/bulma#1929]
This is about the Docs, specific https://bulma.io/documentation/

Why isn't there a search function for the documentations? Or is it me who can't see the search-tab/field?

**Comment by jgthms** [comment]
Duplicate 😉

**Comment by ANorseDude** [comment]
.. what? :-)

**Comment by InstanceOfMichael** [comment]
https://github.com/jgthms/bulma/issues/1325
