### ISSUE TITLE
Column responsiveness not working properly?

### ISSUE THREAD

**Issue by Viducius** [jgthms/bulma#1930]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Google Chrome, but tested across Microsoft Edge and Mozilla Firefox
I am sure this issue is **not a duplicate**

### Description

Currently what is happening, when using columns with 'is-desktop', 2 columns show side by side, but when checking for responsiveness I noticed the 2nd column will snap to a new line (like supposed to) but the width will not snap to 100% until you resize smaller.

Codepen for testing purposes:
https://codepen.io/anon/pen/rKjYrM

### Steps to Reproduce
```
<section class="hero is-dark">
    <div class="hero-body has-text-centered">
        <div class="columns is-desktop">
            <div class="column is-three-quarters" style="background-color: green !important;">
                <br/><br/><br/><br/><br/>
            </div>
            <div class="column" style="background-color: red !important;">
                <br/><br/><br/><br/><br/>
            </div>
        </div>
    </div>
</section>
```

Use the above mentioned code, and resize your browser to check responsiveness. (See gif for an example)

[Click here to open GIF explanation](https://i.imgur.com/4ooUa1l.gif)

### Expected behavior

I expect the second column to snap to a new line, and both columns will become a 100% width

### Actual behavior

While sliding you will notice the second column will snap to a new line but the width of the columns don't update untill you make the screen a bit smaller, when the width will snap to 100%.

**Comment by jgthms** [comment]
Because the “is-three-quarters” is effective from tablet onwards, which is a smaller viewport than desktop.

Try using “is-three-quarters-desktop”.

**Comment by Viducius** [comment]
Yup, that did it for me. Sorry my bad!

**Comment by jgthms** [comment]
No problem 😉

**Comment by galigopi** [comment]
mobile responsive not working properly, that is not showing insept level.
