### ISSUE TITLE
Question: Is it possible to add is-outlined to tiles?

### ISSUE THREAD

**Issue by agcty** [jgthms/bulma#1931]
This is about **Bulma**.

### Question

This is about the Bulma **CSS framework**

I'm using Bulma 0.7.1

Is there any way to add is-outlined to tiles? For example I'd like to add is-primary and is-outlined to a tile to make it outlined.

**Comment by jgthms** [comment]
Tiles are used for layout purposes, so there’s no particularly “styled”.

You can however add your own CSS on top.
