### ISSUE TITLE
text control for forms

### ISSUE THREAD

**Issue by roti** [jgthms/bulma#1932]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **0.7.1**

### Description

In forms you sometimes need to display information which is not an input (e.g. values computed from other inputs based on a formula/rule). I could use read only input fields for this, but it would be nice to also have a "text" form component which just displays something, and is not a label (i.e. is not bold). Current components like "content" or plain HTML tags have the problem that the text is not aligned. Here an example:

```
<form>
    <div class="columns">
        <div class="column is-narrow">
            <div class="field">
                <label class="label">Unit price</label>
                <div class="control"><input type="text" class="input" value="123"></div>
            </div>
            <div class="field">
                <label class="label">Units</label>
                <div class="control"><input type="text" class="input" value="3"></div>
            </div>
            <div class="field">
                <label class="label">Total price</label>
                <div class="control">369 $</div>
            </div>
        </div>
    </div>
</form>
```

**Comment by jgthms** [comment]
Have you tried the `help` element?

**Comment by roti** [comment]
> 
> 
> Have you tried the `help` element?

I'll try and let you know. Thanks.
