### ISSUE TITLE
$body-line-height  breaks responsiveness of some components

### ISSUE THREAD

**Issue by vystepanenko** [jgthms/bulma#1933]
This is about **Bulma**

### Overview of the problem

If variable **$body-line-height** is set, some components like notification, tiles begins to be unresponsive

### Description

By default such components like notification is responsive
For example:
![image](https://user-images.githubusercontent.com/22811452/41220171-35879538-6d69-11e8-9d54-43d126e4ce8f.png)
and 
![image](https://user-images.githubusercontent.com/22811452/41220211-4d5a4246-6d69-11e8-9b8a-2e7b58ca6d5e.png)
But if you set up  **$body-line-height** to any value, this component stop to be responsive and all text inside this components are draw in one line
![image](https://user-images.githubusercontent.com/22811452/41220288-98829048-6d69-11e8-94c3-4a0df04e452f.png)

### Steps to Reproduce

1. Set up  **$body-line-height** to any value
2. Create, for example, notification components with lot of text inside of it
3. Try to change size of the window

### Expected behavior

Components must be responsive with any value of **$body-line-height** 

### Actual behavior

Components aren't  responsive with any value of **$body-line-height**

**Comment by jgthms** [comment]
What's your Sass code?

**Comment by vystepanenko** [comment]
```
$body-line-height: 1px;
//bulma
@import './node_modules/bulma/bulma.sass';
```

**Comment by jgthms** [comment]
Well yeah, you're setting a line-height of `1px` for all your website…

The component is responsive though. The line height doesn't affect responsiveness.

**Comment by vystepanenko** [comment]
Yes it is. But I think that the correct behavior must be the transfer of lines too

**Comment by jgthms** [comment]
> the transfer of lines

Please explain.

**Comment by vystepanenko** [comment]
When you set up $body-line-height, the height must also be responsive 
And component should be like this
![image](https://user-images.githubusercontent.com/22811452/41220171-35879538-6d69-11e8-9d54-43d126e4ce8f.png)
and not like this
![image](https://user-images.githubusercontent.com/22811452/41220288-98829048-6d69-11e8-94c3-4a0df04e452f.png)

ps. english isn't my native language. I apologize for the fact that I not very clear

**Comment by jgthms** [comment]
Ok so responsiveness doesn't mean that. It means different styling is applied based on the viewport width. And what is responsive is usually the **width**, not the height.

The height is defined by the line-height and the number of lines.

But in any case, I mean, you're setting a new body line height, and you're surprised that the line-height is changed?? If you don't want it, don't set it…

**Comment by vystepanenko** [comment]
Ok.
Is there any options how can I decrease the interval between the lines?

**Comment by vystepanenko** [comment]
I find where I was incorrect.
I need to set up $body-line-height without any dimension such as  px, %, em or something else.

This works as expected:
`$body-line-height: 1;`

and this is not 
`$body-line-height: 1`**px;**
