### ISSUE TITLE
Changing input field icon with fa5

### ISSUE THREAD

**Issue by xamado** [jgthms/bulma#1935]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.1]

### Description

I'm trying to change the icon on a input field dinamically, depending on certain conditions, for which I used a template like the following:

`<input class="input" type="text" v-on:keydown.prevent="onKeyPress">`
`<span class="icon is-small is-left">`
`<i v-bind:class="['far', iconName]"></i>`
`</span>`

Problem is that I can only change the icon by setting iconName if I do it inside the mounted() callback. But if I try to change it anywhere else, like in my onKeyPress handler, nothing happens. I noticed that the `<i>` tag gets replaced by svg code once the component is rendered, I'm guessing this has to do with fa5 using svg icons. 

Am I missing something?

### Expected behavior

I would expect changing the class to change the icon.

### Actual behavior

The update to the iconName variable has no effect at all on the rendered markup.

**Comment by jgthms** [comment]
This seems related to Fotn Awesome only, not Bulma. Try asking there: https://github.com/FortAwesome/Font-Awesome
