### ISSUE TITLE
CSS Problem with display-inline + width:auto

### ISSUE THREAD

**Issue by herolda** [jgthms/bulma#1939]
This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help?

### Overview of the problem

This is about the Bulma **CSS framework** 

### Description

Visual Studio Code Editor warns in line 3103,3 in bulma.css: "Property is ignored due to the display. With 'display:inline', the width, height, margin-top, margin-bottom, and float properties have no effect."

**Comment by jgthms** [comment]
Can you copy the CSS rule that triggers this?

**Comment by herolda** [comment]
Yes, here:
  .input.is-inline,
  .textarea.is-inline {
    display: inline;
    width: auto; }

**Comment by jgthms** [comment]
Yeah it’s a modifier. The input already has a width applied by default but you can’t remove it for the modified.
