### ISSUE TITLE
Font Awesome icon has no space before text in with navbar items.

### ISSUE THREAD

**Issue by garretwilson** [jgthms/bulma#1943]
This is about the Bulma **CSS framework**.
I'm using Bulma **version** 0.7.1.
My **browser** is: Chrome Version 67.0.3396.87 (Official Build) (64-bit) (Windows 10 Professional)

I have a simple little navbar, like this:

```html5
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-start">
    <a class="navbar-item" href="#about"><i class="far fa-question-circle"></i> About</a>
    <a class="navbar-item" href="#jobs"><i class="fas fa-briefcase"></i> Jobs</a>
  </div>
<nav>
```

That looks decent, but the Font Awesome icon is squished up against the text of each menu item. (The appearance of the "Jobs" item is particularly problematic.)

I tried to split the link out below its `navbar-item`:

```html5
<div class="navbar-item">
  <a href="#jobs"><i class="fas fa-briefcase"></i> Jobs</a>
</div>
```
That gives me the correct spacing, but ruins the effect of the navbar item. (Instead of a block flyover, I get a link with its link color.

This is my first Bulma project, and my first impression is that it seems very finicky about the order and combination of things. (A button requires a `<span>` wrapper both for the icon and for the text!!!) I can live with that until I decide whether to stick with Bulma or go to something less verbose, but there wasn't anything obvious I could do here to fix the problem of the missing space between the nav item icon and text. I even tried the `<span>` wrappers that Bulma buttons use, to no avail.

**Comment by imkrunal** [comment]
You need to add `<span>` in your code for proper spacing. Your Code should be like this.

Don't forgot to add class icon for the icon.

`<a class="navbar-item" href="#about"><span class="icon"><i class="far fa-question-circle"></i></span><span> About</span></a>`

**Comment by garretwilson** [comment]
I'm 90% sure I already tried that, but I'll try it again.

(Sorry to say it, but it looks ugly as heck, even if it works. I would prefer to use semantic HTML, and not put multiple wrappers around everything. The whole point of CSS was that we could relegate the style to a stylesheet.)

**Comment by thecristen** [comment]
I noticed this too.

```html
<a class="navbar-item" href="...">
    <span class="icon">
        <i class="fas fa-fw fa-chart-pie"></i>
    </span>
    Metrics
</a>
```
produces:
![image](https://user-images.githubusercontent.com/2136286/42694295-e74c12b0-867f-11e8-8ae2-f4c1553897e4.png)
in Chrome on MacOS.

**Comment by jgthms** [comment]
You can try adding another span so that the icon and the text are treated as text and not as flexbox items.

```html
<a class="navbar-item" href="#about">
  <span>
    <span class="icon"><i class="far fa-question-circle"></i></span>
    About
  </span>
</a>
```

**Comment by garretwilson** [comment]
I'm afraid this is a blocker for me. `<i class="fas fa-briefcase"></i> Jobs` is the approach recommended by Font Awesome. It works on Bootstrap.

I don't want a framework that makes add a lot of artificial physical structure just to get the styling I want. This is a deal-breaker.

**Comment by jgthms** [comment]
I’m sorry to hear that but it’s the nature of CSS. “navbar-item” needs to be a flexbox container for various reasons. One drawback might be an additional span in this particular case.

**Comment by garretwilson** [comment]
> I’m sorry to hear that but it’s the nature of CSS. “navbar-item” needs to be a flexbox container for various reasons. One drawback might be an additional span in this particular case.

If this is just a flexbox issue because of some tricks you are playing with navbars, then why is it broken in simple buttons as well?

For example, this does not work; it exhibits the same problem:

```html
<a class="button"><i class="fas fa-briefcase"></i> Jobs</a>
```

Instead Bulma makes me do this just so my button can look halfway decent:

```html
<a class="button"><span class="icon"><i class="fas fa-briefcase"></i></span> <span>Jobs</span></a>
```

The problem arises because you are using `display: inline-flex` on a button. _On a button!!_ You even use `inline-flex` on `<button>`! Flexbox is wonderful, but… for button content? Really? Methinks this is the case of having a hammer and suddenly everything looks like a nail. Here flexbox causes more problems than it solves.

**Comment by tgrushka** [comment]
Added this to my CSS/SCSS after Bulma import: (Not pretty, but it works for the navbar at least)
```css
.icon {
    margin-right: 0.2rem !important;
}
```
