### ISSUE TITLE
Spacing classes?

### ISSUE THREAD

**Issue by kylescousin** [jgthms/bulma#1945]
Bootstrap has ml-1, ml2, pl-1, pl-2, ... etc for setting margins and padding.

Is there anything similar in Bulma?

**Comment by jgthms** [comment]
No but there's a similar issue talking about it.

**Comment by williamabbott** [comment]
Checkout my gist based on Bootstrap's method:
https://gist.github.com/williamabbott/47767c82a7b62f4fe0d931b94a9b489b
