### ISSUE TITLE
Question: How to center card inside column?

### ISSUE THREAD

**Issue by sthomp** [jgthms/bulma#195]
Im trying to have a card centered inside a grid column. The default behavior is that the card sticks to the left side of the column. For example, if I reduce my browser width on the Bulma documentation the card is stuck to the left:

![screen shot 2016-04-28 at 5 12 11 pm](https://cloud.githubusercontent.com/assets/1254471/14901626/66415518-0d64-11e6-80a3-ba3383d7ec6e.png)

Is it possible to have the card centered?

**Comment by jgthms** [comment]
As the card has a defined width, just use `margin-left: auto` and `margin-right: auto`.

**Comment by gkatsanos** [comment]
Why should the card have a defined width? If that's the case, why is it called a "reusable component" ?
