### ISSUE TITLE
.navbar-brand margin is -1rem, but .navbar-item has padding 0.75rem

### ISSUE THREAD

**Issue by FragsterAt** [jgthms/bulma#1952]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.1**
I am sure this issue is **not a duplicate**

### Description

poor navbar alignment in .container

i fix this like this in customisation file:
```
+desktop
  .navbar > .container,
  .container > .navbar
    .navbar-brand
      margin-left: -0.75rem !important;
    .navbar-menu
      margin-right: -0.75rem
```
but may be this must be fixed thru adding variable for this case

### Steps to Reproduce

https://codepen.io/anon/pen/gKvdLb

### Expected behavior

1st navbar item in .container must have same padding & negative margin values

### Actual behavior

1st navbar item moved left from .container by 0.25rem

**Comment by emersonlaurentino** [comment]
This issue has been resolved here: https://github.com/jgthms/bulma/commit/76c068e3290e153bbd0385ecd4dfaae41f5b4266

but, I dont think the final css build was done.
