### ISSUE TITLE
Inconsisten margin bottom in `columns`

### ISSUE THREAD

**Issue by mr-karan** [jgthms/bulma#1957]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.1]
My **browser** is: Google Chrome 67.0.3396.87, Mozilla Firefox 61.0b13
I am sure this issue is **not a duplicate**

### Description

Inconsisten margin bottom in `columns`. Any reason specifically to [move the last](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L434) `columns` element a bit upwards? And all but last element are [offsett downwards](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L436). This breaks horizontal alignment. 

### Steps to Reproduce

https://codepen.io/anon/pen/vrRWJR

Screenshot of what is happening: 
<img width="887" alt="screen shot 2018-06-21 at 10 07 46 am" src="https://user-images.githubusercontent.com/5689132/41698269-fc3d6b3e-753a-11e8-9ac7-9d265123af65.png">

### Expected behavior

The `columns` should have been perfectly aligned horizontally

### Actual behavior

There's an extra margin-bottom in the last `columns` element which seems off.

**Comment by VizuaaLOG** [comment]
Are you able to provide a codepen of the exact code you used in your screenshot? Opening the codepen you provided in Google Chrome also and I'm not seeing any issues with the alignment. Unless I'm missing something.

<img width="1311" alt="screen shot 2018-07-26 at 00 29 59" src="https://user-images.githubusercontent.com/4404472/43232890-115aad10-906b-11e8-83c8-532bab5d0289.png">
