### ISSUE TITLE
Docs showing 0 type sizes available.

### ISSUE THREAD

**Issue by alex-kovac** [jgthms/bulma#1958]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

On [modifiers](https://bulma.io/documentation/modifiers/typography-helpers/ ) page, the first section "sizes" says "There are 0 sizes to choose from:"

![image](https://user-images.githubusercontent.com/174563/41708841-fcb5e774-7541-11e8-94be-994c0eb6740b.png)

### Steps to Reproduce

1. Visit Docs [modifiers](https://bulma.io/documentation/modifiers/typography-helpers/ ) page.
2. Read the first section on Sizes.

### Expected behavior
A table lists the type sizes available.

### Actual behavior
'for' loop is not generating the text and table properly. Results in 0 sizes and an empty table.

**Comment by jgthms** [comment]
Thanks. Fixed!
