### ISSUE TITLE
Make icon in input field clickable

### ISSUE THREAD

**Issue by nicolasvahidzein** [jgthms/bulma#1962]
Hello Jeremy, this should be a quick ticket to close, i cannot find info about how to go about making the second icon in 

<p class="control has-icons-left has-icons-right">

clickable.

This is a password field i am making with the lock icon on the left and the ? icon on the right but i want to make it clickable.

Thank you for your assistance.

**Comment by nicolasvahidzein** [comment]
Hello Jeremy, j'espere que tu vas bien. Ca fait un baille. Super travail sur la nouvelle version de Bulma.

Can i hack the button until you add the feature?

**Comment by scottwernervt** [comment]
Duplicate of #1965. Icon's attached to inputs can be made "clickable" with:

```sass
.icon {
  &.is-action {
    cursor: pointer;
    pointer-events: initial !important;
  }
}
```
