### ISSUE TITLE
Icon in input field not clickable

### ISSUE THREAD

**Issue by umangm99** [jgthms/bulma#1965]
Code for problem statement

`<div className="field">
            <div className="control has-icons-right">
              <input
                className="input"
                type="password"
                placeholder="Confirm Password"
                id="confirm_password"
                autoComplete="on"
                value={this.state.confirm_password}
                onChange={this.handleChange}
              />
              <span className="control icon is-small is-right">
                <FontAwesomeIcon
                  icon={["fas", "eye"]}
                  onClick={this.unmaskPassword}
                />
              </span>
            </div>
          </div>`

**Issue: Not able to click icon.**

**Comment by jgthms** [comment]
This doesn’t seem to be Bulma related.

**Comment by umangm99** [comment]
Hi Jeremy,

`<div class="field">
  <p class="control has-icons-left">
    <input class="input" type="password" placeholder="Password">
    <span class="icon is-small is-left">
      <i class="fas fa-lock"></i>
    </span>
  </p>
</div>`

Is part of basic documentation and even in this icon inside input text box is not clickable. 

**My use case is to to make password show and hide on click of icon.**

**Comment by Mortiferr** [comment]
I think this is an issue for something like StackOverflow, as this isn't related to Bulma directly. Bulma is a framework, not a complete UI kit. So you'd have to implement something of that nature yourself via jQuery or something else.

**Comment by jgthms** [comment]
The `.icon` class has `pointer-events: none`. You can make it clickable again by adding `pointer-events: initial`.

**Comment by SaymV** [comment]
```css
.control .icon {
    pointer-events: initial;
}
```

For the copy pasters finding this in 2020.

**Comment by koiki13** [comment]
Give the icon a class name say "fav-icon", then add this to css 
    `.fav-icon{ 
pointer-events: all;
 cursor:pointer
}`.

pointer-events should be set to all not initial

**Comment by stefanak-michal** [comment]
just add `is-clickable` class
