### ISSUE TITLE
.tags does not wrap on Chrome Version 67.0.3396.87 (Official Build) (64-bit) Mac OS High Sierra

### ISSUE THREAD

**Issue by jschatz1** [jgthms/bulma#1967]
Is it a bug/feature/question or do you need help?
If it's a bug, is it a browser bug? No

### Overview of the problem

'm using Bulma **version** [0.7.1]
My **browser** is: Chrome, Firefox
 am sure this issue is **not a duplicate**? Yes, pretty sure. 😄 

Maybe I am not using Bulma properly. 

### Description

Tags don't wrap right on Chrome.  Looks good on Firefox.

**Chrome:** 
<img width="1163" alt="screen shot 2018-06-25 at 11 08 43 am" src="https://user-images.githubusercontent.com/322665/41858743-9535034e-7868-11e8-9e7c-a3c68534fa6c.png">

**Firefox:** 
<img width="988" alt="screen shot 2018-06-25 at 11 12 45 am" src="https://user-images.githubusercontent.com/322665/41858836-cdc98fcc-7868-11e8-8ba7-7e38fd0da915.png">

### Steps to Reproduce
https://codepen.io/jakecodes-the-reactor/pen/rKrrEB (without external styles) 

### Expected behavior

`.tags` with `.tag` should wrap multi line

### Actual behavior

It doesn't wrap on Chrome but does work on Firefox.

**Comment by patrickabkarian** [comment]
cuz the .columns is too long .tags has nothing to do with this issue

**Comment by Shane-Bryan** [comment]
Not sure if this will help, but I was having the same issue today. I tracked it down to the flex-shrink CSS property in the control class. It's currently set to 0. If you modify it to its default value of 1 it allows the div with the control class to shrink.
