### ISSUE TITLE
can tab into `is-disabled` input text field and still type

### ISSUE THREAD

**Issue by rajasharan** [jgthms/bulma#197]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.24]
* [x] My **browser** is: Chrome V50... on Mac OS X
* [x] I am sure this issue is **not a duplicate**

### Description
When multiple input fields are place on a webpage I can use the `tab` key to jump into an input text field and start typing even it `is-disabled`

### Steps to Reproduce

1. Place two input text fields, one of them normal and the other `is-disabled`
2. Place cursor on first field and hit `tab` key

_Expected behavior:_ the cursor should not jump inside the disabled input text

_Actual behavior:_ cursor jumps into the disabled input text and it is possible to type

```html
<p class="control">
  <input class="input" type="text">
</p>

<p class="control">
  <input class="input is-disabled" type="text">
</p>
```

![screen shot 2016-04-30 at 12 34 46 pm](https://cloud.githubusercontent.com/assets/299522/14937311/a3fe5c52-0ed1-11e6-9184-1feda4072213.png)

**Comment by estevanmaito** [comment]
Hi @rajasharan.

As the docs say (http://bulma.io/documentation/modifiers/helpers/):

`is-disabled` 	Removes any **click** event.

In the _Forms_ section, you can see an example that uses `is-disabled` class alongside the `disabled` HTML attribute.

Example: http://bulma.io/documentation/elements/form/

This way you remove click, tab, etc...

**Comment by jgthms** [comment]
Use `<input disabled>` which is standard HTML.
