### ISSUE TITLE
To change the background color, I had to apply background color to html AND <section>

### ISSUE THREAD

**Issue by elieobeid7** [jgthms/bulma#1972]
I'm on chrome latest version, windows 10, 64 bit, using bulma 0.7.1 Here's my HTML.

https://pastebin.com/7pS0q76y

In order to change the background color, I had to do 

```
html,section {
background-color:rgba(154, 130, 139, 0.77);
}
```
And 
```
body,section {
this also works but I had to apply it to section too
}

```
If I do that, the color would be correct, can't take a screenshot since the screen capture is bad at capturing real colors.

But if I don't apply the color for both elements, if I apply colors for either `html` or `section` the color becomes lighter, it's like something is decreasing the opacity.

**Comment by jgthms** [comment]
You’re using rgba which is transparent. What are you trying to achieve exactly? I’m confused.

**Comment by elieobeid7** [comment]
if I do this

```
html,section {
background-color:rgba(154, 130, 139, 0.77);
}
```

Or this

```
body,section {
background-color:rgba(154, 130, 139, 0.77);
}
```

I see this, which is what I should see

![1](https://user-images.githubusercontent.com/660142/42130011-88c6048a-7cde-11e8-8128-1b3a2242af59.png)


**BUT**

If I do this

```
html {
background-color:rgba(154, 130, 139, 0.77);
}
```

or this

```
section {
background-color:rgba(154, 130, 139, 0.77);
}
```

or this

```
body {
background-color:rgba(154, 130, 139, 0.77);
}
```


I see  this

![2](https://user-images.githubusercontent.com/660142/42130024-ef36eacc-7cde-11e8-9dae-43b135e77a0a.png)


which is wrong, something in bulma is causing the color to be wrong, unless I apply it to section and html together or section and body.

**Comment by elieobeid7** [comment]
The issue is caused by this bug https://github.com/jgthms/bulma/issues/1973
