### ISSUE TITLE
Bulma's <HTML> has a background-color

### ISSUE THREAD

**Issue by elieobeid7** [jgthms/bulma#1973]
Bulma's has

```
html{ 
background-color:#fff;
}
```
Why :( why !! it's causing too many problems, see my background color issue

https://github.com/jgthms/bulma/issues/1972

and too many other issues that I just can't count! why would a css framework have any color whatsoever?

`#fff` is the default color of any blank page, so if no color is applied, there's no need for it, and if I want to change the color, it stands in my way! It's like you're telling me to do

```
html{
    background-color: transparent;
}

```

Before I can apply my color to the body.

And why is it applied to `<html>` in the first place and not `<body>`? It is a standard to apply colors to `<body>`. Again this color is unnecessary.

**Comment by jgthms** [comment]
You can change it with the `$body-background-color` Sass variable.

**Comment by elieobeid7** [comment]
I don't use sass, so it's not a bug?

**Comment by Velociapcior** [comment]
Same here. I just don't understand why would you use this on html tag. Now I have a problem, where I have to write
`html {
background-color: unset;
}`

but on the other hand there is no "unset" option in internet explorer. And closing issue before elieobeid7 had a chance to respond is very unprofffesional
