### ISSUE TITLE
Fixed banner above navbar

### ISSUE THREAD

**Issue by twheel** [jgthms/bulma#1980]
This is about **Bulma**.

I need help

I'm using Bulma 0.7.1

### Description

Is it possible to fix a banner above the (fixed) navbar?

Or, alternatively, is it possible to include a hero in the fixed navbar?

I'm looking to have both the site banner and the navbar stay at the top of the page with the banner above the navbar.

**Comment by jgthms** [comment]
Not really. The fixed navbar has a top: 0; positioning. You’d have to create your own fixed element, which is very easy, and include a non-fixed navbar inside.
