### ISSUE TITLE
Navbar burger icon does not use the appropriate color when color modifier is used in navbar

### ISSUE THREAD

**Issue by corneliusludmann** [jgthms/bulma#1981]
This is about **Bulma**. It's a bug in navbar.sass.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.7.1 and have tested the latest commit in master (1083f01).

My **browser** is: Google Chrome Version 67.0.3396.99

### Description

When using a color modifier for a navbar (e.g., is-dark) the burger icon does not use the appropriate color. This leads to a burger icon and close icon which are not visible when clicked.

### Steps to Reproduce

You can see the wrong behavior in the following minimal code sample (see also: https://jsfiddle.net/pm26zwer/6/). The navbar burger is blue and should be whitesmoke (inverse). When hover the burger button nearly disappears.

```
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  </head>

  <body>
    <nav class="navbar is-dark" role="navigation">
      <div class="container">
        <div class="navbar-brand">
          <a href="/" class="navbar-item">Company</a>

          <a id="navbar-burger-id" role="button" class="navbar-burger is-hoverable">
          <span></span>
          <span></span>
          <span></span>
        </a>
        </div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
        <h1 class="title">
          Hello World
        </h1>
        <p class="subtitle">
          My first website with <strong>Bulma</strong>!
        </p>
      </div>
    </section>
  </body>

</html>
```

### Expected behavior

The navbar burger icon color should be handled as the navbar link color. If you use is-dark for the navbar the navbar burger icon color should be whitesmoke. You can uncomment the CSS in https://jsfiddle.net/pm26zwer/6/ to see how it should look like.

### Actual behavior

The navbar burger color has not the appropriate color when using is-dark or other color modifiers for the navbar.

**Comment by corneliusludmann** [comment]
See pull request #1982 for a proposed solution.

**Comment by emanuelmutschlechner** [comment]
@corneliusludmann there's a simple and quick workaround. Using `<div>` instead of `<a>` prevents the application of the link color on the burger bars

![image](https://user-images.githubusercontent.com/27734375/46290656-bd7d5100-c58c-11e8-8e7e-e3447efd55c1.png)
