### ISSUE TITLE
Navbar Height Adjustment [question]

### ISSUE THREAD

**Issue by Mortiferr** [jgthms/bulma#1984]
This is about **Bulma**.

Is it a **question**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.1**

### Description

Is there a built in way to adjust the height of the navbar component? I know I could easily just do it with a bit of CSS, but if there's a built in way to do it, I'd prefer that.

**Comment by jgthms** [comment]
You can customise the `$navbar-height` value.
