### ISSUE TITLE
Bulma form control icons: issue with Material Design Icon Syntax

### ISSUE THREAD

**Issue by fanomena** [jgthms/bulma#1989]
This is about **Bulma | the Docs**.
It is a bug/feature/question

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Chrome 67.0.3396.87
I am sure this issue is **not a duplicate**

### Description

So I am using material design icons in form fields (e.g. input = text). This is documented here: https://bulma.io/documentation/form/general/
There is an `mdi` class documented here:
https://bulma.io/documentation/elements/icon/#material-design-icons

My problem is that neither with or without the MDI class, the icon is displayed correctly.

### Steps to Reproduce

With the `mdi` class:

```
<div class='columns'>
 <div class='column'>
  <div class='field'>
   <label class="label" for="event_start_date">Date of the event</label>
    <div class='control has-icons-right'>
     <input class="input" required="required" type="text" name="event[start_date]" id="event_start_date" />
     <span class='icon is-small is-right mdi mdi-18px'>
     <i class="material-icons">calendar_today</i>
   </span>
  </div>
 </div>
 </div>
 <div class='column'>tests</div>
</div>
```
Without the `mdi` class:

```
<div class='columns'>
 <div class='column'>
  <div class='field'>
   <label class="label" for="event_start_date">Date of the event</label>
    <div class='control has-icons-right'>
     <input class="input" required="required" type="text" name="event[start_date]" id="event_start_date" />
     <span class='icon is-small is-right'>
     <i class="material-icons">calendar_today</i>
   </span>
  </div>
 </div>
 </div>
 <div class='column'>tests</div>
</div>
```

### Expected behavior

Rendering of the icon within the input text field on the right side.

### Actual behavior

With or without `mdi` class:
Icon is rendered way off the right side, outside the input field.

<img width="737" alt="screen shot 2018-07-13 at 11 00 10" src="https://user-images.githubusercontent.com/13721391/42682866-04cb6fdc-868c-11e8-8da2-c7785d15bf64.png">

**Comment by jgthms** [comment]
I'm not sure what the `material-icons` class does, but you need to have  your `mdi` element as a child of `icon`:

```html
<div class="columns">
 <div class="column">
  <div class="field">
   <label class="label" for="event_start_date">Date of the event</label>
    <div class="control has-icons-right">
     <input class="input" required="required" type="text" name="event[start_date]" id="event_start_date">
     <span class="icon is-small is-right">
          <i class="mdi mdi-signal-4g"></i></span>
  </div>
 </div>
 </div>
 <div class="column">tests</div>
</div>
```

https://codepen.io/jgthms/pen/ajvBWo
