### ISSUE TITLE
uncomfortable dragging is present in mobile view

### ISSUE THREAD

**Issue by rodrigorellana** [jgthms/bulma#1996]
BUG

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.7.1]
My **browser** is: Chrome

### Description

in mobile inspector there are a dragging that doesnt look well

also present in mobile device using ngrok public url aimed to localhost

### Steps to Reproduce

pull this repo [https://github.com/rodrigorellana/bulmabug](https://github.com/rodrigorellana/bulmabug)

### Expected behavior

don't let dragging

### Actual behavior

you can see in this gif [https://imgur.com/a/MoJS8lj](https://imgur.com/a/MoJS8lj)

**Comment by jgthms** [comment]
You scan wrap the container in a `.section`.
