### ISSUE TITLE
[Discussion] How to keep Font Awesome updated?

### ISSUE THREAD

**Issue by Mortiferr** [jgthms/bulma#1998]
Does anyone know of any official CDN link where it links to the latest? This was available for FA 4.x, but since the bump to 5.x it seems to have been dropped, as they've moved to a more self-hosted (use.fontawesome.com) solution--probably to better support Pro.

We could just manually update it, but that leaves it open to be forgotten about, and just generally looks bad to be a version or more behind on a non-breaking update in my opinion.

**Comment by jgthms** [comment]
Bulma doesn't require the latest version of Font Awesome to work. All the icons used on the Bulma website already exist, so they'll never be a "broken" icon displayed on the website.

Bulma's `.icon` class works with any icon font, so it'll work with any version of Font Awesome.

> just generally looks bad

I don't agree. The only occurence of the Font Awesome version in the docs is on the start page. 

The only time it would look bad is if the starting snippet stopped working suddenly. But then again, that snippet has to be **tested** if it's edited. And if it's updated _automatically_, then it could break without our knowledge. So the solution is to keep editing it _manually_. And if it's edited manually, then you can **also** update Font Awesome. See what I mean? :wink:
