### ISSUE TITLE
gitter

### ISSUE THREAD

**Issue by aolko** [jgthms/bulma#2]
please make a gitter support chat

**Comment by eko24** [comment]
+1
or maybe use Slack

**Comment by aolko** [comment]
rocket.chat

**Comment by darol100** [comment]
:+1: , For Gitter.

Slack was not build for online communities IMO. Slack is very good for small personal/work relate communication.

**Comment by JustSteveKing** [comment]
I disagree with @darol100 - I think Sack is a much better solution for this style. It allows the channels to be split into key areas such as:

- Community Help
- General
- RoadMap
- Issues
- Random

**Comment by darol100** [comment]
Too personal, and admin needs to send you an invitation. This is why it fails to grow a community with it. Again Slack is awesome for personal projects/ work relate. Gitter is using the same techology and it can be login with Github, in addition it can link with your github. Then there is an activity block of what is going on in the git project.

**Comment by eko24** [comment]
@darol100 well, this may be handy :wink: 
https://levels.io/slack-typeform-auto-invite-sign-ups/

**Comment by metaperl** [comment]
I think we need a StackOverflow tag.

**Comment by aolko** [comment]
not really, stackoverflow's moderation is **very** strict

**Comment by JustSteveKing** [comment]
@darol100 too personal?? Failing to grow as a community? If it isn't personal it will always fail to grow as a community. Look at some of the bigger communities out there, all using slack, how they create a friendly atmosphere by being more personal. I am part of a few Slack communities, and not only is it great for community chat and help but it is also a very good place to just talk to other members of the community. If you want the unfriendly approach then don't use Slack. However if you want a more involved community that are friendly and active ... need I say more?

**Comment by eko24** [comment]
Regarding Slack invites:
 - http://rauchg.com/slackin/
 - https://stackstorm.com/2015/06/30/using-stackstorm-to-auto-invite-users-to-a-slack-organization/
 - https://www.stacktodo.com/tools/invite

**Comment by dmjio** [comment]
so gitter?

**Comment by vasifnawaz** [comment]
do we have a chat support already on or are we still working on it ?

**Comment by eko24** [comment]
@vasifnawaz if we do - I never heard about it

**Comment by Greenheart** [comment]
Gitter is perfect for OSS projects. If you want evidence, just look at [FreeCodeCamp](http://gitter.im/freecodecamp/freecodecamp). Their community is using multiple gitter-rooms but still have a big main-room

**Comment by juanmnl** [comment]
Bootstrap and ember are on slack, chat with people and find solutions to problems everyday.
:+1: for slack.

**Comment by kuashe** [comment]
@jgthms  Any update on this ? 
It only takes 2 clicks to  create a **free** chatroom for the repository :smile: 

[https://gitter.im/login#createroom]()

**Comment by jgthms** [comment]
Added: https://gitter.im/jgthms/bulma
