### ISSUE TITLE
Modal box not center

### ISSUE THREAD

**Issue by infacq** [jgthms/bulma#200]
![weird](https://cloud.githubusercontent.com/assets/1596891/15064635/014d6112-1389-11e6-8515-fe077c1f8323.gif)

Please check this weird behaviour of large modal. I'm not really good at flexbox. Perhaps others can help

**Comment by tquetano-r7** [comment]
What browser are you on for this? It centers in Chrome and Firefox.

**Comment by infacq** [comment]
Chrome. It only happen in Large modal box

**Comment by tquetano-r7** [comment]
The site you are showing in your GIF looks a bit old ... there is no "Scrollable Modal" on the current site ...

![image](https://cloud.githubusercontent.com/assets/13334725/15097856/b11fd38e-14f8-11e6-8e22-39829c016821.png)

And I'm using Chrome right now ...

![image](https://cloud.githubusercontent.com/assets/13334725/15097858/c197898c-14f8-11e6-8d43-57dad5ecbabd.png)

**Comment by jgthms** [comment]
Yeah I changed the modal. The new one should work better.

**Comment by jartaud** [comment]
Still not center

**Comment by jens1o** [comment]
I disagree. It's centered

**Comment by jartaud** [comment]
@jens1o even on small screen?

**Comment by jens1o** [comment]
@jartaud Using the Chrome Developer Tools, yep.

Until my resolution is 768 x 325, then it's just too small.

I'm using Version 52.0.2743.60 beta-m (64-bit)

**Comment by jartaud** [comment]
@jens1o Google Chrome 51.0.2704.106 (64-bit) Ubuntu Mate 14.04.4 LTS
![Nexus 6P Landscape](http://i.imgur.com/0robevI.png)
![Nexus 6P Portrait](http://i.imgur.com/QUZvTq2.png)
![325 x 768](http://i.imgur.com/AQpC1Kf.png)
![768 x 325](http://i.imgur.com/Sftl77t.png)

**Comment by jartaud** [comment]
modal-container class was the culprit.
