### ISSUE TITLE
Loader component

### ISSUE THREAD

**Issue by roti** [jgthms/bulma#2007]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.1**

### Description

This is a feature request.

Loaders are available in text fields and buttons. It would be nice to have it independent as well, i.e. a loader component which looks similar and can be used everywhere. In my particular case, I need a page loader, and while there are many available, none matches the look & fell of the loaders from buttons and input fields.

**Comment by jgthms** [comment]
You can try using the mixin to create your own class:

```sass
.loader
  +loader
```
