### ISSUE TITLE
Scrolling bar vertical

### ISSUE THREAD

**Issue by Amisoz** [jgthms/bulma#2010]
This is about **Bulma**.

Is it a bug/feature/question or do you need help?  A bug

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.7.1] 
My **browser** is: Tested w/ firefox & edge

I am sure this issue is **not a duplicate**

### Description

The vertical scrolling bar is showed with nothing on the page : 
![image](https://user-images.githubusercontent.com/23367423/43019974-e21fad6c-8c5e-11e8-8093-c0636ca607c9.png)
![image](https://user-images.githubusercontent.com/23367423/43019984-e8a6e5ba-8c5e-11e8-99ea-a975dc5ef705.png)

When i remove the line who importing the css, the scrolling bar is removed.

**Comment by jgthms** [comment]
Yes it’s to prevent horizontal page jumps when switching pages.
