### ISSUE TITLE
Exclude navbar-item from burger

### ISSUE THREAD

**Issue by CDNRocket** [jgthms/bulma#2011]
As the title suggests, there is a way to exclude a specific item from the burger and make it always visible?
For example, I have a search icon at the end of my nav bar and want that it will always visible and near the burger (when it appear).

...or I need to add this outside the .navbar-menu?

**Comment by jgthms** [comment]
Yes outside of the navbar-menu can work. You can use helper classes to keep it visible on mobile or hide it on desktop.
