### ISSUE TITLE
How to vertically stack elements inside a column?

### ISSUE THREAD

**Issue by vedantroy** [jgthms/bulma#2014]
This is about **Bulma**.

### Overview of the problem

This is a very simple question - but I can't figure it out from reading the docs.

I have the following layout:
```
    <div class="columns is-mobile">
        <div class="column">
            <textarea></textarea>
            <button></button>
        </div>
        <div class="column">
            <div></div>
        </div>
    </div>
```

I want the `textarea` and `button` to stack vertically instead of horizontally. I know I can use the `display: block`  attribute to achieve the correct behavior - but considering Bulma is based on flexbox, I would think there is a better way to vertically align elements using flexbox attributes.  I tried using `flex-direction` but it didn't work.

**Comment by jgthms** [comment]
You don’t need Flexbox for that. Just use the “field” class and the “control” class: https://bulma.io/documentation/form/general/
