### ISSUE TITLE
Title and subtitle - style and line spacing differs when using content

### ISSUE THREAD

**Issue by hmistry** [jgthms/bulma#2019]
This is about **Bulma** help.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Safari 11.1.2 macOS 10.13.6

### Description

First time using Bulma and liking it so far. Not sure if this is intended behavior but I noticed there are differences in `subtitle` if used with `content` or without. Also line spacing differs with element.

### Expected behavior

I expect `title` and `subtitle` to be the same regardless as I didn't see anything in the docs to suggest otherwise.

### Actual behavior

see https://jsfiddle.net/n47wkouc/11/

2 questions:
1. What should be the intended behavior for the above?
2. Should I be wrapping everything in `content` or not? It seems like `content` has additional spacing rules that's not in individual classes like `title` or `is-size-3`. Also `is-small`/`is-large` modifiers do not work without content.

**Comment by jgthms** [comment]
Yes the `content` is meant for WYSIWYG content where you can’t add other CSS classes.

The docs could be improved.

**Comment by hmistry** [comment]
And the `subtitle` behavior above a bug or intended?

What class can I use on text html tags to apply the margins, spacing, etc so I can get the same formatting as `content` without overriding html tags?

If it helps, the docs are good for many things but lacking on what is Bulma's conventions on dealing with styling textual content without the use of `.content`.

**Comment by jgthms** [comment]
Basically, you can use `content` for styling textual content but you can't really use other classes _within_ your `content` element.

**Comment by VizuaaLOG** [comment]
@hmistry as @jgthms mentioned the `content` element is only used for WYSIWYG editors, such as TinyMCE etc. These make it more difficult to include the `title` classes etc and can be fiddly to get your own styles. That's why common tags such as `h1 - h6`, `p`, `ul` etc. are styled via the elements themselves.

When inside a `content` container the subtitle concept doesn't apply. If you need to use the more 'custom' styles then you do not want to use a `content` container.

**Comment by hmistry** [comment]
@VizuaaLOG I understand what he said and that's fine even though it doesn't help me.

My issue is they provide `content` for WYSIWYG that has the following styling:
- sizing for h1-6, p, etc
- margins, padding, line spacing, etc
- size helpers for small, med, large

but for non-WYSIWYG stuff all we have is:
- sizing for h1-6, p.

I have to implement my own thing for size helpers, margins, padding, line spacing, etc to apply to h1-6, p, ul, etc. I would be basically copying `content` because that's good enough for me. It was all right there if only it was extended through properly then I wouldn't have to make the same classes and I would have been able to leverage the framework like it should be and use the variables to easily override things.

**Comment by VizuaaLOG** [comment]
Actually, you do have a point there. I thought there was a list class to add bullets to `ul` outside a content div. But I think when creating pages outside a WYSIWYG environment I wrap lists etc. in a `content` element.

There are paragraph size helpers though similar to a title/subtitle you use `is-text-1` - `is-text-7` [typography docs](https://bulma.io/documentation/modifiers/typography-helpers/)

**Comment by areohbe** [comment]
I came here to raise a similar, or maybe the same issue, but I'm having a little trouble following the thread.

Ideally, I'd be able to customize the base font size and corresponding scale for all content using the standard html tags so that it gets applied within or outside the `content` class.

Maybe there's a use case for having a different scale within the `.content` class but this seems like it would be best handled by specific overrides for the `.content` class?

**Comment by hmistry** [comment]
@areohbe I agree. Sorry the thread digressed. The more I use Bulma, the more I find it's lacking on typography formatting (except font weight and size) outside of `.content`. And you may not want to use `.content` because not all the helpers seem to work with it.

**Comment by bonham** [comment]
I have a similar view: I need a content container to have an easy solution for my content layout. But inside content containers other stuff is not working well, e.g. image aspect ratios. And outside content container I would expect that spacing between title and paragraph is already in place, but it is not: https://stackoverflow.com/questions/58846077/how-to-create-a-spacing-before-a-title-in-bulma-without-using-a-content-contain
