### ISSUE TITLE
Responsiveness don't work as expected

### ISSUE THREAD

**Issue by osixia** [jgthms/bulma#202]
### Checklist

* [ ] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.25]
* [ ] My **browser** is:
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [x] I am sure this issue is **not a duplicate**?

### Description
Based on the documentation : 
http://bulma.io/documentation/overview/responsiveness/ 

The reponsivness don't work as expected for example : 
in **sass/base/helpers.sass**
```
.is-hidden-tablet
	  +tablet-only
	    display: none !important
```
generate in css : 
```
@media screen and (min-width: 769px) and (max-width: 979px) {
  .is-hidden-tablet {
    display: none !important; } }
```
so is-hidden-tablet hide an element only on Tablet and not also on Desktop and Widescreen

same problem for is-hidden-desktop that hide an element only on Desktop

**Comment by TroyAlford** [comment]
I'm pretty sure that's precisely what the class is supposed to do. You are
specifying that you are hiding it on tablet.

**Comment by osixia** [comment]
Yes probably :)  but if you refer to the documentation this should hide an element on tablet and desktop and wildscreen. I don't know if the documentation need to be fixed or the source code.

But i think it would be great to have helpers to display elements only on mobile or tablet and so on...

**Comment by jgthms** [comment]
This has been fixed:

* http://bulma.io/documentation/overview/responsiveness/
* http://bulma.io/documentation/modifiers/responsive-helpers/
