### ISSUE TITLE
Table column border on some columns

### ISSUE THREAD

**Issue by hmistry** [jgthms/bulma#2020]
This is about **Bulma** help.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1]
My **browser** is: Safari 11.1.2, macOS 10.13.6

### Description

What do you recommend on how to implement the following - I have a table with 6 columns but I only want to have vertical borders between col 1 & 2, col 3 & 4, and col 5 & 6. 

Make my own class to modify Bulma or does the framework have a way? I only see 2 options, all borders or none.

**Comment by jgthms** [comment]
Yes you would have to do it yourself. It’s too specific to be included in the whole framework.

**Comment by hmistry** [comment]
Yes that would be too specific for a framework. However I was hoping there was some general classes like `has-cell-border-left` or `has-cell-border-right` (plus top and bottom) to use built into the framework for such customizations. This ensures the style will be consistent with the rest and can easily be changed through the variables. What do you think about this?

**Comment by jgthms** [comment]
I was thinking about that but I think it’s too specific. If the issue comes up again, we could add it.

**Comment by hmistry** [comment]
Not sure what you mean by too specific. I'm sure it's a little on the custom side as opposed to a blanket borderless vs full-border table styling but I think a framework should cover all the base options so one can leverage it's benefits while customizing it, otherwise the framework starts loosing it's usefulness quickly.
