### ISSUE TITLE
Help arranging columns

### ISSUE THREAD

**Issue by thepra** [jgthms/bulma#2028]
This is about **Bulma**.

Is it a bug/feature/question or do you need help? **Help**

### Overview of the problem

Arranging columns differently between desktop and mobile

I'm using Bulma **version** [0.7.1] 
My **browser** is: Firefox 62 Beta

### Description

From desktop layout, on a single row, 5 columns:
1 column(is-half) -> 1 column(auto) -> 1 column(auto) -> 1 column(auto) ->1 column(auto)
to mobile, on 3 rows, 1 column, like:
1 column(is-full) -> 1 column(is-full) -> 1 column(is-one-third) -> 1 column(is-one-third) -> 1 column(is-one-third)

Someone has idea of how to implement such layout? I've tried many different compositions but always failed(or on mobile only or on desktop only) and I run out of ideas :(

**Comment by emkajeej** [comment]
```html
<div class="columns is-mobile is-multiline">
  <div class="column is-half-desktop is-full-mobile">col</div>
  <div class="column is-full-mobile">col</div>
  <div class="column is-one-third-mobile">col</div>
  <div class="column is-one-third-mobile">col</div>
  <div class="column is-one-third-mobile">col</div>
</div>
```
https://codepen.io/anon/pen/vapXWd

You can do it with less classes, I just added them for readability (e.g. the first `is-full-mobile` is not needed, it's implied by the second column already being full-width).
