### ISSUE TITLE
Safari button text-align center is not working

### ISSUE THREAD

**Issue by fundon** [jgthms/bulma#203]
```css
.button {
  width: 200px;
}
```

And disable `display: inline-flex;`, the `text-align: center` is working.

**Comment by jgthms** [comment]
Ok I'll add `justify-content: center` as well.

**Comment by tquetano-r7** [comment]
Just a heads up, Firefox does not support `display: inline-flex` on button elements:

https://bugzilla.mozilla.org/show_bug.cgi?id=984869

As they are the only browser that this impacts, they have this as a open bug from a web compatibility perspective (not a spec interpretation perspective), but it is still open.

**Comment by fundon** [comment]
@jgthms  Is it fixed?

**Comment by gregcha** [comment]
I'm still having this issue as display: inline-flex; is in the control.sass file (=control) 
Just have to comment / erase to make it work

**Comment by jeffijoe** [comment]
Still having this issue in Safari.

**Comment by iam-peekay** [comment]
@jeffijoe me too. let me know if you figure it out :/

**Comment by jeffijoe** [comment]
@iam-peekay the solution is to use a `div` with `display: flex`.

**Comment by msambarino** [comment]
@jeffijoe do you have an example? im trying your suggestion but getting nowhere, thanks in advance!

**Comment by jeffijoe** [comment]
@msambarino I already forgot haha :P I think if you just use a div for the content of the button and then use display:flex and align-items: center and justify-content:center that does the trick.
