### ISSUE TITLE
[Docs] Usage of "is-narrow" on field is not documented

### ISSUE THREAD

**Issue by k-j-kleist** [jgthms/bulma#2038]
This is about **the Docs**.
### Overview of the problem

On https://bulma.io/documentation/form/general/ the code example for "Horizontal form" contains
 `<div class="field is-narrow">`.

Obviously this does work, but the only documentation for "is-narrow" is about columns: https://bulma.io/documentation/columns/sizes/#narrow-column

**Comment by k-j-kleist** [comment]
further activity

**Comment by mrdavidhanson** [comment]
More activity. I was also researching how to adjust the width of a form input control and stumbled upon the "is-narrow" feature in a code sample:

https://bulma.io/documentation/form/general/

<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">Department</label>
  </div>
  <div class="field-body">
    <div class="field is-narrow">
      <div class="control">
        <div class="select is-fullwidth">
          <select>
            <option>Business development</option>
            <option>Marketing</option>
            <option>Sales</option>
          </select>
        </div>
      </div>
    </div>
  </div>
</div>

When applied to my code, it appears to reduce the width of the input control (as expected) on desktop and has no impact on mobile. Seems to work great. Is this an official feature of Bulma? If so, perhaps the documentation can be updated -- not finding anything, but I could be missing something...
