### ISSUE TITLE
about the Docs, wrong command

### ISSUE THREAD

**Issue by amebalibre** [jgthms/bulma#2042]
### Overview of the problem

Error on a command from documentation.

This is about the Bulma **Docs**

### Description

Command of npm is build-css not css-build how [here](https://bulma.io/documentation/customize/with-node-sass/#5-add-node-scripts-to-build-your-css)

**Comment by jgthms** [comment]
Good catch. Let’s fix that.

**Comment by jgthms** [comment]
It's correct actually.
