### ISSUE TITLE
How does Bulma handle overflowing table body

### ISSUE THREAD

**Issue by lqmanh** [jgthms/bulma#2043]
This is about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version 0.7.1**

### Description

I have this question: *How does Bulma table with `.table` class handle overflowing body?*
I have a really long table that should be within a wrapper container. I tried to set `overflow: scroll` on the table element but it won't work.

**Comment by jgthms** [comment]
You can wrap your table in a `.table-contakner`.

**Comment by scheinercc** [comment]
Just in case someone else ends up here, there is a small spelling - it is `.table-container`.

Here is an example: https://github.com/jgthms/bulma/issues/1080#issuecomment-387038231

and here the code:
https://github.com/jgthms/bulma/blob/01a1321e12a0cae265a5fa918c7ec5e77f74a879/sass/elements/table.sass#L122
