### ISSUE TITLE
Bg color for dropdown

### ISSUE THREAD

**Issue by themousepotato** [jgthms/bulma#2044]
The dropdown lacks background color. It would be nice to see if it has a bg color.

**Comment by jgthms** [comment]
Which part of the dropdown? You can use [background helpers](https://bulma.io/documentation/modifiers/color-helpers/#background-color).

**Comment by emkajeej** [comment]
@jgthms On a related note, shouldn't .dropdown have support for colours and sizes the same way .select does?
The closed state of the two are identical visually, I would expect them to have the same visual options.
