### ISSUE TITLE
Is there / can there be a way to prevent responsive images from upscaling beyond their original size? 

### ISSUE THREAD

**Issue by mlncn** [jgthms/bulma#2045]
This is about the Docs (but maybe Bulma).  That is, i may just need help, or this might be a feature request.

### Overview of the problem

* I'm using Bulma **v0.6.2**
* My **browser** is Firefox 52.
* I am pretty sure this issue is not a duplicate.

### Description

Upscaling images so that they're larger than their original pixel size rarely looks good for the image itself and frequently can worsen the look of the layout (an [image taking up 1116 pixels of vertical space](https://screenshots.firefox.com/UIOD0pSOVRLqZFTX/family-home.drutopia.org) before the content starts was my specific problem, when it is and should have displayed as only a [200 pixel image like this](https://screenshots.firefox.com/Z13zUwRsnhuTrVks/family-home.drutopia.org)).

However, Bulma's default handling of responsive images seems to be to upscale them.

### Steps to Reproduce

* Visit https://bulma.io/documentation/elements/image/
* Open inspector.
* For the very first example, remove the class `is-128x128`

### Expected behavior

Responsive images don't increase in size past their original size unless we add a class specifically requesting that.

### Actual behavior

The image is enlarged to several times its actual size.

### Fix/mitigation

I'm replacing `.image img { width: 100% }` with:

```
  width: intrinsic;           /* Safari/WebKit uses a non-standard name */
  width: -moz-max-content;    /* Firefox/Gecko */
  width: -webkit-max-content; /* Chrome */
```
but it seems there ought to be another way of simply telling images not to upscale, a better, more Bulma way.

**Comment by mlncn** [comment]
OK so simply removing the `.image` class as well as `is-128x128` on the [documentation page](https://bulma.io/documentation/elements/image/) gives me the behavior i expect.  If that *is* the best approach, my whole issue can be fixed in a single line of documentation.  But is that the right approach?

**Comment by emkajeej** [comment]
Bulma expects the image to be either precisely sized or by ratio. If you don't know either, the responsive behaviour will be to scale to the entire width of the container.|
Either limit the container's width to something that fits your design, or if you want full flexibility without overscaling your images, change `width: 100%` to `max-width: 100%; width: auto` on the `.image img` css.

**Comment by jskrivanek** [comment]
Any update or solution on this? When using `srcset` in a `figure img,` this does not work for me.
