### ISSUE TITLE
Background color variables for table head and foot

### ISSUE THREAD

**Issue by DJWoodZ** [jgthms/bulma#2046]
This is a question/feature request about Bulma.

### Overview of the request

This is about the Bulma **CSS framework** 
I'm using Bulma **version** 0.7.1
I am sure this issue is **not a duplicate**

### Description

Would it be possible to add variables to set the background color of table head and foot independently from the table background (`$table-background-color`) please?

For example:

```
$table-head-background-color: $grey-dark;
$table-foot-background-color: $grey-dark;
```

I appreciate these can be set easily without the existence of these variables, but it would help if they existed.

Thanks!

**Comment by DJWoodZ** [comment]
For completeness it probably makes sense to also add a variable for table body too:

```
$table-body-background-color: $grey-dark;
```

**Comment by motionsuggests** [comment]
👍 I was about to open a request for this. I'm willing to take a shot at it.
