### ISSUE TITLE
[Question] Using Bulma with styled-components theming?

### ISSUE THREAD

**Issue by internetstyle** [jgthms/bulma#2049]
I'm moving to the React / JS world and would like a solution to CSS themes for my projects. Analyzing Bulma and styled-components I found both great.

How do you use styled-components and JS variables to change the theme of Bulma? It is possible?

**Comment by mpaupulaire-rms** [comment]
there s bulma-styled-components

**Comment by jgthms** [comment]
https://github.com/mpaupulaire4/bulma-styled-components
