### ISSUE TITLE
Not able to right align the button addons.

### ISSUE THREAD

**Issue by coderabsolute** [jgthms/bulma#2050]
This is about **Bulma**.

### Overview of the problem

Not able to `right align` the **button field has-addons div**.

I'm using Bulma **0.7.1**
My **browser** is Chrome.

### Description

```
<div class="columns">
  <div class="column has-text-right">
    <div class="field has-addons">
      <p class="control">
        <a class="button">All</a>
      </p>
      <p class="control">
        <a class="button">Reserved</a>
      </p>
      <p class="control">
        <a class="button">Rented</a>
      </p>
      <p class="control">
        <a class="button is-selected is-primary">Overdue</a>
      </p>
    </div>
  </div>
</div>
```

### Expected behavior

The buttons addons should be moved towards the end of right.

### Actual behavior

The buttons addons is still left aligned.

**Comment by jgthms** [comment]
The “has-text-right” works for textual content, not flexbox items, which the “control” elements are.

**Comment by coderabsolute** [comment]
@jgthms How do I get the right aligned, then? :)

**Comment by Lawzy93** [comment]
A short addition to the css will fix this. See #2264

**Comment by jgthms** [comment]
You can use `buttons is-right`:

```html
<nav class="buttons is-right">
  <a class="button">One</a>
  <a class="button">Two</a>
  <a class="button">Three</a>
</nav>
```

**Comment by yomajo** [comment]
Sorry to wake this issue up, but  

@jgthms , is there a way to have two buttons on the left and third on the right (suppose delete element has to be separated)

> You can use `buttons is-right`:
> 
> ```
> <nav class="buttons is-right">
>   <a class="button">One</a>
>   <a class="button">Two</a>
>   <a class="button">Three</a>
> </nav>
> ```
