### ISSUE TITLE
Table doesn't work properly on mobile

### ISSUE THREAD

**Issue by tanin47** [jgthms/bulma#2052]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

`<table>` doesn't work properly with a smaller screen.

I understand that the table is too wide for a small screen, but I'd expect to be able to scroll horizontally to see all of its content. Currently, we can't.

Here's a screenshot of https://bulma.io/documentation/elements/table/

![screenshot from 2018-08-14 08-20-29](https://user-images.githubusercontent.com/494417/44100952-13e4b6ae-9f9b-11e8-8336-4d2402e36283.png)

### Expected behavior

We should be able to scroll right to see all of the `table`'s content.

### Actual behavior

We can't scroll, so we can only see the table partially.

**Comment by jgthms** [comment]
You can use the “table-container” to wrap the actual table.
