### ISSUE TITLE
How to control `Hero` width?

### ISSUE THREAD

**Issue by Rizary** [jgthms/bulma#2056]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Steps to Reproduce
put simple code:

![image](https://user-images.githubusercontent.com/7221768/44245548-66e9cc80-a203-11e8-9b1b-9002d644802f.png)

### Expected behavior
Hero width will follow tile element

### Actual behavior
The hero overlap other `tile`
![image](https://user-images.githubusercontent.com/7221768/44245563-779a4280-a203-11e8-84d8-dfa58d57c92b.png)

**Comment by jgthms** [comment]
The hero is a layout component like the section. You can’t really beat a hero in a section though. I’d recommend using a message or a notification if you want a colored block.

**Comment by Rizary** [comment]
@jgthms are you saying that layout components cannot stack each other? like Hero inside Section, or Hero inside Tiles?

**Comment by VirtualAirwaves** [comment]
![image](https://user-images.githubusercontent.com/13056860/47588730-fc988b00-d91b-11e8-82de-a185761235d4.png)

I'm getting an overlap, too, and I can't figure it out. Here's a sample page.,
