### ISSUE TITLE
is-loading for elements other than buttons

### ISSUE THREAD

**Issue by machinae** [jgthms/bulma#2058]
It would be great to have a general **is-loading** class can be used with a normal div. and/or a **.loading-indicator** element that can be included inside any div.

The implementation would just add a full width/height overlay with a centered loading spinner.

The use case is any element that loads data from an AJAX source, etc, which is very common.

**Comment by emkajeej** [comment]
I agree. I do this now by `@include`-ing the `loader` into `.is-loading::after`, and defining a `.is-loading::before` to match the desired overlay.
This might break some other styles associated on the parent div though, as the `is.loading` will overwrite its pseudo-elements as well as its positioning.

Would be great to have this out of the box regardless.

**Comment by machinae** [comment]
I’ve worked around this for now by adding a ‘has-loader’ class on the parent that just sets ‘position: relative’.

I don’t see the .loader class documented anywhere. Once I found it that solved 90% of the problem.

**Comment by airblade** [comment]
I would like to be able to use `is-loading` with the file upload component.
