### ISSUE TITLE
Navbar with secondary menu in mobile

### ISSUE THREAD

**Issue by xamado** [jgthms/bulma#2061]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **0.7.1**

### Description

I haven't been able to find references to something similar anywhere, so I'm going to go ahead and ask. I'm trying to have another button/element at the end of my navbar, but at the same time, when on mobile, keep it before the burger menu toggle. Basically I want another dropdown menu, for the shopping cart, to always be visible, even in mobile.

So in desktop I would have:

`Logo _____________  home products etc <cart>`

And in mobile:

`Logo _________________________ <cart><burger>`

I have tried using levels to put it after the navbar, tried playing around with the navbar itself to see if I could get it to stay, but I have yet to find something that works.

So in hopes that there's an obvious solution or that someone has solved it before, I pop the question.

**Comment by emkajeej** [comment]
Not out of the box. `.navbar-brand` gets stretched across the entire width on smaller screens, so the only way to do this currently is by using duplicate content; <cart> as part of `.navbar-brand` and as part of `.navbar-end`. This is how bulma.io does it with its github and twitter icons.
To get the <cart> right aligned, give the `.navbar-brand` version a `margin-left: auto`, and get rid of the `.navbar-burger`'s `margin-left`.
I'm not a fan of duplicate content but here we are :)
