### ISSUE TITLE
How to make components works?

### ISSUE THREAD

**Issue by iamchetanp** [jgthms/bulma#2068]
This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help? 

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

There are components available in Bulma CSS. I love it. But how to make it work on website. Where can I find JS for it?

**Comment by scottwernervt** [comment]
Bulma does not ship with any javascript. Some of the components have JS snippets for using them. I recommend searching npm for your framework packages, for example:

- Vue: [buefy](https://buefy.github.io/#/) or  [vue-bulma-components](https://github.com/vouill/vue-bulma-components)
- React: [react-bulma-components](https://github.com/couds/react-bulma-components)
- Ember: [ember-bulma](https://github.com/open-tux/ember-bulma)
