### ISSUE TITLE
p.control.is-grouped with multiple label.checkbox

### ISSUE THREAD

**Issue by vvinhas** [jgthms/bulma#207]
Hi :)

For some reason, the `margin-right: 10px` rule between form controls inside of a `.is-grouped` doesn't work when there are multiple `label.checkbox` inside.

I'm not sure if it's a bug or if it's me doing something wrong. Here's my code:
```html
<div class="box">
	<p class="control is-grouped">
		<label class="checkbox">
			<input type="checkbox"/>
			First Checkbox
		</label>
		<label class="checkbox">
			<input type="checkbox"/>
			Second Checkbox
		</label>
	</p>
</div>
```

Here's how it renders:
![Rendered layout]
(http://i.imgur.com/5eOdPgt.png)

Fiddle: https://jsfiddle.net/f07hehvo/

I'm using version **0.0.26**

**Comment by jgthms** [comment]
The syntax for `is-grouped` has changed. This should work:

```
<div class="box">
    <div class="control is-grouped">
        <p class="control">
            <label class="checkbox">
                <input type="checkbox"/>
                First Checkbox
            </label>
        </p>
        <p class="control">
            <label class="checkbox">
                <input type="checkbox"/>
                Second Checkbox
            </label>
        </p>
    </div>
</div>
```
