### ISSUE TITLE
level.sass seems to be in the wrong folder

### ISSUE THREAD

**Issue by albertofortin** [jgthms/bulma#2070]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** 0.7.1
This is a **Sass** issue

### Description

In the Documentation, "Level" is under "Layout".  The SASS file `level.sass` is in `sass/components` though.

### Expected behavior

I would expect `level.sass` to be in `sass/layout`

**Comment by jgthms** [comment]
Yes it’s a legacy location we’ve kept to avoid breaking changes.
