### ISSUE TITLE
Color Page, Getting Started page is not working properly in Mobile phones

### ISSUE THREAD

**Issue by sauravchandra1** [jgthms/bulma#2071]
In mobile phone Bulma's documentation following things not working properly:

In **Overview**
- "Color page", table content is not scrolling
- Getting started page
- "Add the responsive view port meta tag" not scrolling in getting started page
- Breakpoints table in "Responsiveness"
- "Functions" page is also not working
- Mixins

In **Customize**
- Varibles

**Comment by spencerkordecki** [comment]
There were some tables missing the `.table-container` class that caused them not to scroll horizontally on mobile. Below is a list of the pages I made this change to and will be opening a PR shortly. 

- Overview, Mixins
- Overview, Functions
- Overview, Colors
- Customize, Variables
