### ISSUE TITLE
Question: Is it better to use the Bulma CDN or not for live sites?

### ISSUE THREAD

**Issue by tomhrtly** [jgthms/bulma#2072]
For using the Bulma framework on a live website, would it be better to use the Bulma CDN and then overwrite the styles with my own SASS/CSS files or to download Bulma, change the file variables/add my own styles/etc and upload that for my live site?

Just inquiring which would be better regarding site speed/performance and best practice.

Thanks

**Comment by jgthms** [comment]
The CDN is best for using Bulma’s styles “out of the box”, when you don’t intend to change the default styles.

If you want to customise the styles, I recommend downloading or installing Bulma so you have access to the Sass files.
