### ISSUE TITLE
Bulma button hover color doesn't change (custom theme)

### ISSUE THREAD

**Issue by Resoguy** [jgthms/bulma#2076]
I have a custom color theme for bulma in my nuxt project, I have changed primary color in my main.scss file and it changes the color correctly but on button class it doesn't darken the color when hovered like the default color, it correctly darkens when i click the button.
This is how my main.scss file looks like in assets folder:

```
// main.scss

@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";

$primary: hsl(335, 100%, 50%);

@import "~bulma";
```

**Comment by jgthms** [comment]
The hover color is not that much darker so maybe you don’t notice it.
