### ISSUE TITLE
Feature request: `is-bordered` for images

### ISSUE THREAD

**Issue by DavidGarciaCat** [jgthms/bulma#2077]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I believe that on some occasions a bordered image might be useful, specially if the background of that image matches with the website background

### Steps to Reproduce

Just add the `is-bordered` css class to your `<img>` tag, that for now looks like is only available for HTML tables but not for images.

### Expected behavior

Bordered image in the same way I can get it using Bootstrap

<img width="283" alt="screen shot 2018-08-29 at 23 04 14" src="https://user-images.githubusercontent.com/7809429/44818158-e0a88f80-abdf-11e8-83cd-5dfbbab89d9e.png">

### Actual behavior

Image is displayed without any border

<img width="311" alt="screen shot 2018-08-29 at 23 03 29" src="https://user-images.githubusercontent.com/7809429/44818134-ca023880-abdf-11e8-9226-326028ba8b51.png">

**Comment by janydrozd** [comment]
@DavidGarciaCat is it still open? I could work on this.

**Comment by DavidGarciaCat** [comment]
Hi @janydrozd 

I didn't get an answer, and the issue is still open, so I am assuming no one worked on it.

Cheers,
