### ISSUE TITLE
Modals in safari do not grow with the content

### ISSUE THREAD

**Issue by jvanbaarsen** [jgthms/bulma#208]
**Versions**
Bulma: 0.0.26
Safari: 9.1 (11601.5.17.1)
Chrome: 50.0.2661.94

**Observed behaviour**
When I create a modal box, and look at it in safari, the box does not scale with it's content (See screenshot). While in chrome they show normal behaviour
*safari*
![image](https://cloud.githubusercontent.com/assets/1362793/15220295/49ca7546-1867-11e6-8a9d-96a4ab5ba527.png)
*chrome*
![image](https://cloud.githubusercontent.com/assets/1362793/15220311/5a6440da-1867-11e6-9a32-bc8452078959.png)

**Expected behaviour**
I expect the modal to behave the same way across browsers, and thus scale with its content.

**Comment by jgthms** [comment]
Can you try adding `flex-shrink: 0`

**Comment by jvanbaarsen** [comment]
To what container? The entire box?

**Comment by jvanbaarsen** [comment]
I tried adding it to the following without success:

* .modal
* .modal-card
* .modal-card-body

**Comment by jvanbaarsen** [comment]
@jgthms Why did you close this issue? It has not solved yet?

**Comment by xiaokaike** [comment]
also with this bug  in mac safair


![image](https://cloud.githubusercontent.com/assets/4251499/16337895/64573e20-3a4b-11e6-85a2-1c73640c4eeb.png)

**Comment by jvanbaarsen** [comment]
ping @jgthms Can you please re-open? Since it has not been fixed..

**Comment by RXminuS** [comment]
Similar problem here...please reopen.

It does seem to work though if the rule ```flex: 1``` is removed from ```.modal-card-body``` but that means that flexbox won't work for the contained items right?

**Comment by jgthms** [comment]
Will take a look.

**Comment by jvanbaarsen** [comment]
@jgthms Any news on this? Is there anything I can do to help you further debug this?

**Comment by jvanbaarsen** [comment]
@jgthms / @RXminuS / @xiaokaike The issue is fixed in the latest release! I'll be closing down this issue.
