### ISSUE TITLE
The navbar shadow looks like an ugly, thick line.

### ISSUE THREAD

**Issue by raniesantos** [jgthms/bulma#2081]
This is about **Bulma**.
This is a bug.
Its **NOT A BROWSER BUG**.

### Overview of the problem

This is about the Bulma **CSS framework**
**Version: 0.7.1**
My **browser** is: Chrome
**This is not a duplicate**

### Description

The new value for `box-shadow` on the Navbar's `has-shadow` class makes the shadow look like a thick solid line.

It's not obvious when you use an all-white layout.

![ffcb91aa-c10b-4c02-b229-7e7b5b435b25](https://user-images.githubusercontent.com/8528269/44799137-cf628180-abe5-11e8-9c66-1fab6b6874fe.png)

*(Left, 0.6.&ast;)* In the past versions, the box-shadow used `hsla` in its value.

*(Right, 0.7.1)* Now it uses a solid color.

**Screenshots:**

___

Bulma without themes. Hero under Navbar.

![378d18bd-4ea2-437a-8b32-dee8237286fd](https://user-images.githubusercontent.com/8528269/44904890-0601de80-ad43-11e8-9aec-1951c5d08802.png)

___

Bulma with Cyborg theme (Bulmaswatch).

![633ef21a-3e40-41af-8ce9-7f9b65019b58](https://user-images.githubusercontent.com/8528269/44798364-d38d9f80-abe3-11e8-8fe1-66dad01015a2.png)

___

Bulma with Journal theme (Bulmaswatch). Hero with background image under Navbar.

![screenshot from 2018-08-31 16-55-16](https://user-images.githubusercontent.com/8528269/44903296-bfaa8080-ad3e-11e8-9c68-e981f97cd51a.png)

___

### Steps to Reproduce

Add the class `has-shadow` to the navbar.

Add a modifier to the navbar that changes it's color (anything not close to white).

Add any element below it that is also not white (no margin/padding).

### Expected behavior

The navbar gets a subtle shadow.

### Actual behavior

The navbar shadow looks like an ugly, thick line.

**Comment by denizdogan** [comment]
I just noticed the exact same problem, first time user of Bulma here, but I looked closely at where the CSS came from... I was using `$navbar-box-shadow-size` but I should have used `$navbar-bottom-box-shadow-size`, so I changed that and it fixed my issue. Try it! :)
