### ISSUE TITLE
Column width changes depending on number of columns

### ISSUE THREAD

**Issue by shaief** [jgthms/bulma#2083]
This is about **Bulma**
It is a bug/question

### Overview of the problem
This is about the Bulma **CSS framework**

### Description
https://codepen.io/shaief/pen/jvBxzg
When generating number of columns based on server information, i would like the columns to have constant width.

The problem that i face, as you can see in the codepen above, is that when i have few columns in a line, their widths are OK, but if i have one - it shrinks and i can't even read the text in the placeholder.

### Expected behavior

to have the same column width even with few or one column per row

### Actual behavior

different column width with few or one column per row

**Comment by edlgg** [comment]
Hello, 
Im new to bulma, hopefully I can help you. Is there a specific reason as to why you are using tile? Cant you use section?

```
<section class="section">
  <div class="columns is-multiline">
    <div class="column is-one-quarter">
      <div class="field">
        <div class="control">
          <input class="input is-danger" placeholder="very long name">
        </div>
      </div>
    </div>
  </div>
</section>
```

**Comment by shaief** [comment]
@edlgg - thanks for trying, but it doesn't make any difference.

**Comment by edlgg** [comment]
@shaief  - https://codepen.io/edlgg/pen/QVvvwL

**Comment by shaief** [comment]
thanks! it looks promising but when i try it out with my changing number of columns they keep changing size...

**Comment by Carmezim** [comment]
I've also got this issue.

**Comment by mahmoud-mamdouh-matwaly** [comment]
'fix' the problem by { .columns } take { flex-grow: 1 }
