### ISSUE TITLE
Is there a way to change code based on screen size?

### ISSUE THREAD

**Issue by edlgg** [jgthms/bulma#2086]
This is about Bulma

Question

### Overview of the problem

I want to know if there is a way to react to the screen size. Here are somethings that I would like to do but I dont know if it is possible.

1) Change image based on screen size. I want to display different images to users viewing on desktop, tablet and phone and I want to be able to change the size of the image.

2) Not display certain things if the screen is of a certain size

3) Somehow get the screen size (desktop, mobile, etc) in a vue.js application to change the JS code. For example, change a computed property based on screen size.

**Comment by emkajeej** [comment]
Not really Bulma related questions, nonetheless:
1) Different options here. Look up `srcset`, use mediaqueries for sizing, and [Reponsive Helpers](https://bulma.io/documentation/modifiers/responsive-helpers/#hide) for visibility.
2) [Reponsive Helpers](https://bulma.io/documentation/modifiers/responsive-helpers/#hide) again.
3) This is not css related. Investigate `innerwidth` and `innerheight`. Try [W3Schools](https://www.w3schools.com/jsref/prop_win_innerheight.asp). Take window.resize into consideration.

**Comment by edlgg** [comment]
Thank you!
