### ISSUE TITLE
[Request][Enhancement] Field errors could have css classes to avoid unwanted post-validation expansion of the field/error message.

### ISSUE THREAD

**Issue by billbarni** [jgthms/bulma#2087]
This is about the Bulma **CSS framework**

### Description

Description of the enhancement:

Errors that happen after field is validated could have some css helpers to avoid it to expand the form.
Everytime some error happens in a form, the error shows somewhere around the field expanding the form, breaking some things, creating scrollbars... it should not expand the form in an ugly way like it happens, some helpers should be included so it would be possible for the error message be 'attached' to the field in a similar way as to Material does.

### Expected behavior

Error messages related to a field that appear when required should not expand the form and relocate its surroundings when the developer does not want it to.

### Actual behavior

Error messages just 'appear' and relocates all fields.

**Comment by jgthms** [comment]
Do you have an example or Codepen?

**Comment by jgthms** [comment]
You can just add the `is-invisible` class, so the text is hidden but the element still occupies the proper space.

**Comment by billbarni** [comment]
I changed the error toggle in the codepen for `is-invisible` instead of `is-hidden`, and nothing happens. Seems like `is-invisible` is being ignored for some crazy reason.

**Comment by jgthms** [comment]
You were using an old version of Bulma. Here's your code working with 0.7.1: https://codepen.io/jgthms/pen/OojgZy

```html
<div class="container">
  <div class="section">
    <div class="columns">
      <div class="column is-three-quarters">
        <div class="field">
          <label class="label">Email</label>
          <p class="control has-icons-right">
            <input id="email" class="input" type="text" value="hello@" required>
            <span id="warning" class="icon is-right is-invisible">
              <i class="fa material-icons">warning</i>
            </span>
          </p>
          
          <p id="errormsg" class="help is-danger is-invisible">
            This email is invalid
          </p>
        </div>
        
        <div class="field">
          <p class="control">
            <button onclick="myFunction()" class="button is-primary">Submit</button>
          </p>
        </div>
      </div>      
    </div>
  </div>
</div>
```

**Comment by billbarni** [comment]
Great solution. Sorry to take your time.
Thanks for mantaining this amazing project.
