### ISSUE TITLE
Add required imports to docs

### ISSUE THREAD

**Issue by ChildishGiant** [jgthms/bulma#2088]
This is about **the Docs**.

When importing each required sass file separately, I can't find any docs on what is required. My request is that for each page on the docs, it lists the required imports for the feature to work. 

For example, the [Hero docs](https://bulma.io/documentation/layout/hero/) would list 
```css
@import "../node_modules/bulma/sass/elements/title.sass";
@import "../node_modules/bulma/sass/layout/hero.sass";
@import "../node_modules/bulma/sass/layout/section.sass";
```

An alternative to this would be a page where you can upload/paste an HTML file and it scans it and works out what needs importing. I'd happily make this if I actually knew what each element needs.

**Comment by jgthms** [comment]
The hero itself doesn’t actually need the title or the section. 

It’s hard to figure out exactly what each element needs since some styles are inherited from the reset and the global styles. If you only needed a button, you would need quite a few files to make it work perfectly.
