### ISSUE TITLE
Scaling cards, levels, media and panels

### ISSUE THREAD

**Issue by romikforest** [jgthms/bulma#2090]
I need help
This is about the Bulma **CSS framework** 
My **browser** is: Firefox Quantum 61.0.2 64bit on Windows

When I use **card, level, media or panel containers** I often have a problem with long texts: they go out of supposed container boundaries while scaling (if I resize the browser window to lower sizes horizontally). I have not this problem when I use **columns**, so I usually prefer them. With cards, levels and panels I've tried to use classes like

.clip {
  flex: 1;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
} 

but they work unstable: I need to change classes in several divs and then, if I change something (just add for example is-one-quarter class) - they stop to work.

How is it supposed to use those classes. May be they must be wrapped to some containers to work properly?

**Comment by diomed** [comment]
did you try` word-break` ❔ 
https://github.com/jgthms/bulma/pull/1641
