### ISSUE TITLE
.tags.has-addons.is-right introduces margins at wrong place

### ISSUE THREAD

**Issue by bertBruynooghe** [jgthms/bulma#2091]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.1]

### Description

When using `class="tags has-addons is-right", a margin is introduced between the tag parts.

### Steps to Reproduce

    <div class="tags has-addons is-right">
        <span class="tag">Package</span>
        <span class="tag is-primary">Bulma</span>
    </div>

### Expected behavior

'Package' and 'Bulma' should be nicely glued together, aligned to the right.

### Actual behavior

There is a gap between 'Package' and 'Bulma'

**Comment by msangui** [comment]
I think the right fix is to add a quick "exception" in elements/tag.sass:


     &.is-centered, &.is-right
        .tag
          margin-left: 0
          margin-right: 0


in line 28 right after .has-addons definition

**Comment by bertBruynooghe** [comment]
FYI: I patched locally using:   

    .tags.is-right.has-addons .tag:not(:first-child) {
        margin-left: 0;
    }
