### ISSUE TITLE
No gaps between columns

### ISSUE THREAD

**Issue by Korasami** [jgthms/bulma#2095]
### Overview of the problem
This is about the Bulma CSS framework.

### Description
Looking at the example from the docs, there is a gap between the columns.  Copying the code results in columns with no gap.

### Steps to Reproduce / Actual behavior
Html Code copied from docs- https://codepen.io/anon/pen/EebqLe
Desired result- https://bulma.io/documentation/columns/basics/

**Comment by jgthms** [comment]
The background you applied includes the padding. The gap is between the _content_ of the columns, not the columns themselves.

**Comment by Korasami** [comment]
Thank you

**Comment by navegotel** [comment]
Stumbled over the same thing. Maybe this is worth mentioning in the online Documentation.

**Comment by FiorellaChilcon** [comment]
This should definitely be mentioned on the Docs! I just spent some time figuring out this

**Comment by singhay** [comment]
+1
