### ISSUE TITLE
IcoMoon support for icons

### ISSUE THREAD

**Issue by flexchar** [jgthms/bulma#2096]
This is about **Bulma**.

Feature suggestion. 
It would be nice to have support for IcoMoon icons. The offer quite simple and easy to use platform for making custom icon font sets. Currently, Bulma classes are not friendly with their fonts.

Cheers!

**Comment by jgthms** [comment]
Do you have an example? The Bulma “icon” class should work with any icon font.

**Comment by flexchar** [comment]
@jgthms made one here: https://codepen.io/anon/pen/aaEKgO 

Note that IcoMoon CSS link expires in 24 hours, and therefore, for the code to work new link has to be generated.
