### ISSUE TITLE
No container.sass file in layout folder

### ISSUE THREAD

**Issue by rayhaanq** [jgthms/bulma#2097]
This is a question but maybe a missing feature

Is there a sass file at all for .container? It seems like the files are structured according to the way the docs are organised. I was just wondering if there was a way to import styles relating to `container`. From what I can see, there's only `hero.sass`, `section.sass`, and `footer.sass`. Are the other layout modules missing? Or are they a part of another module completely? https://github.com/jgthms/bulma/tree/master/sass/layout

I've imported `section.sass` into my main `styles.scss`. 

```
<section class="section">
	<div class="container">
		bla
	</div>
</section>
```

It looks as if no styles have been applied to the container div after adding the container class.
I'm doing this in an angular 6 project

I've added the container css manually to work around this for now

**Comment by jgthms** [comment]
It’s there but it’s in the elements folder for backwards compatibility: https://github.com/jgthms/bulma/blob/master/sass/elements/container.sass
