### ISSUE TITLE
Font Awesome icon not displayed correctly when using the span element

### ISSUE THREAD

**Issue by jonkri** [jgthms/bulma#2099]
This issue is about Bulma 0.7.1 and Font Awesome, and it seems to be a bug in the Bulma CSS code.

My browser is Mozilla Firefox.

Font Awesome can i use the `i` element for its icons, but it can also use the (probably more semantically correct) `span` element.

Here is a working example, using `i`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>A working Bulma and Font Awesome example</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"
      rel="stylesheet">
    <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      rel="stylesheet">
  </head>
  <body>
    <p class="subtitle"><i class="fas fa-bars"></i></p>
  </body>
</html>
```

Here is a non-working example, using `span`, not displaying the icon (only a box):

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>A non-working Bulma and Font Awesome example</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"
      rel="stylesheet">
    <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      rel="stylesheet">
  </head>
  <body>
    <p class="subtitle"><span class="fas fa-bars"></span></p>
  </body>
</html>
```

It doesn't matter if I wrap the `p` element in a `section` element.

If I remove `class="subtitle"`, the icon displays correctly.

I expected the icon to be displayed using either code snippet above.

The actual behavior is that the icon is only displayed in the first code snippet.

Thanks!

**Comment by jgthms** [comment]
That's because Bulma has the following rule:

```css
.subtitle em, .subtitle span, .title em, .title span {
  font-weight: inherit;
}
```

**Comment by jonkri** [comment]
@jgthms: Thanks for your reply! How come this side-effect is not considered a bug? It's surprising (at least it was to me) and it breaks Font Awesome usage that would otherwise be acceptable. I'm wondering in particular since Bulma seems to be made to work together with Font Awesome in particular.
