### ISSUE TITLE
Unsure of overflow.

### ISSUE THREAD

**Issue by Lukortech** [jgthms/bulma#2100]
It's a question about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

My **browser** is: Newest chrome/ff.
 This is a **Sass** issue: I'm using version [https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css] 

### Description

I am unsure of it, but does Bulma have in it's css anything about overflow that tries to show the scroll even if there is no overflow? If yes is there a reason for that? 
Sorry for newbie question. Just trying to figure some things out.

### Steps to Reproduce

1. Get this code below inside your <body> tags,
```
<div class="notification is-warning">
<button class="delete"></button>
Primar lorem ipsum dolor sit amet, consectetur
adipiscing elit lorem ipsum dolor. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Sit amet,
consectetur adipiscing elit
</div>
```
2. Check if there is scroll on the left side of the browser,
3. If there is a scroll, eventhough the content does not overflow, is that allright or am I missing something?

**Comment by jgthms** [comment]
It’s there to prevent the website from “jumping” when going from a page that needs a scrollbar to a page that doesn’t.
