### ISSUE TITLE
Select objects with better accessbility

### ISSUE THREAD

**Issue by pkbarbiedoll** [jgthms/bulma#2101]
This is a feature request for **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Currently, Bulma offers very basic functionality for select input objects.  We basically have just what is available to us with vanilla HTML.    When we need to create a select input object for multiple items, the options are to use a multiple select (with text "hold ctrl to select more than one") or multiple checkboxes.  Neither is ideal.

Please consider implementing additional select options similar to what is available on this page.

https://harvesthq.github.io/chosen/

and the project github: 
https://github.com/harvesthq/chosen

The examples provided above do rely on jquery, however, they offer very attractive and easy to use alternatives to vanilla select boxes.  It would be great to see these same options folded in with Bulma.

**Comment by jgthms** [comment]
As you said, such a component requires JavaScript, so it wouldn’t be able to exist on its own in Bulma.

Also, these examples are actually less accessible because they’re not native controls.

**Comment by mm98** [comment]
I'm using [Select2](https://select2.org/) and have added a Bulma theme to it. Include the attached SSCS to your project in the Select2 folder, and insert the bulma theme path to "\select2\src\scss\core.scss"

[src.zip](https://github.com/jgthms/bulma/files/2379204/src.zip)

**Comment by jgthms** [comment]
It seems to be working without having to include it in Bulma. 😉

**Comment by pkbarbiedoll** [comment]
**chosen** works, but the default docsupport/style.css doesn't play nice with Bulma: https://imgur.com/wZbKNmZ  (see gray background where form is).
