### ISSUE TITLE
Spacing Variables

### ISSUE THREAD

**Issue by dgrahn** [jgthms/bulma#2106]
This is about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.1

### Description
Bulma does not appear to have sass variables for the spacing between components. I may be missing it, but most look to be hard coded.

**Comment by williamabbott** [comment]
Checkout a gist based on Bootstrap's method:
https://gist.github.com/williamabbott/47767c82a7b62f4fe0d931b94a9b489b
