### ISSUE TITLE
Use normalize.css?

### ISSUE THREAD

**Issue by taoeffect** [jgthms/bulma#211]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.26]
* [x] My **browser** is: all of them
* [x] This is a **Sass** issue: I'm using version [node-sass 3.7.0]
* [x] I am sure this issue is **not a duplicate**?

### Description

I've been looking through bulma's [reset.sass](https://github.com/jgthms/bulma/blob/master/sass/utilities/reset.sass) and comparing it with [normalize.css 4.1.1](https://github.com/necolas/normalize.css/blob/master/normalize.css).

They seem to be doing a great, comprehensive job of fixing many issues, and not just issues that affect old browsers but some that appear to affect new ones.

I noticed that bulma's reset stylesheet does not have some (possibly important?) items from normalize.css, and it also has some quirky differences, for example using `font-size: 85%` instead of `font-size: 80%` for `small`.

Was there a serious issue with normalize.css that made bulma create its own? Or can bulma incorporate the work that normalize.css has done (and continues to iterate on)?

**Comment by jgthms** [comment]
I've never used normalize but it would clash with some bulma styles so I'd rather have a reset.

Normalize serves a different purpose.

**Comment by taoeffect** [comment]
> A modern alternative to CSS resets

Really? What is that? Normalize describes itself as:

> A modern, HTML5-ready alternative to CSS resets

So it seems to serve the same purpose?

**Comment by jgthms** [comment]
If you check [this page](http://yuilibrary.com/yui/docs/cssnormalize/normalize-basic-example.html), normalize keeps useful defaults such as:

* different heading sizes
* default button style
* list indentation
* underlined links
* block margins

I prefer a reset where every size, margin, padding, style, is removed, as it makes the implementation of bulma styles easier.
