### ISSUE TITLE
.select.is-loading with a .is-$color class creates solid color loader

### ISSUE THREAD

**Issue by ralphpig** [jgthms/bulma#2111]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.1]

### Description

When a select element has the classes `.is-$color .is-loading`, the loader on the select has all 4 borders the same color.

### Steps to Reproduce

```html
<div class="select is-danger is-loading">
  <select>
    <option>Bad</option>
  </select>
</div>
```

### Expected behavior

The select element should be 'danger' color, and have a 'danger' colored spinning loader.

### Actual behavior

The class 'is-danger' sets the border color to danger, therefore overwriting the transparent edges of the loader.

[Codepen](https://codepen.io/ralphpig/pen/xamXRo)

### Suggested Remedy

I noticed for the [button loader](https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L150) the transparent border for the loader was explicitly set, and with an `!important`.
`border-color: transparent transparent $color-invert $color-invert !important `

I supposed the same could be done for the [select loader](https://github.com/jgthms/bulma/blob/master/sass/elements/form.sass#L189)
`border-color: transparent transparent $color $color`

Or maybe set the transparent edges !important for the [loader mixin](https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L242)
`border-right-color: transparent !important`

**Comment by ralphpig** [comment]
I can submit a pull, but I'm wondering what the recommended approach is before that.

**Comment by DanielBiegler** [comment]
Just noticed this in v0.7.2, would love to have a fix for that. :frowning_face:

**Comment by ralphpig** [comment]
@DanielBiegler Ah yeah, the color would have to be fix on hover too.

I'm didn't think that my one line fix would sufficient, as there's probably a couple other things that need to changed. That's why I was hoping to for input from the maintainers.
