### ISSUE TITLE
File button - Right Side not displaying correctly

### ISSUE THREAD

**Issue by andfelzapata** [jgthms/bulma#2115]
### Overview of the problem

This is about the Bulma **Docs** 

My **browser** is: Chrome 69.0.3497.100 (Official Build) (64-bit)

### Description

In the file form/file section: https://bulma.io/documentation/form/file/

The **You can move the CTA to the right side with the .is-right modifier.** example has a problem. 

The file button is not being displayed correctly.

<img width="619" alt="screen shot 2018-09-20 at 8 43 25 pm" src="https://user-images.githubusercontent.com/4138205/45855505-070ca700-bd16-11e8-8328-40177a487e25.png">

**Comment by mm98** [comment]
Take a look at #1904 ... there is a manual fix currently ...
