### ISSUE TITLE
Changing $modal-close-dimensions doesn't change the size of modal close button

### ISSUE THREAD

**Issue by williamkhshea** [jgthms/bulma#2121]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.1] 
My **browser** is: Google Chrome Version 68.0.3440.106

### Description

Changing $modal-close-dimensions variable doesn't change the size of the close button. as it is bound by the max-height, max-width, min-height and min-width set by .delete, .modal-close.

![image](https://user-images.githubusercontent.com/4775489/45929677-aab0be00-bf87-11e8-9438-99778d340c64.png)
### Steps to Reproduce

Change $modal-close-dimensions variable to 80px.

### Expected behavior

The size of modal close button change to 80px.

### Actual behavior

The size of modal close button remains unchanged.

**Comment by andrei-dracea** [comment]
This is still a problem, please re-open

**Comment by jeckojim** [comment]
I corrected it just by defining `max-width` and `max-heigh`t to `$modal-close-dimensions` but I'm very surprised (or deceipt) to cannot customize easily these rules without overwriting the CSS (SCSS).
