### ISSUE TITLE
Multiple Horizontal form alignment and icon / addon problems.

### ISSUE THREAD

**Issue by CromonMS** [jgthms/bulma#2124]
This is about **Bulma**
I'm using Bulma version [0.7.1]

### Overview of the problem

 This is about the Bulma **CSS framework**

### Description

When trying to use Selects alongside text Inputs on a Horizontal form the alignment is off.
Has-left-icons does not work either and the icon hovers over the label.
When using has-addons there is no alignment at all.

### Steps to Reproduce

https://jsfiddle.net/168fdxz0/7/

### Expected behavior

Expected all inputs to line up vertically and horizontally and Icon to be contained within the input, and addon input to line up.

### Actual behavior

Input does not align with Selects. and Left Icon hovers over label, input with addons is all over the place.

-----

Maybe my use of the elements is wrong, but have tried a number of ways and all end up with problems.

Thanks.

**Comment by jgthms** [comment]
You can put a `div` in a `p` and you can't put a `.label` in `.control` element.

```html
<div class="content">
  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
          <label class="label">Product</label>
        <div class="control">
          <div class="select">
            <select>
              <option value="">Select Type</option>
              <option value="A">A</option>
              <option value="B">B</option>
              <option value="C">C</option>
            </select>
          </div>
        </div>
      </div>
      <div class="field">
          <label class="label">Format</label>
        <div class="control">
          <div class="select">
            <select>
              <option value="">Select Format</option>
              <option value="1">1</option>
              <option value='2"'>2</option>
              <option value='3'>3</option>
            </select>
          </div>
        </div>
      </div>
      <div class="field">
          <label class="label">Price</label>
        <div class="control has-icons-left">
          <input class="input" type="number" name="">
          <span class="icon is-small is-left"><i class="fa fa-gbp"></i></span>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Price</label>
          <input class="input" type="number" name="">
        </div>
      </div>
      <div class="field">
        <label class="label">
          Price
        </label>
      <div class="field has-addons">
        <p class="control">
          <a class="button is-static">
            £
          </a>
        </p>
        <p class="control">
          <input class="input" type="number">
        </p>
      </div>
      </div>
    </div>
  </div>
</div>
```

![image](https://user-images.githubusercontent.com/1254808/45959951-feb4b480-c012-11e8-80ab-5b9abba6755c.png)

**Comment by CromonMS** [comment]
Thanks! I knew I probably had it wrong!
