### ISSUE TITLE
.is-loading (buttons) should have fixed/independent border-radius value

### ISSUE THREAD

**Issue by Come2Daddy** [jgthms/bulma#2129]
This is about **Bulma**.

This is about the Bulma **CSS framework** 
 I'm using Bulma **version** [0.7.1]
I am sure this issue is **not a duplicate**

### Description

If squaring corners (border-radius = 0) is wanted on global style, loading icon in buttons with `.is-loading` becomes a spining angle that doesn't mean much anymore or feels weird. The use of global vars for this purpose seems wrong, as it should keep its 'loading' shape unless explicitly specified.

### Steps to Reproduce

1. Set `$radius-rounded` to 0 in `utilities/initial-variables.sass`
2. Compile your sass
3. Test

```
<a class="button is-loading">Loading</a>
```

### Expected behavior

Round shape
![capture d ecran de 2018-09-27 21-24-45](https://user-images.githubusercontent.com/8274383/46169623-f8853900-c29b-11e8-9e2c-4cf4f048d7ec.png)

### Actual behavior

Square shape
![capture d ecran de 2018-09-27 21-21-48](https://user-images.githubusercontent.com/8274383/46169648-08048200-c29c-11e8-91e7-47c933fc841a.png)

**Comment by jgthms** [comment]
The `$radius-rounded` is not really meant to be modified. It’s just to prevent typing it too often.

**Comment by Come2Daddy** [comment]
It's an overwritable variable used in most (all ?) components / elements. That's, in my opinion, part of the customization.

2 ways out :
1. It's not meant to be modified => should not be overwritable.
2. Should stay overwritable => should not be used in this specific case.

**Comment by Come2Daddy** [comment]
Didn't pushed far enougth, as I saw it's an overwritable var I thought I had to put it to 0 to get squared borders. To go totally in your direction I would keep this var fixed, not overwritable... but no big deal.
