### ISSUE TITLE
navbar and container is-widescreen: no lateral space in desktop breakpoint.

### ISSUE THREAD

**Issue by frederikhors** [jgthms/bulma#2134]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.1**
I am sure this issue is **not a duplicate**

### Description

I think there is a misunderstanding with `navbar` and `container is-widescreen`.

Just in the `$desktop` breakpoint the `navbar-brand` and `navbar-menu` are without lateral space, see screen below:

![image](https://user-images.githubusercontent.com/41120635/46246944-c7744800-c404-11e8-8bb2-9f80404bffda.png)

### Steps to Reproduce

Go here on jsfiddle: https://jsfiddle.net/fredhors/v7cd01ft/1/

### Expected behavior

I expect to see lateral spaces (padding) in `$desktop` breakpoint of `container is-widescreen`.

### Actual behavior

Actually there is no lateral space in `$desktop` breakpoint, but there is in `$tablet` one and upper.

**Comment by janydrozd** [comment]
@frederikhors is it still open? I could work on this.

**Comment by frederikhors** [comment]
No stale, @stale!
