### ISSUE TITLE
How to set base font-size for responsive layouts

### ISSUE THREAD

**Issue by Kay2dan** [jgthms/bulma#2137]
This is about **Bulma Documentation**.

This is not a bug, but a question on usage. I have gone through the docs, however, am a bit confused about how to set base fonts for responsive layouts.

### Overview of the problem

I'm using Bulma **version** [0.6.2]
My **browser** is: Firefox 62.0
I am sure this issue is **not a duplicate**. 

I am not clear how to set responsive media queries in Bulma. How can I set a base `$body-size` for `mobile`, `tablet`, `desktop` etc. This would make the sizes & content automatically resize based on the layout.

I posted this question on [Stackoverflow](https://stackoverflow.com/questions/52605748/how-to-set-base-font-sizes-in-bulma-css-for-responsive-design) before posting here.

### Steps to Reproduce
n/a

### Expected behavior
Guidance on how to set the base font-size for different responsive layouts.

Variables or method of setting base `$body-size` for responsive layout.

### Actual behavior
There is no guidance, hence the confusion.

Seeking guidance. Thank you.

**Comment by jgthms** [comment]
You could use the responsive mixins like this:

```sass
+mobile
  html
    font-size: 14px
    
+tablet-only
  html
    font-size: 16px

+desktop-only
  html
    font-size: 18px

+widescreen-only
  html
    font-size: 20px

+fullhd
  html
    font-size: 22px
```

**Comment by Kay2dan** [comment]
Thank you for the guidance @jgthms
