### ISSUE TITLE
The colors of a navbar-item that is inside a navbar-dropdown, doesn't apply properly

### ISSUE THREAD

**Issue by jhonland** [jgthms/bulma#2138]
This is about **Bulma**.
 Is it a bug.

### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.7.1]
My **browser** is: Chrome

### Description

when hovering over a navbar-item that is inside a navbar-dropdown in a nav element, there is a color property on hover inside a media query that overwrites the default color of "a.navbar-item:hover" that has a color of "#3273dc" that is being changed for "#0a0a0a" and the properties inside the media query at the same time overwrites the default background-color on hover state from a color of "#fafafa" to "whitesmoke".

### Steps to Reproduce

inspect in a browser your own example of a "Basic Navbar" https://bulma.io/documentation/components/navbar/#basic-navbar
(because the same happens here)
- mark the parent navbar-element with :hover (the one with the dropdown obviously) for it to stay down.
- mark the 'a' tag that says "About" with :hover and look in the inspector the color being overwritten.

![bulmaissue](https://user-images.githubusercontent.com/28849469/46385718-99ed0000-c68b-11e8-8407-c2c1755e348a.png)

### Expected behavior

Media queries should not overwrite the default color of any element.

### Actual behavior

The class for elements "a.navbar-item:hover" with a default color is being overwrite by a media query
@media screen and (min-width: 1088px)

**Comment by jgthms** [comment]
It's there for 2 reasons actually:

- customization: you can choose different colors for the parent item and the dropdown item
- colored navbars: the parent item is colored, the dropdown is not, so it's necessary to have a distinction here
