### ISSUE TITLE
View Dropdown menu after Click action

### ISSUE THREAD

**Issue by arturplo** [jgthms/bulma#2148]
Hi How to view dropdown menu in  navbar after on click action on navbar-item?

**Comment by jgthms** [comment]
You need to toggle the `is-active` class on the dropdown. It works the same way as with the navbar burger. There's a snippet in this section of the page: https://bulma.io/documentation/components/navbar/#navbar-menu

**Comment by scottwernervt** [comment]
@arturplo You need to add a click [event listener](https://developer.mozilla.org/en-US/docs/Talk:DOM/element.addEventListener) that checks if the target element is outside of the dropdown.
