### ISSUE TITLE
Problem with Dropdown menu content image size

### ISSUE THREAD

**Issue by arturplo** [jgthms/bulma#2149]
Hi, how to view image in size 128px / 128px in navbar dropdown menu ![schowek-1](https://user-images.githubusercontent.com/8561816/46711467-c0430a80-cc4c-11e8-89e8-c770776261f2.png)
![schowek-2](https://user-images.githubusercontent.com/8561816/46712048-64c64c00-cc4f-11e8-83e1-12d4f4d40558.png)

**Comment by WaYdotNET** [comment]
some problem
