### ISSUE TITLE
Modal component is not scrollable IE11

### ISSUE THREAD

**Issue by eboukamza** [jgthms/bulma#2150]
This is about **Bulma**.

It is a bug in IE11 browser. **Other browsers are not concerned**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.7.1
My **browser**  IE11

### Description

The modal component is not scrollable in IE11 so user can interact with de bottom hidden part.

### Steps to Reproduce
Create a modal with a lot of content (depending on your screen resolution) to force bulma to create an scroll.

    <div class="modal" class="is-active">
        <div class="modal-background"></div>
            <div class="modal-card">
               
            </div> 
        </div>
    </div>

### Expected behavior
The `modal-card` content is scrollable

### Actual behavior

The `modal-card` is not scrollable

**Comment by eboukamza** [comment]
looks fixed in #1909

**Comment by samiggapps** [comment]
I found this still an issue but fixed it like this:

```
.modal-card{
  overflow: auto;
}
```
