### ISSUE TITLE
How to create menu sidebar with dropdown click

### ISSUE THREAD

**Issue by aztran** [jgthms/bulma#2152]
Hello ,
I want to make sidebar with some lists have a child. so it needs like dropdown to open a child,
is there possible using bulma to create it?

**Comment by jgthms** [comment]
Any example?

**Comment by aztran** [comment]
![Uploading Screen Shot 2018-10-11 at 20.07.38.png…]()

**Comment by aztran** [comment]
<img width="1049" alt="screen shot 2018-10-11 at 20 07 38" src="https://user-images.githubusercontent.com/9424015/46806286-6730bf00-cd91-11e8-9689-818971e5acc7.png">

@jgthms like this

**Comment by jgthms** [comment]
Not out of the box, but you could customize the menu component: https://bulma.io/documentation/components/menu/
