### ISSUE TITLE
How to use the new list class and its child classes in V 0.7.2?

### ISSUE THREAD

**Issue by GabMic** [jgthms/bulma#2162]
This is about **the Docs**.

### Overview of the problem

 This is about the Bulma **Docs**
 I'm using Bulma **version** 0.7.2

I am sure this issue is **not a duplicate**

### Description
I dont see a proper documentation for the `list` class, but i can go to: 
[https://bulma.io/documentation/components/list](url)

Will this be updated? 
Thanks.

**Comment by GabMic** [comment]
Anyone?

**Comment by jgthms** [comment]
It’s not ready yet. I have to write some documentation.

**Comment by GabMic** [comment]
Thank you! Sure waiting.  :)
