### ISSUE TITLE
Sketch Settings or Templates for Designing on the Bulma Grid?

### ISSUE THREAD

**Issue by mattdeco** [jgthms/bulma#2169]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**

### Description

My team and I are interested in using the grid system in Bulma as the underpinning for an upcoming redesign project. We won't really be using the individual elements / components, just the grid system and some of the parts of the library in the utilities, base, elements, grid, and layout portions.

My team is divided between front end developers and visual designers. The visual designers do not code or write CSS.

I'm hoping to provide them with Sketch resources for each Bulma breakpoint that includes the Bulma grid with correct column / gutter widths, such as a set of templates or collection of layout settings. This is so they can do their visual design on a grid that will then match up to the grid we're using in CSS to create the actual end product.

### Example Use Case
A designer creates a grid of photos where each photo is 3 columns wide at the desktop breakpoint, but 4 columns wide at the tablet breakpoint. They do this by creating 2 comps in Sketch -- one using a template that matches the tablet breakpoint / column / gutter dimensions, and one using a template that matches the desktop breakpoint / column / gutter dimensions. A developer can then implement this design with the following HTML and have the resulting page perfectly match the dimensions the designer is expecting:

```html
<div class="columns">
	<div class="column is-4-tablet is-3-desktop"><!-- img tag --></div>
	<div class="column is-4-tablet is-3-desktop"><!-- img tag --></div>
	<div class="column is-4-tablet is-3-desktop"><!-- img tag --></div>
</div>
```
I've been unable to find any resources that would help with this -- the Bulma Sketch resources I can find are focused on actual Bulma visual elements (like buttons) rather than the "invisible" parts of the framework (like the grid).

Any help figuring this out would be greatly appreciated. Thank you so much for such a great library and accompanying documentation!

**Comment by standingdreams** [comment]
For anyone that may come across this page and is still looking for a resource, below are two UI Kits for Bulma:

https://github.com/joachimesque/Bulma.sketch
https://github.com/michaelwilkins/bulma-ui-kit

**Comment by sarkenny95** [comment]
I've created a sketch template based on Bulma Builder responsive grid settings. Feel free to download:

https://github.com/sarkenny95/bulma-responsive-grid-sketch
