### ISSUE TITLE
[Bug] Buttons in "hero is-fullheight" are going full-width

### ISSUE THREAD

**Issue by Wizjonero** [jgthms/bulma#217]
* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [ ] I'm using Bulma **version** [x.x.x]
* [ ] My **browser** is:
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [x] I am sure this issue is **not a duplicate**?

### Description
Any button used inside "hero is-fullheight" div is going full-width.

Screenshot: http://take.ms/qdIi3

**Comment by matsumurae** [comment]
This should be fixed, but for now...
@Wizjonero you can use a div for contain the button with the `has-text-centered` class. I [attach a photo](https://cloud.githubusercontent.com/assets/1831932/15629577/9f8bd6fc-251c-11e6-8f72-d4b0be2cb510.png) for illustrate the example.

It's a weird fix, but works. Until it's fixed I suggest you to use it if you want your buttons in the center.

**Note:** I'm using bulma 0.0.26 and Chrome in mac.

**Comment by jgthms** [comment]
Argh, it's the `align-items: stretch` that's causing the issue. Not even sure why it was needed in the first place.
