### ISSUE TITLE
Feature Request - Fieldset Class

### ISSUE THREAD

**Issue by Lettucez** [jgthms/bulma#2177]
This is a feature request.

Description

Hello. First off let me say I am new to contributing and would like learn how and get familiar with doing so. I apologize if this is in the incorrect format.

I suggest that there be a "fieldset" class that will style input elements into a group, similar to how the "panel" class and sub-classes currently operate. 

I prepared an example [here ](https://codepen.io/anon/pen/ReeLpv)on codepen, using essentiality the panel class properties to achieve the look I imagine. If there is a more appropriate way to demonstrate this feature then I will happily comply.

Thank you for your time.

**Comment by weyert** [comment]
Why not use `<legend>` for the fields label?

**Comment by Lettucez** [comment]
Good question! I know that `<legend>` has default styling and i wasn't sure if I should continue to use that and try to remove that styling.
