### ISSUE TITLE
Equal height of card components

### ISSUE THREAD

**Issue by danielbayerlein** [jgthms/bulma#218]
What is the way to go if I want to align two card components to the same height.

```html
<div class="container">
  <div class="columns">
    <div class="column">
      <div class="card">
        <div class="card-content">Hello World</div>
      </div>
    </div>
    <div class="column">
      <div class="card">
        <div class="card-content">
          Hello
          <br>
          <br>
          World
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card">
        <div class="card-content">Hello World</div>
      </div>
    </div>
  </div>
</div>
```

<img width="778" alt="bildschirmfoto 2016-05-26 um 18 44 01" src="https://cloud.githubusercontent.com/assets/457834/15582570/f05c870e-2371-11e6-89fd-b7d234b01124.png">

**Comment by danielbayerlein** [comment]
Stupid question! The answer is too simple:

```css
.card {
  height: 100%;
}
``

**Comment by de-raaf-media** [comment]
Simple enough but that does not seem to work in Safari?

**Comment by timonweb** [comment]
Confirm, this seems not to work in Safari

**Comment by heltonteixeira** [comment]
@danielbayerlein 
Using height: 100% only works if you don't use card-footer.

**Comment by rogierborst** [comment]
@heltonteixeira 
```
.card {
    display:flex;
    flex-direction: column;
}
.cart-footer {
    margin-top: auto;
}
```
This will push your footers to the bottom.

**Comment by l2aelba** [comment]
Yep base on @rogierborst 

```
.bm--card-equal-height {
	display:flex;
	flex-direction: column;
	height: 100%;
}
.bm--card-equal-height .card-footer {
	margin-top: auto;
}
```

So now you can do something like :

```
<div class="card bm--card-equal-height">
   <!-- content -->
</div>
```

**Comment by erosenberg** [comment]
So I'm running into something similar with this... I'm able to get all of the cards to be full height, but the `card-content` itself is not stretching to the bottom when I set it `height: 100%`. In fact, it usually goes over the card's actual height. I could just apply `overflow: hidden` to the cards but that seems kind of hacky, right? Is there anything else I can try?

**Comment by danny117117** [comment]
I am facing some problem with angular flex layout I can not  get the card to have the same height

<div fxFlex fxLayout="column">
    <div fxLayout="row" fxLayoutAlign="end start" class="pr-32 pt-8">
        <button mat-mini-fab style="z-index: 100;" (click)="onEditMode()">
            <mat-icon aria-hidden="false" aria-label="Example home icon">edit</mat-icon>
        </button>
    </div>


    <div fxLayout="row"  fxLayoutGap="20px" class="pt-8">
        <div fxFlex="50%" fxLayout="column">
            <app-pereon-info [person]="person"></app-pereon-info>
        </div>
        <div fxFlex="50%" fxLayout="column"  fxFlexAlign="stretch">
            <app-address-info [addresses]="address"></app-address-info>
        </div>
    </div>


    <div fxLayout="row" class="pt-8 pl-32 pr-32 pb-32" fxLayoutAlign="start start">
        <div fxFlex fxLayout="column">

            <app-person-portfolio></app-person-portfolio>
        </div>
    </div>
</div>

**Comment by Yorer** [comment]
```
.card {
  height: 100%;
  display:flex;
  flex-direction: column;
}

.card-block{
  height: 100%;
}
```

This will automatically push the footer to bottom, and also card-footer border will be on the right place.

**Comment by malprax** [comment]
> ```
> .card {
>   height: 100%;
>   display:flex;
>   flex-direction: column;
> }
> 
> .card-block{
>   height: 100%;
> }
> ```
> 
> This will automatically push the footer to bottom, and also card-footer border will be on the right place.

thank you @Yorer

**Comment by bekwam** [comment]
.card-block didn't work for me, but using .card-footer did

`.card {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.card-content {
    height: 100%;
}`

**Comment by jschouwstra** [comment]
> Stupid question! The answer is too simple:
> 
> ```css
> .card {
>   height: 100%;
> }
> ```

I don't think you should call someone stupid regardless of the question.

**Comment by noraj** [comment]
> I don't think you should call someone stupid regardless of the question.

Unless the guy who asked was himself...

**Comment by ervan-silvert** [comment]
> This will push your footers to the bottom.

Oh no, I lost time figuring out there is a typo in your sample, this is ` card-footer`  instead of `cart-footer` haha

**Comment by mooperd** [comment]
I'm not able to get this working with: 

```
.card {
    height: 100%;
    display: flex;
    flex-direction: column;
  }
  
.card-content {
      height: 100%;
  }
```

Can anyone give me a pointer on how to do this with card footer?


![image](https://user-images.githubusercontent.com/3006149/124283782-93498b00-db4c-11eb-87ff-9e747586c054.png)

**Comment by mindtonic** [comment]
@l2aelba & @rogierborst

Bulma friendly naming convention for sass:

```
.is-equal-height
  display: flex
  flex-direction: column
  height: 100%

  .card-footer
   margin-top: auto
```

Works like a charm!
