### ISSUE TITLE
Dynamic multi line Tiles ?

### ISSUE THREAD

**Issue by MrJohnDo** [jgthms/bulma#2185]
First of all, Tiles is fantastic addition. I want a code sample on creating multi line titles.

**Comment by jgthms** [comment]
What do you mean?

**Comment by MrJohnDo** [comment]
I'm trying to create multiline tiles for a pintrest type layout. The problem I'm having is the tiles are placed horizontally and go off the page. I need them to wrap onto the next line. I can't seem to find anything in the docs:

Here's my code (copied from the docs). The items will be pragmatically inserted.

div class="tile is-ancestor">
    <div class="tile is-parent">
      <div class="tile is-child card is-6">
        <p class="title">One</p>
      </div>
      <div class="tile is-child card is-6">
        <p class="title">Two</p>
      </div>
      <div class="tile is-child card is-6">
        <p class="title">Three</p>
      </div>
      <div class="tile is-child card is-6">
        <p class="title">Four</p>
      </div>
    </div>
  </div>
I've tried is-multiline but it doesn't seem to work.

**Comment by MrJohnDo** [comment]
> div class="tile is-ancestor">
>     <div class="tile is-parent">
>       <div class="tile is-child card is-6">
>         <p class="title">One</p>
>       </div>
>       <div class="tile is-child card is-6">
>         <p class="title">Two</p>
>       </div>
>       <div class="tile is-child card is-6">
>         <p class="title">Three</p>
>       </div>
>       <div class="tile is-child card is-6">
>         <p class="title">Four</p>
>       </div>
>     </div>
>   </div>
> I've tried is-multiline but it doesn't seem to work.

**Comment by MrJohnDo** [comment]
https://stackoverflow.com/questions/52129373/bulma-tiles-not-breaking-onto-the-next-line
