### ISSUE TITLE
Add bulma-helpers to Extensions page

### ISSUE THREAD

**Issue by jmaczan** [jgthms/bulma#2190]
This is about **the Docs** - Extensions page.

### Description

There are no helpers in Bulma for functional / atomic css, e.g. spacing, sizing and so on, so I created a standalone library which supplements Bulma with classes such as _has-margin-5_ or _has-width-10_. You can add the library link to the Extensions page.

Link: https://github.com/jmaczan/bulma-helpers

Greetings,
jm

**Comment by jgthms** [comment]
Nice! Can you make a PR to add it to the Readme?
