### ISSUE TITLE
columns class is sized in unexpected way

### ISSUE THREAD

**Issue by atavistock** [jgthms/bulma#2197]
This is a bug (or at least unexpected behavior) in Bulma.   Previous bug was filed as https://github.com/jgthms/bulma/issues/534 , but that was dismissed as a multiline issue.  I have the same problem with a single line specifically when within a panel.

I would expect `columns` in the following html to span the entire width of the `panel-block`:

```
<div class="panel is-fullwidth">
  <a class="panel-block" href="/item/615781e2-001a-4971-8447-895b627c2857">
    <div class="columns">
      <div class="column is-8">This is just an example</div>
      <div class="column is-4">Added 10:29pm, Oct 27th</div>
    </div>
  </a>
</div>
```

The actual output looks like this:

<img width="990" alt="screen shot 2018-10-28 at 6 58 39 pm" src="https://user-images.githubusercontent.com/22277/47625829-c6f2ce00-dae4-11e8-9e43-3b5ba2edec05.png">

I can 'fix' the problem by explicitly setting `style="width: 100%"` to the columns div and that resolves the problem, which now has output that looks like this:

<img width="992" alt="screen shot 2018-10-28 at 6 59 41 pm" src="https://user-images.githubusercontent.com/22277/47625855-ef7ac800-dae4-11e8-8c02-2120fade15a8.png">

I can certainly add something like `.panel-block .columns { width: 100% }` but it seem unexpected and  like other people might run into the same problem (and I guess https://github.com/jgthms/bulma/issues/534 already did).

**Comment by atavistock** [comment]
Also an interesting observation, if I make sure there is content filling in the first column, it renders properly without specifying width.   Heres an example:

<img width="695" alt="screen shot 2018-10-28 at 7 16 22 pm" src="https://user-images.githubusercontent.com/22277/47626035-3ae1a600-dae6-11e8-9316-7b22ac82ae47.png">

**Comment by emkajeej** [comment]
The panel component is typically used for navigation or control purposes, with the .panel-block being a panel's item and not a container.
Deviating from this might indeed show some interesting results. Are you sure you are needing the .panel component in this case?

You can fix this by either changing the .panel-block's display from `flex` to `block` (either by css or by the `.is-block` class), or by adding `flex: 1;` to `.panel-block .columns`.

**Comment by atavistock** [comment]
@emkajeej this is for navigation purposes.    Also adding `is-block` doesn't seem to change the behavior at all.  🤷‍♂️

**Comment by atavistock** [comment]
I have found that its super inconsistent.  I just tried using `columns` within in a `card-content` element and it __does__ behave per the documentation, but using it in a `card-footer` it __does not__.

I guess I'm expecting `columns` to behave in more or less the same way everywhere, filling the width of the containing element as the documentation shows.  If someone is asking for`columns` and defining some ratio of 12 columns is there any case where the expectation should be that its really just a bunch of stuff jammed up to the left with a random amount of negative space on the right?

**Comment by mahmoud-mamdouh-matwaly** [comment]
The reason for this problem is that .panel-block take(display: flex) and inside this panel-block one element this element  .columns In nature it appears this way. and same thing at problem #534 ... fix this bug add [ .columns: flex-grow: 1; ] So .columns take full width of the panel-block.
