### ISSUE TITLE
Contributing is a pain

### ISSUE THREAD

**Issue by cyrilchapon** [jgthms/bulma#2198]
# What I was expecting
`git clone [url] && cd bulma && npm install && npm run dev`

# What I got instead

## Installation

- cloned the repo
- `npm install`
- `cd docs && npm install`
- `brew install ruby`
- `gem install jekyll`
- Error message, ruby sucks with SSL blablabla
- Don't have time for this
- `gem sources --remove https://etc.. && gem sources -a http://etc..`
- `gem install jekyll`
- Error message, gem sucks with urls
- Don't have time for this
- `gem sources --remove http://etc.. && gem sources -a http://etc../` (with a trailing slash at the end)
- `gem install jekyll`
- Error message, ruby sucks with user permissions blablabla
- Don't have time for this
- `sudo gem install jekyll`

## Configuration

- `cp _config.yml _config.local.yml`
- Edit the url to http://localhost:4000

## Running the stuff

Shell session 1)
- `npm start`

Shell session 2)
- `cd docs && npm start`

Shell session 3)
- `cd docs && jekyll serve --incremental --config _config.local.yml`

# Testing the stuff

- Open browser to http://localhost:4000
- Error message, ruby sucks with network interfaces
- Don't have time for this
- Open browser to http://127.0.0.1:4000
- Page shows but I get 404 for every images / vendor / css / lib

As a result, I have
- 4 **shell opened shell sessions**
- **nothing is working**
- **now way to test my contribution**

Come on, it's almost in 2019 and I just lost 1 hour in installing stuff like people did in 1998 with PHP. That's insane, I was full of motivation to address an issue and that simple fact almost disgusted me to do so. I'm not very brave at it, I confess, but come on, this is a 30k stars repo, can do better.

EDIT: And the funniest part is that bulma in itself installs and compiles greatly, fastly, with 2 node.js commands. That time-and-effort-killing dependency is introduced only to build a static website. Bazooka to kill a fly welcome, except the bazooka basically doesn't work.

**Comment by jgthms** [comment]
There have been 235 contributors so far. I'm pretty sure contributing is easier than think 😉 

I'm developing for Bulma on different machines and have rarely had any issue. It seems it's mostly related to ruby itself, not Bulma.

In order to contribute to the **framework**, you don't necessarily need to run the **documentation website**. In which case, you don't even need ruby. And fixing a typo in the docs only requires to edit some Markdown or HTML file, without running the website.

There's a `README.md` in the docs folder. Maybe you want to edit it to explain what steps were missing?

**Comment by cyrilchapon** [comment]
> I'm pretty sure contributing is easier than think

I gotta be stupid, but as you see, I explained my steps, they are simple.. :/

> It seems it's mostly related to ruby itself, not Bulma

Well, myself I never opted for C# to build documentation for my libs, therefore so far I haven't come to a C#-related issue in any of those libs. I'm pretty confident that's not gonna happen tomorow neither. That's a piece of joke but you get my point. Though, I never started a lib as big and critical as bulma, just telling you my opinion after running into troubles.

> In order to contribute to the framework, you don't necessarily need to run the documentation website

Well, the only way to "test your modifications", documented in README.md is precisely to "run the documentation". I wouldn't say that..

> There have been 235 contributors so far.

Well, indeed, and furthermore 235 contributors over 689 watchers, which is pretty impressive.
I might be stupid I repeat.
