### ISSUE TITLE
.is-loading on .is-grouped .control does not apply nicely to all input's

### ISSUE THREAD

**Issue by edhenderson** [jgthms/bulma#220]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [ ] I'm using Bulma **version** [0.0.26]
* [x] My **browser** is: Chrome
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [x] I am sure this issue is **not a duplicate**?

### Description

When you use `is-loading` on a grouped control, only the second (last) element picks up the styling.

For example:

<img width="673" alt="screen shot 2016-05-27 at 11 20 01" src="https://cloud.githubusercontent.com/assets/1378582/15617273/125a45ea-23fd-11e6-99fc-924566d19d61.png">

```html
<p class="control is-grouped is-loading">
    <input class="input is-medium" type="password" required="" minlength="8" maxlength="64" placeholder="Password">
    <input class="input is-medium" type="password" required="" minlength="8" maxlength="64" placeholder="Confirm Password">
</p>
```

### Steps to Reproduce

As per above.

_Expected behavior:_ Both input boxes have the spinner.

_Actual behavior:_ Only one input box has the spinner.

**Comment by matsumurae** [comment]
Why you want to use the `is-loading` in the control group instead of the reset password button? I think this is the normal behavior (if you're using for give feedback to user **after** it clicks on button).

**Comment by edhenderson** [comment]
@matsumurae This is just an example. My point is that the `is-loading` applies only to the second item.

**Comment by jgthms** [comment]
Yeah good catch. Considering an `<input>` is a self-closing element, I'm not sure if pseudo-elements work on them.

**Comment by matsumurae** [comment]
@jgthms in the w3c specification says that _::before and ::after render inside a container_. Input can not contain other elements. So, it will not work.
