### ISSUE TITLE
Bulma layout templates 

### ISSUE THREAD

**Issue by Fandangi** [jgthms/bulma#2203]
### Overview of the problem

This is about the Docs.

I need help.

### Description

Hi - great product.  I am looking for a responsive documentation template constructed on Bulma. I am happy to construct my own but wondered if there was already a skeleton / template of such.

The docs are great but this one thing I could not find. 

Any of these resources there are, or links you can give to me?

Thanks.

**Comment by jgthms** [comment]
I’m planning on creating free templates. Do you have an example of a documentation website you like?

**Comment by Fandangi** [comment]
As with everything there are many but not a perfect representative. The template would be something like the image here where:

1 = title / hero / menu
2 = Chapter list
3 = title of chapter
4 = a section - this would be where authors might want to go to column layouts etc.
5 = paragraphs
6 = image
7 & 8 = links, calls to action, ads, etc.

Should be responsive, of course.

![image](https://user-images.githubusercontent.com/16245859/47716914-fe27c300-dc3b-11e8-9307-9df507716899.png)

**Comment by diomed** [comment]
@Fandangi are you aware of **Bulma Templates** repository?

https://dansup.github.io/bulma-templates/templates/cheatsheet.html
has the basic look of what you need, I believe.

**Comment by Fandangi** [comment]
Thanks @diomed - going in the right direction. How far down the road is this ?

**Comment by diomed** [comment]
this is starter template, upon which you could build, if you know how to code with bulma.

**Comment by Fandangi** [comment]
Thanks - I can code html, just trying to judge how far advanced it is. I guess my issue is not the coding of html, its that I'm about as capable a designer as a chocolate tea pot. I quite like the styling applied in the bulma-docs-min.css file - I have been using the bulma site as a learning resource for bulma.
