### ISSUE TITLE
Vertical nav bar component?

### ISSUE THREAD

**Issue by Fandangi** [jgthms/bulma#2204]
This is about Bulma.

It is a question

I am looking for some pointers on how to tackle this:  My design has a 2 col layout with a table of contents column set as is-one-quarter and the main doc column as is-three-quarters. The design says at mobile size, the left hand col should become a fixed width with the content hidden but with an icon at the top which when clicked expands the container so that the table of contents is visible. 

Pretty much a vertical nav bar, burger at top, when clicked exposes contents. 

I tried hacking something with the nav bar component but I feel it is becoming clunky and there must be a better way. 

I realise this will need some JS which is no problem but I want to use Bulma in its pure form as far as possible.

If not a quick solution, could this be the basis of a new component request ?

**Comment by yfchild** [comment]
Hi Emkajeej,

Can you put an example please? Would be fine. I try what you comment but not succes. TX

**Comment by yfchild** [comment]
Hi Emkajeej,

Can you put an example please? Would be fine. I try what you comment but not succes. TX

**Comment by emkajeej** [comment]
https://codepen.io/anon/pen/qQKzro

Sloppy css but it gets the point across.
