### ISSUE TITLE
Pages are allowed be be dragged/moved horizontally on ios 12

### ISSUE THREAD

**Issue by joevandyk** [jgthms/bulma#2209]
The bulma homepage at https://bulma.io/ allows me to drag the page left and right on mobile (iOS 12.1). 

![a6109190-4476-4f67-8375-5aaee54a358d](https://user-images.githubusercontent.com/1179/47790336-1f3bf280-dcd4-11e8-83ad-18a5392a0af6.png)

However, the documentation index at 
https://bulma.io/documentation/ doesn’t have that problem. 

Why is that? Is it possible to prevent the page from being dragged horizontally? Our website has the same problem.

**Comment by jgthms** [comment]
That’s weird. It doesn’t happen on iOS 11.

**Comment by voordev** [comment]
Just checking this today, on ios public beta 12.1.1 it does not happen.
