### ISSUE TITLE
Bulma logo in SVG

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#2210]
Hi Jeremy,

where can I find the Bulma logo in SVG ?
It could be great, in addition to the "made with bulma" badges to have the official logo (with and without name) available.

Regards

**Comment by jgthms** [comment]
The icon is available here: https://github.com/jgthms/bulma/blob/master/docs/_includes/svg/bulma-b.svg

**Comment by Wikiki** [comment]
Thanks. I didn't see it.
