### ISSUE TITLE
Non configurable .navbar-menu box-shadow

### ISSUE THREAD

**Issue by cleverplatypus** [jgthms/bulma#2217]
This is about Bulma unexpected non configurable feature introduced in v0.7.2 (or possibly v0.7.1)

### Description
Upgraded to v0.7.2 because #2109

Now navbar features a non-configurable box-shadow in .navbar-menu

```
+until($navbar-breakpoint)
...
.navbar-menu
    background-color: $navbar-background-color
    box-shadow: 0 8px 16px rgba($black, 0.1)
    padding: 0.5rem 0
```
Only way to remove it seems to be

```
.navbar-menu {
    box-shadow: none !important;
}
```

### Feature request
Either make the box shadow configurable using variables or just leave it up to the designer to add it via css.

**Comment by philippeluickx** [comment]
I agree this is strange. Especially if you add a brand image, you get a weird result...

**Comment by butaca** [comment]
I'm having this issue in version 0.8.0
