### ISSUE TITLE
Suggestion: make checkbox label text non-selectable

### ISSUE THREAD

**Issue by Youdaman** [jgthms/bulma#2220]
This is about the Bulma **CSS framework**

### Description

Checkbox label text gets selected when clicked on multiple times.

### Steps to Reproduce

1. Create checkbox as per docs
2. Click label text to toggle
3. Click again on the label text

### Expected behavior

Checkbox should toggle without label text being selected.

### Actual behavior

Label text is selected.

### Suggested solution

```
// sass
label.checkbox
  -webkit-user-select: none
  -moz-user-select: none
  -ms-user-select: none
  user-select: none   
```

**Comment by k-j-kleist** [comment]
recent activity
