### ISSUE TITLE
is-size-2-mobile does not works! 

### ISSUE THREAD

**Issue by aesthytik** [jgthms/bulma#2221]
This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help?
### Overview of the problem

This is about the Bulma **CSS framework

### Description

Can we use is-size-2-mobile and change the size of text in mobile view?
I tried and it is not working

### Expected behavior

The size should be responsive

### Actual behavior

Font-size doesnt change!

**Comment by tomhrtly** [comment]
Out of the box, the modifier works correctly as seen here: https://codepen.io/anon/pen/pQdqbv

What does your helpers.sass file look like?
