### ISSUE TITLE
Custom column width for specific column(s) without breaking flexbox?

### ISSUE THREAD

**Issue by voordev** [jgthms/bulma#2222]
This is about **Bulma**.
This is about the Bulma **CSS framework**

### Description

Custom column width for specific column(s) without breaking flexbox?
Is this possible?

I would want to have 1 column to be for example a fixed with of 20px, then the second column should be 100% width. 

Or 
I would like to have 3 columns with the 1st and the 3rd to be 20px but the middle fill-out.

Is there any such way to accomplish this? 
Without breaking the layout flexbox and responsiveness?

```
<div class ='columns'>
   <div class ='column is-1'>
   i would like this column to be exactly 20px for example
   </di>   
   <div class='column-is-10'>
   i would want this column to be maximum width 
  </div>
</div>

**Comment by jgthms** [comment]
If you want specific widths, you will have to create your own classes to have that specific value.

https://codepen.io/jgthms/pen/dQPqPy

```html
<section class="section">
  <div class='columns'>
    <div class='is-20px'>
      
    </div>
    <div class='column is-rest'>
      i would want this column to be maximum width
    </div>
  </div>
</section>
```

```css
.is-20px {
  background: tomato;
  width: 20px;
}

.is-rest {
  background: lavender;
}
```

![image](https://user-images.githubusercontent.com/1254808/47993090-87c90c00-e0e6-11e8-8700-af3e39485c8e.png)
