### ISSUE TITLE
IE11 , "hero.is-fullheight > hero-body" is not in middle center

### ISSUE THREAD

**Issue by HAKASHUN** [jgthms/bulma#2223]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]
My **browser** is: IE11
I am sure this issue is **not a duplicate**?

### Description

"hero.is-fullheight > hero-body" is not in middle center on IE11.

### Steps to Reproduce

```html
<section class="hero is-success is-fullheight">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Fullheight title
      </h1>
      <h2 class="subtitle">
        Fullheight subtitle
      </h2>
    </div>
  </div>
</section>
```
This issue can be found in the "Fullscreen vertical centering" section of https://bulma.io.

### Expected behavior

![2018-11-06 18 28 12](https://user-images.githubusercontent.com/1150412/48055281-8e44aa00-e1f2-11e8-9152-644c11f8157f.png)

### Actual behavior

![2018-11-06 18 27 15](https://user-images.githubusercontent.com/1150412/48055297-9997d580-e1f2-11e8-8fab-75ffc43b515a.png)

**Comment by tomik23** [comment]
Adding height: 100vh to hero-body fixes the problem with IE11 and IE10
<style>
    .hero.is-halfheight .hero-body,
    .hero.is-fullheight .hero-body,
    .hero.is-fullheight-with-navbar .hero-body {
      align-items: center;
      display: flex;
      height: 100vh;
    }
</style>

**Comment by ivanjeremic** [comment]
the issue still exists the above solution is not working anymore.
