### ISSUE TITLE
Font-size in "em" by default

### ISSUE THREAD

**Issue by hmaesta** [jgthms/bulma#2226]
![bulma-1em](https://user-images.githubusercontent.com/741969/48085569-c8f21680-e1e1-11e8-9f5b-edc85a0b5b33.gif)

Left: `$body-size: 16px` /  Right: `$body-size: 1em`

-----

By default, `$body-size` is `16px`. A fixed pixel size used as base for the whole framework.

16px corresponds for the `medium font-size` on Chrome, so if user uses default settings, no difference is visible.

But for users that have special needs and uses another size setting, (probably) all websites powered by Bulma are not accessible.

I am using  `$body-size: 1em` for a while and haven't notice any problem. **So, why isn't this the default value?**

I know that this can be easily changed, but... No one does – and them a lot of people have to manually Zoom In and break the user experience. (OK, maybe not _sooo_ many people, but everyone matters and accessibility must be taken in consideration).

**Comment by diomed** [comment]
umm... make a pull request ⁉️

**Comment by hmaesta** [comment]
I didn't because maybe something (a math calc, for example) need this value in `px`.
I haven't found any problem so far, but I think a more robust test should be made.

@jgthms Can you think any implications this may cause?
