### ISSUE TITLE
Add columns padding for tablets

### ISSUE THREAD

**Issue by PinkyRabbit** [jgthms/bulma#2228]
Hello! This is about Bulma. I need help. I try to make electron app with `800px` width. Columns has no paddings but I need paddings... How I can fix this in sass? Thank you!

**Comment by jgthms** [comment]
Add another div with some padding? I’m not sure I understand.

**Comment by PinkyRabbit** [comment]
@jgthms what class must have a child div?

**Comment by jgthms** [comment]
The column? I’m not sure what you need.

**Comment by PinkyRabbit** [comment]
`column` inside `column` works! Great!
```
  <div class="columns">
    <div class="column">
      <div class="column">
        <div class="field">
          <div class="control">
            <input class="input is-info" type="text" placeholder="Имя текущего проекта">
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      Second column
    </div>
  </div>
```
