### ISSUE TITLE
Lighter Backgrounds [suggestion]

### ISSUE THREAD

**Issue by diomed** [jgthms/bulma#2230]
This is about **Bulma**.

It would be really nice if we could use these colors as lighter backgrounds by default:
I also envisioned these being available as background for **tags**

### Overview of the problem

![91833abd-7298-4f59-a194-5e40bb636d92](https://user-images.githubusercontent.com/72777/48305136-ac2d4a00-e525-11e8-9f32-91ee66d9083c.png)

**Comment by diomed** [comment]
bump!
I will not let this die

**Comment by jgthms** [comment]
I’m actually planning on having them globally available yes. They’ll be computed as `$blue-light` the same way `$blue-invert` is computed.

**Comment by diomed** [comment]
lovely. looking forward to it.

**Comment by jgthms** [comment]
As of 0.8.0 they’re set as global variables. So they could be added as helpers. Reopening.

**Comment by diomed** [comment]
thanks. we need this.

**Comment by diomed** [comment]
any further news on this?

**Comment by jgthms** [comment]
`has-background-primary-light` and others will be available in the next release
![localhost_5000_documentation_helpers_visibility-helpers_ (1)](https://user-images.githubusercontent.com/1254808/81509285-5c3d6800-9301-11ea-8755-9f923418b3d9.png)
.
