### ISSUE TITLE
Disable scroll on body when modal is opened[Question]

### ISSUE THREAD

**Issue by labtocat** [jgthms/bulma#2235]
Hey, can someone guide me how to disable scroll for the body once modal is active for Bulma?

**Comment by jgthms** [comment]
Add `is-clipped` to the html element.

**Comment by labtocat** [comment]
@jgthms actually this is not solving my issue, Just to add context I am using Vue with Bulma
`https://siongui.github.io/2018/09/27/vuejs-bulma-modal/` here is an example of my issue.

click on the model -> goto `modal-background` area scroll (now you can see the background scrolling)

**Comment by Dan-Do** [comment]
> @jgthms actually this is not solving my issue, Just to add context I am using Vue with Bulma
> `https://siongui.github.io/2018/09/27/vuejs-bulma-modal/` here is an example of my issue.
> 
> click on the model -> goto `modal-background` area scroll (now you can see the background scrolling)

Hello @labtocat, did you solve this?

**Comment by Tarlan** [comment]
I use JS solution, not sure all browsers are good with that.
```css
body.has-modal {
  overflow: hidden;
  position: fixed;
}
```
After opening modal add class .has-modal to body. After closing remove this class. But next problem is that body scroll position is loosing. So remember scroll position somewhere before adding this class. In my case I use Vue with Vuex (probably not good practice is manipulating DOM in store, but it just for example):
```js
// Remembering body scroll position anywhere
if (typeof window.pageYOffset != 'undefined') {
    state.scrollPosition = window.pageYOffset;
}
else if (typeof document.compatMode != 'undefined' && document.compatMode != 'BackCompat') {
    state.scrollPosition = document.documentElement.scrollTop;
}
else if (typeof document.body != 'undefined') {
    state.scrollPosition = document.body.scrollTop;
}
document.body.classList.add('has-modal');
```
And restore this position after removing this class.
```js
document.body.classList.remove('has-modal');
// Restoring body scroll position
if (state.scrollPosition) {
    document.documentElement.scrollTop = state.scrollPosition;
    document.body.scrollTop = state.scrollPosition;
}
```
Not tested.
