### ISSUE TITLE
Turn on indents for tablet

### ISSUE THREAD

**Issue by PinkyRabbit** [jgthms/bulma#2237]
This is about Bulma. This is a question and I need help =) Not a bug. In [that topic](https://github.com/jgthms/bulma/issues/2228) I asked how to make indents for tablet.  And in the topic, to make indents on tablet, we nested `.column` inside `.column`. That works fine with single line grid. But now i need `multiline` columns like `column is-two-thirds`. Please look how it is now:

------------
1. Just a casual markdown `.column` inside `.columns` 
```html
<template lang="html">
  <div class="columns">
    <div class="column">
      <div v-for="one in news">
        <section>
          <h1><a href="one.link">{{one.title}}</a></h1>
          <p>{{one.description}}</p>
          <p>{{one.date}}</p>
        </section>
      </div>
    </div>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/11446934/48650299-a4c6de80-ea06-11e8-8d77-b140bfe97266.png)
Just no indents

------------
2. If I will make `.column` inside  `.column` inside `.columns` indents will works:
```html
<template lang="html">
  <div class="columns">
    <div class="column">
      <div class="column">
        <div v-for="one in news">
          <section>
            <h1><a href="one.link">{{one.title}}</a></h1>
            <p>{{one.description}}</p>
            <p>{{one.date}}</p>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/11446934/48650535-a80e9a00-ea07-11e8-8b5e-5a4743811ce9.png)

------------
3. if I make standard markdown ( `.column` inside `.columns` ) and `is-multiline` plus `is-half`
```html
<template lang="html">
  <div class="columns is-multiline">
    <div class="column is-half" v-for="one in news">
      <section>
        <h1><a href="one.link">{{one.title}}</a></h1>
        <p>{{one.description}}</p>
        <p>{{one.date}}</p>
      </section>
    </div>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/11446934/48650512-8b726200-ea07-11e8-986d-fcf8de436506.png)
But there is **no indents** and it is my problem!

------------
4. If i'll try use a trick  `.column` inside  `.column` inside `.columns` indents will show up, but all markdown will broken.
```html
<template lang="html">
  <div class="columns is-multiline">
    <div class="column">
      <div class="column is-half" v-for="one in news">
        <section>
          <h1><a href="one.link">{{one.title}}</a></h1>
          <p>{{one.description}}</p>
          <p>{{one.date}}</p>
        </section>
      </div>
    </div>
  </div>
</template>
```
![image](https://user-images.githubusercontent.com/11446934/48650649-2408e200-ea08-11e8-9ec2-c6b260ca831b.png)

------------
When I started to use that trick with grid ( `.column` inside  `.column` inside `.columns` ) I guessed that this is a wrong way, but didn't know how to make it better. So. My question one more time. I have an application with `800px` width. How I can obtain indents on sides of `.column` in my app? Thank you!

**Comment by PinkyRabbit** [comment]
Sorry. Maybe its because I'm new with bulma. I wrap my `columns` into `section` and all looks nice.
```html
<section class="section">
    <div class="columns">
        <div class="column">
        </div>
    </div>
</section>
```
Also I fixed `section` paddings in sass and that was easy. Thank you for awesome framework! :heart_eyes:

**Comment by jgthms** [comment]
Great!
