### ISSUE TITLE
columns is-tablet

### ISSUE THREAD

**Issue by stevensacks** [jgthms/bulma#2238]
This is about **Bulma**.

Feature

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]

### Description

Columns only have `is-desktop`. It would be really helpful if there was an `is-tablet` breakpoint, as well. `is-desktop` is too wide, and the mobile breakpoint is too narrow before they break.

**Comment by jgthms** [comment]
It exists? There’s is-tablet and is-tablet-only, the former being the default value.
