### ISSUE TITLE
Broken Icons & Outdated Version on Docs Site

### ISSUE THREAD

**Issue by mstaack** [jgthms/bulma#2239]
This is about **the Docs**:

Looking at: https://buefy.github.io/
i see an v0.6.6 Version and the Icons are broken.
![image](https://user-images.githubusercontent.com/10169509/48719620-4116fe00-ec1e-11e8-8645-f6aa80a24b06.png)

Looks like 404's for the icons at:
https://buefy.github.io/static/fonts/materialdesignicons-webfont.5cdddea.woff2

Hardrefresh & Cache Clear does not help

**Comment by jgthms** [comment]
This is an issue for this repo: https://github.com/buefy/buefy

**Comment by mstaack** [comment]
yeah sorry...i messed up :(

**Comment by jgthms** [comment]
No problem.
