### ISSUE TITLE
.button.is-large icons and texts not positioned well in anchor tag

### ISSUE THREAD

**Issue by barohatoum** [jgthms/bulma#224]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.27]
* [x] My **browser** is: Google Chrome
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [x] I am sure this issue is **not a duplicate**?

### Description

When using the class .button and .is-large on `a` tag, the text and icon are not centered vertically

_Expected behavior:_ that the text and icons are positioned vertically

_Actual behavior:_ icon and text are aligned to the top
![capture](https://cloud.githubusercontent.com/assets/1402924/15640870/77477338-260a-11e6-8d48-976ecd4c517f.PNG)

`<a href="http://binder.bflcanada.dev/en/binders/new/" class="button is-large is-fullwidth">
    <span class="icon is-small"><i class="fa fa-edit"></i></span>
    Create a new binder account
</a>`

**Comment by jgthms** [comment]
This should be fixed in the latest version.
