### ISSUE TITLE
Modularity not working as expected

### ISSUE THREAD

**Issue by hd-diegocortez** [jgthms/bulma#2240]
I'm using Bulma **version** [0.7.2]

Docs says:

> Simply import the utilities dependencies, and then the files you need directly

When I try to use `hero.sass` layout I need to import `components/navbar.sass` as well because hero is using $navbar-height variable that is declared in `components/navbar.sass`.

```
@import '~bulma/sass/utilities/all';
@import '~bulma/sass/components/navbar';
@import '~bulma/sass/layout/hero';
```

**Comment by jdriviere** [comment]
@hd-diegocortez Did you make sure to re-build Bulma using the appropriate NPM command?

**Comment by jgthms** [comment]
Ah yes, it's been fixed on `master`. This will ship with `0.7.3`.
