### ISSUE TITLE
Grid columns causing horizontal scrolling 

### ISSUE THREAD

**Issue by hd-diegocortez** [jgthms/bulma#2242]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]

### Description

I have a `hero` element that contains 3 columns, the first one `is-3` the second one is `is-6` and the last one is `is-3`. So I have 12 at the end, which must be full with 25% 50% 25% 

But at the end, I have a horizontal scrolling caused by margins in the `columns` parent. If I remove margin left and margin right everything is ok.

the final code is:

```
<section class="hero is-fullheight">
  <div class="columns">
      <div class="column is-3">
        content
      </div>
      <div class="column is-6">
        content
      </div>
      <div class="column is-3">
        content
      </div>
  </div>
</section>
```
Am I doing something wrong?

**Comment by zihotki** [comment]
Can confirm the behavior with v0.7.4

**Comment by darim92** [comment]
Can confirm too with Bulma v0.7.4

**Comment by Sogl** [comment]
Same here, 0.7.4

**Comment by james-wasson** [comment]
This seems to be an issue with the negative margins on the `.columns` container. I have a feeling that this is intended to allow the columns to be displayed "at full width" while still supporting padding **and** wrapping.

I have added a `.grid` style (PR #2567) which may fix the issue when it gets merged in

**Comment by stelabrego** [comment]
I was having the same problem! This fixed the issue for me:
`
.columns {
  max-width: 100%;
}
`

**Comment by DannyCare** [comment]
I was having the same issue whilst building my first site with Bulma. After looking at the documentation I decided to give the `.is-gapless` class a try, and it seemed to solve the horizontal scrolling overflow problem for me.

`<div class="columns is-gapless">`

I then realised for my use case I wouldn't really ever need any baked-in margins whilst using a grid system, so I added an override to the `.columns` class that basically does the job of the `.is-gapless` class.

```
.columns {
  margin-left: 0;
  margin-right: 0;
  margin-top: 0;

  &:not(:last-child) {
    margin-bottom: 0;
  }
}
```
And then I can just declare the columns class as before:
`<div class="columns">`

I'm coming from the (now abandoned) Foundation framework, and this solution for me gives a similar experience to Foundation's [XY Grid](https://get.foundation/sites/docs/xy-grid.html).

I'm not recommending this for everyone, just thought I'd share for anyone in a similar situation.

**Comment by eledwinn** [comment]
Same here, 0.9.0.

```scss
@import "node_modules/bulma/sass/utilities/_all.sass";
@import "node_modules/bulma/sass/grid/columns.sass";
```

```html
<div class="columns">
  <main class="column is-8">
    Hello
  </main>
  <aside class="column is-4">
    World
  </aside>
</div>
```

![image](https://user-images.githubusercontent.com/2124740/93627983-69531d80-f9ab-11ea-887e-893a552c4b03.png)

**Comment by ckyleda** [comment]
Still exists in 2021.

**Comment by alperdal** [comment]
Just wrap the _container_ div in a div with a _section_ class.

```html
<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column has-text-centered">
        <component-a />
        <component-b />
      </div>
    </div>
  </div>
</div>
```

**Comment by barathistvan91** [comment]
I have added the overflow-x: hidden to the body and the issue disappeared.
`<body style="overflow-x: hidden;">`
It seems work on desktop chrome mobile developer view. Is it a bad practice like the difference between the default scrolling element in different browsers? Could it be unscrollable in some browser like safari?

**Comment by powellian** [comment]
@alperdal your suggestion works - this should be written in the docs

**Comment by barathistvan91** [comment]
> @barathistvan91 tried that idea, predictably it sorted h-scroll but it actually stopped vertical scrolling for whatever reason.
It works for me from february in production (on desktop: Chrome, FF, new Edge. on mobile: Chrome). The html element has
```overflow-x: hidden; overflow-y: scroll;``` by default and it is y scrollable but the h scroll dissapeared as I expected in the above cases.
I do not experience the issue what you mention. I just cannot test on other mobile browser than chrome.

**Comment by lorenzochaudessolle** [comment]
I had the same problem but i found a solution 👍 

In the doc and precisely in the Gap parts (here  : [https://bulma.io/documentation/columns/gap/](https://bulma.io/documentation/columns/gap/) )

We find this code.
```

<div class="columns is-variable is-1-mobile is-0-tablet is-3-desktop is-8-widescreen is-2-fullhd">
  <div class="column">
    Column

  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
</div>

```

All i have to do is to use `is-gapless` on my columns ,or if we want to have the gap on desktop , just use this `columns is-variable is-0-mobile is-3-desktop`

PS : my `.columns` div is in a .`container` div

**Comment by andersou** [comment]
I have the same problem, i fix this using the mx-0 with columns class 

`
<div class="columns mx-0">
  <div class="column">
    Column

  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>
  <div class="column">
    Column
  </div>

`

**Comment by volmer** [comment]
Confirmed that the issue still exists as of latest version (0.9.4). As mentioned before, the simple steps to reproduce is to have a row of `columns` inside a `container` with a variable custom gap. So far the workaround that doesn't require custom CSS is to always define an additional `is-0-mobile`.

**Comment by MariuszDrabik** [comment]
Confirmed that the issue still exists as of latest version (0.9.4).  mx-0 fixed the problem. But this is just a overeide
