### ISSUE TITLE
why has-background-black doesn't work with npm bulma-start?

### ISSUE THREAD

**Issue by henriquepesi** [jgthms/bulma#2243]
This is about **Bulma | the Docs**.

### Overview of the problem

has-background-black not working

### Description
When I try use has-background-black or another background color doens't work, only work if I use the cdn

**Comment by diomed** [comment]
if you're having troubles with bulma-start then you should post in proper repository, dedicated to it.

as far as I see, bulma-start by default uses version 0.6.0 and hasn't been updated for more than a year. 
this could be the reason behind your problem.  however it might be - would be nice if repo was updated with current version @jgthms

**Comment by snitchedable** [comment]
You have to edit the packages.json File. In DevDependencies you find the Line:

"bulma": "^0.6.0",  (or simmiliar!)

change it to

"bulma": "^0.7.2",

save it and do a new npm install, then npm start, now he uses the newest bulma version and you can use the has modifiers who was missed before. ;-)

Kind Regards,
Marcel Hartmann
