### ISSUE TITLE
It would be useful to add an example for custom colors in documentations

### ISSUE THREAD

**Issue by service-paradis** [jgthms/bulma#2244]
This is about **the Docs**.

Missing information in the documentation.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.7.2]

### Description

This [page](https://bulma.io/documentation/customize/variables/) contains a lot of information about customizing variables. Unfortunately, it is unclear how to add custom colors.

### Steps to Reproduce

Reading the documentation page at https://bulma.io/documentation/customize/variables/

### Expected behavior

Having something along:

_In order to add custom colors, you need to customize `$custom-colors` variable_. 
ex.
```
$orange: #ff8606;
$orange-invert: findColorInvert($orange);
$custom-colors: ("orange": ($orange, $orange-invert));
```

**Comment by ryanweal** [comment]
I would add a sentence like this to the end:

Now you can use `is-orange` in your HTML.

**Comment by mobayen** [comment]
@service-paradis 
it's not a Bulma issue but CSS/SASS/SCSS
since custom colors won't override anything

**Comment by service-paradis** [comment]
> @service-paradis
> it's not a Bulma issue but CSS/SASS/SCSS
> since custom colors won't override anything

@mobayen 
I'm only suggesting to add some documentation about using custom colors in Bulma (which is working fine BTW). I'm not having any issues with it.

**Comment by duartemvix** [comment]
How do I change a basic link color defined by the class "is-active"

I just couldn't override anything following the instructions. I am creating variables before importing Bulma but they are still using the default for Bulma.

I'm using a CDN instead of any local installation of Bulma.

**Comment by mobayen** [comment]
@duartemvix 
you can not override CSS styles by setting variables...
import sass version and then you can override anything,

**Comment by alvinkonda** [comment]
Just in case someone is interested to customise Bulma with Sass here is the solution:

```
@charset "utf-8";
@import "../node_modules/bulma/sass/utilities/initial-variables";
@import "../node_modules/bulma/sass/utilities/functions";

// Your custom variables
$primary: $red;

@import "../node_modules/bulma/bulma.sass";

// Your styles
```
