### ISSUE TITLE
Box elements with long text content not breaking

### ISSUE THREAD

**Issue by karanrajpal14** [jgthms/bulma#2247]
This is about **Bulma**.

Is it about Bulma or about the Docs? --> Bulma
Is it a bug/feature/question or do you need help? --> Bug
If it's a bug, is it a browser bug? --> Nope. Same issue persists with Firefox as well.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2]
My **browser** is: Google Chrome v70
I am sure this issue is **not a duplicate**? --> It is similar to #1194 but the solution didn't work here

### Description

When I add a long string to a box, it is forcing the width of the box to extend until the content instead of breaking into multiple lines

### Steps to Reproduce

Have a look at [this](https://codepen.io/karanrajpal14/pen/QJmvMb) codepen

### Expected behavior

Content only extends until the end of the column. After which it should move to the next line.

### Actual behavior

Content does not break to the next line.

Thanks!

**Comment by ranjeetgavandi** [comment]
it's working just remove the class "is-narrow" then check it.
