### ISSUE TITLE
Pagination in Safari

### ISSUE THREAD

**Issue by kvanlierop** [jgthms/bulma#225]
The mobile styling for the pagination UL element needs to be looked at for Safari. The UL element isn't expanding to fill the entire width as it was before.

[Screenshot of Safari/Chrome comparison](https://www.dropbox.com/s/6moteek3hlvaqny/Screenshot%202016-05-30%2021.50.15.png?dl=0)

**Comment by jvanbaarsen** [comment]
@kvanlierop Can you please make sure to upload the screenshot in Github (You can do so by dragging and dropping). Since the link you provided does 404 now.

**Comment by kvanlierop** [comment]
@jvanbaarsen thanks for the note. Not a big github user and didn't realize that was an option. 

Unfortunately, the screenshot doesn't exist anymore. 

Looks like this might be addressed though, when looking at this page in Safari: http://bulma.io/documentation/components/pagination/
