### ISSUE TITLE
Gap initial variable is incorrect

### ISSUE THREAD

**Issue by wiamsuri** [jgthms/bulma#2252]
This is about Bulma.

### Overview of the problem

This is a **Sass** issue: I'm using version 0.7.2.
I think the intended gap size is 32px as initial variables says that
```
// 960px container + 4rem
$desktop: 960px + (2 * $gap) !default
```
But the gap variable is set to `$gap: 64px !default`, which makes `(2 * $gap)` = `8rem`.

### Expected behavior

Gap variable should be set to `$gap: 32px !default` to make `(2 * $gap)` = `4rem`

**Comment by jgthms** [comment]
Thanks but I’m pretty sure it’s. A duplicate. Will close this one.
