### ISSUE TITLE
Gap 64px (container horizontal gap). What exactly is it?

### ISSUE THREAD

**Issue by dkjain** [jgthms/bulma#2254]
This is about Bulma.
It is a question

### Gap 64px (container horizontal gap). What exactly is it?

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2] 

### I'm  not sure what exactly does container horizontal gap means. Is it the minimum container width. Or is it the container's horizontal gap between browser's viewport and container. Can somebody pls, show it visually to better understand this 64px gap?

I understand that a very basic question and some might think that's a stupid question but still I'd like to be enlightened. 

Thanks.

**Comment by jgthms** [comment]
More discussion here #1864
