### ISSUE TITLE
Typo in documentation example: `fas` instead of `fa` make icon render as square

### ISSUE THREAD

**Issue by roncodingenthusiast** [jgthms/bulma#2256]
This is about **Bulma | the Docs**.

 It is a bug in the documentation examples.

### Overview of the problem

This is about the Bulma **Docs** 
 I'm using Bulma **version** [0.7.2]
 My **browser** is: chrome

I am sure this issue is **not a duplicate**? 

### Description

The documentation uses class 'fas' i.e. `<i class="fas fa-home"></i>`  instead of class `fa` which makes the icons render as square in the latest bulma versions
### Steps to Reproduce

1. Copy any of the example code on the icon page into an application that uses bulma: https://bulma.io/documentation/elements/icon/
2. reload browser and observe the specific icon showing up as a square 

### Expected behavior

On The documentation of icons since font-awesome is being used, it should say: `fa fa-lock` which makes the icon render as the actual font-awesome icon

### Actual behavior

Currently on the documentation of icons it says: `fas fa-lock` which makes the icons all render as squares

**Comment by jgthms** [comment]
Screenshot? `fas` is the correct class name.
