### ISSUE TITLE
[Feature] .has-addons sizing in horizontal form

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#226]
I'm unsure if this would be logical, but I'm kinda missing the oppertunity to give control inputs a size, when having `.has-addons` as a parent in a horizontal form.

For instance, see image below. 
![Horizontal form](https://cloud.githubusercontent.com/assets/3226608/15668943/13ad0f4e-271e-11e6-8bde-78493d195cf0.png)

I'd like the zip field, to be like `.is-2`, and the rest to be expanded, maybe by using `.is-expanded`.

**Comment by jeppech** [comment]
The code for the above mentioned form is as follows: 
```html
<div class="control is-horizontal">
    <div class="control-label">
        Name
    </div>
    <div class="control">
        <input class="input is-small" type="text" placeholder="Name" />
    </div>
</div>
<div class="control is-horizontal">
    <div class="control-label">
        Address 1
    </div>
    <div class="control">
        <input class="input is-small" type="text" placeholder="Address 1" />
    </div>
</div>
<div class="control is-horizontal">
    <div class="control-label">
        Address 2
    </div>
    <div class="control">
        <input class="input is-small" type="text" placeholder="Address 2" />
    </div>
</div>
<div class="control is-horizontal">
    <div class="control-label">
        Zip/city
    </div>
    <div class="control has-addons">
        <input class="input is-small" type="text" placeholder="Zip"/>
        <input class="input is-small" type="text" placeholder="City" />
    </div>
</div>
```

**Comment by jeppech** [comment]
Would it make any sense, if we'd use the `is-NUMBER` modifier here, to control the size? Kinda like the workaround @gmann1982 posted in #434

Note the work around does not work for controls having `has-addons` modifier.

**Comment by jeppech** [comment]
Actually, removing `width: auto` of the `has-addons` childs, seems to be correctly sizing them, according to their parent container.

**Comment by jgthms** [comment]
This is possible in 0.4.0
