### ISSUE TITLE
[Question] Vertically center form between navbar and sticky footer

### ISSUE THREAD

**Issue by nullbio** [jgthms/bulma#2266]
Not too sure where to post questions like this, so if there's somewhere better please let me know.

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.7.2]
My **browser** is: Chrome, Firefox

### Description

Trying to figure out how I can vertically and horizontally align a sign up form inside a container between the navbar and a sticky footer. The closest I got would cause the footer to overlap the form at small browser heights, and would cause the form to go underneath the navbar and be hidden by it. So I've ditched that and recreated the basic building blocks of what I'm trying to accomplish, but without the vertical/horizontal center align piece that I'm missing:

https://codepen.io/anon/pen/JeqeoO

I'm stuck on how to maintain this resize functionality but also center that box and its header to the middle of the page. To see what I mean about resizing, you can drag the middle divider down and see that the form will push the footer down, and it won't get overlapped by the navbar. This is perfect, I just need to vertically/horizontally center the "centered-box-wrap" div now.

**Comment by emkajeej** [comment]
Get rid of the CSS.
Wrap everything in `div.hero.is-fullheight`.
Wrap your `nav` element in `div.hero-header`.
Wrap your `.container` in `div.hero-body`.
Wrap your footer in `div.hero-footer`.

Basically this: https://bulma.io/documentation/layout/hero/#fullheight-hero-in-3-parts
Is this the result you are trying to achieve?

**Comment by nullbio** [comment]
@emkajeej Thank you, and sorry for such a late response, I've been in holiday mode. Did what you suggested and that does indeed appear to be what I'm after for the most part, thank you. The only thing that doesn't seem to work is setting the is-primary on the navbar (it doesn't pick up the color). As a result, I guess I can do overrides like the following: https://codepen.io/anon/pen/BMaLpp -- but if you have a better/cleaner way of fixing this I'd love to know. If I put is-primary on the hero section it wraps the center section with that color, as you would expect because it's a hero now. I also wonder what other implications this might have later on (using a hero as a bit of a hack to get these positioning attributes). Thank you.
