### ISSUE TITLE
Graduate is-fullwidth to a first-class citizen

### ISSUE THREAD

**Issue by kaidjohnson** [jgthms/bulma#2267]
This is about **Bulma**.

### Overview 

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.2]

I am sure this issue is **not a duplicate**, but it's related to https://github.com/jgthms/bulma/issues/938

### Description

`.is-fullwidth` appears to be used only as a modifier to some element classes (.button, .input, .text-area, etc)

it would be nice to have
```
.is-fullwidth {
  width: 100%;
}
```

for use anywhere (without requiring another class).

Similarly,

```
.is-fullheight {
  height: 100%;
}
```

Incidentally, the core CSS library would likely be able to be a touch smaller in size, as some of the modifier combinations could be removed in favor of the global application of `.is-fullwidth`

Thanks for the work you're doing here. Really enjoying Bulma in its simplicity and elegance!

**Comment by tomhrtly** [comment]
Should the `is-fullheight` modifier be `height: 100vh` instead? The hero uses this instead of `height: 100%` and it maybe confusing if the global modifier is different to the hero modifier under the same name.

**Comment by kaidjohnson** [comment]
Having `is-fullheight { height: 100vh }` and `is-fullwidth { width: 100% }` together would be inconsistent and thus confusing. It's important that the modifiers are both either relative to the parent or relative to the viewport, but not a mix of each.

Given `is-fullwidth` has several use-cases as `{ width: 100% }` already, I recommend `is-fullheight` be defined as `{ height: 100% }` for parity.

The hero `is-fullheight` currently sets `min-height: 100vh`. This is probably fine if `is-fullheight` is set to `height: 100%` as the definitions won't (necessarily) conflict with each other. Given it's a singular use-case at the moment, there's probably room to get this right (eg rename the hero modifier `is-viewheight`, for example) before it becomes one of those odd inconsistencies in the library. The `is-fullwidth` already has far more use-cases and would be a much harder change to make at this point.

**Comment by jgthms** [comment]
In some cases, the `is-fullwidth` won't work. Also, some users might expect it to be the whole width of the viewport, others of only the container. But in most cases it could work I guess.

The `is-fullheight` is going to be too problematic to become a helper though.
