### ISSUE TITLE
.button.is-white becomes .button.is-#fff

### ISSUE THREAD

**Issue by dominicrico** [jgthms/bulma#227]
In bulma.css for example the `.button.is-white` is correct but in the minified version all `.is-white`, `is-black`, ... is converted to `is-#fff`, `is-#000`, ... 

You should check the minifier settings to prevent that.

**Comment by jgthms** [comment]
Argh, damn minifier. Thanks for pointing that out.

**Comment by dominicrico** [comment]
You're welcome ;)

**Comment by paul002** [comment]
I have challenges with browser compatibility with bulma, can somebody give me a clue on how to handle this one?

Your help will be highly appreciated

**Comment by muodov** [comment]
I've just stumbled upon this issue with the latest (0.3.1) release. Is it a regression, or does it also depend on other packages?..

**Comment by muodov** [comment]
After looking at the fix commit, I understand I need to add `?outputStyle=expanded` to sass-loader config. It seems to work, but I find it quite hacky. @jgthms any chance to make bulma independent of this parameter?

**Comment by quagliero** [comment]
Depending on what your build process does in terms of minification, this issue still can still arise when you compile your own version of bulma (either as a plain 'ol import of bulma.sass, or a collection of modules). 

Literally wrapping the names in quotes to declare them as static strings will fix this.
