### ISSUE TITLE
Issue Getting Html page To Reference Bulma

### ISSUE THREAD

**Issue by johnchendev** [jgthms/bulma#2270]
This is about Bulma

Bulma

### Overview of the problem

Hi guys, I'm having trouble getting my site Header to recognise Bulma.

### Description

1. I installed Bulma via npm at my project root folder
2. Bulma was installed properly, and all the files were uploaded to my project.
2.1: I'm currently using Codekit app via Mac to watch the code for Sass (Codekit is ignoring the node_modules for some reason - due to performance issues)
3. However, I tried referencing to Bulma via the the following code: 

`<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>This is a title</title>
    <link rel="stylesheet" type="text/css" href="/node_modules/bulma/css/bulma.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
`
Reloaded the page, and it didn't work. When I went to the page, I saw that the link could not be found, so I'm pretty sure it was something wrong that I did there.

Thank you all in advance!

**Comment by mobayen** [comment]
@johnchendev the piece at the end of your post is not what supposed to be
you need to include bulma.css

> https://cdnjs.com/libraries/bulma
