### ISSUE TITLE
`disabled` isn't an attribute on `label`

### ISSUE THREAD

**Issue by dfee** [jgthms/bulma#2271]
This is about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**

### Description
`disabled` is not an attribute on a `label` element.

### Steps to Reproduce
Specify `disabled` on a the `label` element of (e.g.) a radio button.

### Expected behavior
`is-disabled` is a class on a label element.

### Actual behavior
`disabled` is an attribute not a class.

**Comment by dfee** [comment]
I should note that this makes using this attribute impossible with a tool like React which strips away unknown attributes: https://reactjs.org/warnings/unknown-prop.html

> ... React currently strips all unknown attributes, so specifying them in your React app will not cause them to be rendered.

**Comment by dfee** [comment]
@jgthms it's not too late to fix this before the 0.7.3 release. You just need to change:
https://github.com/jgthms/bulma/blob/8b60a4939379531b0a951e85142dbf12eba906dc/sass/elements/form.sass#L141 to a class (i.e. `is-disabled`).

**Comment by dfee** [comment]
Any interest in fixing this for 0.7.6?

**Comment by james-wasson** [comment]
I don't think we can just **remove** features others might have already implemented. 
**However** that's not to say we can't extend this to add that functionality.
I will put up a pull request with these changes

**Comment by ymtszw** [comment]
This is also true for `a`.
Bulma started to use `disabled` attributes for disabling "link buttons" (in the course of fixing `button`-disabling, see an issue below) but it is not a valid usage of `disabled`.
https://github.com/jgthms/bulma/issues/276#issuecomment-325207050
Related: https://github.com/jgthms/bulma/issues/885
