### ISSUE TITLE
Feature request - Cheatsheet

### ISSUE THREAD

**Issue by Kehino** [jgthms/bulma#2272]
This is about the Docs.

### Overview of the problem

This is about the Bulma **Docs**.

I am sure this issue is **not a duplicate**.

### Description

A *cheatsheet*, or a list with all the classes, including helpers and modifiers, the whole thing on one page, would be a good addition. I miss the overview of the whole Bulma framework.

**Comment by mobayen** [comment]
a cheat sheet that has a list of all classes with a short description would be nice so we can do a quick search among them
or even better a functional search for the website!

**Comment by kamontat** [comment]
Search in website will be great.

**Comment by ShawnMilo** [comment]
Activity.

**Comment by ShawnMilo** [comment]
So, @Kehino, @imlinus, @mobayen, @kamontat: 

There are five of us. If we divide up the work we can each take a subset and submit a PR. It would help us all learn Bulma a little better. I assume that if we each want this it's because we're not familiar enough with its capabilities.

**Comment by molecula451** [comment]
This would be great!

**Comment by thangbn** [comment]
+1

**Comment by kamontat** [comment]
Please use thumb up on each comment instead of +1 which might lead to unnecessary comment. 

Thanks.
