### ISSUE TITLE
Horizontal nav menu on tablets

### ISSUE THREAD

**Issue by nancywh** [jgthms/bulma#2275]
This is about Bulma.

### Description

I'm trying to get the nav menu to remain as is on tablets, rather than switching to a dropdown style. I can't find this in the docs and experimentation with breakpoints etc is not getting me anywhere.

### Expected behavior

I would like the nav bar to remain horizontal on tablet width screens. Actually, I have different mobile page so it should really remain horizontal no matter what screen width it is.

### Actual behavior

It switches to the dropdown style on tablet width screens.

**Comment by jgthms** [comment]
I believe this is a dupe. There’s a ticket open for customisable breakpoint.
