### ISSUE TITLE
Are Bulma Lists usable?

### ISSUE THREAD

**Issue by BobWalsh** [jgthms/bulma#2276]
This is about ** the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description

I found https://bulma.io/documentation/components/list/ from https://github.com/jgthms/bulma/pull/1720 which seems to be semi-implemented in the docs (not is list of Components). Is it available to use?

### Expected behavior

Bulma does a list of list-items. List item text properly wraps within the list item.
### Actual behavior

List item text extends beyond the list-item in mobile view, breaking the UX pattern.

![cursor_and_devshortcuts](https://user-images.githubusercontent.com/5097/49701566-d7e23500-fba2-11e8-8e79-a7f6357c7560.png)

**Comment by jgthms** [comment]
Not yet. And it actually looks too similar to the panel so I’m not sure if it’ll stay in this form.
