### ISSUE TITLE
Unclear or incorrect documentation - missing "_sass/main.scss"

### ISSUE THREAD

**Issue by pkbarbiedoll** [jgthms/bulma#2279]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

I'm using Bulma **version** [0.7.2]

### Description

After installing via npm, I am unable to locate this referenced file in the README.md:  `_sass/main.scss`

### Steps to Reproduce

1) Downloaded the current version archive from bulma.io
2) Extracted to /docs/web/bulma-0.7.2/
3) Opened terminal and `cd /docs/web/bulma-0.7.2/` 
4) Followed instructions from the **Try it out!** section: 
4) Issued npm install (no errors appeared)
    added 383 packages from 383 contributors and audited 3794 packages in 8.212s
    found 0 vulnerabilities
5) Issued npm start
6) **Unable to locate /docs/web/bulma-0.7.2/_sass/main.scss** to test changing background color. 

### Expected behavior

After installing via npm install, I expect to find files that are included in the README.md help file.  

### Actual behavior

The _sass folder and subcontents were not created with npm install.

**Comment by mobayen** [comment]
it is main.sass (whit an A)
I guess it is a typo!!!

**Comment by mobayen** [comment]
I didn't read that page, 
just whatever it says about main.scss, it's wrong, use main.sass instead

**Comment by richardkmichael** [comment]
@pkbarbiedoll I have tried to reproduce what you are describing, but there does not seem to be a typo anywhere in the docs.  Please clarify your installation steps, and where you found the reference to `_sass/main.sass`.

- If you installed bulma using `npm install bulma`, as on the front page of bulma.io, then you should follow the [customize instructions](https://bulma.io/documentation/customize/) -- you probably want to read the [section on variables](https://bulma.io/documentation/customize/variables/).

- If you installed bulma using `npm install bulma-start`, the [documentation](https://bulma.io/bulma-start/) correctly references the `_sass/main.scss` file.

**Comment by mobayen** [comment]
@richardkmichael 
you right, the doc is fine
but he was using a wrong file in the doc directory (https://github.com/jgthms/bulma/tree/master/docs/_sass/main.scss) which doesn't exist!
