### ISSUE TITLE
does container on tablet devices have a set fixed width?

### ISSUE THREAD

**Issue by dkjain** [jgthms/bulma#2282]
This is about Bulma.
It is a question

This is about the Bulma CSS framework
I'm using Bulma version [0.7.2]

Out of the box, does `.container` on tablets has a fixed/set width like desktop which has a .container size of 960px? If yes, what exactly is it? Where is it defined in SASS files. 

I understand that a very basic question and some might think that's a stupid question but still I'd like to be enlightened.

Thanks.

**Comment by jgthms** [comment]
Yes you can see it defined in https://github.com/jgthms/bulma/blob/master/sass/elements/container.sass
