### ISSUE TITLE
vscode autocomplete class

### ISSUE THREAD

**Issue by slyang-git** [jgthms/bulma#2283]
Hey,

When I using bulma in VSCode,  it did't give any suggestion(autocomplete) of the bulma class name. I find it hard to remember some bulma class name when I am still a newbie of bulma. 

So, How to configure the VSCode to give smart suggestion of class names ? Thanks

(Maybe this issue is not relate to bulma)

**Comment by ZiFFeL1992** [comment]
I'd recomend you to use: https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion

**Comment by yoga-hz** [comment]
But Sublime Text has it.
![autocomplete bulma on sublime text](https://user-images.githubusercontent.com/30396862/51794890-a1be4a80-220e-11e9-9e49-5ca41d6b733e.png)

**Comment by maxiqboy** [comment]
Does anyone have an answer to this?

When I installed Bulma via NPM, and `import 'bulma/css/bulma.css'` via main.js file, I cannot get the autocomplete on Vscode,

In another project, when I attach Bulma CSS file directly to the project, everything works fine
