### ISSUE TITLE
bulma 0.6.1 - web site content under CC BY-NC-SA 4.0

### ISSUE THREAD

**Issue by luisapace** [jgthms/bulma#2288]
Hi, my team would like to use the package bulma 0.6.1 and to approve that I've to verify all its licenses.
Now, at https://github.com/jgthms/bulma/blob/0.6.1/docs/_includes/footer.html I read:

_**Website content licensed<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.**_

So I have to ask my team to eliminate the website content from the code (if any); could you please tell me what directories contain the Website content so I can ask to eliminate them from the code? 

Thanks for your support.

**Comment by jgthms** [comment]
Sure, all the website content is in the `/docs` folder. Just delete it.

**Comment by luisapace** [comment]
Thanks for your quick reply.
