### ISSUE TITLE
Navbar dropdown is below another navbar

### ISSUE THREAD

**Issue by eboukamza** [jgthms/bulma#2294]
This is about **Bulma**.
Is it a bug, is it a browser bug.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** 0.7.2
My **browser** is: Chrome 71

### Description

Seen in docs. When more than one navbar the dropdawn is below the other navbar.

### Steps to Reproduce

Follow link [Link to reproducer](https://bulma.io/documentation/components/navbar/#colors
) 
and mouseover on the navbar dropdown in the color section.

### Expected behavior

The dropdown is visible

### Actual behavior

Look the drowpdown in the screenshot.

![screenshot from 2018-12-24 10-19-52](https://user-images.githubusercontent.com/4034433/50395894-d69a3600-0766-11e9-9500-e5b4b25cfaf8.png)

**Comment by FragsterAt** [comment]
Just use z-index, with the max value for the first navbar and decreasing for following navbars

**Comment by eboukamza** [comment]
> Just use z-index, with the max value for the first div.navbar and decreasing for following navbars

I think dropdown should have by default a z-index greater than navbar

**Comment by abnersajr** [comment]
@eboukamza navbar has `position: relative`, so children `z-index` is "locked" to the `navbar` class.
Your desired effect can be accomplished using the suggestion of @FragsterAt. You can put different z-indexes for your navbars.

This isn't a bug. I suggest closing this issue.
