### ISSUE TITLE
How to autocomplete a searchBar?

### ISSUE THREAD

**Issue by dcalixto** [jgthms/bulma#2295]
Hello,  someone please can clarify how to autocomplete a searchbar with bulma?

in the screenshot below you can check the issue.

 version  v0.7.2

![autocomplete](https://user-images.githubusercontent.com/1009077/50454063-368e0980-092c-11e9-9c00-03cf1197154b.png)

**Comment by ZiFFeL1992** [comment]
Bulma it's just a styling library with 0 JavaScript functionality, anything you need you'll need you to build it for your self or find a third party library...

**Comment by sts-ryan-holton** [comment]
From the docs:

> CSS only, so it integrates in any JS environment

https://bulma.io/

@dcalixto 

Consider searching before opening issues.
