### ISSUE TITLE
Be able to use <button> instead of <a> for navbar hamburger

### ISSUE THREAD

**Issue by hansott** [jgthms/bulma#2298]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**.
I'm using Bulma **version** 0.7.2.
I am sure this issue is **not a duplicate**.

### Description

Be able to use `<button>` instead of `<a>` for navbar hamburger. Why? https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md

### Steps to Reproduce

Use `<button>` as navbar hamburger instead of `<a>`.

### Expected behavior

The `<button>` is styled like `<a>`.

### Actual behavior

<img width="957" alt="screenshot 2018-12-31 16 47 28" src="https://user-images.githubusercontent.com/3886384/50563400-b9dca000-0d1c-11e9-9b54-3db8bc21d7b3.png">

<img width="957" alt="screenshot 2018-12-31 16 47 42" src="https://user-images.githubusercontent.com/3886384/50563397-b6e1af80-0d1c-11e9-8b32-94d12e16593a.png">

**Comment by mobayen** [comment]
you can do so
just add `button is-white` css classes to the button

**Comment by gvdp** [comment]
@hansott Next time, you should include which browser you are using, this doesn't seem to happen in Chrome. Create a PR with a proposal for a solution once I remembered other browsers exist :-).

**Comment by hansott** [comment]
@gvdp You're right! Thought it was a global issue... Thanks for fixing.

**Comment by kekkler** [comment]
I'm seeing this issue.

**Comment by MefhigosetH** [comment]
Hi there.

I recently faced the same jsx-a11y/anchor-is-valid error. My fix was:

```
<button className="navbar-burger" aria-label="menu" aria-expanded="false" data-target="primaryNavbar" href="#">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
</button>
```

I remplaced the `<a>` element by `<button>`, remove the `role='button'` statement, and put `href='#'` at end. This changes pass the rule and keep functional the burger menu.
