### ISSUE TITLE
(Safari/Webkit) Grouped button with input field missing padding?

### ISSUE THREAD

**Issue by kherge** [jgthms/bulma#23]
It looks like a button grouped to the right of an input field loses its padding.

Not sure if this is an issue with Safari (9.0.3) or Bulma.

![screen shot 2016-01-29 at 4 49 24 pm](https://cloud.githubusercontent.com/assets/9122157/12692162/6e93ea26-c6a8-11e5-9177-d84927ae71fc.png)

**Comment by jgthms** [comment]
Mmmh that's an interesting one. Let me see if I can reproduce.

**Comment by Lanchez** [comment]
Might be cured by flex-shrink: 0 for buttons.  Safari is intensely buggy browser.

**Comment by jgthms** [comment]
@Lanchez That's a good shout actually.

@kherge could you try that (with Safari's developer console)?

**Comment by kherge** [comment]
That fixed it.

![screen shot 2016-01-30 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/9122157/12699450/11df89b6-c770-11e5-9c1c-59099d26ae83.png)

**Comment by ChuckJHardy** [comment]
I had the same issue with a line of images http://bulma.io/documentation/elements/image in safari and `flex-shrink: 0` solved it.

**Comment by kherge** [comment]
Since this is tagged as "wontfix", I'll close the issue.
