### ISSUE TITLE
[Feature] Preloader Skeletons

### ISSUE THREAD

**Issue by jdmg94** [jgthms/bulma#2300]
This is about **Bulma**.

### Overview

This is about the Bulma **CSS framework**

I am sure this issue is **not a duplicate**

### Description

Create a new Skeleton class that can be used as a placeholder for loading UIs.
The new feature could be implemented as a small refactoring of the progress bar class.

### Expected behavior

![](https://cdn-images-1.medium.com/max/800/1*Tq6CuI_IJ0kX8D2tToUeTQ.gif)

### Actual behavior

🍃

**Comment by jgthms** [comment]
This could be a modifier class for existing Bulma elements. I believe the image, the titles, the buttons could easily be implemented. For the paragraph it would need a bit of content but it should work.

**Comment by jdmg94** [comment]
I like that approach, the paragraph could have a `preloads-x-lines` class that renders the necessary breakpoints

**Comment by jdmg94** [comment]
I think it could even be a variation of the progress bar that already exists

**Comment by sira313** [comment]
hi, i am waiting for this. so cool, is this ready to use?

**Comment by mickorj** [comment]
any news?

**Comment by jdmg94** [comment]
Ok, here's an implementation that we could base this off https://codepen.io/oslego/pen/XdvWmd
we need to address the API for this feature are there are native css pseudo-elements that kinda fit the description.

**Comment by alexsandro-xpt** [comment]
May this could be a `Modifiers`? This will be a really nice feature.

**Comment by EirikFA** [comment]
Perhaps this should be re-opened?

**Comment by laurensV** [comment]
Agreed, issue should be reopened, would love to have this

**Comment by ilyamio** [comment]
Hello! Is the preloader skeletons already realized with bulma?
