### ISSUE TITLE
Level right is not well positioned at the rigth if it is the only child

### ISSUE THREAD

**Issue by eboukamza** [jgthms/bulma#2302]
This is about **Bulma**.

Is it a bug

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.2
My **browser** is: Chromium 71

### Description

When a level has only a child, and level-right is the only one, it is not well positioned at the right

    <nav class="level">
       <div class="level-right">
        <div class="level-item">level-right</div>
      </div>
    </nav>

### Steps to Reproduce

[reproducer](https://plnkr.co/edit/Jjw0nI1PJ5CdHz6XG081?p=preview)

### Expected behavior

level item is aligned at the right

### Actual behavior

It is aligned at the left

### Workarround

I have a workarround adding an empty level-item

     <nav class="level">
      <div class=level-item></div>
       <div class="level-right">
        <div class="level-item">level-right</div>
      </div>
    </nav>

**Comment by yongonyon** [comment]
I think the proper work-around would be to add an empty `level-left` item just above the `level-right`
That seems to work on your Plunker

**Comment by deepankarmalhan** [comment]
Had to do the same thing, have an empty div tag of `level-left` and that will align `level-right` elements properly.

**Comment by freitzzz** [comment]
Still not working when level-right is the only element declared.

Is this intended?

**Comment by GunnarPDX** [comment]
Try adding `.is-mobile` class to your `.level`
This will prevent Bulma from thinking your level is being viewed on mobile where it tries to horizontally and vertically align level items.

**Comment by DJPretorius** [comment]
The question still stands. Is this behaviour intended?

It feels unnecessary to have an empty level-left div just to have a single level-right div.

**Comment by Sazzo** [comment]
Same problem here, I added an empty item as described above and it worked lol

**Comment by maxailloud** [comment]
Same issue here.
At the end the class `level-right` doesn't do anything on its own, it requires a `level-left` before to actually positioned the items to the right. Doesn't seem really semantic to me.
