### ISSUE TITLE
field-label with is-normal not aligned with input checkbox

### ISSUE THREAD

**Issue by kinglau66** [jgthms/bulma#2304]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **0.7.2** 

 My **browser** is: Firefox 64.0 (64bit)

### Description

When field-label set with is-normal, the checkbox input does not aligned?

### Steps to Reproduce

1. The following code is used from the [example](https://bulma.io/documentation/form/general/#horizontal-form)
```
<div class="field is-horizontal">
  <div class="field-label">
    <label class="label">No padding</label>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <label class="checkbox">
          <input type="checkbox">
          Checkbox
        </label>
      </div>
    </div>
  </div>
</div>
```
2. `is-normal` modifier is used for `field-label`
```
<div class="field is-horizontal">
  <div class="field-label is-normal">
    <label class="label">No padding</label>
  </div>
  <div class="field-body">
    <div class="field">
      <div class="control">
        <label class="checkbox">
          <input type="checkbox">
          Checkbox
        </label>
      </div>
    </div>
  </div>
</div>
```

### Expected behavior

> ![image](https://user-images.githubusercontent.com/15945904/50672666-9499ab80-1014-11e9-87d0-7d70532e9f64.png)

Expected alignment as photo in example 
https://bulma.io/documentation/form/general/

### Actual behavior

> ![image](https://user-images.githubusercontent.com/15945904/50672654-85b2f900-1014-11e9-9b57-049cb4bc41e1.png)

Field-label is not aligned with checkbox input

**Comment by mobayen** [comment]
I confirm the 4 sizes (small, normal, medium and large) do not work well with checkboxes and radio-buttons!
