### ISSUE TITLE
Feature Request: Smaller/Denser Tables

### ISSUE THREAD

**Issue by kerbo** [jgthms/bulma#2307]
I need a table that is smaller. Smaller means smaller font size for content, less spacing between rows, etc. A smaller, denser table is needed to see more rows on a page or more columns.

Extending the "is-small" attribute to tables would be great!

**Comment by yongonyon** [comment]
The existing `is-narrow` modifier for Tables should largely handle this. It doesn't affect the font-size, however.

**Comment by emkajeej** [comment]
You can use the `is-size-*`classes on tables as well.
So a table `.is-narrow .is-size-7` should probably give you the desired result.
