### ISSUE TITLE
what template engine does bulma use to render documents?

### ISSUE THREAD

**Issue by mobayen** [jgthms/bulma#2308]
This is about ** the Docs**.

Is it a question!

### Overview of the problem
I was looking to doc files (basics.html) and find out it is not pure HTML and I didn't understand some commands! things that look like are for or if loops or variables that contains some other HTML stuff:

```{% capture columns %}```
```{% endcapture %}```
```{% highlight html %}{{ columns }}{% endhighlight %}```

so the question is what does Bulma use to render the HTML files?!

**Comment by jgthms** [comment]
That’s Liquid templates. It’s what Github Pages use.
