### ISSUE TITLE
Mobile Nav - last-child

### ISSUE THREAD

**Issue by kvanlierop** [jgthms/bulma#231]
Looks like the `padding-right` needs to be reset when the mobile nav is activated

[Click here for screenshot of issue](https://www.dropbox.com/s/st7jqp8qfuyhzdc/Screenshot%202016-06-03%2022.29.03.png?dl=0)

line reference: nav.sass:116

```
.container > .nav > .nav-right > .nav-item:last-child:not(.is-tab) {
    padding-right: 0;
}
```

**Comment by kvanlierop** [comment]
The screenshot doesn't go a great job of showing the issue, but there's no padding-right which is causing alignment issues on the last-child compared to the other child elements.

**Comment by omega** [comment]
I am running version 0.1.0 of bulma, this is about the bulma css, my browser is firefox 49

I can't see the screenshot linked above, but I think this is the same issue I am having, the `padding-right: 0;` and `padding-left: 0` on the `:not(.is-tab)` is making things go outside the container so to speak:

![attempt to display misalignment](https://dl.dropboxusercontent.com/s/a3ur80y12nq7z1k/Screen%20Shot%202016-07-19%20at%2020.48.31.png?dl=0)

if I make the `padding: 10px` in the mobile responsive section `!important` it fixes this, but the better fix is probably to adjust the styles that set `padding-right` and `padding-left` to `0` to not apply on mobile?

https://github.com/jgthms/bulma/blob/master/sass/components/nav.sass#L64 is the line that sets the padding on mobile, https://github.com/jgthms/bulma/blob/master/sass/components/nav.sass#L105-L117 sets is to `0` again
