### ISSUE TITLE
Feature request - Typeahead element

### ISSUE THREAD

**Issue by shaddu** [jgthms/bulma#2310]
This is about **Bulma**

Feature request

### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.7.2] 

### Description

I need an element which can support typeahead feature in Bulma.
Something like this https://twitter.github.io/typeahead.js/examples/ but only CSS part.

**Comment by jgthms** [comment]
The CSS is too tied to the JS but you should be able to use the drop down element or the box one for youru styling needs.
