### ISSUE TITLE
tiles bug on chrome

### ISSUE THREAD

**Issue by fundon** [jgthms/bulma#232]
# Chrome
![screen shot 2016-06-04 at 5 19 36 pm](https://cloud.githubusercontent.com/assets/27926/15798801/a5854802-2a78-11e6-9767-46a464cd646d.png)

# Safari
![screen shot 2016-06-04 at 5 19 47 pm](https://cloud.githubusercontent.com/assets/27926/15798802/acfe9ed0-2a78-11e6-90fa-9d4e7ba8d34b.png)

**Comment by idolab** [comment]
Problem:
Chromes seems to miscalculate the size of nested flexbox. [Reference](https://bugs.chromium.org/p/chromium/issues/detail?id=604147&q=nested%20flexbox&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

FIX: 
Adding a { min-height: min-content } to .tile
Didnt test for other browsers and versions.
![screen shot 2016-06-08 at 15 16 24](https://cloud.githubusercontent.com/assets/7658690/15885779/0065ae36-2d8c-11e6-839f-3b1759bcf469.png)

**Comment by XoneFobic** [comment]
Change `flex: 1` to `flex: 1 1 auto` in `.tile`

**Comment by AWulkan** [comment]
@XoneFobic A simpler way to write it would just be `flex: auto;`. Both of them do the same thing.

Reference:
https://css-tricks.com/almanac/properties/f/flex/#article-header-id-3

**Comment by XoneFobic** [comment]
Hm, unless I'm mistaken, not all browsers (versions) render `flex: 1` the
same way. I don't know how `auto` renders across the board, but I'll give
it a test. We've got to support a wide range of browser versions, luckily
all of which have some version of flex support, but we do need to make sure
they all render the same. In that case I'm rather explicit then implicit.
