### ISSUE TITLE
Only get the required styles

### ISSUE THREAD

**Issue by mohammedzamakhan** [jgthms/bulma#2324]
This is about **Bulma**.

### Overview of the problem

In my application I am using simple buttons, and not using inverted, outlined, rounded buttons.

### Description

There is no way to just get the code that we only want, if we want buttons, we will have to get all the code for all the buttons.

https://bulma.io/documentation/overview/modular/

### Steps to Reproduce

Import styles using
```
@import "bulma/sass/utilities/_all.sass"
@import "bulma/sass/elements/button.sass"
```

### Expected behavior

More control over what code needs to be included

### Actual behavior

Includes all the styles of buttons

**Comment by FragsterAt** [comment]
Try to use https://www.purgecss.com/
