### ISSUE TITLE
Not getting same version from bulma via npm

### ISSUE THREAD

**Issue by vmarcel** [jgthms/bulma#2328]
This is about **Bulma | the Docs**.

Is it about Bulma or about the Docs? Bulma

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [7.2.0]

### Description

when installing bulma via npm. Even when the version installed says 7.2.0, there are features of bulma not available, which it should have based on the bulma download

### Steps to Reproduce

1. npm i bulma
2. check bulma in node_modules and compare table.sass in element folder to github master repo and you can see it is not the same

### Expected behavior

Get the true version of bulma install via npm

### Actual behavior

Getting a different version of bulma when installing via npm

**Comment by jgthms** [comment]
The Master branch is the currently developed version. On npm you get the latest release.
