### ISSUE TITLE
Bulma Modal DOCS don't make it clear that you need to place `is-clipped` on body

### ISSUE THREAD

**Issue by DropsOfSerenity** [jgthms/bulma#2331]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The Docs for bulma modal should make it clear that you need to add `is-clipped` class on a containing element in order to prevent scrolling.

**Comment by james-wasson** [comment]
This has been fixed. Directly from the docs:

> To activate the modal, just add the `is-active` modifier on the `.modal` container. You may also want to add `is-clipped` modifier to a containing element (usually html) to stop scroll overflow.
