### ISSUE TITLE
Using Bulma mixins

### ISSUE THREAD

**Issue by anitagraham** [jgthms/bulma#2335]
This is about **Bulma**
It is a question about mixins.

### Overview of the problem

 This is about the Bulma **CSS framework**

 I'm using Bulma **version** [0.7.2] 

 I am sure this issue is **not a duplicate**

### Description

Can I use mixins to add bulma features to existing markup?

For instance 
```css
.page_content { 
    @include container();
}
```

rather than changing the markup to `<section class="page_content container">`?

The content with markup is generated by a CMS. I *can* change the markup but I would prefer not to.

thanks Anita

**Comment by jgthms** [comment]
It's not available yet but it's been discussed here: #33

In your particular case, you could use the Sass extend feature:

```sass
.page_content { 
    @extend .container;
}
```
