### ISSUE TITLE
prefix classes in bulma?

### ISSUE THREAD

**Issue by jlop77** [jgthms/bulma#2337]
Hi, I'm using bulma with wordpress and the generatepress theme. The "container" class, the theme uses it in the customizer, that is, the styles are inline.

I need to rename "container" class in bulma. I'm a noob.

I'm starting in sass. Is there any easy way to do this? I am temporarily manually changing the classes (also create a file to document the changes), for example, prefix-container in sass/elements/container.sass and sass/layout/hero.sass (10 changes in total). I know it's not the best option, but for now it's good for me.

I was reading in #302 , but I do not know what to do :(

Thanks

**Comment by jgthms** [comment]
Prefixing is not planned. However, having each class as a mixin _is_ planned.

What you also can do is import everything _but_ the container.

**Comment by jlop77** [comment]
This is very important for many inexperienced people. So many years and no easy solution :(
Many people like me, want to use bulma and in the end give up for things like these.

**Comment by creativesuspects** [comment]
I've created a simple NPM builder for bulma.css (v0.8.2) with a custom class namespace:

https://github.com/creativesuspects/bulma-custom
https://github.com/creativesuspects/bulma-custom/blob/master/all/bulma.prefixed.css
https://github.com/creativesuspects/bulma-custom/blob/master/all/bulma.prefixed.min.css

The package also includes a custom builder that allows you to only include the elements and components you need. I have only done some simple tests, but I haven't encountered any issues so far. I've also included the Checkradio extension in the custom build and that also works.

**Comment by lil5** [comment]
here is one for version 0.9.0
https://github.com/lil5/bulma-custom
a fork of @creativesuspects

**Comment by Eduruiz** [comment]
@lil5 and @creativesuspects solutions are good (thanks!), but keep in mind that the general rules from things like `tables`, `body` etc. will keep interfering with your styles, I got a problem with the `font-family` of certain buttons because bulma sets it with the element selector and not using a class.

**Comment by faeb187** [comment]
is prefixing ALL bulma classes now possible? I'ce seen there is bulma-prefix (github), looks abandoned (7months) and to be clear: no ignore ".is-" or similar, EVERY class has to become .bulma-tized and if bulma-prefix is the way, what about "bulma-components" package? probably fails then? I don't really need that, could builf the components myself quickly, but as it already exists, I try not to reinvent the wheel... As I'm implementing a common interface for EVERY existing (known) framework, I don't have much time fixing/extending (basic?-)features like prefixing. And I really like Bulma so thank you for a quick update. If there isn't a clean way yet I'm releasing the frsmework without it and add it asap...

**Comment by faeb187** [comment]
bulma-custom sounds interesting. up-to-date and ready? thanks in advance. <3 one love to open-source community. my framework will be open-source too. will release pretty soonish. you can't see it yet, private until ready for collaboration
