### ISSUE TITLE
[question] The 'columns' class adds margin:-10

### ISSUE THREAD

**Issue by mkuts12** [jgthms/bulma#234]
### Checklist

* [x] This is aFbout Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** [0.0.28]
* [x] My **browser** is:
* [x] I am sure this issue is **not a duplicate**?

### Description

Why is adding the 'columns' class adds changes to the [margin](https://github.com/jgthms/bulma/blame/master/css/bulma.css#L4066)?
Maybe I'm using it in a wrong way but it breaks my css.

### Steps to Reproduce

```jsx
    <span
      className='columns'
      style={{
        border: 'solid 1px',
      }} >
      <span
        className='column is-three-quarters' >
        <progress
          className='progress is-medium'
          value={8}
          max={10} >
          80%
        </progress>
      </span>
      <span
        className='column'>
        8/10
      </span>
    </span>
```
_Expected behavior:

![image](https://cloud.githubusercontent.com/assets/11707236/15823792/e4716e5a-2c04-11e6-8e82-01d93896ea99.png)

_Actual behavior:

![image](https://cloud.githubusercontent.com/assets/11707236/15823813/f973152e-2c04-11e6-9574-ba416293ed72.png)

You can see it [here](http://codepen.io/anon/pen/mEeyKX)

**Comment by ShaggyDude** [comment]
This is the way the columns work. It is the same with bootstrap. I'm not familiar enough with bulma yet to tell you how to override this yet but I'm sure there is a way..

**Comment by seriouz** [comment]
I have overwriten the -10px on the columns class (with margin: 0px;) and it works just fine!

**Comment by jgthms** [comment]
The negative margin is here to ensure that each column has the appropriate width. If you remove it, you might get issues with sizing the columns, but I'm glad it worked for you in this case.

**Comment by hugows** [comment]
So how do you make the following design with the **horizontal** line going from the column to the window border?

![drawing](https://cloud.githubusercontent.com/assets/11545/23176851/8e54164c-f843-11e6-84e0-277201917a82.png)

**Comment by seriouz** [comment]
You don't make such a layout with bulma?

**Comment by neilcarpenter1** [comment]
The negative margins doesn't make any sense to me? @jgthms Could you give an example of how not having negative margins might cause an issue with sizing columns? I seem to get more issues by having negative margins than I do without. Just wrapping everything in a div.section seems like unneccessary markup to me.
