### ISSUE TITLE
Incomplete sentence in Image Docs

### ISSUE THREAD

**Issue by ryannhg** [jgthms/bulma#2340]
Hey there,

I noticed that there is a new section with some missing content!

Not sure if you wanted to remove it or finish it 😄

https://github.com/jgthms/bulma/blob/ee3415787661fc0bb69e6d9f8d890a4634c6af02/docs/documentation/elements/image.html#L184

**Comment by mi9dev** [comment]
ryannhg,

[image.html](https://github.com/jgthms/bulma/blob/ee3415787661fc0bb69e6d9f8d890a4634c6af02/docs/documentation/elements/image.html#L184) you opened is commit(ee3415787661fc0bb69e6d9f8d890a4634c6af02) Tree branch related file.

Please check the Master branch [image.html](https://github.com/jgthms/bulma/blob/master/docs/documentation/elements/image.html) file
https://github.com/jgthms/bulma/blob/master/docs/documentation/elements/image.html

This issue can be closed, not a valid one
