### ISSUE TITLE
Footer.scss file footer-padding commit doesn't appear to be pushed to npm

### ISSUE THREAD

**Issue by shereenqumsieh** [jgthms/bulma#2343]
Hi there,

This is about **Bulma & the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs** 
I'm using Bulma 0.7.2

### Description

I'm using yarn to install bulma, version 0.7.2 and I'm specifically trying to modify the `$footer-padding` variable. It doesn't seem to have any affect. If I click to download the files directly from the bulma site, the footer.scss file in sass/layout doesn't have this change. Meaning, the footer padding is still hard coded.

This is the file in question:
https://github.com/jgthms/bulma/blob/master/sass/layout/footer.sass

This is the commit:
https://github.com/jgthms/bulma/commit/a9b5d284cccbf379399c36345ec1465197c1af2c

The documentation seems to be updated and indicates I should be able to set this variable:
https://bulma.io/documentation/layout/footer/

Should this be available in 0.7.2?

**Comment by MMysiv** [comment]
I confronted with a similar problem. That's why I'm here) $footer-padding really have no changes.

**Comment by shereenqumsieh** [comment]
Closing this since it was a fix in 0.7.3 which was just released. I've just done a yarn upgrade and can confirm it now works. Thanks Jeremy!
