### ISSUE TITLE
The show responsive helper isn't working

### ISSUE THREAD

**Issue by JwanKhalaf** [jgthms/bulma#2344]
I am trying to get something to show only on mobile devices, so [as per docs](https://bulma.io/documentation/modifiers/responsive-helpers/), I want to use the show helpers.

Here is the HTML:

```
<section class="hero is-large">
  <div class="hero-head">
    <div class="mobile-logo is-flex-mobile">
      <img src="images/logo.svg" width="170" />
    </div>
  </div>
</section>
```

For some reason, even on desktops, the `mobile-logo` still shows. What am I missing? I believe the documentation could be better on this.

Thank you.

**Comment by Neha** [comment]
Hello,

As per docs, Bulma don't support visible only for Mobile. If you go through the documents, it will make visible for mobile and tablet (I assume landscape view of mobile).

To fix the issue you are facing:
1) add class **_is-hidden-tablet_**

![bulma](https://user-images.githubusercontent.com/61655/52688605-259d6400-2f7d-11e9-8fed-ab51a0da07b4.PNG)

I hope this will be helpful for you.

Thanks,
Neha

**Comment by JwanKhalaf** [comment]
Thank you, that worked.

**Comment by Neha** [comment]
You can close the issue now :)
