### ISSUE TITLE
Global is-radiusless

### ISSUE THREAD

**Issue by vertonghenb** [jgthms/bulma#2348]
This is about **Bulma | Features**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

To get a more modern design, it should be possible to easily set **all** components / elements without a `radius`, `is-radiusless` is already possible but currently you have to set it for every element which is abit redundant.

### Expected behavior
Make it possible to set a global variable to theme the css.

**Comment by jgthms** [comment]
It's in the next release.

**Comment by vertonghenb** [comment]
@jgthms Nice!
Any ETA on the next release?
