### ISSUE TITLE
First char of select disappear on print preview (Chrome PC only)

### ISSUE THREAD

**Issue by jpbecotte** [jgthms/bulma#2350]
This is about **Bulma** (not the docs). This is a bug and it happens only with Chrome on PC (not Mac), latest version 72.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.2] 
I am sure this issue is **not a duplicate**

### Description

First character of select elements disappear in print mode

### Steps to Reproduce

1. Use the simple following HTML.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        Hello World
      </h1>
      <p class="subtitle">
        My first website with <strong>Bulma</strong>!
      </p>
      <div class="select is-small is-fullwidth">
        <select>
          <option>Select dropdown</option>
          <option>With options</option>
        </select>
      </div>
    </div>
  </section>
  </body>
</html>
```

2. Select «With options»

3. CTRL + P

4. You'll see «ith options»

### Expected behavior

To See «With options»

### Actual behavior

You'll see «ith options»

![capture d ecran le 2019-02-07 a 09 56 16](https://user-images.githubusercontent.com/4622285/52424425-9c3eeb00-2abf-11e9-9158-ce8e733dc608.png)

**Comment by abnersajr** [comment]
I had created a test and found this issue only with this chrome version.
What is causing the problem is the following code:
```
select {
 padding-left: calc(.625em - 1px) // results 6.5px
}
```
Any decimal number between n.5 - n.9 will cause this issue.
Maybe also is a bug on chrome.
In the image below I use the value `15.5px` and the issue occurs.

![image](https://user-images.githubusercontent.com/1998649/52497457-4486a980-2bbd-11e9-968a-2e02495c2ed4.png)

Could you assing this issue to me. I'm working on it.

**Comment by abnersajr** [comment]
@jpbecotte what you can do by yourself is create a CSS to override that until we fix this on Bulma 👍

**Comment by jpbecotte** [comment]
@abnersajr : Thanks! that fixed the issue!

**Comment by abnersajr** [comment]
@jpbecotte do not close the issue please. This can help more people until we fix.
