### ISSUE TITLE
.css missing (0.7.3)

### ISSUE THREAD

**Issue by nikkop** [jgthms/bulma#2351]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

`.css` missing from build 0.7.3. Is this intentional? I didn't see any information about it in the notes.

### Expected behavior

I expected a` .css `file to be in the release.

### Actual behavior

There was none. Only `.sass`

**Comment by ideodora** [comment]
+1

**Comment by davidbudnick** [comment]
+1

**Comment by jgthms** [comment]
Fixed! For some reason, the `/css` folder got deleted in the process. Thanks for pointing that out.
