### ISSUE TITLE
Table reset properties should be in _tables.scss

### ISSUE THREAD

**Issue by e-belair** [jgthms/bulma#2353]
### Description

Table reset properties should be in _tables.scss instead of [minireset.scss](https://github.com/jgthms/bulma/blob/3d6680fae204c54fe184c964c83a5bb7d7c9c1f6/sass/base/minireset.sass#L77)
for those (like me) that use only few components of the framework

**Comment by jgthms** [comment]
I reckon it could be duplicated in `tables.sass`.

**Comment by manuscle** [comment]
I can make a PR if you want

**Comment by e-belair** [comment]
not stale
