### ISSUE TITLE
Safari's input[disabled] text is too faded

### ISSUE THREAD

**Issue by dsernst** [jgthms/bulma#2355]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**.
I'm using Bulma **version** 0.7.2.
My **browser** is: Desktop Safari 11.1.2, iOS Safari 10.3.3.
I am sure this issue is **not a duplicate**.

### Description

Safari is rendering `disabled` input fields with faded text. 

Instead of the Bulma default `#7a7a7a` (48% luminosity), the input text renders at `#cecece` (81% luminosity).

### Steps to Reproduce

```html
<input disabled value="Some text" />
```

### Expected behavior

Text color would match across browsers.

### Actual behavior

![image](https://user-images.githubusercontent.com/6340841/52501503-5d7b6480-2b95-11e9-8902-0c965f8ef960.png)

------------

Here's a StackOverflow documenting this issue (not Bulma specific): https://stackoverflow.com/questions/262158/disabled-input-text-color

It looks like one solution is patching [`sass/elements/form.sass`](https://github.com/jgthms/bulma/blob/ff8c4c18accf2c0094aa77945b1d2180ac927159/sass/elements/form.sass#L67):

```patch
input
  &[disabled],
  fieldset[disabled] &
+   -webkit-text-fill-color: $input-disabled-color
+   opacity: 1
```

Happy to submit a PR if welcome.

**Comment by Neha** [comment]
Hey,
Every browser has its own styling or default style for native HTML tags. When developing a lib/framework should we leave the tags default behavior on the browser and if any user wants to change it, they can go ahead and do needful changes in its own code? 

What is your thought? 

Thanks,
Neha

**Comment by dsernst** [comment]
Multiple users reported they were confused, thinking the `<input disabled>` field's `value=` was instead `placeholder=` text, because it was so faded.

I agree in part with the sentiment to respect browser defaults. 

But Bulma is [already choosing to override the default `<input disabled>` text `color`](https://github.com/jgthms/bulma/blob/ff8c4c18accf2c0094aa77945b1d2180ac927159/sass/elements/form.sass#L67). That setting simply isn't taking effect in Safari & iOS Safari.

I believe this can be considered more of a bug than a stylistic choice.

**Comment by Neha** [comment]
Make sense. Especially when the Bulma has taken care of the code to override the browser(s) default style. 

You should raise the PR with fix as you suggested.

**Comment by mxlje** [comment]
Is someone working on this? I tried out the fix above and it does fix the issue for me.

**Comment by dsernst** [comment]
PR opened: https://github.com/jgthms/bulma/pull/2517
