### ISSUE TITLE
Allow modifers like `is-danger` on `modal-card-head` 

### ISSUE THREAD

**Issue by jboarman** [jgthms/bulma#2356]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.4**

### Description

The `is-danger` modifier does not seem to work with the `modal-card-head` element.  I am trying to set the background color to model after the provided reference modal image shown for the expected behavior.

### Steps to Reproduce

Add `is-danger`, as in `<header class="modal-card-head is-danger">`, as seen below:

``` html
<div class="modal is-active">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head is-danger">
      <p class="modal-card-title">Confirm Delete</p>
      <button class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <div class="content">
        Type "<b>delete</b>" to confirm that you want to delete this agreement.
        </div>
      <div class="field">
        <div class="control">
          <input type="text" class="input"
                 placeholder="type `delete` and then click confirm">
        </div>
      </div>
    </section>
    <footer class="modal-card-foot">
      <button class="button is-danger">Confirm Delete</button>
      <button class="button">Oops, go back please...</button>
    </footer>
  </div>
</div>
```
### Expected behavior

Here's an example I'm trying to clone from another system:
![2019-02-09_12-06-34](https://user-images.githubusercontent.com/1108065/52524504-39865480-2c63-11e9-9ec5-97af3373ca3d.png)

### Actual behavior

However, the `is-danger` seems to have no effect on the header, as seen here:
![2019-02-09_12-14-58](https://user-images.githubusercontent.com/1108065/52524708-b6b2c900-2c65-11e9-995a-f86516c4045a.png)

**Comment by jboarman** [comment]
See this other modal-related issue regarding placement of buttons: #1589

**Comment by jboarman** [comment]
As a workaround, I'm using the custom `has-bg-danger` variable suggested in this other issue comment: https://github.com/jgthms/bulma/issues/1525#issuecomment-350846389

**Comment by asmaloney** [comment]
Came here looking for this.

Using the `is-*` classes to change the title colours of a modal is the natural thing to try and I'm surprised it doesn't work...
