### ISSUE TITLE
CHANGELOG.md only lists 0.7.3 

### ISSUE THREAD

**Issue by madscientistproductions** [jgthms/bulma#2362]
This is about the github repository.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** 0.7.4

### Description

The CHANGELOG.md file only lists changes up to and including Bulma 0.7.3.  There is no mention of any changes in 0.7.4.

### Steps to Reproduce

1.  Open the changelog. :)

### Expected behavior

Read all about the new stuff and changes in 0.7.4.

### Actual behavior

Only see 0.7.3.

**Comment by jgthms** [comment]
There’s no difference. 0.7.4 was released instantly after 0.7.3 because the CSS was missing.

**Comment by madscientistproductions** [comment]
Okay, thanks for the reply.  It's still incorrect to have the CHANGELOG.md only reference 0.7.3 though.

**Comment by emkajeej** [comment]
The docs state some new features as 0.7.4, which I can't seem to find in the 0.7.3 changelog tho?
For example: https://bulma.io/documentation/modifiers/typography-helpers/#font-family

**Comment by MalyshevDmitry** [comment]
@jgthms I agree with @madscientistproductions. I spent an hour to understand what is the difference between 0.7.3 and 0.7.4. Also, it will be helpful to have changelog on bulma.io site.
