### ISSUE TITLE
Incomplete documentation for the Image element

### ISSUE THREAD

**Issue by borxes** [jgthms/bulma#2364]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description

Incomplete documentation at 
[http://bulma.io/documentation/elements/image/#arbitrary-ratios-with-any-element](
http://bulma.io/documentation/elements/image/#arbitrary-ratios-with-any-elemen)

The documentation for the **arbitrary ratios** section is an incomplete sentence.

**Comment by billwagner3** [comment]
I agree with borxes here. Where are the docs for arbitrary ratios?

**Comment by nickwesselman** [comment]
Agree needs docs, but details can be found here:
https://github.com/jgthms/bulma/pull/592

Short story is that you can drop `image` and the ratios on any element.
