### ISSUE TITLE
how to set margin to the container

### ISSUE THREAD

**Issue by iliakut** [jgthms/bulma#2366]
Here the example: https://dansup.github.io/bulma-templates/templates/admin.html

I want to aside left menu was attached to the left. 
For this I need to set margin-left of the container, but Bulma sets it auto. 

what should I do to resolve it?

**Comment by abnersajr** [comment]
You have some options:

- Edit `container.sass` file. Although, I don't suggest this.
- Override the` .container` class  in your own CSS file. Your CSS file should be loaded after the Bulma file.
- Use your own "container" class.
- Append another class to the HTML element alongside the container class writing only the `margin-left.

This is how you can set up the `margin-left`.
However, removing the `margin: 0 auto` you will push all the content to the left.

@jgthms taking in count what was asked, this issue should be closed.
