### ISSUE TITLE
[Bug] Help class has unnecessary padding.

### ISSUE THREAD

**Issue by vinczebalazs** [jgthms/bulma#2370]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

Could be a duplicate of [723](https://github.com/jgthms/bulma/issues/723), but it's still not resolved.

### Description

When using the `help` class inside a group of fields that have the `is-expaned` class, the fields expand too much if the text inside the help element is a bit longer.

### Steps to Reproduce

The following snippet clearly demonstrates the issue:

```
<div class="container">
  <div class="field is-grouped">
    <div class="field is-expanded">
      <label class="label">
        Field
      </label>
      <div class="control">
        <input class="input">
      </div>
      <p class="help is-danger">This input should not be this wide.</p>
    </div>
    <div class="field is-expanded">
      <label class="label">
        Field
      </label>
      <div class="control">
        <input class="input">
      </div>
    </div>
    <div class="field is-expanded">
      <label class="label">
        Field
      </label>
      <div class="control">
        <input class="input">
      </div>
      <p class="help is-danger">This input should not be this wide.</p>
    </div>
    <div class="field is-expanded">
      <label class="label">
        Field
      </label>
      <div class="control">
        <input class="input">
      </div>
    </div>
  </div>
</div>
```

![Image of the issue.](https://i.ibb.co/9wSz6Cq/Screenshot-2019-02-19-at-2-09-03.png)

### Expected behavior

The inputs inside the fields should not expand when the help text is a bit longer, as the text is still not wider than the input it self.

### Actual behavior

The inputs inside the fields expand despite the help text being way narrower than the inputs themselvs.

**Comment by yxngl** [comment]
I don't think Bulma defines grouped fields in field, just grouped controls in field. I think it is better to just use columns in this case.
