### ISSUE TITLE
Cannot vertically stack tags

### ISSUE THREAD

**Issue by JeanLucEsser** [jgthms/bulma#2373]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Tags are a godsend, but I can't find a way to show them vertically stacked, only horizontal with the option of multiline. Did I miss something? There are times it would be useful to have a list of tags, each on its own line. I used to put them in a p:field tag, but now with the tags class it doesn't work anymore. I'm using the tags class to right align them in their container.

### Steps to Reproduce

``` html
<div class="tags is-right">
  <p class="field">
    <span class="tag">tag 1<span>
  </p>
  <p class="field">
    <span class="tag">tag 2<span>
  </p>
</div>
```

### Expected behavior

```
<tag 1>
<tag 2>
...
```

### Actual behavior

```
<tag 1> <tag 2> ...
```

**Comment by jgthms** [comment]
Have you tried

```
  <p class="field">
    <span class="tag">tag 1<span>
  </p>
  <p class="field">
    <span class="tag">tag 2<span>
  </p>
```

**Comment by JeanLucEsser** [comment]
If I omit the `<div class="tags is-right">` it works as intended, but it won't be right aligned.

This is vertically stacked but left aligned:
```
  <p class="field">
    <span class="tag">tag 1</span>
  </p>
  <p class="field">
    <span class="tag">tag 2</span>
  </p>
```

This is right aligned but not vertically stacked:

```
<div class="tags is-right">
  <p class="field">
    <span class="tag">tag 1</span>
  </p>
  <p class="field">
    <span class="tag">tag 2</span>
  </p>
</div>
```

How to get the tags to be right aligned and stacked?

**Comment by jgthms** [comment]
You could do:

```html
<div class="tags is-right">
  <span class="tag">tag 1</span>
</div>
<div class="tags is-right">
  <span class="tag">tag 2</span>
</div>
```

**Comment by JeanLucEsser** [comment]
Yes, that's what I ended up doing but then I have to manage to too high bottom margins and it also kind of defeats the initial purpose of using tags to group them. But it works so I guess we're all set.

Thanx.
