### ISSUE TITLE
Is contributing to Bulma a waste of time?

### ISSUE THREAD

**Issue by Maxhodges** [jgthms/bulma#2374]
40 PRs are over a year old. People's hard work has sat for over-a-year with no action or comment by @jgthms 

See https://github.com/jgthms/bulma/pull/1622

Why should anyone contribute to this project when the maintainer ignores valuable PRs which community members are begging for? If the maintain can't handle the load, perhaps he could elevate another contributor's permission to help merge PRs?

**Comment by jgthms** [comment]
Around 200 PRs have been closed/merged in the past year, so no, contributing is _not_ a waste of time 😉

**Comment by Maxhodges** [comment]
@jgthms dude, why do you make it a priority to instantly reply to this issue, yet fail to reply to this issue and associated PR request for over a year, despite dozens of people upvoting it? 

#1325

**Comment by Maxhodges** [comment]
inquiring minds want to know: #1325
