### ISSUE TITLE
Feature discussion: object-fit

### ISSUE THREAD

**Issue by mrg0lden** [jgthms/bulma#2377]
### Overview of the problem

 This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.4]

I am sure this issue is **not a duplicate**?

### Description

I'm gonna work on it, this is just an RFC.
I want to implement `object-fit` for `.image`.
 It can be supported for more elements (e.g. `video`) as well although edge doesn't support any elements but `img` for now. (it's gonna use chromium soon so that shouldn't be a problem.)

[CANIUSE](https://caniuse.com/#feat=object-fit)

### Suggested Classes

I suggest using `.is-cover` for `object-fit: cover`, `.is-contain`, and `.is-fill` (the last one is the default behavior so I find it unnecessary) .
I also want to support `object-position` that has similar values to `background-position`.
I suggest using `.is-centered`, `.is-top`, `.is-bottom`, `.is-left`, `.is-right` (center is the default behavior)

I'm happy to receive feedback to reach the best possible result.

**Comment by mrg0lden** [comment]
@jgthms Shall I start by making a pull request?

**Comment by Kimeiga** [comment]
I would also like this because object-fit: cover; is such a common thing to use when you are getting images from other sources and can't control the resolution.

**Comment by dipeshparashar** [comment]
Must have. Any updates ?
