### ISSUE TITLE
Links styled with 'button' won't let you tap and hold in mobile Safari to copy the link.

### ISSUE THREAD

**Issue by maddox** [jgthms/bulma#2378]
This is about **Bulma**.

### Overview of the problem

I'm finding something weird in mobile Safari. Normally in Safari, you can tap and hold a link and copy it. It presents an alert with these options:

* Open
* Open in New Tab
* Add to Reading List
* Copy
* Share...

When a link is styled with the `button` class, it will not show this alert. You can hold forever, and nothing happens.

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.0]
My **browser** is: Mobile Safari

### Steps to Reproduce

1. Open a site that's using bulma in mobile Safari (https://getchannels.com)
2. tap and hold a link styled with `button`

### Expected behavior

An alert in mobile Safari should show with options as listed above.

### Actual behavior

Nothing.

**Comment by maddox** [comment]
It looks like [this](https://github.com/jgthms/bulma/blob/ceae8a675edad50591fc0ad62db1278286d8d6aa/sass/utilities/mixins.sass#L133) is the culprit.

I'm curious why this was set in the first place.

**Comment by cliffpyles** [comment]
I was able to activate the menu and copy the link on Mobile Safari. @maddox Are you still able to reproduce this?

**Comment by cliffpyles** [comment]
What device are you on? I tested it on an older iPad (iPad Air 2).

**Comment by maddox** [comment]
This was on iPhone in the past. Looks like it works now with a more modern safari.
