### ISSUE TITLE
.container.is-fluid not aligning items properly within .section

### ISSUE THREAD

**Issue by shakib609** [jgthms/bulma#2379]
This is about the **Bulma CSS framework**.

### Overview of the problem
`.container` is not aligning properly with the `.navbar` when `.is-fluid` is applied.

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.4]
My **browser** is: **Brave Browser 0.60.28**(Chromium 72)
I am sure this issue is **not a duplicate**

### Description
`.container.is-fluid` is not aligning properly with the `.navbar` which also uses `.container.is-fluid`.
My contents are wrapped within a `.section`.
The `.container` without the `.is-fluid` works without any issues and lines up properly with the navbar.
If I don't wrap my content within the `.section` then the `.is-fluid` works but I need the `.section` to get padding on mobile-view.

### Steps to Reproduce

Create a Navbar with `.container.is-fluid` and below create a `.section` with a `.container.is-fluid` inside of it.
```
<nav class="navbar">
  <div class="container is-fluid">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <h1>Brand</h1>
      </a>
    </div>
  </div>
</nav>
<div class="section">
  <div class="container is-fluid">
    <h1>Hello World</h1>
  </div>
</div>
```
### Expected behavior

The contents will line up properly with the `.navbar` items.

### Actual behavior

The contents are not aligned properly with the `.navbar` items.

![container-fluid-issue](https://user-images.githubusercontent.com/3992124/53282691-90ad1e80-3765-11e9-8eba-030312ba76c9.png)

**Comment by Neha** [comment]
Hey,

It is coz you are using class ' .section'.
 .section is taking padding/margin around. If you will remove the class section it will align properly.

Please check the Bluma documentation for same: https://bulma.io/documentation/layout/section/

Here is the pen for code demo (after removing class .section) : https://codepen.io/NehhaSharma/pen/EMxPxj 

Thanks,
Neha

**Comment by shakib609** [comment]
Hey, Thanks for taking the time to take a look at the issue. The **Bulma** documentation specifies that `.container` class can be used in any context, but mostly as a direct child of `.navbar`, `.hero`, `.section` and `.footer`. [https://bulma.io/documentation/layout/container/](https://bulma.io/documentation/layout/container/)

Also this is the screenshot of the `.container` without the `.is-fluid` class wrapped with a `section.section`:
![screenshot_20190225_235516](https://user-images.githubusercontent.com/3992124/53357823-ee558c80-3958-11e9-92fc-63741ab80f0f.png)

Also one other thing, `.container` takes the whole width of the screen in smaller devices without any paddings when not used within a `.section`.

Thanks,
Shakib

**Comment by Neha** [comment]
Hello,

Apologies, I am not able to understand the requirements. What I can understand - you want to align both blocks. 

Yes, Bulma says that you can have the child but padding/margin around it will remain.
