### ISSUE TITLE
Unable to get hero nav hamburger menu to work

### ISSUE THREAD

**Issue by rudedogg** [jgthms/bulma#238]
Bulma Version: 0.28
Browser: Tested Chrome & Safari

### Description
I'm unable to get the hamburger menu to work in hero->nav

I originally used the example under `hero`, and have tried mimicking the html used on https://github.com/jgthms/bulma-website

### Steps to Reproduce
```html
<body>
  <section class="hero is-dark">
    <div class="hero-head">
      <div class="container">
        <nav class="nav">
          <div class="nav-left">
            <a class="nav-item" href="/"><img src="images/logo-small.png" alt=""></a>
          </div>
          <span id="nav-toggle" class="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
          </span>
          <div id="nav-menu" class="nav-right nav-menu">
            <a class="nav-item is-active" href="/">Home</a>
            <span class="nav-item"> <a class="button is-primary" href="#linkhere"><span class="icon"><i class="fa fa-shopping-cart"></i></span><span>Buy</span></a></span>
          </div>
        </nav>
      </div>
    </div>
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">hero text</h1>
      </div>
    </div>
  </section>
  ...
</body>
```

Any help would be appreciated. I ran through the examples a couple times and checked everything to make sure I wasn't missing a tag or something. The result is that the hamburger menu appears, but clicking it has no effect.

I put a sample page in index.html of https://github.com/rudedogg/bulma

**Comment by patrickbolle** [comment]
Same problem here.

**Comment by inseldesign** [comment]
Yeah you simply need a JS event to handle the click and "add" or "remove" the '.is-active'-class on '#nav-menu'.

**Comment by rudedogg** [comment]
Thanks! I thought it must be some fancy css animation or something and I just had the wrong html.

```javascript
	<script type="text/javascript">
		document.getElementById("nav-toggle").addEventListener ("click", toggleNav);
		function toggleNav() {
				var nav = document.getElementById("nav-menu");
				var className = nav.getAttribute("class");
				if(className == "nav-right nav-menu") {
					nav.className = "nav-right nav-menu is-active";
				} else {
					nav.className = "nav-right nav-menu";
				}
		}
	</script>
```

**Comment by somenxavier** [comment]
You need [bulma.js](http://bulma.io/javascript/bulma.js)

**Comment by softwareguy74** [comment]
Doesn't requiring jquery to do this defeat the purpose of Bulma in the first place, which I thought was a jquery free alternative to Bootstrap?  Anyway to do this with pure javascript instead so as to not take on the extra weight of jquery?

**Comment by rudedogg** [comment]
@softwareguy74 Not sure if things have changed, but I was able to get it working with pure javascript using the code I posted above.

**Comment by dak0rn** [comment]
It is actually possible to get the mobile menu to work w/out JavaScript by adding a hidden checkbox and showing/hiding the menu depending on its state.

See this fiddle: https://jsfiddle.net/jfm2jyk5/

**Comment by somenxavier** [comment]
> Doesn't requiring jquery to do this defeat the purpose of Bulma in the first place, which I thought was a jquery free alternative to Bootstrap? Anyway to do this with pure javascript instead so as to not take on the extra weight of jquery?

I took that from bulma.io website. Which uses jquery.

**Comment by softwareguy74** [comment]
@dak0rn   Hey, that did the trick!  And no jquery OR javascript.  Thanks!

**Comment by somenxavier** [comment]
Perhaps they could implement this in bulma.io website  for making example

**Comment by GBarkhatov** [comment]
React snippet on an element with `className="nav-toggle"`

`onClick={() => {
            let toggle = document.querySelector(".nav-toggle");
            let menu = document.querySelector(".nav-menu");
            toggle.classList.toggle("is-active");
            menu.classList.toggle("is-active");
          }}`

**Comment by abinashdpatra** [comment]
@dak0rn nice trick man. dint knew for attribute could be used like that also. one question though, why does the checkbox gets hidden

**Comment by dak0rn** [comment]
@abinashdpatra On the technical side, it gets hidden because of the corresponding CSS rule in the style sheet. Functionally, it's hidden because it's just the state holder and does not provide any value to the user.

**Comment by abinashdpatra** [comment]
@dak0rn thanks for the explaination. had missed it.

**Comment by AngeloAnolin** [comment]
@dak0rn wondering if I am missing something but, say after selection of an item, shouldn't the menu item automatically close?

**Comment by rushstrike** [comment]
```

document.getElementById("nav-toggle").addEventListener ("click", toggleNav);
        function toggleNav() {
                var nav = document.getElementById("nav-menu");
                var className = nav.getAttribute("class");
                if(className == "nav-right nav-menu") {
                    nav.className = "nav-right nav-menu is-active";
                } else {
                    nav.className = "nav-right nav-menu";
                }
        }

```

Any tips on how to update this code to make it auto close after menu selection?

**Comment by dak0rn** [comment]
@AngeloAnolin Ah, I missed your response.
With the CSS-only technique it indeed does not auto-close; you'd need to add JavaScript.

If you do not use a framework and you are not developing a single page application, you could use the following (plain ol' JavaScript) way: attach a `click` listener to `body`. When this listener is triggered, you check if the user has clicked somewhere outside of the menu (with [this](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) function) and if so, you just emit a `click` event on the `label` again.

**Comment by shaneturner** [comment]
A bit more succinct on the nav item itself:

`<span class="nav-toggle" onclick="document.querySelector('.nav-menu').classList.toggle('is-active');">`

**Comment by xlcrr** [comment]
Following on from @shaneturner 

If you want to toggle the text colour of certain nav-items when the hamburger is pressed 

<span class="nav-toggle" onclick="document.querySelector('.nav-menu').classList.toggle('is-active'); document.getElementsByClassName('nav-item')[1].style.color = 'black'; document.getElementsByClassName('nav-item')[2].style.color = 'black';">

**Comment by arturadib** [comment]
@shaneturner's answer should be the default example in the docs

**Comment by lukepighetti** [comment]
This works for me in 2018

```
function hamburgerHelper(){
    document.querySelector('.navbar-burger').addEventListener("click", toggleNav);
    function toggleNav() {
            var nav = document.querySelector('.navbar-menu');
            var className = nav.className;
            if(className == "navbar-menu") {
                nav.className = "navbar-menu is-active";
            } else {
                nav.className = "navbar-menu";
            }
    }
}
```

**Comment by KeepingItClassy** [comment]
@GBarkhatov, your solution is a life-saver! I packaged it in its own function since it was too much code to use in-line for my liking, but it's the only thing that's worked for me in React.

BTW, it's almost been two years since the original post, and the Bulma docs still don't mention that you need to write a JS event handler for the burger menu to work. This may be obvious to seasoned front-end developers, but not to us noobs.

**Comment by davidwparker** [comment]
@KeepingItClassy - You can always update the docs and add a PR for them too 😄 (https://github.com/jgthms/bulma/blob/master/docs/documentation/components/navbar.html)

**Comment by tbonz** [comment]
@KeepingItClassy the Bulma docs actually have done a really good job explaining how navbar-menu works, and even give you a js snippet to implement it.
https://bulma.io/documentation/components/navbar/#navbar-menu

**Comment by KeepingItClassy** [comment]
@tbonz my apologies, I was looking in the navbar burger section, not in navbar menu, since the burger is the element that's being toggled. Like I said, I'm new to frontend-development. 😳

**Comment by ibonkonesa** [comment]
There is a snippet at the docs, but if you use Bulma with Vue can do something like this:

`<script>
    export default {
        name: 'app',
        mounted() {
            let navbar = document.querySelector('.navbar-burger');
            navbar.addEventListener('click', function () {
                let target = navbar.dataset.target;
                let $target = document.getElementById(target);
                navbar.classList.toggle('is-active');
                $target.classList.toggle('is-active');

            });
        }

    }
</script>`

**Comment by samuelkristianto** [comment]
im using vue 2.6.10 with buefy 0.7.5
```
<span
  class="navbar-burger burger"
  v-on:click="isActive = !isActive"
  v-bind:class="{ 'is-active': isActive }"
  data-target="navbarMenuHeroA"
>
```
```
<div
  id="navbarMenuHeroA"
  class="navbar-menu"
  v-bind:class="{ 'is-active': isActive }"
>
```
```
<span class="navbar-item">
  <router-link
    to="/register"
    class="button is-my-green is-outlined"
    @click.native="isActive = !isActive">Register
  </router-link>
</span>
```
```
<script>
module.exports = {
  data: function(){
    return{
      isActive: false
    }
  }
}
</script>
```

**Comment by hanscees** [comment]
Hi,
is there a way t adjust the script or code to:

- have the hamburger menu show the menu when you click it

- But NOT expand dropdowns? 

Directly expanded dropdowns are not very friendly IMHO. I'd like the dropdown menu's to appear but not expanded, only expanding if you click them like my site here:
[www.bomengids.nl](url)

**Comment by Chompas** [comment]
I'm having the same issue as @hanscees .

Also on a separate note, I managed to be able to add / close the menu but the menu doesn't go away when I click on a item inside of it or even if I click outside. Any ideas?

**Comment by SofianeMeziani** [comment]
jQuery :

`$('body').on('click', '.navbar-burger.burger', function () {
		if ($('.navbar-menu').hasClass('is-active')) {
			$('.navbar-menu').removeClass('is-active');
		} else {
			$('.navbar-menu').addClass('is-active');
		}
	});`
