### ISSUE TITLE
modal horizontal margins disappear on mobile width 

### ISSUE THREAD

**Issue by noymer** [jgthms/bulma#2387]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.7.4.
My **browser** is chrome desktop.

### Description

When width is smaller than 769px, modal horizontal margins disappears.
On v0.6.2, horizontal margin exist.

|actual (v0.7.4) | expected (v0.6.2) |
|-|-|
|![image](https://user-images.githubusercontent.com/8816130/53682440-0e11f980-3d39-11e9-8ecc-a9e94eeee41e.png)|![image](https://user-images.githubusercontent.com/8816130/53682444-179b6180-3d39-11e9-9cec-c223fce871dc.png)|

### Steps to Reproduce

Look jsfiddle.

0.7.4 (actual behavior)
https://jsfiddle.net/x6Lohyz3/

0.6.2 (expected, past behavior)
https://jsfiddle.net/x6Lohyz3/2/

### Expected behavior

As 0.6.2, margins should exist.

### Actual behavior

No horizontal margins.

### guess

I think It is because #1905.
If you delete `flex-direction` at `.modal`, margins appear.

--

I thank bulma very much, it's invaluable!

**Comment by tanoabeleyra** [comment]
I updated Bulma and run into this (running Firefox by the way). As @noymer said, #1905 broke the margins when width is less than 960px.

**Comment by akmadian** [comment]
Having the same issue, tried applying another class on top of the `modal-card` that adds margins, but the margins still aren't showing.

**Comment by sum93** [comment]
@akmadian Try a wrapper within the `modal-card` element.

**Comment by fabiofdsantos** [comment]
@jgthms 

I had to replace:
```diff
.modal-card {
-     margin: 0 $modal-content-margin-mobile
+     padding: 0 $modal-content-margin-mobile
}
```

If you think this is the best solution for this issue, I will open a PR. Otherwise just leave this issue open until someone provides another solution.

**Comment by FreekyMage** [comment]
Another solution that seems very clean to me:

```
.modal-card
  max-width: calc(100vh - #{$modal-card-spacing})
```

This is just like https://github.com/jgthms/bulma/blob/0dc44161bcef0aa5eed38680af7b04cea416b6f2/sass/components/modal.sass#L73 but for width instead of height. This adds margins while the margin itself can stay as `auto`.

**Comment by akicho8** [comment]
There is currently the same problem.
