### ISSUE TITLE
[Feature Request] Class flag to disable responsiveness on navbar (links always show, no hamburger).

### ISSUE THREAD

**Issue by ergose** [jgthms/bulma#2391]
This is about **Bulma** and is a **feature request**.

### Description

**Use case:** Electron app using Vue2 and Bulma.

What I'm wanting is something like a class that tells bulma navbar to flat out not be responsive (at least in regard to top-bar links dissappearing for the hamburger.) A split screen forces the user to click the hamburger when the navbar only has a few links. I'm pulling Bulma in to SimulatedGREG's [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate. Then npm installing bulma as a dependency. I'd rather not have to touch the framework just to keep two/three links visible. I know an electron app probably wasn't the original intent of where this would be used, but it's a great fit if you all could support some scenarios like this.

### Steps to Reproduce
1 - Pull down the [electron-vue](https://github.com/SimulatedGREG/electron-vue) boilerplate and `npm i`
2 - Get maybe 2 or 3 routes setup (like for a simple app)
3 - Grab the 1st navbar example from the Bulma site, change the 1st two navbar-item's to router-links
4 - Remove burger and everything else to make it look kinda like below:
```
<template lang='pug'>
#app
    nav.navbar(role="navigation" aria-label="main navigation")
        .navbar-brand
            a.navbar-item(href="https://bulma.io")
                img(src="https://bulma.io/images/bulma-logo.png" width="112" height="28")
        #navbarBasicExample.navbar-menu
            .navbar-start
                router-link(to='/').navbar-item
                    | Menu-Link1
                router-link(to='/something').navbar-item
                    | Menu-Link2
    router-view
</template>

<style lang='scss'>
@import "~bulma/css/bulma.css";
/* CSS */
</style>
```
5 - `npm run dev`

### Expected behavior

If burger html or class like 'disable-responsive' or 'disable-burger' (pick 1, I'm not saying all 3) is added to nav element with 'navbar', the two links will remain. When super small width they can just break as the min-width of the window could be set at the electron level, preventing the user from ever seeing it.

### Actual behavior
Split screen with few views results in unnecessary click by user. Dependency has to be tweaked. #1042 doesn't really hit the mark here since it is more involved and Bulma is already a great fit stock for small apps.

**Comment by JakeLogemann** [comment]
@ergose I solved this with `is-flex-mobile is-flex-tablet`. Its not pretty to write out everywhere but it works.

**Comment by t-rapp** [comment]
@JakeLogemann: When adding these `is-flex*` modifiers to all `navbar-menu`, `navbar-start` and `navbar-item` divs in Bulma v0.9.1 the menu items are shown but with vertical stacking.

Current version of Bulma allows to configure the `$navbar-breakpoint`. What would be the value to disable the breakpoint for all widths (including mobile)?

**Comment by t-rapp** [comment]
BTW: Looks like this ticket is a duplicate of #1445.

**Comment by t-rapp** [comment]
For future reference: Configuring Bulma v0.9.1 with `$navbar-breakpoint` set to zero allows to force a horizontal navbar layout for all page widths. It applies globally to all navbar instances within the page, though.

**Comment by ryanburnette** [comment]
Echoing @t-rapp. This works.

```scss
$navbar-breakpoint: 0;
```
