### ISSUE TITLE
has-navbar-fixed-top inconsistence when changing font-size and setting to html

### ISSUE THREAD

**Issue by volnei** [jgthms/bulma#2392]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.4** 
My **browser** is: Any webkit
I am sure this issue is **not a duplicate**

### Steps to Reproduce
1. Create a page using any sass tool to allow changing variables
2. Add a top fixed navbar;
3. Add the class **has-navbar-fixed-top** to html
4. Change the variable **$body-size** to 14px
5. Add a .hero.is.is-primary section whit any content 
6. Open the page and see that has a blank spacing between Navbar and the hero section.

### Expected behavior

No blank spaces between hero and navbar
<img width="403" alt="image" src="https://user-images.githubusercontent.com/619072/53705362-ad4ef380-3e02-11e9-8c79-615a2a6908b7.png">

### Actual behaviour
An undesirable space is added 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/619072/53705392-e9825400-3e02-11e9-9196-2422052340d5.png">

Note that if you use the  class **has-navbar-fixed-top** on body the problem is solved.

**Comment by Neha** [comment]
Hey,

Can you share the code?

Thanks,
Neha

**Comment by guillecro** [comment]
Same problem here
But I was adding the class "has-navbar-fixed-top" to `<html>` and `$body-size: 14px;`
But in Google Chrome it looks like the `3.25rem` paddingTop doesnt work well, but with `em` it does.

But hey, **here is a fix**
Dont add it to `<html>`, add it to `<body>`! And now it works
