### ISSUE TITLE
About customizing bulma

### ISSUE THREAD

**Issue by giorgi-m** [jgthms/bulma#2395]
This is about the Bulma **CSS framework** 

### Overview of the problem

I'm using Bulma **version** 0.7.4
My **browser** is: Chrome 72

### Description

 I am using create-react-app 2.
 I successfully managed to change navbar breakpoint using this:

```

 $navbar-breakpoint:300px;

@import '../node_modules/bulma/bulma.sass';
```

However, I had impression from reading elsewhere that I had to import first the file in which the variable I wanted to modify was located in (in this case navbar sass file)

```
@import "bulma/sass/utilities/_all.sass";
@import "bulma/sass/components/navbar.sass";
 
$navbar-breakpoint:300px;

@import '../node_modules/bulma/bulma.sass';
```
Which is the correct approach?

PS They both work in the sense that burger menu is shown only on <300px, however with the _second approach_ some shadow appears for the navbar too for certain screen widths.

Here is screenshot
![capture](https://user-images.githubusercontent.com/41240312/53979912-69246180-4128-11e9-8567-2e6244dd0976.PNG)

**Comment by yxngl** [comment]
Follow the docs.

Bulma initializes variables to defaults if it is undefined. Put custom definition later only rewrites the variable, not others depending on it.

**Comment by giorgi-m** [comment]
@yxngl So my first code snippet was correct one? (Bit new to sass, hence confusion).

**Comment by yxngl** [comment]
Yes.
