### ISSUE TITLE
issues relating to button pseudo

### ISSUE THREAD

**Issue by chistel** [jgthms/bulma#2397]
since button element has hover/focus/active helper, then the default pseudo such as *button:hover, button:focus,button:focus:not(:active),button:active*  be remove, 
it's not looking pretty from image attached below.

besides those default pseudo attached to the helper does not allow the result of the helper to be seen.

![image](https://user-images.githubusercontent.com/46791424/54071706-d17e5a80-4270-11e9-8972-8296e41d4817.png)

**Comment by geoblanc** [comment]
Could you please describe the problem in more detail, making use of the suggested steps?

-Overview of the problem
-Description
-Steps to Reproduce
-Expected behavior
-Actual behavior
