### ISSUE TITLE
Why the last box is taller than others?

### ISSUE THREAD

**Issue by 3douhao** [jgthms/bulma#2398]
This is about Bulma

My browsers are Chrome, Firefox, Safari

### Expected behavior

I expected that all boxes have equal height. Like this

<img width="1019" alt="Screen Shot 2019-03-10 at 11 18 09" src="https://user-images.githubusercontent.com/29688038/54080228-3f388e00-4326-11e9-81f5-dabf91c20e97.png">

### Actual behavior

But the last box is always taller. Like this

<img width="765" alt="Screen Shot 2019-03-10 at 11 14 40" src="https://user-images.githubusercontent.com/29688038/54080230-56777b80-4326-11e9-93aa-3156a391721e.png">

Here is the simple html code:

`<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" rel="stylesheet">
		<link href="styles.css" rel="stylesheet">
	</head>
	<body>
		<main>
			<div class="box">
				<figure>
					<img src="" alt="">
				</figure>
				<p class="title">1</p>
				<a href="/" class="subtitle button is-info"></a>
			</div>

			<div class="box">
				<figure>
					<img src="https://i.postimg.cc/BZkHVBqR/fiat.jpg" alt="">
				</figure>
				<p class="title">2</p>
				<a href="/" class="subtitle button is-info"></a>
			</div>
                           
                           ...
                </main>
    </body>`
Here is the css code:

`
main {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  grid-gap: 10px;
}
`

Does anyone know how to fix this? Thanks

**Comment by micovi** [comment]
Hi, I looked into the code you provided and looks like all box elements, except the last one are generated with margin-bottom:1.5rem;

One quick fix for your problem could be adding margin-bottom: 1.5rem to your last box, but be careful that it could break something else up (the last box that will have the same bottom margin on mobile too) 

.box:last-child {
margin-bottom: 1.5rem;
}

**Comment by 3douhao** [comment]
> Hi, in your case Bulma is generating all box elements, except the last one, with `margin-bottom:1.5rem;`
> 
> One quick fix for your problem could be adding margin-bottom: 1.5rem to your last box, but be careful that it could break something else up (the last box that will have the same bottom margin everywhere)
> 
> `.box:last-child { margin-bottom: 1.5rem; }`
> 
> To prevent errors that could appear, I would add a custom class to the boxes container (in your example case `<main class='custom-boxes-container'>`) and target only elements from inside it:
> 
> `.custom-boxes-container .box:last-child { margin-bottom: 1.5rem; }`

It works! Thanks for the reply. I really appreciate it!

**Comment by Danisca** [comment]
nice, worked for me using bulma's columns and column classes.

**Comment by ctala** [comment]
Is this a bug? I am having the same issue.

**Comment by shortydutchie** [comment]
I saw the same issue with a set of 'column box' divs inside a 'columns' div. It was fixed by adding a specific 'mb-1' class (ie. margin-bottom) to the 'column box' bit.

Think it is a bug, to be honest.
