### ISSUE TITLE
List Component Missing from Bulma Docs List

### ISSUE THREAD

**Issue by dyllandry** [jgthms/bulma#2402]
### Overview of the problem

This is about the Bulma **Docs**

### Description
The [docs page for list components](https://bulma.io/documentation/components/list/) is not present in the component list sidebar or tab menu.

**Comment by mi9dev** [comment]
Per @jgthms, This component is not actually ready, and might be deprecated soon.

Jeremey, Can you please close this issue as well?

**Comment by mi9dev** [comment]
#2434

**Comment by mi9dev** [comment]
Per #2434, this issue can be closed.
