### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [jgthms/bulma#2411]
Hi, what is the current status of this project? The activity seems to be lower and there are many open issues and PRs.

**Comment by jgthms** [comment]
Still active! There's still PRs getting merged and issues getting closed, don't worry.

There a few things in the pipelines: classes as mixins, support for CSS variables, and a fresh design update.

**Comment by bobbwal** [comment]
Any eta on the classes as mixins, or any way to contribute?

**Comment by DanielRuf** [comment]
> classes as mixins

For this you can also use `pstcss-classes-to-mixins`: https://github.com/nrkno/postcss-classes-to-mixins

See https://github.com/DanielRuf/tachyons-tailwind-mixins/blob/master/index.js for an example.
