### ISSUE TITLE
How to write html when columns are not certain?

### ISSUE THREAD

**Issue by jinfagang** [jgthms/bulma#2413]
Hello！ guys! thanks for this wonderful framwork!! I have a stupid but nowhere to find answer question.

The situation is, I am using vue.js to for .. loop my data to construct a responsive 4 columns. 
I can write something like this:

```html

 <div class="columns">
                <div class="bd-index-js-tweet" v-for="data in allData">
                    <div class="column">
                          <p>{{data.title}}</p>
                    </div>
              </div>
</div>
```

However, it will make it a single line....... (As bulma dividing automatically)

What should I do to **make it wrap when one line more than 4**?

thanks inadanced!!

**Comment by jinfagang** [comment]
No just a single line?

**Comment by yxngl** [comment]
Add `is-multiline` to columns and `is-one-quarter` to column like https://bulma.io/documentation/columns/options/#multiline

Also I think column should be immediate children of columns.

**Comment by jgthms** [comment]
@yxngl is right on both accounts. Use `is-multiline` and try to have them as immediate children.

**Comment by jinfagang** [comment]
Thank u your guys so much!!!! I'll try it out!!
