### ISSUE TITLE
How to make tab wrap?

### ISSUE THREAD

**Issue by jinfagang** [jgthms/bulma#2421]
Hi, My I ask, how to make this tab to wrap when on mobile phones?

![image](https://user-images.githubusercontent.com/21303438/54869198-418ff300-4dd0-11e9-9768-915ed7dddf4b.png)

It's now can not wrapping

**Comment by geoblanc** [comment]
You have a flex container `<ul>` inside another flex container `<div class="tabs">`. 
This `<ul>` has `flex-shrink: 0` which does not allow its width to shrink.
Just set `flex-shrink: 1` and then `flex-wrap: wrap` should work.
```
.tabs ul {
    flex-shrink: 1;
    flex-wrap: wrap;
}
```

**Comment by jinfagang** [comment]
@geoblanc Thanks, this is a snippet copied from bulmba, it does not wrap which not good at mobile phone experiences

**Comment by michaelteter** [comment]
I'm looking at tabs and wrapping as well, and I observe strange behavior on the official Bulma tabs document page.  At adequate page width, the full tab list is displayed.  At somewhat reduced width, the tabs wrap... up to a certain point.  At a further reduced width, the tabs stop wrapping, switch back to one horizontal row, and show a scrollbar.

<img width="940" alt="Screen Shot 2019-05-30 at 16 32 40" src="https://user-images.githubusercontent.com/411964/58666536-363dd400-82f9-11e9-9ad3-d613adea240c.png">

<img width="728" alt="Screen Shot 2019-05-30 at 16 33 20" src="https://user-images.githubusercontent.com/411964/58666544-3c33b500-82f9-11e9-98ae-023fd7e54f88.png">

<img width="746" alt="Screen Shot 2019-05-30 at 16 33 36" src="https://user-images.githubusercontent.com/411964/58666549-4190ff80-82f9-11e9-933f-05dfc38481c0.png">

**Comment by jinfagang** [comment]
@michaelteter  Would u show some source codes?

**Comment by michaelteter** [comment]
@jinfagang It's just the Bulma documentation page.  You can go there https://bulma.io/documentation/components/tabs/ and resize the window to see the behavior, and view the code if you like :).

**Comment by jinfagang** [comment]
@michaelteter  Oh, notice that, that's really a not beautiful design
