### ISSUE TITLE
Dropdown menu inside a hamburger menu

### ISSUE THREAD

**Issue by omrllm** [jgthms/bulma#2422]
This is a **question**.

### Overview of the problem

So, when I add a dropdown menu inside a hamburger menu, on mobile, the dropdown menu doesn't correctly show up.

![Screenshot from 2019-03-23 22-16-29](https://user-images.githubusercontent.com/45340167/54871735-8fe5c780-4db9-11e9-8368-160066b86307.png)

I'm using Bulma **version** [0.7.4]

### Steps to Reproduce

Just add a dropdown menu inside a navbar hamburger menu and you will find this problem.

### Expected behavior

The dropdown menu should be silent till activated.

### Actual behavior

The dropdown menu is already active and weird.

**Comment by thepra** [comment]
Faced the same issue today, lets see if I can hack around it
