### ISSUE TITLE
Bulma doesn't have inset shadows

### ISSUE THREAD

**Issue by 1mahd** [jgthms/bulma#2423]
This is about **Bulma | the Docs**.

  Is it a bug/feature/question or do you need help? 

### Expected behavior

I wanted to add some inset shadows with bulma but It turn out there is nothing as of now that can do it. 
### Actual behavior
There is no class to do required things.

Bulma doesn't have inset shadow

**Comment by jgthms** [comment]
It's true not many elements use inset shadows. Even these might disappear. That's why there's no helper either because the type of shadow is quite dependent on the style of the website anyway.
