### ISSUE TITLE
Bulma CSS being changed by Font Awesome icons

### ISSUE THREAD

**Issue by deepankarmalhan** [jgthms/bulma#2424]
This is about **Bulma**.

It's a **bug**. Not a browser bug.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.4]
My **browser** is: Google Chrome & Safari
I am sure this issue is **not a duplicate**? **No**

### Description

Using icons from FontAwesome 5 messes up tile css from Bulma.

Testing tiles without any icons from FA:
<img width="1680" alt="Screen Shot 2019-03-25 at 1 04 16 PM" src="https://user-images.githubusercontent.com/8868461/54939287-93369b80-4efe-11e9-9c00-6ed37b773247.png">

The code for above screenshot:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Testing tiles</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../node_modules/bulma/css/bulma.min.css" />
</head>
<body>
  <div class="tile is-ancestor notification is-light">
    <div class="tile is-parent is-vertical notification is-link">
      <div class="tile is-child notification is-primary">Test data in the tiles</div>
      <div class="tile is-child notification is-primary">Test data in the tiles</div>
      <div class="tile is-child notification is-primary">Test data in the tiles</div>
    </div>
  </div>
</body>
</html>
```

The CSS after using a single icon (no `span` tags) is below. Notice the width b/w tiles is gone, font became bold, font type changed, and icon is showing up multiple places even though code only has it once:
<img width="1680" alt="Screen Shot 2019-03-25 at 1 08 06 PM" src="https://user-images.githubusercontent.com/8868461/54939487-18ba4b80-4eff-11e9-8304-57f779d3712a.png">

The code below:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Testing tiles</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="../node_modules/bulma/css/bulma.min.css" />
</head>
<body>
  <div class="tile is-ancestor notification is-light">
    <div class="tile is-parent is-vertical notification is-link">
      <div class="tile is-child notification is-primary"><i class="fas fa-info-circle"/></div>
      <div class="tile is-child notification is-primary">Test data in the tiles</div>
      <div class="tile is-child notification is-primary">Test data in the tiles</div>
    </div>
  </div>
</body>
</html>
```

The only thing that changed is the first child tile uses an icon now. Same thing with enclosing the icon in a `span` tag.

### Steps to Reproduce
1. Add icons from FontAwesome to a bunch of tiles

### Expected behavior
1. Icons get added without changing font-type, color, boldness, space between tiles, etc.

### Actual behavior

1. Font type, color, boldness, space between tiles changed.

**Comment by errnaa** [comment]
Does this work?
<i class="fas fa-info-circle"></i>

**Comment by errnaa** [comment]
`<i class="fas fa-info-circle"></i>`

**Comment by thinkverse** [comment]
Okay, I think you just had forgotten a closing `</div>` tag, using the same files the only way I can recreate the **bug** is by using this code:
```html
<div class="tile is-ancestor notification is-light">
  <div class="tile is-parent is-vertical notification is-link">
    <div class="tile is-child notification is-primary"><i class="fas fa-info-circle"/></div><i class="fas fa-info-circle"/>
    <div class="tile is-child notification is-primary">Test data in the tiles</div>
    <div class="tile is-child notification is-primary">Test data in the tiles</div>
  </div>
</div>
```
So I'm suspecting user error and not a **bug**

**Comment by errnaa** [comment]
`<i class="fas fa-info-circle"/>`
IS NOT a thing in vanilla HTML.

`<i class="fas fa-info-circle"/>`
IS a thing in most frameworks.

`<i class="fas fa-info-circle"/>`
is rendered as
`<i class="fas fa-info-circle">`
by the browser.

**Comment by errnaa** [comment]
Just follow the example in the documents:
`<span class="icon">
  <i class="fas fa-home"></i>
</span>`
https://bulma.io/documentation/elements/icon/

**Comment by thinkverse** [comment]
Correction @errnaa `<i class="fas fa-info-circle"/>` is valid HTML, it's called a self closing tag, like `<img src=".." />` for example, altought `<i>` does require a closing tag according to the specifications.

**Comment by errnaa** [comment]
Self closing tags can only be used when there can be nothing in the tags.
There can be nothing in an img tag which is why it CAN be used.
There can be something in and i tag which is why it CAN'T be used.

Read more here:
https://www.techopedia.com/definition/31857/self-closing-tag

**Comment by errnaa** [comment]
For example you can't do this:
`<div class="abc"/>`

**Comment by deepankarmalhan** [comment]
@errnaa and @thinkverse your solution worked! I always thought `<i>` was a self-closing tag, and React never complained because it automatically converted it to an empty container tag. This is not a bug, just my lack of knowledge. Thanks for the help!
