### ISSUE TITLE
is-spaced documentation missing?

### ISSUE THREAD

**Issue by selketjah** [jgthms/bulma#2426]
This is about **the Docs**.
This is a question/I need help.

### Overview of the problem

This is about the Bulma **Docs**

I am sure this issue is **not a duplicate**? 
I searched for `is-spaced` in the issues, but did not find anything mentioning it.

### Description

There is a class called `is-spaced` in the sass file of the component of navbar (https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass#L278)
and it is being used for the top navbar of the documentation too, but it is not documented (https://bulma.io/documentation/components/navbar/)
It adds extra padding to the navbar.

Is this missing from the documentation?

### Steps to Reproduce
Look at the source code of the top navbar of Bulma documentation:

<img width="977" alt="Screenshot 2019-03-27 at 14 23 22" src="https://user-images.githubusercontent.com/2250570/55079181-f578d300-509b-11e9-8cbb-76fa2be37da3.png">

### Expected behavior
Documented

### Actual behavior
Not documented

Related issue: https://github.com/Fulma/Fulma/issues/180

**Comment by mi9dev** [comment]
Issue Fix merged as part of #2436. This can be closed.
