### ISSUE TITLE
No control over the size of the widget.

### ISSUE THREAD

**Issue by isum** [jgthms/bulma#2428]
This is about **Bulma**.

### Overview of the problem

I'd like to use Bulma to design a widget, which will be integrated in many different sites.
Therefore I have no control over **html font-size**, on which Bulma relies upon, to size it's elements, apparently (**rem**).
Also, there are files *base/minireset.sass* and *base/generic.sass*, that are tampering with host site **html & body**.
Another thing is, no to control over the margins, paddings, etc...

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.4]

### Description

Although I've overridden *minireset.sass* and *generic.sass* and **nested** them inside my class. Now they don't interfere with the host website design. I propose to refactor **html & body** out  of them.

But the main question remains: what do I do with the sizes? Or maybe I miss anything?
16px is too large for my widget, 14px is much better.
And the margings, paddings, spacings, ... are too large as well.

Maybe we should have 2 more initial variables, on which everything else will depend?
So we have an option not to rely on html.
Say:
```
$font-size 16px !default
$spacing-ratio 1 !default
```

**Comment by adamdehaven** [comment]
@jgthms I found this issue and it's the exact problem I'm running into: I'd like to utilize Bulma on a web component (that will be embedded into the regular DOM of other sites) and have no control over the font-size attribute of the root `html` element. Is there any way to still use Bulma and have the units properly scale? I know Bulma uses `rem` but didn't know if there was any known way to override.
