### ISSUE TITLE
Why bulma always show scroll when height content isn't than height screen?

### ISSUE THREAD

**Issue by hoangdangduy** [jgthms/bulma#2432]
I have a question why scroll always display when my content isn't over than height for height of screen. I must set style `overflow-y: auto;` into tag html. Set like that I afraid that will have hidden problem about responsive or display scroll.
Are anybody can confirm for me about capacity have problem when set css like that?

My bulma version: 0.7.4
Chrome version: 73.0.3683.86 

![QA](https://user-images.githubusercontent.com/8912039/55332079-d5dc1300-54be-11e9-9002-5e381f856b84.png)

**Comment by jgthms** [comment]
It’s to prevent the page from “jumping” when switching between pages that need and don’t need a scrollbar
