### ISSUE TITLE
Bottom list item has rounded corners on wrong edge

### ISSUE THREAD

**Issue by sorenbug** [jgthms/bulma#2435]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.4]
My **browser** is: Google Chrome Dev

I am sure this issue is **not a duplicate**.

### Description

Last items of lists have 4px borders on the top instead of the bottom

### Steps to Reproduce

1. Make a list
2. Have at least 2 elements
3. Select the last one and look at the corners

### Expected behavior

There's rounded edges on the bottom of the item

### Actual behavior

There's rounded edges on the top of the item

![image](https://user-images.githubusercontent.com/7751296/55373504-43397500-54ba-11e9-9a7f-d6a34521ba5d.png)

**Comment by ehne** [comment]
Hello, 
Could you please provide some code to help fix this issue.
Thanks,
darcy

**Comment by ehne** [comment]
@sorenbug , PR #2438 should fix this problem
