### ISSUE TITLE
Question: input/iextarea/select styled by default 

### ISSUE THREAD

**Issue by PayteR** [jgthms/bulma#2437]
Hi, is there any proven way to style inputs, textareas and selects by default? That means, i don't want to set classes to inputs, they will be styled anyway. I came with something like this for now:

```
textarea,
input[type="text"],
input[type="password"],
input[type="datetime"],
input[type="datetime-local"],
input[type="date"],
input[type="month"],
input[type="time"],
input[type="week"],
input[type="number"],
input[type="email"],
input[type="url"],
input[type="search"],
input[type="tel"],
input[type="color"]{
  @extend .input;
}
```
Is it good approach? O do i miss something?

And how do i implement this to the select field? Thank you.

**Comment by anitagraham** [comment]
I agreed with @PayteR that default styling for elements would be a big step forward - albeit not following the Bulma standard of everything being done by classes.  I am just going round adding classes that duplicate the element tag, and it seems "wrong".
