### ISSUE TITLE
Color classes and elements

### ISSUE THREAD

**Issue by wemyss** [jgthms/bulma#244]
### Checklist
- [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [x] I'm using Bulma **version** [0.0.28]
- [x] I am sure this issue is **not a duplicate**?
### Description

I've used this framework for about 2 weeks now, and I think it's awesome! But I just have a question in regards to color classes :).

What is the reason to only use the color classes "is-info" or "is-dark" on certain elements such as buttons, notifications, etc? It means that I am not able to color things like a "column" as "is-error". Should there be seperate more generic color classes, with slight alterations for each element if need be?

This is more of a design question as I'm not too sure myself what the best solution is :).

Thanks!

**Comment by jgthms** [comment]
https://github.com/jgthms/bulma/pull/126
