### ISSUE TITLE
Pagination in hero gets wrong color 

### ISSUE THREAD

**Issue by domiSchenk** [jgthms/bulma#2441]
This is about Bulma.

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.7.4] 
My **browser** is: Google Chrome

I am sure this issue is **not a duplicate**

### Description

When using Pagination in a Hero that is using `.is-white` `.is-warning` or `.is-light`
the color of `.is-current` is black.

### Steps to Reproduce

jsbin:
https://jsbin.com/vohezehute/edit?html,output
=> layout/hero.sass line 20-22
### Expected behavior

Color of `.is-current` item should be white when using default colors.

### Actual behavior

Color of `.is-current` is black and does not looks good.

**Comment by ehne** [comment]
hello @domiSchenk 
PR #2476 should fix this issue.

**Comment by domiSchenk** [comment]
thanks for the fix
