### ISSUE TITLE
Feaure request: tagfield

### ISSUE THREAD

**Issue by giorgi-m** [jgthms/bulma#2446]
Bulma seems to have multiple select: https://bulma.io/documentation/form/select/
But the dropdown seems to be always visible.
Wouldn't it be nice bulma to have also tagfield? e.g. something like this:

 
![tagfield](https://user-images.githubusercontent.com/41240312/56016844-99a28100-5d0e-11e9-94aa-c89ef9e18f7e.jpg)

**Comment by jgthms** [comment]
It’s quite a complex component. You need a list of tags, a text input that follows that list, a container for both, then a dropdown list, and another container for everything. That would be the minimum.

But also, Bulma would only provide the UI. And in this case the implementation will be closely tied to the markup. So I’m not sure that would be easy to maintain. 

I think however that it could exist as a Bulma extension.

**Comment by giorgi-m** [comment]
@jgthms I see there is one: https://wikiki.github.io/form/tagsinput/, though it allows to use only custom tags, no dropdown.

I see bulma also has no date component? Is it because bulma is only css and in case of date component you'd need js methods say to get selected date?
