### ISSUE TITLE
Image overflows even after setting size

### ISSUE THREAD

**Issue by HJain13** [jgthms/bulma#2447]
This is about **Bulma**.

This is a possible **Bug/Feature**.
It's not a browser bug. 

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **0.7.2** 
My **browser** is: Google Chrome v74
I am sure this issue is **not a duplicate**

### Description
After setting image size to be 64x64. A differently sized image overflows, a similar thing doesn't happen when setting as a ratio. 

### Steps to Reproduce

```
<figure class="image is-128x128">
  <img class="is-rounded" src="https://bulma.io/images/placeholders/480x600.png">
</figure>
```

### Expected behavior
![expected](https://user-images.githubusercontent.com/6277011/56078659-41e84080-5e08-11e9-92fd-57fa1df6a102.PNG)

### Actual behavior
![actual](https://user-images.githubusercontent.com/6277011/56078661-457bc780-5e08-11e9-8311-8303dbc7f051.PNG)

### Solution using Bulma as it is right now
```
<figure class="image is-square is-128x128">
   <img class="is-rounded" src="https://bulma.io/images/placeholders/480x600.png" style="object-fit: cover;">
</figure>
```

**Comment by HJain13** [comment]
@jgthms Is this an actual issue or I am way over my head here 😓

**Comment by rsoeldner** [comment]
I run into this issue today as well but with a

```
<div class="box">
  <article class="media">
    <figure class="media-left">
       <p class="image is-128x128"><img src="large.png"></p>
    </figure>
  <div class="media-content">
     <div class="content">
	 <p class="title is-4">Heading 1</p>
	 <p class="subtitle is-6">@User</p>
	<table class="table is-fullwidth is-narrow">
		<tr><td>Name1</td><td>a</td></tr>
		<tr><td>Name2</td><td>b</td></tr>
		<tr><td>Name3</td><td>c</td></tr>
	</table>
	</div>
	</div>
</article>
</div>
```

but your solution is not working for me.

**Comment by HJain13** [comment]
@rsoeldner it seems to be working for me: https://codepen.io/HJain13/pen/PgLPzB
Is this what you intended?

```html
<div class="box">
  <article class="media">
    <figure class="media-left">
       <p class="image is-128x128 is-square"><img src="https://bulma.io/images/placeholders/480x600.png" style="object-fit: cover"></p>
    </figure>
  <div class="media-content">
     <div class="content">
	 <p class="title is-4">Heading 1</p>
	 <p class="subtitle is-6">@User</p>
	<table class="table is-fullwidth is-narrow">
		<tr><td>Name1</td><td>a</td></tr>
		<tr><td>Name2</td><td>b</td></tr>
		<tr><td>Name3</td><td>c</td></tr>
	</table>
	</div>
	</div>
</article>
</div>
```

**Comment by rsoeldner** [comment]
@HJain13 Thank you. Looks like the `is-squared` is fixing it and not the `object-fit`. I was assuming the `is-128x128` is already enforcing image size.

**Comment by HJain13** [comment]
@jgthms shouldn't `is-AxB` force the children `img` tag to be of that particular size?
