### ISSUE TITLE
"Made with Bulma" badges are leaving a cookie

### ISSUE THREAD

**Issue by philshem** [jgthms/bulma#2452]
This is about **Bulma**.

### Overview of the problem

This is a really minor "problem", but linking to the [Bulma badges](https://bulma.io/made-with-bulma/) is leaving a cookie from Cloudflare.

For those of us going for a 100% cookie-free and no-tracking website, it would be cool to host the badges without

### Description

The request to bulma.io for this image:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/4997607/55032474-37a90280-5011-11e9-892a-ef9517580be7.png">

Is leaving the cookie "cfduid" on the browser of website visitors:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4997607/55032360-fb75a200-5010-11e9-98ad-485d2c148b18.png">

This cookie is from CloudFlare and is [not for tracking](https://support.cloudflare.com/hc/en-us/articles/360024915491), and is for determining unique users with a common IP. It's been discussed [here](https://github.com/mozilla/http-observatory/issues/202).

(also posted [here](https://github.com/textbook/bulrush/issues/20))

**Is it possible to host an image hosted on a site that doesn't leave a cookie?**

**Comment by jgthms** [comment]
Ah, I actually didn't know! It's apparently created by Cloudflare automatically, but not by me for sure.

I set up Cloudflare to speed up the website, and also because GitHub Pages did not support `https` at the time. It seems they do now, so we might not need Cloudflare anymore.

**Comment by My1** [comment]
now THAT cookie is fun. depending on the headers the client sends along this can actually be used for tracking (even if CF randomizes the cookie for every domain, the domain the image is from is always bulma.io.)

@philshem just download the image. even without cookies with IPv6 depending on how devices handle it enough tracking is possible, it's better to just host it yourself.
![image](https://user-images.githubusercontent.com/6696524/56540240-68c11800-6568-11e9-88a1-5ac408530036.png)

**Comment by philshem** [comment]
Thanks for looking into it. I would normally download the image and host it myself, but I'm using a theme for python [pelican](https://github.com/getpelican/pelican) called [Bulrush](https://github.com/textbook/bulrush) that is pointing to that badge. I'm trying to not change the theme at all, for a couple reasons (so that I can always simply use `pip install bulrush`, and because the html templates are not part of the hosted repository branch). I know neither of those reasons are related to this repository, but I just wanted to bring the cookie to your attention, and I don't expect Bulma to change their host because of this cookie.

(I've also opened the issue at [Bulrush](https://github.com/textbook/bulrush/issues/20))

**Comment by jgthms** [comment]
If you can't host the image, I'd recommend uploading the one you want on a service like Imgur, or even a S3 bucket if you have that. This would circumvent the cookie.

**Comment by philshem** [comment]
> If you can't host the image, I'd recommend uploading the one you want on a service like Imgur, or even a S3 bucket if you have that. This would circumvent the cookie.

It's more an issue of using a static content generating package that is linking to the bulma.io hosted image. I can change my own code, but if I change that theme's static template, I have to include that static template in my webpage code repository, so that travis-ci to get the fixed template.
