### ISSUE TITLE
Undefined variable?

### ISSUE THREAD

**Issue by PatrickWhitehouse** [jgthms/bulma#2459]
I've just converted Bulma from SASS to SCSS using sass-convert. When running my gulp task to convert SCSS to CSS, i'm getting a constant undefined variable. 

![image](https://user-images.githubusercontent.com/15248507/56441647-b4b05a80-62e5-11e9-9320-b9c4ba896092.png)

I've also not touched the import order of the files either so don't quite get why this is happening?

Any help would be appreciated. 

Thanks.

**Comment by tomhrtly** [comment]
Have you imported the initial variables before `generic.sass`?

**Comment by PatrickWhitehouse** [comment]
> Have you imported the initial variables before `generic.sass`?

Yes, all I've done is convert them from Sass to SCSS.

**Comment by tomhrtly** [comment]
Are you able to share your SCSS setup?

**Comment by PatrickWhitehouse** [comment]
> Are you able to share your SCSS setup?

I've just got a simple gulp setup which includes browser sync and scss to css. Nothing extensive.

**Comment by tjkohli** [comment]
Check your paths. I do this routinely using `sass-convert` and it works fine.

**Comment by MrVibe** [comment]
I am facing the exact same issue. It seems we can not extend the bulma framework by adding our own imports and variables. Any variable I define and try to use in a custom scss file it shows undefined variable.

**Comment by darzove** [comment]
Documentation does clarify this, although it is not as pronounced as it should be imo. 

Ensure you import all utility variables first:

```@import "bulma/sass/utilities/_all.sass"
@import "bulma/sass/grid/columns.sass"```
