### ISSUE TITLE
Vue Bulma Components

### ISSUE THREAD

**Issue by fundon** [jgthms/bulma#246]
Hi, I created the [vue-admin](https://github.com/fundon/vue-admin)，vue + bulma is power.
Currently, I just fished the [Notification](https://vue-admin.fundon.me/#!/ui/notifications) and [Message](https://vue-admin.fundon.me/#!/ui/messages) components.

If someone interest these. Join this project and add more components. 😄

**Comment by jgthms** [comment]
Wow, that's amazing! Great work! 👍 

I'll add it to the readme.

**Comment by fundon** [comment]
Thanks. I'm glad to see that. 👍

**Comment by fundon** [comment]
I added some components:

* [Tabs](http://vue-admin.fundon.me/#!/ui/tabs)
* [Tooltip](https://vue-admin.fundon.me/#!/ui/tooltips)
* [Modal](https://vue-admin.fundon.me/#!/ui/modals)
* [ProgressBar](https://vue-admin.fundon.me/#!/ui/progress)

Thanks again to @jgthms.
