### ISSUE TITLE
Stacked Font Awesome 5.5 icon do not align properly

### ISSUE THREAD

**Issue by Nantor** [jgthms/bulma#2460]
This is about **Bulma | the Docs**.

Is it about Bulma or about the Docs?

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** [0.7.4] -->
My **browser** is: Firefox, Chromium

I am sure this issue is **not a duplicate**? Yes

### Description

Since Font Awesome version 5.5 the stacked icons (may others too) is not squared any more.
So the icons are not correct rendered with Bulma.
So the example from the [Doc](https://bulma.io/documentation/elements/icon/#font-awesome-variations) will not work any more, with Font Awesome version 5.5 or higher.

### Steps to Reproduce

Link too JSFiddle: [https://jsfiddle.net/kpr120yx/](https://jsfiddle.net/kpr120yx/)

**Comment by dawnerd** [comment]
Just ran into this too. With the stacked code from the docs and the FA website this happens:

![image](https://user-images.githubusercontent.com/24781/63405126-94c79b00-c39a-11e9-8b8f-f290849dab82.png)

```html
<span class="icon is-small">
  <span class="fa-stack fa-2x">
    <i class="fas fa-square fa-stack-2x"></i>
    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
  </span>
</span>
```

Removing the `icon` class fixes it (As does adding `is-inline-block`). Looks like it's the `display: inline-flex`

**Comment by Nantor** [comment]
Hi,
it still not work for the newest bulma version 0.8.2 an Font Awesome version 5.13.0.

**Comment by noraj** [comment]
If using fa-2x you should use is-large on the container

![image](https://user-images.githubusercontent.com/16578570/108828402-14a17780-75c7-11eb-9531-37eedffef5d5.png)
