### ISSUE TITLE
flyout option for Navbar

### ISSUE THREAD

**Issue by pkbarbiedoll** [jgthms/bulma#2461]
This is about **Bulma**.

This is a feature request.

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **0.7.4** 

### Description

Bulma's **Navbar** looks and works great, however my org desires flyout options.   Could this be added to Navbar?

**Comment by jgthms** [comment]
Do you have an example?

**Comment by pkbarbiedoll** [comment]
Yes, something like this (for pure functionality demonstration): 

http://cssmenumaker.com/blog/css-flyout-menu-starter-kit/

**Comment by pkbarbiedoll** [comment]
Any updates on this?
