### ISSUE TITLE
Tabs on the navbar

### ISSUE THREAD

**Issue by dcalixto** [jgthms/bulma#2466]
Hello, i would like to know if to place a tabs on the header like the attached screenshot is possible without change the css because every time that i place a tab on the navbar
the tabs is placed  far right or far left to the navbar

![bulma_navbar_item](https://user-images.githubusercontent.com/1009077/57004903-71899d80-6ba9-11e9-8886-3647489acf19.png)

**Comment by jgthms** [comment]
Not really. What you can do however, is placed them in sequence:

```html
<nav class="navbar">
  …
</nav>

<section class="section">
  <div class="container">
    <ul class="tabs">
      <li>…</li>
    </ul>
  </div>
</section>
```

Something like that.

**Comment by dcalixto** [comment]
@jgthms thank you
