### ISSUE TITLE
navbar is-fixed-top together with is-spaced incorrect padding for has-navbar-fixed-top

### ISSUE THREAD

**Issue by sspilleman** [jgthms/bulma#2471]
Its a bug

### Overview of the problem

This is about the Bulma **CSS framework** 
 I'm using Bulma **version** [current]
My **browser** is: Chrome

### Description

navbar **is-fixed-top** together with **is-spaced** leads to incorrect padding

### Steps to Reproduce

1. Add is-spaced *and* is-fixed-top to navbar element classlist
2. Add has-navbar-fixed-top to body or html element
3. See what happens

### Expected behavior

That correct padding is applied to page, including the extra needed padding for is-spaced (1rem = 2 * $navbar-padding-vertical)

### Actual behavior

The extra padding introduced by the is-spaced class is not added either body or html

**Comment by sspilleman** [comment]
Workaround is adding the following to my sass file
```
html, body {
  &.has-navbar-fixed-top {
    padding-top: $navbar-height + 2 * $navbar-padding-vertical
  }
  &.has-navbar-fixed-bottom {
    padding-bottom: $navbar-height + $navbar-padding-vertical
  }
}
```

**Comment by logological** [comment]
> Workaround is adding the following to my sass file

This workaround has no effect for me.

**Comment by sspilleman** [comment]
> > Workaround is adding the following to my sass file
> 
> This workaround has no effect for me.

Are you using SASS / SCSS? It wont work in plain CSS

**Comment by logological** [comment]
>  Are you using SASS / SCSS? It wont work in plain CSS

Yes, it's in the SCSS file I use to generate my site's CSS.

**Comment by StaffOfHades** [comment]
A better fix would be to add a new class, something like has-navbar-spaced, to mantain consistency, & update the sass to be the following:
`html,
body
  &.has-navbar-fixed-top
    padding-top: $navbar-height
    &.has-navbar-spaced
      padding-top: $navbar-height + 2 * $navbar-padding-vertical
  &.has-navbar-fixed-bottom
    padding-bottom: $navbar-height
    &.has-navbar-spaced
      padding-bottom: $navbar-height + 2 * $navbar-padding-vertical`
That way it takes into account if a navbar is spaced or not, and doesnt affect everything.

**Comment by a8t** [comment]
this issue -- https://github.com/jgthms/bulma/pull/1974

made me realize that you need BOTH `has-navbar-fixed-top` and `has-spaced-navbar-fixed-top` in your html element class names
