### ISSUE TITLE
Feature request: ability to show value of progress bar

### ISSUE THREAD

**Issue by Niek** [jgthms/bulma#2473]
This is a feature request for the Bulma **CSS framework**.

Right now the value of a progress bar is not visible, sample code:
```html
<progress class="progress" value="15" max="100">15%</progress>
```

If would be great if the "15%" could be made visible in some way, maybe with a class toggle.

**Comment by emkajeej** [comment]
easiest way to do it: https://codepen.io/anon/pen/wbOBKq

**Comment by Niek** [comment]
Adding a comment here to keep the issue open. I still think this would be a great addition to have in the framework.

**Comment by trapcodeio** [comment]
Yes please we need it.

**Comment by lorenzocarlesso** [comment]
Yes, we'll appreciate the this feature.

**Comment by francesco-loreti** [comment]
What do you think about my solution?
[https://codepen.io/francesco-loreti/pen/yLyRQLp](https://codepen.io/francesco-loreti/pen/yLyRQLp)
But it's not compatible with <progress> tag

**Comment by lorenzocarlesso** [comment]
Sorry  Franceso Loreti but I don't understand your solution. 
Is your proposed solution a new custom progress bar?
