### ISSUE TITLE
Form submit buttons loading animation not visible

### ISSUE THREAD

**Issue by SEAPUNK** [jgthms/bulma#248]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** 0.0.28
* [x] My **browser** is: Chromium 51.0.2704.84 (64-bit)
* [x] I am sure this issue is **not a duplicate**

### Description

`is-loading` class does not work on the `<input type='submit' class='button'>` buttons. Screenshot provided for comparison, the latter is a regular `<a class='button'></a>`

![](http://i.imgur.com/bluIGJa.png)

_Expected behavior:_ Loading spinner animation to show up on the submit button

_Actual behavior:_ No loading spinner

---

Super sweet CSS framework, BTW. I love it :+1:

**Comment by SEAPUNK** [comment]
This is most likely having to do with the `:after` selector, and input having a lack thereof.

**Comment by jens1o** [comment]
You'll can use`<button type="submit" class="button is-danger">Delete Repo forever</button>`

**Comment by SEAPUNK** [comment]
Oh, nice! I didn't know that, I'm definitely doing that. Thanks.

I'll keep this issue open in the meantime, in case jgthms wants to fix it or not.

**Comment by jgthms** [comment]
Yeah, as `<input>` is a self-closing element, it doesn't support the `:after` pseudo-selector. So you need to use `<button>` as @jens1o suggested.
