### ISSUE TITLE
[Question/possible BUG] white button color on blue background

### ISSUE THREAD

**Issue by diomed** [jgthms/bulma#2481]
This is about **Bulma**.

### Overview of the problem

I'm using Bulma **version** [0.7.5] 
My **browser** is: Firefox
I am sure this issue is **not a duplicate**?

### Description:

Button in navigation should be transparent, right?  
Not white on blue background.

https://codepen.io/diomed/pen/oQvaGM?editors=1100

**Comment by jgthms** [comment]
No that's correct. A button has a white background.

**Comment by diomed** [comment]
lol. umm... am I missing something here?
coz text of button is obviously hidden and nothing can be read that way

**Comment by diomed** [comment]
bump!
