### ISSUE TITLE
feature - Modal is-xx sizes

### ISSUE THREAD

**Issue by LukeTOBrien** [jgthms/bulma#2482]
Hello there,

I am working with [Modal](https://bulma.io/documentation/components/modal/) and I require different sizes for different situations.  
For example I might have a input form modal or just a simple alert modal.
I see you have SASS variables, but this would be global affecting the sizes of all modals, I only want some to be different sizes.

My proposal is that you have size classes like: `modal is-small`, `modal is-large` etc  
And would it be possible using % rather than px? e.g. 40% rather than 640px.

This is similar to https://github.com/jgthms/bulma/issues/1479

Whatya think?

**Comment by francesco-loreti** [comment]
UP

**Comment by francesco-loreti** [comment]
I have append in my custom sass file(the sizes are same of "Responsive helpers"):
```
.modal
  .modal-content, .modal-card
    &.is-small
      max-width: 768px
    &.is-medium
      min-width: 769px
      max-width: 1023px
    &.is-large
      min-width: 1024px
      max-width: 1215px
    &.is-xlarge
      min-width: 1216px
      max-width: 1407px
    &.is-full
      min-width: 100%
```
