### ISSUE TITLE
Joo - Niche Multi-Purpose HTML Template Made with Bulma

### ISSUE THREAD

**Issue by mohamdio** [jgthms/bulma#2487]
Hello,

Thanks for this great CSS framework and I want to share my latest work with Bulma community.

**Joo - Niche Multi-Purpose HTML Template Made with Bulma**.

Joo is a niche multi-purpose HTML template created for creative, corporate, business, restaurant, logistics, barber shop and wedding websites with fully RTL support. 15 Full niche templates in one template to get you started quickly.

**Demo**: https://themes.jozoor.com/html/joo/
**RTL Demo**: https://themes.jozoor.com/html/joo/rtl/

#### Features:

- 15 Full Niche Templates
- Made with Bulma ( Fully Compatible )
- Fully RTL Support
- 50+ Unique Elements
- 40+ Inner Pages
- 30+ Portfolio Styles
- 20+ Blog Styles
- Header Side Navigation
- Header Hamburger Menu
- Header Sticky Navigation
- Mega Menu Navigation
- Header Top Bar Styles
- Page Title Layouts
- Revolution Slider
- Working Contact Form
- Google Maps
- Different Header Layouts
- Different Footer Layouts
- Support all Bulma features and extensions
- And Much More…

I hope it will be useful for someone to create any website quickly and easily.

And please can Bulma team share it with Expo page?

Regards. 

![01](https://user-images.githubusercontent.com/2317124/58127016-af13a080-7c14-11e9-8292-aa3bc20aec52.jpg)

**Comment by hanscees** [comment]
do you really mean niche, or do you mean nice? 
If niche I do not understand (probably my bad))

**Comment by rognales** [comment]
@mohamdio Happy buyer here! Great job. Any plan to include admin panel?
