### ISSUE TITLE
Feature Request: Rounded Textarea

### ISSUE THREAD

**Issue by VishwaJay** [jgthms/bulma#2491]
This is about **Bulma**.

### Overview of the feature
This is about the Bulma **CSS framework**

I think for the sake of keeping a uniform look, the corner radius of textareas should appear to match that of same-sized inputs (most types of keyboard inputs, buttons, etc). Thus, if the typical height of an input[type='text'] is 1.25rem, then the corner radius might be: `(text-size + padding + margin + border-size) / 2` or something similar.

Just a thought/idea to ponder.

**Comment by GuilhermeSnts** [comment]
It makes a lot of sense. Actually, we can't use a full rounded design because Bulma doesn't have rounded options in all components. that's cool stuff.

**Comment by diomed** [comment]
totally agree. if one has rounded forms, why not rounded tetarea as well 💯 👍

**Comment by VishwaJay** [comment]
I'm wondering if there can't be some kind of calc() done on the height of an existing element to give the same roundedness by making it 1/2 the height of the single-line elements? I know this can be done in JS, not so sure about CSS.

**Comment by diomed** [comment]
lets not let this one die

**Comment by VishwaJay** [comment]
So, resuscitation or just stale?

**Comment by VishwaJay** [comment]
Anyone else? I'm sure at least someone has some ideas about adding a rounded box around a borderless textarea in pure CSS in order to accomplish this... but I don't know how it might accomplish that without a second element. Come on, anyone?
