### ISSUE TITLE
Version 0.7.5 breaks navbar at 1024px width

### ISSUE THREAD

**Issue by amir20** [jgthms/bulma#2493]
This is about **Bulma**.

### Overview of the problem
When upgrading from version 0.7.4 to 0.7.5, the navbar no longer shows the burger at 1024px. This might be intended but I wasn't able to find anything about it documentation. 

### Description

![test-js-home-page-renders-ipad-viewport-1-diff](https://user-images.githubusercontent.com/260667/58205414-4fa8a580-7c93-11e9-8886-7612d68f9de3.png)

The left is with version 0.7.4 and the right is with 0.7.5. 

### Steps to Reproduce

See screenshot above.

### Expected behavior

For the behavior to remain the same with a patch update. 

### Actual behavior

Broken navbar.

**Comment by emielmolenaar** [comment]
This might be related: the navbar dropdowns don't seem to be working at all here in MS Edge. No problems in Chrome and Firefox.
