### ISSUE TITLE
Setting $navbar-background-color from mixin

### ISSUE THREAD

**Issue by nickwild-999** [jgthms/bulma#2497]
### Overview of the problem

 This is about the Bulma **CSS framework** 

### Description

I am having issues using mixins and variables. I am using with Gatsby.

### Steps to Reproduce

I do have mixins working with regular sass, but when I use with a variable it does not work -  is it user error?

````
+desktop
  $navbar-background-color: $secondary!important

+mobile
  $navbar-background-color: $primary!important
````

**Comment by jgthms** [comment]
Yes that's not possible in Sass. If you check the output CSS, you'll see that it doesn't do anything.

You can however use [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) for that.

```sass
.navbar
  background-color: var(--navbar-bg)

+desktop
  --navbar-bg: $secondary

+mobile
  --navbar-bg: $primary
```

**Comment by nickwild-999** [comment]
Thanks @jgthms. It didn't with variables for some reason, but it worked with hex. So I got a result! :-)

Also just to say thanks so much for a brilliant framework 👍
