### ISSUE TITLE
Use alpha greys instead of solid ones

### ISSUE THREAD

**Issue by gfpacheco** [jgthms/bulma#250]
I just wanted to bring this up for discussion.

I was wondering if you would be open to change the way Bulma uses the grey tones. The way it is now, if I use some of the components over colorful backgrounds the grey colors get very ugly, since they don't adapt from the white background they're used to.

It would allow this:
<img width="450" alt="screen shot 2016-06-21 at 12 28 44" src="https://cloud.githubusercontent.com/assets/3705660/16235601/e5117230-37ab-11e6-8032-784f36a04b83.png">

To become this:
<img width="454" alt="screen shot 2016-06-21 at 12 33 09" src="https://cloud.githubusercontent.com/assets/3705660/16235749/61cf350a-37ac-11e6-9a06-5c714d3cb386.png">

Instead of this:
<img width="453" alt="screen shot 2016-06-21 at 12 32 34" src="https://cloud.githubusercontent.com/assets/3705660/16235756/6706c54c-37ac-11e6-93e0-4a619392bced.png">

I made an experiment and changed all grey colors with the respective `$black` with alpha and created `-invert` greys that come from `$white` with alpha.

This made possible to use all components over colored background and the colors were adjusted automatically: https://github.com/gfpacheco/bulma/tree/alpha-greys

The downside is that I couldn't keep the nice "blue-ish" greys without picking a different base color for every grey. With a little more effort we can make it be.

**Comment by jbrooksuk** [comment]
I think there should be a `.is-alpha` addon class for this.

**Comment by jgthms** [comment]
You can customize the `$white` `$black` `$light` and `$dark` variables.
