### ISSUE TITLE
Pure CSS navbar toggle

### ISSUE THREAD

**Issue by NikiProToss** [jgthms/bulma#2500]
This is about **Bulma** features.

### Overview of the problem

This is about the Bulma **CSS framework**, namely behavior of hamburger menu.

### Description

Right now there is no out-of-the-box functionality for mobile navbar toggle due to Bulma being pure CSS framework. However I found some pure CSS solutions to this feature. 

### Steps to Reproduce

Basic Bulma Navbar with out of the box toggle functionality could be found in [this pen](https://codepen.io/Nikitoss334/pen/KLxaJK).

It uses behavior of  checkbox to style menu based on the state of a checkbox.

In my opinion this issue should be taken for consideration since it uses no JavaScript which means it could be implemented regardless of any JS framework.

**Comment by hanscees** [comment]
Hi, this is great! I am trying to apply your example on a real navbar here:
[navbar example](https://www.bomengids.nl/2019test/hcnav-2019c1.html)

But the codepen doesn't make clear to me how the menuwrap links to a real navbar bulma style.
If you could tip me howto combine the two? 
Sorry, I am not a coder, but more of a tinkerer trying to get a good navbar for my hobby [tree website.](https://www.bomengids.nl/)

**Comment by NikiProToss** [comment]
Hi.

Here I made a codepen using your code. Check it out [here](https://codepen.io/Nikitoss334/pen/GaXZZZ) .

You have to change very little: add checkbox, change hamburger from `<a>` to `<label>`, link them together (`for` attribute with the same value as checkbox `id`). Then add CSS from my codepen (which is basically code from `is-active` class in bulma).

Please let me know if you found any issues with my code or if you have trouble implementing.
> Hi, this is great! I am trying to apply your example on a real navbar here:
> [navbar example](https://www.bomengids.nl/2019test/hcnav-2019c1.html)
> 
> But the codepen doesn't make clear to me how the menuwrap links to a real navbar bulma style.
> If you could tip me howto combine the two? The codepen seems to show (sorry if I dont get it) some translation that happend when you click the hamburger menu.
> But how can I show a complete menu that is hidden inside the hamburger when a screen is small?
> 
> Sorry, I am not a coder, but more of a tinkerer trying to get a good navbar for my hobby [tree website.](https://www.bomengids.nl/)

**Comment by hanscees** [comment]
that is just wonderfull! Thank you very much! Have a look here:
[working page](https://www.bomengids.nl/2019test/hcnav-2019c1.html)

Now I am only looking for a solution to make the menu's in the expanded hamburger menu appear closed as you can see here with a bootstrap method:
[example with boostrap hamburger](https://www.bomengids.nl/2019test/hcnav-2019e.html)

**Comment by NikiProToss** [comment]
Check this  [pen](https://codepen.io/Nikitoss334/pen/GaXZZZ) again. Is that what you want?

**Comment by hanscees** [comment]
> Check this [pen](https://codepen.io/Nikitoss334/pen/GaXZZZ) again. Is that what you want?
> 
> > that is just wonderfull! Thank you very much! Have a look here:
> > [working page](https://www.bomengids.nl/2019test/hcnav-2019c1.html)
> > Now I am only looking for a solution to make the menu's in the expanded hamburger menu appear closed as you can see here with a bootstrap method:
> > [example with boostrap hamburger](https://www.bomengids.nl/2019test/hcnav-2019e.html)

I am sorry I was not clear. I will try to be more precise: 

- On a small  screen you see only the hamburger menu

- if you click on the hamburger the first-hidden broad-screen menu appears as a list of items and these items sometimes have sub-items (in the case of a drop-down menu). 

- However in the list the items the subitems of a drop-down menu are visible right away after clicking on the hamburger menu. That is unwanted . Normally you want to see only the drop-down items, not the sub-menu items. 

So is it possible to producre a way where after clicking on the hamburger menu drop-down lists are not flded-out and sub-items are hidden until you click on a particular dropdown-list 

Like in the bootstrap [example](https://www.bomengids.nl/2019test/hcnav-2019e.html)

Hopefully I've explained it better now.

**Comment by NikiProToss** [comment]
My bad, now I got you, [code here](https://codepen.io/Nikitoss334/pen/GaXZZZ). 

I used radio buttons for this one but idea is the same.

**Comment by hanscees** [comment]
Hi,
although I see no difference in chrome or firefox between the three codepens (should I? ) 
the second one works great. In the first one and the third you can "unfold"  a dropdown menu, but it does not fold back if you click the button twice (I am testing on linux desktop).

But I am totally satisfied with number two: that is wonderful! Thank you so much!
