### ISSUE TITLE
0.7.5: Tile gaps don't work unless each .is-child is wrapped in its own .is-parent, docs unclear

### ISSUE THREAD

**Issue by purrloftruth** [jgthms/bulma#2505]
This is about **both Bulma and the Docs**. Specifically, it is a bug with either Bulma or the docs, depending on developer intent.

### Overview of the problem

This is [potentially] about the Bulma **CSS framework**
This is [potentially] about the Bulma **Docs**
I'm using Bulma **version** 0.7.5
My **browser** is: Safari 12.1.1

I am sure this issue is **not a duplicate**? ❌ There is an issue #2293 opened by @jp06 dealing with this problem from December, but the user stopped at figuring out that wrapping each .is-child in an .is-parent fixed their issue instead of pushing for further clarity for the docs or bug fixes.

### Description

The documentation leads users to believe that they do not have to surround each individual .tile.is-child element with its own corresponding .tile.is-parent element in order for a gap to display between tiles -- on the page, gaps are shown between tiles where multiple .tile.is-child elements are housed within one .tile.is-parent. However, in Bulma 0.7.5, each individual .tile.is-child needs to be housed within its own .tile.is-parent (where .is-vertical is not being used; it was not tested here and its effect here is currently unknown as it has as of yet been unnecessary for my project) for gaps to show up.

### Steps to Reproduce

1. Create a set of three tiles structured as such:
```
# .tile.is-ancestor
|----# .tile.is-parent
     |----# .tile.is-child is-4 notification is-warning
          |----# p.title
          |----# p.subtitle
     |----# .tile.is-child is-4 notification is-warning
          |----# p.title
          |----# p.subtitle
     |----# .tile.is-child is-4 notification is-warning
          |----# p.title
          |----# p.subtitle
```
2. Observe.

### Expected behavior

As intimated by the documentation, a gap should appear between the three tiles.

### Actual behavior

No gap appears between each tile.

### Commentary

Add a surrounding .tile.is-parent to each individual .tile.is-child element. You will find that the gaps reappear. The docs do not seem to make clear that this is necessary.

**Comment by zogar1993** [comment]
Struggled for quite a while until I bumped into this. Docs did not lead me to believe there was an issue with my code.

**Comment by joevandyk** [comment]
I ran into this as well. Docs are wrong?

**Comment by deather** [comment]
Similar issue here. I fixed the gap with this piece of code
```scss
.tile:not(.is-vertical) > .tile.is-child:not(:last-child) {
    margin-right: 1.5rem !important;
 }
```

You can see a preview [here](https://jsfiddle.net/j0p8yLtf/6/).

**Comment by etremel** [comment]
I'm also having this same issue, in the current version of Bulma (0.9.3). The behavior of child tiles is still inconsistent with the docs. Why was this issue closed if it hasn't been fixed?
