### ISSUE TITLE
[ Proposal ] Automated visual testing

### ISSUE THREAD

**Issue by KayakinKoder** [jgthms/bulma#2508]
A question/proposal for the maintainers: what if Bulma were one of the few (maybe only?) CSS frameworks that could claim "all of our releases run through automated visual regression tests on all browsers we support." Is this something you would be interested in the community looking into?

Issues like https://github.com/jgthms/bulma/issues/2503 could become a relative thing of the past.

I don't know much if anything about this myself, but I would imagine there would be a lot of interest from the community in helping do this. It looks like there are frameworks and services out there that make this type of automated testing possible these days.

**Comment by emielmolenaar** [comment]
We might implement something like https://github.com/anandthakker/doiuse (although this particular project isn't really maintained anymore as it seems). Easier to setup I guess, and just as accurate.

**Comment by KayakinKoder** [comment]
I was thinking real visual testing; webpages get generated, screenshots taken, compared for differences from previous version. It looks like there are some commercial solutions out there and one open source project I could find (http://galenframework.com/), but it would require a commercial cross browser testing service.

Some of the commercial solutions provide free usage to open source projects. Something you guys would be interested in?
