### ISSUE TITLE
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading. 

### ISSUE THREAD

**Issue by asliwinski** [jgthms/bulma#2509]
According to [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=bulma.io&tab=desktop) `font-display` should be used to ensure text visibility while the fonts are loading.

[More info](https://developers.google.com/web/updates/2016/02/font-display).

**Comment by Christilut** [comment]
Not stale, Lighthouse test also reports this missing

PS: Don't use stalebot

**Comment by Niek** [comment]
+1 for this (or at least to make it a SCSS variable)

**Comment by frederiksen** [comment]
For Google fonts you can add "&display=swap" to the url.

https://www.infyways.com/fix-ensure-text-remains-visible-during-webfont-load/

**Comment by MadReal** [comment]
> For Google fonts you can add "&display=swap" to the url.
> 
> https://www.infyways.com/fix-ensure-text-remains-visible-during-webfont-load/

you'll still get the error in google pagespeed test even after this tho
