### ISSUE TITLE
Add typescript bulma.d.ts files next to bulma.css

### ISSUE THREAD

**Issue by yaitskov** [jgthms/bulma#2513]
This is about Bulma feature

### Overview of the problem
 

 This is about the Bulma **CSS framework** 
 Webpack and typescript are allowing to check styles used in DOM automatically.

Many other libraries follow that rule and provide .ts.d files together with .css which simplifies
building against them.
This way typoes are catched at build stage not in the browser.

**Comment by yaitskov** [comment]
Look good example: With .ts.d file I already noticed that .burger doesn't exist.

**Comment by jojoblaze** [comment]
Typescript support should be mandatory for new web libraries. 
I have just realized there is no accordion. I need to install bulma-extension but it lacks Typescript support.
