### ISSUE TITLE
[Question] What coding style does bulma use?

### ISSUE THREAD

**Issue by alanaasmaa** [jgthms/bulma#2520]
Title says it all :)

**Comment by CaimDev** [comment]
AFAIK it's all lowercase with hyphens, hex-colours where possible etc. You know, the usual CSS-spec. 

Or were you thinking in terms of a general lint-config for example?

**Comment by alanaasmaa** [comment]
Yes lint config would be awesome

**Comment by james-wasson** [comment]
Take a look at [this file](https://github.com/jgthms/bulma/blob/master/.github/CONTRIBUTING.md#bulma-sass-styleguide) for style guidelines

**Comment by alanaasmaa** [comment]
Thanks @james-wasson
