### ISSUE TITLE
Column gap without default variable

### ISSUE THREAD

**Issue by jvlobo** [jgthms/bulma#2521]
https://github.com/jgthms/bulma/blob/01a1321e12a0cae265a5fa918c7ec5e77f74a879/sass/grid/columns.sass#L469

I was trying to change the gap for my columns by setting the `$column-gap` before Bulma import as documented. But the gap was not changing and I saw that part of the code.

Shouldn't that `--columnGap` be `--columnGap: $column-gap` or just use `$column-gap` instead of `--columnGap`???

**Comment by purrloftruth** [comment]
If something like this looks okay, I'll file a PR:

<img width="549" alt="Screenshot 2019-06-06 18 47 40" src="https://user-images.githubusercontent.com/280610/59071180-9699bc00-888b-11e9-86f4-47ac9534de1d.png">

...etc, etc, etc. I don't know exactly how wordy Bulma typically likes the variable names to be. (Or if that's even a good variable name, but it can easily be changed before I make a commit.)
