### ISSUE TITLE
Add modifier

### ISSUE THREAD

**Issue by temizerm** [jgthms/bulma#2524]
This is about **Bulma**.

It is a question.

It is not a browser bug.

### Overview of the problem

This is about the Bulma **CSS framework**
I dont know which version of Bulma i am using, i downloaded bulma-start in May 2019.
My **browser** is: Firefox.
I dont know if This is a **Sass** issue.
As i searched the web I think this issue is **not a duplicate**.

### Description

Can i add a modifier like is-bordered to img and use it?
Below is what i have done so far.

### Expected behavior

I expected no erors and use is-bordered modifier.

### Actual behavior

{
  "status": 1,
  "file": "<my bulma directory>/node_modules/bulma/sass/elements/image.sass",
  "line": 11,
  "column": 21,
  "message": "Undefined variable: \"$image-border-width\".",
  "formatted": "Error: Undefined variable: \"$image-border-width\".\n        on line 11 of node_modules/bulma/sass/elements/image.sass\n>>       border-width: $image-border-width;\n\n   --------------------^\n"
}

**Comment by jgthms** [comment]
You would need to define that variable first:

```scss
$image-border-width: 2px;
```

**Comment by temizerm** [comment]
Thanks for the response.
Where should i add?

I tried
added the variables to initial-variables.sass
or
image.sass
```


$image-border-width: 4px !default
$image-border-color: #ff00ff !default
$image-border-style: solid !default
```

when i added to image.sass the error become:

{
  "status": 1,
  "file": "/home/merve/Documents/merve/merve_deranchocolate/deranchocolate-bulma/node_modules/bulma/sass/elements/image.sass",
  "line": 22,
  "column": 22,
  "message": "Undefined variable: \"$radius-rounded\".",
  "formatted": "Error: Undefined variable: \"$radius-rounded\".\n        on line 22 of node_modules/bulma/sass/elements/image.sass\n>>       border-radius: $radius-rounded; } }\n\n   ---------------------^\n"
}


a previously defined variable is mentioned when I define variables in image.sass

**Comment by temizerm** [comment]
Thanks for the response.
I added a custom .sass file that's fine now.
Do you encourage to adding custom sass files?
