### ISSUE TITLE
Responsive margin + paddings

### ISSUE THREAD

**Issue by georgfranz** [jgthms/bulma#2527]
### Responsive margins + paddings

I am sure that I am not the first one who needs a different margin and padding setting on tablet and on desktop devices etc.

So, it would be cool if you can do the following thing:

`<section class="section is-marginless-vertical-mobile has-margin-vertical-tablet"></section> `

By default, there are only these entries in the helper.sass:
```
.is-marginless
  margin: 0 !important

.is-paddingless
  padding: 0 !important
```

I've extended this having such things like:

```
is-marginless-tablet
is-paddingless-vertical
has-padding-horizontal
has-margin-vertical-desktop
```
If you don't need all variations (there are a lot...), you can control this by two arrays.

I attach the sass file and a sample output with all variations.

If this is also helpful for anybody else, I can do a pull request.

[margin_sample.css.txt](https://github.com/jgthms/bulma/files/3276839/margin_sample.css.txt)

[margin_responsive.sass.txt](https://github.com/jgthms/bulma/files/3276843/margin_responsive.sass.txt)

Best wishes,
Georg.

_PS: I luv Bulma!!!!_

**Comment by Hibrix-net** [comment]
> 
> ### Responsive margins + paddings
> 
> I am sure that I am not the first one who needs a different margin and padding setting on tablet and on desktop devices etc.
> 
> So, it would be cool if you can do the following thing:
> 
> `<section class="section is-marginless-vertical-mobile has-margin-vertical-tablet"></section> `
> 
> By default, there are only these entries in the helper.sass:
> 
> ```
> .is-marginless
>   margin: 0 !important
> 
> .is-paddingless
>   padding: 0 !important
> ```
> 
> I've extended this having such things like:
> 
> ```
> is-marginless-tablet
> is-paddingless-vertical
> has-padding-horizontal
> has-margin-vertical-desktop
> ```
> 
> If you don't need all variations (there are a lot...), you can control this by two arrays.
> 
> I attach the sass file and a sample output with all variations.
> 
> If this is also helpful for anybody else, I can do a pull request.
> 
> [margin_sample.css.txt](https://github.com/jgthms/bulma/files/3276839/margin_sample.css.txt)
> 
> [margin_responsive.sass.txt](https://github.com/jgthms/bulma/files/3276843/margin_responsive.sass.txt)
> 
> Best wishes,
> Georg.
> 
> _PS: I luv Bulma!!!!_

This is truly amazing! Please, don't hesitate to send a pull request.
I can't believe that I am the first and for the moment the only one to appreciate your great work. 

Many thanks,
