### ISSUE TITLE
.nav-left overtakes .nav-center in mobile view

### ISSUE THREAD

**Issue by selfagency** [jgthms/bulma#253]
### Checklist

* [X] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [X] I'm using Bulma **version** [0.0.28]
* [X] My **browser** is: Chrome
* [X] I am sure this issue is **not a duplicate**?

### Description

In mobile view, `.nav-left` grows and shifts `.nav-center` flush right. 

![screenshot 2016-06-17 12 03 37](https://cloud.githubusercontent.com/assets/2541728/16272604/6375f482-386c-11e6-85bd-60c5d0e23090.png)

![screenshot 2016-06-17 12 04 19](https://cloud.githubusercontent.com/assets/2541728/16272614/710a8cc0-386c-11e6-869c-3d396044d1a6.png)

### Steps to Reproduce

![screenshot 2016-06-17 12 04 03](https://cloud.githubusercontent.com/assets/2541728/16272623/7b874fa8-386c-11e6-995c-358fdd469d66.png)

```
      <nav class="nav">
        <div class="nav-left"><a href="#" class="nav-item nav-toggle"><i class="icon-menu"></i></a></div>
        <div class="nav-center is-hidden-desktop">
            <a href="#" class="nav-item nav-logo is-hidden-tablet">
              <svg viewBox="0 0 263.7 44.7">
                <use xlink:href="#nylon-logo"></use>
              </svg>
            </a>
            <a href="#" class="nav-item nav-share is-hidden-tablet">share</a>
        </div>
        <div class="nav-center is-hidden-mobile">
            <a href="#" class="nav-item nav-n">
              <svg viewBox="0 0 42.9 44.2">
                <use xlink:href="#nylon-n"></use>
              </svg>
            </a>
            <a href="#" class="nav-item nav-fashion">Fashion</a>
            <a href="#" class="nav-item nav-radar">Radar</a>
            <a href="#" class="nav-item nav-beauty">Beauty</a>
            <a href="#" class="nav-item nav-news">News</a>
            <a href="#" class="nav-item nav-music">Music</a>
            <a href="#" class="nav-item nav-video">Video</a>
            <a href="#" class="nav-item nav-guys">Guys</a>
            <a href="#" class="nav-item nav-espanol">Espa&ntilde;ol</a>
            <a href="#" class="nav-item nav-shop"><span>Shop</span>
              <div class="burst">
                <svg viewBox="0 0 62.9 34.3">
                  <use xlink:href="#burst"></use>
                </svg>
              </div>
            </a>
            <a href="#" class="nav-item nav-subscribe">Subscribe</a></div>
        <div class="nav-right"><a href="#" class="nav-item nav-search"><i class="icon-search"></i></a></div>
      </nav>
```

_Expected behavior:_ `.nav-left` should not grow. `.nav-center` should be centered and full width.

_Actual behavior:_ `.nav-left` grows and `.nav-center` gets shifted flush right.

**Comment by jgthms** [comment]
I see what you mean but for the `nav-left` to be centered, the `nav-left` and `nav-right` need to "push" it to the center, and need to grow, hence the `flex: 1` on both left and right but not on the center.

I guess in your case, you want to flip it, and put the `flex: 1` on the center, but it will only work if left and right are of equal width.

**Comment by selfagency** [comment]
I see what you're saying, but then it seems in this case that nav-right simply isn't growing.
