### ISSUE TITLE
Container or Column not taking up the full available width of the screen

### ISSUE THREAD

**Issue by howienoble** [jgthms/bulma#2537]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I have two columns: one for my vertical menu and another as my main content panel.
In my main content panel I have a container with a horizontal rule and a paragraph.

The container is not taking up all the available horizontal space on the screen unless I have a paragraph with a really long text.
Currently the container is only taking up the width of my longest element which is my paragraph.

### Steps to Reproduce

You can view the following example: https://codepen.io/howienoble/pen/qzRJvw
As you can see, the hr element is not taking up all the available horizontal space.

### Expected behavior

I would expect that either a column with the `is-full` attribute or a container with the `is-fullhd` attribute would use up all the available horizontal space available.

### Actual behavior

Neither my column nor my container are taking up all the available horizontal space.

**Comment by james-wasson** [comment]
It does if you follow the [docs](https://bulma.io/documentation/columns/basics/) about `.columns`. Nesting a `section` under the `.columns` is causing the full width column to not work. 
A `.column` must be a direct child of `.columns`

**Comment by howienoble** [comment]
I confirm that this fixes the issue. Thank you @james-wasson
