### ISSUE TITLE
[Question] Any plans to support web components in the future?

### ISSUE THREAD

**Issue by mgenware** [jgthms/bulma#2541]
Some related discussions on [bootstrap](https://github.com/twbs/bootstrap/issues/28131)

**Comment by james-wasson** [comment]
No I don't think @jgthms would want to do this. Bulma is a pure CSS framework so it can be used with any library or set of libraries. **No JS ever**.
**However** you can always design a library using Bulma to support this kind of thing. In fact there already many like this for Vue and [others](https://github.com/jgthms/bulma#related-projects).

**Comment by james-wasson** [comment]
Were you thinking something in CSS for the `:host` or `::slotted` selectors?
