### ISSUE TITLE
Tabs inside card-header

### ISSUE THREAD

**Issue by mikedpid** [jgthms/bulma#2543]
This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.7.5]
My **browser** is: google chrome

### Description

I want the tabs to have fullwidth inside the card-header, tried is-fullwidth but it doesnt work

### Steps to Reproduce

```(javascript)
<div className="card">
    <header className="card-header">
         <div className="tabs is-fullwidth">
               ...
          </div>
     </header>
</div>
```

### Expected behavior
tabs should take the full width of the card-header div

### Actual behavior
tabs take half of the space only
https://i.imgur.com/6i9zjOl.png

**Comment by DevSpeak** [comment]
I'm not sure if you have got this solved yet @mikedpid if not here is one way.

**index.html**
`<div class="tabs fulltabs">`

**style.css**
`.fulltabs {
    width: 100%;
    li {
        width: 50%;
    }
}`

Behavior: https://i.imgur.com/WrRzSY9.png

**Comment by mikedpid** [comment]
Thanks for your help @DevSpeak
