### ISSUE TITLE
spacing between an input text and a group of buttons

### ISSUE THREAD

**Issue by oupala** [jgthms/bulma#2547]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.5]
My **browser** is: Firefox 67.0.4

I am *pretty* sure this issue is **not a duplicate**

### Description

There should be a space between the text input and the group of buttons.

### Steps to Reproduce

See this [jsfiddle](https://jsfiddle.net/9tqvzr8j/2/).

### Expected behavior

There should be a space between the text input and the group of buttons.

### Actual behavior

There is no space between the text input and the group of buttons.

**Comment by james-wasson** [comment]
Add the class `.field` to the `<fieldset>`.
Right now `<fieldset>` is really only used to disable groups of fields all at once.
@jgthms is it intended for `<fieldset>` in inherit all styles of field without adding the class?

**Comment by oupala** [comment]
Thanks for the tip @james-wasson.

It is strange that `fieldset` is not usable in a standard way with bulma.

**Comment by james-wasson** [comment]
It is usable. The only use case is the `disabled` attribute
But if you look at the [contributing guide](https://github.com/jgthms/bulma/blob/master/.github/CONTRIBUTING.md#bulma-sass-styleguide) we can see that classes are the only thing we are supposed to use.
A `fieldset` is a `field` right? So it makes sense in a way.

**Comment by oupala** [comment]
In my opinion, a `fieldset` is *not* a field. It is a **set** of `fields`.

And I can't get the point of your previous comment, can you explain it to me again?

**Comment by james-wasson** [comment]
When we write our CSS in Bulma we are to only make use of classes.
No attributes or tags or generally anything else -- one of the only exceptions being the `disabled` attribute.
This is done to ensure browser compatibility.

So I guess my point is: would you rather have a `.fieldset` class or just use the `.field` class because we have no other options in this framework. (I mean we do but it's against style guides)

**Comment by oupala** [comment]
Oh I see now, you're talking about the way `fieldset` is [documented in bulma's documentation](https://bulma.io/documentation/form/general/#disabled-form):

> You can disable part or a whole form by wrapping a set of controls in a fieldset with a disabled HTML attribute.

where adding an attribute is not the classic way of using bulma.

The strange thing about `fieldset` in bulma is that they are not graphically rendered, by default (I wa staling about that in another issue #2548). I would appreciate to have a `fieldset` class that offers an *enclosure* rendering without being obliged to override default styling in sass file.

**Comment by james-wasson** [comment]
Try something like this:
```HTML
<fieldset class="box">
   <!-- Fields go here -->
</fieldset>
<fieldset class="box" disabled>
   <!-- Disabled fields here -->
   <!-- I have correct spacing - no need for .field class -->
</fieldset>
```

**Comment by oupala** [comment]
Thanks a lot for this answer @james-wasson. This works and it helps me to better understand the philosophy of bulma.

However, this makes a standard box whereas a fieldset has a legend which label has now a line-through from the box line. Real fieldset with border manage the legend to not be line-through-ed.

**Comment by james-wasson** [comment]
Like this:
```HTML
<div class="box">
    <fieldset>
    </fieldset>
</div>
```
Normally just wrapping something in a div fixes a lot of issues.

**Comment by oupala** [comment]
With your first proposal, as said in my previous comment, the frame is manager by the box class and not by the fieldset. Hence the legend has the border line-through:

![fieldset with a class box](https://user-images.githubusercontent.com/13458743/61940681-3b846b80-af96-11e9-8f3f-15e81b0709e5.png)

With your last proposal, the result is a (div) `box` which contains an *invisible* `fieldset` with an attached `legend` which seems to float in the `box`. Here is how it looks:

![a div with a box inside](https://user-images.githubusercontent.com/13458743/61940090-06c3e480-af95-11e9-9f76-5a49d69bc3b0.png)

The `legend` does not clearly appear as a legend. To me, it does look like a label of something, floating somewhere.

What I want is a `legend` that is clearly  distinguishable legend of the `fieldset`, as shown here:

![real fieldset with a real legend](https://user-images.githubusercontent.com/13458743/61940310-70dc8980-af95-11e9-9114-0be641f8af5c.png)

You can notice that the frame is automatically interrupted to not go through the `legend`.

But to achieve that, I had to add some css styling to the sass file, and I'm styling the css instead of adding bulma classes.

```css
fieldset {
  margin: 10px;
  padding: 10px;
  border: 1px solid gray;
  border-radius: 10px;
}

legend {
  padding: 5px;
}
```

I believe that styling the css instead of adding bulma classes to html is not the correct way of using bulma, but I don't see any other way to achieve that. Maybe the look of the second screenshot does not comply the look and feel of bulma...

All thoughts are welcome to let me know what you think of my thoughts.

**Comment by james-wasson** [comment]
There are just some things Bulma doesn't support at this time. We're working to make it better.
Can you open a new issue (with the label stuff) and close this one?
I will work on implementing the changes tonight.

**Comment by oupala** [comment]
I'm ok to close this issue.

And no need to open another issue as #886 already exists and is opened.

**Comment by james-wasson** [comment]
@oupala awesome! I'll try to get this handled tonight so you can probably expect it with the next release.

**Comment by oupala** [comment]
Perfect.

Do not hesitate to ask if your need some testing.
