### ISSUE TITLE
Enforce horizontal tiles?

### ISSUE THREAD

**Issue by goodengineer** [jgthms/bulma#2552]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **0.7.5**
My **browser** is: `Chrome Version 74.0.3729.169 (Official Build) (64-bit)`
Searched the docs and issues and haven't found an answer.

### Description

I'm using tiles to create a grid that I intend to look the same on mobile. I expected the ancestor tile to respond to `is-mobile` class just like columns do, but apparently they don't. Is there a way to enforce the same layout on mobile?

### Steps to Reproduce

This example html should reproduce my case:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
  </head>
  <body>
    <div class="tile is-ancestor is-mobile">
      <div class="tile is-parent">
        <div class="box is-child">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, soluta?
        </div>
      </div>
      <div class="tile is-parent">
        <div class="box is-child">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, soluta?
        </div>
      </div>
    </div>
  </body>
</html>
```

### Expected behavior

The two tiles should be displayed horizontally on mobile

### Actual behavior

The tiles are being wrapped and displayed vertically

**Comment by Notmeor** [comment]
> This is about **Bulma**.
> 
> ### Overview of the problem
> This is about the Bulma **CSS framework**
> I'm using Bulma **0.7.5**
> My **browser** is: `Chrome Version 74.0.3729.169 (Official Build) (64-bit)`
> Searched the docs and issues and haven't found an answer.
> 
> ### Description
> I'm using tiles to create a grid that I intend to look the same on mobile. I expected the ancestor tile to respond to `is-mobile` class just like columns do, but apparently they don't. Is there a way to enforce the same layout on mobile?
> 
> ### Steps to Reproduce
> This example html should reproduce my case:
> 
> ```
> <!DOCTYPE html>
> <html lang="en" dir="ltr">
>   <head>
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <title></title>
>     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
>   </head>
>   <body>
>     <div class="tile is-ancestor is-mobile">
>       <div class="tile is-parent">
>         <div class="box is-child">
>           Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, soluta?
>         </div>
>       </div>
>       <div class="tile is-parent">
>         <div class="box is-child">
>           Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum, soluta?
>         </div>
>       </div>
>     </div>
>   </body>
> </html>
> ```
> 
> ### Expected behavior
> The two tiles should be displayed horizontally on mobile
> 
> ### Actual behavior
> The tiles are being wrapped and displayed vertically

Have you ever resolved this?
