### ISSUE TITLE
Customize using default variables

### ISSUE THREAD

**Issue by jwonlineuk** [jgthms/bulma#2554]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5
My **browser** is: Edge Beta

### Description

I'm not sure from the documentation how to customize using the default variables as part of the customization. For example:

```css
$body-background-color: $white-ter;

@import "../node_modules/bulma/bulma.sass";
```
produces an error because `$white-ter` is undefined at the time I'm trying to define `$body-background-color`.

Should I be importing `utilities/_all` first and then defining using the default variables?

**Comment by arvind0598** [comment]
My main SASS file just consists of a bunch of imports.
The first few lines look like this:
```
@charset "utf-8";
@import "reset";
@import "~bulma/sass/utilities/all";
```

And in my reset.sass, I have this:
```
$primary: #22A39F;
$progress-bar-background-color: #FFF;
```

Have you considered structuring your code as above?
PS: You could use `~bulma/bulma` instead of `../node_modules/bulma/bulma.sass`
