### ISSUE TITLE
[Question] How to break long string on bulma tag

### ISSUE THREAD

**Issue by Laraveldeep** [jgthms/bulma#2555]
For example:
```
<span class="tag">Bulma is a free, open source CSS framework based on Flexbox and used by more than 150,000 developers.</span>
```

How to break this on smaller layouts?

I tried these with no luck
```
overflow-wrap: break-word;
word-wrap: break-word;
word-break: break-word;
word-break: break-all;
```

**Comment by scheinercc** [comment]
Hey @Laraveldeep,
First of all I would change the title from `word` to `string`, as your example includes spaces, otherwise I would expect an example like, `<span>ThisIsOneVeryLongWordWeNeedToWrapSomewhere</span>`.

Also the question might be better suited for StackOverflow ;)

but try this:
```
.your-selector { // needs to be stronger than .tag:not(body)
  white-space: normal; // counteract white-space: nowrap;
  word-wrap: anywhere; // only required if you want to break one long word anywhere
  height: auto; // counteract fixed height: 2em;
}
```

**Comment by james-wasson** [comment]
You can also use the `<wbr>` tag in the place you would like to break the line.
Outlined [here by MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr)

**Comment by scheinercc** [comment]
@Laraveldeep has any of the answers helped you resolve your issue? Can this ticket be closed?
