### ISSUE TITLE
[question] Form input and checkbox in one line

### ISSUE THREAD

**Issue by arturplo** [jgthms/bulma#2558]
Hi im using Bulmaa 0.75
How to display fullwidth input field and checkbox field on same line?

Name:
[_________________________][checkbox]
Actual code:
![Schowek-3](https://user-images.githubusercontent.com/8561816/61166614-c7c37700-a530-11e9-85be-b35615a2c858.jpg)
Actual display:
![Schowek-2](https://user-images.githubusercontent.com/8561816/61166573-33591480-a530-11e9-917e-ced68fe49306.jpg)

**Comment by james-wasson** [comment]
Hi try something like this:
```HTML
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label">From</label>
        </div>
        <div class="field-body">
            <div class="field">
                <p class="control is-expanded">
                    <input class="input" type="text" placeholder="Name">
                </p>
            </div>
            <div class="field">
                <p class="control">
                    <label class="checkbox">
                        <input type="checkbox">
                        I agree to the <a href="#">terms and conditions</a>
                    </label>
                </p>
            </div>
        </div>
    </div>
```
Specifically you need to add `is-expanded` to the `control` you want to be full width
