### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by selfrefactor** [jgthms/bulma#256]
For exapmle, you can enforce the horizontal layout for both columns or nav by appending the is-mobile modifer.

---------
It is nothing, but it is a shame when everything is so perfect. Keep the good work!

**Comment by jens1o** [comment]
Just create a PR if you want to fix it. Also, this is a Website Problem, not bulma itself.

I've just created a PR for you: https://github.com/jgthms/bulma-website/pull/45
