### ISSUE TITLE
Container height

### ISSUE THREAD

**Issue by LukeTOBrien** [jgthms/bulma#2560]
Hi there,

I've just been looking at you [Container documentation](https://bulma.io/documentation/layout/container/).  
You have classes for **width**, such as `.is-widescreen`, `.is-fullhd` but you don't have any for **height**.

A comman thing to want to do it to postion a `<div>` in the center of the screen.  
I have made [a little CodePen example](https://codepen.io/luketobrien/pen/agrYKM) with a centered `<div>`, but I have had to add extra CSS rule to do that:

``` css
  height: 100vh;
  ...
  display: flex;
  justify-content: center;
  align-items: center;
```

Do you think you can add some classes for the height?  
Perhaps `is-full-height` or `is-flex`, `is-centred`?

> Note I used [Css Tricks](https://css-tricks.com/centering-css-complete-guide/)

**Comment by Stewartside** [comment]
@LukeTOBrien You can use the `.hero.is-fullscreen` CSS class to get what you want.

More info can be found here: https://bulma.io/documentation/layout/hero/#sizes
Demo with `has-text-centered`: https://codepen.io/anon/pen/eqvKOr

**Comment by LukeTOBrien** [comment]
Okay thanks, I didn't look at the `hero` element.  
Seems like `is-fullheight` only works with the `hero` not with the `container` as I was using.

I will close this issue.
