### ISSUE TITLE
Tiles size

### ISSUE THREAD

**Issue by focussing** [jgthms/bulma#2561]
This is about **Bulma

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5
My **browser** is: Chrome 75

### Description

I would like to create a layout like this:

![Schermafbeelding 2019-07-16 om 13 51 33](https://user-images.githubusercontent.com/26736152/61292502-a208cd00-a7d1-11e9-8a88-a8480dc168b0.png)

I have implemented it using Bulma's great Tiles and end up like this:

![Schermafbeelding 2019-07-16 om 13 51 42](https://user-images.githubusercontent.com/26736152/61292533-b9e05100-a7d1-11e9-9d70-3097133c30d4.png)

I have two questions:

1) Basically in my case the aspect ratio of the tiles should be fixed, like for example 1:1 or 1:2.
How can I achieve that?

2) For smaller display sizes I would like to have "One" and "Two" besides each other, and not stacked on top of each other.
How can I do that?

Thanks a lot!

**Comment by CN91** [comment]
What is your current code? 

You can use the is-4 and is-4 on both is-parent to split the width of the container to 50/50,

for the bottom row you can try is-2 is-8 is-2  for each parent. The use of is-number can go up to 12 ;).

**Comment by focussing** [comment]
This is my code:

```
<template>
	<div class="section">
		<div class="container">
			<div class="tile is-ancestor">
				<div class="tile is-vertical">
					<div class="tile">
						<div class="tile is-vertical">
							<div class="tile">
								<div class="tile is-parent">
									<article class="tile is-child box">
										<p class="title">One</p>
										<p class="subtitle">Subtitle</p>
									</article>
								</div>
								<div class="tile is-parent">
									<article class="tile is-child box">
										<p class="title">Two</p>
										<p class="subtitle">Subtitle</p>
									</article>
								</div>
							</div>
							<div class="tile is-parent">
								<article class="tile is-child box">
									<p class="title">Three</p>
									<p class="subtitle">Subtitle</p>
								</article>
							</div>
						</div>
						<div class="tile is-8 is-parent is-vertical">
							<article class="tile is-child box">
								<p class="title">Four</p>
								<p class="subtitle">Subtitle</p>
								<div class="content">
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.</p>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.</p>
								</div>
							</article>
							<article class="tile is-child box">
								<p class="title">Five</p>
								<div class="content">
									<p>Lorem ipsum dolor sit amet</p>
								</div>
							</article>
						</div>
					</div>
					<div class="tile">
						<div class="tile is-parent">
							<article class="tile is-child box">
								<p class="title">Six</p>
								<p class="subtitle">Subtitle</p>
							</article>
						</div>
						<div class="tile is-parent is-8">
							<article class="tile is-child box">
								<p class="title">Seven</p>
								<p class="subtitle">Subtitle</p>
							</article>
						</div>
						<div class="tile is-parent">
							<article class="tile is-child box">
								<p class="title">Eight</p>
								<p class="subtitle">Subtitle</p>
							</article>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>
```

**Comment by focussing** [comment]
What I need is that all the 'boxes' keep their aspect ratio while changing the browser width.
So for example square when set to 1:1 aspect ratio.
In the figure above box "One" is not square but rectangular.

**Comment by CN91** [comment]
Removed some unnessecary tile-divs, and added width where needed for the parent tiles. 

<div class="tile is-ancestor">
    <div class="tile is-vertical is-6">
        <div class="tile">
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <p class="title">One</p>
                    <p class="subtitle">Subtitle</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <p class="title">Two</p>
                    <p class="subtitle">Subtitle</p>
                </article>
            </div>
        </div>
        <div class="tile is-parent">
            <article class="tile is-child box">
                <p class="title">Three</p>
                <p class="subtitle">Subtitle</p>
            </article>
        </div>
    </div>
    <div class="tile is-6 is-parent is-vertical">
        <article class="tile is-child box">
            <p class="title">Four</p>
            <p class="subtitle">Subtitle</p>
            <div class="content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu
                    pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat
                    facilisis.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu
                    pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat
                    facilisis.</p>
            </div>
        </article>
        <article class="tile is-child box">
            <p class="title">Five</p>
            <div class="content">
                <p>Lorem ipsum dolor sit amet</p>
            </div>
        </article>
    </div>
</div>
<div class="tile is-ancestor">
    <div class="tile is-parent is-3">
        <article class="tile is-child box">
            <p class="title">Six</p>
            <p class="subtitle">Subtitle</p>
        </article>
    </div>
    <div class="tile is-parent is-6">
        <article class="tile is-child box">
            <p class="title">Seven</p>
            <p class="subtitle">Subtitle</p>
        </article>
    </div>
    <div class="tile is-parent is-3">
        <article class="tile is-child box">
            <p class="title">Eight</p>
            <p class="subtitle">Subtitle</p>
        </article>
    </div>
</div> 

However the aspect ratio is difficult, or to create actual squares. It's not usually done by CSS only. However you can use javascript to measure the current width, and set the height accordingly.

**Comment by focussing** [comment]
Hey thank you for your changes!
Do you think that this would work within tiles?
https://www.w3schools.com/howto/howto_css_aspect_ratio.asp

**Comment by CN91** [comment]
You could try ;) although the width is probably set with mixins since it is responsive already. So you would still have to find some way matching those values.
