### ISSUE TITLE
Documentation issue about using tabs in hero elements.

### ISSUE THREAD

**Issue by arvind0598** [jgthms/bulma#2562]
This is about **the Docs**.

### Overview of the problem

Usage of tabs as suggested in the full height hero documentation is incorrect.

This is about the Bulma **Docs**

I am sure this issue is **not a duplicate**

### Description

In the documentation about full-height heroes, linked [here](https://bulma.io/documentation/layout/hero/#fullheight-hero-in-3-parts), the code given for using tabs isn't the one suggested in the actual tabs documentation.

The essence of the issue lies in the fact that tabs are supposed to just have a \<ul> element inside it for proper styling. The container element in the hero documentation should be a parent of the `.tabs` node, and not the other way around.

Since it was the other way around, it was not possible to use `.is-centered` or `.is-right` on the tabs.

### Steps to Reproduce

```
<div class="hero-foot">
    <nav class="tabs is-boxed">
      <div class="container">
        <ul>
          <li class="is-active"><a>Overview</a></li>
          <li><a>Modifiers</a></li>
          <li><a>Grid</a></li>
          <li><a>Elements</a></li>
          <li><a>Components</a></li>
          <li><a>Layout</a></li>
        </ul>
      </div>
    </nav>
  </div>
```
Add a `.is-centered` to the `.tabs` element.

### Expected behavior

The tabs should be centered.

### Actual behavior

The tabs were not centered.

**Comment by james-wasson** [comment]
For me the `tabs` are centered even with the `container` inside the `tabs`

**Comment by arvind0598** [comment]
Okay, it works for me too, I'm not sure what the issue was back then. I'll be closing this.
