### ISSUE TITLE
Vertical menu with clikable / hoverable element ?

### ISSUE THREAD

**Issue by Epistol** [jgthms/bulma#2564]
This is about **Bulma, feature**.

### Overview of the problem

 This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.7.5]
 I am sure this issue is **not a duplicate**

### Description

Could we have an enhanced vertical menu ? The actual one is a bit "fix", with no interaction possible and all elements are for example, not hoverable or clickable natively, to have a kind-of effect of the sidebar on the current website of bulma.

**Comment by jgthms** [comment]
What do you mean by hoverable?

**Comment by Epistol** [comment]
I mean a bit like an accordion effect or the one you see on wordpress, or either the one on https://bulma.io/documentation/ on the right side.

**Comment by jgthms** [comment]
You would need JavaScript to toggle the state, so it's not really relevant for Bulma. The menu is customisable though: https://bulma.io/documentation/components/menu/
