### ISSUE TITLE
The required error message for a form-field does not align

### ISSUE THREAD

**Issue by scaljeri** [jgthms/bulma#2571]
### Description
I used the example given on the [Bulma webpage](https://bulma.io/documentation/form/general/) for a currency input field. I've made it required and if left empty the error message shows up like this

![image](https://user-images.githubusercontent.com/1078741/61768721-8e202500-ade8-11e9-980b-70e2e410e3ec.png)

This is not as I would expect it, the error message should start below the currency sign.
I first asked the question on [SO here](https://stackoverflow.com/questions/56955163/bulma-form-class-has-addons-gives-alignment-issue-with-my-error-message)

### Steps to Reproduce

This is the HTML I've used

    <form [formGroup]="myForm">
        <div class="field has-addons">
            <p class="control">
                <span class="select">
                    <select formControlName="currency">
                        <option>$</option>
                        <option>£</option>
                        <option>€</option>
                    </select>
                </span>
            </p>
            <p class="control">
                <input formControlName="amount" class="input amount" type="text" placeholder="Amount of money">
                <span *ngIf="isSubmitted && amount.invalid" class="help is-danger">
                        <span *ngIf="amount.errors.min" class="help is-danger">The amount should be bigger than 0.01</span>
                        <span *ngIf="amount.errors.required" class="help is-danger">This field is required</span>
                </span> 
            </p>
        </div>

### Expected behavior

I've tried to position the error message HTML below that form field

    <form [formGroup]="myForm">
        <div class="field has-addons">
            <p class="control">
                
            </p>
        </div>
        <span *ngIf="isSubmitted && amount.invalid" class="help is-danger">
                        <span *ngIf="amount.errors.min" class="help is-danger">The amount should be bigger than 0.01</span>
                        <span *ngIf="amount.errors.required" class="help is-danger">This field is required</span>
          </span> 

Which looks like

![image](https://user-images.githubusercontent.com/1078741/61769264-f58aa480-ade9-11e9-8a9f-1a4ae1e7efe8.png)

Horizontally the position is ok now, but the vertical spacing is wrong. The documentation doesn't say anything about this (composed form field with error message). 

Is there a way to fix this?

**Comment by james-wasson** [comment]
Pulled directly from the [documentation](https://bulma.io/documentation/form/general/#horizontal-form) and modified to fit this use case:

```HTML
  <div class="field">
    <div class="field-body">
      <div class="field">
        <div class="field has-addons">
          <p class="control">
            <span class="select">
              <select formControlName="currency">
                  <option>$</option>
                  <option>£</option>
                  <option>€</option>
              </select>
          </span>
          </p>
          <p class="control">
            <input formControlName="amount" class="input amount" type="text" placeholder="Amount of money">
          </p>
        </div>
        <p *ngIf="isSubmitted && amount.invalid" class="help is-danger">
          <span *ngIf="amount.errors.min">The amount should be bigger than 0.01</span>
          <span *ngIf="amount.errors.required">This field is required</span>
        </p> 
      </div>
    </div>
  </div>
```

I think this should get you.

Best of luck!

**Comment by scaljeri** [comment]
@james-wasson thanks, that did the trick
