### ISSUE TITLE
.table-container not working on desktop

### ISSUE THREAD

**Issue by stanolacko** [jgthms/bulma#2572]
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5
My **browser** is: Chrome 74

I have big table in table-container, which is scrollable on small devices.
But on desktop, if table is bigger than screen, it's not possible to scroll hidden content on right side, which is possible on mobile device.

**Comment by james-wasson** [comment]
Can you give us an example: jsFiddle, CodePen, etc.?

**Comment by james-wasson** [comment]
My best guess would be you're not wrapping the table in a `.table-container`.
However that's not your fault as the documentation doesn't mention it at all. 

Here is a working [jsFiddle](https://jsfiddle.net/james_wasson/2gfshrob/) (Notice the div wrapping the whole table)

**Comment by james-wasson** [comment]
Please don't close this issue until the documentation is updated.

**Comment by stanolacko** [comment]
@james-wasson You are right. 
But check this [jsFiddle](https://jsfiddle.net/smj5ubhx/) and try to expand right iframe for size where columns will be in one row.
In this case, table is not scrollable.
![image](https://user-images.githubusercontent.com/1910456/61803113-e4fe1c80-ae31-11e9-8883-e494919f1775.png)

**Comment by james-wasson** [comment]
@stanolacko looks to be an issue with the flex property.
Instead of wrapping the `.table-container` in a `.column` try putting the `.column` on the `.table-container`:
```HTML
<div class="columns">
    ...
    <div class="column table-container">
        <!-- Table goes here -->
    </div>
    ...
</div>
```

**Comment by stanolacko** [comment]
Perfect. It works.
Yes this will be fine to put to documentation.
Thanks a lot for help.

**Comment by james-wasson** [comment]
@stanolacko You're welcome 😄

**Comment by stanolacko** [comment]
It will be good to mention in docs also my case: table_containter in column.

**Comment by Bizcuit** [comment]
Hi @james-wasson 
I have the same problem, but my table is nested deep inside the column. That's why it is not possible to apply the fix suggested above. I played a bit with CSS without any success. It only works when I disable "display: flex" on the "columns" class and chrome automatically fallsback to "display: -webkit-box".
Do you guys have any ideas how this can be fixed?

**Comment by james-wasson** [comment]
@Bizcuit I can help more if you produce a simple JSFiddle or something so I can try to fix it.

**Comment by Bizcuit** [comment]
Thanks @james-wasson. It is the same as mentioned above.

Here you go: https://jsfiddle.net/89jesr6g/7/

I just found a dirty workaround. It works if you wrap ".table-container" with another div that has "display: grid"

smth like
```
<div style="display: grid">
<div class="table-container">.....table goes here.....</div>
</div>
```

**Comment by james-wasson** [comment]
@Bizcuit If you just want the column to scroll you can use
`<div class="column" style="overflow: auto;">`

**Comment by Bizcuit** [comment]
@james-wasson 
My entire application has a two column structure. So basically "columns" div is at the very top of the dom hierarchy. Scrollable tables is just a small piece of a content that is in one of two columns. The idea was that only this table is scrollable and not the whole column. Otherwise would have been too simple to fix it :)

**Comment by james-wasson** [comment]
Yeah, I dunno.
This really seems like a problem with the specs.
I did find one other solution:
- Put `max-width: 100%` on `.columns`
- Put `max-width: 100%` on `.column`

```HTML
<div class="columns" style="max-width: 100%">
  <div class="column" style="max-width: 100%">
        <div class="table-container">
      <table class="table is-bordered">
        <thead>
          <tr>
            <th>AAAAAAAAAAAAAAAAAAAAAA</th>
            <th>BBBBBBBBBBBBBBBBBBBBBB</th>
            <th>CCCCCCCCCCCCCCCCCCCCCC</th>
            <th>DDDDDDDDDDDDDDDDDDDDDD</th>
            <th>EEEEEEEEEEEEEEEEEEEEEE</th>
            <th>FFFFFFFFFFFFFFFFFFFFFF</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>
```

**Comment by Bizcuit** [comment]
@james-wasson 
interesting... I've just tried it... Looks like this approach works with very simple html, but in my case it actually becomes even worse. It becomes a mixture of scrolling and hidden content :) Either a problem in the spec or in the html engine of chrome. Have not tried it yet on other browsers though.

**Comment by james-wasson** [comment]
Well I'm sorry I couldn't help more.
If you find any other solutions post them here so we can incorporate the into Bulma if possible

**Comment by Bizcuit** [comment]
Thanks a lot for help, @james-wasson 
As mentioned before, I found a workaround. Probably not the best one, but works in chrome (which is ok for my app). 

```
<div style="display: grid">
    <div class="table-container">
        <table class="table">...</table>
    </div>
</div>
```

**Comment by Bizcuit** [comment]
@james-wasson

Here is an example of the fix:
https://jsfiddle.net/8ebcyLf1/

And here is the original one that has an issue:
https://jsfiddle.net/89jesr6g/7/

Hope this helps. 

PS: You guys are working on a fantastic project. Big thanks to the entire team!
