### ISSUE TITLE
is-primary doesn't use primary

### ISSUE THREAD

**Issue by twobitunicorn** [jgthms/bulma#2576]
This is about Bulma.

Bulma

Budz?

Nope.

### Description

Modifying $primary doesn't effect $is-primary.  I am not sure if this is intended, but I had assumed that if a button was primary, then it should have the primary color.  Not sure if this is a bug or by design.

**Comment by jgthms** [comment]
What does your Sass code look like?

**Comment by twobitunicorn** [comment]
I am setting `$primary: green;` and using the `button.is-primary` that I get from bulma.css.  That looks like this

```
.button.is-primary {
     background-color: #00d1b2;
    border-color: transparent;
     color: #fff;
}
```

I would assume background-color should be set to primary.

**Comment by gragland** [comment]
@twobitunicorn The button background color is not green because you're overriding it with `background-color: #00d1b2;`.

**Comment by james-wasson** [comment]
@twobitunicorn At what point are you defining the variable?
Take a look at [this documentation page](https://bulma.io/documentation/customize/variables/)
Specifically:
> To override any of these variables, just set them **before** importing Bulma.

**Comment by twobitunicorn** [comment]
@gragland That background-color is imported from Bulma.css.  I assumed that when I set `$primary`, that it would change `background-color` to the color that I set, not a fixed color of `#00d1b2`.   The question is if that was intended that Bulma set it explicitly, or if it should have been set by 'primary'.

I have been defining the variables before I import Bulma.  For example, I want to set `$orange`, but it isn't getting set.

**Comment by gragland** [comment]
If you comment out `background-color: #00d1b2;` does it work as intended? Not sure I understand why your also setting a color in that style, rather than just `$primary: green;`

**Comment by twobitunicorn** [comment]
The question I am trying to answer is "If I use the class `$is-primary` on a button, what color should the button be?".  If I set the derived variable `$primary`, I assumed that the color of the button should be the color that I have set in `$primary`.  However, this is not the case.

Commenting out `background-color: #00d1b2;` would require me to modify `bulma.css`.  I want to use Bulma without modifying it.  More than happy to make a pull request if this is what is intended.

**Comment by james-wasson** [comment]
Have you imported your variable file before or after the SASS?

**Comment by twobitunicorn** [comment]
I have imported the file before.
```
// Import custom variables
@import "variables";

// Import Bulma and Buefy styles
@import "~bulma";
```

**Comment by gragland** [comment]
@twobitunicorn Ah sorry, misunderstood where that css was coming from.

**Comment by james-wasson** [comment]
Can we take a look at that variable file?

**Comment by twobitunicorn** [comment]
Here is the variable file
```
$orange: #e8934b;
$primary: #374f78;
$modal-background-background-color: rgba($red, 0.86) ;
```
And the version is "0.7.5".  I am using Nuxt and Beufy also.

**Comment by james-wasson** [comment]
And you're sure you're not importing any part of Bulma before that moment?
`$modal-background-background-color` gets set in the modal file itself while `$orange` and `$primary` are set in `utilities/initial-variables.sass` and `utilities/derived-variables.sass` respectively.

**Comment by james-wasson** [comment]
On Buefy's website they have an example:
```SASS
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```
which is wrong. Don't import Bulma before hand at all!
Do like this:
```SASS
// Set your colors

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

**Comment by james-wasson** [comment]
More info [from the Nuxt repo](https://github.com/nuxt/nuxt.js/issues/1092). Maybe you can use this loader to set your globals?

**Comment by twobitunicorn** [comment]
Yes, I will give it a try.  Let me see where I can get today.  Thanks again for helping me along @james-wasson @jgthms and @gragland !

**Comment by MalvinJay** [comment]
@twobitunicorn Were you able to get to the root of this issue? Kinda have a similar challenge

**Comment by jgthms** [comment]
> Here is my scss file.
> 
> ```
> // Import custom variables
> @import "variables";
> 
> // Import Bulma and Buefy styles
> @import "~bulma";
> ```
> 
> where `_variables.scss` defines my colors.

Aren’t you missing an underscore in the filename when importing it?

**Comment by MalvinJay** [comment]
![tempsnip](https://user-images.githubusercontent.com/17595758/72326699-94140600-36a7-11ea-83d8-4852afb56e67.png)

I did that on my end but still having issues. "section.is_primary" won't take the default primary's color as the background color but rather set's a transparent background

**Comment by jgthms** [comment]
Sections don’t come in different colors. But the hero elements do. Try that.
