### ISSUE TITLE
Using Tags in Media Object creates ugly scrollbars

### ISSUE THREAD

**Issue by fcandi** [jgthms/bulma#2578]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.7.5.

### Description

When using a group of Tags in Media-Object, additional vertical scroll bars appear on small screens.

Its easy to reproduce, I combined s striped down combination out of the docs, see here:

```
<article className="media">
    <div className="media-content">
        <div className="content">
            <p>
                <strong>John Smith</strong> <small>@johnsmith</small> <small>31m</small>
                <br/>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu
                pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat
                facilisis.
            </p>
            <div className="tags are-medium">
                <span className="tag">All</span>
                <span className="tag">Medium</span>
                <span className="tag">Size</span>
            </div>
        </div>
    </div>
</article>
```

### Expected behavior

There should be no scroll bars.

See screenshot. Did I miss something? I already tried to wrap the tags in many differnet kinds of tags,  containers.. but nothing helps.

<img width="509" alt="Bildschirmfoto 2019-07-31 um 15 38 04" src="https://user-images.githubusercontent.com/153574/62216535-374aba80-b3a9-11e9-8636-7e39941aa30d.png">

**Comment by ivansenic** [comment]
@fcandi I had a same problem, but then figured out that these scroll bars are result of having a `<p>` inside of the `media-content`.. Was lazy to check why exactly..

**Comment by jgthms** [comment]
The issue comes from this rule:

```css
@media screen and (max-width: 768px) {
  .media-content {
    overflow-x: auto;
  }
}
```

I believe it's here to prevent the content from over-expanding horizontally. There might be a workaround.

**Comment by fcandi** [comment]
Hey, thx @ivansenic and @jgthms for the good hints.

I just set it to     

`overflow-x: visible; `

for the moment. And it works just fine.

Andreas
