### ISSUE TITLE
The documentation link for `.header` is missing

### ISSUE THREAD

**Issue by vdh** [jgthms/bulma#258]
The [Container](http://bulma.io/documentation/layout/container/) documentation is the only place I can find that mentions `.header`.

After much confusion, I tried a wild guess and managed to find http://bulma.io/documentation/layout/header/
but this page is not linked to from the Layout documentation's tabs (Container, Hero, Section, Footer).

**Comment by jbrooksuk** [comment]
It looks broken to me:

![image](https://cloud.githubusercontent.com/assets/246103/16372575/2e1f3bf4-3c45-11e6-8371-07d0df9c234e.png)

**Comment by jbrooksuk** [comment]
Also, this issue needs to be opened on https://github.com/jgthms/bulma-website/issues

**Comment by vdh** [comment]
Ok: https://github.com/jgthms/bulma-website/issues/46
