### ISSUE TITLE
table is-fullwidth is not working when setting a (maximum) height

### ISSUE THREAD

**Issue by CN91** [jgthms/bulma#2580]
### Overview of the problem

 This is about the Bulma **CSS framework**

 I'm using Bulma **version** [^0.7.5] 
My **browser** is: Chrome / IE / Firefox
 I am sure this issue is **not a duplicate**

### Description

When I try to set a maximum height for a table, to be able to use scroll (overflow-y) it either:
- ignores values like height & max-height;
- when also using display: block, it stops ignoring the set height however the is-fullwidth stops working ! 

### Steps to Reproduce
Use below code: 

` <table class="table is-fullwidth" >
                        <thead>
                            <tr>
<th> test  </th>
                        <th> test 2</th>
</tr>
                        </thead>
                        <tbody style="display:block; max-height: 10vh">
<tr><td></td><td></td></tr>
<tr><td></td><td></td></tr>
<tr><td></td><td></td></tr>
<tr><td></td><td></td></tr>
<tr><td></td><td></td></tr>
</tbody></table>`

To fully reproduce, put enough rows in it, to create a table that overflows the size you want it to have. You can test it with 10vh.

### Expected behavior
is-fullwidth shouldn't stop working, or  that I would have been able to at least set a maximum height for overflow to be able to kick in. 

### Actual behavior
Not being able to set maximum height for a table, nor able to create a table in which you have to scroll (only tbody preferably) with is-fullwidth also properly working. is-fullwidth stops working when you use display-block (is needed for height/max-height to work).

**Comment by CN91** [comment]
Trying to use the following snippet, https://codepen.io/wikiki/pen/JyMYLd  also doesn't work! 
The snippet doesn't actually load bulma, so it doesn't even use the actual is-fullwidth. When trying to use it with actual bulma and is-fullwidth the is-fullwidth is ignored.

**Comment by CN91** [comment]
My current workaround; using two tables. 

                        <div class="tile is-child box">
                            <p class="subtitle">Open orders</p>
                            <table class="table is-fullwidth is-marginless table-header-padding">
                                <thead>
                                    <tr>
                                        <th> test </th>
                                        <th> test </th>
                                    </tr>
                                </thead>
                            </table>
                            <div class="table-container">
                                <table class="table is-fullwidth">
                                    <tbody>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                        <tr>
                                            <td> 2</td>
                                            <td>3</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

And in CSS 

.table-container {
  height: 200px;
  overflow-y: scroll;
    width: auto;
  }

  .table-header-padding th{
    padding-left: 0.2rem;
  }

**Comment by CN91** [comment]
However this isn't optimal when having more than two columns. Header elements have different sizing :(. 

Any other ideas are welcome.

**Comment by baijiahei** [comment]
same issue
