### ISSUE TITLE
Basic navbar with IE11

### ISSUE THREAD

**Issue by GrandGTO** [jgthms/bulma#2581]
Hi,
I noticed that the dropdown menu is not working properly with Internet Explorer 11.
I use this example : https://bulma.io/documentation/components/navbar/#basic-navbar

**Comment by AltMcDermot** [comment]
This is also happening on Edge, the dropdown on http://bulma.io doesn't open on hover.

**Comment by emielmolenaar** [comment]
Duplicate of https://github.com/jgthms/bulma/issues/2503

**Comment by Niek** [comment]
Workaround @ https://github.com/jgthms/bulma/issues/2503#issuecomment-519650331
