### ISSUE TITLE
full height video bulma

### ISSUE THREAD

**Issue by six501** [jgthms/bulma#2583]
This is about **Bulma | the Docs**.

yes

need help

### Overview of the problem

 This is about the Bulma **CSS framework** 

 I'm using Bulma **version** [0.7.5] 
My **browser** is: chrome

 I am sure this issue is **not a duplicate**? 
yes

### Description

Why is my video displaying over content already place at the top of the page
### Steps to Reproduce

1. First Step
I place a section class with the class of .hero-video is-fullheight  video .
inside that a div with a class of .hero-video 
2. Second Step
and inside that a video tag 
3. and so on...

### Expected behavior

a full height video at the bottom of my page.

### Actual behavior

Its displaying at the top of my page over content.

**Comment by rajasimon** [comment]
I have the same problem. I just want to add a full height video to the hero card and I can't find away. And without anything Bulma reset the image to half I don't understand why.
