### ISSUE TITLE
Expose $column-gap var in documentation

### ISSUE THREAD

**Issue by scheinercc** [jgthms/bulma#2586]
I guess this could go somewhere here: https://bulma.io/documentation/columns/basics/ ?
https://github.com/jgthms/bulma/blob/a413a7086a36dbfe57bf4d62c7ee2f4e63377484/sass/grid/columns.sass#L1

**Comment by jgthms** [comment]
It’s here https://bulma.io/documentation/columns/gap/

**Comment by scheinercc** [comment]
@jgthms sry for not following [RTFM](https://en.wikipedia.org/wiki/RTFM) just an fyi why I also might have missed it was, because I was looking for a `Variables` table at the bottom of each `/columns` page (I mean like: https://bulma.io/documentation/elements/button/#variables) and assumed there was nothing documented when I didn't find this table.
