### ISSUE TITLE
Overriding Font Awesome base class breaks size modifiers

### ISSUE THREAD

**Issue by gfpacheco** [jgthms/bulma#259]
### Checklist
- [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [x] I'm using Bulma **0.28.0**
- [x] My **browser** is: Chrome 51
- [ ] This is a **Sass** issue: I'm using version [x.x.x]
- [x] I am sure this issue is **not a duplicate**?
### Description

Overriding Font Awesome base class breaks it's size modifiers (`fa-lg`, `fa-2x`).
### Steps to Reproduce
1. Add `<i class="fa fa-2x"></i>` to a page with Font Awesome and Bulma

_Expected behavior:_ The icon becomes bigger

_Actual behavior:_ The icon size doesn't change

**Comment by jgthms** [comment]
The `.icon` element does not style `.fa` anymore.
