### ISSUE TITLE
Bulma.css file not found

### ISSUE THREAD

**Issue by mrosenbaum15** [jgthms/bulma#2596]
I've installed Bulma using npm and am trying to link it in an HTML file. I am working in Electron.
I included this in the had of my HTML file: 

`        <link rel="stylesheet" href="/node_modules/bulma/css/bulma.css"> `

When I run my app and view the dev console, I get this error: 

> Failed to load resource: net::ERR_FILE_NOT_FOUND

The same thing happens when trying to link any files within the node_modules folder. How do I get rid of this error?

**Comment by james-wasson** [comment]
This is not a problem with Bulma and should be directed towards StackOverflow or some other forum.
But I went ahead and did a google search and maybe this can help:
https://stackoverflow.com/questions/30664111/how-to-use-node-modules-within-electron

**Comment by jgthms** [comment]
Thanks @james-wasson
