### ISSUE TITLE
.textarea doesn't honor <textarea>'s `rows` attribute

### ISSUE THREAD

**Issue by cvrebert** [jgthms/bulma#26]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-rows

**Comment by jgthms** [comment]
This is for the [Bulma website repository](https://github.com/jgthms/bulma-website). Please submit an issue there or submit a PR.

**Comment by cvrebert** [comment]
@jgthms No, this is an alleged CSS bug.

**Comment by jgthms** [comment]
Ah sorry, I understood it wrong.

Do you mean that the `rows` attribute should set the textarea's initial height accordingly?

**Comment by cvrebert** [comment]
Correct.
Or if that's not possible, then note the limitation in the documentation.

**Comment by omgaz** [comment]
I'd prefer for Bulma to not dictate the height of the textarea at all and to have it defined by the rows attribute instead.

**Comment by slashdotdash** [comment]
@cvrebert and @omgaz The following CSS style resets textarea elements to a height dependent upon their `rows` attribute.

```css
textarea,
.textarea {
  min-height: inherit;
  height: auto;
}
```

**Comment by noxecane** [comment]
I would suggest you extract the `min-height: 120px` settings to another class. Or you add maybe `raw` class that  implements @slashdotdash's solution
