### ISSUE TITLE
[Feature Request] Three dots ellipsis dropdown

### ISSUE THREAD

**Issue by truongnmt** [jgthms/bulma#2606]
## Overview of the problem
This is about the Bulma CSS framework

## Description
I looking for a simple way to create dropdown with button is three dot, ellipsis only, no down arrow.
![Aug-25-2019 13-34-53](https://user-images.githubusercontent.com/11817656/63645602-32292300-c73d-11e9-89d3-3080c06f7864.gif)

**Comment by truongnmt** [comment]
Actually do-it-myself. Just change the icon:

```html
<div class="dropdown post-options">
  <div class="dropdown-trigger">
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu-post">
      <span class="icon is-small">
        <i class="fas fa-ellipsis-h" aria-hidden="true"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu-post" role="menu">
    <div class="dropdown-content">
      <a href="#" class="dropdown-item">
        Update
      </a>
      <a class="dropdown-item">
        Delete
      </a>
    </div>
  </div>
</div>
```

**Comment by bartmika** [comment]
Thank you @ truongnmt! I think this is still a valuable issue.
