### ISSUE TITLE
Question : Control with add-ons which has icons 

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#261]
### Checklist
- [X] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [X] I'm using Bulma **version** [0.1.0]
- [X] My **browser** is: Chrome
- [ ] This is a **Sass** issue: I'm using version [x.x.x]
- [ ] I am sure this issue is **not a duplicate**?
### Description

I'm trying to create a form including controls with add-ons and icons but when I use the following code
`<form class="has-text-centered">
                    <p class="control has-addons">
                        <span class="control has-icon">
                            <input class="input is-large" type="text" placeholder="Catégorie, Nom, Mot clé">
                            <i class="fa fa-search"></i>
                        </span>
                        <span class="control has-icon">
                            <input class="input is-large" type="text" placeholder="Ville, Code postal">
                            <i class="fa fa-map-marker"></i>
                        </span>
                        <button class="button is-primary is-large">Trouver un projet</button>
                    </p>
                </form>`

The control doesn't take full-width as in the documentation.
How can I use icons within addons ?

![capture d ecran 2016-06-30 a 11 45 52](https://cloud.githubusercontent.com/assets/10529979/16484208/4efa551e-3eb8-11e6-8f2f-6db70ff546be.png)

**Comment by jeppech** [comment]
I'm facing the same issue, i think the following structure would make sense:
```html
<div class="control has-addons">
	<div class="control has-icon">
		<input type="date" class="input is-small">
		<i class="fa fa-calendar"></i>
	</div>
	<div class="control has-icon">
		<input type="button" class="button is-small">
		<i class="fa fa-search"></i>
	</div>
</div>
```

This should render an input field with an icon, and a button on the right, only containing an icon.

**Comment by jgthms** [comment]
Let me have a look.

**Comment by Wikiki** [comment]
Hi,

Any news for this issue ?

**Comment by jgthms** [comment]
You can do it with the new field element: http://bulma.io/2017/03/10/new-field-element/
