### ISSUE TITLE
Modal weird overlay shadow

### ISSUE THREAD

**Issue by hiendv** [jgthms/bulma#2613]
This is about **Bulma**. This is a bug with Modal component.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5
My **browser** is: Version 76.0.3809.132 (Official Build) (64-bit)
I am sure this issue is **not a duplicate**

### Description
There is an unknown box shadow area behind the modal-content.
![Screenshot from 2019-09-03 15-08-10](https://user-images.githubusercontent.com/1917947/64155630-567fb080-ce5d-11e9-8a53-4c08cbeda056.jpg)

Click and open the image in full-size. It's kinda hard to see but it's there. I tagged the corners with 4 "x".

### Steps to Reproduce
1. Go to the official docs of Modal. https://bulma.io/documentation/components/modal/
2. Launch the first example modal.
3. Carefully watch for the unknown box shadow area behind the content. You could delete the close button to notice the different.

### Expected behavior

It should not be there.

### Actual behavior

There is a weird box shadow there.

**Comment by jgthms** [comment]
I can't reproduce this on Chrome/Mac. What browser are you on? Can you disable your extensions?

**Comment by hiendv** [comment]
@jgthms Chrome Version 76.0.3809.132 (Official Build) (64-bit) in Ubuntu 18.04

**Comment by hiendv** [comment]
@jgthms It's also contrast-biased. Do you notice the different when remove the "X" icon?

**Comment by hiendv** [comment]
Can't reproduce Firefox. I guess something is wrong with Chrome in my PC.
