### ISSUE TITLE
how to fill blank vertical spaces in columns alignment

### ISSUE THREAD

**Issue by rizwan92** [jgthms/bulma#2618]
Is it a bug/feature/question or do you need help? 

### Overview of the problem

how to fill blank vertical spaces in columns alignment

I am putting video link here to show you my problem

### Description

I am rendering the columns dynamically, to align columns I am using is-multiline class>
but my first column is very big in height and the next two columns are small in heights.
when my fourth column renders it go below to the first column and leave blank space beside my first column.

### Steps to Reproduce

```
<div>
  <div className="columns is-multiline is-mobile">
     {result.map((res, i) => {
	return (
	   <div className="column is-4" key={i}>
		<List products={res.products} categoryName={res.categoryName} />
		    </div>
		  );
		})}
	</div>
</div>
```

[video link to understand it very clearly](https://res.cloudinary.com/dcr2pfgxy/video/upload/v1567789244/rizwan/fillverticalheightsmp4.mp4)

**Comment by rschindhelm** [comment]
Hey @rizwan92, not sure I'm right on this one, but can't you use tiles instead?
https://bulma.io/documentation/layout/tiles/

**Comment by rizwan92** [comment]
I tried using tile but no luck. if I use it static then columns and tiles both are fine and good 

bu in my condition it is dynamic. inside an array, I have 14 elements. Means 14 times rendering of a column.

is-multiple property wraps it to the next line. but can't fill the gap. same with tile
any solution?

**Comment by rschindhelm** [comment]
I couldn't reproduce your issue with v0.7.5. Here's a [working example](https://jsfiddle.net/es470btq/) rendering eight columns and some sample text. Each column gets resized to the largest column on the respective row.

Maybe you can try to render your site with a minimum working example?
