### ISSUE TITLE
Dropdown is not hiding automatically after click on a dropdown link on navbar

### ISSUE THREAD

**Issue by diptomondal007** [jgthms/bulma#2619]
This is about the Bulma CSS framework..I am working on a project and i am using bulma dropdown on navbar..but the dropdown is not hiding after clicking on link of the dropdown and to make it hide another click is needed outside..How can i fix this..??

**Comment by phunanon** [comment]
I have the same problem.

**Comment by jgthms** [comment]
Any example?

**Comment by diptomondal007** [comment]
This problem is happening in react if i use navbar as a generic component in routing...I have solved that problem by using jbx bulma(a bulma react library). @phunanon

**Comment by phunanon** [comment]
It happens for me even without React when I investigated. I visit the menu example [here](https://bulma.io/documentation/components/navbar/#basic-navbar), inspect the "About" item and add `href="#"`. The element remains "active" after a click, preventing the drop-down hide (Firefox 69). Weird though: giving it a 'proper' href such as `#basic-navbar` avoids the issue, but on my React app I'm using a 'proper' href and it's still not closing.

**Comment by diptomondal007** [comment]
@phunanon  you may try jbx...and without react you may use jquery to solve the problem..there are so many jquery solutions available..

**Comment by simplenotezy** [comment]
I have the same issue, quite annoying. I am using vue

**Comment by slidenerd** [comment]
A dropdown made with is-hoverable does not close automatically after navigating away from the current page, on nuxt.js here

**Comment by rknidzam** [comment]
I ended up use this solution. I'm using React JS to control the NavBar Burger.

1) I used React Hooks 

`const [isActive, setisActive] = useState(false);`

2) Then in the navbar-burger button I used onClick method to open the NavBar.

```
onClick={() => {
setisActive(!isActive);
}}
```

3) Lastly, I do the same on all the navbar item link.

```
onClick={() => {
setisActive(!isActive);
}}
```

Hope it helps.

**Comment by itsip** [comment]
Here's another solution for this using react without having to use state.

I just add `onClick={(event) => { event.target.blur(); }}` to any dropdown links.

Example with react-router:

```
<div className="navbar-item has-dropdown is-hoverable">
  <span className="navbar-link">Dropdown Text</span>
  <div className="navbar-dropdown">
    <Link className="navbar-item" to="/path" onClick={(event) => { event.target.blur(); }}>
      Link Text
    </Link>
  </div>
</div>
```

**Comment by FunctionDJ** [comment]
Here's my implementation if anyone comes across this: https://github.com/couds/react-bulma-components/issues/382

**Comment by romikforest** [comment]
I use `document?.activeElement?.blur();`. `event.target.blur();` and `currentTarget` don't work on complex elements.

**Comment by foximoxi** [comment]
I solved it with a piece of JS code.
At the moment of clicking, you can set the
style.display=none and after a short timeout set the empty value again.

Not elegant but works. Other methods described here have not worked.
Invoke function onclick:
`
function hideMenu(id) { 
let el = document.getElementById(id);
el.style.display = 'none';
setInterval(function () { el.style.display = ''; }, 50);}
`
