### ISSUE TITLE
Question: adopting more friendly syntax on grid components

### ISSUE THREAD

**Issue by bendo01** [jgthms/bulma#262]
i'm looking on bootstrap 4 flex grid one thing i found is their grid flex syntax like this
`.col-xs-4 {
  flex: 0 0 66.66667%
}`
my question / suggestion if grid component syntax can be written like that
example, current bulma grid sass
`.columns.is-mobile > &.is-three-quarters {
    flex: none;
    width : 75%;
}`

to this
`.columns.is-mobile > &.is-three-quarters {
    flex 0 0 75%;
}`

**Comment by jgthms** [comment]
Yeah it might be a good option. I'm not sure if there's any difference. I should investigate.

**Comment by bendo01** [comment]
if you want i'll submit a pr

**Comment by jgthms** [comment]
The shorthand property is not well supporter by all browsers.
