### ISSUE TITLE
iframe height auto makes embedded Youtube videos smaller in height and there is no workaround

### ISSUE THREAD

**Issue by FabianRohr** [jgthms/bulma#2622]
I don't know what's the idea behind

`img, embed, iframe, object, video {
    height: auto;
    max-width: 100%;
}`

but it´s not working for me. And I can't even overwrite it, there is no option for "height" that can undo this. So I can not use Bulma at the moment whatsoever.

**Comment by Hillcow** [comment]
Link to stackoverflow thread: https://stackoverflow.com/questions/57918429/bulma-css-framework-adds-iframe-height-auto-and-embedded-youtube-videos-get-le

**Comment by jonas-scytech** [comment]
This is fixed on `master` and its already on the changelog (#2060 412bef4) but not released yet.

For now I think the best workaround is to replace `@import "node_modules/bulma/sass/base/minireset";` with a direct import of [minireset.css](https://github.com/jgthms/minireset.css)

**Comment by iainhallam** [comment]
Still being affected by this, so I've removed the same lines as 412bef4 in my copy.

**Comment by bpugh** [comment]
Looks like the fix for this is now included in the `0.8.0` release 🎉 
so this issue can probably be closed now.
