### ISSUE TITLE
There is no `is-hidden-fullhd-only` helper

### ISSUE THREAD

**Issue by dukedave** [jgthms/bulma#2623]
This is about **Bulma and the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

There is no `is-hidden-fullhd-only` [helper](https://bulma.io/documentation/modifiers/responsive-helpers/#hide) (but there is a `is-hidden-fullhd`).

If this is intentional then I think the docs should explain why the asymmetry, if it is not, then it's a bug?

**Comment by service-paradis** [comment]
Since `fullhd` if the biggest breakpoint, `is-hidden-fullhd-only` would have the same behavior as `is-hidden-fullhd`.

**Comment by dukedave** [comment]
Oh, I suppose that does make sense 😁 

Not sure if that should be explained in the docs, or if it should be obvious enough to other people?
