### ISSUE TITLE
is-capitalized does not work on option elements

### ISSUE THREAD

**Issue by shughes-uk** [jgthms/bulma#2625]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.7.5]
My **browser** is: Firefox
I am sure this issue is **not a duplicate**?

### Description

is-capitalized does not work on option elements like expected. The options remain lowercase (unless they are actually selected)

### Steps to Reproduce

Add is-capitalized to an option element inside a select

### Expected behavior

Options in dropdown should be capitalized

### Actual behavior

Not capitalized

**Comment by mimidotsuser** [comment]
This is a reported bug with Mozilla Browser. The issue is referenced (here)[https://bugzilla.mozilla.org/show_bug.cgi?id=1445885]
