### ISSUE TITLE
Bootstrap to Bulma converter?

### ISSUE THREAD

**Issue by Bobbbay** [jgthms/bulma#2639]
Not much of an issue, more of a question.

Just a thought - wouldn't it be better for pretty much everybody if there was an official Bootstrap to Bulma converter? 

Issues:
- Is it even Legal?
- What would happen to things that are in Bootstrap but not in Bulma?

I personally believe that this would be a great idea. I don't think making a converter is illegal. And if there isn't support for the item, there should be an error message somwhere, maybe even accompanied by a link to post a new issue on Github? 

What do you think, @jgthms? Thanks!

**Comment by flayestdev** [comment]
what is the main purpose of doing so ? 
if the design is implemented in such a framework why bother to try to migrate to another one ? I think you would want that only if  the other option offer more scalability , I wont invest time and effort to migrate to other framework just to migrate

**Comment by Bobbbay** [comment]
In my opinion, Bulma has a bunch of features that Bootstrap doesn't, and also has a much simpler design. 

Again, I'm not sure if this is a good idea is not, which is why I opened it up as an issue. All criticism is welcome.

Thanks!

**Comment by shikkaba** [comment]
I don't think this is within the realm of the project itself for the dev to take time to build a converter.

Also, with websites, there are so many things to look out for, that unless the user of such a converter stuck to strict vanilla Bootstrap, something would be missed. There is a big difference between bootstrap and bulma, so the code wouldn't know where exactly to put specific custom classes or ids.

Not saying it's not possible, but it's A LOOOOOT of work for something that isn't really worthwhile. If you want to switch frameworks for one reason or another, you're going to have to rebuild.

**Comment by Bobbbay** [comment]
Alright, if nobody else is going to state their opinion, then I'll close this issue for now. Feel free to re-open it if you would like to work on this idea.

**Comment by gotexis** [comment]
This is a brilliant idea and also one much needed.

There are so many good bootstrap templates there. It will be good they could be just used.
