### ISSUE TITLE
Bulma select dropdown not showing on Safari 

### ISSUE THREAD

**Issue by angelocapone** [jgthms/bulma#2640]
Bulma select dropdown not showing the dropdown on Safari browser; even it causes Safari to freeze when clicking repeatedly on select dropdown.
I can reproduce the issue on macOS Mojave version 10.14.6 with Safari version 13.0.1.
The issue occurs on any sites with Bulma select, even on the official Bulma site:
https://bulma.io/documentation/form/select/

Is this a Bulma/Safari bug? Any workaround/solution?

**Comment by Azword** [comment]
https://github.com/jgthms/bulma/issues/2626
