### ISSUE TITLE
[Bug] Nested ul list items have outside dot, resulting in 2 dots

### ISSUE THREAD

**Issue by thepra** [jgthms/bulma#2641]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.7.5]
My **browser** is: Firefox Dev Edition
I am sure this issue is **not a duplicate**? Yes

### Description

The nested unordered list items of other nested items have outside dots resulting in more than 1 dot at the left of nested lists of items

### Steps to Reproduce

```
<div class="content">
	<ul>
		<li>a</li>
		<li>b</li>
		<li>
			<ul>
				<li>inner with left dots</li>
			</ul>
		</li>
		<li>c</li>
		<li>d</li>
	</ul>
</div>
```
![immagine](https://user-images.githubusercontent.com/7032509/66268610-61a07480-e83f-11e9-9444-6ff59a9ddff5.png)

### Expected behavior

One dot per inner list of items

### Actual behavior

More than one dot per inner list

**Comment by amyegan** [comment]
I don't believe this is a flaw in Bulma. There appears to be an error in your example code. You have one too many `li` elements. It should be 
```html
<div class="content">
  <ul>
    <li>a</li>
    <li>b
      <ul>
        <li>inner without left dots</li>
      </ul>
    </li>
    <li>c</li>
    <li>d</li>
  </ul>
</div>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

**Comment by jgthms** [comment]
The markup looks fine. There might be a few styles missing actually in the content class.

**Comment by motionsuggests** [comment]
@amyegan is correct, the `<li>` that wraps the nested `<ul>` has no text so the bullet for that `<li>` appears next to the first `<li>` in the nested `<ul>`. 

Without adding a class to the wrapping `<li>` I don't think there is a way to fix this.

**Comment by jgthms** [comment]
Ah yes, I see what you mean.
