### ISSUE TITLE
Link in documentation is broken.

### ISSUE THREAD

**Issue by arvind0598** [jgthms/bulma#2642]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

I am sure this issue is **not a duplicate**?

### Description

In the documentation about hero elements, linked [here](https://bulma.io/documentation/layout/hero/), the first paragraph says "For the full height hero to work...", but links to a section that does not exist. (https://bulma.io/documentation/layout/hero/#full-height-hero)

### Expected behavior

Upon clicking the link, be redirected to the correct section. I believe the section that it actually has to redirect to is https://bulma.io/documentation/layout/hero/#fullheight-hero-in-3-parts

### Actual behavior

There was no redirection.

**Comment by jgthms** [comment]
Ah thanks for pointing it out but the section to link to is a bit higher. LMFT.
