### ISSUE TITLE
Unable to customize font.

### ISSUE THREAD

**Issue by TheDrone7** [jgthms/bulma#2646]
This is about **Bulma**.

This seems to be a bug but I might be doing it wrong as well. I was trying to modify bulma using node-sass and while I was able to modify the background color by setting a new value for `$body-background-color` variable, nothing seemed to work when I tried to modify the font color by setting a new value for the `$body-color` variable. The font family also didn't change.

I'm using Bulma **version** 0.7.5
<!-- My **browser** is: Google Chrome v77.0.3865.90

### Steps to reproduce

1. Follow https://bulma.io/documentation/customize/with-node-sass/ to set everything up.
2. Set a new value for `$body-background-color` to `#363636` and `$body-color` to `#dedede`

### Expected behavior

I expected it to change the color of background to dark grey and color to light grey.

### Actual behavior

It changed the background color to dark grey but the font color remained same thus making the text disappear because of the color similarities.

Here's my scss file
```
@charset "utf-8";
@import "https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap";

$grey-dark: #363636;
$font-color: hsl(0%, 0%, 86%);

$body-family: "Monsterrat", sans-serif;
$body-background-color: $grey-dark;
$body-color: #FFFFFF;

@import "../node_modules/bulma/sass/utilities/_all.sass";
@import "../node_modules/bulma/sass/base/_all.sass";
@import "../node_modules/bulma/sass/elements/button.sass";
@import "../node_modules/bulma/sass/elements/container.sass";
@import "../node_modules/bulma/sass/elements/title.sass";
@import "../node_modules/bulma/sass/components/navbar.sass";
@import "../node_modules/bulma/sass/layout/hero.sass";
@import "../node_modules/bulma/sass/layout/section.sass";
```

**Comment by jgthms** [comment]
What’s your setup?

**Comment by TheDrone7** [comment]
It was just me being stupid, sorry for the troube.
