### ISSUE TITLE
Full FlexBox Support on Bulma 👍🏻

### ISSUE THREAD

**Issue by elysiopires** [jgthms/bulma#2648]
First of all, I would like to congrats for the awesome work on Bulma framework...

I also would like to ask to add these features to the core... I believe Flexbox is a awesome system and should be implemented by default as bootstrap does...

Using core flexbox as a reference: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

@jgthms What do you think Thomas?

Best,
Elysio
===>>>

Seems like there's already an issue but was left unanswered.

#386
#1315

Having to manually add justify-content and align-items manually on containers, I'm wondering if we could have a class for that?

Suggesting to use

is-justified-center
is-justified-start
is-justified-end
is-justified-around
is-justified-between
is-aligned-start
is-aligned-center
is-aligned-end
is-aligned-stretch
is-aligned-baseline

**Comment by Tofandel** [comment]
Yet again unanswered.. Much needed feature for https://github.com/jgthms/bulma/issues/516

**Comment by miketeix** [comment]
Since the cat is out of the bag, so to speak, with helper classes (https://bulma.io/documentation/helpers/spacing-helpers/), perhaps flexbox helpers could be revisited?

**Comment by Tofandel** [comment]
@miketeix https://github.com/jgthms/bulma/commit/3c4dd3a326bc55282b78c00203029377f5c0951f

**Comment by rajasimon** [comment]
This is awesome. I need this feature asap
