### ISSUE TITLE
Message At The Bottom Of Horizontal Field With Addons

### ISSUE THREAD

**Issue by MannikJ** [jgthms/bulma#2662]
### Overview of the problem
This is about the **CSS framework**
I'm using Bulma **version** [0.7.5] 
My **browser** is: Chrome Version 69.0.3497.92 (Official Build) (64-bit)

### Description
Please see this [codepen](https://codepen.io/mannikj/pen/PooGyVE).
As opposed to the first field when adding `has-addons` class and one or more addons like in the second field, the validation message at bottom of the field is pulled to the same line of the input field.

### Desired behavior
I would like to have the validation message at the bottom of the input field as in the first example. Preferably without any custom css. 
The current behavior feels like a bug to me or at least very unintuitive.

**Comment by yxngl** [comment]
See #640
