### ISSUE TITLE
Getting Started references a CDN file that isn't available

### ISSUE THREAD

**Issue by kedronrhodes** [jgthms/bulma#2663]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description

Looks like /docs/_includes/snippets/getting-started.html is trying to reference the latest version of Bulma, but that version isn't available on the CDN. 

### Steps to Reproduce

1. Visit https://cdnjs.com/libraries/bulma
2. Select version number
3. Latest version is 0.7.5

### Expected behavior

Was hoping that 0.8.0 was available.

### Actual behavior

Using the /docs/_includes/snippets/getting-started.html file, I get a 404 for the Bulma request.

**Comment by jgthms** [comment]
Ah yes, I’m not sure how quickly CDNJS picks up the new version.

**Comment by DapperFox** [comment]
Just ran into this as well, seems like poor timing as the docs look like they just pull from `site.data.meta.version` so I guess this is just a timing issue `¯\_(ツ)_/¯`
