### ISSUE TITLE
On the website the list component is not in the menu 

### ISSUE THREAD

**Issue by reedjones** [jgthms/bulma#2669]
This is about a bug in the Docs

### Overview of the problem

This is about the Bulma **Docs**

### Description

The list component is not in the menu 
this is the url: https://bulma.io/documentation/components/list/
### Steps to Reproduce

1. Go to https://bulma.io/documentation/components/
2. You will not see the "list" component anywhere

### Expected behavior

There should be a menu item linking to: https://bulma.io/documentation/components/list/
### Actual behavior

There is no menu item for the "list" component

**Comment by service-paradis** [comment]
Duplicate: #2402

**Comment by reedjones** [comment]
> Duplicate: #2402

It's duplicate yes, but the other problem is closed, and it 's still not solved?

**Comment by reedjones** [comment]
Is there anyway I can contribute this to the project? I would be more than willing just point me to where

**Comment by service-paradis** [comment]
Check this comment: https://github.com/jgthms/bulma/pull/2434#issuecomment-478781816
