### ISSUE TITLE
Question: Any ideas for Slider and Switch Components?

### ISSUE THREAD

**Issue by fundon** [jgthms/bulma#267]
I created the [Slider](https://vue-admin.fundon.me/#!/ui/sliders) and [Switch](https://vue-admin.fundon.me/#!/ui/switch) Components, but they are DIY design. 

Do you and ideas or suggestions for them? 

@jgthms , thank you very much, again. :)

**Comment by jens1o** [comment]
Really nice! Please merge it in this repo, I like to use them....
