### ISSUE TITLE
[HELP] Navbar with Left, center and right text

### ISSUE THREAD

**Issue by ttwhost** [jgthms/bulma#2670]
This is about the Bulma CSS framework
I'm using Bulma version [0.5.3]

**Description**

"MIRROR ENTERTAINMENT" isn't in center and i dont know how i fix it. **Can someone help**?
![72844285_568193857253041_2233649556770258944_n](https://user-images.githubusercontent.com/1353766/67229419-8f8ad900-f43b-11e9-9814-881529c5f27a.png)

**My code:**

**HTML:**
<div class="sticky">
<nav class="navbar is-fixed-top">
    <div class="navbar-brand">
        <div id="logo">
    <a class="navbar-item" href="">
      <img src="../test/Images/Logo/logo.png">
    </a></div>
        
    <span class="navbar-burger burger" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </span>
  </div>
  <div id="navMenu" class="navbar-menu">
      
        <div class="navbar-start">
           <a href="#" class="navbar-item is-active">COMMERCIALS</a>
           <a href="contact.html" class="navbar-item">CONTACT</a>
        </div>
        <div class="my-navbar-center">
                    <center>
                <strong>MIRROR ENTERTAINMENT</strong></center>
                </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <span class="icon has-text-danger" style="width:80%;margin-top: 0.4rem;vertical-align:middle;">
            <a href="https://www.instagram.com/mirror.bio/"> <i class="fa fa-instagram fa-4x" style="font-size:27px;margin-right:0.2rem;"></i></a> <br>
			
            <a href="https://vimeo.com/mirrorentertainmentaps"> <i class="fa fa-vimeo-square fa-4x" style="font-size:27px;margin-right:0.2rem;"></i></a>
            
            <a href="https://www.youtube.com/channel/UC-WHBQwOgQJ5Ix6UqEoMwYw?view_as=subscriber"> <i class="fa fa-youtube-square fa-4x" style="font-size:27px;margin-right:0.2rem;"></i></a>
            
            <a href="https://www.facebook.com/Mirror-Entertainment-369692753571748/"> <i class="fa fa-facebook-official fa-4x" style="font-size:27px;margin-right:0.2rem;"></i></a>
            </span>
            </div>
        </div>
  </div>
  
</nav>
</div>

**CSS:**
@charset "utf-8";
html {
    font-family: 'Arial', sans-serif;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}    
body {
    font-size:1.3rem;
}
div.sticky {
  z-index: 1 !important;
  background-color:#fffefe !important;
  width:100%;
  padding-top:1rem;
  padding-left:1rem;
  padding-right:1rem;
  padding-bottom:0rem;
  position: -webkit-fixed !important;
  position: fixed !important; 
} 
.navbar-start {
    font-size:0.85rem;
}
.my-navbar-center {
    font-size: 1.3rem !important;
    margin-top: 1.2rem;
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    margin-right: auto;
    flex-grow: 1;
    justify-content: center;
}
.navbar-item img {
    max-height: 5rem !important;
}

**Comment by kwahsog** [comment]
This may help you:

https://github.com/jgthms/bulma/issues/1604
