### ISSUE TITLE
Container fluid size in mobile view

### ISSUE THREAD

**Issue by punkt2** [jgthms/bulma#2672]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.0

### Description

Fluid container in mobile view has different width as normal container

### Steps to Reproduce

https://codepen.io/punkt2/pen/bGGgQWM

### Expected behavior

In mobile view .container and .container.is-fluid should have the same size

### Actual behavior

In mobile view .container.is-fluid is smaller than .container

**Comment by jgthms** [comment]
That's the intended behaviour, per the [documentation](https://bulma.io/documentation/layout/container/):

> This container is fluid: it will have a 32px gap on either side, on any viewport size

The additional space you see comes from the `section` elements. Here's without them: https://codepen.io/jgthms/pen/xxxgBRx
