### ISSUE TITLE
How to use custom colors (v0.8.0)?

### ISSUE THREAD

**Issue by airblade** [jgthms/bulma#2674]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]
I am sure this issue is **not a duplicate**

### Description

I read the blog post about [light and dark colors](https://bulma.io/2019/10/15/light-dark-colors/#light-dark-colors) in v0.8.0 but I'm not quite sure how to take advantage of the new functionality.

It sounds like if I add a custom color, Bulma will calculate the inverted color, a light version, and a dark version.

However I'm not sure how to get hold of these calculated colors.

### Steps to Reproduce

1. I made a `$custom-colors` map in my sass:

```sass
$custom-colors: ("foo": #f3488c)
```

2. I added some html which works:

```html
<a class="button is-foo">this works as expected</a>
<p class="has-text-foo">this works too</p>
```

3. But this doesn't work:

```html
<a class="button is-foo-dark">oh dear</a>
<p class="has-text-foo-dark">oh noes</p>
```

Am I wrong to expect that to work?

4. I found another way to get at the calculated colors but it seems a bit roundabout.  In my sass:

```sass
.bar
  color: nth(map-get($colors, 'foo'), 4)
  // These don't compile because there's no such variable:
  // color: $foo
  // color: $foo-dark
```

Then in my html this works:

```html
<a class="button bar">ok</a>
<p class="bar">also ok</p>
```

Please can you tell me whether there's a better way?

Many thanks in advance!

**Comment by jgthms** [comment]
This doesn't exist:

```html
<a class="button is-foo-dark">oh dear</a>
<p class="has-text-foo-dark">oh noes</p>
```

But you could try this:

```html
<a class="button is-foo is-light">oh dear</a>
```

**Comment by airblade** [comment]
Thank you.
