### ISSUE TITLE
columns layout incorrect with svg child elements

### ISSUE THREAD

**Issue by jasoma** [jgthms/bulma#268]
### Checklist
- [✓] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [✓] I'm using Bulma **version** [0.1.0]
- [✓] My **browser** is: Firefox/Safari/Chrome/Opera
- [✗] This is a **Sass** issue: I'm using version [x.x.x]
- [~] I am sure this issue is **not a duplicate**?
### Description

When using `columns` if the child element of a `column` div is an `svg` the columns do not layout evenly. Columns containing `svg` elements take up more space in the layout then expected and the other columns are semi-collapsed.
- This is true even if the `svg` element is nested (only tested with one additional level of nesting).
- This is true if the svg element itself is the `column` element.
- This is true even if sizing classes (`is-1` etc...) are applied.
### Steps to Reproduce
1. Add a `div class="columns"` element.
2. Add 2+ `div class="column"` elements at least one of which should have an `svg` child.

_Expected behavior: Each `column` div consumes an equal amount of horizontal space.

_Actual behavior: The size of each `column` div element is different.

<img width="1129" alt="screen shot 2016-07-11 at 1 12 45 pm" src="https://cloud.githubusercontent.com/assets/9513315/16739961/99ee2c16-476a-11e6-8feb-bc864284c07d.png">

**Comment by jasoma** [comment]
example:
http://codepen.io/strombane/pen/VjAkkK

**Comment by Come2Daddy** [comment]
Seems to be related to browser implementation of flexbox, or worst : specification.
See [w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/issues/694)
And [philipwalton/flexbugs](https://github.com/philipwalton/flexbugs/issues/184) for recommendations
