### ISSUE TITLE
Need a search input to make documentation more easier

### ISSUE THREAD

**Issue by riyaz7us** [jgthms/bulma#2680]
Hi, I used bootstrap before and now I am completely in love with Bulma. 

One thing though, **bootstrap documentation** provides a sidebar with **navigation and search** form to make it easier to find what we are looking for. 

In Bulma, I have to go through a few clicks and sometimes I get confused.
I would humbly request you to add a search option in documentation or make navigation more readable.

Thanks a lot!
![Screenshot_1](https://user-images.githubusercontent.com/32412620/68029686-c4b9e580-fcdd-11e9-9494-8d5efceec64d.png)

**Comment by jgthms** [comment]
Duplicate #1325
