### ISSUE TITLE
Input width is more than 100% because of padding

### ISSUE THREAD

**Issue by jsaguet** [jgthms/bulma#2685]
This is about **Bulma**.
Is it a bug. I have reproduce it both on Firefox and Chrome. (I haven't tested other browsers)

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0] 
My **browser** is: Firefox 70

### Description

The input fields takes more than 100% of the container.

This issue arises because there is padding applied to the input field and it is not taken into account when calculating the input width, which is always set to 100%.

This can be fixed by calculating the size as 100% minus the horizontal padding of the input.

### Steps to Reproduce
HTML file:
```
<div class="container">
      <div class="box">
          <div class="field">
            <div class="control">
              <input class="input" type="text">
            </div>
          </div>
      </div>
</div>
```
SASS file:
```
@import "~bulma/sass/utilities/all";
@import "~bulma/sass/elements/box";
@import "~bulma/sass/elements/container";
@import "~bulma/sass/form/shared";
@import "~bulma/sass/form/tools";
@import "~bulma/sass/form/input-textarea";
```

### Expected behavior

The input should stay in its container with the proper margin on each side.

### Actual behavior

The input goes beyond the container's right border.

**Comment by jgthms** [comment]
You’re probably in the wrong box-sizing mode. The Bulma minireset makes every element be in `box-sizing: border-box` which means the padding is not added to the width. You’re in `content-box` for some reason, where the padding is added to the width.

Solution is to include the minireset file or to set `.input{ box-sizing: border-box;}`.

See https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
