### ISSUE TITLE
Question: column content overflow

### ISSUE THREAD

**Issue by vladra** [jgthms/bulma#269]
### Checklist
- [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [X] I'm using Bulma **version** [0.1.0]
- [X] My **browser** is: Chrome
- [ ] This is a **Sass** issue: I'm using version [x.x.x]
- [ ] I am sure this issue is **not a duplicate**?
### Description

I have 2 columns on the website. If content of the second column is longer then width of the screen, it is partially "cut". On mobile everything looks good.

![screen capture on 2016-07-14 at 12-03-42](https://cloud.githubusercontent.com/assets/2317652/16834161/42eb706a-49bb-11e6-9751-7e83036a4170.gif)

To solve this problem I've added this code:

```
.column {
  @include tablet {
    &:last-child {
      width: 0;
    }
  }
}
```
### Steps to Reproduce
1. Create `div.columns` with 2 `div.column` inside
2. Place some very wide table inside second `div.column`
3. Screen will overflow on tablets and above, but will look okay on mobile

_Expected behavior:_ Content fit screen

_Actual behavior:_ Content overflows screen

**Comment by dumptyd** [comment]
Well? Did you find any workaround for this?
