### ISSUE TITLE
Beginner: not seeing anything special

### ISSUE THREAD

**Issue by David263** [jgthms/bulma#2690]
This is about **Bulma | the Docs**. Not sure

 Not sure.
 need help, no support on main website
doubtful

### Overview of the problem

I need hand-holding to get started.

### Description

My example is not working, I think. When I enable CSS error detection, there are no errors detected in the Firefox Web Console. Firefox 70.0.1 (64-bit). OS: Windows 10 Home.

### Expected behavior

To see some formatting.

### Actual behavior

No formatting that I can see.
[BulmaTest.zip](https://github.com/jgthms/bulma/files/3820867/BulmaTest.zip)

**Comment by David263** [comment]
I've solved my own problem: on Windows, you can't use standard Windows absolute file paths for CSS files, believe it or not. I'm not sure why, but seems weird.

Changing to:

<link rel=stylesheet type="text/css" href="/bulma-0.8.0/css/bulma.css">

which is client-side absolute addressing, works. I see the formatting.

I think this method of addressing using a local server should be included in your documentation, at least for Windows. It may also apply to a local Linux server, I don't know.

**Comment by jgthms** [comment]
It's true that inclusion paths can be tricky but it's not specific to Bulma. It's better to refer to the documentation of the filesystem or the server in that case.

**Comment by k-j-kleist** [comment]
I bought the e-book "https://jgthms.com/css-in-44-minutes-ebook/" a year and a half ago, and found it very useful as a kick-starter. It costs less than what you probably earn in half an hour, and is a nice way to support the creator and main maintainer of Bulma.

**Comment by David263** [comment]
The announcement is not clear. It offers a free sample, then for that free sample requires an answer to the question "name a fair price". How can I name a fair price for a sample that is supposed to be free before I am allowed to see it? Why don't you just reply with the price you paid for this PDF, please.

**Comment by David263** [comment]
I replied $1,000,000 and it responded with a form to charge my credit card one million dollars for this free sample.
