### ISSUE TITLE
Many error messages in Firefox Web Console

### ISSUE THREAD

**Issue by David263** [jgthms/bulma#2691]
This is about **Bulma**.

May be a bug in Bulma or Firefox, not sure.

Firefox 70.0.1 (64-bit), Windows 10 Home.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0] 

### Description

When I visit a small example, I see lots of error messages in the
[BulmaTest.zip](https://github.com/jgthms/bulma/files/3821008/BulmaTest.zip)
[BulmaTest.zip](https://github.com/jgthms/bulma/files/3821012/BulmaTest.zip)

 Firefox web console with CSS enabled. I cannot hide these messages by turning off the severity level buttons.

### Steps to Reproduce

1. Visit bulma.html
2. Enable web console.

### Expected behavior

Expect to see no error messages. This is important because a real error cannot be seen if hidden inside false error messages.

### Actual behavior

I saw error messages in SASS files, like this:

Unknown pseudo-class or pseudo-element ‘-ms-fill’.  Ruleset ignored due to bad selector. progress.sass:7

This is very strange, because I am only using the bulma.css file and I don't even have SASS installed on my computer.

Please ask if you need more information.

**Comment by jgthms** [comment]
`-ms-fill` is simply a browser-specific property, nothing to worry about. The ruleset will simply be ignored. There are other declarations like this throughout Bulma but they don't affect the styling at all.

**Comment by David263** [comment]
I guess I wasn't clear enough. I'm not worried about any of these error messages: I know that they can be ignored. But error messages should not, in principle, be ignored. Ignoring them makes no sense. Either they are true errors or not. If they are true errors, they should be fixed. If they are not, they should not be reported as errors. So either Bulma or Firefox has a bad bug.

Why do we care? Because a **real** error message, one made by an end user of Bulma, will be lost among all the "fake" error messages generated by Bulma.

Bulma has a responsibility other than styling: it should not make finding a problem with my CSS more difficult by generating fake error messages.

I'm hoping this reply will open this issue again. If not, I'll post another issue. We should not hide this bug, in my opinion.

**Comment by jonathanclark** [comment]
This really  should be resolved properly. The OP is correct.

**Comment by guest20** [comment]
It says in the message that firefox is ignoring the declaration. That makes it an "info", at best. It's not an error. If firefox is ignoring it you should be ignoring it too.

This is how web hacks, and css hacks in particular work:

You put in a tag that is ignored by one UA but makes another UA do the thing you want.

You put in invalid syntax that cause one UA to stop parsing so you can smuggle in css for a UA that silently ignores the syntax error.

Browsers prefix new features specifically so other browsers know they can safely ignore them

Super common for ... IE support 

This is how cross-browser compatibility jank works. It's what the whole web is made of, and has always been made of, all the way back to the first browser wars.
