### ISSUE TITLE
reset IMG vertical-align

### ISSUE THREAD

**Issue by missinglink** [jgthms/bulma#2692]
Heya,

I've been following the lighthouse report to optimize our site and after I added a `doctype` declaration I noticed that there was a vertical positioning issue with images which wasn't there prior to adding the doctype 🤷‍♂ 

```html
<!DOCTYPE html>
```

<img width="647" alt="Screenshot 2019-11-08 at 16 37 43" src="https://user-images.githubusercontent.com/738069/68489772-069bdc00-0248-11ea-90c6-5479f2502f7b.png">

Using the inspector I can confirm that this is not caused by `margin` or `padding`, it's also not part of the image itself.

I was able to resolve this issue with the help of a [SO post](https://stackoverflow.com/a/490052) by adding the following CSS:

```css
img { vertical-align: bottom; }
```

I'm including `bulma/sass/base/_all` in my build which includes `bulma/sass/base/minireset.sass`.
Would you consider adding this to the `minireset` file?

**Comment by jgthms** [comment]
Yeah image alignment can be tricky. I actually tend to do the opposite:

```css
img { vertical-align: top; }
```

I think it's too opinionated to include in the reset, or even the base styles. It's a preference of each user, and it would break setups if included now.
