### ISSUE TITLE
There is no clear link to the GitHub on the Docs

### ISSUE THREAD

**Issue by weaversam8** [jgthms/bulma#2696]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: Firefox Development Edition

### Description

The Bulma website does not have a clear link to the Bulma GitHub repository in the documentation. The only link is on the homepage for Bulma.io. There are other links like:

- The link to star the project or view stargazers
- The link to follow Jeremy
- The link to edit/improve the current page

### Steps to Reproduce

Browse to any page in the Bulma documentation.

### Expected behavior

I expected to find a link to the GitHub.

### Actual behavior

No link to the GitHub is found.

### Resolution:

We should add a link to the GitHub repository in the footer of Bulma.io docs, preferably with a GitHub icon for clarity.

**Comment by sylfel** [comment]
Hello

In header, there's a icon link to github, and one to twitter

**Comment by weaversam8** [comment]
Ah, nice catch! My screen size is not large enough to show the icon by default.

My normal screen size:
![image](https://user-images.githubusercontent.com/2546219/68777704-16c50a00-0600-11ea-9bf7-203ba1c639fb.png)

Adjusted screen size, with icon visible:
![image](https://user-images.githubusercontent.com/2546219/68777747-26445300-0600-11ea-9513-78e609ddf62a.png)

Perhaps those links should move to the "More" menu when the screen is too narrow.

**Comment by weaversam8** [comment]
`32509d3` seems to have fixed this for some screen sizes, but somehow, it hasn't quite fixed it for mine 😬 

![image](https://user-images.githubusercontent.com/2546219/68915900-d1a0f500-0731-11ea-8885-3bef12720c9c.png)

For reference, these are the dimensions of my window:

```js
window.innerWidth = 1269;
window.innerHeight = 506;
```

**Comment by jgthms** [comment]
That’s weird. Will have a look.

**Comment by weaversam8** [comment]
I can confirm that this issue is still a problem. My current browser window is 1500x1000 pixels, and the icon isn't visible. No list entry is visible in the "More" menu either.

**Comment by weaversam8** [comment]
This is no longer an issue as of November 2020. Thanks!
