### ISSUE TITLE
.is-inline has !important

### ISSUE THREAD

**Issue by henrypenny** [jgthms/bulma#2697]
This is about **Bulma**.

### Overview of the problem

The .is-inline helper has display: inline !important;
This means you can't use style="display:none;", which means you can't use `style="display: none;"`, jQuery hide/show etc.

**Comment by jgthms** [comment]
Yes all helpers have the important flag because they’re used to override styles already applied.
If you use jQuery just swap the classes instead with addClass and removeClass.
