### ISSUE TITLE
Incorrect Media Query for is-tablet

### ISSUE THREAD

**Issue by sparkyspider** [jgthms/bulma#2699]
Unless I'm confused...

Media query for is-hidden-tablet is wrong (current master):

```
@media screen and (min-width: 769px), print {
  .is-hidden-tablet {
    display: none !important;
  }
}
```

Should read:

```
@media screen and (max-width: 1023px), print {
    .is-hidden-tablet {
        display: none !important;
    }
}
```

**Comment by jgthms** [comment]
That's the correct CSS rule. `+tablet` is for `767px` and above.
See https://bulma.io/documentation/overview/responsiveness/ and https://bulma.io/documentation/modifiers/responsive-helpers/
