### ISSUE TITLE
Body shifted like 10 pixels to the left

### ISSUE THREAD

**Issue by luishendrix92** [jgthms/bulma#27]
I have this issue on Codepen that makes the body shift to the left by approximately 10 pixels leaving a gray vertical bar on the right side. I'm using the codepen.io editor.

**Comment by zaccharles** [comment]
@luishendrix92 To make things easier, perhaps you can link to your particular codepen, paste in a screenshot, and mention which browser (and version) you're using?

**Comment by jgthms** [comment]
@zaccharles is right: a like to the actual codepen would be useful, because the issue can come from anywhere.

**Comment by luishendrix92** [comment]
http://s.codepen.io/luishendrix92/debug/JGZVNO

Check the right side of the page, there's a gray bar and it's added even without content.
I used rawgit to use the raw css file on the repo's css folder.

**Comment by BlueAccords** [comment]
Maybe it's just me but I can't see the gray bar you're describing. I went to the code pen page itself and tried changing the body element's background color to a more noticeable color but still couldn't see the gray bar.

**Comment by zaccharles** [comment]
I also can't see anything weird. @luishendrix92 can you please post a screenshot? I'm guessing it's some browser-specific issue.

**Comment by jgthms** [comment]
Closing, as this doesn't seem to be a Bulma-related issue.
