### ISSUE TITLE
Bulma Templates - grid template? plus, one currently exiting template gives '404'

### ISSUE THREAD

**Issue by tweed** [jgthms/bulma#270]
http://bulma.io/templates/welcome.html
[broken?]
haven't been able to see this one.

PLUS, how cool would it be to have a template that has the top bar and footer
AND in the content area just a, say, 4 column grid.

anyone done this?
in any event - thanks. great to be here.

**Comment by madjake45** [comment]
If this is about templates on the website then this issue should really go in the https://github.com/jgthms/bulma-website repo

**Comment by tweed** [comment]
right - of course - sorry
i noticed a post here about asking for templates
thank you

**Comment by pkunze** [comment]
The templates seem to be removed from the docs, im nor sure if this happened on purpose?

**Comment by jgthms** [comment]
The templates are a WIP. I didn't migrate them when switching the docs repo, but they're planned!
