### ISSUE TITLE
Change colors according prefers-color-scheme media query

### ISSUE THREAD

**Issue by dlemper** [jgthms/bulma#2700]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.8.0
My **browser** is: Firefox/Chromium

I am sure this issue is **not a duplicate** as #2342 is about theming in general in my opinion

### Description

I would like to switch between a dark theme and the standard light theme automatically based on „ prefers-color-scheme“ media query. For this, I would like to use the new $scheme-* variables. Is that possible with bulma (in a Vue project) and if so, how?
I understand, that I can‘t use the media query in a SASS file as SASS gets preprocessed. So am I missing something?

### Steps to Reproduce

1. create a Vue.js project using the vue cli
2. add bulma to the project e.g. by adding a <style lang=„sass“> with the import of bulma
3. try to use the media query „ prefers-color-scheme“  and change the variable $scheme-main to #000

### Expected behavior

Expected colors to change according the media query

### Actual behavior

Nothing changed

**Comment by Grovkillen** [comment]
See my comments regarding this: https://github.com/jgthms/bulma/issues/1837
