### ISSUE TITLE
App too wide on Mobile

### ISSUE THREAD

**Issue by kerbo** [jgthms/bulma#2703]
I have tested my app in responsive mode on Chrome and Safari (desktop) for an iPhone 7 (375px wide). Display is perfect.

When I run the app on the actual phone (Safari or Chrome) the display is little wide. And I can drag the display left/right because of the overflow.

Shouldn't this work? How can I fix this? I'm using Vue and Buefy if that matters.

**Comment by jgthms** [comment]
What's your code?

**Comment by jgthms** [comment]
You might need this:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

See https://bulma.io/documentation/overview/start/#starter-template

**Comment by kerbo** [comment]
I inspected the page and viewport meta tag is there (Vue must add it).

I was hoping there was something I missed in the configuration (like the meta tag) before I start the process of dissecting my app to something I can post.

**Comment by Grovkillen** [comment]
Make sure you do a "CTRL+SHIFT+R" to force the DOM to be redrawn from scratch.

**Comment by kerbo** [comment]
Thanks,

The problem I think was from a template where I added margins to a section. This one change caused all layouts to overflow.

With this fix, the app is working as expected.

What surprised me is this issue did not show up in the responsive mode emulators in Chrome and Safari.
