### ISSUE TITLE
[Feature Request] Classes to fill available vertical space

### ISSUE THREAD

**Issue by RobJacobson** [jgthms/bulma#2704]
I found it difficult to place content into the body of a full-height hero that used up all of the available vertical space in the body.  The goal was to stretch the divs to take up the complete hero body.  I found this article about how to do this with flexbox:
https://css-tricks.com/boxes-fill-height-dont-squish/

I created an example to illustrate.  The hero body has four divs.  The first and second divs do not have any modifiers, so they are sized normally to fit their content.  The third and fourth divs have a modifier class "is-max-height," which divides all of the remaining vertical space between them, increasing their height.  The fourth also has a modifier class "is-vertically-centered" which makes the content centered vertically in the div.
https://codepen.io/RobJacobson/pen/QWWJPWK

This seems like a common use-case.  Are there any existing modifiers in Bulma that allow this?  (I.e., am I reinventing the wheel?)  If not, I'd propose adding classes like these, along with supporting documentation/examples on the website.  I think this would  be quite useful.

Also, I'd like to suggest creating a layout control for full-page content that isn't a hero.  It seems to be a common practice to use a hero for full-page content, such as in the linked tutorial (which is excellent).  However, this seems to me like "overloading" the hero class when it's used as a general layout tool for full-page layouts.  It works, but it seems weird -- using a hero for something that doesn't have traditional "hero" content.
https://scrimba.com/p/pV5eHk/cvrwyfR

**Comment by thepra** [comment]
Yep, I'd add also the possibility to specify the overflow should follow a scrollbar if the content if this vertical space is filled up.
