### ISSUE TITLE
How to change Navbar dropdown arrow color?

### ISSUE THREAD

**Issue by rugleb** [jgthms/bulma#2705]
Hi, I have a question about **Bulma**.

### Overview of the problem

I'm using Bulma **version** 0.8.0;
My **browser** is: Chrome;
I am sure this issue is **not a duplicate**? Not;

### Description

How to change default arrow color in [navbar dropdown](https://bulma.io/documentation/components/navbar/#dropdown-menu)?
By default, color is blue (see below), but I want to change it.

![Screenshot from 2019-11-17 09-51-39](https://user-images.githubusercontent.com/26823697/69004188-138f8e00-0920-11ea-92e8-8958ebce49b0.png)

What class/property should change?
I'm not good at frontend, but I really hope for your help.
Thanks.

**Comment by service-paradis** [comment]
I think you should be able to update this color using the `$input-arrow` variable
