### ISSUE TITLE
Colors are hard-set for h and strong tags

### ISSUE THREAD

**Issue by StevenLantinga** [jgthms/bulma#2708]
I have a question about Bulma version 0.8.0. I could not find a duplicate of this question.

Is there a reason why colors are so hard set in Bulma? For instance, a strong element by default has a dark grey color. Now whenever I use a strong element inside a .card with a .has-background-black the text within the strong text is hardly readable. Even when I add the  .has-text-white class to the card the strong text will remain dark grey. I can add the .has-text-white class to the strong element of course but this must be a work around and more importantly this won't work inside a WYSIWYG editor.

The same goes for h tags that also have their colors hard set.

Wouldn't it be better to remove these colors and make these elements take the color set as the default for the body or a some other parent?

**Comment by jgthms** [comment]
It’s to have higher contrast for these elements by making them darker. But in some instances this color is reset or overridden with `currentColor`. This is something you can set with a Sass variables globally if you want.

**Comment by StevenLantinga** [comment]
Higher contrast then really depends on your overal styling or the element the text is in. If the rest of the text is anything darker than the default strong color then contrast will actually be lower. And if the background is any dark color the strong text will blend in.

Many sites have different sections with different background colors. Bulma has this sorted with the .has-background-* class but setting the color for h and strong tags really defies this. The color for these elements should not be set. This is way to fixed for a framework with such a lite theme.
