### ISSUE TITLE
Navbar Dropdown does not open on Edge Browser

### ISSUE THREAD

**Issue by dewanganlakhan** [jgthms/bulma#2710]
This is about **Bulma | the Docs**.

### Overview of the problem
The Navbar Drop down does not open up when we hover mouse or click on it, on Edge Browser.

### Steps to Reproduce
Check the below Docs of Latest Edge browser, you will get the problem.
https://bulma.io/documentation/components/navbar/

### Expected behavior
Should Open the Drop down menu when we hover mouse.

**Comment by Niek** [comment]
Duplicate of #2503, workaround @ https://github.com/jgthms/bulma/issues/2503#issuecomment-519650331
