### ISSUE TITLE
SVG Image is not showed up inside navbar-brand

### ISSUE THREAD

**Issue by ezmemoar** [jgthms/bulma#2712]
Hi, i'm making a react app and currently using bulma 0.8.0. When i try to add an SVG image in navbar-item inside the navbar-brand class, it doesn't showed up. example code is below:
```
<div className="navbar-brand">
      <a className="navbar-item">
           <img src={logo} alt="logo" />
      </a>
</div>
```

But when i place the the image before the navbar-item class, it is showed. example:
```
<div className="navbar-brand">
      <img src={logo} alt="logo" />
      <a className="navbar-item">
      </a>
</div>
```
Is there anything i miss in here?

By the way, thanks for making such great framework. I really love Bulma

**Comment by RobJacobson** [comment]
I had a similar problem.  I solved it by defining my image as follows, with a height:

```
      <div className="navbar-brand">
        <a className="navbar-item">
          <img
            src={BoatLogo}
            style={{
              maxHeight: "2.5rem"
            }}
          />
          <span className="headerBrandLogoText">FerryTime</span>
        </a>
        <NavbarBurger />
      </div>
```

If you add a width or a height, it should appear as expected.

**Comment by ezmemoar** [comment]
> I had a similar problem. I solved it by defining my image as follows, with a height:
> 
> ```
>       <div className="navbar-brand">
>         <a className="navbar-item">
>           <img
>             src={BoatLogo}
>             style={{
>               maxHeight: "2.5rem"
>             }}
>           />
>           <span className="headerBrandLogoText">FerryTime</span>
>         </a>
>         <NavbarBurger />
>       </div>
> ```
> 
> If you add a width or a height, it should appear as expected.



Well, that will be good to solve the problem. But wouldn't it be better if the SVG is showed up since it has its own default height and width? And by not showing up without setting up height and width can make people get confused, like me example.

**Comment by hereCOMESlappy** [comment]
still an issue

**Comment by RobJacobson** [comment]
Thanks for reporting, @hereCOMESlappy. I had completely forgotten about this issue. I hope someone can address it.

**Comment by cldershem** [comment]
Still an issue.
