### ISSUE TITLE
[Feature Request] Maximum number of columns into line

### ISSUE THREAD

**Issue by francesco-loreti** [jgthms/bulma#2714]
Hi,

it is possible to add a function in which to set the maximum number of columns in a div of columns.
For example:
The "columns.has-3" -> "has-3" class includes "is-multiline" and the column line has max 3 columns. After the third column, a new line is created.

Do you think it's possible?

Thanks

**Comment by jgthms** [comment]
It might be possible yes, using `max-width` in a way. Let me see what's possible.

**Comment by francesco-loreti** [comment]
Ok, I can try to append this feature 😄

**Comment by francesco-loreti** [comment]
I have append my solution. It's ok, into my tests. Do you have any suggestions? The name of class it's good or I need to change it?

**Comment by 6XGate** [comment]
This would be nice to have or some way to fill out the rest of the line to start a new one, like `is-auto` on a final column.
