### ISSUE TITLE
[REQUEST] is-1, is- 2 etc. are NOT sensible class names

### ISSUE THREAD

**Issue by veryverygoodgood** [jgthms/bulma#2716]
One should be able to understand what a class does just by looking at it. This is true for most of Bulma, but unfortunately not the `is-1`, `is-2` etc. part.

https://en.wikipedia.org/wiki/Semantic_HTML

--VVGG

**Comment by jgthms** [comment]
Semantic HTML has nothing to do with CSS class names. HTML is content, where semantics apply.

As for `is-1` `is-2` etc. they are modifier classes. So they are attached to a main class like `title` or `subtitle`. So they do make sense in the context of being attached to a descriptive class name.

**Comment by veryverygoodgood** [comment]
I must disagree with you on that one. In the real non-framework world, semantic HTML is made up of tags that reflect the structure or meaning of its content and not its looks. The latter is CSS and only CSS's job, and it should remain separated from the HTML.

As we all know, this is not possible in the framework world. But, it is ofcourse possible to get a lot closer to it. `is-1` is one example of poor structural meaning. The whole tag inside tag inside tag like those Russian dolls is another example of poor semantics. Like why can't this:

```
<section class="hero is-white">
  <div class="hero-head">
  <nav class="navbar is-transparent">
    <div class="container">
    <div class="navbar-brand">
      <%= link_to 'Whatever', root_path, class: "title navbar-item" %>
    </div>
    <div class="navbar-menu">
      <div class="navbar-end">
      <%= link_to "New post", new_post_path, class:"navbar-item" %>
      <a class="navbar-item">New post</a>
      </div>
    </div>
    </div>
  </nav>
</section>
```

Become this:

```
<section>
  <nav class="is-white is-transparent">
    <div class="logo is-left">
      <%= link_to 'Whatever', root_path %> <-- Bulma should know this is the logo, considering its class is the logo which is in the nav tag
    </div>
    <div class="menu is-right">
      <%= link_to "New post", new_post_path %> <-- Same here, Bulma should know this is a menu item
    </div>
  </nav>
</section>
```

There's no denying the last example is better. Bulma should recognize more of the HTML due to its semantics, and not do like Bootstrap and confuse us with unnecessary tags and non-sensical class names.

There really should be no excuse, other than the developers not being able to think clearly, as the mess in ones code often reflects the mess in ones head.
