### ISSUE TITLE
.nav-right has this weird tablet-only section

### ISSUE THREAD

**Issue by mtimofiiv** [jgthms/bulma#272]
This is for the current release of Bulma, `0.1.0`. I have tested this on mobile devices (Chrome on Android and Safari on iphone).

The nav component has some funny behavior with `.nav-right` on non-tablet mobile. Here's the code from [`components/nav.sass#L82`](https://github.com/jgthms/bulma/blob/master/sass/components/nav.sass#L82):

``` sass
.nav-right
  // Responsiveness
  +tablet
    align-items: stretch
    display: flex
    flex: 1
    justify-content: flex-end
```

The result breaks the `.nav-right` element on non-tablet mobiles like so:

![screen shot 2016-07-22 at 16 08 51](https://cloud.githubusercontent.com/assets/428948/17059736/e85e23be-5026-11e6-93f0-dc8e7c199794.png)

Changing this to:

``` sass
.nav-right
  // Responsiveness
  align-items: stretch
  display: flex
  flex: 1
  justify-content: flex-end
```

Makes all play nice, including tablet and desktop.

I can submit a PR, but I was just wondering if there was a reason first before I go ahead and do that!

**Comment by mtimofiiv** [comment]
I made a PR to remove the tablet-only requirement.

**Comment by martinek** [comment]
This is probably meant to work with .nav-menu but is definitely buggy behavior.

Currently it is impossible to use .nav-right on mobile.

**Comment by mtimofiiv** [comment]
@martinek I fixed it in the PR https://github.com/jgthms/bulma/issues/348

**Comment by mtimofiiv** [comment]
So is this fixed then?

**Comment by jgthms** [comment]
I need to investigate. The `nav-right` should be hidden when used with `nav-menu`.

**Comment by martinek** [comment]
Problem is that without `.nav-menu`, content of  `nav-right` on tablet is not on the right as one would expect, but it breaks.

You can see this in documentation for nav component. If you remove `nav-menu` class from `nav-right` in first example the menu breaks up.
