### ISSUE TITLE
What's with Jeremy Thomas closing important issues before we even get a chance to reply?

### ISSUE THREAD

**Issue by veryverygoodgood** [jgthms/bulma#2721]
Like this:

https://github.com/jgthms/bulma/issues/2719

Highlighting Bulma's current messy way of doing things. It's like Jeremy Thomas doesn't want people to know about this so he won't lose his funding or whatever. This sort of censorship is ridiculous.

Starting to regret having built my app on this thing.

--VVGG

**Comment by jgthms** [comment]
I'm closing issues when they are solved, but also when they are irrelevant or misleading or wasting time for everyone.

In this particular case, I closed the issue after having replied in detail to each of the points. You seem to be confused about what "semantic HTML" is, and are even contradicting yourself. It's not really worth the community's time, including mine, to go further into the matter.
