### ISSUE TITLE
Part 2: What's with Jeremy Thomas closing important issues before we even get a chance to reply?

### ISSUE THREAD

**Issue by veryverygoodgood** [jgthms/bulma#2724]
> I'm closing issues when they are solved, but also when they are irrelevant or misleading or wasting time for everyone.
>
> In this particular case, I closed the issue after having replied in detail to each of the points. You seem to be confused about what "semantic HTML" is, and are even contradicting yourself. It's not really worth the community's time, including mine, to go further into the matter.

Curious though, why certainly didn't let me respond to any of your points. Not letting people properly present their case, especially when they're trying to help Bulma improve, is both extremely rude and arrogant.

You seem to think that you are right and everyone else is wrong. Earlier you claimed that this place here on GitHub was the place for the community to discuss matters surrounding Bulma. But that's just a load of BS judging by the way you're acting right now.

Seems you want to keep criticism, even though it's constructive, away from public view just so you can keep on getting your sponsor funding and ad revenue.

What a waste of time this is.

**Comment by veryverygoodgood** [comment]
> If we use `small`, `medium`, `big`, you're describing how the component looks, not what it means. So I'm not sure how it applies to your idea of "semantic HTML"?

That's the point I was trying to make earlier is that it's already obvious that CSS frameworks be semantic HTML in its HTML. However we can make things as semantic as possible. 

For instance at https://bulma.io/documentation/layout/media-object/ -- you use `<strong>` and `<small>` where there's no meaningful difference between the information presented. Classes like these http://bulma.io/documentation/modifiers/syntax/ would be more proper here, or at least `<h1>` through to `<h6>`.

Further `<p><strong>Link1 - Link 2</strong></p>` should be `<ul class="has-bold-text"><li>Link1</li><li>Link2</li></ul>`. And `<div class="columns"><div class="colum"></div><div class="colum"></div></div>` when it should already be obvious that the children are columns since they belong to a parent whose name is `columns`.

Yes, it certainly did, and thanks for taking the time to respond.

I also admit I often mix the words semantic with basic good design. However like shown above, there are cases where the examples in your documentation could be made more semantic, as well as cases where you could stick to using classes already built into Bulma instead of unnecessarily blending in HTML elements for visual purposes.

**Comment by veryverygoodgood** [comment]
And, the idea of future frameworks using some sort of middleware where you can link its classes with classes perfectly semantic HTML isn't that bad of an idea, is it?

Maybe I should have kept this idea to myself, as the majority of HTML/CSS peeps around the world simply hate any form for CSS frameworks. But with something like that middleware thing, I think I could have created a framework that could be loved and cherished by all.

Sorry if my posts became a bit too long, but as Blaise Pascal once said: "This letter got longer than usual because I didn't have time to make it any shorter." :D

Cheers!

**Comment by jgthms** [comment]
It seems your ideas are not compatible with the very foundation of Bulma: CSS classes are **independent** from the underlying HTML. This separation method allows the **semantics** of the HTML to be **freely chosen** by the user.

That's why people pick Bulma: they can simply add some base classes, a few modifiers, and their styling is done!

You write the [HTML you want](https://bulma.io/documentation/overview/classes/). Bulma does the rest.

> I think I could have created a framework that could be loved and cherished by all.

I believe that's the best way to go, and wish you good luck.
