### ISSUE TITLE
Part 3: What's with Jeremy Thomas closing important issues before we even get a chance to reply?

### ISSUE THREAD

**Issue by veryverygoodgood** [jgthms/bulma#2725]
> It seems your ideas are not compatible with the very foundation of Bulma: CSS classes are independent from the underlying HTML. This separation method allows the semantics of the HTML to be freely chosen by the user.
>
> That's why people pick Bulma: they can simply add some base classes, a few modifiers, and their styling is done!
>
> You write the HTML you want. Bulma does the rest.

That's the point I'm trying to make -- that this is simply just idn't the case!

Bulma allows you to add a few cases, a few modifiers, and you're done -- that part is fine.

But, unfortunately, Bulma requires you to drastically alter your HTML, and even insert unnecessary tags where classes could be used instead. You talk about me not understanding semantic HTML, with all due respect I think it's the other way around.

I'm just asking you to make Bulma more consistent by sticking to your core principle of using clean, simple and self-explanatory classes without interfering with ones HTML up to the point where you have to use old style tags to get what you want, and in addition put tags inside tags inside tags inside tags like some sort of Russian doll.

Having said that, I wish you good luck as well, and may all of Bootstrap's users become your users one day. Cheers!

**Comment by jgthms** [comment]
Thanks.

**Comment by 1234dev** [comment]
@jgthms I sort of agree that Bulma could add a few more modifier classes so we could get away with using HTML tags where it shouldn't be needed. Having multiple `<br>` stacked on top of each other just doesn't feel right.

Same goes for stuff like `<h1 class="title">` when it's already obvious that `<h1>` is a title. I think what he's trying to say is to respect the semantics of HTML a bit more before requiring users to add modifier classes.

I also agree there should be a place where we can discuss how to improve Bulma. The way you're shrugging off constructive criticism like this seems a bit strange.
