### ISSUE TITLE
[Question] Is the documented limitations for Control correct or is it overly generalized?

### ISSUE THREAD

**Issue by jzabroski** [jgthms/bulma#2728]
This is about **the Docs**.

This is a **question**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs** 
I'm using Bulma **version** [0.7.4]
My **browser** is: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

I am sure this issue is **not a duplicate**

### Description

The documentation for [form control ](https://bulma.io/documentation/form/general/#form-control)says:

> The Bulma control is a versatile block container meant to enhance single form controls. Because it has the same height as the element that it wraps, it can only contain the following Bulma elements:
> 
> * `input`
> * `select`
> * `button`
> * `icon`

However, in reading the blog post from 2017 where [control was split into field and control in v.04.0](https://bulma.io/2017/03/10/new-field-element/), the examples cover using a `span` inside a control and why I can't have a complex control of HTML elements inside a control element:

```html
<!-- Before -->
<label class="label">Username</label>
<p class="control has-icon has-icon-right">
  <input class="input is-success" type="text" placeholder="Text input" value="bulma">
  <span class="icon is-small">
    <i class="fas fa-check"></i>
  </span>
  <span class="help is-success">This username is available</span>
</p>

<!-- After -->
<div class="field">
  <label class="label">Username</label>
  <p class="control has-icon has-icon-right">
    <input class="input is-success" type="text" placeholder="Text input" value="bulma">
    <span class="icon is-small">
      <i class="fas fa-check"></i>
    </span>
  </p>
  <p class="help is-success">This username is available</p>
</div>
```

### Steps to Reproduce

Not exactly steps to reproduce, but additional context: I'm asking specifically because I want to use Bulma with Telerik Kendo UI, and Kendo UI translates it's "`<kendo-dropdownlist>` element into something like the following for an empty dropdown list, and its top-level elements are span and input, which violates the rules in the Bulma documentation HOWEVER everything seems to "work ok" - I think this is because the span is actually the floating listbox and therefore not part of the actual layout rules applied by Bulma, but it's been about 3+ years since I last did Web apps:

```html
<div class="field">
  <label class="label" for="Status" id="Status_label">Status</label>
  <p class="control">
    <span title="" class="k-widget k-dropdown" unselectable="on" role="listbox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-owns="Status_listbox" aria-labelledby="Status_label" aria-live="polite" aria-disabled="false" aria-busy="false" style="" data-children-count="1">
      <span unselectable="on" class="k-dropdown-wrap k-state-default">
        <span unselectable="on" class="k-input" data-children-count="0"></span>
        <span unselectable="on" class="k-select" aria-label="select" data-children-count="0">
        <span class="k-icon k-i-arrow-60-down"></span>
      </span>
    </span>
    <input id="Status" name="Status" type="text" value="" data-lpignore="true" autocomplete="off" data-role="dropdownlist" style="display: none;">
   </span>
  </p>
</div>
```

### Expected behavior

Clarify documentation that a control can contain the four elements, or any element that is not directly in the layout of the control element (e.g., floating above as in a pop-up control)

### Actual behavior

It seems to be OK to have spans and other elements, as long as it's not directly in the element's "has layout" path.  But, again, it's been 3+ years since I've built a Web app, so I may be overlooking something, especially with Flexbox, as this is my first Flexbox app.

**Comment by jzabroski** [comment]
What?  Is this a joke?

**Comment by jzabroski** [comment]
@jgthms/bulma Is anyone looking at this repository?  Seems a bit cold to turn on stale-bot and not respond to issues.

**Comment by jgthms** [comment]
I believe the `control` behavior has changed a bit since v0.4.0. The documentation specifies it should only contain one of those 4 elements because the behavior of these is guaranteed. Any other element is not. So it might work in some cases, but it's more of a whitelist than a blacklist kind of thing. The `control` doesn't have too complex styles:

```css
.control {
  box-sizing: border-box;
  clear: both;
  font-size: 1rem;
  position: relative;
  text-align: left;
}
```

But it can be extended. For example, `control` with the the `has-icons-left` modifier allows to add icons to the left of an input. It does so by adding some padding:

```css
.control.has-icons-left .input, .control.has-icons-left .select select {
  padding-left: 2.5em;
}
```

So I would say, in most cases, you can add other elements in `control` but it's at your own (albeit small) risk.
