### ISSUE TITLE
Icon button with hidden text is not displayed properly

### ISSUE THREAD

**Issue by vdlbk** [jgthms/bulma#2731]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0] .   
My **browser** is: Chrome Version 78.0.3904.108 .   

I am sure this issue is **not a duplicate**? 
No, but I didn't find something similar

### Description

The icon button with hidden text is not displayed properly.   
I'm looking for a solution, a workaround or maybe I simply missed something.

### Steps to Reproduce

1. Add a button with an icon and text
2. Add a hide responsive helper on the text
3. Set the width of your browser in the right breakpoint (when you see the text disappeared)

You can also find a jsfiddle [here](http://jsfiddle.net/c3b5x7o4/5/)     
In case it does not work or it's deleted for any reason, here's a screenshot: 
![screenshot](https://i.ibb.co/6yjw7ZN/Capture-d-e-cran-2019-12-06-a-20-49-05.png)

### Expected behavior

The icon button with hidden text should be displayed as a normal icon button.

### Actual behavior

There is an extra space next to the icon. It is not displayed as a simple icon button as it should.
It's probably because of this:
```css
.button .icon:first-child:not(:last-child) {
    margin-left: calc(-0.5em - 1px);
    margin-right: 0.25em;
}
```

It seems that there is the same issue with the `is-sr-only` class.

**Comment by abnersajr** [comment]
@vdlbk I fix your issue with one minor change. The Label must be positioned before the icon as you can see in PR.

**Comment by vdlbk** [comment]
@abnersajr Thank you for your contribution but my main issue is about the hide responsive helpers like `is-hidden-mobile`.    
Also, I think that I should not have to change my codebase for this kind of thing. It should work regardless of whether I decide to put the label to the right or left of the icon.

**Comment by abnersajr** [comment]
@vdlbk about change your codebase I understood, but we have some CSS selectors limits. 
I will rethink about a selector that can solve this for both sides or CSS change.
About the responsive classes I got your point. I will do this too.

**Comment by jgthms** [comment]
Ok this could work if we introduce a `is-only-child` class, because that's what this selector is trying to "guess":

![image](https://user-images.githubusercontent.com/1254808/71184124-8cfd0200-2279-11ea-950a-74b27559910d.png)

And then you can do:

```html
 <button class="button">
   <span class="icon is-small is-only-child">
     <i class="far fa-trash-alt"></i>
   </span>
   <span class="is-sr-only">Delete</span>
 </button>
```

**Comment by abnersajr** [comment]
@jgthms LGTM. I will redo with your change and docs note too.

**Comment by abnersajr** [comment]
PR Updated with suggestions.

**Comment by vdlbk** [comment]
@jgthms After testing a bit, it does not seem to work when we set a breakpoint where the text appears.    
Here's an other jsiddle : [http://jsfiddle.net/L2muvkah/1/](http://jsfiddle.net/L2muvkah/1/)

![result](https://i.ibb.co/yhryhsQ/1.png)

```html
 <div class="container">
  <p>
     Hide text on mobile devices
  </p>
  <button class="button">
    <span class="icon is-small is-only-child">
      <i class="far fa-trash-alt"></i>
    </span>
    <span class="is-hidden-mobile">Delete</span>
  </button>
  <button class="button">
    <span class="is-hidden-mobile">Delete</span>
    <span class="icon is-small is-only-child">
      <i class="far fa-trash-alt"></i>
    </span>
  </button>
</div>
```

But maybe, I miss something.    
Can you confirm that you have the same problem than me ?

**Comment by jgthms** [comment]
We’d need `is-only-child-mobile` `is-only-tablet` etc.

**Comment by vdlbk** [comment]
I think this issue should stay open
