### ISSUE TITLE
Navbar variables ignored when color is specified

### ISSUE THREAD

**Issue by Zeranoe** [jgthms/bulma#2732]
Variables such as:
`$navbar-item-active-background-color: white;`
have no effect when a color is used for the navbar, such as `navbar is-dark`.

Intuitively I assumed the variable would override any color selection.

**Comment by jgthms** [comment]
So the coloured versions generate their own color scheme for better readability. That way, you don’t have to specify the colours of each sub element in the navbar.

The main variables such as `$navbar-item-active-background-color: white` are for the default style of the navbar.
