### ISSUE TITLE
$grey-lightest not used in shades

### ISSUE THREAD

**Issue by osamajandali** [jgthms/bulma#2734]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.8.0] 
My **browser** is: Google Chrome Version 78.0.3904.108

### Description

In the new [customize page ](https://bulma.io/documentation/customize/variables/), there is a variable called `$grey-lightest` and it is not used anywhere in the framework.
I think it should be added to `$shades`.

**Comment by mervvi** [comment]
13 Haz 2020 Cmt 17:50 tarihinde stale[bot] <notifications@github.com> şunu
yazdı:
