### ISSUE TITLE
Hero Sizes should be configurable variables

### ISSUE THREAD

**Issue by hammadzz** [jgthms/bulma#2739]
Like done with section sass these hero sizes should be variables: 

https://github.com/jgthms/bulma/blob/5381f2649d3466487585a0f0dfa8f177c8f42b1d/sass/layout/hero.sass#L71-L85

See section sass:
https://github.com/jgthms/bulma/blob/5381f2649d3466487585a0f0dfa8f177c8f42b1d/sass/layout/section.sass#L1-L3

I can make a pull request on it if this seems like something many others would also want.

**Comment by IvanFrescas** [comment]
Hi, I'm looking to make my first contributions, can I work on this issue?

**Comment by kaleabMelkamu** [comment]
Yes ofcourse u can

**Comment by IvanFrescas** [comment]
I made the changes and made the pull request.
Any feedback is welcome. 🙂
