### ISSUE TITLE
Version 0.1.0 can't build on Windows and not able to build minified css

### ISSUE THREAD

**Issue by miniskulljob** [jgthms/bulma#274]
When running `npm run build` on Windows to compile bulma, it gives an error because it's trying to do `rm -rf css`.
Also, in current version, it not longer builds a minified version. Why was it removed?

**Comment by jgthms** [comment]
The minified version was removed as the minifier included bugs in the output.

Not sure how to fix that, so I leave it to users to minify their assets. I believe this step shouldn't be part of the framework actually.

**Comment by jgthms** [comment]
As for `rm -rf css`, yes it's a bug. I believe someone posted a fix at some point, because the unix command doesn't work on windows.

**Comment by jgthms** [comment]
Uses `rimraf` now.
