### ISSUE TITLE
Select is breaking down in mobile view

### ISSUE THREAD

**Issue by Shofol** [jgthms/bulma#2745]
This is about **Bulma**.
There is a problem in select in mobile view.

### Overview of the problem
 This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]
 My **browser** is: Chrome

### Description
The select is shrinking when clicking on mobile view. 

### Expected behavior
The select should not be shrink.

![error](https://user-images.githubusercontent.com/30428153/71087791-418a1b80-21c7-11ea-8c32-5c0a23fe5874.png)

**Comment by abnersajr** [comment]
If you take a look at your chrome the zoom size is 80% and this might be causing the issue.
I wasn't able to reproduce this in an emulator neither in a small smartphone.
Try again with 100% zoom and see if still breaking.

**Comment by Shofol** [comment]
No, the screen size is not the issue. I will give you a live example then.
