### ISSUE TITLE
Cannot find the functions described in the doc

### ISSUE THREAD

**Issue by David263** [jgthms/bulma#2748]
This is about **the Docs**.

question

### Overview of the problem

 This is about the Bulma **Docs** 

### Description

Page https://bulma.io/documentation/overview/functions/ describes some functions but doesn't say where they live. Bulma is supposed to be a single css file, bulma.css. I can't find these functions in this file.

**Comment by jgthms** [comment]
So CSS doesn’t support functions. Only Sass does. You can find them here https://github.com/jgthms/bulma/blob/master/sass/utilities/functions.sass

**Comment by David263** [comment]
Closed, except you didn't say you would change the documentation. I don't want to use the Sass program. Please use a unique color or some other marking next to any documentation that requires Sass, and explain this marking at the beginning of the documentation. Thanks.
