### ISSUE TITLE
Progress color not working

### ISSUE THREAD

**Issue by MangelMaxime** [jgthms/bulma#275]
Hello guys, on the [demo site](http://bulma.io/documentation/elements/progress/) and in my project, the `progress` bars are not styled by the `is-success | is-danger` classes.

I think this is a bug because otherwise I don't see the purpose of this sample:

``` html
<progress class="progress" value="15" max="100">15%</progress>
<progress class="progress is-primary" value="30" max="100">30%</progress>
<progress class="progress is-info" value="45" max="100">45%</progress>
<progress class="progress is-success" value="60" max="100">60%</progress>
<progress class="progress is-warning" value="75" max="100">75%</progress>
<progress class="progress is-danger" value="90" max="100">90%</progress>
```

**Comment by jens1o** [comment]
It's styled on the demo site.

**Comment by MangelMaxime** [comment]
It's styled under Firefox but not Edge.
I just tested out different browsers. Sorry.

According to [Can I Use](http://caniuse.com/#search=progress), it's should work under Edge too.

**Comment by jens1o** [comment]
wow. it is a bug, but you won't fix it, without any note?...

**Comment by jgthms** [comment]
It's a browser bug.
