### ISSUE TITLE
How to replace "·" with <ul> and list-style-type: disc;?

### ISSUE THREAD

**Issue by 1234dev** [jgthms/bulma#2753]
Bulma's HTML examples are full of sporadic use of unsemantic HTML such as " · " to separate links within a `<p>`, whereas it should be:

```
<ul>
  <li></li>
  <li></li>
  <li></li>
</ul>
```

with `list-style-type: disc`. But no matter how much I try to apply this, and overriding similar settings, I seem to have no luck.

Any chance anybody here'd know? Thanks!

**Comment by 1234dev** [comment]
Note that "·" causes web frameworks like Ruby on Rails to error out with no stack trace or anything. It was just through pure luck that we managed to figure it out.

**Comment by jgthms** [comment]
> Bulma's HTML examples are full of sporadic use of unsemantic HTML such as " · " to separate links within a `<p>`

Do you have a link to a page with such an example?

**Comment by 1234dev** [comment]
Hi @jgthms and a happy new year!

Ie. the nesting example at https://bulma.io/documentation/layout/media-object/ but the problem is not so much removing the dots from the HTML, but rather how to move it over to CSS without it getting overriden by Bulma despite repeated use of `!important`.

To see how it affects Ruby on Rails I'll try to set up a Heroku instance for you later on.

Cheers!

**Comment by jgthms** [comment]
That part is simply to demonstrate what you can put inside a “content” element. But really you can put anything inside the “content” or even remove it completely.

**Comment by 1234dev** [comment]
True, but for some reason Bulma overrides `list-style-type: disc !important` no matter what I try. I probably slipped up somewhere, I'll have a second go after new years.

As for demonstrating use, you might be better off showcasing and promoting proper HTML while at the same time avoiding strange characters that cause weird errors with the world's most popular web frameworks.
