### ISSUE TITLE
Update progress bar from `requestAnimationFrame`

### ISSUE THREAD

**Issue by cwilby** [jgthms/bulma#2754]
This is about **Bulma**.  It is a bug/question about progress bars and requestAnimationFrame.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.7.5
My **browser** is: Chrome latest

### Description

I'm building a component that calculates/displays playback progress of multiple videos.  To do this, I'm using `requestAnimationFrame` to set a `progress` value which is bound to a bulma progress bar using Buefy.  The values update correctly, but the progress bar doesn't update until the end of the video.  I think it's because the CSS transition of the progress bar is slower than the frequency of the animation, so nothing happens.

### Steps to reproduce

This single video example demonstrates the issue using Vue and Buefy, but the issue stems from Bulma.

`VideoPlayer.vue`
```vue
<template>
  <div>
    <b-progress :value="progress" show-value>{{ progress }}%</b-progress>
    <video
      ref="player"
      @play="onPlay"
      @pause="onStop"
      @ended="onStop"
      :src="videoUrl"
    ></video>
  </div>
</template>

<script>
export default {
  name: 'VideoPlayer',
  
  props: ['videoUrl'],

  data: () => ({
    progress: 0,
    watcher: null
  }),

  methods: {
    onPlay() {
      this.watcher = requestAnimationFrame(() => this.updateProgress());
    },

    onStop() {
      cancelAnimationFrame(this.watcher);
    },

    updateProgress() {
      const { currentTime, duration } = this.$refs.player;
      this.progress = currentTime / duration * 100;
      this.watcher = requestAnimationFrame(() => this.updateProgress());
    }
  }
};
</script>
```

**Comment by jgthms** [comment]
So there’s no transition on the progress bar, only an animation. But this animation is only present when the progress bar is indeterminate, meaning when it has no value or no “max” attribute. So maybe your value or the max is not a floating point number.

**Comment by cwilby** [comment]
@jgthms Thanks, adding a max attribute fixed the issue!
