### ISSUE TITLE
Sass base scroll bar issue

### ISSUE THREAD

**Issue by xxsuperdreamxx** [jgthms/bulma#2757]
Is it a bug/feature/question or do you need help?
Bug

### Overview of the problem

 I'm using Bulma **version** [^0.8.0]

This is a **Sass** issue: I'm using version [^4.13.0]
I am sure this issue is **not a duplicate**? Didn't find it.

I am currently developing a Theme for the Bulma and noticed something the scroll bar is always on and it is bugging me out this issue is coming from 
@import "../node_modules/bulma/sass/base/_all.sass";
![image](https://user-images.githubusercontent.com/20241808/71601570-b01e9000-2b5c-11ea-878a-3eafd229e3c7.png)

**Comment by xxsuperdreamxx** [comment]
Commenting   // overflow-y: $body-overflow-y for the HTML tag is fixing the annoying scroll bar

**Comment by jgthms** [comment]
It has been mentioned before. It’s done on purpose so that when navigating between pages of different height, the width of the viewport doesn’t “jump”.

**Comment by xxsuperdreamxx** [comment]
Oh alright it was something which was making me nuts haha

**Comment by ghiscoding** [comment]
I'm new to Bulma and this is also bugging me quite a lot, I thought some of my DOM elements were oversized or something... I'm using the CDN with latest version

Anyway, this brings another issue, if you visit this [Badge Extension](https://demo.creativebulma.net/elements/badge/demonstration/) website, I can eventually see 2 scrollbars after some resizing... that is far from being expected lol

![image](https://user-images.githubusercontent.com/643976/76674248-8f72ad80-6583-11ea-8929-d22f406920a8.png)

**Comment by ChildishGiant** [comment]
This is very annoying when making a single page app, where I know it'll never need to scroll. Maybe a class to disable this would be good?
