### ISSUE TITLE
[Feature Request] Circular Progress Bar

### ISSUE THREAD

**Issue by kkesley** [jgthms/bulma#2760]
This is about **Bulma**.

### Overview of the feature request

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]

### Description

Would you consider adding a circular progress bar to the [current progress bar](https://bulma.io/documentation/elements/progress/)?

Maybe add a class `is-circle` to the element? e.g. `<progress class="progress is-circle" value="15" max="100">15%</progress>`

Example:

![circular-progress-bar-example](https://user-images.githubusercontent.com/14907878/71759756-0e08fa00-2f06-11ea-86bf-2aca00f69cd1.PNG)

**Comment by suterma** [comment]
I have found a very great circular progress bar here: https://gist.github.com/nicbet/49a681d036ab8c2886e3419a6e8c6efb
It works well, and looks quite similar to the proposal here. Maybe this could get added more or less like in the gist?
