### ISSUE TITLE
Add variables for `dropdown-item` and `navbar-item` padding

### ISSUE THREAD

**Issue by getup8** [jgthms/bulma#2765]
This is a feature request for Bulma.

Would love to see some additional variables for `dropdown-item` and `navbar-item` padding (especially top and bottom as currently I think it's too small).

**Comment by bekwam** [comment]
I'm working through the examples in "Creating User Interfaces with Bulma".  It seems like there is extra dropdown item padding in the books examples, but when I code the examples and view in Firefox and Chrome, the icons are jammed next to the text like this.

![image](https://user-images.githubusercontent.com/6334243/75249195-c2efc280-57a3-11ea-9a17-aac890b3e213.png)
