### ISSUE TITLE
Style information provided by parsed sourcemap points to "wrong" sass file

### ISSUE THREAD

**Issue by contactjavas** [jgthms/bulma#2766]
This is about **Bulma**.
This is a bug regarding Bulma's source map.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]
My **browser** is: Latest Chrome
I am sure this issue is **not a duplicate**

### Description

The style information provided by source map (when inspecting element) almost always leads to wrong sass/ scss file. This makes the source map become *useless*. Because we have nothing to do with the information provided when inspecting elements.

### Steps to Reproduce

1. Download official Bulma or bulma-scss via npm
2. Write some layout
3. Inspect element and check the style information provided from parsed sourcemap

### Expected behavior

Source map's style information should be helpful, lead to the correct file.

### Actual behavior

The style information provided from parsed source map leads to wrong file.

**Comment by jinlaohu** [comment]
I'm use Bulma 0.8.0 and success generated map by gulp-dart-sass but it's not show in any browser, search for any causes and no clues.

**Comment by contactjavas** [comment]
> I'm use Bulma 0.8.0 and success generated map by gulp-dart-sass but it's not show in any browser, search for any causes and no clues, not sure about Bulma.

Yea, the map is generated.. but the information provided by it (when inspecting element) is not useful (we can't just go to the right sass/ scss file). Maybe this is because lot of Bulma's output are generated through mixins. 

But still, whatever the cause, this makes the provided style when inspecting elements become useless.
