### ISSUE TITLE
Mixins.scss uses un-imported variables.

### ISSUE THREAD

**Issue by Didel** [jgthms/bulma#2773]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.0
This is a **Sass** issue.
I am _almost_ sure this issue is **not a duplicate**.

### Description

[Utilities/mixins.scss](https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass) includes`@import "initial-variables"` in order to resolve the variables used in the various defined mixins. However, version 0.8.0 includes a mixin (=delete) that makes use of the `$scheme-invert` variable, while it is not specified in the included initial-variables.scss .

This will cause a problem if you only import the mixins, because the `$scheme-invert` variable will be undefined. 

### Steps to Reproduce

- Create a new .scss file
- Import the mixins.scss from Bulma (e.g. `@import "./node_modules/bulma/sass/utilities/mixins";`)
- compile the .scss file you created above.

### Expected behavior

No compilation errors.

### Actual behavior

I got a compiler error:
```
{
  "status": 1,
  "file": "../node_modules/bulma/sass/utilities/mixins.sass",
  "line": 173,
  "column": 26,
  "message": "Undefined variable: \"$scheme-invert\".",
  "formatted": "Error: Undefined variable: \"$scheme-invert\".\n        on line 173 of node_modules/bulma/sass/utilities/mixins.sass, in mixin `delete`\n        from line 236 of node_modules/bulma/sass/utilities/mixins.sass\n        from line 1 of src/base/mixins.scss\n        from line 4 of src/base/all.scss\n>>   background-color: rgba($scheme-invert, 0.2);\n\n   -------------------------^\n"
}
```

**Comment by Didel** [comment]
I have created Pull-Request #2774 that will fix this issue.

**Comment by crabnky** [comment]
Have the same - when can I expect fix to be released?

**Comment by DiCrEn** [comment]
Meanwhile I fix it importing all the files that are necessary

```
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/derived-variables";
@import "~bulma/sass/utilities/mixins";
```

**Comment by gonzofish** [comment]
@DiCrEn I believe `initial-variables` is already imported into `mixins`

**Comment by CallumWatkins** [comment]
> @DiCrEn I believe `initial-variables` is already imported into `mixins`

`derived-variables` also requires `initial-variables` to be imported first, regardless of `mixins`.

**Comment by gonzofish** [comment]
Ah, right, @CallumWatkins, good point!

**Comment by Didel** [comment]
> > @DiCrEn I believe `initial-variables` is already imported into `mixins`
> 
> `derived-variables` also requires `initial-variables` to be imported first, regardless of `mixins`.

@gonzofish Exactly, that is why in #2774 I've also added the `derived-variables` import to `mixins.sass`. This way, you can choose to only import `mixins.sass` without having to worry about importing other dependencies.

**Comment by Didel** [comment]
I don’t agree with the Stale bot. As the PR hasn’t been merged yet, it should not be closed.

**Comment by Artem-Schander** [comment]
It takes almost four years to fix this issue?

**Comment by Didel** [comment]
> It takes almost four years to fix this issue?
@Artem-Schander I don’t know what you mean, this ticket was created in January of this year.

@jgthms what a great way to show how thankful you are to people who contribute. After 10 months of (seeming) inactivity, you close the issue by ignoring the created PR, and instead create a commit of your own without any credit to someone who has supplied (part of) the solution. Then you continue to close this ticket without any message, at least a simple ‘thank you for your contribution’ would have been nice.

If it takes 10 months to look into a change of 1 line of scss, together with what I said in the lines above, that does raise serious questions about the state of the project and its maintainers. The open source community is a wonderful community, but if you treat them like this, don’t expect people to actively contribute in the future any more.

**Comment by Artem-Schander** [comment]
@Didel You‘re right. My bad. I‘ve seen the 17 and thought, what a long time.
However, 10 months is a long time for this kind of issue as well.
I subscribed to this issue a long time ago and would like to see the PR merged or the issue resolved. It sucks that i can not use the scss for the newer stuff.

**Comment by dbryar** [comment]
Latest NPM package (0.9.1) still does not have this issue fixed so the build fails in a TypeScript VueJS app without the PR included.

**Comment by alexd73** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bulma@0.9.1` for the project I'm working on.



Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bulma/sass/utilities/mixins.sass b/node_modules/bulma/sass/utilities/mixins.sass
index 0ed78c1..7c5ee20 100644
--- a/node_modules/bulma/sass/utilities/mixins.sass
+++ b/node_modules/bulma/sass/utilities/mixins.sass
@@ -1,4 +1,5 @@
 @import "initial-variables"
+@import "derived-variables"
 
 =clearfix
   &::after
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>
