### ISSUE TITLE
Horizontal forms, misalignes.

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#278]
As of d7379e8b22a30cc1d528a031bed6523e15649e3a, horizontal forms became unaligned. See [Forms documention](http://bulma.io/documentation/elements/form/) at the Horizontal Forms section (bottom of the page).

I'm suspecting, it's caused by the removal of the `flex` shorthand e.g: `flex: 5` -> `flex-grow: 5` as this is leaving out the `child`styles of the `flex` style:

For instance, `flex: 5` is equal to:
```css
flex-grow: 5;
flex-shrink: 1;
flex-basis: 0%;
```
I tried adding just `flex-basis: 0%`, which looks like it solved the problem.

**Comment by citycide** [comment]
I can back this one up. It's also the case for `level`. The first `level-item` ends up being wider than the rest. Changing `flex-grow: 1` to `flex: 1` or keeping `flex-grow` and using `flex-basis: 0%` as @jeppech mentioned solves it.

**Comment by jgthms** [comment]
I believe this has been fixed.
