### ISSUE TITLE
No link to List component in docs

### ISSUE THREAD

**Issue by sporifolous** [jgthms/bulma#2780]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The [list component](https://bulma.io/documentation/components/list/) doesn't seem to have a menu option in the documentation. 

### Steps to Reproduce

1. Go to https://bulma.io/documentation/components/
2. See that there is no link to the List component docs
3. Click any of the other components
4. See that the tab menu at the top also does not contain a link to the List docs

### Expected behavior

Expected to see a link to the List component docs (https://bulma.io/documentation/components/list/)

### Actual behavior

No such link is provided.

**Comment by Anish-Agnihotri** [comment]
Just hopped in and added List to the component docs in #2782. 

It should now show up in sidebar menu, tab menu at the top, and in the [Coming from Boostrap](https://bulma.io/alternative-to-bootstrap/) comparison table.

**Comment by service-paradis** [comment]
I dont think it will be merged according to #2402

**Comment by Anish-Agnihotri** [comment]
Ah shoot, my apologies. Hadn't noticed that this may be a duplicate issue.

If the component is not in the deprecation pipeline already, I would be happy to bring it up to spec for re-release?

**Comment by service-paradis** [comment]
Will need to ask @jgthms

**Comment by jgthms** [comment]
The list is too close to the panel in my opinion. I feel like it would bloat Bulma to have both. It was a mistake to add the list in the first place.

**Comment by lgg** [comment]
@jgthms hello, any news about this issue?

**Comment by lgg** [comment]
ping jgthms

**Comment by lgg** [comment]
ping @jgthms
