### ISSUE TITLE
link color bug on safari

### ISSUE THREAD

**Issue by fabienrohrer** [jgthms/bulma#2785]
## Description

On Safari only, the link color is not correctly computed when inserted in a hero with some color modifier.

## To reproduce

```
<section class="hero is-info">
  <a>Hello world</a>
</section>

<section class="hero">
  <a>Hello world</a>
</section>
```

Result:

| Correct behavior (Chrome) | Wrong behavior (Safari) |
| --- | --- |
| ![correct behavior](https://user-images.githubusercontent.com/866788/73375150-aacb7700-42bb-11ea-86ab-b4798d6d6ac9.png) | ![wrong behavior](https://user-images.githubusercontent.com/866788/73375151-aacb7700-42bb-11ea-9bdb-14c6b0b17a94.png) |

I expect that the link color should be `$link-color` as on Chrome.

## Reason

When not working (on Safari only), the following rule is triggered:

https://github.com/jgthms/bulma/blob/master/sass/layout/hero.sass#L24-L26

I cannot explain why this occurs only on Safari, but for sure, inheriting the color (i.e. take the parent color) cannot lead to a good result here.

**Comment by fabienrohrer** [comment]
Naively, I would go to drop the lines:

https://github.com/jgthms/bulma/blob/master/sass/layout/hero.sass#L24-L26

.. but I don't know the side effects. I don't see any example when inheriting the color is a good idea.

**Comment by fabienrohrer** [comment]
Could I have the opinion of Bulma maintainers? I could submit a patch to drop these lines.

**Comment by jgthms** [comment]
Do you have a sample HTML code to share? It might come from an error in your markup where the browser doesn’t parse your page correctly.

**Comment by fabienrohrer** [comment]
I confirm I can reproduce the issue with this simple example:

```html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>
  <body>

    <section class="hero is-info">
      <a>Hello world</a>
    </section>

    <section class="hero">
      <a>Hello world</a>
    </section>

  </body>

</html>
```

![Capture d’écran 2020-01-29 à 17 50 24](https://user-images.githubusercontent.com/866788/73377780-e5cfa980-42bf-11ea-9283-73f8377c92da.png)

Do I missed something?

**Comment by jgthms** [comment]
That is the correct behaviour. In `hero` components, all links inherit the text color. Otherwise, the links would be blue on blue.

**Comment by fabienrohrer** [comment]
The bug is that this small sample does not provide the same result on safari (the first ‘hello world’ is white) and on Chrome/Firefox (the first ´Hello World’ is blue). I expect that the Chrome behavior is more correct, but the important thing to me is that Bulma should behave the same in every Browser.

**Comment by jgthms** [comment]
Seems Safari is the only browser to support chaining `:not()` selectors: https://developer.mozilla.org/en-US/docs/Web/CSS/:not#complex-selector-list

**Comment by fabienrohrer** [comment]
Thank you for your reply and interest, this explains indeed why there is a difference here.

- I also observe the same issue in iOS.
- Therefore, using `_not()` in your sass files is not a good idea. It may explain other bugs as this one: #2597 
- This is my personal point of view, but I am not fan of the fact that the link color inherits from its parent in case of `strong` and `a` in a hero section. A link is a link, I would like to be able to see clearly it's a link, consistently in the whole page. => I would go to drop this rule, without pressure :-D 

How to proceed next?
