### ISSUE TITLE
Allow long button labels

### ISSUE THREAD

**Issue by henk23** [jgthms/bulma#2787]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version 0.8.0**
Related issue: #1258 (long text in button outside of the screen)

### Description

At the moment we cannot have long button labels on narrow screens.

![button](https://user-images.githubusercontent.com/10068060/73524791-2b01f180-440e-11ea-9925-a58c1c0868bf.png)

With a slight modification to the .button class this would be possible:

    .button {
      height: auto;
      min-height: $control-height;
      white-space: normal;
    }

Would there be a reason not to do this? (Like for example compatibility with other form elements?)

**Comment by ogai** [comment]
I have been also hit by this issue. If there is some reason not to use

    white-space: normal;
    height: auto;

what about adding the possibility of using the class `.is-multiline` together with the class `button` ?

**Comment by ruihildt** [comment]
FYI, there's a PR #1653 and an easy way to add a `is-multiline` button modifier, just use this css:

```
.button.is-multiline {
  min-height: 2.25em;
  white-space: unset;
  height: auto;
  flex-direction: column;
}
```
Demo: https://codepen.io/timacdonald/pen/EQmQbL

All of this is thanks to @timacdonald 🙏🏻
