### ISSUE TITLE
Documentation: Typo 

### ISSUE THREAD

**Issue by arung86** [jgthms/bulma#279]
### Instructions

**Tiles Documentation has a typo.**  
**http://bulma.io/documentation/grid/tiles/**  
### Description

Documentation says incorrect width for is-4, there is a type over.
bug
### Steps to Reproduce
1. visit http://bulma.io/documentation/grid/tiles/
2. navigate to section How it works: Nesting
3. read description for resize

_Expected behavior:_ is-4 will take 1/3 of horizontal space

_Actual behavior:_ is-4 will take 2/3 of horizontal space

**Comment by jens1o** [comment]
this is a bulma-website issue, not a issue in the actual framework

**Comment by arung86** [comment]
Yes agree with you.

**Comment by jens1o** [comment]
So, please, create this issue at the repo called "bulma-website"

**Comment by vasef** [comment]
isn't `is-4` 1/3 of the space. ? 4 of 12 columns.

**Comment by pkunze** [comment]
This issue can be closed as the docs have been updated
