### ISSUE TITLE
Columns in container not resizing appropriately

### ISSUE THREAD

**Issue by agoldstein03** [jgthms/bulma#2793]
This is about **Bulma**. I am unsure of whether or not this is a bug or my own error. It appears similarly across browsers.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0]
My **browser** is: Chrome, Edge

### Description

Columns inside of a container are not resizing appropriately, with some getting cut off. After it switches to vertical columns it appears fine; the horizontal columns appear to be the issue.
### Steps to Reproduce

1. View [https://codepen.io/agoldstein03/pen/jOEgPwL](https://codepen.io/agoldstein03/pen/jOEgPwL)
2. Resize the window and see how the columns do not resize correctly.

### Expected behavior

A centered, spaced container with equal-sized columns that fit in the container.

### Actual behavior

A not centered, only left-spaced container with non-equal-sized columns that are cut off by the right side of the screen.

**Comment by TeraNovaLP** [comment]
I have the same problem. Columns can flow out of the Container.

![2020-02-02 12_13_10-p-client](https://user-images.githubusercontent.com/16338782/73607467-9090e200-45b6-11ea-8305-63272e8591b6.png)

My code: https://codepen.io/teranovalp/pen/zYxgNOX

With this code I would expect that only two columns are displayed in a row and the other two are displayed below in a second row.

**Comment by hellobetkowski** [comment]
Hey there,
had a go at reproducing what you have created. 

https://codepen.io/hellobetkowski/pen/jOPEemN?editors=1100

Check it out and see if this helps.

**Comment by agoldstein03** [comment]
I think the real issue may be how date inputs are resized. Even when a date input has the input class, it still does not resize correctly, whereas a text input does resize correctly. For example, compare https://codepen.io/agoldstein03/pen/KKpwLMO with https://codepen.io/agoldstein03/pen/Exjazg

**Comment by agoldstein03** [comment]
Any thoughts on how to properly contain a native date input, with proper, consistent spacing, would be much appreciated.

**Comment by hellobetkowski** [comment]
Second link throws 404, could you replace it?

**Comment by agoldstein03** [comment]
Just replaced; sorry about that.

**Comment by hellobetkowski** [comment]
@agoldstein03 
It ain't great, but it kind of works with this workaround:
https://codepen.io/zerosleep/pen/poJJybM

**Comment by agoldstein03** [comment]
Thank you very much for the effort; unfortunately it looks like it still doesn't work quite right closer to the switching point (I think I can tweak it to get it there). But at this point this definitely seems like something that should be fixed in Bulma.
