### ISSUE TITLE
Unable to fully use Bulma Sass with the new Sass modular system (@use)

### ISSUE THREAD

**Issue by chamilleri** [jgthms/bulma#2797]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0] 

This is a **Sass** issue: I'm using version [1.25.0] (Dart Sass)
I am sure this issue is **not a duplicate**

### Description

I was refactoring code to start using the new Sass modular system and at first it was ok, but once I tried to use navbar.sass directly the compiler started complaining:
`
SassError: Undefined variable.
    1 │ $navbar-background-color: $scheme-main !default
` 
I tried several options like placing the variable in the file I am calling this from, pushing the variable though with the 'with' option, calling @import on the derived-variables but nothing worked.
I feel that the Bulma structure would need to be updated to support this.

### Steps to Reproduce
1. `@use "~bulma/sass/components/navbar.sass" with (
  $scheme-main: "red"
);`
2. compile

### Expected behavior

It compiles

### Actual behavior
Get an error
`
SassError: Undefined variable.
    1 │ $navbar-background-color: $scheme-main !default
`

**Comment by chamilleri** [comment]
There is a post on Sass which refers to this issue: https://github.com/sass/sass/issues/2809#issuecomment-573942660

**Comment by jgthms** [comment]
Interesting. I will start working on upgrading Bulma to this new system.

**Comment by twaiiiin** [comment]
A little bit of context: https://sass-lang.com/blog/the-module-system-is-launched

Namespacing variables is a good idea indeed.

**Comment by bkarlson** [comment]
This is kinda breaking change for Bulma, as moving to Yarn 2 (Berry) we don't have `node_modules` anymore and have to resort to `@use` and `@forward`, none of which work with current Bulma release. I'm not well versed in Sass unfort, so cannot help here, but maybe if this issue gets more attention, someone from community can help move to new modular system sooner.

**Comment by twaiiiin** [comment]
I guess at some point, Bulma will have to make some breaking changes between major releases while adding new features (css-variables support or sass module for exemple) It would be wise to group them together in order to limit their impact. 

I would like to help Bulma to move forward, but I don't know the direction that @jgthms wants to give to the project or the mode of governance he wants to adopt. I have ideas (and maybe some criticizes). I'm open to talk about it further.

**Comment by chamilleri** [comment]
I would just like to check if this issue is being addressed.

**Comment by Pipzero** [comment]
I have found a solution.

Prefix all the sass files with underscore ( _ ), and in all @import "file.sass", remove the ".sass"

**Comment by Pipzero** [comment]
> This is kinda breaking change for Bulma, as moving to Yarn 2 (Berry) we don't have `node_modules` anymore and have to resort to `@use` and `@forward`, none of which work with current Bulma release. I'm not well versed in Sass unfort, so cannot help here, but maybe if this issue gets more attention, someone from this community can help move to new modular system sooner.

I have managed to eliminate the error by prefixing underscore ( _ ) to all the Sass files.
Also, remove all the underscore ( _ ) in your @import file name, as well as the ".sass" file extension

![bulma_solution](https://user-images.githubusercontent.com/5483898/78807625-eb035000-79f6-11ea-83ce-37105aec6165.jpg)

**Comment by muodov** [comment]
Is there any update on this?

**Comment by 3rdSenna** [comment]
Same issue here

**Comment by janhaa** [comment]
Are there concrete ways to help here? I just updated bulma and unfortunately face the same issue. Any directions?

**Comment by fredDesign** [comment]
Im really disapointed by this system 
The navbar scss use a color map with only 2 colors ,  one for the background , the other for the text-color.
There is some manipulation based on lighten/darken for the others states .
Its really limited for make a design . 
Hope for remove the manipulations and use at least 4 colors (background,color, activebackground, active color ) maybe more.

**Comment by jgthms** [comment]
Yes this could be improved. Some of the manipulations are done for the colors map but could be moved globally.

**Comment by FeixuRuins** [comment]
Any updates? Anything that I import gives me an undefined variable error. The only thing that works is if I import `bulma/all`, which ruins the whole modular aspect.
I'm using `node-sass-middleware` and Bootstrap worked fine :\

**Comment by MrToxy** [comment]
I was able to actually make this work without any additional packages:

// vendors/_bulma.scss

```scss
@charset "utf-8";

@forward '~bulma/bulma' with(
  $danger: blue,
  $size-1: 50rem,
);
```

// vendors/index.scss
@use 'bulma';

// index.scss
@use 'vendors';

**Comment by PixsaOJ** [comment]
@MrToxy What if I have colors.css file with all the custom colors to pass with bulma?
