### ISSUE TITLE
Font awesome icons disappear on new page load

### ISSUE THREAD

**Issue by HarshdipD** [jgthms/bulma#2799]
This is about **Bulma**.
Specifically, this is about a bug in Bulma.

### Overview of the problem

This is about the Bulma **CSS framework**

My **browser** is:
Chrome and Firefox

I'm using **Ruby on Rails** framework without the Bulma gem, just the external Bulma link in `<head>`. I don't think that should be a problem.

I am sure this issue is **not a duplicate**?
No, but I couldn't find anything related to it.

### Description

I'm using font-awesome icons in the navbar, but they disappear every time I go to a new page. They appear back when I reload the page.

### Steps to Reproduce

1. Adding these lines in `buttons` class div which is in `navbar-item` div: 

`<%= link_to raw("<span class=\"icon\"><i class=\"fas fa-plus\"></i></span><strong>&nbsp;Post</strong>"), new_post_path, class: 'button is-info' %>`

2. Reload page to see the change - works perfectly
![image](https://user-images.githubusercontent.com/31940194/73761135-5ea98800-473c-11ea-863d-766f8722d365.png)

3. Go to this link or any other link in the navbar - Icon disappears.
![image](https://user-images.githubusercontent.com/31940194/73761161-69641d00-473c-11ea-9544-7d23a710b337.png)

4. Reload the page - icon is back.
![image](https://user-images.githubusercontent.com/31940194/73761170-708b2b00-473c-11ea-96ab-cf09d8a97a61.png)

### Expected behavior

Icons should be there every user goes to a new page

### Actual behavior

The page needs to be reloaded after visiting to see the icons.

**Comment by jgthms** [comment]
This is an issue with Font Awesome not loading. The styling is there so it doesn't seem to be an issue caused by Bulma.

**Comment by HarshdipD** [comment]
My application is pretty simple, and I'm not using any other CSS external or internal.

**Comment by jgthms** [comment]
How do you load Font Awesome?

**Comment by HarshdipD** [comment]
I used the starter template which loads the icons as an external script. This code is in application.html.erb so it's loaded on every page 

https://bulma.io/documentation/overview/start/#starter-template

**Comment by kiminohero** [comment]
@HarshdipD I am also facing the same problem. I am using bulma in my nextjs app. I am also loading the font awesome icons in the head tags as per the starter template.
