### ISSUE TITLE
type error .hero .tabs .ul in Stylesheets

### ISSUE THREAD

**Issue by SDJeff** [jgthms/bulma#2800]
I think in the current version 0.8.0 is an type error.

Instead of:

`.hero .tabs ul {
    border-bottom: none;
}`

it should be:

`.hero.tabs ul {
    border-bottom: none;
}`

because otherwise the border of the tab items are set to NONE if you use them f.e. in a Card.

**Comment by jgthms** [comment]
No that is correct. It’s targeting unordered lists that are in tabs which themselves are in a hero. There’s no cards here.

**Comment by SDJeff** [comment]
![image](https://user-images.githubusercontent.com/2220942/73836549-d1cffe80-480f-11ea-9073-435d15248f92.png)

So it looks here, instead of normally:

![image](https://user-images.githubusercontent.com/2220942/73837223-4fe0d500-4811-11ea-91a3-466b5ed2015f.png)

**Comment by SDJeff** [comment]
Here we're talking about .tabs and not about unordered list. The function of an tab-item is to look like one. Correct?

**Comment by jgthms** [comment]
What does your html look like?

**Comment by SDJeff** [comment]
`<div class="columns">
                            <div class="column">
                                <div class="card card-is-fullheight">
                                    <header class="card-header">
                                        <p class="card-header-title">
                                            <span class="icon"><i class="far fa-address-card"></i></span>
                                            <span>Address</span>
                                        </p>
                                    </header>
                                    <div class="card-content">
                                        <b-tabs v-model="activeTab" type="is-boxed">
                                            <b-tab-item label="Company Address" icon="building">
                                                <p>
                                                    <strong>{{ props.row.company.address_line1 }}</strong>
                                                    <span v-show="props.row.company.street_line2"><br>{{ props.row.company.address_line2 }}</span>
                                                </p>
                                                <p>
                                                    {{ props.row.company.street_line1 }}
                                                    <span v-show="props.row.company.street_line2"><br>{{ props.row.company.street_line2 }}</span>
                                                </p>
                                                <p>
                                                    {{ props.row.company.zip }} {{ props.row.company.city }}<br>
                                                    {{ props.row.company.country }}
                                                </p>
                                            </b-tab-item>

                                            <b-tab-item label="Private Address" icon="address-book">
                                                <p>
                                                    <strong>{{ props.row.address_line1 }}</strong>
                                                    <span
                                                        v-show="props.row.firstname"><br>{{ props.row.lastname }}</span>
                                                </p>
                                                <p>
                                                    {{ props.row.street_line1 }}
                                                    <span v-show="props.row.street_line2"><br>{{ props.row.street_line2 }}</span>
                                                </p>
                                                <p>
                                                    {{ props.row.zip }} {{ props.row.city }}<br>
                                                    {{ props.row.country }}
                                                </p>
                                            </b-tab-item>
                                        </b-tabs>
                                    </div>
                                </div>
                            </div>`
