### ISSUE TITLE
SASS function findDarkColor not working correctly

### ISSUE THREAD

**Issue by basejump** [jgthms/bulma#2805]
#### Purpose

Darker colors, specifcally $danger-dark, are not being created properly

#### How to reproduce
as outlined here https://bulma.io/documentation/customize/with-node-sass/
create a mystyles.scss with the following
```
@charset "utf-8";
$red: #af0d2e;
@import "../node_modules/bulma/sass/utilities/_all.sass";

@debug "***** $red: #{$red}"; //#af0d2e
@debug "***** $danger: #{$danger}"; //#af0d2e
@debug "***** $findDarkColor($red): #{findDarkColor($red)}"; //#ee1642
@debug "***** $danger-dark: #{$danger-dark}"; //#ee1642
```

produces

```
***** $red: #af0d2e
***** $danger: #af0d2e
***** $findDarkColor($red): #ee1642
***** $danger-dark: #ee1642
```

Where $danger is `#af0d2e` correctly being set to $red in utilities but $findDarkColor($red) produces `#ee1642` which is clearly a lighter red. 

#### What we did to fix for us

```
@charset "utf-8";
$red: #af0d2e;
// instead of importing utilities/_all.sass do each file so we can override findDarkColor
@import "~bulma/sass/utilities/initial-variables.sass";
@import "~bulma/sass/utilities/functions.sass";

//there is a problem with the bulma findDarkColor, doesn't alway darken so override.
@function findDarkColor($color) {
  @if type-of($color) == 'color' {
    @return scale-color($danger, $lightness: -20%);
  }
  @return $text-strong;
}
@import "~bulma/sass/utilities/derived-variables.sass";
@import "~bulma/sass/utilities/animations.sass";
@import "~bulma/sass/utilities/mixins.sass";
@import "~bulma/sass/utilities/controls.sass";

@debug "***** $red: #{$red}"; //#af0d2e
@debug "***** $danger: #{$danger}"; //#af0d2e
@debug "***** $findDarkColor($red): #{findDarkColor($red)}"; //#ee1642
@debug "***** $danger-dark: #{$danger-dark}"; //#ee1642
```
produces 

```
***** $red: #af0d2e
***** $danger: #af0d2e
***** $findDarkColor($red): #8c0a25
***** $danger-dark: #8c0a25
```

Where danger is `#af0d2e` and danger-darker is `#8c0a25` which is an accurate "darker" color

**Comment by uptonking** [comment]
your  implementation  of  `findDarkColor` is simple and better to understand.    
bulma's implementation contains so many magic numbers. It's hard for me to understand.    

`$base-l`  is decimal, is less than 1. But `$luminance-delta` may be negative decimal.

```
@function findDarkColor($color)
  @if type-of($color) == 'color'
    $base-l: 29%
    $luminance: colorLuminance($color)
    $luminance-delta: (0.53 - $luminance)
    $target-l: round($base-l + ($luminance-delta * 53))
    @return change-color($color, $lightness: max($base-l, $target-l))
  @return $text-strong
```

**Comment by xdivby0** [comment]
I don't know if this is the right place to ask (if not, simply delete this or tell me to). I have the same problem for my primary color and I thought pasting the @function directive into my initializing scss file would solve this but it didn't. I import bulma in one go (import bulma.sass, not the individual parts), maybe that's the mistake. I tried overriding the function after importing bulma and also tried to define it before importing bulma. 

Both following methods are not working for me (not working as in displaying the brighter color instead of a darker one):
```
@import "../node_modules/bulma/bulma.sass";
// temporary fix for findDarkerColor
@function findDarkColor($color) {
  @if type-of($color) == 'color' {
    @return scale-color($danger, $lightness: -20%);
  }
  @return $text-strong;
}
```

```
// temporary fix for findDarkerColor
@function findDarkColor($color) {
  @if type-of($color) == 'color' {
    @return scale-color($danger, $lightness: -20%);
  }
  @return $text-strong;
}
@import "../node_modules/bulma/bulma.sass";
```

Can someone point me into the right direction?

**Comment by dejurin** [comment]
I got only greys colors

**Comment by josephbow** [comment]
I believe that there's a small error in the fix posted by @basejump above.

The function return from above uses `$danger` as the argument:

`@return scale-color($danger, $lightness: -20%);`

but the initial argument `$color` needs to be used:

`@return scale-color($color, $lightness: -20%);`

**Comment by mjsarfatti** [comment]
This issue is still present, as the function has never been amended.

**Comment by iameru** [comment]
can confirm, standard nodesass using the instructions from the documentation will leave me with non-working `primary-light` and `primary-dark` (just plain not working)
