### ISSUE TITLE
What's the best way to do this?

### ISSUE THREAD

**Issue by santiagobasulto** [jgthms/bulma#281]
I'm trying to make sense out of the grid, layout and the docs.

I'm trying to have a centered column with some padding at the right and left on big screens, but have just 1 big column (that takes the entire screen) on small screens (tablet, mobile). Here you can see the end result:

Desktop:
![image](https://cloud.githubusercontent.com/assets/872296/17482530/8bfbf472-5d58-11e6-8b39-674c9543e34c.png)

Smaller screens:
![image](https://cloud.githubusercontent.com/assets/872296/17482542/9ed23b2e-5d58-11e6-852a-9aec16e897a8.png)

With bootstrap, I'd do something like:

``` html
<div class="col-md-12 col-lg-8 col-lg-offset-4"></div>
```

My current code using bulma is:

``` html
<section class="section">
  <div class="columns">
    <div class="column is-one-quarter is-hidden-touch"></div>
    <div class="column" style="text-align: center;">
      Main content
    </div>
    <div class="column is-one-quarter is-hidden-touch"></div>
  </div>
</section>
```

Is it the correct way?

**Comment by bordalix** [comment]
Why not simply this?

```
<section class="section">
  <div class="columns">
    <div class="column has-text-centered">
      Main content
    </div>
  </div>
</section>
```
