### ISSUE TITLE
Modal Style

### ISSUE THREAD

**Issue by kanrar-subhankar** [jgthms/bulma#282]
For some modal like image modal the simple cross sign is coming top of the corner.But it would be better if it can be kept on the top of the modal corner as like modal card.Default tab line should be removed.

**Comment by jgthms** [comment]
You could move `modal-close` inside `modal-content` and set it to `position: absolute`.

But as the content of `modal-content` can be almost anything, I'd rather leave the close button in the top right corner by default.
