### ISSUE TITLE
Notification inside Hero may make Title & Subtitle unreadable

### ISSUE THREAD

**Issue by awhitford** [jgthms/bulma#2825]
This is about **Bulma**.

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]
My **browser** is: Chrome Version 80.0.3987.106 (Official Build) (64-bit).
I am sure this issue is **not a duplicate**

### Description
When embedding a Notification inside a Hero, the Title and Subtitle classes may not be readable.  The Hero.Title and Hero.Subtitle colors override the Notification -- so when the Notification has a contrasting color to the Hero, the font colors are light/light or dark/dark instead of light/dark.

### Steps to Reproduce

```html
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column">
          <p class="title">Title</p>
          <p class="subtitle">Subtitle</p>
          <p>Some content.</p>
        </div>
        <div class="column">
          <div class="notification">
            <p class="title">Title is legible</p>
            <p class="subtitle">Subtitle is legible</p>
            <p>Some content.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column">
          <p class="title">Title</p>
          <p class="subtitle">Subtitle</p>
          <p>Some content.</p>
        </div>
        <div class="column">
          <div class="notification">
            <p class="title">Title is not legible</p>
            <p class="subtitle">Subtitle is not legible</p>
            <p>Some content.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
```

### Expected behavior

I would expect that the Title and Subtitle would be controlled by its surrounding Notification, not the parent Hero.

### Actual behavior

Instead, the Title and Subtitle are impacted by the Hero.

**Comment by VizuaaLOG** [comment]
I could be completely wrong here, bit titles and subtitles are not intended to be inside a notification are they?

**Comment by awhitford** [comment]
Aren't titles and subtitles just content that can be placed anywhere?  (The [documentation](https://bulma.io/documentation/elements/title/) does not state any restriction.)

**Comment by VizuaaLOG** [comment]
Apologies for the delay in responding! I did not see the notification for your reply 😞

Although the docs don't state it, titles and subtitles are semantically for adding titles to sections of content. Notifications are to just display some text to notify the user of something and wouldn't usually require a large title. Instead of bolding some text would be sufficient.

Although it may be an idea to add this as a feature as some situations may need the addition of a larger title, personally I don't ever see a need for this since a notification should be a fairly short 'hey something happened'.
