### ISSUE TITLE
iTemplate (Bulma Admin Template ) jQuery 3 + bootsrap 4 javascript library

### ISSUE THREAD

**Issue by bendo01** [jgthms/bulma#283]
i've created a simple admin template using jquery 3 and bootsrap 4 javascript library and bulma
the source code are here https://github.com/bendo01/itemplate
you can view it live here http://itemplate.ga
hope to see your feed back
@jgthms Thank You For Bulma

**Comment by jgthms** [comment]
That looks great! I'll add it to the list of related projects.
