### ISSUE TITLE
is-light not working

### ISSUE THREAD

**Issue by mezeipetister** [jgthms/bulma#2846]
Hi!
I am using Bulma 0.8.0 via NPM module, and I have a style.sass file with the following:
```sass
@import "../node_modules/bulma/bulma.sass"
```
Bulma works great, but **is-light** not working in .notification tag.

Do you have any idea what can be wrogn?

Thank you in advance!

Best wishes,
Peter Mezei.

**Comment by jgthms** [comment]
It's coming soon!

**Comment by ukhanzada-nisum-com** [comment]
@jgthms still facing the same issue `"bulma": "^0.7.1",`

**Comment by jcsoriano** [comment]
I am also facing the same issue, using bulma v0.8.17. The docs are a bit misleading:

**Comment by gregpassmore** [comment]
This is still not working for me, the `is-light` examples from the docs don't work. FWIW I'm using 0.8.2 via npm in a react app.

**Comment by dnymxm** [comment]
Same problem here

**Comment by jesuskinto** [comment]
Same problem with Buefy :(

**Comment by TupleTechnologies** [comment]
Can we get this opened? When are we expecting this feature? It's already mentioned in the documentation but doesn't work as of now.

**Comment by mezeipetister** [comment]
@jgthms could you please reflect the comments shown above? Its really misleading, and discourage using Bulma with almost zero communication with the devs.

**Comment by TupleTechnologies** [comment]
I can confirm it's working on 0.9.0. Thanks @jgthms!! Hope Bulma continues to be active going forward and does not leave us Devs high and dry after a few years down the line.

**Comment by ckyleda** [comment]
I also have this issue, updated to 0.9.0, is-light does absolutely nothing. Any update on this issue? The docs also say available on 0.8.0, yet this also does not work.

**Comment by mezeipetister** [comment]
For me its working. Be sure you are using is-light at a correct place. So eg: https://bulma.io/documentation/elements/notification/
As I understand it correctly, is-light is valid under a notification.

**Comment by leonfancy** [comment]
It's not working for [tags](https://buefy.org/documentation/tag/).

**Comment by mimiza** [comment]
it's not working at all

**Comment by Hith14** [comment]
Worked without issues in v0.9.2
