### ISSUE TITLE
how do i align text to the right of a button?

### ISSUE THREAD

**Issue by AnderssonPeter** [jgthms/bulma#2849]
i have a login form, and im trying to show the login error to the right of my login button, but the text is not centered, what css class can i use to achive the desired result?

![image](https://user-images.githubusercontent.com/1308309/75441543-26255480-595e-11ea-9034-099436ea0e87.png)

```
<div class="field is-grouped">
    <div class="control">
        <button class="button is-primary" type="submit">Login</button>
    </div>
    <div class="control">
        <p class="has-text-danger">error</p>
    </div>
</div>
```

**Comment by RohitKumarGit** [comment]
What yo want to do?

**Comment by ludemys** [comment]
You can put those two elements in a container and center them with flexbox, like this!
![image](https://user-images.githubusercontent.com/52580686/77713901-6ce68880-6fb6-11ea-9fec-423f2e855766.png)
![image](https://user-images.githubusercontent.com/52580686/77713907-71ab3c80-6fb6-11ea-97d5-eff97eddffd4.png)
