### ISSUE TITLE
Sample project with working compiler and sample page..

### ISSUE THREAD

**Issue by ShaggyDude** [jgthms/bulma#285]
Hello,

I love this project as a replacement for bootstrap and others.
Is there a repo somewhere that I can just pull down and edit sass and compile?
I don't really care what runner it uses.

WIth the sample pages would be best but someone please point me to how I can play around with source.

Thanks,,

**Comment by joshmanders** [comment]
@ShaggyDude 
> Is there a repo somewhere that I can just pull down and edit sass and compile?

Yes, you can get the source at https://github.com/jgthms/bulma

**Comment by jgthms** [comment]
Cheers @joshmanders
