### ISSUE TITLE
Use SASS mixins in SCSS code

### ISSUE THREAD

**Issue by simplenotezy** [jgthms/bulma#2858]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **1.2.1^**

### Description

I am building an application in Vue & Nuxt.js and I am using SCSS as my primary language for writing styles. However, I need to import the mixins from Bulma, but I can't since they are written in SASS.

How can I use the bulma mixins in SCSS instead?

**Comment by jgthms** [comment]
You can. For example, instead of `+mobile`, just write them in Scss:

```
@include mobile {
  /* Your code */
}
```
