### ISSUE TITLE
BulmaStart links broken in docs

### ISSUE THREAD

**Issue by jbeeko** [jgthms/bulma#2860]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description

The links to BulmaStart at the bottom of this page http://versions.bulma.io/0.7.0/documentation/overview/start/#bulma-start are broken. 

### Steps to Reproduce

1. Navigate to http://versions.bulma.io/0.7.0/documentation/overview/start/#bulma-start
2. Click on either the BulmaStart button or the check-it-out button and the result is a 404. 

### Expected behavior

Go to the page

### Actual behavior

404

**Comment by EliaSulimanov** [comment]
I think that the current link should be [https://bulma.io/bulma-start/](https://bulma.io/bulma-start/).

The issue sits here: [https://github.com/jgthms/bulma/blob/master/docs/documentation/overview/start.html](https://github.com/jgthms/bulma/blob/master/docs/documentation/overview/start.html)

href="{{ site.url }} is used to retrive sites url.
The docs is on sub-domain, and therefore {{ site.url }} returns the sub-domain.
We expact to get to the primary site.

**Comment by phoenix344** [comment]
I just found this framework and wanted to test it. From my point of view the complete website is broken. Not a good first impression.
