### ISSUE TITLE
Fix example about Twitter

### ISSUE THREAD

**Issue by MokkeMeguru** [jgthms/bulma#2862]
This is about **the Docs**.

### Overview of the problem

The Twitter brand guideline says We cannot use the "Twitter icon" with "Twitter Text".

https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf

But you show an example of it.
https://bulma.io/documentation/elements/button/

This example leads us to do violating usage.
Can you fix it?

**Comment by fmmricardo** [comment]
Hi @MokkeMeguru , what would be the best solution here, keep the twitter icon or the text?

**Comment by MokkeMeguru** [comment]
I think, we should update,

```
  <button class="button is-primary">
    <span class="icon">
      <i class="fab fa-twitter"></i>
    </span>
    <span>Twitter</span>
  </button>
```
to 

```
  <button class="button is-primary">
    <span class="icon">
      <i class="fab fa-twitter"></i>
    </span>
    <span>@Bluma</span>
  </button>
```

This will not violate the Twitter's terms !

**Comment by fmmricardo** [comment]
PR - [#2874]( https://github.com/jgthms/bulma/pull/2874)

**Comment by MokkeMeguru** [comment]
Thanks for your works!
