### ISSUE TITLE
Columns do not properly adjust when using the "box" CSS class

### ISSUE THREAD

**Issue by thehydrogen** [jgthms/bulma#2865]
This is about **Bulma**.

This is a: Bug
Browser issue?: Not certain

### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.0
My **browser** is: Chrome 80.0.3987.122 (Official Build) (64-bit)

### Description
When using the `box` CSS class in a column grid, the grid breaks and fails to properly & equally adjust. I am not certain whether this only happens when images are included, because that seems to be the only time I see this, but every time I've tried this I've had images in and haven't tested it yet.

*What I'm talking about:*
```
<div class="columns">
    <div class="column box">
        content
        <img src="/test.png" alt="images might be the cause">
    </div>
    <div class="column box">
        content 2
        <img src="/test2.png" alt="images might be the cause 2">
    </div>
</div>
```

### Steps to Reproduce

```
<div class="columns">
    <div class="column box">
        content
        <img src="/test.png" alt="images might be the cause">
    </div>
    <div class="column box">
        content 2
        <img src="/test2.png" alt="images might be the cause 2">
    </div>
</div>
```

### Expected behavior

Columns to scale and adjust properly.

### Actual behavior

Weird overlapping behavior

**Comment by zack256** [comment]
In the code provided the second box sticks out a little. I made them line up by removing the css property `.box:not(:last-child) {
    margin-bottom: 1.5rem;
}`. Does that help?

**Comment by thehydrogen** [comment]
I’ll check it out
