### ISSUE TITLE
Feature: has-image-centered

### ISSUE THREAD

**Issue by feralheart** [jgthms/bulma#2868]
This is about **Bulma** | the Docs.
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8
My **browser** is: Firefox/Chromium

### Description

It would be good if we would have an option to center an image natively.

**Comment by jgthms** [comment]
Since an image is an `inline-block` you can use `has-text-centered` on the parent.

**Comment by feralheart** [comment]
Thank you for your answer
