### ISSUE TITLE
Form seems odd 

### ISSUE THREAD

**Issue by rafael-oliveira-silva** [jgthms/bulma#2869]
This is about **Bulma**.

 Bulma
I need help with the layout

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

The form does not align correctly, the appearance is strange.

### Steps to Reproduce

<form action="" method="post">
        <label for="title" class="label">Title</label>

        <div class="control">
            <input type="text" class="input" name="title" id="title">
        </div>

        <div class="field">
            <label for="excerpt" class="label">Excerpt</label>

            <div class="control">
                <textarea name="excerpt" id="excerpt" class="textarea"></textarea>
            </div>
        </div>

        <div class="field">
            <label for="excerpt" class="label">Body</label>

            <div class="control">
                <textarea name="excerpt" id="excerpt"class="textarea"></textarea>
            </div>
        </div>

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-link is-dark" type="submit">Submit</button>
            </div>
        </div>
    </form>

### Expected behavior

I thought everything would fit properly.

### Actual behavior

Form looks all messed up with formatting.

![Screen Shot 2020-03-11 at 15 50 34](https://user-images.githubusercontent.com/62062373/76452851-8a113980-63b0-11ea-89e8-443d5134453e.png)

**Comment by feralheart** [comment]
Are you tried placing the form in a `container` div?
