### ISSUE TITLE
JS Function missing on document pages

### ISSUE THREAD

**Issue by petrk94** [jgthms/bulma#2870]
Hello,
I just want to ask, whether the issue is aware, that the documentation pages which provide function where JS is required, are not showing the JS code, like this here, the tabs cant be switched.
https://bulma.io/documentation/components/tabs/

**Comment by jgthms** [comment]
Yes it’s normal. Bulma provides the UI classes. It’s up to you to decide on the implementation.

For the tabs you don’t necessarily need JS actually. If you use templates, the server can use different templates per page. You only need to move around the “is-active” class between templates. No Js required.

**Comment by petrk94** [comment]
No, I dont think this is normal, even Bootstrap is providing JS for the functions, thats the problem why I struggle sometimes about the usage, because the lack of such few functions, I have to combine different frameworks to get my projects work.
https://getbootstrap.com/docs/4.4/getting-started/introduction/

Thats why I want to make a discussion about adding the functions to the documentation to reduce problems.
