### ISSUE TITLE
bulma space does not work anymore on text-area after using jquery keyup event

### ISSUE THREAD

**Issue by neuronflow** [jgthms/bulma#2872]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

https://stackoverflow.com/q/60677191/3485363

### Steps to Reproduce
see SO

### Expected behavior
spaces while typing

### Actual behavior
no spaces when typing

**Comment by jgthms** [comment]
Works https://codepen.io/jgthms/pen/zYGWgpG
