### ISSUE TITLE
Form labels do not respect `hero` styling

### ISSUE THREAD

**Issue by csicar** [jgthms/bulma#2881]
This is a **Bug** in  **Bulma**. 

If it's a bug, is it a browser bug? No

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0] 
My **browser** is: Firefox 74.0 
I am sure this issue is **not a duplicate**? Could not find similar issue

### Description

Form styling does not respect `.hero.is-primary` classes correctly.

The bug occurs because the css selector for `.label` is takes precedence over the inherited color from `.hero.is-primary`
![1584957453_grim](https://user-images.githubusercontent.com/725406/77304752-2f070d00-6cf5-11ea-94fe-7c568977c7da.png)

### Steps to Reproduce

https://codepen.io/csicar/pen/vYOzVOK?editors=1000

### Expected behavior

Label "Name" is colored white 

### Actual behavior

Label "Name" is colored black

**Comment by butaca** [comment]
I'm having the same issue with <a> elements inside the hero. Only reproducible in Firefox. Is there a workaround?

Bulma: 0.8.2
Firefox: 75
