### ISSUE TITLE
value of input does not show in 0.8.1

### ISSUE THREAD

**Issue by kinglyl** [jgthms/bulma#2885]
This is about **Bulma**.

need help
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **0.8.1** 
My **browser** is: Firefox and Chrome

### Description

I use bulma as a index page of my site https://52proxy.xyz
And I found the `value` and `placeholder` have the same color with the background color of input ???  (I always use the latest version of bulma and I found the problem in today)
I am not a professional fontend programmer so I don't konw how to test it
my code is like this
```html
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@latest/css/bulma.min.css">
  <script defer src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/js/all.min.js"></script>
</head>
```

```html
    <div class="container has-text-centered">

    <div id="frm">

      <!-- I wouldn't touch this part -->
      <form action="index.php" method="post" style="margin-bottom:0;">
        <div class="control has-icons-left" id="form">
          <input class="input is-info is-rounded" name="url" type="text" value="https://scholar.google.com.hk/" placeholder="http(s)://" autofocus>
		  <span class="icon is-small is-left">
			<i class="fab fa-edge"></i>
		  </span>
        </div>
        <button class="button is-fullwidth is-rounded is-link" type="submit">
		<span class="icon">
			<i class="fab fa-searchengin"></i>
		</span>
		<span>
			开启隐私之旅
		</span>
		</button>
      </form>
    </div>
    </div>

```

**Comment by jgthms** [comment]
Indeed, that is a bug. This is the commit that changed that value: https://github.com/jgthms/bulma/commit/5ba407bf91107fb6284327d23253065caccd9604#diff-42c86d867d812e65b671ffb6320c7226

I'm not sure what happened. I'll release a fix asap.

**Comment by robbertkl** [comment]
I'm also hitting this bug, after updating to the latest version. Is there any chance the 1.8.2 could be pushed out with just this fix? Thanks @jgthms !
