### ISSUE TITLE
navbar burger does not work without javascript

### ISSUE THREAD

**Issue by 0xAcid** [jgthms/bulma#2890]
This is about Bulma

### Overview of the problem
This is about the Bulma CSS framework

I'm using Bulma 0.8.1

Is Bulma really a javascript-less framework ?

### Description

I am quite new to the world of web developpement and wanted to use a really simple CSS framework, with not dependency to javascript etc;
I was trying out the basic sample of navbar : https://bulma.io/documentation/components/navbar/
Looks really great, however, when i resize it, in order to get that "navbar-burger", i am not able to toggle it without javascript enabled. 

It seems that there is a dependecy on the following files : 

```
<script src="https://bulma.io/vendor/clipboard-1.7.1.min.js"></script>
<script src="https://bulma.io/vendor/js.cookie-2.1.4.min.js"></script>
<script src="https://bulma.io/lib/main.js?v=202003261744"></script>
```

It is not possible to use the navbar on small screens.

### Steps to Reproduce

Use the "get started quickly" snippet from the navbar doc : https://bulma.io/documentation/components/navbar/

* Load the page
* Resize it to a mobile device size
* Try to click on the navbar burger

### Expected behavior

navbar menu should unroll

### Actual behavior

Nothing is happening

**Comment by 0xAcid** [comment]
My bad, should have scrolled a bit more the doc.

**Comment by etsea117** [comment]
@0xAcid what was the answer? I can't find it in the doc

**Comment by 0xAcid** [comment]
It's been a while, but if I remember correclty, you need that tiny bit of javascript, that you can find in the doc (https://bulma.io/documentation/components/navbar/) at `Javascript toggle`.
Cheers
