### ISSUE TITLE
Placeholder has the same color as the input

### ISSUE THREAD

**Issue by aocneanu** [jgthms/bulma#2891]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.1]
My **browser** is: Chrome

I am sure this issue is **not a duplicate**?

### Description

The placeholder has the exact same color as the input. I'm noob with sass but by debugging a bit it seems that the `rgba($color, $alpha) (`bulmaRgba`) is not applied anymore because `$input-color` is not a `color` anymore.

I guess [this](https://github.com/jgthms/bulma/commit/5ba407bf91107fb6284327d23253065caccd9604#diff-42c86d867d812e65b671ffb6320c7226R1) is the culprit

### Steps to Reproduce

Visit Bulma homepage, the [forms section](https://bulma.io/documentation/form/input/)

Look at any input example.

![image](https://user-images.githubusercontent.com/16073274/77826054-cfa26600-7115-11ea-90f0-0d302964751e.png)

### Expected behavior

Placeholder to be greyed out

### Actual behavior

Placeholder is not greyed out

**Comment by mskian** [comment]
yes I too face this issue

**Comment by nickcn** [comment]
This seems to be the case only in Chrome browser. Firefox works fine I believe.

**Comment by matt-allan** [comment]
FWIW I encountered this with Safari on MacOS too.

**Comment by jordelver** [comment]
I've seen this today with Chrome (80.0.3987.149) on macOS.
