### ISSUE TITLE
is-fullhd and is-widescreen does not work

### ISSUE THREAD

**Issue by mezeipetister** [jgthms/bulma#2893]
Question:

I am using Bulma as the latest NPM package and when I use **is-fluid** it works on a container, but when I use **is-fullhd** or **is-widescreen** it does not work. It's like having the same container with without any modification.

Could you help me with this?

Thank you in advance,
Best wishes,
Peter Mezei.

**Comment by mezeipetister** [comment]
anybody? Please!

**Comment by gogojosh** [comment]
I'm also experiencing similar issues using `is-widescreen*`, which don't appear to apply the necessary `.column` classes when in `widescreen` and greater breakpoints.

I'm not using `is-fluid`, but the correct classes are being applied when I switch to use the `is-desktop` helper class (i.e. `.column` only applied in `desktop` and greater breakpoints), so there appears to be a precedent of this working for other breakpoint helper classes.

**Comment by jaider** [comment]
I have similar issue... when I compare the generated code between `import bulma` vs my own scss (https://bulma.io/documentation/customize/with-node-sass/) and I discovered that `is-*-widescreen` class was missing.
![image](https://user-images.githubusercontent.com/1471688/86505827-4044c880-bd7e-11ea-9677-524c4462812d.png)

**Comment by jaider** [comment]
I have similar issues and I fixed it by removing this properties... these are in the sass sample page https://bulma.io/documentation/customize/with-node-sass/
```
$widescreen-enabled: false;
$fullhd-enabled: false;
```

**Comment by Pablo-Take** [comment]
Thanks to @jaider, added a variable to sass file 
`$fullhd-enabled: false
`
