### ISSUE TITLE
Incorrect $button-family variable description

### ISSUE THREAD

**Issue by mattdocumatt** [jgthms/bulma#2895]
This is about the Bulma **Docs**

### Overview of the problem

Button documentation (https://bulma.io/documentation/elements/button/) has incorrect type and default value for ``$button-family`` variable.

### Description

Docs says it's ``boolean`` with ``false``, but it's variable to change button font family and default value is ``$family-primary``.

**Comment by scheinercc** [comment]
according to the code base the documentation is correct:
https://github.com/jgthms/bulma/blob/f75ae3db01cb3be96dde517811f4950540f4c76f/sass/elements/button.sass#L3

https://github.com/jgthms/bulma/search?q=%24button-family&unscoped_q=%24button-family

**Comment by mattdocumatt** [comment]
Okay. So I don't understand what is the purpose of $button-family. All -family variables in Bulma, set font family.

What `$button-family: true` does? What `$button-family: false` does?

**Comment by scheinercc** [comment]
@ mattdocumatt you would not set it to `true`, but to a font family instead
```
@if $button-family
  font-family: $button-family
```
is not doing anything

but if you set e.g. `$button-family: Verdana;` in your config button text will be in Verdana from there on.
