### ISSUE TITLE
How to correctly apply border radius to a table?

### ISSUE THREAD

**Issue by neofight78** [jgthms/bulma#2898]
This is about **Bulma**.

### Overview of the problem

How do I apply a border radius to a table? Simply adding the css style doesn't seem to work with a header background or with the row highlighting (they get square corners)

#### Sass:

```
$table-head-background-color: $dark

table
  border-radius: 3px
```

#### HTML:

```
<table className="table is-striped is-hoverable is-fullwidth">
            <caption className="is-size-4 has-text-weight-bold">Table</caption>
            <thead>
            <tr>
                <th className="has-text-white">Col A</th>
                <th className="has-text-white">Col B</th>
                <th className="has-text-white">Col C</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Val A</td>
                <td>Val B</td>
                <td>Val C</td>
            </tr>
            </tbody>
</table>
```

### Expected behavior

A table with a border radius on each corner

### Actual behavior

Square corners on the header, and square borders at the bottom when hovering over the last row.

**Comment by pundoo** [comment]
Did you find any solution for this yet?

**Comment by lorenzochaudessolle** [comment]
I have a workaround solution,
you can add border-radius to the tag `table` if you put the `border-collapse: inherit;`
But you need to change `background-color` and others css rules if you want to have a beautiful render

**Comment by edub008** [comment]
Thanks @lorenzochaudessolle adding `border-collapse: inherit;` to my CSS table definition was all I needed to do and luckily my borders are looking nice with just that :)  Cheers

**Comment by jgthms** [comment]
This seems to be resolved. I will close it now. Thanks for those who helped.
