### ISSUE TITLE
The dropdown menu in the Navbar is getting overflow and last item is hidden from the Viewport

### ISSUE THREAD

**Issue by Aravin** [jgthms/bulma#2909]
This is about **Bulma**.

### Overview of the problem
The dropdown menu in the Navbar is getting overflow and last item is hidden from the view.

Bulma **CSS framework** 
Bulma **version** ^0.8.2
My **browser** is: Chrome

### Description

My project is Angular 8.
Using full bulma.min.css
The dropdown menu in the Navbar is getting overflow and last item is hidden from the view.

### Steps to Reproduce

```
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand" >
    <a class="navbar-item" href="/">
      <!-- <img src="" width="112" height="28"> -->
      <span style="font-weight: 900; font-size: x-large;">title</span>
    </a>

    <a role="button" class="navbar-burger burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navMenu" class="navbar-menu">
    <div class="navbar-end">

      <a class="navbar-item">
        Applications
      </a>

      <a class="navbar-item">
        Services
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            Terms & Conditions
          </a>
          <a class="navbar-item">
            Privacy Policy
          </a>
          <a class="navbar-item">
            About us
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>

    </div>
  </div>
</nav>

```

### Expected behavior

Content should not overflow. Navbar dropdown should be in viewport.

### Actual behavior

![image](https://user-images.githubusercontent.com/4869265/79200738-8875de00-7e54-11ea-95aa-376b05735fed.png)

**Comment by marcoczen** [comment]
Hi ...did u ever solve your problem ?

**Comment by Aravin** [comment]
> Hi ...did u ever solve your problem ?

NO @marcoczen 

I reduced the text size (refer https://epix.io) . It is a temp workaround. Have to find out solution.

**Comment by emschwartz** [comment]
I think adding `is-right` to the div with the class `navbar-dropdown` should solve this. 

I didn't see this on my first look through the docs either but take a look at the section called **Right Dropdown** here: https://bulma.io/documentation/components/navbar/#dropdown-menu
