### ISSUE TITLE
Docs: How do I configure the width at which menu items go away and the burger appears?

### ISSUE THREAD

**Issue by xenoterracide** [jgthms/bulma#2910]
How do I configure the width at which menu items go away and the burger appears? this currently seems to happen very wide, something like 90% of my screen width, and for 2 elements in the menu this seems crazy. The documentation doesn't mention how to customize this. Would be even better if this could detect when overflow was going to happen and only show the burger then (though I bet that takes js)

```
Calebs-MBP:warmeister calebcushing$ yarn list bulma
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ bulma@0.8.2
✨  Done in 0.99s.
```

**Comment by Wivita** [comment]
You can set the variable $navbar-breakpoint before importing Bulma. Use any pixel width or variable width you like. Like: `$navbar-breakpoint: $tablet;` or `$navbar-breakpoint: 640px;`

**Comment by lance-anderson** [comment]
> You can set the variable $navbar-breakpoint before importing Bulma. Use any pixel width or variable width you like. Like: `$navbar-breakpoint: $tablet;` or `$navbar-breakpoint: 640px;`

Thank you. In the case where the burger should always be present, is it best practice to set `$navbar-breakpoint` to something like `10000 px`?
