### ISSUE TITLE
Importing variables without importing the whole sass file

### ISSUE THREAD

**Issue by mebibou** [jgthms/bulma#2911]
This is about **Bulma**.

### Overview of the problem

This is a **Sass** issue: I'm using version [0.8.2]

### Description

I would like to be able to import the variables of a component without having to import the whole component itself. Actually, it would be nice to be able to import one single file containing all the variabbles. Use-case : if I want to use the `$navbar-height` in a component for example, I have to do
```sass
@import '~bulma/bulma.sass'
```
Which imports the whole file although I just wanted one variable.

**Comment by jgthms** [comment]
For now you can import only the navbar:

```sass
@import "~bulma/sass/components/navbar.sass"
```

But the new `@use` system will allow you to do exactly what you want.

**Comment by mebibou** [comment]
Is this going to be included in a near release?
