### ISSUE TITLE
Have a problem with flexbox height in all bulma versions

### ISSUE THREAD

**Issue by naymapl** [jgthms/bulma#2921]
Hi.
I use bulma columns with no gap (is-gapless is-marginless is-paddingless) to get full height and width content grid. But always I have a problem with small 6-7px margin on bottom part of line like here:
https://druzbice.com/
I can`t remove this white few pixels margin. Is that a bulma problem/issue or I make something wrong ?? I have this issue always. When I change display to flex for column is gone but is damage website view in Safari.

Thank you for any help.

**Comment by jgthms** [comment]
The issue is with the images. That's how they behave by default. A few options: add `img { vertical-align: top;}` or `img { display: block; }`.

![image](https://user-images.githubusercontent.com/1254808/79801471-1de20800-8356-11ea-80c1-9dfec3383f36.png)
