### ISSUE TITLE
pre doesn't respect the width of its parent

### ISSUE THREAD

**Issue by jamierocks** [jgthms/bulma#2924]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.8.2
My **browser** is: Firefox 75.0

### Description

I want to display some code on one of my pages, unfortunately one of the lines is rather long and is causing the parent `.content` to extend :(

### Steps to Reproduce

```html
    <div class="container">
        <div class="columns">
            <div class="column">            
                <div class="content">
                    <pre><code>Name    "FTB Academy"
OutFile "out\ftb-academy-1-2-0.exe"

InstallDir "$APPDATA\NeptuneFTB\ftb-academy\"
DirText    "This will install FTB Academy 1.2.0 on your computer. Choose a directory"

Section
    InitPluginsDir
    inetc::get "https://github.com/jamiemansfield/ftbinstall/releases/download/v0.1-alpha/ftbinstall.exe" "$PLUGINSDIR\ftbinstall.exe"

    SetOutPath $INSTDIR
    nsExec::ExecToLog '"$PLUGINSDIR\ftbinstall.exe" ftb-academy 1.2.0'
SectionEnd</code></pre>
                </div>
            </div>
        </div>
    </div>
```

For further context [this](https://ftb.neptunepowered.org/docs/installer/) is the page it would be displayed on - under the images. See https://gist.github.com/jamierocks/e2eb7330473b869ff93de70633f68b0a for a more complete source example.

### Expected behavior

The code block to stay within the boundaries of the parent `div` - such as the following **without** the code block.

![https://i.imgur.com/6FPkJXT.png](https://i.imgur.com/6FPkJXT.png)

### Actual behavior

![https://i.imgur.com/ZBnMpRK.png](https://i.imgur.com/ZBnMpRK.png)

**Comment by jgthms** [comment]
This happens when there is a long uninterrupted string, in this case `"https://github.com/jamiemansfield/ftbinstall/releases/download/v0.1-alpha/ftbinstall.exe" "$PLUGINSDIR\ftbinstall.exe"`.

It can be fixed with:

```css
.content pre {
  white-space: pre-wrap;
}
```

It's more of a choice than a bug, because when dealing with code, line-breaks are not neutral. That's why Bulma will only wrap if the code actually does. But it can have issues like here.

**Comment by jamierocks** [comment]
![image](https://user-images.githubusercontent.com/5103549/80124228-d9d64980-8587-11ea-8c91-c09885d760e9.png)

I'm happy with that - though it would be nice if Bulma defaulted to either wrap or scroll. Though I can definately understand hesitation to make either a default - in that case perhaps 2 new classes? (`.pre-wrap` and `.pre-scroll` perhaps?)

**Comment by jgthms** [comment]
Maybe `pre-wrap` sounds like a sensible default.

**Comment by jamierocks** [comment]
> 
> 
> Maybe `pre-wrap` sounds like a sensible default.

I've given this some thought, and given mobile will currently scroll - it would be preferable if that wasn't to change.

**Comment by joshtriplett** [comment]
While I'd love to see a solution to this problem, I would not want to see Bulma making `pre` tags wrap by default, as this can lose information. Scrolling is not ideal, but it has the advantage of not causing semantic problems within the represented code.

**Comment by ricardoboss** [comment]
I am not fine with the `pre-wrap` solution. Is there any other to fix this without having to wrap all my codeblocks in some wrapper?
