### ISSUE TITLE
add    <table > table-layout: fixed;

### ISSUE THREAD

**Issue by Valar103769** [jgthms/bulma#2929]
i feel that is better,
```css
.table{
table-layout: fixed;
}
```
 text-overflow:ellipsis

**Comment by jgthms** [comment]
It's not better because the content is more important than the layout. It's easy with a fixed layout table to render something like this:

![image](https://user-images.githubusercontent.com/1254808/80573128-538e8d00-89f7-11ea-84a0-204013feed62.png)
