### ISSUE TITLE
Notification close button issue

### ISSUE THREAD

**Issue by Fedez1879** [jgthms/bulma#2930]
This is about the Bulma Notification 
I'm using Bulma 0.8.0
My Browser is Chrome Version 81.0.4044.129

### Description

When I create multiple notification box, only one could be closed.

The others stay.

My solution:

https://bulma.io/documentation/elements/notification/

changed

```
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
```

with

```
document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    $delete.addEventListener('click', () => {
	  $delete.parentNode.remove();
    });
  });
});
```

**Comment by jgthms** [comment]
Thanks for sharing. It's a different behavior for sure. I believe some users don't want to delete all notifications at once. The snippet in the documentation is only given as an example.

**Comment by Fedez1879** [comment]
Thank you for the answer Jeremy.

Sorry for my english, I probably explained badly my issue:

I didn't inted to close all the notification at once.

The problem occurs when I've two or more notification:

Let's say:

```
<div class="notification is-info"><button type="button" class="delete"></button>first</div>
<div class="notification is-info"><button type="button" class="delete"></button>second</div>
<div class="notification is-info"><button type="button" class="delete"></button>third</div>

```
I start closing them by clicking on the delete button.

regardless of which delete button I click, always the last one is closed 

when I try to close the others, they remain opened. Chrome console says:
```
102 Uncaught TypeError: Cannot read property 'removeChild' of null
    at HTMLButtonElement.<anonymous>

```
I've solved the issue with the above code change.

Hope you understand now.

Bye :)

**Comment by Fedez1879** [comment]
Thank you for the answer Jeremy.

Sorry for my english, I probably explained badly my issue:

I didn't intend to close all the notification at once.

The problem occurs when I've two or more notification:

Let's say:

```
<div class="notification is-info"><button type="button" class="delete"></button>first</div>
<div class="notification is-info"><button type="button" class="delete"></button>second</div>
<div class="notification is-info"><button type="button" class="delete"></button>third</div>
```

I start closing them by clicking on the delete button.

regardless of which delete button I click, always the last one is closed

when I try to close the others, they remain opened. Chrome console says:

```
102 Uncaught TypeError: Cannot read property 'removeChild' of null
    at HTMLButtonElement.<anonymous>
```

I've solved the issue with the above code change.

Hope you understand now.

Bye :)

**Comment by distal-shores** [comment]
@Fedez1879 thanks for this, I had the same issue and this fixed it.
