### ISSUE TITLE
Sticky table header

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [jgthms/bulma#2931]
Question about Bulma

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.1

### Question

I am using bulma fixed navbar and I would like to make the table head in a table stick to the bottom of the navbar while looking at the table. It's a log table(height and width) so have the table headers stick to the top is crucial for be able to easily read the table. I started looking at [css-tricks](https://css-tricks.com/position-sticky-and-table-headers/) for how to do this but it doesn't seem to work with bulma.

**Comment by ulf1** [comment]
The sticky CSS hack are not working

**Comment by dangowans** [comment]
I've been experimenting with sticky table headers and first columns in Bulma using that exact CSS Tricks page.

https://cityssm.github.io/bulma-sticky-table/

Hope this helps.
