### ISSUE TITLE
Changing background color / text color of navbar-dropdown

### ISSUE THREAD

**Issue by marcoczen** [jgthms/bulma#2933]
### Overview of the problem

 I'm using Bulma **version** [0.8.2] 

### Description

I have a navbar with color is-black.
I want to change the navbar-dropdown colour to black 
with white text.

Is there a css class or setting that we can use to overide the navbar-dropdown background  ( its currently white with grey text. The hover as we move over the dropdown is almost non existent so i would like to change that too.

**Comment by jgthms** [comment]
Yes there are lots of Sass variables you can change: https://github.com/jgthms/bulma/blob/master/sass/components/dropdown.sass#L3

**Comment by marcoczen** [comment]
Hi ..I am still a novice to sass / nodejs etc and i dont think i can do that. Also i dont want to change the defaults - i only want the colors changed for a particular set of pages.

Isnt there a way where i can just apply a style like;

.bgcolor        { background-color:black;   }

```
<div class="navbar-dropdown   bgcolor"> 
      <a class="navbar-item has-text-black" href="user.php">Link 1</a>                                                   
      <a class="navbar-item has-text-black" href="mgmt.php">Link 2</a>            
</div>
```

**Comment by marcoczen** [comment]
Anybody ? I dont want to change defaults when its only some pages involved ? Cant we use css overrides ?

**Comment by marcoczen** [comment]
Update - I just switched to BootStrap. You can just css to override defaults for a particular page.
Thanks.

**Comment by MindMansion** [comment]
```
.bg-is-inherited
     background-color: inherit!important
     ....
```

```
    <div class="navbar-dropdown   bgcolor"> 
      <a class="navbar-item bg-is-inherited has-text-black" href="user.php">Link 1</a>                                                   
      <a class="navbar-item bg-is-inherited has-text-black" href="mgmt.php">Link 2</a>            
    </div>
```
