### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by locness3** [jgthms/bulma#2935]
This is about **Bulma**.
This is an feature request.

### Description

Would be great, if someone's available to, to create a composer package for use in PHP apps.

**Comment by Ben52** [comment]
Composer is a package manager for php packages. You can include Bulma in your php application by using npm, which is for css/js packages. 
If you have a specific question how to set it up in your project, provide some details on your application's setup, and I'm sure someone will be able to help!

**Comment by locness3** [comment]
I'd like to not combine npm and Composer, and that's why i ask for a Composer package (but I know I can use the two)

**Comment by PF94** [comment]
> by using npm, which is for css/js packages.

last time i checked, it is a package manager for node, which is javascript-based.
