### ISSUE TITLE
Please consider having all the docs on a single page

### ISSUE THREAD

**Issue by yousefamar** [jgthms/bulma#2936]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

I have searched for a duplicate issue and not found any.

### Description

Can you _please_ consider having all the docs on a single page like every other CSS framework? I can't express how much of a nightmare it is to browse those docs. It's incredibly difficult to find what I need, and even when I know where it is, I still have to click through several things to get there. If it was all on a single page, I could ctrl-f to anything I needed instantly.

This would also be really beneficial for onboarding new developers, as they would be able to scroll through and see everything that bulma has to offer. I didn't know certain things were possible, until I stumbled upon them by chance in the docs while looking for something else. This is made worse by the fact that the sections/subsections are organised in a way that isn't very intuitive to me. I would much rather be able to just search something like "center" and see if there are classes related to centering, etc.

**Comment by guanzo** [comment]
More generally, the docs should be easier to browse, right now there's too much nesting.

What about a "search anything" input at the top, like a lot of doc sites have? For example the vue docs https://vuejs.org/v2/guide/

**Comment by service-paradis** [comment]
Searching Bulma is a feature request since 2017 as you can see in #1325

**Comment by guanzo** [comment]
Thanks, read through the issue. This is not a good look, Bulma needs to step up their game. Documentation search isn't some trivial feature request.
