### ISSUE TITLE
panel without panel-tabs caused a gap behind the panel-header

### ISSUE THREAD

**Issue by EdJoPaTo** [jgthms/bulma#294]
### Checklist
- [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
- [x] I'm using Bulma **version** [0.1.2]
- [x] My **browser** is: Chromium, Firefox
- [x] I'm using the precompiled css from the cdn
- [x] I am sure this issue is **not a duplicate**?
### Description

I know that jgthms said in #183, the panel is still a bit messy, but i want to report this anyways:

![screenshot from 2016-09-03 16-38-19](https://cloud.githubusercontent.com/assets/7953011/18225552/dce1c398-71f4-11e6-8242-484f5a999899.png)

When i remove the `.panel-tabs` (don't need them) there is a gap between the `.panel-heading` and the first `.panel-block`.
This is caused by `.content p:not(:last-child) { margin-bottom: 1em; }` applied to the `.panel-heading`.

A workaround for this for everyone with the same problem: (until there is a bulma side fix, always better than a workaround)

``` css
p.panel-heading {
  margin-bottom: 0;
}
```
### Steps to Reproduce
1. copy the panel from the documentation
2. remove the panel-tabs

_Expected behavior:_ neatless elements

_Actual behavior:_ a gap between the `.panel-heading` and the first `.panel-block`.

**Comment by AlgusDark** [comment]
@jgthms I believe this one is not an issue anymore in the last release (0.4.2) of bulma.

![image](https://user-images.githubusercontent.com/818856/26889479-f24db300-4b73-11e7-8d4e-f56da55ddbf4.png)
