### ISSUE TITLE
On macOS w/ Chrome or Safari, select menus are shifted to the left

### ISSUE THREAD

**Issue by hchauvat** [jgthms/bulma#2944]
This is about **Bulma**.
I feel like it's a bug related to macOS but not browser-specific (seen on Safari, Chrome but NOT on Firefox)

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0]
My **browser** is: Chrome (81.0.4044.138) and Safari (13.1 (15609.1.20.111.8))

I am sure this issue is **not a duplicate**? I searched for 'select' and 'dropdown' but couldn't find anything related.

### Description

On macOS, Safari or Chrome, the content of a dropdown menu is shifted to the left.

### Steps to Reproduce

1. Go to https://bulma.io/documentation/form/select/ on a Mac running Safari or Chrome
2. Click on the first dropdown

### Expected behavior

The options list should be perfectly aligned on top of the dropdown element.

**On Firefox**
<img width="216" alt="Firefox" src="https://user-images.githubusercontent.com/59441901/81818085-dbaf7f00-952d-11ea-91ca-aa16fc49b19b.png">

### Actual behavior

The options list is shifted to the left.

**On Safari**
<img width="217" alt="Safari" src="https://user-images.githubusercontent.com/59441901/81818112-e36f2380-952d-11ea-970d-c8f08586282b.png">
**On Chrome:**
<img width="211" alt="Chrome" src="https://user-images.githubusercontent.com/59441901/81818117-e538e700-952d-11ea-9dcf-318fbc8bdc1b.png">

**Comment by thomasedwards** [comment]
Weirdly it might be the other way around. Firefox uses a custom UI that just smells a bit like macOS, whereas Chrome and Safari use macOS’s standard UI.
