### ISSUE TITLE
why does some source code not conform to sass recommendation

### ISSUE THREAD

**Issue by anlexN** [jgthms/bulma#2946]
This is about **Bulma | the Docs**. Bulma
![image](https://user-images.githubusercontent.com/8686739/81897138-9b610700-95e8-11ea-952e-6dcce0f63d40.png)

[Indented Mixin Syntax](https://sass-lang.com/documentation/at-rules/mixin#indented-mixin-syntax)

**Comment by jgthms** [comment]
That’s because the whole source code is using the indented syntax. 

Also, it’s only an issue if you are writing the source code, not if you use Bulma. You can still use SCSS and use a Bulma mixin the SCSS way.
