### ISSUE TITLE
move away from jQuery?

### ISSUE THREAD

**Issue by trymeouteh** [jgthms/bulma#2949]
Will Bulma move away from jQuery? I know it is useful but I think it is better if Bulma had no dependencies and JavaScript has come a long ways, making it so jQuery is not needed for developing JS quickly.

Or even to have Bulma not require jQuery and have a optional jQuery integration JS script to allow people to use jQuery with Bulma if they wish.

**Comment by jgthms** [comment]
Why do you think Bulma requires jQuery?
