### ISSUE TITLE
Invalid HTML examples in the docs

### ISSUE THREAD

**Issue by mayrsascha** [jgthms/bulma#2951]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

Several examples in the Docs are not valid HTML.

I decided to open this issue which includes multiple closely related issues in order to reduce the bureaucratic overhead.

### Description

I had several issues with the W3C Validator when copy/pasting HTML from the Bulma docs. The service marked some parts of my HTML as an error or warning so I decided to go through all the docs and filter out those examples which produce invalid HTML:

- [Starter template](https://bulma.io/documentation/overview/start/#starter-template)
- [Disabled link examples](https://bulma.io/documentation/modifiers/syntax/)
- [Every example of media objects](https://bulma.io/documentation/layout/media-object/)
- [Fullheight Hero with Navbar](https://bulma.io/documentation/layout/hero/)
- [Fullheight Hero in 3 parts](https://bulma.io/documentation/layout/hero/#fullheight-hero-in-3-parts)
- [Tiles example](https://bulma.io/documentation/layout/tiles/#example)
- [Tiles - Nesting requirements](https://bulma.io/documentation/layout/tiles/#nesting-requirements)
- [Tiles - 3 columns](https://bulma.io/documentation/layout/tiles/#3-columns)
- [Tiles - 4 columns](https://bulma.io/documentation/layout/tiles/#4-columns)
- [Disabled checkbox](https://bulma.io/documentation/form/checkbox/)
- [Disabled Radio button](https://bulma.io/documentation/form/radio/)
- [Box](https://bulma.io/documentation/elements/box/)
- [Delete combinations](https://bulma.io/documentation/elements/delete/#combinations)
- [Every example of Image](https://bulma.io/documentation/elements/image/)
- [The first table example](https://bulma.io/documentation/elements/table/)
- [The first 2 examples of Card](https://bulma.io/documentation/components/card/)
- [Every example of Message](https://bulma.io/documentation/components/message/)
- [Card Modal](https://bulma.io/documentation/components/modal/)
- [Basic Navbar](https://bulma.io/documentation/components/navbar/#basic-navbar)
- [Navbar Brand](https://bulma.io/documentation/components/navbar/#navbar-brand)
- [Navbar Menu first example](https://bulma.io/documentation/components/navbar/#navbar-menu)
- [Transparent Navbar](https://bulma.io/documentation/components/navbar/#transparent-navbar)
- [Dropdown Menu](https://bulma.io/documentation/components/navbar/#dropdown-menu)
- [Every example of Pagination](https://bulma.io/documentation/components/pagination/)
- [Panel Colors](https://bulma.io/documentation/components/panel/#colors)

### Steps to Reproduce

1. Go to the [W3C Validator](https://validator.w3.org/#validate_by_input) website
2. Paste in this HMTL skeleton
```
<!DOCTYPE html>
<html lang="en">
<head>
<title>Bulma</title>
</head>
<body>
{example}
</body>
</html>
```
3. Replace {example} which each example mentioned above.

### Expected behavior

The [W3C Validator](https://validator.w3.org/#validate_by_input) should not show errors or warnings for each of the examples mentioned above.

### Actual behavior

The [W3C Validator](https://validator.w3.org/#validate_by_input) shows errors and/or warnings for each of the examples mentioned above.

**Comment by mayrsascha** [comment]
IMHO if the Bulma team wants this framework to be relevant it should also put a focus on producing high-quality documentation especially considering that a LOT of devs are simply copy/pasting from the easily copyable examples.

**Comment by barraclm** [comment]
I have just had the W3 validator fail my code because I have <media> tags without an <h > tag
