### ISSUE TITLE
Full Height Column

### ISSUE THREAD

**Issue by ahmed-alamer** [jgthms/bulma#2959]
How do I make a column full width? I am working with a `menu` but I noticed that it doesn't support sizes per the docs.

How do I make a column that contains the menu full height?

**Comment by RasdanJames** [comment]
I just did this. You can do it by setting:

`min-height: 101vh !important`

Within whatever class (or direct style) you want to use. If you do 100vh, it doesn't quite go all the way down. You'll also need to put that into every column as part of the same thing. Once I did that, it works nicely.

**Comment by ahmed-alamer** [comment]
That worked! Thanks.
