### ISSUE TITLE
Overriding navbar values doesn't work

### ISSUE THREAD

**Issue by Norgul** [jgthms/bulma#2961]
This is about **Bulma**.
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.2]
My **browser** is: Chrome 
I am sure this issue is **not a duplicate**

### Description

I wanted to use navbar item dropdown with hoverable property. I am using a hero layout 

```
<section class="hero is-info is-fullheight is-bold">
```

The navbar dropdown is done like this:

```
<div class="hero-head">
        <nav class="navbar is-info">
                <div class="navbar-brand">
                          .......
                </div>
                <div id="navbarMenuHeroB" class="navbar-menu is-info">
                    <div class="navbar-end">
                      
                        <div class="navbar-item has-dropdown is-hoverable">
                             <a class="navbar-link">
                                <font-awesome-icon :icon="languageIcon"/>
                            </a>

                            <div class="navbar-dropdown is-right">
                                <a class="navbar-item is-active">
                                    EN
                                </a>
                                <a class="navbar-item">
                                    FR
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
        </nav>
    </div>
```

With the defaults, the dropdown just has wrong colors on hover:

![image](https://user-images.githubusercontent.com/11718157/82360531-d52b7680-9a09-11ea-80d5-b20ba52f3fc5.png)

If I omit the is-active, the first item is not showing until hover, same as second item. 

I tried overriding values by importing this before loading bulma sass

```
@import "~bulma/sass/utilities/initial-variables";
@import "~bulma/sass/utilities/functions";
@import "~bulma/sass/utilities/derived-variables";

$footer-padding: 1.5rem 1.5rem 1.5rem;

$navbar-dropdown-background-color: $info;

$navbar-dropdown-item-hover-color: $info-invert;
$navbar-dropdown-item-hover-background-color: $info-invert;
$navbar-dropdown-item-active-color: $info-invert;
$navbar-dropdown-item-active-background-color: $info;
```

The `navbar-dropdown-background-color` is the only one which does something to the view, all other variables do nothing whatever I try. What seems to be the issue, am I doing something wrong?

**Comment by hammypants** [comment]
You're not doing anything wrong. None of the default values for _any_ of the `navbar` are initialized by default in those first three imports. [Check it.](https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass) All loaded when you import `navbar`.

+1ing this issue, the documentation is just straight up wrong.

**Comment by Norgul** [comment]
So how could I override them? I'm not much of a front end guy so please if you have any hints I'd appreciate it. Thanks

**Comment by hammypants** [comment]
> So how could I override them? Does it need to go after I load complete Bulma dependencies? I'm not much of a front end guy so please if you have any hints I'd appreciate it. Thanks

You can modify it after, but not in the way it is documented. You would have to apply changes in a more traditional modification of CSS/SCSS, with class/id/element selectors for the items you want to change.

Arbitrary example; assuming you're unaware:
```scss
// selecting a class-- "all elements of class navbar-dropdown"
.navbar-dropdown {
// change properties of all navbar-dropdown
    &:hover {
    // change things for navbar-dropdowns when hovering
    }
}
```
