### ISSUE TITLE
Nested dropdowns always shown

### ISSUE THREAD

**Issue by sebastian-bartkowiak** [jgthms/bulma#2963]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.2]

I am sure this issue is **not a duplicate**

### Description

This is bug/unexpected behaviour/feature. With current Bulma (0.8.2) it is not possible to create nested dropdown components due to the way Bulma decides when to show/hide dropdown content. Compiled selector is `.dropdown.is-active .dropdown-menu, .dropdown.is-hoverable:hover .dropdown-menu`, which means that a `.dropdown-menu` that has a parent `.dropdown.is-active` (or hover, I'm using `is-active` version, so I will stick with that in description for clarity) immediately gets shown, even if it is not its designated `.dropdown` element. I belive that a proper selector for determining whether dropdown is displayed or not should be `.dropdown.is-active > .dropdown-menu` (notice the direct child selector change). This simple fix allows to nest dropdowns without any issues, and (as far as I can see) does not break any current behaviour.

### Steps to Reproduce

I created a [demo](https://codepen.io/sebastian-bartkowiak/pen/BaoMjWj) showing current behaviour - please notice how nested dropdown does not have `.is-active` class.

### Expected behavior

Nested dropdown hidden.

### Actual behavior

Nested dropdown shown.

**Comment by Tofandel** [comment]
Great bug report, what a weird use case though, curious on that

**Comment by sebastian-bartkowiak** [comment]
Hi, thanks for the feedback. To be honest - I do not really use on my site the way I showed in demo, however I built an autocomplete input using dropdown, and discovered this bug when embeding my autocomplete component into actual dropdown :)
