### ISSUE TITLE
Sass formatter

### ISSUE THREAD

**Issue by webspilka** [jgthms/bulma#2965]
This is question about **sass formatter and Bulma mixins.sass**.

### Overview of the problem
This is a **Sass** question: I'm using version [0.8.2]

### Description

I use  https://github.com/TheRealSyler/sass-formatter/. But after last update to 0.4.5 it remove indent after +desktop.
https://github.com/TheRealSyler/sass-formatter/issues/18
https://github.com/TheRealSyler/sass-formatter/issues/16

What do you think about this issues?
What sass formatters do you use?

In vs Code I use https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented,is there anything like this plugin? Please, share your experience of how you format sass when writing code

**Comment by jgthms** [comment]
I don't use a Sass formatter. It seems the issue you're describing is with the formatter itself, as explained in the issues you've linked to. It seems the formatter doesn't consider the possibility of having `@content` in the mixin, in which case the indentation should be there.

There's nothing I can do on Bulma's side.
