### ISSUE TITLE
no style for <ol> or <li> (remove bullet/numbers)

### ISSUE THREAD

**Issue by emretufekci** [jgthms/bulma#2967]
On the docs, it's nothing to tell about no style, i checked previous issues but they're not working as well.
https://bulma.io/documentation/elements/content/

**Comment by RasdanJames** [comment]
I've found that if I don't wrap the lists in a `<div class="content">` then they don't work correctly. But when I do, then the lists work correctly. So you should be able to do:
```html
<div class="content">
    <ul>
        <li>Test</li>
    </ul>
</div>
```
And then have it display correctly.

**Comment by emretufekci** [comment]
Your answer is for unordered list, i'm asked for ordered list and this is not the case also, we sould have something from css classes like "is-nostlye"

**Comment by RasdanJames** [comment]
It works the same with ol:
```
<div class="content">
    <ol>
        <li>1</li>
        <li>2</li>
    </ol>
</div>
```
renders as:
![image](https://user-images.githubusercontent.com/65590179/82699364-5f99f300-9c21-11ea-8fc2-43758fc0134b.png)

**Comment by emretufekci** [comment]
@RasdanJames in renders it shows as
1. 1
2. 1

I'm asking to remove bullets & numbers thanks but this is not an answer for my question.

**Comment by RasdanJames** [comment]
Oh! Thanks for clarifying. I think you can just do that with:
```html
<div style="list-style: none">
    <ol>
         <li>1</li>
    </ol>
</div>
```
This is the same thing Bulma does with `<ul>`.

You can add a class to encapsulate that (it's what I did).

**Comment by emretufekci** [comment]
Yes this is working but i'm using as well but anyway, bulma should have official support for no style,

we should define like this:

`  <ol class="is-no-bullet">
`  
`<ol class="is-no-number">
`

So, this issue is feature request actually. Not a bug.
