### ISSUE TITLE
$family-sans-serif doesn't work

### ISSUE THREAD

**Issue by angelsix** [jgthms/bulma#2969]
This is about **Bulma**.

`$family-sans-serif` (or any overriding of font's) doesn't work.

### Description

Overriding font family doesn't work as homepage or documentation states.

### Steps to Reproduce

`npx create-nuxt-app test` then use Yarn and Buefy.
Create a .scss file and edit settings:

```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors
$primary: #74ba53;
$primary-invert: findColorInvert($primary);

// Setup $colors to use as bulma classes (e.g. 'is-twitter')
$colors: ("white": ($white, $black),
  "black": ($black, $white),
  "light": ($light, $light-invert),
  "dark": ($dark, $dark-invert),
  "primary": ($primary, $primary-invert),
  "info": ($info, $info-invert),
  "success": ($success, $success-invert),
  "warning": ($warning, $warning-invert),
  "danger": ($danger, $danger-invert),
);

// Links
$link: $primary;
$link-invert: $primary-invert;
$link-focus-border: $primary;

@import url('https://fonts.googleapis.com/css?family=Poppins');

$family-sans-serif: "Poppins",
sans-serif;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

### Expected behavior

Font should be Poppins

### Actual behavior

Font doesn't change.

Changing $family-sans-serif to $body-font works.

**Comment by getup8** [comment]
I think you're importing the variables and then setting them perhaps via your: `@import "~bulma/sass/utilities/_all";` at the top?

From the Bulma docs:

*To override any of these variables, just set them before importing Bulma.*

**Comment by Tofandel** [comment]
Nope, the override is correct, even if the variable was imported before it would still be overridden before bulma's import
Since you're using nuxt, It might be a nuxt issue

**Comment by daniellenzofficial** [comment]
imho getup8 is right, you are importing bulma utils at the top. And you import all bulma styles at the bottom. You have to import bulma styles at bottom.

**Comment by Gameghostify** [comment]
This happens for me as well. Other overrides work perfectly fine.
