### ISSUE TITLE
Make left column appear under a right column on tablet/mobile devices

### ISSUE THREAD

**Issue by josefzacek** [jgthms/bulma#297]
Make left column appear under a right column on tablet/mobile device

![bulma](https://cloud.githubusercontent.com/assets/2744855/18256691/ae91faae-73b0-11e6-9abd-1cc7b5dd380f.png)

Link below shows bootstrap example but I unfortunately could not implement anything like that with bulma

http://stackoverflow.com/questions/19569541/making-a-left-sidebar-appear-under-a-right-hand-column-on-a-mobile-with-bootstra

**Comment by dyusha** [comment]
Hey @josefzacek,

I guess `flex-direction: column-reverse` in a media query on a container should do this trick for you.

**Comment by josefzacek** [comment]
Hi @dyusha 

I was hoping there is a built-in class that could do it for me. Thank you for suggestion anyway

**Comment by LionelRieder** [comment]
I'm very curious why Bulma doesn't have a built-in class for that ? There is a specific reason behind that choice ?

**Comment by jgthms** [comment]
It's too opinionated. And it's a single line of CSS for those who need it.

**Comment by stoqe** [comment]
I'm new to Bulma and I'm loving it so far. However coming from Tachyons I'm certainly left wanting more; especially more built-in classes.

Providing an optional built-in class is not opinionated at all: not providing an optional built-in class is totally opinionated.

**Comment by jvarness** [comment]
After my bulma import in my sass, I was able to put this code into my codebase to force reversed column order when I needed it:

```sass
.columns.is-reversed-mobile
  +mobile
    display: flex
    flex-direction: column-reverse
```

**Comment by s-gbz** [comment]
Just in case someone has the same error as I had using scss `Invalid CSS after "*/": expected 1 selector or at-rule`.
Make sure to use curly braces:

```css
.columns.is-reversed-mobile
  +mobile {
    display: flex;
    flex-direction: column-reverse;
}
```
