### ISSUE TITLE
Responsive horizontal size modifiers for Tiles

### ISSUE THREAD

**Issue by justin13888** [jgthms/bulma#2972]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.8.0]
My **browser** is: Chrome

### Description

According to the [Tiles](https://bulma.io/documentation/layout/tiles/) doc, there doesn't seem to be any horizontal size modifiers that are responsive like what is available for [columns](https://bulma.io/documentation/columns/responsiveness/).

### Steps to Reproduce

```html
<div class="tile is-ancestor">
    <div class="tile is-parent is-9-desktop">
        <div class="tile is-child">
            <!-- content -->
        </div>
    </div>
    <div class="tile is-parent is-hidden-touch">
        <div class="tile is-child">
            <!-- content -->
        </div>
    </div>
</div>
```

### Expected behavior

The tile should take up three-quarters (9/12) of the viewport while in desktop.

### Actual behavior

There aren't such responsive helpers. I think there should be at least the modifiers that work on [columns](https://bulma.io/documentation/columns/responsiveness/) available for Tiles as well.

**Comment by Rio517** [comment]
This seems to be a recurring request to get this built into the framework- https://github.com/jgthms/bulma/issues/1757

@jgthms - would you consider revisiting?

**Comment by tyrantwren** [comment]
Is this problem solved? I still confuse about how to make a breakpoint for the tile. Could you explain that?
