### ISSUE TITLE
Stacked Font Awesome 5.5 icon do not align properly

### ISSUE THREAD

**Issue by Nantor** [jgthms/bulma#2974]
This is about Bulma | the Docs.

Is it about Bulma or about the Docs?
Overview of the problem

This is about the Bulma CSS framework
This is about the Bulma Docs
I'm using Bulma version [0.7.4] -->
My browser is: Firefox, Chromium

I am sure this issue is not a duplicate? Yes
Description

Since Font Awesome version 5.5 the stacked icons (may others too) is not squared any more.
So the icons are not correct rendered with Bulma.
So the example from the Doc will not work any more, with Font Awesome version 5.5 or higher.
Steps to Reproduce

Link too JSFiddle: https://jsfiddle.net/kpr120yx/

It is not working also for current version of bulma (0.8.2) and Font Awesome (5.13.0).

**Comment by BraydenTW** [comment]
Is your `<i>` element taking up the width of the `<span>`?

**Comment by Nantor** [comment]
So far that I can see is that the {{display: inline-flex;}} on the {{.icon}} class is the problem, without it looks fine.

**Comment by BraydenTW** [comment]
Does it look fine without it then?

**Comment by Nantor** [comment]
I look a bit further. It will look fine, when the bulma wrapper `.icon` is set to large.
Than I looked at the font Font Awesome classes and it looks like they extended the width (I think this is also the point you mean) from `2em` to `2.5em` (`.svg-inline--fa.fa-stack-2x {
    height: 2em;
    width: 2.5em;
}`). When I pull theses back to `2em`, it will be fine again (without changing bulma css).
Here a updated version of the fiddle: [https://jsfiddle.net/8e5g71az/1/](https://jsfiddle.net/8e5g71az/1/).
Does this mean bulma will no longer work with stacked icons on medium?

**Comment by BraydenTW** [comment]
Hmmm... well I am new to contributing to Bulma so I wouldn’t know of right now. Sorry about that.

**Comment by Tofandel** [comment]
You might want to report this to font-awesome as the width of the icons are bigger than their actual content
On the other hand you can fix this by adding another class to your stack icons and adding 
    width: 3rem; to that class

**Comment by Nantor** [comment]
@Tofandel: that could be a good option. I opened a Issue on Font-Awesome ([.fa-stack-xx not square size](https://github.com/FortAwesome/Font-Awesome/issues/16812)).
May there come some help or information.

**Comment by Nantor** [comment]
I got an answer back from the Font Awesome front:
> Hi!
>
>Thanks for being part of the Font Awesome Community and thanks for reporting this.
>
>Sorry for the breaking change, but this has been done to fix an issue when stacking wide icons like book-open with the CSS framework.
>
>Demo: https://jsfiddle.net/zye03bav/
>
>Also, documentation about stacks warns that some use cases may need style changes:
>
>Quoting from: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons
>
>    Some Custom CSS Required
>    You'll need to write your own custom rules if you change the default font-size of stacked icons as well as depending on your layout needs (by default stacked icons are set to display: inline-block; and vertical-align:middle;).
>
>Feel free to adjust your CSS if width: 2em works better for your use case
>
>Since you are using the SVG Framework, it is worth to note that you can go for layering, masking, and power transforms instead of stacking: https://fontawesome.com/how-to-use/on-the-web/styling/layering
>
>Demo: https://jsfiddle.net/5drL1ng0/
>
>Ref:
>
>https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
>https://fontawesome.com/how-to-use/on-the-web/styling/masking
>https://fontawesome.com/how-to-use/on-the-web/styling/layering
>
>Hope it helps
>
>Closing here
>
>edit
>
>    This lead to issues, where some CSS-Frameworks expect an Icon squarish.
>
>Font Awesome icons do not have same width and height by design choice. Some icons are wider than others (eg: hexagon, long-arrow, book-open, ...)

So I think bulma couldn't do here any thing.

In the documentation should be hint about this.
