### ISSUE TITLE
Creating fixed vertical navigation (a Menu?): initial guidance

### ISSUE THREAD

**Issue by JamesCropcho** [jgthms/bulma#2977]
This is about **Bulma**.

One could say I have a question, or instead that I need help.

### Overview of the problem

This is about the Bulma **CSS framework**

I am not sure that this issue is not a duplicate. I have searched for duplicates and not found any, but there is not a clear-winner term for which to search.

### Actual behavior

======

Hello,

I am trying to use Bulma to make a website layout which (at least on the desktop) looks like this: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_sidenav_fixed. (I'd want a different interface—probably something "hamburgery"—when viewed on a handset.)

I've read the documentation and I can't see if/how this is possible. It looks like I will need to use the Menu component, but I can't get it to expand to full height and to stay fixed while the main canvas scrolls.

Can you kindly point me in the right direction?

Sincerely,
James Cropcho

**Comment by RasdanJames** [comment]
For the sidebar, use a Menu (as you expected). Set the height to 100vh; This will make it run the entire length of the page. You can then change the sidebar so it's position fixed, then change the CSS for the right hand side to position it as outlined in that link.
