### ISSUE TITLE
Message header without body

### ISSUE THREAD

**Issue by Tofandel** [jgthms/bulma#2978]
This is about **Bulma**.
It is a feature request

### Description
It's currently possible to have a message without a header, but not possible to have one without a body

It would be nice to add the ability to add a message-header without a body

Adding a class .has-no-body to the header to make it fully rounded

### Code

```html
<article class="message">
  <div class="message-header has-no-body">
    <p>Hello world</p>
    <button class="delete" aria-label="delete"></button>
  </div>
</article>
```

### Current behavior
![image](https://user-images.githubusercontent.com/6115458/83549309-679d4100-a505-11ea-9838-e7f2cfb53a62.png)

### Desired behavior
![image](https://user-images.githubusercontent.com/6115458/83549355-7dab0180-a505-11ea-9919-daf7cc963c1b.png)

**Comment by RasdanJames** [comment]
Why not use Notifications for this then? 
```css
<div class="notification is-primary">
  <button class="delete"></button>
  Primar lorem ipsum dolor sit amet, consectetur
  adipiscing elit lorem ipsum dolor. <strong>Pellentesque risus mi</strong>, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum <a>felis venenatis</a> efficitur. Sit amet,
  consectetur adipiscing elit
</div>
```

**Comment by RasdanJames** [comment]
Makes sense. I wound up using notification for this exact thing and added a class (rather than the style) to do that for me. I also added a helper that makes the padding less so I could get the look I wanted. Your way would be easier. :)
