### ISSUE TITLE
Putting an image in a <label> tag using an image ratio causes an overblown image height

### ISSUE THREAD

**Issue by 6XGate** [jgthms/bulma#2979]
This is about a bug in **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.8.2
My **browser** is: Chrome
I am sure this issue is **not a duplicate**.

### Description

Putting an image in a `label` tag using an image ratio causes an overblown image height.

### Steps to Reproduce

Please see this CodePen: https://codepen.io/6XGate/pen/GRoRrNa

### Expected behavior

The image will be sized to within 96x96; but if small on either dimension, it will be padded to fill out.

### Actual behavior

The image is given a 96 pixel width, but the height is insanely out of control.

**Comment by jgthms** [comment]
Why use “is-1by1” and “is-96x96” together?

**Comment by 6XGate** [comment]
Using `is-96x96`, or any other sizing class, by itself only caps the dimensions of the image.  It doesn't ensure the `figure.image` element actually is that side.  So if you have a 96x8 image, the `figure.image` element will render as 96x8.  By having `is-1by1`, in most places, except a `label` element, you get a 96x96 `figure.image`, but with the 96x8 pixel image centered within it.

**Comment by 6XGate** [comment]
Still no word on this?
