### ISSUE TITLE
Cards should support the is-xxxx color headers

### ISSUE THREAD

**Issue by RasdanJames** [jgthms/bulma#2980]
This is a feature request.

Card headers should support the various color helpers that buttons, etc. use, to make the header that color. 

as in: 
```html
<div class="card">
    <div class="card-header is-primary">
         <p class="card-header-title">Title</p>
    </div>
    <div class="card-content">
         <div class="content">
              Some content
         </div>
    </div>
</div>
```

**Comment by jsjb** [comment]
`card-header` supports e.g. `has-background-primary`, but a text colour class like `has-text-white` must be applied to the `card-header-title` instead of the header itself to match.

**Comment by RasdanJames** [comment]
Thanks. I was trying to do something similar like the buttons have with is-xxxx but this works.
