### ISSUE TITLE
Columns doesn't autowrap when the limit of 12 columns is reached.

### ISSUE THREAD

**Issue by FoksVHox** [jgthms/bulma#2982]
This is about **Bulma**.

Is it a bug

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version**: 0.8.2
My **browser** is: Brave
I am sure this issue is **not a duplicate**?

### Description

So I've started with Bulma some days ago, and I've found a problem with the columns when you have a set of columns that exceeds 12 columns it doesn't go down under the elements..

### Steps to Reproduce

1. Create a default boilerplate with the Bulma CSS installed
2. Use the code below
```html
<div class="columns">
<div class="column is-6">
                    <div class="field">
                        <div class="control">
                            <input class="input" type="text" placeholder="Søg på f.eks. supper">
                        </div>
                    </div>
                </div>

                <div class="column is-3">

                    <div class="field">
                        <div class="control">
                            <div class="select is-primary is-fullwidth">
                                <select>
                                    <option>Select dropdown</option>
                                    <option>With options</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="column is-3">

                    <div class="field">
                        <div class="control">
                            <div class="select is-primary is-fullwidth">
                                <select>
                                    <option>Select dropdown</option>
                                    <option>With options</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="column is-4">

                    <button class="button is-dark is-fullwidth">Dark</button>

                </div>
</div>
```

### Expected behavior

I expect the columns to be responsive in terms of the 12 column limit.

### Actual behavior

It just continues out.
![image](https://user-images.githubusercontent.com/37844753/83952089-95042a80-a836-11ea-8310-33b2e2a6de27.png)

**Comment by jgthms** [comment]
Have you tried the multi line option https://bulma.io/documentation/columns/options/#multiline

**Comment by FoksVHox** [comment]
Oh
I didn't know that was a thing sorry!

**Comment by mboullouz** [comment]
> Have you tried the multi line option https://bulma.io/documentation/columns/options/#multiline

Thanks for the response 👍 
I spend a lot of time on this issue, I assume most user coming from Bootstrap (they are many) just expect ths `.columns .colum.is-12` to start a new row/column.
Please make this obvious in the doc maybe as warning to people like me in the first section about columns.
Thanks,
