### ISSUE TITLE
typography helpers documentation missing

### ISSUE THREAD

**Issue by kevinastock** [jgthms/bulma#2985]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

https://bulma.io/documentation/modifiers/typography-helpers/ is missing content. It looks like it was removed in https://github.com/jgthms/bulma/commit/8c65f026279a1d9eec824e71a886c2fe159b1175#diff-bd6f107486d4d4b13c95e845f32c5aa5

### Steps to Reproduce

https://bulma.io/documentation/modifiers/typography-helpers/

**Comment by kevinastock** [comment]
I see, they were moved to the top level helpers: https://bulma.io/documentation/helpers/

It seems this whole intermediate page is no longer necessary, it's just a reference to syntax and some now moved content: https://bulma.io/documentation/modifiers/

**Comment by jgthms** [comment]
Ah yes good point. I forgot to remove the old pages. Will do that soon.
