### ISSUE TITLE
Bulma 0.9.0 removed list component, but this was not noted in the changelog

### ISSUE THREAD

**Issue by cnorthwood** [jgthms/bulma#2988]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.9.0]

I am sure this issue is **not a duplicate**?

### Description

Bulma 0.9 unexpectedly removed the list component, and this was not mentioned in the changelog.

### Steps to Reproduce

1. View Changelog at https://github.com/jgthms/bulma/blob/master/CHANGELOG.md#090 to check for breaking changes
2. Upgrage Bulma version after noting no breaking changes (despite this being a semver-major release)

### Expected behavior

Components styled using Bulma continue to work as before.

### Actual behavior

Upgrading to Bulma 0.9.0 removed the list component resulting in various unstyled components in the app appearing that were previously styled as a list.

I accept 0.8 -> 0.9 is a semver-major change (and therefore can contain breaking changes as Bulma has not yet reached a stable semver), but it'd be good practice to have included this in the changelog, rather than just removing the list component from the docs (related to #2780)

**Comment by jgthms** [comment]
That's true, sorry about that. I will update the changelog.

**Comment by cypressious** [comment]
What was the reason for the removal?

**Comment by cnorthwood** [comment]
@cypressious 0.8 -> 0.9 is a major version bump under semver (versions starting 0. have a different set of rules as it's classed as an unstable release)

**Comment by airblade** [comment]
@cypressious 
> The list is too close to the panel in my opinion. I feel like it would bloat Bulma to have both. It was a mistake to add the list in the first place.

https://github.com/jgthms/bulma/issues/2780#issuecomment-578443216
