### ISSUE TITLE
Typography Helper has no effect on footer (0.9.0 vs 0.8.2 )

### ISSUE THREAD

**Issue by rognales** [jgthms/bulma#2989]
This is about **Bulma**.

### Overview of the problem

 This is about the Bulma **CSS framework**
I'm using Bulma **0.9** 
My **browser** is: Chrome 83
 I am sure this issue is **not a duplicate**? 

### Description

Some text modifier/helper behaves differently between 0.8.2 and 0.9.0
The class has to effect to child or current elements.

### Steps to Reproduce
![carbon (4)](https://user-images.githubusercontent.com/28396330/84168697-4959b700-aaaa-11ea-8aeb-cf121dd32fae.png)

1. Applies typo helper. In this code snippet

- Line 1 -> ````has-text-white````
- Line 8,10,12 -> ````has-text-white````
- Line 20 -> ````has-text-right````

### Expected behavior

This is the output in ````0.8.2````
![image](https://user-images.githubusercontent.com/28396330/84168121-9d17d080-aaa9-11ea-9b6f-bab9f6bd7e61.png)

### Actual behavior

This is the output in ````0.9.0````
![image](https://user-images.githubusercontent.com/28396330/84168184-aef97380-aaa9-11ea-8d56-6ea8935bc317.png)

**Comment by rognales** [comment]
Looks like i didn't include ````bulma/sass/helpers/_all```` in my build process.
Weird since it works in 0.8.2 without explicitly importing the helper sass.

````css
@import "bulma/sass/utilities/_all.sass"
@import "bulma/sass/base/_all"
@import "bulma/sass/elements/_all"
@import "bulma/sass/form/_all"
@import "bulma/sass/components/_all"
@import "bulma/sass/grid/_all"
@import "bulma/sass/layout/_all"
@import "bulma/sass/helpers/_all"
````

**Comment by jgthms** [comment]
Ah yes, the helpers used to be in `@import "bulma/sass/base/helpers` but they've moved to their own folder now. There should be a warning in the console.

**Comment by rognales** [comment]
Owh the changes introduced in 0.9.0? Perhaps you can mentioned this in the changelog?

Nope, nothing was complain during build.
