### ISSUE TITLE
is-active doesn't highlight the link

### ISSUE THREAD

**Issue by kaihendry** [jgthms/bulma#2990]
This is about **Is it a bug/feature/question or do you need help?**.

### Overview of the problem

**is-active** class isn't highlighting a link of a current page

### Description

I have navigation list of pages expressed as an unordered list. I simply want to mark the active link in the section

### Steps to Reproduce

https://jsfiddle.net/kaihendry/cgh2b0ka/

### Expected behavior

Link is **highlighted**

### Actual behavior

Link is not highlighted, so users have no cue that this is the current page.

**Comment by rognales** [comment]
Are you talking about **List** component? But your snippet does not looks a **deprecated** Bulma List component?

Perhaps you can use **Menu**?

**Comment by kaihendry** [comment]
Thank you. I didn't know about [menu](https://bulma.io/documentation/components/menu/), and it seems to do the trick!
