### ISSUE TITLE
Linked icons dissapear on hover

### ISSUE THREAD

**Issue by kaihendry** [jgthms/bulma#2991]
This is about **Is it a bug/feature/question or do you need help?**.

### Overview of the problem

Hovering over an icon causes it to disappear

### Description

When about to click an icon, they disappear

### Steps to Reproduce

https://jsfiddle.net/kaihendry/pd0ngv4k/

### Expected behaviour

When icons are hovered over, the visual cue is that it's available to clicked on

### Actual behaviour

On hover the link disappears

**Comment by RasdanJames** [comment]
They're not disappearing. Your background is dark and the hover is darkening the icon, which makes it hard to see, but if you look closely, it's there. So the hover color should be changed when the background color is darker (perhaps to white).

Here's the modification I made: https://jsfiddle.net/sa6gjp2k/

It's quick and dirty but this would be a good feature request to automate as part of Bulma.

**Comment by kaihendry** [comment]
I don't have the time or energy to propose a feature request. Thank you for your modification, it works great!
