### ISSUE TITLE
Centered images like Puzzle Bobble

### ISSUE THREAD

**Issue by kaihendry** [jgthms/bulma#2994]
This is about **asking for help**.

### Overview of the problem

I want images to be spaced evently from the middle of the page. I'm not sure how to do that. https://bulma.io/documentation/elements/image/ doesn't help.

### Description

I want to center some images.

### Steps to Reproduce

https://jsfiddle.net/kaihendry/h6nq32dr/

### Expected behavior

Aligned from the center

### Actual behavior

Left aligned

**Comment by jgthms** [comment]
You can use Flexbox with “justify-content: space-evenly” https://cssreference.io/flexbox/#justify-content

**Comment by kaihendry** [comment]
Are columns already flexing?

Wonder why `.columns { justify-content: space-evenly; }` doesn't work...

https://jsfiddle.net/kaihendry/aoh4fzex/1/
