### ISSUE TITLE
Initial color variables are not overridden for has-XXX-classes in Angular 9 using Bulma 9

### ISSUE THREAD

**Issue by duck74** [jgthms/bulma#3000]
This is about **Bulma | the Docs**.

 Is it a bug/feature/question or do you need help?

### Overview of the problem

 This is about the Bulma **CSS framework**

 I'm using Bulma **version** [0.9.0]
My **browser** is: Chrome

### Description

In my angular app (version 9.1.11) I have overridden the initial Bulma color variables and when using the the has-text-XXX and has-background-XXX classes (whereas styles for buttons, which make use of the newly set colors, for example is-danger, still work), before it would use the colors I assigned. Since Bulma 9 this does not work anymore and the initial colors are still used.

### Steps to Reproduce
I have overridden the initial colors like that in the overall style.scss in my Angular App:
// Set your brand colors
$primary-blue: #23528C;
$light-gray: #B4B4B4;
$medium-gray: #7F7F7F;
$dark-blue: #163459;
$medium-pale-blue: #58789F;
$medium-blue:   #77A3D8;
$light-blue: #CFE1F7;
$red:  #B83B5E;
$green: #00B7A8;
$orange: #F8981C;
$dark-green: #008075;

// Update Bulma's global variables
$family-sans-serif: "Nunito Sans", sans-serif;
$grey-dark: $medium-gray;
$grey-light: $light-gray;
$primary: $primary-blue !default;
$danger: $red;
$success: $green;
$warning: $orange;
$link: $medium-blue;
$light: hsla(59, 82%, 50%, 0.08);

After that, I imported Bulma the Bulma extensions.

### Expected behavior

class has-text-primary would use the color, I defined for primary and not the turquoise color

### Actual behavior

Bulma initial colors are used for the has-text-XXX and has-background-XXX classes

**Comment by Loque18** [comment]
I'm running into a similar issue, I am not able to replace any of the initial Bulma variables in Angular (v15), did you find any solution for your problem ?
