### ISSUE TITLE
Usage permissions for Bulma logo

### ISSUE THREAD

**Issue by MattIPv4** [jgthms/bulma#3003]
This is about **Bulma and the docs**?

### Overview of the problem

I note that the Bulma logo is available in the docs directory of the repository: https://github.com/jgthms/bulma/blob/master/docs/_includes/svg/bulma-b.svg

The repository is licensed under MIT, though this license is oriented towards software/code.

What license/permissions cover the logo and the use of it?

### Description

For context, we’re currently working on a redesign on the cdnjs.com site and would like to feature some of the bigger libraries we host on the homepage, one of which is Bulma, so we’d like to be able to use the Bulma logo if possible as part of a bigger graphic on the new homepage.

As such, I wanted to check what license the logo falls under if any, and what permissions are granted for use of the logo/brand mark for Bulma?

**Comment by jgthms** [comment]
You're right, I should clarify that. There is no trademark on the logo right now (and I don't intend to create one). I should specify guidelines on how to use the logo, but it's more about aesthetics than legal restrictions.

So I want to say: go ahead and feel free to use it. In the meantime I will create a brand guidelines page, like [Mailchimp's](https://mailchimp.com/about/brand-assets/).

**Comment by MattIPv4** [comment]
Awesome, thank you for the quick answer!
