### ISSUE TITLE
Default tablet breakpoints don't affect iPads

### ISSUE THREAD

**Issue by eri-b** [jgthms/bulma#3019]
This is about the Bulma **CSS framework** 

### Description

Bulma's default tablet breakpoints do not work with iPads or iPad minis.

From the [docs](https://bulma.io/documentation/overview/responsiveness/), `tablet` refers to devices from 769px to 1023px in width. The trouble is &mdash; iPads and iPad Minis are 768px width in portrait, and 1024px width in landscape.

The breakpoint variables can be adjusted, but it seems odd to have defaults that don't work.

This issue was raised 3 years ago [here](https://github.com/jgthms/bulma/issues/1420), but the issue was closed.

### Steps to Reproduce

Use any tablet-specific responsive helper on an iPad or iPad mini, and it doesn't work.

Ex. `is-hidden-tablet-only`, `is-two-thirds-tablet`

[Here's a demo](https://bulmatablet--eri-b.repl.co/)

### Expected behavior

iPad or iPad Mini should respond to default Bulma responsive tablet helpers in both Portrait and Landscape mode.

### Actual behavior

iPad Portrait responds to Mobile helper, and iPad Landscape responds to Desktop helper.

**Comment by scheinercc** [comment]
Came across the same issue and agree. Some in the old ticket argued that on landscape (1024) hamburger is not necessary anymore and I'd be fine with that, but the `769px` breakpoint is particularly odd.

**Comment by scheinercc** [comment]
There are several +1s. Do they count for anything? Has this ticket been reviewed at all?
