### ISSUE TITLE
ma and pa - margin and padding for all sides

### ISSUE THREAD

**Issue by ambrt** [jgthms/bulma#3020]
**Feature proposal**

Along m* and p* helpers there could be all sides helpers. (a is for all)
```
pa-1
pa-2
etc
```

**Comment by sjclark** [comment]
I would recommend this simply become `m-1` `p-2` etc.
I don't think there is a need for the `a`.

I've just looked up that this approach also seems to be consistent with Bootstrap (not that the goal is to rip-off Bootstrap, however, the rest of the implementation seems largely identical).

**Comment by thefoxie** [comment]
@jgthms could you make a release? It's in the docs already which is nice but it doesn't work.

**Comment by sjclark** [comment]
@thefoxie definitely works, sure you've got updated Bulma and looking at the correct docs:
https://bulma.io/documentation/helpers/spacing-helpers/#list-of-all-spacing-helpers

**Comment by thefoxie** [comment]
@sjclark no. The commit is from 26days ago which was 27th of August and the latest release was on 7th of June.

**Comment by jgthms** [comment]
Will release this week. Sorry about the delay.

**Comment by sjclark** [comment]
@thefoxie AHHHH sorry didn't see the **all** thought this was an earlier issue about just the normal ones! Right you are!
