### ISSUE TITLE
Remove weight from has-text-weight-light and similar ones

### ISSUE THREAD

**Issue by codeyash** [jgthms/bulma#3021]
has-text-weight-light | Transforms text weight to light
-- | --
has-text-weight-normal | Transforms text weight to normal
has-text-weight-medium | Transforms text weight to medium
has-text-weight-semibold | Transforms text weight to semi-bold
has-text-weight-bold | Transforms text weight to bold

Sounds little long

has-text-bold is enough

Remove weight from all :)

**Comment by jgthms** [comment]
Problem “has-text-normal” could be fit anything: size, weight, style, capitalisation…

**Comment by codeyash** [comment]
I really like shorter names which says everything. One more way to go : https://tailwindcss.com/docs/font-weight
