### ISSUE TITLE
Add width weights for table columns when using the table class

### ISSUE THREAD

**Issue by svdHero** [jgthms/bulma#3022]
This is a feature request for Bulma.

### Description
When I use a `table` with many columns inside a `table-container`, the line breaks in the table cells' content can be really ugly.

It would be great if one could add weights to the columns in order to have more control over the width of a column.
Maybe something similar as with the `column` class, e.g.:

```html
<div class="container">
    <div class="table-container">
        <table class="table is-narrow is-bordered is-striped is-hoverable is-fullwidth">
            <thead>
                <tr>
                    <th class="is-half">Foo</th>
                    <th class="is-one-quarter">Bar</th>
                    <th class="is-one-quarter">Umu</th>
                </tr>
            </thead>
            <tbody>
                ...
            </tbody>
        </table>
    </div>
</div>
```

**Comment by RasdanJames** [comment]
You can have total control of the width even so just by doing percentage widths with style attribute or in a CSS class. I do it all the time. That said, it would be nice if the same CSS classes for DIV spacing also applied to tables as this requests. Then, we can use those or override them as needed.

**Comment by svdHero** [comment]
@jgthms Could this be re-opened, please? I would still find it helpful, if the same CSS classes could be used for table columns as for `column` class, instead of having to fall back to defining my own custom classes.
