### ISSUE TITLE
Disabled checkbox: cursor is not "not-allowed"

### ISSUE THREAD

**Issue by yelizariev** [jgthms/bulma#3024]
This is about **Bulma**. It's a bug, not a browser bug.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.0]
My **browser** is: latest chrome and firefox

 I am sure this issue is **not a duplicate**

### Description

Disabled checkbox: cursor is not "not-allowed"

### Steps to Reproduce
Try to add "disabled" to checkbox intput: https://bulma.io/documentation/form/general/

### Expected behavior

Cursor should be "not-allowed" as in other inputs
### Actual behavior

cursor is "pointer"

**Comment by abnersajr** [comment]
The issue is confirmed. I'm gonna make a PR tomorrow to fix it.
