### ISSUE TITLE
Input Range Styling

### ISSUE THREAD

**Issue by JelaniThompson** [jgthms/bulma#303]
Hi there!

I was just wondering if there were plans for a stylized input range object in Bulma any time soon. I'm currently creating an application that utilizes them but can't seem to find anything for it in the docs.

If not, could anyone recommend some style tips to help make one that fits in with Bulma? Thanks!

**Comment by jgthms** [comment]
It's not stylable in CSS. I recommend using http://rangeslider.js.org/
