### ISSUE TITLE
Tabs component has 2em left margin inherited from default <ul> styling.

### ISSUE THREAD

**Issue by BeetrootShoulders** [jgthms/bulma#3030]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.0]

I am sure this issue is **not a duplicate**

### Description

Tabs have a 2em left margin, inherited from the overall `<ul>` tag styling.

### Steps to Reproduce

```
<div class="tabs is-fullwidth">
   <ul>
      <li class="isactive">Tab One</li>
      <li>Tab Two</li>
  </ul>
</div>

```
### Expected behavior

Tabs extend full width of the page.

### Actual behavior

Left edge of left tab is 2em from the edge of its container. Inspection shows `.content .ul` is imposing this. Attempts to override in SASS before main Bulma import seem to make no difference. Currently fixed by adding `margin-left:0em` to relevant tag in `components\tabs.sass`.

**Comment by RasdanJames** [comment]
This is probably a minor point but the "isactive" should be "is-active".
