### ISSUE TITLE
How to use with angular?

### ISSUE THREAD

**Issue by AnderssonPeter** [jgthms/bulma#3031]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0]

This issue could be related to https://github.com/jgthms/bulma/issues/1568

### Description

Hi I'm developing a angular 9 application and want to use the scss variables defined by Bulma in my components.
But in angular each component has a scss file, so the only way i found to get access to the bulma variables where to `@import "~bulma/bulma";` in each component style file, but when bundling this results in me getting a copy of bulma bundled for each component and the style file grows to a huge size.

Do you have any ideas how to solve this? the only solution i can think of would be to move the variables, functions & mixins of bulma into their own files? (But this would have to be done
It seems bootstrap has done it this way https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss

**Comment by jgthms** [comment]
You can import only what you need into the component. For example, in your button component, you can import only “utilities/_all” and “elements/button”.

**Comment by AnderssonPeter** [comment]
Yes but say i need the button in two componens, now i end up with the css for the button two times (three if we count the that i include it in the global scss file).

Does `utilities/_all` include all variables or just the common ones? (They might be all i need)

**Comment by AnderssonPeter** [comment]
including utilities/_all solved my problem as i only need access to the common variables.
