### ISSUE TITLE
Change sass-cli page from gem to Dart Sass?

### ISSUE THREAD

**Issue by cameronelliott** [jgthms/bulma#3033]
This is about ** the Docs**.

I went through the tutorial on this page: [https://bulma.io/documentation/customize/with-sass-cli/](https://bulma.io/documentation/customize/with-sass-cli/)

Which is fantastic that it exists, because I am not a web-dev, and I really dislike yarn and npm,
and am thrilled to avoid them both. (mostly because I don't know them well)

But, going through it, installing the gem failed, and I ended up using Dart Sass,
which is the [primary implementation of Sass](https://sass-lang.com/dart-sass)

The issues with the gem are:
- installation doesn't go smooth on some systems (at least my Ubuntu 18.04)
- Dart Sass installs simply with an unzip & add to path
- Dart Sass is the primary implementation of Sass

I propose updating  the sass-cli page to use Dart Sass

I will do it, if the maintainers express interest in having a PR submitted for this small proposal.

I would do:
- add installation directions for Dart Sass on Linux (the Dart Sass directions are a little weak for beginners)
- remove gem install directions
- fix sass arguments format for Dart Sass ( `--sourcemap=none` has changed, etc...)
- fix `@import "../node_modules/bulma/sass/utilities/_all.sass";` lines to use correct or dynamic bulma version path like earlier in page

I really am thrilled with Bulma and this cli-based sass tutorial, so I wanna give a little love back. 

Thank you
Cameron

**Comment by jgthms** [comment]
I’ve been looking at and using Dart Sass a bit. Really love it. I need to see how I can add @use and @forward without breaking a lot of setups.

For the docs, I think there’s a case for keeping both a node-sass and a Dart sass page. I don’t think Dart sass is widely adopted yet.

**Comment by cameron-elliott** [comment]
I didn't know this earlier, but Ruby Sass has been discontinued and the repo has been archived.
[https://sass-lang.com/blog/ruby-sass-is-unsupported](https://sass-lang.com/blog/ruby-sass-is-unsupported)
[archived repo link](https://github.com/sass/ruby-sass)

But, I suppose there is still some value to showing how to use it.
