### ISSUE TITLE
Background color in burger menu doesn't recognize color setting of navbar

### ISSUE THREAD

**Issue by AracKnight** [jgthms/bulma#3037]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.0]

### Description

The background color of a navbar-menu is set to white for devices with less than 1024px width, when you are using a burger, no matter what the navbar is set to.

### Steps to Reproduce

1. Take following code:
```
<body>
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">
      <img src="logo.png">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="mainNavBar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="mainNavBar" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
          Home
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
             <a class="button is-light" href="logout">
                  Ausloggen
              </a>
        </div>
      </div>
    </div>
  </div>
</nav>
<script>
$(document).ready(function() {
  $(".navbar-burger").click(function() {
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");
  });
});
</script>
</body>
```
2. Deploy it to a website
3. Open the website with a device with less than 1024px width
4. Open the burger menu

### Expected behavior

The opened burger menu should have dark background color, since this was defined in class="navbar is-dark".

### Actual behavior

The background color of the opened burger menu is white, thus the menu entries aren't readable anymore.
![burger white](https://user-images.githubusercontent.com/43955252/87203696-78f71b80-c303-11ea-9d09-98bae67b6d18.png)

### Workaround
You can bypass this problem completely by overriding $navbar-background-color with a custom .scss-file. Then the background color of the burger menu is the same as navbars.

**Comment by arnelamo** [comment]
Thanks. 

I have the same problem, and this fixed the issue for me:

`$navbar-background-color: #363636;`

**Comment by VishwaJay** [comment]
A more broad-reaching fix (and one I deploy in my dark-themed project) is altering the color of `$scheme-main` in my alterations file (compiled with node-sass, per the documentation). I also altered `$background` and `$text` to accommodate before the compile. 

Hope this helps.
