### ISSUE TITLE
Content class doesn't use $title-family sass variable

### ISSUE THREAD

**Issue by MonsieurMan** [jgthms/bulma#3039]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 9.0.0

### Description

When customizing bulma using `$title-family`, the font family is changed for `.title` class, but not for `.content > h*` headers.

### Steps to Reproduce

- Change $title-family
- Use any h tag within a tag with `.content`

### Expected behavior

The font family to change accordingly.

### Actual behavior

The font family is not changed.

### Notes

This may be intentional behavior, but then maybe a `$content-heading-family` variable should be added ?

I got around adding this for now : 
```scss
@for $i from 1 through 5 {
    h#{$i} {
        @extend .title;
        @extend .is-#{$i}
    }
}
```

**Comment by DawoodHayat** [comment]
hello? bro if u mind i have some query about node-sass bulma pkg would u like to ans my queries
