### ISSUE TITLE
A lot of errors in w3c validator

### ISSUE THREAD

**Issue by cadhead** [jgthms/bulma#3040]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.7.5**

### Description

I'm try to use buefy which uses v. 0.7.5, but getting a lot of errors (134) by w3c validator.
https://validator.w3.org/unicorn/check?ucn_uri=https%3A%2F%2Fcadhead.github.io%2Findex.html&ucn_task=conformance#

Is this fixed in 0.9.0 currently/planning exactly? I'm tryna find same closed issue, but looks like it's not exist.

**Comment by jgthms** [comment]
They’re mostly the same issues repeated. For example `—columnGap` is a CSS variable which is totally fine. 
Then there are other properties like pointer-events or text-rendering which trigger errors although they’re supported by all popular browsers.
In other words, I wouldn’t worry about these errors. Your website will work fine. This validator is a bit outdated.
