### ISSUE TITLE
$nav-height doesn’t affect logo height

### ISSUE THREAD

**Issue by oluckyman** [jgthms/bulma#305]
### Checklist
- [x] This is about the Bulma **CSS framework**
- [x] I'm using Bulma **version** [0.1.2]
- [x] I am sure this issue is **not a duplicate**?
### Description

There is a `$nav-height` variable which allows to change nav size. But the logo size remains hardcoded to `24px`. For now I’m using css override like so:

```
$nav-height: 70px

@import "~bulma/bulma"

.nav-item img
  max-height: 44px
```

But it does not seem reliable.
### Expected behavior

`$nav-logo-height` is exposed. Or calculated from `$nav-height`
### Actual behavior

logo height remains `24px`

**Comment by lxc-xx** [comment]
Is there any followup on this? I recently struggled on the height of navigation bar, too.

**Comment by dfu-io** [comment]
I think that this issue could be closed. With 0.6.0 version you can do this:

```css
$navbar-item-img-max-height: 40px;
$navbar-height: 70px;
```

**Comment by xlcrr** [comment]
The above code works to make a navbar height change
Edit line 6846 in the css
But it does not center navbar-items vertically as expected. How can I achieve this?

**Comment by xlcrr** [comment]
Quick hack to center items vertically in navbar. Wrap nav in divs+height

<div style="height: 10px;></div>
    <nav class="navbar">
     ...
    </nav>
<div style="height: 10px;></div>

**Comment by theturrible** [comment]
Also just wanted to point out that the new units for `$navbar-height` are `rem`, not `px`

**Comment by marcuxyz** [comment]
Change the `.navbar-item img`  class in `css`. Should works

e.g:
```
.navbar-item img {
    max-height: 3rem;
}
```

**Comment by imasip** [comment]
#header-logo{
  background: url(http://via.placeholder.com/160/640) no-repeat center center;
  background-size: cover;
  width: 152px
}

And on Html

only <a id="header-logo" class="navbar-item"></a>
