### ISSUE TITLE
Bulma documentation site available in spanish

### ISSUE THREAD

**Issue by TheUltraNerd** [jgthms/bulma#3050]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

I would like to suggest a spanish translation of the entire documentation site.
I've already been working on this, but I would like to hear some words about this idea first before going further...

### Steps to Reproduce

1. Generating a docs mirror site https://bulma.io/documentation/es/
2. Translation -> Pull request -> Review -> Approval -> Making it available on the site.
3. Continuous update and improvement by the community

### Expected behavior

Ideally, there would be a language selector on the navbar that redirects to a separate independent mirror (/documentation/es/), where anyone who's interested could work safely without modifying the main docs site.

It should end up looking like this:

![bulma_suggestion](https://user-images.githubusercontent.com/49707488/87868331-b2aece80-c962-11ea-9617-dda8fa2b6051.png)

Thanks for your time.

Sincerely,
Javier.

**Comment by jgthms** [comment]
I like the idea but unfortunately Github Pages doesn’t support Jekyll plugins. So we’d need to build the website somewhere else and push it to Github. 

Also, I’m not sure how the content would be translated. Right now, each page is a mixture of HTML, code snippets, JSON loops, and includes. So you’d have to translate everything. The quick and easy way would be to duplicate all the files and translate manually. The first translation would take a lot of time but it would work.

The main issue is maintaining it. After the first translation, if there’s any HTML change or code change or structural change, it has to be replicated across both languages.

Another approach would be to use a plugin to keep the content separate from the HTML but like I said it’s not supported by Github pages. 

Also, documentation is currently added and updated on a regular basis. I can handle the English version but someone would need to update the Spanish one soon afterwards.

I think a translation could work but as a separate repo and a separate website from which I can link. That way you have full control over the content and can structure and code it as you want.

**Comment by TheUltraNerd** [comment]
> I think a translation could work but as a separate repo and a separate website from which I can link. That way you have full control over the content and can structure and code it as you want.

Sounds nice! I'll go that way and inform you when I have the site ready. Cheers, Jeremy.

**Comment by jgthms** [comment]
Ok great. Closing this for now.
