### ISSUE TITLE
A bug with Bulma's class "columns" (?)

### ISSUE THREAD

**Issue by timongithubcom** [jgthms/bulma#3051]
This is about Bulma's class "columns".

### Overview of the problem

Maybe there is a bug on small displays (?).

On a smartphone, the page would pan left and right as if there is something wrong with spacing and sizing. 

### Steps to Reproduce

Here is my HTML to help you reproduce the issue. Load the page on a smartphone, and try pan the page left and right with your thumb.

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css">
</head>

<body>
    <section class="columns">
        <div class="column">
            First column
        </div>
        <div class="column">
            Second column
        </div>
    </section>
</body>

</html>
```

### Expected behavior

I expect the page to be static and "fit" the display and not pan.

### Actual behavior

The page is panning left and right even when there is little content.

Any feedback is appreciated. Thanks in advance!

**Comment by jgthms** [comment]
It’s the normal behaviour. Columns have a negative margin. You’re better off wrapping your content in a class=“section”.

See #2730

**Comment by timongithubcom** [comment]
Thank you!!!

**Comment by alcalbg** [comment]
This is documented under 'section' and included in the starter template as well.

"Use sections as direct children of body"

However, it doesn't say class 'section' so it's kinda confusing imho.

Cheers!
