### ISSUE TITLE
Select element can't make use of overflow-text

### ISSUE THREAD

**Issue by elmatou** [jgthms/bulma#3052]
Need help. 

I don't think it is a bug, but more a lack of feature.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description
I have <select> element, wrapped in a a "control". One of the options is veryyyyyyyyyyy long. 
I would like the text to overflow as an ellipsis and there is a good style attribute for this `text-overflow: ellipsis;`. but for this to work <select> or any parents need to have fixed width.. which is not the spirit of the framework
 
### Steps to Reproduce

```html
<div  class="control">
    <span class="select is-empty">
        <select
            style="text-overflow: ellipsis;overflow: hidden;">
            <option disabled="disabled" value="" hidden="hidden">
                Select a zone
            </option>
            <option data-v-d4e316ac="" value="AERO_FRANCE">FRANCE</option>
            <option data-v-d4e316ac="" value="AERO_EUROC">EUROC</option>
            <option data-v-d4e316ac="" value="AERO_EUR">EUR</option>
            <option data-v-d4e316ac="" value="AERO_TAHITI-EASTER_ISLAND-CHILI">TAHITI-EASTER_ISLAND-CHILI</option>
            <option data-v-d4e316ac="" value="AERO_TAHITI-POLYNESIE-FRANCAISE">TAHITI-POLYNESIE-FRANCAISE</option>
        </select>
    </span>
</div>
```

### Expected behavior

![image](https://user-images.githubusercontent.com/292021/88077165-3e9b4300-cb7b-11ea-83b1-6c171e59dd2b.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/292021/88076761-bf0d7400-cb7a-11ea-8abc-6ffd9d89f2e8.png)

If anybody got any clue ?!

**Comment by daniellenzofficial** [comment]
Probably you could shorten the options texts for Tahiti like so:
TAHITI-EASTER_ISLAND-CHILI -> TAHITI-EA_ISL-CHIL
And
TAHITI-POLYNESIE-FRANCAISE -> TAHITI-POLY-FRA
Or even shorter...

**Comment by elmatou** [comment]
Thx for your input, but I prefer not to temper with the data, and sort this in UI only.

**Comment by daniellenzofficial** [comment]
Makes sense :)) but text-overflow ellipsis only works for chrome for now...

Maybe here is a bunch of possible workarounds:
https://stackoverflow.com/questions/7289769/ellipsis-for-overflow-text-in-dropdown-boxes

**Comment by elmatou** [comment]
Nop, text-overflow :ellipsis is an old lady, it works since chrome 1 and Firefox 7.
https://developer.mozilla.org/fr/docs/Web/CSS/text-overflow
But it needs a width to work, and Bulma liquid concept avoid to give width value.

**Comment by daniellenzofficial** [comment]
probably you would need !important in your inline css then?

**Comment by RasdanJames** [comment]
I provide widths anyway where I need them, Bulma handles it just fine.
