### ISSUE TITLE
.input within <td>  makes a messy .table, because width:100%;

### ISSUE THREAD

**Issue by tsamop** [jgthms/bulma#3053]
This is about Bulma 

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.7.4]

### Description

Line 3030:
**.input,
.textarea {
....
  width: 100%;
}**
Causes issues when there is other content in same cell as an input or textarea, as the input box tries to take up the whole cell.

I would suggest adding:
**.table .input,
.table .textarea{
    width: unset;
}**

In order to override the width:100%; behavior for input boxes within table cells.

**Comment by daniellenzofficial** [comment]
Did you try with v0.9.0? Same behavior?
