### ISSUE TITLE
tabs broken inside .hero

### ISSUE THREAD

**Issue by torpay-dev** [jgthms/bulma#3056]
This is about **Bulma**.

It's a bug.

### Overview of the problem

This is about the Bulma **CSS framework**.
I'm using Bulma **version** [v0.9.0]
My **browser** is: Firefox

### Description

The tabs look broken when inside the `.hero` section.

### Steps to Reproduce

```
<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
          <div class="tabs">
            <ul>
              <li class="is-active"><a>Pictures</a></li>
              <li><a>Music</a></li>
              <li><a>Videos</a></li>
              <li><a>Documents</a></li>
            </ul>
          </div>
        </div>
    </div>
</section>
```

**Comment by codecat** [comment]
Possible duplicate of #3009, although this started happening to me since a recent Firefox update.

**Comment by digitigradeit** [comment]
I was able to resolve this by wrapping <nav.tabs inside <section

https://codepen.io/digitigradeit/pen/yLKxMwK

**Comment by electrofloat** [comment]
Tabs, are still broken inside hero

**Comment by digitigradeit** [comment]
> Tabs, are still broken inside hero

Please read my previous comment.
