### ISSUE TITLE
No GAPS between columns

### ISSUE THREAD

**Issue by TeachHip** [jgthms/bulma#3059]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.0] 
My **browser** is: Firefox (last version)

### Description

There re no GAPS between columns (as default)
### Steps to Reproduce

                <div class="columns">
                    <div class="column is-3">
                        First column
                    </div>
                    <div class="column">
                        Second column
                    </div>
                    <div class="column">
                        Third column
                    </div>
                </div>

### Expected behavior
To have GAPS between columns unless otherwise stated by adding specific class.

### Actual behavior
No GAPS.

**Comment by jgthms** [comment]
There are gaps, unless you put a background on the column. Do you have a screenshot?

**Comment by TeachHip** [comment]
Sure. Also I find now that when I apply a background color to each .column the .columns div seems to grow (!).

I attach code and screenshot:

`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <style>
        .with-bg .column {
            background-color: aquamarine;
        }
    </style>
</head>

<body>

    <section clas="section">
        <div class="container">
            <div class="columns">
                <div class="column is-3">
                    First column
                </div>
                <div class="column">
                    Second column
                </div>
                <div class="column">
                    Third column
                </div>
            </div>
        </div>
    </section>

    <section clas="section">
        <div class="container">
            <div class="columns with-bg">
                <div class="column is-3">
                    First column
                </div>
                <div class="column">
                    Second column
                </div>
                <div class="column">
                    Third column
                </div>
            </div>
        </div>
    </section>


</body>

</html>`


![Screenshot_2020-07-26 Document](https://user-images.githubusercontent.com/55443146/88485311-42f99e80-cf75-11ea-8894-24a41e4cf4c7.png)

Thank you!

**Comment by TeachHip** [comment]
Up! Any clue?
I should be teaching Bulma to my students this week but don't feel very comfortable with documentation :-( 
That's why I'd need some help, if possible. Ty

**Comment by jgthms** [comment]
You shouldn't put a background color on `columns` or `column` but rather on the element that is the direct child of the `column`.

**Comment by TeachHip** [comment]
Thank you! My fault.
Hope I can improve my learning curve now.
