### ISSUE TITLE
i want solution for bulma-sass-node version varaibles

### ISSUE THREAD

**Issue by DawoodHayat** [jgthms/bulma#3060]
hello fellas i got struck since yesterday but didn't understand the bulma official documentation about customise variables .i used bulma node-sass package everything was fine  and. no error while installing  all related dependencies but i got issue when i want to change navbar color or even its size it didn't change through scss variables. i learn documentation lots of time but i can't get it. 

 

main-folder-- webpro
-- node_modules
--sass folder
  -- mystyles.scss
-- css folder 
  -- mystyles.css
-- pkg.json
-- pkg-lock.json

### my index.html starter code 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My custom Bulma website</title>
    <link rel="stylesheet" href="vendors/bulma/css/bulma.css">
    <link rel="stylesheet" href="css/mystyles.css">
  </head>
  <body>
 <section class="hero is-primary pb-4">
      <nav class="breadcrumb is-right mt-2" aria-label="breadcrumbs">
        <nav class="breadcrumb" aria-label="breadcrumbs">
          <ul>
            <li>
              <a href="#">
                <span class="icon is-small">
                  <i class="fas fa-home" aria-hidden="true"></i>
                </span>
                <span>Bulma</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="icon is-small">
                  <i class="fas fa-book" aria-hidden="true"></i>
                </span>
                <span>Documentation</span>
              </a>
            </li>
            <li>
              <a href="#">
                <span class="icon is-small">
                  <i class="fas fa-puzzle-piece" aria-hidden="true"></i>
                </span>
                <span>Components</span>
              </a>
            </li>
            <li><a href="#">
                <span class="icon is-small">
                  <i class="fas fa-thumbs-up" aria-hidden="true"></i>
                </span>
                <span>Breadcrumb</span>
              </a>
            </li>
          </ul>
        </nav>
  </nav>
</section>

<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="#">
        Home
      </a>

      <a class="navbar-item " href="#">
        Home
      </a>
      <a class="navbar-item" href="#">
        Home
      </a>
      <a class="navbar-item" href="#">
        Home
      </a>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="https://bulma.io" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=https://bulma.io&amp;via=jgthms">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
              <span>
                Tweet
              </span>
            </a>
          </p>
          <p class="control">
            <a class="button is-primary" href="https://github.com/jgthms/bulma/releases/download/0.9.0/bulma-0.9.0.zip">
              <span class="icon">
                <i class="fas fa-download"></i>
              </span>
              <span>Download</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>

</nav>

<figure class="image is-5by3">
  <img src="images/2.jpeg">

    <div class="container">
      <h1 class="title">
        Fullheight title
      </h1>
      <h2 class="subtitle">
        Fullheight subtitle
      </h2>
    </div>
</figure>

<script src="bulma.js" charset="utf-8"></script>
  </body>
</html>

## my scss file 

  @charset "utf-8";
  @import "../node_modules/bulma/bulma.sass";
  @import "./node_modules/bulma/sass/utilities/initial-variables";
  @import "./node_modules/bulma/sass/utilities/functions";
  @import "../node_modules/bulma/sass/utilities/_all.sass";
@import "../node_modules/bulma/sass/base/_all.sass";
  @import "../node_modules/bulma/sass/components/navbar.sass";
  @import "../node_modules/bulma/sass/layout/hero.sass";

  $navbar-background-color:  hsl(217, 71%, 53%);
$breadcrumb-item-color: hsl(0, 0%, 21%);
$breadcrumb-item-separator-color: $border-hover;
$body-background-color:  hsl(0, 0%, 21%);;

**Comment by jgthms** [comment]
Put your variables before importing everything else.

```scss
@charset "utf-8";
@import "./node_modules/bulma/sass/utilities/initial-variables";
@import "./node_modules/bulma/sass/utilities/functions";
@import "../node_modules/bulma/sass/utilities/_all.sass";
@import "../node_modules/bulma/sass/base/_all.sass";
@import "../node_modules/bulma/sass/components/navbar.sass";
@import "../node_modules/bulma/sass/layout/hero.sass";

$navbar-background-color: hsl(217, 71%, 53%);
$breadcrumb-item-color: hsl(0, 0%, 21%);
$breadcrumb-item-separator-color: $border-hover;
$body-background-color: hsl(0, 0%, 21%);

@import "../node_modules/bulma/bulma.sass";
```
