### ISSUE TITLE
Feature Request: Add .is-clickable helper

### ISSUE THREAD

**Issue by vjik** [jgthms/bulma#3062]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Add this code to helpers:

`.is-clickable { cursor: pointer; }`

**Comment by RasdanJames** [comment]
Yes, I second this. Great suggestion.

**Comment by imlinus** [comment]
Yes!

There's a few different utility-classes I'm still missing in Bulma. This is definitely one of them 👍 
Here's a paste of my complimentary `utils.scss` file

```
.is-clickable {
  cursor: pointer;
  pointer-events: all;
}

.is-dimmed {
  opacity: 0.5;
}

.is-disabled {
  cursor: not-allowed;
  pointer-events: none;
}

.is-not-resizeble {
  resize: none !important;
}
```

Cheers

**Comment by service-paradis** [comment]
Instead of `is-clickable`, it could have been good to use something more along `has-cursor-pointer`. This way, other cursor helpers could be added eventually. Ex. `has-cursor-move`, `has-cursor-not-allowed`, etc.

**Comment by service-paradis** [comment]
@jgthms Instead of is-clickable, it could have been good to use something more along has-cursor-pointer. This way, other cursor helpers could be added eventually. Ex. has-cursor-move, has-cursor-not-allowed, etc.

**Comment by LoopsGod** [comment]
@service-paradis Might create too much helpers, ``is-clickable`` is a really common use case. If you need the other cursors, you'd be better off setting them on your own CSS classes in my opinion. You don't really need 10+ helpers for a basic CSS property.

**Comment by service-paradis** [comment]
Not necessary to add the other helpers right now (or never in fact). But if someday, @jgthms want to add some more, it would be easier to keep it consistent. But it is only a matter of opinion. I have not really a problem with it right and it is already merged anyway!
