### ISSUE TITLE
is-active on panel-block

### ISSUE THREAD

**Issue by FreekyMage** [jgthms/bulma#3063]
This is about **Bulma**.
This a **bug**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.8.0] (but I checked the code here on github and it also applies to 0.9.0 as well)
I am sure this issue is **not a duplicate**

### Description

$panel-block-active-border-left-color is never actually used.
In the code you can find:
```
.panel-block
  &.is-active
    border-left-color: $panel-block-active-border-left-color
```
This doesn't do anything because a border on the left for .panel-block is never defined.

### Steps to Reproduce

1. Go to https://bulma.io/documentation/components/panel/
2. You can see that no panel blocks have a left border, not even the active ones.

### Expected behavior

A colored left or bottom (because that one is defined) border on active panel blocks.

### Actual behavior

No border on active panel blocks is show.

**Comment by RogerE** [comment]
Comparing to 0.9.0 to 0.7.5 it seems that style and with for the border is no longer defined, just color, so I was able to "fix" this by adding the following to my css:

`.panel-block.is-active {
    border-left:  1px solid;
}`
