### ISSUE TITLE
RTL for `navbar-start` and `navbar-end` not updating content margins

### ISSUE THREAD

**Issue by msomji** [jgthms/bulma#3064]
### Overview of the problem

RTL for `navbar-end` and `navbar-start` don't appear to be working as expected. When setting the `dir="rtl"` on the body tag, the element with the class `navbar-end`and `navbar-start` moves to the the expected location, however the margin remain unchanged. 

 I'm using Bulma **version** [0.9.0] 
 My **browser** is: Chrome

### Steps to Reproduce
 I was able to reproduce this locally as well as on the bulma.io site as described below:

1. navigate to [bulma navbar section](https://bulma.io/documentation/components/navbar/)
2. open inspect tools and update body tag to container `dir="rtl"`
3. Observe the changes in the nav bar. (alternatively look at the screenshots I have below)

### Actual behavior

This is the LTR version of the navbar: 
![nav-ltr](https://user-images.githubusercontent.com/9360934/88825594-c2fe4f00-d195-11ea-9200-8ef67bfc16f5.png)

This is the RTL version of the same navbar: 
![nav-rtl](https://user-images.githubusercontent.com/9360934/88825610-c85b9980-d195-11ea-997b-9b84268cc2fe.png)

### Expected behavior

I would expect that the login/Sign up buttons to be pushed to the left and the More/Documentation/Home links to be pushed to the right.

**Comment by msomji** [comment]
I just noticed that adding the sass variable `$rtl: true` allows the navbar to work as expected.  Is there anyway to be able to support both rtl and ltr versions without having to regenerate all the css again?

**Comment by saraElsanan** [comment]
My same Question here , like tailwind , it allows you to add rtl:mr-2 or ltr:m;-3
where you can use both options not regenerate the whole css , only one file that can handle both Arabic and other languages
