### ISSUE TITLE
Loading status only works for default input size

### ISSUE THREAD

**Issue by mzgajner** [jgthms/bulma#307]
### Checklist
- [x] This is about the Bulma **CSS framework**
- [x] I'm using Bulma **version** [0.1.2]
- [x] I am sure this issue is **not a duplicate**
### Description

_Please see reproduction steps first to understand the bug._ I'm preparing a PR that fixes this, but could use some feedback first.

My main issue is that the loading status modifier (`.is-loading`) is present on the `.control` wrapper while size modifiers (`.is-large`) are specified on the child input element, so they cannot be used to style the size of the loader.

I checked the docs and since there is no example of an input without the wrapper, the most practical solution would be to change the way size modifiers behave and move them to the wrapper element. How do you feel about this?

A less important sub-question - do you think it would make sense to scale loader sizes on buttons in the same way? Currently, they remain the same regardless of button size.
### Steps to Reproduce
1. Copy an example of a non-default sized (small/medium/large) input from the docs.
2. Add `.is-loading` class to the `.control` wrapper.
3. Look at the incorrectly sized input.
### Expected behavior

The size of the loader should match the size of the input.
### Actual behavior

The size of the loader remains the same.

**Comment by jgthms** [comment]
This has been fixed.
