### ISSUE TITLE
Buggy behavior when upgrading from 0.8.2 to 0.9

### ISSUE THREAD

**Issue by simplenotezy** [jgthms/bulma#3073]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

When upgrading to 0.9 from 0.8.2, it looks like this:

**0.9.0**
![image](https://user-images.githubusercontent.com/3786627/89285255-529d7500-d650-11ea-8976-2a36d0623ab2.png)

**0.8.2**
![image](https://user-images.githubusercontent.com/3786627/89285476-ba53c000-d650-11ea-8932-78c4d0e98c26.png)

### Steps to Reproduce

1. Have version 0.8.2
2. Upgrade to version 0.9
3. See result

### Expected behavior

Paragraphs, font-familys, text-decoration etc, would be unchanged

### Actual behavior

It's not respecting the font-family set by $family-primary or $family-sans-serif.

Links should not have underline

### Addtional

I haven't been able to see anything in the changelog that should be related to this.

**Comment by jgthms** [comment]
Could you share how you load Bulma and set the variables? Only the top-level Sass file basically.

**Comment by simplenotezy** [comment]
This is how I do it:

	@import './bulma_variables.scss';

	@import '~bulma/sass/utilities/_all.sass';

	@import '~bulma/sass/base/_all.sass';

	@import '~bulma/sass/grid/columns.sass';

	@import '~bulma/sass/elements/container.sass';
	@import '~bulma/sass/elements/button.sass';
	@import '~bulma/sass/elements/notification.sass';
	@import '~bulma/sass/elements/title.sass';
	@import '~bulma/sass/elements/table.sass';
	@import '~bulma/sass/elements/other.sass';
	@import '~bulma/sass/elements/tag.sass';

	@import '~bulma/sass/form/shared.sass';
	@import '~bulma/sass/form/input-textarea.sass';
	@import '~bulma/sass/form/select.sass';
	@import '~bulma/sass/form/tools.sass';

	@import '~bulma/sass/layout/hero.sass';
	@import '~bulma/sass/layout/section.sass';

	@import '~bulma/sass/components/dropdown.sass';
	@import '~bulma/sass/components/menu.sass';
	@import '~bulma/sass/components/navbar.sass';
	@import '~bulma/sass/components/modal.sass';
	@import '~bulma/sass/components/message.sass';

And my `bulma_variable.scss` file:

	@import '~bulma/sass/utilities/initial-variables';

	$primary: #103033;
	$secondary: #E3CEBD;
	$grey: #737373;
	// $grey: #818690; // NOT enough color contrast ratio: https://web.dev/color-contrast/?utm_source=lighthouse&utm_medium=devtools
	$grey-light: #e3e3e3;
	$grey-lighter: #EFEFEF;
	$grey-lightest: #FAFAFA;
	$title-color: #363636;
	$subtitle-color: #4a4a4a;
	$radius: 0px;

	$family-sans-serif: Helvetica, Arial, sans-serif;
	$family-primary: $family-sans-serif;
	// $family-primary: futura-pt, sans-serif;
	$weight-light: 300;
	$weight-normal: 400;
	$weight-medium: 500;
	$weight-semibold: 500;
	$weight-bold: 500;

**Comment by bekwam** [comment]
After I saw some elements weren't aligned properly, I added the whole bulma.sass in place of individual imports.  See if this restores your app and then reconcile the imports.

**Comment by jgthms** [comment]
The helpers have moved from `base/helpers.sass` to their own `helpers` folder.

Add `@import '~bulma/sass/helpers/_all.sass' as an import.
