### ISSUE TITLE
Table headers are centered aligned in Safari

### ISSUE THREAD

**Issue by scottwernervt** [jgthms/bulma#3076]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.0]
My **browser** is: Safari Version 13.1.2 (15609.3.5.1.3) and Firefox 79.0 (64-bit)
I am sure this issue is **not a duplicate**

### Description

Table headers are **left aligned** in Firefox and Chrome but **centered aligned** in Safari.

Firefox
![image](https://user-images.githubusercontent.com/1048949/89563443-734d0280-d7e9-11ea-9015-340be074142c.png)

Safari
![image](https://user-images.githubusercontent.com/1048949/89563431-6f20e500-d7e9-11ea-8728-36649bb3fd9a.png)

### Steps to Reproduce

1. In Firefox, navigate to https://bulma.io/documentation/elements/table/
2. Sample table column headers are **left aligned**
3. In Safari, navigate to https://bulma.io/documentation/elements/table/
4. Sample table column headers are **center aligned**

### Expected behavior

Header text alignment should be consistent with each browser. The default should be left aligned.

### Actual behavior

Header text alignment is not consistent across Firefox/Chrome vs Safari.

**Comment by hernanvicente** [comment]
Hello, I can confirm the same behavior in Safari. The texts of the `th` elements are being centered.
Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by thedoglett** [comment]
Same here, Bulma 0.9.0 and Safari 14.0.3 (Catalina).

**Comment by airblade** [comment]
Still outstanding.

**Comment by airblade** [comment]
Thank you!
