### ISSUE TITLE
Spacing helpers missing in bulma.min.css of the release artifact 0.9.0

### ISSUE THREAD

**Issue by waahhhh** [jgthms/bulma#3077]
This is about **Bulma | the Docs**.

It's about Bulma.

It's a bug.

It's not a browser bug.

### Overview of the problem

It's about the Bulma **CSS framework**.

I'm using Bulma **version** [0.9.0].

I am sure this issue is **not a duplicate**.

### Description

**bulma.min.css** of the release artifact 0.9.0 doesn't include the spacing helpers.

### Steps to Reproduce

1. Checkout the **bulma.min.css** from https://github.com/jgthms/bulma/blob/0.9.0/css/bulma.min.css.
2. Ensure the class `.mt-0` is available
3. Checkout the **bulma.min.css** from https://github.com/jgthms/bulma/releases/download/0.9.0/bulma-0.9.0.zip.
4. Ensure the class `.mt-0` is available

### Expected behavior

The spacing helpers should be available in the  **bulma.min.css** of https://github.com/jgthms/bulma/releases/download/0.9.0/bulma-0.9.0.zip.

### Actual behavior

The spacing helpers aren't available in the  **bulma.min.css** of https://github.com/jgthms/bulma/releases/download/0.9.0/bulma-0.9.0.zip.

**Comment by halivert** [comment]
They are

![mt in bulma.min.css](https://user-images.githubusercontent.com/16197249/90696127-61d01580-e241-11ea-8aaf-26e3fd501ed5.png)

![mt in bulma.min.css from zip](https://user-images.githubusercontent.com/16197249/90696322-abb8fb80-e241-11ea-8478-69c8df35deb2.png)

**Comment by waahhhh** [comment]
Seems to be fixed. 👍
