### ISSUE TITLE
block is not vertically centered

### ISSUE THREAD

**Issue by vxfil** [jgthms/bulma#3082]
### Description

please tell me how to center the block vertically

```
<div className="columns is-centered is-vcentered is-desktop">
      <div className="column is-one-quarter">
        <div className="box">
            // code...
        </div>
      </div>
 </div>
```
![screen](https://user-images.githubusercontent.com/46137927/90171679-842de300-ddaa-11ea-9cf1-8cfea4c631b4.jpg)

**Comment by jgthms** [comment]
You need a full height container that has `height:100vh`. Try the full height hero.

**Comment by vxfil** [comment]
sorry, please, I didn't quite understand what needs to be wrapped in a hero container, if it was about it, it didn't work for me
```
<div className="hero" style={{height: "100vh"}}>
  <div className="columns is-centered is-vcentered is-desktop">
      <div className="column is-one-quarter">
        <div className="box">
            // code...
        </div>
      </div>
   </div>
</div>
```

**Comment by vxfil** [comment]
> You need a full height container that has `height:100vh`. Try the full height hero.

sorry, please, I didn't quite understand what needs to be wrapped in a hero container, if it was about it, it didn't work for me

```
<div className="hero" style={{height: "100vh"}}>
  <div className="columns is-centered is-vcentered is-desktop">
      <div className="column is-one-quarter">
        <div className="box">
            // code...
        </div>
      </div>
   </div>
</div>
```
