### ISSUE TITLE
No spacing helper present for all directions (top, right, bottom, left)

### ISSUE THREAD

**Issue by erkanonal** [jgthms/bulma#3083]
This is about **Bulma**.

It can be called as an improvement.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.0]

### Description

Description of the bug, enhancement, or question:

In this version, there are spacing helpers for all directions (top: t, right: r, bottom: b, left: l) and also (left and right: x, top and bottom: y) but there is no spacing helper to choose all directions. For example: I initially expected m-1 to work as margin: 0.25 rem but it does not. It would be great to add an appropriate helper to handle this. It could be making m-1 kind of way or adding an another helper like all -> m-all.

**Comment by service-paradis** [comment]
I think this duplicate #3020

**Comment by erkanonal** [comment]
Seems so. I am sorry that I did not notice that issue. Closing this...
