### ISSUE TITLE
Proposal: "is-tiny", because "is-small" not always small enough

### ISSUE THREAD

**Issue by Zauberfisch** [jgthms/bulma#3092]
This is about **Bulma**.  
This is a feature request.  

### Description

To my understanding bulma currently has the sizes `is-small`, `is-normal`, `is-medium`, `is-large`.
However, very frequently, I come across the need to have very small elements that are not really covered by this.  

I thought about changing the size of `is-small` to fit my need, but I often need 2 steps below `is-normal`, so I would need to make `is-medium` my new default and restyle all 3.

2 examples:

- `<input>` inside `<th>` to filter the table. 
  This often has to be really small to not mess with the table style
- inline `<button>` that I need to be sized to fit in with a bunch of text

A possible solution could be to introduce an additional size `is-tiny`.   
So we have `is-normal` and 2 steps up and 2 steps down.

**Comment by Zauberfisch** [comment]
bump.

Is adding an additional size something the project is open to?
I might implement it and create a PR if I know there is a decent chance it will get merged.

**Comment by Stazer** [comment]
I would love to see this feature, since 5 levels of size provide more granularity.

**Comment by Zauberfisch** [comment]
sorry to do this, but: bump

I'd be willing to do a PR if I get a hint that there is a good chance it will ger merged

**Comment by Zauberfisch** [comment]
bump
