### ISSUE TITLE
navbar collapses when screen width is <= 1024px

### ISSUE THREAD

**Issue by elgs** [jgthms/bulma#3093]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.0]
My **browser** is: Chrome

### Description

When the browser width is <= 1024px, the nav bar collapses. Is there a way I can set the 1024 to a much smaller value? Thanks.

### Steps to Reproduce

```html
<nav class="navbar is-primary" role="navigation" aria-label="dropdown navigation">
   <div class="navbar-item has-dropdown is-hoverable">
     <a class="navbar-link">
       Docs
     </a>
 
     <div class="navbar-dropdown">
       <a class="navbar-item">
         Overview
       </a>
       <a class="navbar-item">
         Elements
       </a>
       <a class="navbar-item">
         Components
       </a>
       <hr class="navbar-divider">
       <div class="navbar-item">
         Version 0.9.0
       </div>
     </div>
   </div>
 </nav>
```

### Expected behavior

![image](https://user-images.githubusercontent.com/55955/91514557-e7843e80-e89b-11ea-8df3-9d7d99ba7336.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/55955/91514542-de936d00-e89b-11ea-8a5b-76975a1f7345.png)

**Comment by jgthms** [comment]
Have you tried changing the value of `$navbar-breakpoint`?

**Comment by elgs** [comment]
It works! Thank you so much!
