### ISSUE TITLE
Hero Body misalignment in Internet Explorer 11

### ISSUE THREAD

**Issue by RichardBosworth** [jgthms/bulma#3108]
This is about **Bulma**.

Misaligned hero in Internet Explorer 11.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.9.0**
My **browser** is: IE11

### Description

When creating a full height hero section, based off the Bulma documentation, whilst it works well in Chrome/Edge etc, the alignment of the Body is offset in Internet Explorer 11.

### Steps to Reproduce

1. Create a hero section

```
<section className="hero is-light is-fullheight">
            <NavBar />
            <div className="hero-body">
                <div className="container">
                    <div className="card">
                        <div className="card-header">
                            <div className="card-header-title">Login</div>
                        </div>
                    </div>
                </div>
            </div>
</section>
```

### Expected behavior

This should work on all browsers

### Actual behavior

The body of the hero is offset to the side/down on Internet Explorer 11. See image below.

<a href="https://ibb.co/xzLCcDw"><img src="https://i.ibb.co/p4w0sxN/Bulma-issue.png" alt="Bulma-issue" border="0"></a>

The extent of this depends on the size of the browser window.

**Comment by jgthms** [comment]
Unfortunately, IE11 has weird bugs with Flexbox. I’m not sure how to fix this.

**Comment by sierikov** [comment]
I think we don't need the support of IE anymore.

**Comment by hyunbinseo** [comment]
Setting `height: 0;` in the `.hero` element works in IE 11 ([reference](https://stackoverflow.com/a/42930574/12817553)).

- Windows 10 21H2
- OS Build 19044.1766

![image](https://user-images.githubusercontent.com/47051820/177262879-16112290-386f-46df-b1ab-94470247cbad.png)

```html
<nav class="navbar">
</nav>
<section class="hero is-link is-fullheight-with-navbar" style="height: 0;">
  <div class="hero-body">
    <p class="title">
      Fullheight hero with navbar
    </p>
  </div>
</section>
```
