### ISSUE TITLE
is-paddingless class is missing when installed by npm

### ISSUE THREAD

**Issue by noomerzx** [jgthms/bulma#311]
- [ ] This is about the Bulma **CSS framework**
- [ ] I'm using Bulma **version** [0.1.2]
- [ ] My **browser** is: Google Chrome
### Description

I'm install bulma via npm on my vue webpack project. i just do some simple things like use is-paddingless in my component but it's not working. So I've reinstall bulma and it's still not work.
### Steps to Reproduce
1. install bulma via npm install bulma on vue project with webpack.
2. create div.container
3. create div.columns inside div.container.
4. create div.column.is-6.is-paddingless twice inside div.columns.
5. run npm run dev then test on Google Chrome and it's not working properly.

So I've exucute npm run build then looking into compiled css file. So is-paddingless class not exist and then I'm looking into nodemodule/bulma/css/bulma.css and the class is missing to.
### Expected behavior

I need to remove the column padding.
### Actual behavior

columns and column work find but is-paddingless not working

**Comment by jgthms** [comment]
You might need to compile the `bulma.sass`. I'll check if the `is-paddingless` is present in the output.

**Comment by Njoror** [comment]
@noomerzx  Version 0.1.2 (which you specified you are using) does not have that class, but the latest version 0.2.1 does. It looks like the class got added around September 11th.

**Comment by noomerzx** [comment]
@Njoror yep I don't try the lastest release yet. But I think like you. So the problem is I though all feature is base on documentation and last week the document still v.0.1.2 and that class is appear on modifiers sections but in css file does not have it and I don't have any sass file. So may be it's bug by the way.

I've work around by override it i just noticed by you that the new version is already release So I'll reinstall it. Thank you so much for the answer.

**Comment by Come2Daddy** [comment]
Version mismatch - need to be closed.
