### ISSUE TITLE
BUG: White strip on the right hand side on mobile

### ISSUE THREAD

**Issue by tofl** [jgthms/bulma#3122]
This is about **Bulma**.

It's a bug that occurs on most browsers I've tested (Chrome Desktop/mobile, Safari IOS, Firefox mobile, but not Firefox Desktop).

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.8.0]
My **browser** is: Chrome for Ubuntu (Desktop)

### Description

On mobile, there is a white gap on the right hand side of the screen. It looks like the bug is related to Bulma (and not my code), because I have found it on lots of sites made with Bulma including **bulma.io** (!) itself. Here are some examples:

![Bulma.io](https://i.imgur.com/I8ZmqH5.png)
![Other](https://i.imgur.com/qR9taRg.png)

You can see that I'm using the default zoom (100%).

### Steps to Reproduce

The problem seems related to the `columns` element. It has a margin of -12px on the right and removing it seems to solve the problem, but it also creates unwanted side effects (changes the alignment of the page). There should be a better way to solve it than changing Bulma's default properties.

**Comment by pburndorfer** [comment]
Can relate, we've stubled upon this too. It seems to be a bug of the negative margin (left and right) which applies to a **columns** class and the corresponding paddings on the **column** class which causes a horizontal scrolling on our site:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30462296/94565282-4c4f0200-0269-11eb-900a-aed0fb7b67e8.gif)

**Comment by akicho8** [comment]
I am troubled with the same problem too.
IOS Safari has a horizontal scroll, and the content moves left and right while operation.
Attempt and error, did the following:
But I do not know if this is good.

```
+mobile
  .columns
    margin-left: unset
    margin-right: unset
  .column
    padding-left: unset
    padding-right: unset
```
