### ISSUE TITLE
Question: Negative Margin in Titles?

### ISSUE THREAD

**Issue by steffchep** [jgthms/bulma#3123]
This is about Bulma

I have a question

### Overview of the problem

It turns out that Bulma uses negative margins in at least two places, namely the title and subtitle classes that are not also "is-spaced"

Negative margins raise all sorts of alarm bells in my head, as I learned that the only time to use them is if you want to overlap a div with a previous div - which I doubt is the goal when using titles and subtitles?

I know I can just override the variable, but why was this choice made, and is there no better solution? 

We stumbled across this when adjusting the header sizes in our derived theme, and were wondering about this when our headers suddenly started overlapping.

**Comment by jgthms** [comment]
So this negative margin only appears when you either have `.title` followed by a `.subtitle` or the opposite. It's to remove the gap between both, as it looks better to remove this gap when they're combined.

Compare this:
![image](https://user-images.githubusercontent.com/1254808/94259986-4c789600-ff27-11ea-8f57-ff8f360f86f2.png)

To this:
![image](https://user-images.githubusercontent.com/1254808/94260000-539fa400-ff27-11ea-9012-63f673f42904.png)

It's an opinionated decision but you can reverse it by setting `$subtitle-negative-margin` to `0`.

**Comment by steffchep** [comment]
Thanks for the response, I figured out about the variable - just seems weird to have negative margins by "default" anywhere.

**Comment by jgthms** [comment]
No worries. Hope it helped.
