### ISSUE TITLE
Margin m-* classes are missing in Bulma 0.9.0 version of the css

### ISSUE THREAD

**Issue by cbmgit** [jgthms/bulma#3124]
This is about **Bulma**.

It's a bug. CSS classes are missing in 0.9.0 version of bulma file.

### Overview of the problem

It looks like m-* classes are missing from the 0.9 css files. I have spent aroung 30 min to find the issue. I dont know if it left it on purpose or it's just got missed.

![image](https://user-images.githubusercontent.com/40800907/94366841-4c7bc000-00f8-11eb-87ed-2c3315f29fc0.png)

![image](https://user-images.githubusercontent.com/40800907/94366831-45ed4880-00f8-11eb-807f-3ac9ed511823.png)

https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.css

**Comment by goodbyte** [comment]
Odd... it seems that both the npm and cdn version are wrong.
Use the raw github one in the meantime
[https://raw.githubusercontent.com/jgthms/bulma/master/css/bulma.min.css](https://raw.githubusercontent.com/jgthms/bulma/master/css/bulma.min.css)

**Comment by cbmgit** [comment]
Thank you i will use the raw github one.  What if many classes are missed :).. Loved the Bulma, is the best css framework with almost zero learning curve.

**Comment by jgthms** [comment]
Out in `0.9.1` just now.
