### ISSUE TITLE
www. origin dns cloudflare error

### ISSUE THREAD

**Issue by marc-maurer** [jgthms/bulma#3125]
Hi,
if i visit bulma with www prefix (https://www.bulma.io/) it displays an "Error 1016 Origin DNS Error".  Without the www prefix its working fine.

I think there is some kind of configuration missing.

**Comment by superDuperCyberTechno** [comment]
Probably intended as the www-prefix is nonsensical and obsolete these days. I personally never have it enabled.

**Comment by marc-maurer** [comment]
I just noticed it because some had a wrong link on his website on the footer.

I agree that the prefix is outdated but a redirect would be nice.

**Comment by jgthms** [comment]
I thought I’d enabled the redirect. Let me check.

**Comment by marc-maurer** [comment]
![image](https://user-images.githubusercontent.com/19869755/104893954-5c076900-5974-11eb-8978-8a0d7832bc4a.png)
still not working

**Comment by jgthms** [comment]
Should be fixed now: https://www.bulma.io/
