### ISSUE TITLE
tabs styles without `ul` `li`

### ISSUE THREAD

**Issue by wildfrontend** [jgthms/bulma#3129]
maybe can use className instead

because it cant be use by `NavLink` in React

likes ,i want use `tabs` class style NavLink, it will not work
```
<div class="tabs">
  <ul>
    <li class="is-active"><a>Pictures</a></li>
    <li><a>Music</a></li>
    <li><a>Videos</a></li>
    <li><a>Documents</a></li>
  </ul>
</div>
```
but styled by class is more flexible
```
<div class="tabs">
     <NavLink activeClassName="is-active" className="tabs-item">Menu</NavLink>
</div>
```

**Comment by jgthms** [comment]
You can achieve it by setting the active class name on the parent element. Example: https://stackoverflow.com/questions/35053161/how-to-set-activeclassname-for-wrapper-element-of-link-or-indexlink-in-react-rou/35080727

**Comment by wildfrontend** [comment]
https://stackoverflow.com/a/57199037

thanks use innerRef can be deal with this case
