### ISSUE TITLE
Documentation for helpers not sufficient

### ISSUE THREAD

**Issue by RasdanJames** [jgthms/bulma#3133]
This is about the Docs.

### Overview of the problem

This is about the Bulma **Docs**

### Description

The documentation for helpers isn't very helpful in that many are missing or simply not described. This has been an ongoing problem. The Changelog from 0.9 to 0.9.1 lists:
#3047 Flexbox helpers but it doesn't say what those helpers are. So I don't have a good idea whether I should upgrade from 0.9.0 to 0.9.1.

Please update the documentation to reflect what the actual helpers are.

**Comment by jgthms** [comment]
Ah sorry, the documentation exists but was not published yet since 0.9.1 hadn’t been released yet. Thanks for the reminder. Will publish the docs ASAP.

**Comment by RasdanJames** [comment]
Thank you sir!

**Comment by sierikov** [comment]
If this issue is resolved, please close it.

**Comment by RasdanJames** [comment]
I don't think it is yet, I don't see the 0.9.1 tags under helpers to know what the new helpers are. So I don't think it's been done yet.

**Comment by rjcorflo** [comment]
Yeah, the Flex helpers doc is accesible on https://bulma.io/documentation/helpers/flexbox-helpers/ but there is no link at this moment in the helpers page.

**Comment by jgthms** [comment]
Fixed.
