### ISSUE TITLE
Docs: Tag element missing alignment examples.

### ISSUE THREAD

**Issue by djizco** [jgthms/bulma#3137]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.9.1]

### Description

The Docs for the **tags container** is missing examples for the alignment modifiers `is-centered` and `is-right`.

https://bulma.io/documentation/elements/tag/#list-of-tags

### Expected behavior

Expect examples or description of the alignment modifiers.

### Actual behavior

Documentation Missing

**Comment by hardik2901** [comment]
Can I work on this?

**Comment by djizco** [comment]
I've found some more classes that are either missing documentation, deprecated or intentionally left out:

a.box
a.tag
.tags .is-centered, .is-right
.field is-narrow has-addons-fullwidth
.table td, th: .is-selected, .is-narrow, .is-vcentered, and colors
.input is-active, is-fullwidth, is-inline
.hero-video
.hero-buttons
.menu .is-small, .is-medium, .is-large
.navbar .is-top-desktop, .is-bottom-desktop, .is-top-touch, is-bottom-touch
.navbar-tabs
.navbar-content
.header
.number
.highlight
.loader

**Comment by hardikvats** [comment]
Can i know, how will this respository on my local machine after cloning it to that? There is django in that but i wasn't able to loacate any .py file. Any help regarding this will be highly appreciated
