### ISSUE TITLE
customize background through sass variables

### ISSUE THREAD

**Issue by scottgrayson** [jgthms/bulma#314]
- [x] This is about the Bulma **CSS framework**
- [x] This is about the Bulma **Docs**
- [x] I'm using Bulma **version** [0.1.2]
- [x] My **browser** is: Chrome
### Description

Bulma seems opinionated towards a white background. What are the steps to make a site with a grey background?
##### Notes:
- Light grey is the default background

```
$body-background: $grey-lighter !default
$background: $grey-lighter !default
```
- but components like nav and section use white backgrounds: https://github.com/jgthms/bulma/blob/master/sass/components/nav.sass#L101
- I can make my site white easy enough with

```
$body-background: white
$background: white
```
- but to create a grey background would I need to override some of the components' backgrounds?
### Expected behavior

I expected the component backgrounds to use the $background or $body-background. Or for the components to be transparent. What is the advantage of setting them all to $white?
### Actual behavior

By default, If i do not cover my site in full width components, i get grey sides and white content
![image](https://cloud.githubusercontent.com/assets/7796074/18753900/cef72d12-80b4-11e6-81c4-a458d0e798ff.png)

**Comment by jgthms** [comment]
`$background` is simply a shortcut to have a light grey background. It's not meant as the background of all components.
