### ISSUE TITLE
Dropdown content is bounded by a parent card

### ISSUE THREAD

**Issue by gsvarovsky** [jgthms/bulma#3145]
This is about **Bulma**.
It is a change of behaviour in Bulma 0.9.1 since 0.9.0.

### Overview of the problem
This is a **Sass** issue: I'm using version [0.9.1]

I am sure this issue is **not a duplicate**.

### Description
If a dropdown is used in a card, the dropdown content is bounded by the card.

This is caused by the default value of the new variable `$card-overflow`

### Steps to Reproduce
1. Put a dropdown menu in a card, such that the dropdown content would go beyond the bottom of the card (I used`is-hoverable`)

### Expected behavior
<img width="628" alt="Screenshot 2020-10-07 at 14 34 00" src="https://user-images.githubusercontent.com/19226962/95337839-2ac5ca00-08aa-11eb-8e3e-2239f6535d4b.png">

Dropdown content shows fully.

### Actual behavior
<img width="634" alt="Screenshot 2020-10-07 at 14 24 28" src="https://user-images.githubusercontent.com/19226962/95337692-07028400-08aa-11eb-9405-e4481078e28a.png">

Dropdown content beyond the bottom of the card is hidden.

**Comment by jgthms** [comment]
Good point. I didn't realise the overflow would be an issue. It was introduced to allow the card to have rounded corners. There might be a workaround.

**Comment by gsvarovsky** [comment]
Sorry, yes, forgot to mention, I just added `overflow: visible` as a workaround on my page.

**Comment by jgthms** [comment]
I mean there is a way to add rounded corners to the card without using `overflow: hidden`, so that you don't need this workaround. 

I will add it to the next release.
