### ISSUE TITLE
Upgrading from 0.8.2 to 0.9.1 breaks gaps / widths

### ISSUE THREAD

**Issue by simplenotezy** [jgthms/bulma#3149]
This is about **Bulma & the Docs**

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** 0.8.2 -> 0.9.1

### Description

When upgrading from version 0.8.2 to 0.9.1 the website changes gaps/layouts changes.

I have been unable to find anything in the changelog or docs describing how I could revert to the previous setting.

Example:

![ezgif-5-10ba2dc9cebf](https://user-images.githubusercontent.com/3786627/95690407-dd35be00-0c17-11eb-8766-a872db8bc32c.gif)

**Comment by simplenotezy** [comment]
Time flew by, and decided to postpone upgrading since I wrote https://github.com/jgthms/bulma/issues/3073 - an issue I totally forgot about. This time I figured out I needed to add `@import '~bulma/sass/helpers/_all.sass';` instead of replacing it by `@import '~bulma/sass/base/_all.sass';` - so that looks good now, thanks ;)

But this is still an issue though; the gaps being different.

**Comment by jgthms** [comment]
It might be an issue with the `container`. The max-width should be `1344px` on large screens:
![image](https://user-images.githubusercontent.com/1254808/95693016-e9bf1400-0c21-11eb-8e81-69c53cdc69a0.png)

Can you check the value?

**Comment by simplenotezy** [comment]
Thanks. Thinking about it actually the new 0.9.1 version looks better (a bit wider)
