### ISSUE TITLE
[Request feature]

### ISSUE THREAD

**Issue by lucasdavidferrero** [jgthms/bulma#3151]
This is about **Bulma | the Docs**.

Is it a bug/feature/question or do you need help? 

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Hi, It would be nice if we can add a generic Loader since is very useful when you request data when you enter a route.

**Comment by VishwaJay** [comment]
There is an additional page loader for Bulma (as a separate file by @Wikiki on their own repo).

I've downloaded the SASS file, `@import`-ed the file into my customized Bulma file, and it works smoothly per the instructions (which you must follow from BOTH docs to get them to work).

https://github.com/Wikiki/bulma-pageloader 

The Bulma pageloader repo on Github will give you some basic functionality like you describe. Just be sure to read the instructions on both Bulma and this separate page loader separately.
