### ISSUE TITLE
Different column sizes on desktop, tablet or mobile

### ISSUE THREAD

**Issue by Jurrevandenberg** [jgthms/bulma#3157]
This is about **a question**.
Is it a bug/feature/question or do you need help?

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I am using bulma's grid system to make column blocks. For example I have 4 div's next to eachother and each div has column is-3 is-offset-0 as its class. My question is how can I show these div's on tablet 2x2 and on mobile 1x1? Mobile is working but I can't get it working on tablet. 
In the picture you see 4 columns next to eachother, that is what I want on desktop but on tablet only I want them to show like 2 columns per row.

Does anyone know how to do this?

![image](https://user-images.githubusercontent.com/49535945/96629745-56b66600-1314-11eb-8689-e0fd5ccd49c1.png)

**Comment by spencerfai** [comment]
Hey @Jurrevandenberg - I think you're looking for https://bulma.io/documentation/columns/responsiveness/#different-column-sizes-per-breakpoint. This gives pretty granular control over column sizes on each breakpoint. Hope this helps!
