### ISSUE TITLE
Vertical tables

### ISSUE THREAD

**Issue by Norgul** [jgthms/bulma#3161]
This is about **Bulma** /feature/question 

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.8.2] 
My **browser** is: Chrome 

### Description

Is there an option (or roadmap plan) for vertical tables? Mobile table looks really off when in horizontal layout.

Thank you

**Comment by jgthms** [comment]
Do you have an example?

**Comment by Norgul** [comment]
Sure, take a look [here](https://medium.com/appnroll-publication/5-practical-solutions-to-make-responsive-data-tables-ff031c48b122) under "Transformed" section.

**Comment by Norgul** [comment]
Any news about this @jgthms ?
