### ISSUE TITLE
Javascript changed CSS for button not updating on screen

### ISSUE THREAD

**Issue by camillo777** [jgthms/bulma#3166]
Bug

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1
My **browser** is: Chrome Version 86.0.4240.111 (Official Build) (x86_64)

### Description

If I change add/remove a CSS class with Javascript for button, class is correctly added/removed, but no change is visible on screen (no refresh?).
If I click on another button (for example), the change gets visible.

### Steps to Reproduce

Click on Button 1 to toggle "is-outlined" class to the button.
Nothing happens to Button1, but class is correctly added to CSS element.
Now click on Button2, Button1 now shows outlined, as stated by the "is-outlined" class, but Button2 stays the same.
If you click again on Button1 now Button2 gets outlined on screen.
Visibility Toggle works OK.

Jquery example
https://jsfiddle.net/wu9qxf0j/4/

Cash JS example
https://jsfiddle.net/aswn3o7f/2/

### Expected behavior

Button should become outlined when clicked.

### Actual behavior

CSS Class is added/removed but there is no change on screen

**Comment by lionzeye** [comment]
The lack of a visible change is due to the fact that the button is still in its focused state after clicking, thus applying the default background color for .button.is-primary.is-outlined:focus

**Comment by jgthms** [comment]
> The lack of a visible change is due to the fact that the button is still in its focused state after clicking, thus applying the default background color for .button.is-primary.is-outlined:focus

That is the correct answer. The button when clicked has the `:focus` state (that's the default behaviour of browsers). And in Bulma, the outlined `:focus` state is similar to the `:hover` one, as in it has a background color.

Hope it helps.

**Comment by camillo777** [comment]
Thank you, but... So what is the solution to have the correct behavior?

**Comment by lionzeye** [comment]
@camillo777 bulma honors the default button behaviour in this case. You can remove the focus programatically https://jsfiddle.net/8zfge3ok/ or use an element that's probably better suited for this use case https://wikiki.github.io/form/switch/
