### ISSUE TITLE
responsive grid

### ISSUE THREAD

**Issue by Redani** [jgthms/bulma#3167]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Hi, I'm new to Bulma, switching from vuetify to Buefy.
I have a grid of 4 columns displayed in 2 lines for desktop, but on mobile, I want my column 3 and 4 to be in the same line but it doesn't seem to be working (attached image).
I know i can add a new `div.columns.is-mobile` but I don't want to use all the time nesting columns for that.
Any recommendation?

Thanks

<img width="1440" alt="Screen Shot 2020-10-31 at 18 47 54" src="https://user-images.githubusercontent.com/328526/97786346-39eb1f80-1bab-11eb-8980-91f4bdd29c19.png">

**Comment by jgthms** [comment]
Try adding `columns is-mobile` on your columns container.

**Comment by Redani** [comment]
adding `columns is-mobile` will cause column 1 and 2 to be in 1 row on mobile :/

**Comment by Redani** [comment]
So, any idea how to solve that?

Also about the Columns gap, as per the documentation https://bulma.io/documentation/columns/gap/ we can use Variable gap which is AMAZING :) however I find it very unfortunate that only the right and left padding change :/ how can i do to make all paddings change to have a better and aligned grid?

**Comment by jgthms** [comment]
Try this:

```html
<div class="columns is-mobile is-multiline">
  <div class="column is-6-tablet is-12-mobile">
    <p class="notification is-primary">First column</p>
  </div>
  <div class="column is-6is-tablet is-12-mobile">
    <p class="notification is-primary">Second column</p>
  </div>
  <div class="column is-8">
    <p class="notification is-primary">Third column</p>
  </div>
  <div class="column is-4">
    <p class="notification is-primary">Fourth column</p>
  </div>
</div>
```

**Comment by Redani** [comment]
Nice, it worked thanks :) but is that the way you recommend to do or better to use nested columns?

And please what about the column gap padding?

**Comment by jgthms** [comment]
You can use nested columns too but I'd recommend using a single set of columns like this.

If you want the vertical gap to change as well add this to your CSS:

```css
.columns.is-variable .column {
  padding: var(--columnGap);
}
```

**Comment by Redani** [comment]
Great, thank you so much 🙏
Have a lovely evening.
Cheers
