### ISSUE TITLE
Bulma colors v0.2.0

### ISSUE THREAD

**Issue by core01** [jgthms/bulma#317]
*This is about the Bulma **CSS framework**

What happens? The older version 0.1.2 looks better than current. Current version is cutting my eyes.
Please add a transparent colors!!!!!
I know, i can change all colors in sources, but you had a good color-theme from the box.

+1if you are think so

**Comment by ChaseGiunta** [comment]
Have to agree. Really does hurt readability.

**Comment by jgthms** [comment]
I believe the green shade needs some work in terms of readability.

Here are the previous colors for those who want it:

```
$blue:      #42afe3
$green:     #97cd76
$orange:    #f68b39
$purple:    #847bb9
$red:       #ed6c63
$turquoise: #1fc8db
$yellow:    #fce473
```

**Comment by core01** [comment]
@jgthms when i looking for CSS Framework to my new project, i  choose Bulma, because Bulma has beautiful and unique element colors from the box, сompared with the bootstrap or uikit and other frameworks. 
I'm not Frontend developer, it  is hard to me, to write CSS code on SASS/LESS.

But no matter what Thank YOU for this framework!

**Comment by jgthms** [comment]
Before and after

![before](https://cloud.githubusercontent.com/assets/1254808/18816802/799f3a30-8348-11e6-91da-a0904fddcb0e.png)

![after](https://cloud.githubusercontent.com/assets/1254808/18816793/484b21ce-8348-11e6-9113-12393ab48cc5.png)

**Comment by core01** [comment]
Before:
![Before](https://pic.rosa.pro/uploads/25.09.2016_002.png)
After:
![After](https://pic.rosa.pro/uploads/25.09.2016_003.png)

New colors are too bright and with white text cut eyes

**Comment by ChaseGiunta** [comment]
@core01, while we may disagree with his new color theme choice, @jgthms has every right to change the color theme as he sees fit. It's his framework after all.  Feel free to use values he provided above or fork the project.

Thanks for the color tweak @jgthms

**Comment by jgthms** [comment]
All the colors have actually a **better contrast ratio** score than the old ones. Example for green:

* before http://leaverou.github.io/contrast-ratio/#white-on-%2397cd76
* after http://leaverou.github.io/contrast-ratio/#white-on-hsl%28141%2C%2071%25%2C%20%2048%25%29

Same for the body text.

**Comment by ChaseGiunta** [comment]
@jgthms contrast ratio != readability. The gripe is somewhat two-part: 1) readability 2) "safe" . By "safe", I mean your new choice in bright neon colors will undoubtedly result in a higher percentage of framework adopters changing the default colors to something less neon, bright, unsafe for their project.

**Comment by duzhipeng** [comment]
I guess @jgthms use the Retina screen (MBP) to do work.If you use that,the colors of current version are not so bad.But under that kind of displaybut(DELL P2214H 21.5 )  is cutting my eyes.

**Comment by jgthms** [comment]
I use my MBP but also a Dell screen, and it looks great on both.

**Comment by SEAPUNK** [comment]
I updated today, and I'm agreeing with @core01. I have a dual monitor setup (different monitors), and while on one it looks _mostly_ alright, the new primary color on the other monitor just gives me a headache.

**Comment by SEAPUNK** [comment]
The primary color could also benefit from another tweak to help differentiate between the "success" color:

![](http://i.imgur.com/jC4KmAU.png)

vs

![](http://i.imgur.com/FqDrYYj.png)

**Comment by core01** [comment]
I would like to apologize @jgthms, I hurried up with the creation of this issue and now i realize that. Bulma is the best and new flexbox CSS Framework which use SASS.
Thank you @jgthms for your JOB!

P.S.:
I foollow @jgthms advice with [redefine colors](https://github.com/jgthms/bulma/issues/317#issuecomment-249424444) and also others styles.
Also i upgrade template on one website in production. Bulma is great.
