### ISSUE TITLE
Feature request: Make navbar work on mobile without JS

### ISSUE THREAD

**Issue by ptmkenny** [jgthms/bulma#3170]
Bulma does not include JS, so at present a small amount of JS is required to get the hamburger menu to work on mobile. 

However, there are [techniques for making mobile menus in pure CSS](https://medium.com/@heyoka/responsive-pure-css-off-canvas-hamburger-menu-aebc8d11d793), which would be nice to have in Bulma so that the mobile menu works even if JS is disabled in the browser.

**Comment by gfrcsd** [comment]
I was going to open a pull request for that one as it seemed like a no brainer, but the caveats are really non-negligeable 👀 

I would argue that the current approach of not providing any JS or CSS implementation is the correct one, leaving that liberty to the developer

**Comment by Frits1980** [comment]
Is there at least a link to workable code, and a warning? Because as a non-developer it was hard to find out that it does not work out of the box and never will. How can I make it work?

**Comment by matthewdarwin** [comment]
Sample javascript is included with the documentation https://bulma.io/documentation/components/navbar/

**Comment by Frits1980** [comment]
Wow, that was a fast reaction! And apparently I'm blind, because I totally missed the javascript part. Had to use the browsers find function to actually find it. But thanks, I can work with that.
