### ISSUE TITLE
There should be a class "is-ghost" for buttons as stated in the docs.

### ISSUE THREAD

**Issue by daniel-lenz** [jgthms/bulma#3171]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** [0.9.1]

### Description
button class "is-ghost" is missing.

### Expected behavior

There should be a class "is-ghost" for buttons as stated in the docs.
https://bulma.io/documentation/elements/button/

### Actual behavior

There is no class "is-ghost" for buttons.

**Comment by service-paradis** [comment]
Looking at the [commit](https://github.com/jgthms/bulma/commit/e9389a982195de66380400c701fb2f1689d45e05), it will be available in the next release (0.9.2)
