### ISSUE TITLE
[Feature] Allow is-static chaining with color classes and disabled prop

### ISSUE THREAD

**Issue by marcebdev** [jgthms/bulma#3177]
This is about **Bulma**.
It is a feature request to hopefully help improve styling.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.1]
I am sure this issue is **not a duplicate**? Yes

### Description
Combining `.is-static` with another color class for instance as with `.is-primary` and `.is-disabled` or `.is-light` does not produce complementary behavior as `.is-static` overrides the color class' property.

#### Why?
1) For better flexibility and consistency I think it would make sense to have `is-static` be properly chainable with color classes as well as with `is-light` and `disabled` so developers can use it in combination to achieve a specific desired effect.`

2) I believe `disabled` used to have this issue (not currently able to reproduce it) where this opens the door for color pallets that are hardly readable which is poor for accessibility, where it is difficult for any user to read.

### Steps to Reproduce

1. Add the `is-static` class along with a color class such as `is-primary` to any compatible element.

### Expected behavior

Scenario 1:
Applies static's `pointer-events` and `box-shadow` properties while matching with the selected color palette.

Scenario 2:
Applying `<class="is-static is-primary" disabled>` treats the button like `<class="is-static disabled>` but with the additional `is-static` properties so that there would be no `pointer` or `box-shadow`. These should work together because for one it causes it to be unreadable and a user might want an element to appear with the custom shaded disabled styling just without any `pointer-event`. 

### Actual behavior

Scenario 1:
For instance styling, a button with `"is-primary is-static" overpowers `is-primary`'s color palette. 

scenario 2:
Styling a button as `<class="is-static is-primary" disabled>` keeps the chosen color palette class but applies `is-static`'s `color` property which makes it unreadable.

**Comment by Kncarrier** [comment]
I agree that the proposed functionality would be consistent with the rest of Bulma. The example of `is-disabled` with colors shows that there is use case here for `is-static` to be combined with color classes. In my case, I don't want to fully disable the button (shows the unclickable icon on hover) but want to disable pointer events in certain cases.
