### ISSUE TITLE
[bug] Inconsistent button border behavior when grouped with .has-addons class

### ISSUE THREAD

**Issue by marcebdev** [jgthms/bulma#3188]
This is about **Bulma**.

Is it a bug/feature/question or do you need help? : It is a Bug
If it's a bug, is it a browser bug?: No

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.1]
I am sure this issue is **not a duplicate**? None that I could find

### Description

When 3 or more buttons are grouped (with `.has-addons`) certain patterns result in visual border bugs. I've found one of these patterns to be a when button with a border style is grouped with buttons without a border style.

### Steps to Reproduce

Simple example with addons
```html
<div class="buttons has-addons">
  <button type="button" class="button is-primary is-light">
    <span>a</span>
  </button>
  <button type="button" class="button">
    <span>b</span>
  </button>
  <button type="button" class="button is-primary is-light">
    <span>c</span>
  </button>
</div>
```

Also in fields
```html
<div class="field">
  <div class="field-body">
    <div class="field has-addons">
      <p class="control">
        <button type="button" class="button is-danger is-light">
          <span>a</span>
        </button>
      </p>
      <p class="control">
        <button type="button" class="button">
          <span>b</span>
        </button>
      </p>
      <p class="control">
        <button type="button" class="button is-primary is-light">
          <span>c</span>
        </button>
      </p>
    </div>
  </div>
</div>
```

https://codepen.io/MarceDev/pen/NWrJqpM?editors=1011

### Expected behavior

The left border should not be visible.

### Actual behavior

The left border is visible while the right border is not visible, so this is inconsistent.

**Comment by jgthms** [comment]
Probably a z-index issue. Let me investigate.

**Comment by lionzeye** [comment]
Any grouped, bordered button should not have the negative margin-right of 1px I think.
https://github.com/jgthms/bulma/blob/0a1ef3c4fbf05d503ac626c7f53b1b7a93ac350b/sass/elements/button.sass#L316

**Comment by jgthms** [comment]
It's to overlap the borders, and prevent to have double borders all the way.

**Comment by lionzeye** [comment]
Yea, I think the solution can be similar to a pull request I made earlier for disabled inputs/selects. Any non-bordered, grouped button/control should have a lower z-index than a bordered one.

https://github.com/jgthms/bulma/pull/3105

**Comment by service-paradis** [comment]
I fixed this behavior in Buefy using `z-index` (https://github.com/buefy/buefy/pull/3032).
Would be great if the fix comes from Bulma instead!

**Comment by jgthms** [comment]
It’s not exactly the same as there is no selected button here. Just a combination of bordered and borderless buttons.

**Comment by service-paradis** [comment]
> It’s not exactly the same as there is no selected button here. Just a combination of bordered and borderless buttons.

Not the same issue, but the same behavior. Buttons at right are always "on top". In our case, we needed to change `z-index` for `is-selected`.

**Comment by lionzeye** [comment]
Proposed a fix in https://github.com/jgthms/bulma/pull/3192 Any additional testing/feedback is welcome!
