### ISSUE TITLE
Conditional Rendering of Icon with React not working

### ISSUE THREAD

**Issue by iamnckblr** [jgthms/bulma#3193]
This is about **Bulma**.

### Overview of the problem / Description
I want to build a login form with bulma css and react js. Therefore, in my login form, I wanted to conditional render a right aligned Icon based on the user's input (if it is valid or not). However, the icon is not changing (even tho the javascript variable is changed to the correct css class).

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.1]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Steps to Reproduce

1. Clone the following project: https://gitlab.com/iamnckblr/auth-server-ui
2. `yarn install` and `yarn start`
3. Open `http://localhost:3000`
4. Enter a valid email (e.q. asdfsdf@asdfadf.com)

### Expected behavior
Danger Icon changes to check icon

### Actual behavior

Danger Icon keeps showing.

**Comment by jgthms** [comment]
This seems to be an issue with your React code, or with how Font Awesome is loaded, but not with Bulma.
Bulma only provides the `icon` element as a container for your icon to load.

**Comment by iamnckblr** [comment]
Thanks for your response, didn't notice that bulma is really only providing a container. Solved the problem by using the official FontAwesome React Library (https://fontawesome.com/how-to-use/on-the-web/using-with/react). Now my code works!

**Comment by jgthms** [comment]
Glad you figured it out.
