### ISSUE TITLE
Request: Add Pagination CSS

### ISSUE THREAD

**Issue by leesiongchan** [jgthms/bulma#32]

**Comment by jgthms** [comment]
Please provide a description of the requested features. Do you want just previous/next? Numbers? Dots? Both? A dropdown?

**Comment by ahlee2326** [comment]
http://foundation.zurb.com/sites/docs/pagination.html

I am thinking we could build a pagination like foundation but on top leverage on the power of modifiers making it possible to change the pagination to different styling, possibly `is-round`, `is-space-between`, `is-space-around`, `is-large`, etc.

**Comment by jbrooksuk** [comment]
http://bulma.io/documentation/components/pagination/

Pagination is a thing?

**Comment by roukmoute** [comment]
It's from the begininng of the week.
I think it's an oversight.

**Comment by jgthms** [comment]
Yes, landed this week.
