### ISSUE TITLE
[question] Shouldn't Tabs with `is-fullwidth` have equal width?

### ISSUE THREAD

**Issue by scheinercc** [jgthms/bulma#3203]
This is about **Bulma**.

Is it a question for a proposed change.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.1]
My **browser** is: Firefox DevEdition
I am sure this issue is **not a duplicate**.

### Description & Steps to Reproduce
Under: https://bulma.io/documentation/components/tabs/#combining

Tabs set to `is-fullwidth` look in the example as if they were equal width, due to similar string lengths, while their lengths are indeed 264px, 248px, 254px, 288px:
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/817856/100571220-b7c75580-3326-11eb-89b8-efe165d454a8.png">

Changing the length of some of the strings to highlight what currently happens:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/817856/100571271-de858c00-3326-11eb-8d65-c5da95a5bf30.png">

Adding `flex-basis: 0;` to `.tabs.is-fullwidth li` looks better IMHO:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/817856/100571333-01b03b80-3327-11eb-94cf-08fd74782a4a.png">

https://github.com/jgthms/bulma/blob/0a1ef3c4fbf05d503ac626c7f53b1b7a93ac350b/sass/components/tabs.sass#L111
could then be shortened to `flex: 1 0 0`.

Maybe with `px` value (`flex: 1 0 0px`) as per: https://stackoverflow.com/questions/29503227/how-to-make-flexbox-items-the-same-size#29503264

**Comment by jgthms** [comment]
That’s a good point. It does look better if you have enough space. But you’re running the risk of having a tab with very little horizontal padding, making the text look crammed into the tab, which doesn’t look good either.

I think it’s preferable to let the developer decide the behaviour based on context.

**Comment by scheinercc** [comment]
> I think it’s preferable to let the developer decide the behaviour based on context.

Are you referring to a helper class or to simply adding it in "manually" to ones project's styles?

**Comment by jgthms** [comment]
I'd say manually, although a helper class for that behaviour could exist. The Bulma columns actually use the technique you mention.
