### ISSUE TITLE
limit scope of bulma only inside a specific div

### ISSUE THREAD

**Issue by peratik** [jgthms/bulma#3207]
This is about **Bulma** .
This is about **Question** .

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.9.1**

### Description

How can we limit scope of Bulma only inside a specific div ?

### Expected behavior

We want to use Bulma  inside a specific div: `<div id="app"></div>`
We don't want to apply Bulma  outside of that div.

**Comment by lionzeye** [comment]
I'd recommend using https://github.com/jgthms/bulma-start, updating bulma to the latest version and then wrapping the import inside #app like

```
#app {
  import "../node_modules/bulma/bulma";
}
```

and moving the html/body styles to the #app selector.
