### ISSUE TITLE
Tags with icon in a taglist should be aligned with others

### ISSUE THREAD

**Issue by elmatou** [jgthms/bulma#3209]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** 0.9.1
My **browser** is: Firefox,

I am sure this issue is **not a duplicate**

### Description

In a taglist, tag with close icon, should be aligned others

### Steps to Reproduce
See : https://codepen.io/elmatou/pen/WNGxGXe
```html
  <div class="tags">
    <span class="tag">One</span>
    <span class="tag">Two</span>
    <span class="tag">Three</span>
    <div class="tags has-addons">
      <span class="tag is-danger">Alex Smith</span>
      <a class="tag is-delete"></a>
    </div>
  </div>
```

### Expected behavior
Every tags should be vertically aligned

### Actual behavior

Tags with attached icons got vertical offset

**Comment by lionzeye** [comment]
I don't think nesting the .tags container in another .tags contrainer is supported.

Combining your code with the documentation:

```
<div class="field is-grouped is-grouped-multiline">
  <div class="control">
    <span class="tag">One</span>
  </div>

  <div class="control">
    <div class="tags has-addons">
      <span class="tag is-danger">Alex Smith</span>
      <a class="tag is-delete"></a>
    </div>
  </div>

  <div class="control">
    <span class="tag">Two</span>
  </div>

  <div class="control">
    <span class="tag">Three</span>
  </div>

  <div class="control">
    <div class="tags has-addons">
      <span class="tag is-danger">Alex Smith</span>
      <a class="tag is-delete"></a>
    </div>
  </div>
</div>

**Comment by elmatou** [comment]
You write about the documentation, even if I think we lost the simplicity of bulma in this case.
If maintainers do not want to filed this as a bug, it could be filed as an enhancement.

**Comment by jgthms** [comment]
You raised a good point. This should be fixed.
