### ISSUE TITLE
Complete basic navbar example uses superfluous CSS class

### ISSUE THREAD

**Issue by martinburger** [jgthms/bulma#3211]
This is about a minor **bug** in **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**.

### Description

The complete basic navbar example contains superfluous CSS class `burger`.

### Steps to Reproduce

1. Go to: https://bulma.io/documentation/components/navbar/#basic-navbar
2. Have a look at line 7 of the example's source code:

```html
<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
```

### Expected behavior

The hamburger button should not contain CSS class `burger`.

### Actual behavior

That button contains CSS class `burger` which seems to have no effect at all.

**Comment by jgthms** [comment]
That's a good point. Probably a residue of an older version of the documentation.
