### ISSUE TITLE
Where is the 0.9.2 release?

### ISSUE THREAD

**Issue by dbudwin** [jgthms/bulma#3212]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**

I am sure this issue is **not a duplicate**?

### Description

[The changelog references version 0.9.2](https://github.com/jgthms/bulma/blob/master/CHANGELOG.md#092) as the most recent version, but the latest package is version 0.9.1.  Am I simply missing something?

There is [a `next` branch](https://github.com/couds/react-bulma-components/commit/d607343209a173654fcca269f4f4924ce6071604#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) for `react-bulma-components` that references Bulma version 0.9.2 as well.  However, if I try to install version 0.9.2, I get an error.

`npm ERR! notarget No matching version found for bulma@0.9.2.`

### Steps to Reproduce

1. Try to install version 0.9.2

### Expected behavior

Bulma installs successfully

### Actual behavior

Errors because there is no Bulma 0.9.2 release even though it's mentioned in the changelog.

**Comment by lionzeye** [comment]
The changelog is built up while new changes come in, before the latest version mentioned is released. I'd agree that this isn't clear enough currently though. Adding a status to the versions in the changelog could solve this issue.
