### ISSUE TITLE
 The bulma page urgently needs an internal search engine

### ISSUE THREAD

**Issue by jhonatalex** [jgthms/bulma#3219]
This is about **Bulma | the Docs**.

### Description 

The bulma page urgently needs an internal search engine to be able to quickly locate what is needed since it is a bit cumbersome to navigate and find the topics that one is really going to need at the moment.

**Comment by service-paradis** [comment]
Take a look at https://github.com/jgthms/bulma/issues/3144#issuecomment-704243691
