### ISSUE TITLE
Thank you Devs

### ISSUE THREAD

**Issue by acupofjose** [jgthms/bulma#3222]
Just wanted to take a moment to thank y’all for this framework. I discovered bulma on accident about a year and a half ago and it has progressively become my go-to bootstrap. Truly, it has made my life (especially responsive web layouts) so much easier.

So thank you for all the hours you put into this project - I’m very appreciative of it!

A merry Christmas and happy new year to y’all!

**Comment by jgthms** [comment]
Thank you for the kind words, much appreciated! The community has really helped take Bulma to the next level, so thank you as well.

There are a lot of new things coming up for Bulma in 2021, so stay tuned. 😉
