### ISSUE TITLE
'is-hovered' not working it seems

### ISSUE THREAD

**Issue by BenjDG** [jgthms/bulma#3224]
This is about **Bulma**.

I think it is a bug.

I can recreate the bug in chrome, firefox, & edge.

### Overview of the problem

This may be about Bulma and/or the docs.  
I'm using Bulma **version** 0.9.1  
  
My **browser** is:  
Chrome  
  
Am I sure this issue is **not a duplicate**?  
I searched for 'hovered' and didn't see any open issues.  

### Steps to Reproduce

When I use the `<button class="button is-hovered">Hover</button>`
Also you can see that it doesn't seem to work on the docs website: https://bulma.io/documentation/elements/button/

### Expected behavior

I thought it would show a hovered style on the button.

### Actual behavior

No change from a 'normal' button.  
  
![hover](https://user-images.githubusercontent.com/10341013/103335348-43bdc180-4a3a-11eb-9934-83ed4d9ea2da.PNG)

**Comment by jgthms** [comment]
The change is subtle but the hover versions are very slightly darker. You can see it in action by actually hovering the "Normal" buttons.

**Comment by BenjDG** [comment]
Thanks for answering.  I'll have to figure out how to make it more drastic or have a talk with my eye doctor.

**Comment by ryankashi** [comment]
As a feature request, is there a way that we can apply the is-hovered effect to provide that subtle outline effect on other Bulma CSS elements?

For example, I would like to use JQuery to slightly modify the color of a div or object (i.e. the background of a Bulma CSS media object), and it would be great if I could just add the class "is-hovered" to my media object, or whatever element/class to apply Bulma CSS's slight color change!
