### ISSUE TITLE
.navbar-burger:hover doesn't include $navbar-item-hover-color

### ISSUE THREAD

**Issue by matthewdarwin** [jgthms/bulma#3227]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1
My **browser** is: Firefox

I checked the previous issues but couldn't find something similar.

### Description

.navbar-burger:hover doesn't include color: $navbar-item-hover-color  The hover cover is instead inherited from a:hover.  When the `navbar` has a dark background an `a` has a dark color, the combination is not readable.

### Steps to Reproduce

1. Change the bulma scss to have a dark background for the navbar

$blue: #336699;
$lblue: #00ffff;
$lgrey: #cccccc;
$xlgrey: #eeeeee;
$black: #000000;

$navbar-background-color: $blue;
$navbar-dropdown-background-color: $blue;
$navbar-item-hover-background-color: $blue;
$navbar-dropdown-item-hover-background-color: $blue;
$navbar-dropdown-item-active-background-color: $blue;

$navbar-dropdown-color: $white;
$navbar-dropdown-arrow: $white;
$navbar-item-color: $white;
$navbar-dropdown-item-hover-color: $lblue;
$navbar-item-hover-color: $lblue;

2.  Create a navbar according to the example. https://bulma.io/documentation/components/navbar/

```
      <a class="navbar-burger burger" data-target="navMenuMain">
        <span></span>
        <span></span>
        <span></span>
      </a>
```

3. Shink the screen, hover over the 3 line hamburger

### Expected behavior

The hover over color should be applied to the 3 lines as well as the X that make up the burger.

### Actual behavior

![image](https://user-images.githubusercontent.com/26171839/103445262-d4b1ba00-4c3f-11eb-811b-856430557bff.png)

![image](https://user-images.githubusercontent.com/26171839/103445252-c1065380-4c3f-11eb-88c7-5f3b03568839.png)

**Comment by jtommy** [comment]
Yes, right
