### ISSUE TITLE
Feature request: basic styles mode

### ISSUE THREAD

**Issue by inspector71** [jgthms/bulma#3232]
This is about **Bulma**.

### Overview

Addition of a mode (body class switch?) whereby basic browser defaults are not neutralized.

### Description

Understand many, perhaps most, want to use Bulma to start a project from a neutral, reset, full control state whereby all margins, font sizes and other simple basics - mostly default browser styles - are neutralized. Then use the declarative class approach.

**_Some may not want that_**. If you just want to throw Bulma at a single/simple page, for example, and get the basics of a page that may benefit from simplicity of some browser defaults whilst also allowing the addition of Bulma features later, such as notifications for one example, would it be possible to provide a variation of the default mode for such use cases?

### Steps to Reproduce

Take the basic https://bulma.io/documentation/overview/start/#starter-template

Add significant paragraphs, headings to generate a very simple page without any header, sidebar or other layout. Perhaps using lorum ipsum.

Remove arguably excess / unnecessary classes such as `h1 class=title`, `h2 class=subtitle`.

### Expected behavior

Basic browser default heading font styles - size, weight, margins - are maintained instead of an unreadable state.

### Actual behavior

Headings are indistinguishable from paragraph text.

**Comment by laurent22** [comment]
For those who end up on this post, you can get Bulma to apply default styles by wrapping your content in an element with `content` class.
