### ISSUE TITLE
[Bug] Breakpoints on grid layout is not working as expected - hiding content when it should not be hiding content

### ISSUE THREAD

**Issue by JunayedMizan** [jgthms/bulma#3234]
This is about **Bulma

Is it about Bulma or about the Docs? This is about Bulma
Is it a bug/feature/question or do you need help? It is a bug
If it's a bug, is it a browser bug? No. It is a bug in Bulma

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.1] 
My **browser** is: Google Chrom Version 87.0.4280.88 (Official Build) and Safari Version 14.0.1 (15610.2.11.51.10, 15610)

### Description
The breakpoints are not behaving as expected. 

In the example below, I expect the contents in the two columns to be displayed only on a desktop. On a mobile and tablet, it should be hidden.

This is not happening. Instead, on a desktop and mobile and tablet the contents of the column are hidden.

### Steps to Reproduce

Simple example to reproduce the issue:

      <div className="columns">
        <div className="column is-hidden-mobile is-hidden-tablet is-9-desktop">
          Only on mobile
        </div>
        <div className="column is-hidden-mobile is-hidden-tablet is-3-desktop">
          Only on Desktop
        </div>
      </div>

### Expected behaviour

I expect the contents in the two columns to be displayed only on a desktop. On a mobile and tablet, it should be hidden.

### Actual behaviour

This is not happening. Instead, on a desktop and mobile and tablet the contents of the column are hidden.

**Comment by jgthms** [comment]
It should be `is-hidden-tablet-only`.
