### ISSUE TITLE
Nav items overflows

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#324]
After this commit https://github.com/jgthms/bulma/commit/d7f34c9d0daf9fe5230420521c009e16c1c839e7 nav items, began to overflow surrounding container, which has a fixed width, due to `flex-shrink` being set to 0, in sass/components/nav.sass https://github.com/jgthms/bulma/commit/d7f34c9d0daf9fe5230420521c009e16c1c839e7#diff-8f41c89b51c546a9b8d98193bfee5ad1R18

I tried changing the flex-shrink value back to the default `flex-shrink: 1` which rendered, the items back to "normal".

I've got a fiddle that demonstrates it. https://jsfiddle.net/6anv8sm6/

I'm not sure, that just setting value of flex-shrink back to its default, is enough. Maybe this should be approached differently.

**Comment by rafaelrenanpacheco** [comment]
In 0.6 they are wrapped, so they don't overflow anymore.

@jgthms I guess this issue can be closed.

**Comment by Come2Daddy** [comment]
Tryed fiddle with last version of bulma: fixed. Can be closed.

**Comment by jeppech** [comment]
Awesome, I'm closing!
