### ISSUE TITLE
add default `backgroun-color  to` .pagination-link `

### ISSUE THREAD

**Issue by Valar103769** [jgthms/bulma#3243]
*feature*
could you add a variable to set default `backgroun-color:white` of `.pagination-link` ?

**Comment by Maagztech** [comment]
Inam very much begginer can i try this

**Comment by priyanshuSharma-WebDev** [comment]
> _feature_
> could you add a variable to set default `backgroun-color:white` of `.pagination-link` ?

will you give me more context about this problem?

**Comment by kanak22** [comment]
Can I try this problem?
