### ISSUE TITLE
Broken extends.sass import with release 0.9.2 

### ISSUE THREAD

**Issue by jimblue** [jgthms/bulma#3247]
Following breaking advice from latest release don't work:
> To fix duplicate imports, all Sass placeholders have moved from the utilities/mixins file to its own utilities/extends file. If you were importing them directly from utilities/mixins, you'll need to import utilities/extends instead.

The `control` mixin is require in [**extends.sass** ](https://github.com/jgthms/bulma/blob/c5edaea84f289b1e92f406b6d38de40970262e46/sass/utilities/extends.sass#L4) but it is not imported with `mixins.sass`. This mixin is located in `controls.sass`, so this file should also be imported.

**Comment by jgthms** [comment]
Good point. It’s highly unlikely to happen but it should still be fixed.

**Comment by paulmwatson** [comment]
I upgraded to 0.9.2, got the `@controls` error and then read about including `extends` and not `mixins` but I also had to move `controls.sass` above either;
```
...
@import "bulma/sass/utilities/derived-variables.sass";
@import "bulma/sass/utilities/controls.sass";
@import "bulma/sass/utilities/extends.sass";
@import "bulma/sass/helpers/color.sass";
...
```
