### ISSUE TITLE
Bulma 0.9.1 causing issues with body scroll lock

### ISSUE THREAD

**Issue by JunayedMizan** [jgthms/bulma#3250]
Is it a bug/feature/question or do you need help?
Bug with bulma 

It's happening in browser

### Overview of the problem

This is about the Bulma **CSS framework**
### Description

Let's say you have a button. When you click on the button a popup/modal is opened. When the modal/opens, the background content should not be scrollable. Only the modal should be scrollable. When you implement this feature with bulma. The issue I'm having is with the body scroll lock. When the modal is open, I'm still able to scroll the body. Only the modal should be scrollable.

I've created a simple example of my scenario on code sandbox `https://codesandbox.io/s/bulma-nextjs-contextual-routing-with-modal-9bifu?file=/pages/index.js`

After digging through bulma code base, it looks like these two lines in` bulma/base/generic.sass`
```
html
  overflow-y: $body-overflow-y
  overflow-x: $body-overflow-x
```

is causing the issue. After removing those two lines, it starts working.

### Expected behavior

When modal opens, background content should not be scrollable. Only the modal content should be scrollable.

### Actual behavior

The background content is scrollable

**Comment by jgthms** [comment]
Your `body` element has `overflow: hidden;`. Can't you put in on your `html` element instead?

**Comment by JunayedMizan** [comment]
It doesn't look like `overflow: hidden;` is causing the issue. Here is a codesandbox example of it working `https://codesandbox.io/s/bulma-nextjs-contextual-routing-with-modal-working-u9kyn?file=/pages/index.js`

In the working example, `overflow: hidden;` still exists and does't cause any issues. 

Am I doing something wrong? Is there anything I can do to the original code to get it to work so I can use `@import "bulma/bulma";` rather than importing individual modules.

**Comment by jgthms** [comment]
You can try either:

* `html { overflow: visible;}`
* `html { overflow: unset;}`
* `html { overflow: initial;}`

**Comment by JunayedMizan** [comment]
Thank you. Your above suggestion has worked.
