### ISSUE TITLE
Violation of the Content Security Policy directive

### ISSUE THREAD

**Issue by Octavia0509** [jgthms/bulma#3255]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1
My **browser** is: Google Chrome

### Description

Whenever I want to add an image anywhere on my page, it does not appear and a console error appears:
For example: Refused to load the image '**https://bulma.io/images/bulma-logo.png**' because it violates the following Content Security Policy directive: "img-src 'self' data:".

I have already researched some solutions on the internet, all without success

### Expected behavior

**A correctly displayed image**

### Actual behavior

**Console error appears**

**Comment by scheinercc** [comment]
This is not related to Bulma as far as I can see and would be better off on SO, but for what its worth:
Are you trying to load the Bulma logo straight from the Bulma website? Just upload it to your server and serve it from there.
Here some background on the CSP rule mentioned: https://content-security-policy.com/self/
