### ISSUE TITLE
Highlight.js has some sort of border

### ISSUE THREAD

**Issue by ravener** [jgthms/bulma#3258]
Hi, i'm trying to make a blog with markdown. I rendered the markdown inside a `<div class="content">` and have setup highlight.js on the browser for syntax highlighting, however something looks odd.

With Bulma: ![image](https://cdn.discordapp.com/attachments/455058727884554240/806537618291949603/Screenshot_20210203_192210.jpg)
Without Bulma: ![image](https://cdn.discordapp.com/attachments/455058727884554240/806537618489344010/Screenshot_20210203_192220.jpg)

How can I get it to lie flat in the page like in the second screenshot?

**Comment by ravener** [comment]
I solved this. I had to add the `hljs` class on the `<pre>` (my bad) to fill the background color correctly.

Then Bulma was applying a pretty big padding to `<pre>` tags so I just added my own CSS to adjust the padding.

**Comment by jgthms** [comment]
Actually, there was some `.highlight` styles in the Bulma CSS but it will be removed in the next release.
