### ISSUE TITLE
sticky navigation bar?

### ISSUE THREAD

**Issue by hridoy** [jgthms/bulma#326]
sticky nav bar already added? or  if added any docs help for sticky nav bar?

**Comment by VizuaaLOG** [comment]
This is currently a work in progress #367

**Comment by maarteNNNN** [comment]
`.nav {
    position: fixed !important;
    top: 0;
    left: 0;
    right: 0;
}`

This should give you a fixed nav

**Comment by ankitrg** [comment]
Will this work with `.navbar` too?

**Comment by VizuaaLOG** [comment]
I don't see why it wouldnt.

_Sent from my Htc HTC 10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ankitrg** [comment]
@VizuaaLOG yes, it works!

**Comment by liphiep** [comment]
.navbar { position: fixed !important; top: 0; left: 0; right: 0; z-index: 1} and margin to content.

**Comment by misterpoloy** [comment]
Is there any option to achieve `affix` like in ant.design?
https://ant.design/components/affix/
