### ISSUE TITLE
Support and promote to use button elements as buttons

### ISSUE THREAD

**Issue by remcohaszing** [jgthms/bulma#3261]
This is about **Bulma**. However, it applies to the docs as well.  
I consider this to be a bug.  
It’s not related to a specific browser.

### Overview of the problem

This is about the Bulma **CSS framework**  
I'm using Bulma **version** 0.9.2  
My **browser** is: Google Chrome 88  
I am sure this issue is **not a duplicate**

### Description

Bulma uses an anchor (`<a>`) as a button where a button element (`<button>`) can be used. Using a button as a button is generally preferred over repurposing another element.

Some example that come to mind:

It should be supported and promoted to use `<button>` for:

- `.breadcrumb` grandchildren
- `.dropdown-item`
- `.navbar-burger`
- `.navbar-item`
- `.navbar-link` (Used for as a navbar dropdown button)
- `.panel-tabs` children
- `.tabs` grandchildren

Typically this means adding the following css:

```css
outline: none;
```

Although some classes require additional styling to get rid of button defaults.

### Steps to Reproduce

N/A

### Expected behavior

To be able to use a `<button>` element to define user interaction.

### Actual behavior

Bulma forces me to either use an `<a role="button">` or to define custom CSS.

**Comment by jgthms** [comment]
Yes that is true. The button element should be favoured in the documentation. I just need to check that all elements can support it.
