### ISSUE TITLE
Hero-foot active tab text is white color in Chrome and cannot be read

### ISSUE THREAD

**Issue by ngrimaldo** [jgthms/bulma#3263]
This is about Bulma 

This is a question or maybe a bug.
### Overview of the problem

 I'm using Bulma **version** [0.8.0]
 My **browser** is: Google Chrome
 I am sure this issue is **not a duplicate**

### Description

The text of the "is-active" tab in the hero-foot > tabs section is not readable since it becomes white color similar to the color of the selected\active  tab. This didn't happen before so I'm not sure if some Chrome update affected it. 

### Steps to Reproduce

1. Go to the Documentation on the Layout -> Hero
2. Scroll to the a Hero that has a hero-foot with an item selected with class "is-active"
3. Observe that the text of the selected item is white and cannot be read.

### Expected behavior

Text of active item\tab should be readable.

### Actual behavior

Text of active item\tab is white and cannot be read. 

![image](https://user-images.githubusercontent.com/41707157/107692860-fe182980-6c72-11eb-82e1-85e131800d20.png)

**Comment by luispastendev** [comment]
in firefox it also happens it seems to be really a bug

**Comment by bundgaard** [comment]
Hi

What is the preferred way to inform that, we have also experienced this? Using the Emoji +1 or this kind of information.

Using Microsoft Edge (webkit) and also have this problem with the latest bulma@0.9.1 version.

**Comment by ngrimaldo** [comment]
For now, I'm getting around this by setting the color of the element containing the text and icon to #4a4a4a when the tab is active.
