### ISSUE TITLE
Wrapping text inside a button to prevent overflowing a column

### ISSUE THREAD

**Issue by asad-awadia** [jgthms/bulma#3265]
This is about **Bulma 

Is it a bug/feature/question or do you need help? 

Question

### Overview of the problem

 This is about the Bulma **CSS framework

I'm using Bulma **version** [0.9.1]
My **browser** is: firefox

 I am sure this issue is **not a duplicate**

### Description

 Description of the bug, enhancement, or question 

Long text inside a button causes the button to spill out from the column

Simple <p> text wraps correctly

### Steps to Reproduce

```
  <div class="hero-body">
            <div class="container">
                <div class="columns is-multiline">
                    <div class="column is-half">
                        <figure class="image is-square">
                            <img src="https://cataas.com/cat/says/hello%20world!">
                        </figure>
                    </div>
                    <div class="column is-half">
                        <div class="buttons">
                            <button class="button is-link is-fullwidth is-size-4-desktop is-size-5-mobile">
                                Martha J. Lewis - Private accountant
                            </button>

                                <button class="button is-primary is-size-4-desktop is-size-5-mobile">
                                    Priscilla M. Wareham - Instrumentation technician Priscilla M. Wareham -
                                    Instrumentation technician
                                    Instrumentation technician

                                </button>

                            <button class="button is-info is-fullwidth is-size-4-desktop is-size-5-mobile">
                                Jeff H. Crowell - Toolmaker
                            </button>

                            <button class="button is-success is-fullwidth is-size-4-desktop is-size-5-mobile">
                                Virginia D. Black - Dressmaker
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
```
### Expected behavior

The text should stay inside [maybe get smaller?] the button and the button should get longer/taller instead of going off screen wider

### Actual behavior

Button becomes super wide

<img width="837" alt="Screen Shot 2021-02-15 at 12 15 30 AM" src="https://user-images.githubusercontent.com/6923282/107907949-ec5cad80-6f22-11eb-94ed-2395019cf5af.png">

**Comment by asad-awadia** [comment]
@jgthms any suggestions?

**Comment by pratikrpawar** [comment]
use button-wrap-text class

**Comment by asad-awadia** [comment]
@pratikrpawar I don't see any class like that

Also, doesn't seem to work

**Comment by asad-awadia** [comment]
```
  .button {
        height: 100%;
        white-space: normal;
    }
```

this seems to work

**Comment by s-gbz** [comment]
> ```
>   .button {
>         height: 100%;
>         white-space: normal;
>     }
> ```
> 
> this seems to work

I'd suggest `height: max-content;` to prevent unintentional oversizing.
If applied to a `.button`, `white-space: inherit` should do the job (test the available options in your browser's inspector if in doubt).

In total this is I what I came up with:

```css
.wrap-button-text {
    height: max-content;
    white-space: inherit;
}
```
