### ISSUE TITLE
Responsive tiles

### ISSUE THREAD

**Issue by stanolacko** [jgthms/bulma#3273]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.9.2**

### Description

Tiles are mot responsive.

### Steps to Reproduce

1. Open documentation https://bulma.io/documentation/layout/tiles/#example
2. Resize browser to max width 768px

### Expected behavior

Allow to set tiles responsive, like for columns

### Actual behavior

Tiles working as designed (parent / child etc) only on large devices.
All devices with width <= 768px have tiles in one column, each one below previous one.

**Comment by akselele** [comment]
Any updates on this? I've seen issues dating back to 2018 asking for this feature, as well as a PR
