### ISSUE TITLE
How to change font families dynamically?

### ISSUE THREAD

**Issue by svdHero** [jgthms/bulma#3277]
This is a question about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.2
My **browser** is Chrome
This is a **Sass** issue: I'm using node-sass version 5.0.0

### Description

For customizing fonts, I use node-sass and overwrite Bulma variable such as `$family-sans-serif` or `$title-family` as described [in the doc](https://bulma.io/documentation/customize/with-node-sass/).

My problem is that my company wants to support different languages like English, Chinese and Russian and we have corporate identity guidelines about which fonts to use for each language.

Is it somehow possible to dynamically change Bulma fonts?
As far as I understand it, SASS is a pre-compiler, so I cannot change  `$family-sans-serif` or `$title-family` at runtime. Thus, it seems as if I have to compile the whole Front-End app for each language separately and then run several instances, one for each language, which seems a bit strange. But I am new to SASS and still a Bulma beginner, so maybe there is a more practical approach?

Ideally a user would just use a dropdown menu for selecting his/her language and JavaScript and Bulma are doing their magic behind the scenes. Any ideas on how to achieve that?

**Comment by ecoztas** [comment]
This question is not about Bulma, Bootstrap, Foundation or etc. These are css frameworks so they styling web pages. You should change fonts dynamically for differet languages. You can do that with JS.

Firstly you should detect the language of the browser.

https://stackoverflow.com/questions/8199760/how-to-get-the-browser-language-using-javascript

Then you should change font for the language of the browser.

https://stackoverflow.com/questions/13757011/changing-fontfamily-conditionally

**Comment by jgthms** [comment]
If you are using Bulma, then the `font-family` is only set in 5 locations:

![image](https://user-images.githubusercontent.com/1254808/109141177-58c28280-7755-11eb-8ede-38c2832ff425.png)

So if you were to dynamically load a font family, you only need to apply to those selectors:

```
body,
button,
input,
optgroup,
select,
textarea,
code,
pre
```

If you had already set `$button-family`, `$title-family` or `$subtitle-family`, then also include these selectors:

```
.button,
.title,
.subtitle
```

**Comment by svdHero** [comment]
@ecoztas thank you for your answer and the links. I know that my question was not CSS-related per se. However, I was hoping to get advice on how to "inject" a dynamic font into Bulma easily, without having to manipulate the DOM manually.

@jgthms thank you for pointing me in the right direction and clarifying which DOM elements to search for.
