### ISSUE TITLE
"is-block" modifier class for buttons does not with <button> elements

### ISSUE THREAD

**Issue by thehydrogen** [jgthms/bulma#3282]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.1
My **browser** is: Google Chrome 88.0.4324.190 (Official Build) (64-bit)

### Description

When using a button element with the `button` class, the `is-block` modifier class doesn't change it.

### Steps to Reproduce

```
<button type="submit" class="button is-success is-block">Create</button>
```

### Expected behavior

The button should be the full width of the page.

### Actual behavior

The button's size does not change.

**Comment by ecoztas** [comment]
Bulma's `button` class is styled using flexbox. You can learn more about flexbox:

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox

You can use `is-fullwidth` class Instead of `is-block`.

For example:

```
<button type="submit" class="button is-success is-fullwidth">Create</button>
```

Or you can add `width: 100%` property to `is-block`.

```
.is-block {
    width: 100%;
}
```

**Comment by thehydrogen** [comment]
Thanks, @ecoztas
