### ISSUE TITLE
Customize Navbar burger dropdown background color

### ISSUE THREAD

**Issue by payne911** [jgthms/bulma#3284]
# Context

Similar problem as #1688, except I'm not sure I understand what I'm supposed to do. The provided doc link is hard for me to follow (sorry, I'm more of a backend dev). Is there a way to achieve what I want through CSS ?

My `navbar` :

![navbar](https://user-images.githubusercontent.com/38117856/110343651-b464f980-7ffa-11eb-9837-f867320807e6.png)

When `burger` appears and is toggled:

![burger](https://user-images.githubusercontent.com/38117856/110343770-d2325e80-7ffa-11eb-8f7c-7f80547e3636.png)

# Missing customization

* Not being able to modify the background color prevents users from seeing the "Settings" icon which is white
* The text isn't vertically aligned with the icons in the burger items

# Code

```html
  <!-- Navigation bar -->
  <nav class="navbar is-dark" style="z-index: 1">
    <div class="container">
      <div class="navbar-brand">

        <!-- Left-side buttons which are always displayed -->
        <a class="navbar-item" href="https://useful-forks.github.io/"
           onclick="ga_homeHeader();">
          <img src="assets/useful-forks-logo.png" alt="UsefulForks_logo" />
          <strong>&nbsp;&nbsp;Home</strong>
        </a>
        <a class="navbar-item" href="https://github.com/useful-forks/useful-forks.github.io" target="_blank" rel="noopener noreferrer"
           onclick="ga_githubHeader();">
          <img src="assets/github-white-icon.png" alt="GitHub_logo" />
          <strong>&nbsp;&nbsp;Open-Source Project</strong>
        </a>

        <!-- Dropdown button for smaller screens -->
        <div class="navbar-burger burger" data-target="uf-burger">
          <!-- Each `<span>` is a line in the burger icon -->
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="uf-burger" class="navbar-menu">

        <!-- Left-side buttons which will populate the Burger -->
        <div class="navbar-start">
          <a class="navbar-item" href="https://github.com/useful-forks/useful-forks#chrome-extension-wip" target="_blank" rel="noopener noreferrer"
             onclick="ga_chromeHeader();">
            <img src="assets/chrome-icon.png" alt="Chrome_logo" />
            <strong>&nbsp;&nbsp;Chrome Extension (WIP)</strong>
          </a>
        </div>

        <!-- Right-side buttons which will populate the Burger -->
        <div class="navbar-end">
          <a id="addTokenBtn" class="navbar-item"
             onclick="ga_openTokenHeader();">
            <img src="assets/settings-icon.png" alt="Settings" />
            <strong>&nbsp;&nbsp;Add an Access Token</strong>
          </a>
        </div>
      </div>
    </div>
  </nav>
```

**Comment by jgthms** [comment]
So the `navbar-menu` on small screens has a white background, even the dark version of the navbar. It's because if the `navbar-menu` also had a dark background, it would require the items in the navbar menu to change their color too for readability. It's definitely something that will be improved in the future.

As for the alignment of the icon, it's not due to Bulma. You can try using `vertical-align: middle` on your `<img>`.

**Comment by payne911** [comment]
With `vertical-align: middle` on my `<img>`:

![image](https://user-images.githubusercontent.com/38117856/110356055-ddd85200-8007-11eb-822d-deca4f49a2ee.png)
vs
![image](https://user-images.githubusercontent.com/38117856/110356080-e3359c80-8007-11eb-8172-ab89f10f165d.png)

We can actually see how the text isn't aligned exactly the same.

**Comment by jgthms** [comment]
For the icon I’d recommend using Flexbox actually. Bulma does provide helper classes for that.

**Comment by payne911** [comment]
> For the icon I’d recommend using Flexbox actually. Bulma does provide helper classes for that.

That? https://bulma.io/documentation/helpers/flexbox-helpers/

I must admit I wouldn't know how to use that thing.
