### ISSUE TITLE
has-text-centered-mobile doesn't center on mobile

### ISSUE THREAD

**Issue by s-gbz** [jgthms/bulma#3289]
This is about **Bulma**.
It could be a missunderstanding, but I believe it's a bug, because there're at least two people who expected different behaviour.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.9.2
My **browser** is: Firefox 86.0 Ubuntu, Responsively 0.15.0 (Chrome 83.0.4103.122)

I am sure this issue is **not a duplicate** (https://github.com/jgthms/bulma/issues/293 is the most related issue I could find).

### Description
I'd like to align a button group left on desktop and have it centered on sizes less than iPad.
As suggested in my original [StackOverflow question](https://stackoverflow.com/questions/66726993/bulma-how-to-align-an-element-left-but-center-it-on-mobile) `has-text-centered-mobile` should center the element.

Also, I'd like to avoid any custom css in order to learn using Bulma properly.

### Steps to Reproduce
```html
<footer class="section footer is-widescreen">
    <div class="container">
        <div class="columns">

            <div class="column ">
                <div class="buttons has-text-centered-mobile has-text-left-tablet">
                    <a class="button" target="_blank" href="https://deletefacebook.com/"><img src="/placeholder/icons/facebook-f.svg" alt=""></a>
                    <a class="button" target="_blank" href="#"><img src="/placeholder/icons/instagram.svg" alt=""></a>
                    <a class="button" target="_blank" href="https://twitter.com"><img src="/placeholder/icons/twitter.svg" alt=""></a>
                </div>
            </div>

            <div class="column has-text-centered has-text-right-tablet">
                <p class="subtitle is-6">&copy; {{ now.Year }} codeklasse</p>
                <a href="https://bulma.io">
                    <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="128" height="24">
                </a>
            </div>
        </div>
    </div>
</footer>
```

### Expected behavior
The buttons should be centered.

### Actual behavior
The buttons remain aligned left when in mobile view. 
![Screenshot from 2021-03-20 23-10-10](https://user-images.githubusercontent.com/23424538/111899608-090e6880-8a2e-11eb-93b2-97772f0a531d.png)

The css inspector applies the rule, but lacks power to enforce it.
![Screenshot from 2021-03-21 10-08-35](https://user-images.githubusercontent.com/23424538/111899560-addc7600-8a2d-11eb-987c-ada1fa8636b4.png)

---
Please let me know if I can provide further information. Thanks for creating and maintaining this awesome project!

**Comment by jgthms** [comment]
So `buttons` is using `display: flex`, so `has-text-centered` won't work here, because each `button`  is a flexbox item, not an inline one.

Try using `is-justify-content-center` instead.

**Comment by s-gbz** [comment]
Hi! Thanks for the suggestion. Trouble is that it doesn't align left on desktop though (looks like the first image in the StackOverflow question).

Do you have any idea how that might be fixed?

21.03.2021 13:37:18 Jeremy Thomas ***@***.***>:

**Comment by jgthms** [comment]
Ah yes, those helpers don't have a mobile-only version. You could add it manually in your Sass:

```scss
@include mobile {
  .your-buttons {
    justify-content: center;
  }
}
```

**Comment by s-gbz** [comment]
That works! Thanks a lot for your support :100: :heart: 
Feel free to close the issue.
I could also try to create a PR if you outline what to do.

**Comment by jgthms** [comment]
You're welcome.

Don't worry about a PR. I think those flexbox helpers should have responsive versions anyway, and there might be another issue open for that.
