### ISSUE TITLE
Font Awesome icon showing above nav menu

### ISSUE THREAD

**Issue by christippett** [jgthms/bulma#329]
### Checklist
- [x] This is about the Bulma **CSS framework**
- [x] I'm using Bulma **version** [0.2.1]
- [x] I am sure this issue is **not a duplicate**?
### Description

Font Awesome icons show above the nav menu on mobile.

![image](https://cloud.githubusercontent.com/assets/7218120/19013904/c745246a-883a-11e6-8b75-0907ade6fa94.png)
### Steps to Reproduce
1. Position a Font Awesome icon near the top of the page such that the nav menu on mobile will overlap.
### Expected behavior

The nav menu should appear above the page elements below it.
### Actual behavior

Font Awesome icon appears above the nav menu on mobile when the active.
### Proposed solution

The Font Awesome icon has a z-index of 4:

```
.control.has-icon > .fa {
    z-index: 4
}
```

Whereas the nav element has a z-index of 2:

```
.nav {
    z-index: 2
}
```

Propose to increase the z-index of the .nav element to a value greater than 4.

**Comment by jpagnano** [comment]
thank you very very much, I knew that was the simple fix. I just had no idea what the z-index value for icon was. Saved me loads of time! 👍
