### ISSUE TITLE
[Docs] Missing sidebars in /layout/ - Bug?

### ISSUE THREAD

**Issue by turbopixel** [jgthms/bulma#3290]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
My **browser** is: Mozilla Firefox (Windows and linux)
Screen resolution: 1920 x 1080px

### Description

Both sidebars are missing or hidden. Only the "Layout" section in the documentation is affected.

### Steps to Reproduce

Open 
* https://bulma.io/documentation/layout/section/
* https://bulma.io/documentation/layout/hero/
* https://bulma.io/documentation/layout/container/

### Expected behavior
Sidebar visible
![grafik](https://user-images.githubusercontent.com/15839724/112012150-3d1a8400-8b29-11eb-8f72-aff382a88cfd.png)

### Actual behavior
Missing sidebar (left and right)
![grafik](https://user-images.githubusercontent.com/15839724/112012049-270cc380-8b29-11eb-9432-1ce393e24402.png)

**Comment by jgthms** [comment]
It's actually intended. It's because some components (like the Hero) need to span the whole width of the page. So I need to remove the two sidebars from the flow. But you can still see them, and interact with them on hover. I added the dots to show the user where they are.

**Comment by T1mL3arn** [comment]
I would like to see this behavior on every page in the docs. I had to make some userstyle to hide the right sidebar and make the docs more usable with 1280x1024 monitor.
