### ISSUE TITLE
Feature Request: Waves effect to buttons

### ISSUE THREAD

**Issue by nh916** [jgthms/bulma#3292]
I was wondering if we could add a waves effect class that developers could add to their buttons to have a waves effect go through the button when it is clicked. I think this is better user feedback and better UX as it makes it very clear that the button has been pressed by the user. 

I thought something like this would be beautiful!

https://codepen.io/wiosloo/pen/GjxmEy

**Comment by jgthms** [comment]
There is no plan to add such a feature but you could create a Bulma extension for it to share with the community if you want.
