### ISSUE TITLE
Official Bulma website broken

### ISSUE THREAD

**Issue by svdHero** [jgthms/bulma#3305]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
My **browser** is: Firefox 87.0 (64-Bit)
I am sure this issue is **not a duplicate**? (at least I couldn't find any)

### Description

The official Bulma website seems to be broken. More precisely, the two subpages

- http://bulma.io/documentation/layout/hero/
- http://bulma.io/documentation/layout/section/

have a broken menu on the left:

![Bulma_Website](https://user-images.githubusercontent.com/24250824/113866727-f3c76700-97ad-11eb-82b9-e74010e598b1.png)

### Steps to Reproduce

Just visit the pages above.

### Expected behavior

A proper menu bar on the left like with the other subpages.

### Actual behavior

A broken menu that is collapsed and only shows bullets.

**Comment by jgthms** [comment]
It is the correct behaviour. See #3290
