### ISSUE TITLE
Align the second column right and the first column left.

### ISSUE THREAD

**Issue by p4ck3t0** [jgthms/bulma#3313]
This is about **Bulma**.
I need **help** because I have not found the function.

### Overview of the problem

This is about the Bulma **CSS framework**

Align the second column right and the first column left.

### Description

If I create these columns:

```html
<div class="columns">
  <div class="column">
    First column
  </div>
  <div class="column">
    Second column
  </div>
</div>
```
The  rendered html looks like this:

![1619386632267685836](https://user-images.githubusercontent.com/48812495/116010497-92155280-a61f-11eb-853f-9001588871c3.png)

When the HTML is rendered on a mobile device, first column is on top of the second column. I need the second column on top of the first column.

I can do this by making the first column on the right and the second column on the left, but how is it done?
This is wat I need:

```html
<div class="columns">
  <div class="column is-on-right">
    First column
  </div>
  <div class="column is-on-left">
    Second column
  </div>
</div>
```

Thank you for your help.

**Comment by Heroges** [comment]
```
<div style="display: flex; flex-direction: column-reverse;" class="columns">
  <div class="column is-on-right">
    First column
  </div>
  <div class="column is-on-left">
    Second column
  </div>
</div>```

**Comment by Heroges** [comment]
![Screenshot_20210502_135043_com teejay trebedit](https://user-images.githubusercontent.com/77005710/116804998-7cd38300-ab4d-11eb-950c-d769ad053dfb.jpg)
![Screenshot_20210502_135039_com teejay trebedit](https://user-images.githubusercontent.com/77005710/116804999-7e9d4680-ab4d-11eb-9fec-03ff692c72bf.jpg)
```html
<div class="columns">
  <div class="column">
    First column
  </div>
  <div class="column">
    Second column
  </div>
</div>
```
```css
.columns {
	display: flex;
	flex-wrap: wrap-reverse;
}
```
