### ISSUE TITLE
.has-shadow is not documented in the navbar page

### ISSUE THREAD

**Issue by darkylmnx** [jgthms/bulma#3315]
This is about the Bulma **Docs** 

### Description

I struggled to find the shadow class for the navbar and had to check the source code to find it.

### Expected behavior

`.has-shadow` to be documented in the docs.

### Actual behavior

Not in the doc.

**Comment by WilliamJohnsonJr** [comment]
Just pointing out that for some reason the PR did not get associated with this issue. This issue can probably be closed.
