### ISSUE TITLE
custom shades are returning as a whole map and not working properly

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [jgthms/bulma#3316]
Hi everyone
As there are certain prebuilt bulma shades given at utilities/derived-variables.sass

**Overview of the problem**
`$shades: mergeColorMaps(("black-bis": $black-bis, "black-ter": $black-ter, "grey-darker": $grey-darker, "grey-dark": $grey-dark, "grey": $grey, "grey-light": $grey-light, "grey-lighter": $grey-lighter, "white-ter": $white-ter, "white-bis": $white-bis), $custom-shades) !default`

there is scope to define custom shades same as custom-colors but it is returning a whole list due to automatically taking all four values (normal.dark,light,invert)

**Steps to Reproduce**
Define new variable named `$grey-custom` and `$custom-shades` and assign map value to that before importing bulma sass library.
```
$grey-custom: hsl(0, 0%, 25%) !default
$custom-shades: ("grey-custom": $grey-custom)
```

**Expected behavior**
class **has-background-grey-custom** should output only
`background-color: #404040 !important;`

**Actual behavior**
`background-color: #404040, #fff, whitesmoke, #878787 !important;`

**Comment by niuage** [comment]
👍  on this one, it's definitely an issue.

Also, why isn't `$grey-lightest` part of the default `$shades` variable?

**Comment by niuage** [comment]
I submitted a PR to fix that issue, hopefully it's looked at soon! It shouldn't be a very disruptive change.
