### ISSUE TITLE
Bulma Pagination Conflicts with ngx-pagination angular

### ISSUE THREAD

**Issue by riturajanand91** [jgthms/bulma#3317]
![image](https://user-images.githubusercontent.com/18161437/116801636-43891c00-ab29-11eb-833a-f4d38c293713.png)

NGX pagination in angular UI is broken when implementted with bulma css

**Comment by Ijee** [comment]
If anyone else has problems like these it can most likely be avoided by changing the view encapsulation for your angular component. Of course additional styling needs to be done afterwards.
