### ISSUE TITLE
Number inputs inner buttons are not clickable on Firefox

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#3318]
### Overview of the problem

This is about the Bulma **CSS framework**

Using Bulma **version** 0.9.1
My **browser** is: Mozilla Firefox 88.0

### Description
Inner buttons used to increase/decrease the value on inputs of type `number` with the `input` class cannot be clicked on Firefox.

### Steps to Reproduce

* `<input type="number">` works
* `<input class="input" type="number">` does not works

![Screenshot_2021-05-04_09-59-06](https://user-images.githubusercontent.com/74409786/116975919-b4167100-acc0-11eb-9fbe-ac01e3e324f7.png)

Adding a right padding of 0 makes the inner buttons clickable

![Screenshot from 2021-05-04 09-59-59](https://user-images.githubusercontent.com/74409786/116975983-c8f30480-acc0-11eb-9465-4bca71a99c6f.png)

**Comment by valentin-rigal** [comment]
I just saw "number" input is not supported by the `input` class in the documentation:
https://bulma.io/documentation/form/input/

It may be an interesting feature to have consistent forms.
