### ISSUE TITLE
Page rendering is broken by large <pre> element

### ISSUE THREAD

**Issue by mkende** [jgthms/bulma#3321]
This is bug or a feature request about Bulma (depending on your point of view I suppose.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.2.
My **browser** is: Chrome 89
This is **not** a **Sass** issue
I *believe* this issue is **not a duplicate**.

### Description

A very long line in a `<pre>` elements, inside a column will force the column to be very wide (up to a certain size, then, even if the 
line continue to grow the column will not grow further)

### Steps to Reproduce

On a computer or a tablet, save the provided [minimal.txt](https://github.com/jgthms/bulma/files/6444673/minimal.txt) file and rename it to `.html` (GitHub does not allow attaching html files directly it seems).

This document has 3 columns, with size 1/5th, 3/5th, 1/5th, and the center column contains some text and a `<pre>` element with very wide lines.

Open the document.

### Expected behavior

The main text in the center column should only take 3/5th of the width of the browser. The `<pre>` element should have a scroll-bar to be able to see the content that can’t fit in that width.

### Actual behavior

The "center" column extends with its content beyond the right of the viewport. There is no scrollbar so the right-side of the content cannot be seen (including an entire column at the right of the main one).

Here is a screenshot of the page as I see it:
![minimal](https://user-images.githubusercontent.com/3381888/117516338-24f7aa80-af99-11eb-961a-af187e6287fd.png)

**Comment by felmab** [comment]
I ended up adding `overflow-x: auto` on the parent container. I agree, this is not the same issue as #2924.

**Comment by linkdd** [comment]
I've met the same problem, @felmab thank you for your solution.

Here is a working codepen to reproduce the error AND the solution: https://codepen.io/linkdd/pen/WNpmYYd
