### ISSUE TITLE
Level does not look vertically centered

### ISSUE THREAD

**Issue by knutov** [jgthms/bulma#3322]
Bulma 0.9.2.
Both Chrome and Firefox

### Overview of the problem

according to documatatiln: 

> In a `level-item`, you can then insert almost anything you want: a title, a button, a text input, or just simple text. No matter what elements you put inside a Bulma `level`, they will always be **vertically centered**. 

But in real life they are not vertically centered in case of using class `title` or `subtitle`:

### Steps to Reproduce

```html
<nav class="level" style="border: 1px solid #FF0000">
	<!-- Left side -->
	<div class="level-left">
		<div class="level-item">
			<p class="subtitle is-5">
				<strong>123</strong> posts
			</p>
		</div>
		<div class="level-item">
			<p class="level-item"><a>Test</a></p>
		</div>

	</div>

	<!-- Right side -->
	<div class="level-right">
		<p class="level-item"><strong>All</strong></p>
		<p class="level-item"><a class="button is-success">New</a></p>
	</div>
</nav>
```

### Expected behavior

vertical centered elements

### Actual behavior

Firefox:

![2021-05-08 04-15-13 Mozilla Firefox](https://user-images.githubusercontent.com/255869/117516977-18cd1680-afb4-11eb-8d8f-1b5db21a10f4.png)

Chrome:

![2021-05-08 04-08-09 dh8 ru bulma-play index2 shtm](https://user-images.githubusercontent.com/255869/117516789-7c0a7900-afb3-11eb-8717-d6e675d3cec0.png)

They are only equally aligned if font-size of all elements are equal.

**Comment by matsn0w** [comment]
You are correct. It's off by `2px` on the bottom (or top, depends on how you see it 😀)

![measure](https://user-images.githubusercontent.com/15019582/120532959-8700cf80-c3e0-11eb-88ca-8ae36827776f.png)

**Comment by kdidkovsky** [comment]
> Bulma 0.9.2. Both Chrome and Firefox
> ### Overview of the problem

I've managed to fix it by removing ".level:not(:last-child), " from bulma.css at line 95.
