### ISSUE TITLE
[Question] How do i force navbar-burger on desktop/full screen?

### ISSUE THREAD

**Issue by leu2tm** [jgthms/bulma#3326]
### Overview of the problem

I'm using Bulma ^0.9.2

Maybe a related to this question: https://github.com/jgthms/bulma/issues/1042

### Description

I would like to display the burger menu at all time, which goes against the docs which says:
_"The navbar-burger is a hamburger menu that only appears on **touch** devices."_

How do I make the burger menu appear on all screen sizes?

Overwriting the `$navbar-breakpoint` variable didn't do it for me.

Thanks.

**Comment by elmatou** [comment]
`$navbar-breakpoint` work greater for me, just need to set to the wider screen
by default it is set on $desktop, but you can set it on $fullhd or any integer value you wich (eg: 70000000000)
