### ISSUE TITLE
custom hover appears on disabled button

### ISSUE THREAD

**Issue by AleaQ** [jgthms/bulma#3331]
This is about **Bulma**.

 bug on disabled button 

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

 I have a custom hover on the is-primary button. I used to be able to hide it on a disabled button with the css .button.is-primary:not(:disabled):hover This no longer works in the latest bulma version 

### Steps to Reproduce

1. create hover for is-primary button like .button.is-primarynot(:disabled):hover { background-color: green}
2. disable button
3. hover over disabled is-primary button 

### Expected behavior

 I expect the hover to not show on disabled button

### Actual behavior
hover color shows on disabled button

**Comment by jgthms** [comment]
There might be a typo. Try `.button.is-primary:not(:disabled):hover`

**Comment by AleaQ** [comment]
it was because instead of an element of <button> I had <a>. Sorry false alarm
