### ISSUE TITLE
[Bug]: modal-card-title does not wrap

### ISSUE THREAD

**Issue by christian-knollmann** [jgthms/bulma#3332]
This is about **Bulma**.

### Overview of the problem

[x] This is about the Bulma **CSS framework**

[x] I'm using Bulma **version** [0.9.2] 
[x] My **browser** is: Chrome Version 90.0.4430.212, Edge Version 90.0.818.62, Firefox 88.0.1 (probably all browsers)

[x] I am sure this issue is **not a duplicate**

### Description

If the title of a modal card is longer than the width of the modal, the title does not wrap (and hides the close button).

### Steps to Reproduce

1. Go to [https://bulma.io/documentation/components/modal/](https://bulma.io/documentation/components/modal/)
2. Click on "Launch card modal" button
3. Open developer console
4. Change the content of the `<p>`-tag with class `modal-card-title` from "Modal title" to a long string

### Expected behavior

![grafik](https://user-images.githubusercontent.com/84377918/118623841-eba91100-b7c8-11eb-8f1b-756060bfb0c5.png)

### Actual behavior

![grafik](https://user-images.githubusercontent.com/84377918/118623965-07acb280-b7c9-11eb-8732-84cc20d45962.png)

### Possible fix

Remove the `flex-shrink` and the `line-height` from `.modal-card-title`:

```diff
.modal-card-title {
     color: #363636;
     flex-grow: 1;
-    flex-shrink: 0;
     font-size: 1.5rem;
-    line-height: 1;
}
```

This fix proposal has only been tested on the above browsers (desktop-versions).

**Comment by ecoztas** [comment]
If you write the title in the .content class, there will be no problem.

**Example**

```
<header class="modal-card-head">
    <div class="content">
        <p class="modal-card-title">Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla... Bla bla bla...</p>
    </div>

      <button class="delete" aria-label="close"></button>
</header>
```

**Screenshot**

![bulma io_documentation_components_modal_(Moto G4)](https://user-images.githubusercontent.com/15870022/120569126-f0eb9a00-c41d-11eb-8ad7-d9c76a33dfca.png)


See the .content class at [https://bulma.io/documentation/elements/content/](https://bulma.io/documentation/elements/content/)

**Comment by christian-knollmann** [comment]
Thank you for your reply, but it causes other problem, so I hope someone else has another idea or confirms my fix proposal in the initial post.

If the title is short, then the close button floats to the left side:
![grafik](https://user-images.githubusercontent.com/84377918/120999399-5b3b6c00-c789-11eb-9347-815ca29c99c5.png)

In addition to that, the .content class causes a padding-top and a margin-bottom (which could be fixed with a `pt-0 mb-0`):
![grafik](https://user-images.githubusercontent.com/84377918/120999701-b2414100-c789-11eb-9d26-3c0e2deca22a.png)

Does nobody else have problems with long modal titles?
