### ISSUE TITLE
Responsive/Typography helpers - is-size-[size]-mobile helpers do not appear to be working

### ISSUE THREAD

**Issue by mikeywade** [jgthms/bulma#3341]
This appears to be a bug.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I am having an issue with the is-size-[size]-mobile helper. It doesn't appear to be working. If I use the is-size-[size] helper without specifying the breakpoint, this works fine.

Here is my code for the specific section I am trying to add the helper to:

```
<section class="tab-content is-active">
  <div class="content">
      <h2 class="animated is-size-4-mobile"></h2>
  </div>
</section>
```

The above is also wrapped in a .column and .section further up in my layout.

This is my first time opening an issue on here, so I am open to criticism and advice 😊

### Expected behavior

The heading should be resizing.

### Actual behavior

The heading is not being resized and the helper is ignored.

**Comment by marcbelletre** [comment]
The `is-size-{size}-mobile` helper does work as expected.  

The `h2` tag has a font size of 1.75em when in a `.content` element. The difference with the default `$size-4` value of 1.5rem is very subtle so maybe you didn't see it.

Here is a simple test with the exact same markup you provided on a mobile screen:
<img width="670" alt="Capture d’écran 2021-06-01 à 12 06 48" src="https://user-images.githubusercontent.com/6853334/120306354-11a6d900-c2d2-11eb-92cd-0a05e96d3d30.png">

And the same test on a larger screen:
<img width="1140" alt="Capture d’écran 2021-06-01 à 12 07 08" src="https://user-images.githubusercontent.com/6853334/120306349-1075ac00-c2d2-11eb-8c18-9bab0fc83c46.png">

If you look at the inspector window in the first screenshot you can see that the `.is-size-4-mobile` class has been applied.

**Comment by mikeywade** [comment]
Thanks @marcbelletre 

I've just checked the inspector and this doesn't appear to be showing the class style getting applied.

Could there be a reason as to why the styles are not getting applied or are missing? Others helpers and classes seem to work fine from what I can see.

**Comment by mikeywade** [comment]
Closing this as no longer an issue. The issue was coming from a compiling error rather than a bug from Bulma.
