### ISSUE TITLE
Are there any plans to add Split Button Dropdowns to Bulma?

### ISSUE THREAD

**Issue by SandyDatatables** [jgthms/bulma#3346]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I am sure this issue is **not a duplicate**

### Description

Hi,

I'm part of the [DataTables](https://datatables.net/) core team. We really like what you are doing and are about to release integrations with Bulma for our library and all of the extensions.

We are looking at adding split buttons to our [Buttons extension](https://datatables.net/extensions/buttons/) in the coming weeks as we think that this would be a great addition to our software. Of course, we would like to be able to support Bulma with this addition, but as far as I can tell Bulma does not yet support split dropdown buttons.

Have I missed it in the documentation/other issues? Are there any plans to add this in the future?
 
Some examples of split buttons in other libraries that we support...
* [Bootstrap 5](https://getbootstrap.com/docs/5.0/components/dropdowns/#split-button)
* [Bootstrap 4](https://getbootstrap.com/docs/4.0/components/dropdowns/#split-button-dropdowns)
* [Bootstrap 3](https://getbootstrap.com/docs/3.3/components/#btn-dropdowns)
* [Foundation](https://get.foundation/sites/docs/button-group.html#split-buttons)
* [jQuery UI](https://jqueryui.com/controlgroup/#splitbutton)

Cheers,
Sandy

**Comment by mateusbw** [comment]
@SandyDatatables check if this works for you

```
<div class="dropdown-trigger">
    <button class="button">
      <span>Dropdown button</span>
    </button>
    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu" id="button">
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
 </div>
```

If so, I could add this example to the docs.

**Comment by SandyDatatables** [comment]
Hi @mateusbw ,

That seems to be along the right lines - thanks!

Adding it to the docs would be greatly appreciated. Then I will be able to see exactly how your intended styling looks and we can start supporting it.

Cheers,
Sandy

**Comment by SandyDatatables** [comment]
Hi @mateusbw ,

Has there been any progress with this?

All the best,
Sandy
