### ISSUE TITLE
The target selector was not found.

### ISSUE THREAD

**Issue by fbeqirllari** [jgthms/bulma#3349]
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: The target selector was not found.
Use "@extend %block !optional" to avoid this error.
   ╷
13 │   @extend %block
   │   ^^^^^^^^^^^^^^
   ╵
  node_modules/bulma/sass/elements/notification.sass 13:3  root stylesheet
SassError: SassError: The target selector was not found.
Use "@extend %block !optional" to avoid this error.
   ╷
13 │   @extend %block
   │   ^^^^^^^^^^^^^^

"bulma": "^0.9.2",

**Comment by b3j0f** [comment]
Same error here while trying to import button.sass

```sass
@charset 'utf-8'

$turquoise: hsl(171, 100%, 41%)
$light: hsl(0, 0%, 96%)
$dark: hsl(0, 0%, 21%)
$primary: $turquoise
$link: hsl(229, 53%,  53%)
$info: hsl(207, 61%, 53%)
$success: hsl(153, 53%,  53%)
$warning: hsl(44, 100%, 77%)
$danger: hsl(348, 86%, 61%)

@import 'bulma/sass/grid/columns.sass'
@import 'bulma/sass/elements/button.sass'
```

> Syntax Error: SassError: The target selector was not found.
Use "@extend %control !optional" to avoid this error.
   ╷
61 │   @extend %control
   │   ^^^^^^^^^^^^^^^^
   ╵
  node_modules/bulma/sass/elements/button.sass 61:3  root stylesheet

**Comment by heinsenberg82** [comment]
Any updates on this? Same issue here!
