### ISSUE TITLE
Webpack for .sass

### ISSUE THREAD

**Issue by infacq** [jgthms/bulma#337]
I have a `.scss` file and later I import a file `@import "~bulma/sass/base/classes.sass";` but when successfully compile it hit the error

``` bash
Module build failed: 
  +desktop
          ^
      No mixin named desktop

Backtrace:
    node_modules/bulma/sass/base/classes.sass:7
      in /Users/infacq/Documents/sewa/src/react-client-app/node_modules/bulma/sass/base/classes.sass (line 7, column 12)
```

what is the right setup to import `.sass` file

**Comment by jgthms** [comment]
You need to import all the utilities first.

**Comment by infacq** [comment]
is it documented properly?
