### ISSUE TITLE
is-capitalized does not work with uppercases text (caps lock on)

### ISSUE THREAD

**Issue by lucraraujo** [jgthms/bulma#3375]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.3]
 My **browser** is: Firefox 89.0.2
I am sure this issue is **not a duplicate**

### Description

When I type an uppercased text in a input with class 'is-capitalized', the text remains in uppercase

### Steps to Reproduce

https://jsfiddle.net/w16jtco2/

### Expected behavior

When typing um uppercase (caps lock), the text must be converted to Capitalized.

### Actual behavior

The text remains uppercased.

**Comment by lucraraujo** [comment]
I realized that this is a CSS problem, but, is there a way to fix this behavior?
IMHO, capitalize should work for all lowercase and all uppercase.
e.g. "lucas araujo" => capitalized => "Lucas Araujo"
e.g. "LUCAS ARAUJO" => capitalized => "Lucas Araujo"

**Comment by jgthms** [comment]
I think in CSS it only affects the first letter and leaves all following ones untouched.
