### ISSUE TITLE
Sass Survey: not enough options

### ISSUE THREAD

**Issue by fosskers** [jgthms/bulma#3377]
Hi there, I love Bulma, and I just noticed the survey on the site. However, I don't use any of those Sass versions and neither does "I don't know" apply to me. I use the [sass compiler](https://github.com/compass-rs/sass-rs) built into the [trunk](https://github.com/thedodd/trunk) build tool for Rust/WASM projects. 

At the very least, an "Other: please specify" option on the survey could help.

**Comment by jgthms** [comment]
It seems sass-rs is a wrapper around libsass. So you’re essentially using libsass. I’ll specify that the node-sass package on non is only an example of a libsass implementation.

**Comment by fosskers** [comment]
> It seems sass-rs is a wrapper around libsass.

Ah so it is, I should have read further. Thank you!
