### ISSUE TITLE
Help: how to add custom colors to Bulma?

### ISSUE THREAD

**Issue by Wandalen** [jgthms/bulma#3379]
I have found this code: 

```sass
$custom-colors: null !default

$colors: mergeColorMaps(("white": ($white, $black), "black": ($black, $white), "light": ($light, $light-invert), "dark": ($dark, $dark-invert), "primary": ($primary, $primary-invert, $primary-light, $primary-dark), "link": ($link, $link-invert, $link-light, $link-dark), "info": ($info, $info-invert, $info-light, $info-dark), "success": ($success, $success-invert, $success-light, $success-dark), "warning": ($warning, $warning-invert, $warning-light, $warning-dark), "danger": ($danger, $danger-invert, $danger-light, $danger-dark)), $custom-colors) !default
```

How to extend the list of colors and classes associated with each color?
It's clear I need to define a variable `$custom-colors` before including Bulma, but it's not clear what format of $custom-colors should be? I didn't find an example or good description of that. Any help?

**Comment by Max131** [comment]
You need to "recompile" bulma to do that, but there is a tutorial in the docs. (I use the node-sass way). In the docs, in every page at bottom, there is the variables that you can customize. 

https://bulma.io/documentation/customize/

**Comment by Wandalen** [comment]
@Max131 what format of $custom-colors? Could you please give an example?

**Comment by Max131** [comment]
I found this, I test it and works perfectly. You must add this to your customized sass main file.

https://github.com/jgthms/bulma/issues/2244
https://bulma.io/documentation/customize/with-node-sass/

~~~javascript
$orange: #ff8606;
$orange-invert: findColorInvert($orange);
$custom-colors: ("orange": ($orange, $orange-invert));
~~~

**Comment by Wandalen** [comment]
Thank you, Max131 :) That's what I have been lookign for.
