### ISSUE TITLE
[request] remove debug lines

### ISSUE THREAD

**Issue by thom-nic** [jgthms/bulma#338]
I'm using bulma v0.2.1 with sass-loader and webpack; bulma itself imported as a npm module, and I `@import '~bulma/bulma'` in my SASS sources.  Every time my sources recompile I get the following:
<img width="589" alt="screen shot 2016-10-04 at 1 27 41 pm" src="https://cloud.githubusercontent.com/assets/95562/19084989/9e0afd24-8a36-11e6-9338-f62ba9dbce61.png">

Source is bulma/sass/utilities/functions.sass:27-28

Aside from forking and commenting out the `@debug` lines I can't find a way to turn off that output.  I could redirect stderr but I don't want to lose other error output from webpack.  As far as I can tell libsass doesn't have an option to control logging verbosity.  

Suggest leaving these commented out?  I'm not sure they're useful for bulma _users_ vs developers.  Or maybe they can be disabled by an `@if` directive?

**Comment by jgthms** [comment]
Yeah, they shouldn't be there. I'll remove them in the next push.

**Comment by tvld** [comment]
And when will the next push be ? )))  npm still has them, the code seems ok ))

**Comment by VizuaaLOG** [comment]
@tvld You may already know this but the @debug lines were removed in commit 91bcdb6 

@jgthms This issue can now be closed :)

**Comment by tvld** [comment]
@VizuaaLOG : Top :)) Bulma is rocking  :+1:
