### ISSUE TITLE
is-hidden-desktop doesn't work on new release

### ISSUE THREAD

**Issue by pouya-abbassi** [jgthms/bulma#3382]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.9.3]
My **browser** is: Firefox & Chromium
I'm pretty sure this issue is **not a duplicate**.

### Description
I just upgraded  from an older version (probably 0.7.3), and I tried Firefox and Chrome.
In both of them, `is-hidden-desktop` of my navbar items doesn't work on [0.9.3] but used to work on older version I had since 2019.

### Steps to Reproduce
My (simplified) HTML tags which contain `is-hidden-desktop` class:
```html
<div class="navbar-end">
    <a class="navbar-item is-large" href="..." id="github" title="GitHub">
        <span class="is-large icon">
            <i class="fab fa-github fa-lg" aria-hidden="true"></i>
        </span>
        <span class="is-large is-hidden-desktop">GitHub</span>
    </a>
</div>
```
My sass file looks like this (I haven't changed it for this upgrade):
```sass
@import "sass/utilities/_all"
@import "sass/base/_all"
@import "sass/elements/_all"
@import "sass/form/_all"
@import "sass/components/_all"
@import "sass/grid/_all"
@import "sass/layout/_all"
```
So by definition, `sass/helpers/visibility.sass` and `sass/utilities/helpers/visibility.sass` must be imported in my css.

I expect those texts to be hidden on desktop and only visible on smaller screen (where it's visible inside burger menu)
It used to look like the top image, now it's like the bottom one:
![image](https://user-images.githubusercontent.com/8519318/126094060-83990667-858a-4587-ae3f-dd3c302df4c2.png)

Documents on [visibility helpers](https://bulma.io/documentation/helpers/visibility-helpers/#hide).
You can also check the live version of [my website](https://pouyacode.net) (I still haven't fixed the issue manually)

**Comment by marcbelletre** [comment]
The `visibility.sass` file is located in `sass/helpers` and not `sass/utilities`.
You have to import `sass/helpers/visibility` or `sass/helpers/_all`.  

I guess the file has been moved since 0.7.3.
