### ISSUE TITLE
Syntax error in 0.9.3 (thrown in codesandbox)

### ISSUE THREAD

**Issue by y-nk** [jgthms/bulma#3386]
### Overview of the problem

This is about the Bulma **CSS framework**
This is about **Bulma**
My **browser** is: Chrome latest
This is a **Sass** issue: I'm using version [0.9.3]

### Description

When using in codesandbox, there's an error thrown:

```
expected ";".
  ╷
3 │ $black:        hsl(0, 0%, 4%) !default
  │                                       ^
  ╵
  node_modules/bulma/sass/utilities/initial-variables.sass 3:39  @import
  stdin 2:9                                                      root stylesheet
```

### Steps to Reproduce

1. Open this [repro link](https://codesandbox.io/s/github/AmityCo/Amity-Social-Cloud-Web-Sample-Apps/tree/main/vue2-single-channel-chat)

### Expected behavior

Should not have error

### Actual behavior

Has error

**Comment by jgthms** [comment]
It seems it’s trying to use the SCSS parser instead of the Sass one.
