### ISSUE TITLE
Footer color is not a bool

### ISSUE THREAD

**Issue by razzeee** [jgthms/bulma#3388]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

https://bulma.io/documentation/layout/footer/ says `$footer-color` is a bool, it only seems to work with a color value from testing.

### Expected behavior

Docs should be correct :)

### Actual behavior

Docs are not correct?

**Comment by motionsuggests** [comment]
The `default` is `false` so this might be why.   https://github.com/jgthms/bulma/blob/master/sass/layout/footer.sass#L4
