### ISSUE TITLE
Button consistency

### ISSUE THREAD

**Issue by eshell** [jgthms/bulma#339]
### PLEASE READ THE FOLLOWING INSTRUCTIONS

Tag your issue accordingly:
- is it about Bulma or about the Docs?
  Bulma
- is it a bug/feature/question or do you need help?
  Bug?
- if it's a bug, is it a browser bug?
  no

Thanks for helping out! 😇

Please remove any unused content (including these instructions) before submitting your issue.
### Checklist
- [ ] This is about the Bulma **CSS framework**
- [ ] I'm using Bulma **version** [0.2.1]
- [ ] My **browser** is: Ubuntu Chrome (latest)
- [ ] I am sure this issue is **not a duplicate**?
### Description

When dynamically changing buttons from `<button class="button is-danger is-outlined">Button</button>` to `<button class="button is-danger">Button</button>` for effect, the content around the button is pushed due to `is-outlined` using a border, but regular buttons do not. 
Using an outlined button should take the same space as a regular button.
### Steps to Reproduce

https://jsfiddle.net/5m1fdog9/
### Expected behavior

all buttons the same width
### Actual behavior

buttons change width

**Comment by jgthms** [comment]
True. I removed the border on coloured buttons so that the box-shadow inset looks better.
