### ISSUE TITLE
HTTPS downgrade while browsing Docs

### ISSUE THREAD

**Issue by abrain** [jgthms/bulma#3395]
This is about **the Docs**.
It is likely a bug/mistake in the web server configuration.

### Overview of the problem

This is about the Bulma **Docs**
My **browser** is: Firefox 91.0.1
I am sure this issue is **not a duplicate**.

### Description

Browsing the documentation with the latest Firefox and enabled HTTPS-only mode is quite cumbersome. Every click to a different documentation page caues an HTTPS warning.

### Steps to Reproduce

1. Go to bulma.io
2. Click _Documentation_
3. see HTTPS warning

### Expected behavior

Navigation should not trigger warnings.

### Actual behavior

This affects all links on bulma.io that do not have a trailing slash.

```
% curl -v https://bulma.io/documentation 
...
< HTTP/2 301 
< date: Wed, 18 Aug 2021 12:07:09 GMT
< content-type: text/html
< x-origin-cache: HIT
< location: http://bulma.io/documentation/
...
```

URLs without a trailing slash get redirected to the version with the trailing slash. This redirect downgrades to HTTP, which causes the warning.

**Comment by sjoqvist** [comment]
This still seems to be an issue. Is the stale label applied too quickly? Or is the project dying?

**Comment by abrain** [comment]
I did not notice this behaviour recently, but that might be due to some change in Firefox. However, the https-to-http redirect as mentioned above is still in place and should be fixed.
