### ISSUE TITLE
Typo on bulma's website

### ISSUE THREAD

**Issue by Jimmar** [jgthms/bulma#3402]
This is about **the Docs**.

### Overview of the problem
Found a typo in the main website specifically here
https://github.com/jgthms/bulma/blob/ee8eb6ad0d8b7bfe3ee75624218b216126a7d0a7/docs/_includes/index/beautified.html

> See what Bulma developers are bulding

should be

> See what Bulma developers are building

**Comment by FidalMathew** [comment]
Please assign me, I would like to work on this issue.

**Comment by jgthms** [comment]
It has already been fixed actually.
