### ISSUE TITLE
navbar is-transparent does not make navbar transparent

### ISSUE THREAD

**Issue by rSSi** [jgthms/bulma#3403]
This is about **Bulma** 0.9.3.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** 0.9.3
My **browser** is:  Firefox Developer Edition 92.0b9 (64-bit) on Windows 10
I am sure this issue is **not a duplicate**

### Description

`navbar is-transparent` is not transparent, not even in the [example](https://bulma.io/documentation/components/navbar/#transparent-navbar)

It still has the color rgb(255,255,255) as set by .navbar

Thank you!

**Comment by lionzeye** [comment]
The is-transparent class has the following purpose according to the documentation placed above the mentioned example: "This will remove any hover or active background from the navbar items." so it's not meant to make the navbar itself transparent, rather the items in it, in their hovered and active state.

**Comment by rSSi** [comment]
Thank you - being able to read and understand certainly helps! ;)
