### ISSUE TITLE
Can Bulma fix my Js parsing issue

### ISSUE THREAD

**Issue by conorseb20** [jgthms/bulma#3404]
I need to know whether it is possible to fix the issue with this page using Bulma - https://order.tophomeworkexpert.com/order
It was working perfectly, and all over sudden it failed to load. I tried checking java parsing issues to no avail.
Is there a way I can use the bulma css framework or tools to fix it. It is a recourse of frontend at [top homework expert](https://tophomeworkexpert.com/).

**Comment by jgthms** [comment]
Bulma is only a css framework.l and only affects how a page looks, not how it loads.  Your problem seems to be related to JavaScript so I don’t believe we can help you here sorry.
