### ISSUE TITLE
Bulma.min.css vscode error message

### ISSUE THREAD

**Issue by fingertip12** [jgthms/bulma#3421]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework
I'm using Bulma **version** 0.9.3

### Description

What is this error message in bulma.min.css? I don't like to see error messages in my project. 

![image](https://user-images.githubusercontent.com/91487994/134966055-10451456-9283-40a5-9b74-79f4c530c4bf.png)

### Steps to Reproduce

1. Open bulma.min.css in Visual Studio Code

**Comment by jgthms** [comment]
It’s a vendor prefixed property that autoprefixer adds for compatibility reasons. I’m not sure how useful it is nowadays

**Comment by fingertip12** [comment]
@jgthms , Honestly I don't care what is it, I just don't like to see that one error message...
