### ISSUE TITLE
select.is-loading appears not to be vertically centered

### ISSUE THREAD

**Issue by kaysievers** [jgthms/bulma#3426]
The animated spinner of ```select``` ```is-loading``` appears not be vertically centered.

<img width="258" alt="Screen Shot 2021-10-11 at 13 46 20" src="https://user-images.githubusercontent.com/1064936/136785000-cba5932d-6e58-4a2b-8014-47ce473a2492.png">

It is visible in the documention: https://bulma.io/documentation/form/select/#states

Changing the position values from .625em to 0.75em appears to move it to the center. Thanks!

**Comment by YisusJuarez** [comment]
I can help with this.

**Comment by mohannadize** [comment]
This issue occurs also in the input `is-loading`

![image](https://user-images.githubusercontent.com/20673938/154885997-c3e3f105-599b-4c34-b519-34e423210f9d.png)

Screenshot taken from the [bulma documentation website here](https://bulma.io/documentation/form/input/#:~:text=Copy-,Loading,-%3Cdiv%20class%3D%22control)

**Comment by YisusJuarez** [comment]
@mohannadize  
 I think #3450 solution solves it.

**Comment by darkuranium** [comment]
@jgthms I see you've closed the ticket, but are there any plans on merging the solution?

I just ran into this issue today, and the PR is still unmerged as off right now.
