### ISSUE TITLE
how to do customizing if i need mobile only looks

### ISSUE THREAD

**Issue by yunfan** [jgthms/bulma#3440]
This is about **Bulma**.

Its about i need help

### Overview of the problem

<-- This is about the Bulma **CSS framework** -->

<-- I'm using Bulma **version** [0.9.3] -->
<-- My **browser** is: Chrome 91-->

<-- I am sure this issue is **not a duplicate**? -->

### Description

hi i am a totally beginner of frontend developing, while i am a backend developer
i knew some css concepts but i havnt familiar with sass

what i want is a mobile only look which will only limit the max width of the page containter to 768px and center it when the media query result is bigger then 768px , but i had tried  modifiers like `is-mobile` , seems not works as i need. is it possible to add a  modifier for this purpose ? maybe named it `is-mobile-only` ?

**Comment by accpickatwu** [comment]
i use this for my projects

(pc ui) <div class="is-hidden-mobile is-hidden-touch is-hidden-tablet-only">

both ui also end with </div>

(mobile ui) <div class="is-hidden-widescreen-only is-hidden-desktop-only">

**Comment by yunfan** [comment]
> i use this for my projects
> 
> (pc ui) `<div class="is-hidden-mobile is-hidden-touch is-hidden-tablet-only">`
> 
> both ui also end with `</div>`
> 
> (mobile ui) `<div class="is-hidden-widescreen-only is-hidden-desktop-only">`
> 
> Also `is-mobile` means support mobile

thanks very much
