### ISSUE TITLE
Bulma Fixed Position Elements

### ISSUE THREAD

**Issue by jcantrel** [jgthms/bulma#3443]
This is about Bulma.

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.9.2] 
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

I have created a fixed position button for moving to the top, using manual CSS. Is there a way to do this natively within Bulma? I try to avoid custom CSS whenever possible. Here is the fixed position button, which always remains at the bottom right of the page:

![image](https://user-images.githubusercontent.com/37300313/140992320-5784efce-ba55-4471-add9-9f1f52400cea.png)

Here is the HTML I used to accomplish it:

`<a href="#top" class="button is-primary" style="position: fixed; bottom: 10%; left: 96%">
        <i class="fas fa-chevron-up"></i>
    </a>`

Due to the way my pages in this app can have wildly diffrent page lengths, I needed this button to always remain in the same spot and to float above all other elements. After a few interations the above CSS accomplished what I needed. I searched for a way to do this with Bulma and could not find one.

**Comment by jgthms** [comment]
I think this css would be too specific to be included in a css framework, in particular left: 96% and bottom: 10%. It would significantly increase the css file to include all possible options. 

But that is how you use a framework like Bulma: you use predefined styles as much as possible and then add your own styles on top for fine tuning.
