### ISSUE TITLE
How to get two columns in tablet and single column in mobile

### ISSUE THREAD

**Issue by alaksandarjesus** [jgthms/bulma#3445]
Choose one of the following:
This is about **Bulma | the Docs**.
Bulma
Is it about Bulma or about the Docs?
Bulma
Is it a bug/feature/question or do you need help?
help

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.9.3]
My **browser** is: Chrome

### Steps to Reproduce

`div class="columns is-tablet"
    div class="column">a</div
    div class="column">b</div
/div

### Expected behavior
(If there is no class like is-tablet, how to make this happen)

In Tablet

a   b

In Mobile

a

b

### Actual behavior

In Tablet

a

b

In Mobile

a   

b

**Comment by jgthms** [comment]
"Tablet" is from `769px` and above. Columns work by default from that point on. Maybe you're not on a viewport wider than that?

**Comment by alaksandarjesus** [comment]
I am not sure whether i did convey properly. So made some visual.

**Desktop**

![image](https://user-images.githubusercontent.com/4712552/141396234-5ecb84c0-e00e-4fad-a641-d1c4b11161f8.png)

**Tablet**
![image](https://user-images.githubusercontent.com/4712552/141396272-c02ed28d-34a8-450a-8abb-5a44b1590cd8.png)

**Mobile**
![image](https://user-images.githubusercontent.com/4712552/141396324-df5cd697-33b5-47f6-aa44-749c006a44af.png)

I need 
  Sounds Like
  Spelled
  Associated
  Related To
in single rows only on mobile view.

I have used columns and they work perfect on tablet and desktop

**Comment by alaksandarjesus** [comment]
Ok. I got it. I was reading all the time 769 as 767. Thank you. I love bulma. Hope there should be no more struggles
