### ISSUE TITLE
I can't log in to bulmo. IO

### ISSUE THREAD

**Issue by Bald-mans** [jgthms/bulma#3452]
I can't log in to bulmo. IO website.When I click on the hyperlink of the bulmo.io website.I got this result:
![image](https://user-images.githubusercontent.com/57175015/144034878-8c172a77-c954-48b1-b56b-0ca834cf04d5.png)
I just wanted to use this CSS library today.But this problem has forced me to give up using it for the time being.I hope you can help me，thanks.

**Comment by jgthms** [comment]
It works for me. Where are you based?

**Comment by accpickatwu** [comment]
Hi im pickatwu, Maybe your wifi or Wifi security

Cause that happened to me 
I told my network administrator to configure 
Website/ Allow me to visit this page
