### ISSUE TITLE
docs - broken design at layout - container, hero and section ?

### ISSUE THREAD

**Issue by moh-sushi** [jgthms/bulma#3456]
Hi,

while studying the docs in order to use it in a web app, i have found (_imho_) broken design pages:
- https://bulma.io/documentation/layout/container/
- https://bulma.io/documentation/layout/hero/
- https://bulma.io/documentation/layout/section/

These mentioned pages are shown equal in current google chrome and firefox (on windows).

Is this "broken design" wanted?

non-broken design:
If you load e.g. [doc footer ](https://bulma.io/documentation/layout/footer/), the doc itself in centered between ToC overall (left) and ToC current side itself (right). This looks as desired.

**Comment by jgthms** [comment]
It’s intentional as the layout needs to be full width. There’s another issue discussing the same topic.
