### ISSUE TITLE
Mobile navigation with left, center and right section

### ISSUE THREAD

**Issue by jakobrosenberg** [jgthms/bulma#346]
I'm not sure if this is an issue with Bulma itself or its documentation.

I'm at a loss in my attempt to make a basic mobile navigation menu like this:

```
 -------------------------------------------
|   Menu          Brand          username   |
|-------------------------------------------|
|                                           |
|                                           |
```

Am I missing something obvious?

**Comment by thomasmarciniak** [comment]
I'm also looking for something similar. Would love to see simple solution for that in docs as I've got to do many tweaks on current nav to make it act like this.
