### ISSUE TITLE
I can't see navbar.

### ISSUE THREAD

**Issue by dkyung213** [jgthms/bulma#3470]
This is about **Bulma | the Docs**.

### Overview of the problem
I can't see navbar.

### Description
I can't see navbar when I use my phone.
![image](https://user-images.githubusercontent.com/80299969/149866621-2f585fe2-1c06-4c5b-a598-250688a391d1.png)
![image](https://user-images.githubusercontent.com/80299969/149866673-472e647f-2398-4ef7-a4d3-c952f21ea6f2.png)
It changes which width is less than 1024.

**Comment by jgthms** [comment]
What is your code?

**Comment by dkyung213** [comment]
Oh I found the error. You don't have to help me now. Thank you for comment my issue.
