### ISSUE TITLE
Bulma Button text is not centered

### ISSUE THREAD

**Issue by Yifei-G** [jgthms/bulma#3471]
This is about **Bulma**.

### Overview of the problem
I have upgraded Bulma to v0.9.3, the text of the button are not centered. 

This is about the Bulma **CSS framework** 
I'm using Bulma **version**  v0.9.3 
My **browser** is: Google Chrome Version 96.0.4664.110 (Official Build) (x86_64)

### Description
All the button texts are justify-content- flex-start instead of center

### Steps to Reproduce

Add the following code in the HTML:
<button class="button">Button</button>

This will render a button with text alight at the left side instead of at the center

### Expected behavior

Button's text should be at the center

### Actual behavior

Button's text are at the left side of the button

**Comment by Yifei-G** [comment]
<img width="889" alt="Screenshot 2022-01-18 at 11 39 56" src="https://user-images.githubusercontent.com/53911347/149921849-fa27b7f0-9428-46d2-953e-ad5ca1785148.png">

**Comment by Yifei-G** [comment]
<img width="429" alt="Screenshot 2022-01-18 at 11 41 04" src="https://user-images.githubusercontent.com/53911347/149922019-f1fdde13-0048-4afa-a132-842760960cdd.png">

**Comment by srikargunnam** [comment]
Hi @jgthms, i am new to open source contribution, can i fix the above simple issue by raising a pull request?

**Comment by acieroid** [comment]
I also encountered this one when upgrading from 0.9.2 to 0.9.3. A temporary fix is to override `justify-content` in your CSS: `.buttons { justify-content: center }`

**Comment by jgthms** [comment]
Which version are you using? Because buttons are centered here: https://github.com/jgthms/bulma/blob/80e0396424cc44a93db0223446e8b6029d77dd53/sass/elements/button.sass#L70

![image](https://user-images.githubusercontent.com/1254808/152686029-7a17297e-0f9a-4779-8955-09a2543a869d.png)

**Comment by acieroid** [comment]
I'm using bulma 0.9.3 with bulmaswatch and bulma-slider, i.e., the following imports:
```
@import "../../node_modules/bulmaswatch/cyborg/bulmaswatch.scss";
@import '~bulma-slider';
@import "../../node_modules/@creativebulma/bulma-tooltip/dist/bulma-tooltip.css";
```

And I'm definitely using `button` and not `buttons`, with the following result:
![button](https://user-images.githubusercontent.com/58877/152686352-e4af51f6-9c5e-45fd-b108-37997737b525.png)

**Comment by jgthms** [comment]
What happens if you only import bulma, and not bulmaswatch or the bulma-slider?

**Comment by acieroid** [comment]
Ah indeed, the problem comes from bulma-slider, downgrading it to 2.0.4 fixes the issue! Thanks for the help, I will add an issue in bulma-slider then.
