### ISSUE TITLE
Just desktop and mobile breakpoints on the grid?

### ISSUE THREAD

**Issue by PhillippOhlandt** [jgthms/bulma#35]
Hey,

I just looked over the docs and saw there is only a desktop view and a mobile view (all columns under each other).

Any reasons why you provide no breakpoints for mobile, tablet and desktop like bootstrap?

**Comment by jgthms** [comment]
Yeah I'm not sure how to handle it yet. Btw, this is discusses in #7.

**Comment by PhillippOhlandt** [comment]
Well,

`<div class="column is-6-mobile is-2-tablet is-2-desktop"></div>`

would be a good solution in my mind.

**Comment by JustSteveKing** [comment]
+1 @PhillippOhlandt

**Comment by uolot** [comment]
+1 for that

**Comment by jgthms** [comment]
@PhillippOhlandt That's a good idea. It's easy to read as well: `is-6-mobile` would be _"Is 6 out of 12 columns on mobile"_.

But please, discuss this in #7.
