### ISSUE TITLE
Question: fixed bottom center

### ISSUE THREAD

**Issue by hardcoar** [jgthms/bulma#350]
- Docs
- Question

hi. im new to web dev and also bulma. quick question:
    how do i implement something fixed bottom center? e.g. button. when i override fixed position to bottom it goes to bottom left corner and columns/tiles do not apply.

the framework is awesome btw. are there any helpers like fixed bottom? this might be a feature request or additional docs request and sure it'll help newbies outhere.

thanks in advance.

**Comment by hardcoar** [comment]
any workaround is welcome too.

**Comment by jgthms** [comment]
You need to dive into CSS positioning: http://marksheet.io/css-position.html
