### ISSUE TITLE
Typo/Grammatical error on the docs, specifically the blocks page

### ISSUE THREAD

**Issue by KrisKamweru** [jgthms/bulma#3509]
This is about the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description
There is a grammatical error on the very last line of the block description page

### Expected sentence
This prevents the last sibling * from adding * unnecessary space at the bottom.

### Actual behavior
This prevents the last sibling * to add * unnecessary space at the bottom.

**Comment by jgthms** [comment]
Good catch. Would you mind creating a PR to fix this typo?

**Comment by KrisKamweru** [comment]
Sure thing. I'll get on it soon

**Comment by KrisKamweru** [comment]
Alright, lemme know if I need to do anything else

**Comment by jgthms** [comment]
Many thanks.
