### ISSUE TITLE
The navbar overlaps with sidebars in "Fullheight hero with navbar" 

### ISSUE THREAD

**Issue by PogromcaPapai** [jgthms/bulma#3510]
This is about the Docs.

It's a bug. It's not a browser bug.

### Overview of the problem

This is about the Bulma **Docs**

My **browser** is: Firefox

I am sure this issue is **not a duplicate**
I've searched the past issues and i haven't found anything similar.

### Description

The hero with navbar is on top of the sidebars. I'm quite sure this is not a browser bug, as it's reproducible in Edge.

### Steps to Reproduce

Go to [this page](https://bulma.io/documentation/layout/hero/#fullheight-with-navbar) and open any sidebar while being in the "Fullheight hero with navbar" section.

### Expected behavior

The hero with navbar should be behind the sidebars.

### Actual behavior

The hero with navbar is on top of the sidebars.

**Comment by geeksilva97** [comment]
Same here. I think i can investigate this.

**Comment by geeksilva97** [comment]
Nice job @atilafb!
