### ISSUE TITLE
Change Suggestion for tabs

### ISSUE THREAD

**Issue by doerner** [jgthms/bulma#3528]
This is about **Bulma .

This is a request for change the "tabs"-setup in Bulma to reduce JavaScript for a solution .

In the current version of Bulma, you need JS to change the active tab and to 
show a different content-panel associated with the new tab selected.

But there are pure CSS solutions (making use of the :checked-property) 
for this problem if you use radio-buttons instead of the link <a>.
https://codepen.io/markcaron/pen/MvGRYV

Therefore I suggest to base the "tabs" on "radio buttons" and "labels" instead of  <ul> and <a>-tags so that such a pure css solution is feasible to implement.

**Comment by jgthms** [comment]
It is true that there are pure CSS solutions for tabs, as there are for a lot of things (like toggling a hamburger menu with a checkbox). But these solutions feel more like hacks, and are not very clean to implement. They would also probably not be optimal when used with classic fullpage reloads or even break functionality when used in the context of a JS framework.

I wouldn't add this functionality to Bulma but it's still possible to add it in your own project with a few lines of CSS.
