### ISSUE TITLE
No margin between buttons

### ISSUE THREAD

**Issue by serby** [jgthms/bulma#353]
### Checklist

* [X] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [X] I'm using Bulma **version** [x.x.x]
* [X] My **browser** is: Chrome 53
* [X] I am sure this issue is **not a duplicate**?

### Description
Buttons rely on newlines for gap. Compressing the HTML removes all space between buttons.

### Steps to Reproduce

```html
<div class="column">
  <a class="button is-outlined">Outlined</a>
  <a class="button is-primary is-outlined">Outlined</a>
  <a class="button is-info is-outlined">Outlined</a>
  <a class="button is-success is-outlined">Outlined</a>
  <a class="button is-danger is-outlined">Outlined</a>
</div>
```
Produces this:

![screen shot 2016-10-18 at 13 19 32](https://cloud.githubusercontent.com/assets/254583/19477345/91772c22-9535-11e6-8b87-50b44085efea.png)

Remove the newlines:

```html
<div class="column"><a class="button is-outlined">Outlined</a><a class="button is-primary is-outlined">Outlined</a><a class="button is-info is-outlined">Outlined</a><a class="button is-success is-outlined">Outlined</a><a class="button is-danger is-outlined">Outlined</a></div>
```

![image](https://cloud.githubusercontent.com/assets/254583/19477443/0d30d340-9536-11e6-9057-d2ae15bab3e9.png)

### Expected behavior

There should be some margin between buttons.

### Actual behavior

No margin

**Comment by jgthms** [comment]
Yes it's the normal behaviour, as buttons are `inline-flex` or `inline-block`. This allows to specify an exact margin.

If you want regular spacing, you can use a button group.

**Comment by serby** [comment]
Thanks, I can see that `is-grouped` is the correct usage now.

Is there any possibility of having it so that buttons margins' aren't mutated based on newlines to prevent idiots like me question the behaviour of button margins.

**Comment by jgthms** [comment]
That's unfortunately the default behaviour of browsers.

**Comment by serby** [comment]
Thanks, I can see why this must be like this now. Great project BTW! Really enjoying using it.

**Comment by claide** [comment]
> 2019

Need to wrap the buttons inside a div with a class buttons

```
<div class="buttons">
    <button class="button">Button 1</button>
    <button class="button">Button 2</button>
</div>
```
