### ISSUE TITLE
Allow tabs to show/hide content

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [jgthms/bulma#3556]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** latest
My **browser** is: Chrome/Linux

### Description

Tabs do not seem to have a feature built in to show/hide divs by ID, so that only the div corresponding to the selected tab is ever shown, and so that when different tabs are clicked on, different content is shown. 

Look at Switcher in UIKit for how I would expect this to work:

https://getuikit.com/docs/switcher

**Comment by jgthms** [comment]
Bulma does not include any JavaScript. There are also solutions with CSS hacks but there are not favoured by Bulma. Most developers will have their own JS solution for tabs.
