### ISSUE TITLE
Sponsorship bug

### ISSUE THREAD

**Issue by Casinoburst** [jgthms/bulma#3565]
Hi guys, 

Started to sponsor you guys with 200 dollars a month for my sites casinoburst.com and uudetkasinot.com, for this I should get a logo and link on bulma. However its now a week and cant see them live. Can you pls check it out? 

Best

Simon

**Comment by jgthms** [comment]
Will contact you directly.

**Comment by Casinoburst** [comment]
thanks! info@lannistermedia.com
