### ISSUE TITLE
Also accept <section> as partent of container

### ISSUE THREAD

**Issue by tvld** [jgthms/bulma#357]
From the docs: 
```
The .container class can be used in any context, but mostly as a direct child of either:
    .header
    .hero
    .section
    .footer
```
Why do I need to write ``<section class="section">`` all the time? It's a bit double ?

**Comment by jgthms** [comment]
Bulma is tag agnostic: you can use `<div class="section">` or `<main class="section">`. It's up to you.

**Comment by tvld** [comment]
well...but it's common to use a lot of ``<section>`` so was just wondering. But.. .so ... we will keep it double )
