### ISSUE TITLE
Bulma Docs: Layout sub-items behave differently

### ISSUE THREAD

**Issue by CorporateActionFigure** [jgthms/bulma#3571]
Different sub-menu items under the **Layout** menu item on the left-hand side exhibit different behavior. In certain cases (e.g. 'hero' and 'container', at least), you see this behavior:

![image](https://user-images.githubusercontent.com/54010963/189462447-80cc839d-6b6a-4c5f-8dc6-64d82303342f.png)

Other menu items have the behavior I would expect, which is to say:

![image](https://user-images.githubusercontent.com/54010963/189462484-87220de5-86c0-43a4-afd5-a0776884150e.png)

This is on `Firefox 104.0.2` and `Monterey 12.5.1` if that is at all helpful (although I suspect this is not platform/browser-specific as I can re-produce identical behavior in Safari).

Let me know if I can provide additional information.

**Comment by jgthms** [comment]
See #3290
