### ISSUE TITLE
.content is dark on dark .hero

### ISSUE THREAD

**Issue by Antrikshy** [jgthms/bulma#359]
### Checklist
- [x] This is about the Bulma **CSS framework**
- [x] I'm using Bulma **version** [0.2.3]
- [x] My **browser** is: Safari 10.0
- [x] I am sure this issue is **not a duplicate**?
### Description

`color` of `.content` is dark on `.hero.is-dark`.

I hope I'm not using anything incorrectly, but I have a dark `.hero`, and I'm trying to place `.content` on it like so:

```
<section class="hero is-dark is-fullheight main-section">
  <div class="container">
    <h1 class="title is-pulled-right">Experience</h1>
  </div>
  <div class="hero-body content">
    <div class="container">
      <div class="columns">
        <div class="column is-3">
          <img src="logo-here.jpg" />
        </div>
        <div class="column is-9">
          <h2>Job position</h2>
          <p>Description of job position</p>
        </div>
        <div class="column is-3">
          <img src="logo-here.jpg" />
        </div>
        <div class="column is-9">
          <h2>Job position</h2>
          <p>Description of job position</p>
        </div>
      </div>
    </div>
  </div>
</section>
```

I have tried placing the content class in many different places, but looking at the CSS generated, it seems like Bulma does not support placing `.content` on a dark background. Removing the class fixes the color issue, but makes sizes of `h2` and `p` exactly the same because of mini-reset.

I'm pretty sure this is a shortcoming right now, and I'll have to work around this. Figured I should open a discussion here.

**Comment by VizuaaLOG** [comment]
I think the main use of hero is to show a heading and sub heading. The text colour is applied through the ```.title``` and ```.subtitle``` classes. I think you may be using the hero for something outside of what it was created for.

**Comment by Antrikshy** [comment]
I see. I guess I'm just looking for a section element with a dark background.

On Sat, Oct 29, 2016 at 6:36 PM Thomas Erbe

<
mailto:Thomas Erbe <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I think the main use of hero is to show a heading and sub heading. The text colour is applied through the

.title

and

.subtitle

classes. I think you may be using the hero for something outside of what it was created for.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/jgthms/bulma/issues/359#issuecomment-257126490
, or

**Comment by VizuaaLOG** [comment]
You could use a section and then have some custom CSS like the following:
```CSS
section.is-dark {
    background-color: #363636;
    color: whitesmoke;
}

section.is-dark a {
    color: whitesmoke;
}
```

**Comment by Antrikshy** [comment]
Looks like making a custom dark `.section` would be best, because it's a bit more complicated to change everything to whitesmoke on a dark hero.

Would love to see a dark section preset if you ever decide to do that. Given what it comes with already, I've come to expect a lot from Bulma! :)

**Comment by Antrikshy** [comment]
Another reason I use hero is that I like to use `.is-fullheight`, which section doesn't seem to come with.
