### ISSUE TITLE
Columns modifiers not documented

### ISSUE THREAD

**Issue by nathanjessen** [jgthms/bulma#36]
The site currently has column modifiers (is-2, is-3, etc) documented but none of the columns modifiers (is-gapless, is-grid). Initially, I was trying to layout a row of elements using 3 columns of is-5, is-5, and is-2 modifiers. The columns ended up having a total width larger than 100% because of the margin gap between each column. It wasn't until I dove into the sass files that I found some of the modifiers like is-gapless and is-grid. These still aren't super intuitive but need to be added to documentation nonetheless.

**Comment by jgthms** [comment]
Yeah you're right. I didn't document these features cause they're still WIP. And the column system needs additional stuff, like classes for each breakpoint, alignment, spacing...

Working on it.

**Comment by joelataylor** [comment]
exciting to see those features added to the column/grid system @jgthms !

**Comment by jgthms** [comment]
So `is-gapless` and `is-grid` are not documented yet, but `is-multiline` and `is-mobile` have been added: http://bulma.io/documentation/grid/

**Comment by jgthms** [comment]
Added to the docs.
