### ISSUE TITLE
[Feature Request] Custom Checkboxes

### ISSUE THREAD

**Issue by fire17** [jgthms/bulma#3607]
Hi there, I just found out about bulma
looks really beautiful.
I would like it if anyone knows how can i make a checkbox that has multiple states
for example [ ] empty [ * ] dotted [V] Checked, and [VV] double checked (like whatsapp)
the value for each can be a string, and there should be a small icon to go along with it

what do you guys think ?
is there any way to do this currently ?
Thanks and have a good one!

**Comment by jgthms** [comment]
You can find good tutorials on the internet. Check out this for example https://moderncss.dev/pure-css-custom-checkbox-style/
