### ISSUE TITLE
Is Bulma actively maintained?

### ISSUE THREAD

**Issue by stsrki** [jgthms/bulma#3627]
Hello team.

I'm a long-time user of Bulma. And I could not but notice that the last 0.9.4 version was released almost a year. From what I can see, there is not much going on to add new features. There are also many open PRs still in the queue. So my question is, are there any plans or a roadmap to move forward? Toward the stable v1.0? Thanks

**Comment by jgthms** [comment]
Yes it is! There hasn’t been releases lately because I’m working on the actual v1, which will bring a lot of new features: CSS variables, dark mode, class prefix, new smart grid, etc.

It’s a big change and there is a branch which activity. I’ll announce a beta version soon.

**Comment by stsrki** [comment]
That's good to know. Thank you for your quick response!

**Comment by Tragio** [comment]
@jgthms is there any ETA for it? There are no commits since February 😞 https://github.com/jgthms/bulma/tree/bulma-v1-css-variables
