### ISSUE TITLE
Printing uses mobile layout

### ISSUE THREAD

**Issue by yscik** [jgthms/bulma#363]
- [x] This is about the Bulma **CSS framework**
### Description

Since all responsive media queries are formed along the lines of `@media screen ...`, printing a page defaults to the mobile-first, everything is vertical style, making most of the layout features unusable. There is also no way to override this with configuration. 

Are there any plans regarding this? Including `@media print` in the `tablet` mixin seems like a good fit.

**Comment by jgthms** [comment]
Mmmh that's an interesting one. I never really thought about the impact of using `@media screen`, as printing a webpage is something I rarely do.

I actually don't use `@media screen` anymore, so I don't see any real harm in removing it.
