### ISSUE TITLE
Ordering of 'Backers' page

### ISSUE THREAD

**Issue by BWPanda** [jgthms/bulma#3631]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

I am sure this issue is **not a duplicate**

### Description

The [Backers page](https://bulma.io/backers/) is ordered as follows:
- Generous backers ($30+)
- Documentation sponsors ($500+)
- Website sponsors ($300+)
- Homepage sponsors ($100+)
- Bulma backers ($10+)

It seems to me that the 'Generous backers' section should be bumped down to sit between 'Homepage sponsors' and 'Bulma backers'. That way everything would be ordered in descending order by amount donated.

**Comment by jgthms** [comment]
It’s on purpose as the generous backers only appear on this page, unlike the other backers.
