### ISSUE TITLE
Navbar-dropdown not accounting for width of icons and is wrapping

### ISSUE THREAD

**Issue by jorvis** [jgthms/bulma#3635]
This is about **Bulma**.

It could be Bulma or me missing something in the docs.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.9.4
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

### Description

If you have a navbar-dropdown which is on the right side of the page, the items wrap if they contain icons. 

### Steps to Reproduce
Create a navbar like this:

```
                  <div class="navbar-dropdown is-right">
                      <a class="navbar-item">
                        <span class="icon-text">
                          <span class="icon"><i class="mdi mdi-account"></i></span>
                          <span>User profile</span>
                        </span>
                      </a>
                    </div>
```

### Expected behavior

The dropdown should size itself to accommodate the width of the child[

### Actual behavior

It doesn't seem to account for the width of the icon and padding, instead wrapping like this:

![edit](https://user-images.githubusercontent.com/330899/230225282-cfbf619d-afb8-4b6d-a74e-b62c3dd57fe0.png)

If I take the icon out it works, and if I replace the text with a much longer string it works.  But the inclusion of the icon makes it wrap.

**Comment by dh-i** [comment]
@jorvis I tried and it seems to be working fine. Can you please check again and if the problem still persists, can you share the complete code for your nav bar? Or a codepen, codesandbox link with the code will be very much appreciated.

**Comment by jorvis** [comment]
Thanks!  Bouncing between airports right now but the code is here:

https://github.com/IGS/gEAR/blob/ui-v2/www/new_page_template.html#L172

**Comment by dh-i** [comment]
That is because in your `css/gear-theme-purple.css` you are writing additional css for `.icon-text` class(which seems redundant but you might know better) and that is causing the issue.

If you remove flex-wrap, it'll work as expected.

![bulma_icon_fix](https://github.com/jgthms/bulma/assets/51533230/fb03e231-9051-4ddb-9df3-b2d9570dbd93)

**Comment by jorvis** [comment]
@dh-i  I really appreciate you looking into this.  In this case, it appears bulma is generating that portion of the code.  I only authored [this SCSS file](https://github.com/IGS/gEAR/blob/ui-v2/www/css/gear-theme-purple.scss) and then transpiled it:

sass gear-theme-purple.scss:gear-theme-purple.css

My source scss doesn't have any flex definitions like that in it.

**Comment by dh-i** [comment]
@jorvis You are correct, it's coming from `@import "../css/bulma/sass/elements/_all.sass";`

Not sure about the exact reason for that approach. The fix I would use is to add 

```
.icon-text{
  width: max-content;
}
```
