### ISSUE TITLE
Simple Content Centering Classes [question/feature request]

### ISSUE THREAD

**Issue by alexsasharegan** [jgthms/bulma#364]
### Description

I've looked through the docs and the sass source, but I can't seem to find much in the way of centering utility classes besides these: 
- **Text Utilities** 
  - `.has-text-centered` 
- **Grid Utilities**
  - `.is-centered`
  - `.is-vcentered`

How about expanding on the grid utility classes to affect any element? I know that flexbox centering depends on flex-direction, so maybe we could use modifiers off `.is-flex` to provide access to column direction as well. Maybe `.is-flex-col || .is-column`? Then `.is-centered` would modify it's behavior to accommodate the flex-direction property.

If these things exist in the library, then tag this a docs request; otherwise, tag this a feature request. Love the library! Cheers!
- [x] This is about the Bulma **CSS framework**
- [x] This is about the Bulma **Docs**
- [x] I'm using Bulma **version** [0.2.3]
- [x] My **browser** is: Chrome _Version 54.0.2840.71 (64-bit)_
- [x] I am _fairly_ sure this issue is **not a duplicate**

**Comment by gbourgneuf** [comment]
+1
It will be very useful .

**Comment by rusthub** [comment]
I would like to note that this is quite handy and should be a part of the Bulma helper classes.

**Comment by alexsasharegan** [comment]
Closing from inactivity.
