### ISSUE TITLE
Docs - Left Nav collapses for widescreen for container, hero, and section topics.

### ISSUE THREAD

**Issue by gskaplan** [jgthms/bulma#3652]
This is about **The Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

In the docs, the left navigation collapses and shows only dots after selecting Container, Hero, and Section. When selecting any other topics in the nav menu, the navigation becomes visible again.

### Steps to Reproduce

1. View this page:  https://bulma.io/documentation/layout/container/ or https://bulma.io/documentation/layout/hero/ or this page https://bulma.io/documentation/layout/section/.

### Expected behavior

When viewing on a desktop with ample browser width, I would expect that the left navigation remains visible and not collapsed.

### Actual behavior

The left navigation collapses when selecting Layout/Hero, Layout/Section, and Layout/Container

**Comment by jgthms** [comment]
It is the correct behaviour. See #3290
