### ISSUE TITLE
Navbar burger lines are weird

### ISSUE THREAD

**Issue by alexandrehtrb** [jgthms/bulma#3656]
### Overview of the problem

Navbar burger looks weird, because the burger lines do not have the same height. Some are thinner than the others.

![image](https://github.com/jgthms/bulma/assets/27026741/3fcb5a68-30c1-43de-93e9-dff7c597c280)

Version 0.9.4.

Tested on Firefox and Edge.

### Expected behavior

They should all have the same height.

**Comment by VIVEKIITdelhi** [comment]
You may assign this to me...

**Comment by VIVEKIITdelhi** [comment]
Sir can u tell me the documentation which I may refer to clone and run this repo? @alexandrehtrb

**Comment by alexandrehtrb** [comment]
> Sir can u tell me the documentation which I may refer to clone and run this repo? @alexandrehtrb

You can clone this repo, but I don't know which branch they are using, I am not a maintainer

**Comment by alexandrehtrb** [comment]
I checked it today and it seems fixed:

![image](https://github.com/jgthms/bulma/assets/27026741/e4b3a1ad-aac5-409e-ac99-790dbf1454f8)

**Comment by spavel-gh** [comment]
@alexandrehtrb @singhcoder694 

To reproduce the issue, you need to set the [page zoom](https://support.google.com/chrome/answer/96810?hl=en&co=GENIE.Platform%3DDesktop&oco=1) to 110%, 125%, 150%, and so on.

You can also reproduce the problem by leaving the page zoom at 100% and adjusting the system scaling. For example, I'm using Windows 10 with a Full HD laptop screen, and I have my [system scaling](https://support.microsoft.com/en-us/windows/view-display-settings-in-windows-37f0e05e-98a9-474c-317a-e85422daa8bb) set to 125%. Under these conditions, I consistently observe the issue.


These screenshots illustrate the issue when zoomed in using Chrome:

- 100% 
![a](https://github.com/jgthms/bulma/assets/71533482/3b156f29-c53a-4795-adbc-155107152d50)
- 110% 
![b](https://github.com/jgthms/bulma/assets/71533482/51e57b28-5058-4012-bb29-f12c08fbe820)
- 125% 
![c](https://github.com/jgthms/bulma/assets/71533482/5d0530c6-b997-4e10-90cf-5681c278f5dc)
- 150% 
![d](https://github.com/jgthms/bulma/assets/71533482/bb8eb9f0-9fc5-4793-96e1-79416b659d09)
