### ISSUE TITLE
Any plan for new minor release(0.10.0)?

### ISSUE THREAD

**Issue by zhaolinlau** [jgthms/bulma#3678]
I was wondering if there are any plans to release a new minor version since there hasn't been one for 3 years

**Comment by Ash-Crow** [comment]
Per #3627, @jgthms is working on a 1.0 release, but AFAIK there is no info on when it will be released.

**Comment by zhaolinlau** [comment]
> Per #3627, @jgthms is working on a 1.0 release, but AFAIK there is no info on when it will be released.

Yea I know, but the v1.0 branch has already gone more than 6 months without any commits

**Comment by askmrsinh** [comment]
@jgthms 
I hope all is well with you. I wanted to politely ask about the current challenges implementing some of the most requested features (#3682, #1837) and if you need any help with the upcoming version.

**Comment by tatwww** [comment]
@jgthms
Looking forward to new versions and features appearing!

**Comment by kraaden** [comment]
It appears that there hasn't been much activity on this project recently. Is it still being maintained?

**Comment by thefirstspine** [comment]
Hello,

Yes @jgthms is still working and maintaining the repo. He merged one of our MR for dependencies update a few days ago.

But I have to admit that having more than one maintainer would be great on Bulma.

**Comment by luischicllarosas** [comment]
The question is why it takes so long if there are many sponsors who support the project, I don't understand.

**Comment by zhaolinlau** [comment]
Since Bulma CSS is not actively developed anymore, I think it's time to migrate to [Cirrus CSS](https://www.cirrus-ui.com/)

**Comment by thefirstspine** [comment]
Got some news from @jgthms - Bulma v1 is still planned for early 2024 with some features in separated branches:
- CSS Variables
- Dark Mode
- SCSS instead of Sass
- Dart support

I agree that lack of communication is somewhat frustrating.

**Comment by firdaus-aziz** [comment]
![Screenshot from 2023-12-14 10-58-12](https://github.com/jgthms/bulma/assets/1595757/ade9c1d2-cf95-466c-8063-1bb8caeaf438)

Can't wait for v1

**Comment by suterma** [comment]
Thanks @thefirstspine for chiming in. An upcoming release is good news. That said, Bulma has always and is working very well for me, I consider it mature. This v1 will be well deserved.

**Comment by thefirstspine** [comment]
Hello,

Bulma V1 was released a few days ago.

@jgthms I think you can close the issue 💯
