### ISSUE TITLE
Classless variant release

### ISSUE THREAD

**Issue by janat08** [jgthms/bulma#3679]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Classless variant of Bulma. Bulma is advertised as something that just works it should be classless, for 0 effort installation and usage.

### Steps to Reproduce

Release another stylesheet that applies classes  to html tags and not classes.

### Expected behavior

None of the framework classless being really used, can be easily adopted or switch away from.

### Actual behavior

Will require some effort to install and delete.

**Comment by jgthms** [comment]
It would probably be way too difficult to implement. It also wouldn’t cover all the elements from Bulma, so it would only be a partial implementation. I think users would end up confused and disappointed. 

There are also already great classless frameworks out there who are probably better suited for the job.

**Comment by digitigradeit** [comment]
Well... WELCOME TF back either way :)

**Comment by janat08** [comment]
Couldn't it be as simple as applying some regex to apply class selectors to
html tag selectors, moving everything else to separate stylesheet to be
downloaded separately?

**Comment by jgthms** [comment]
I don’t think “regex” and “simple” can be in the same sentence.
