### ISSUE TITLE
Problem with example JavaScript for Modal

### ISSUE THREAD

**Issue by rgalea** [jgthms/bulma#3692]
This is about the Bulma **Docs** 

The example JavaScript on https://bulma.io/documentation/components/modal/ has the following block:
<pre>// Add a keyboard event to close all modals
document.addEventListener('keydown', (event) => {
  if (event.code === 'Escape') {
    closeAllModals();
  }
});</pre>

This does not work on Chrome (118.0.5993.88) on a Mac (13.5.2)

I replaced it with:
<pre>// Add a keyboard event to close all modals
document.addEventListener("keydown",function(e){
  if(e.key === "Escape") {
    closeAllModals();
  }
});</pre>

I have tested this solution on Chrome and Firefox on a Mac and on Edge on Windows.

**Comment by Adelrisk** [comment]
Makes sense. The documentation gives me the impression that `code` shouldn't be the first choice.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

> [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) Read only
> 
>     Returns a string with the code value of the physical key represented by the event.

> [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) Read only
>
>     Returns a string representing the key value of the key represented by the event.

(`code` also has a warning emphasising the difference.)

**Comment by rgalea** [comment]
In the change you made you kept the original "event" variable when adding the listener and my "e.key" in the "if" statement.
