### ISSUE TITLE
All CDN urls return 404 Not Found

### ISSUE THREAD

**Issue by ejstembler** [jgthms/bulma#3698]
This is about **Bulma's CDN urls**.

### Overview of the problem

All of the CDN urls return 404 Not Found.

### Description

My website is using the `0.9.1`.:  https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css but you can try any version. The latest: https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css.

None work.

The [CDN landing page](https://www.jsdelivr.com/package/npm/bulma) looks empty with no stats.

### Steps to Reproduce

Open a website which uses a Bulma CDN link.  It will not render correctly since the CDN url returns 404 Not Found.

### Expected behavior

Expect the CDN urls to work correctly.

### Actual behavior

They return 404 Not Found instead.

**Comment by jgthms** [comment]
Seems to be working now.
