### ISSUE TITLE
v1 release date?

### ISSUE THREAD

**Issue by stsrki** [jgthms/bulma#3708]
Hi. I have noticed a new banner saying v1.0 is coming soon.

Is there any ETA when we might expect it?

**Comment by n614cd** [comment]
I am also curious. I found Bulma on a recently reviewed site for CSS frameworks.
It looks very promising, except the lack of activity. There has been very little activity for close to four years.

Tim

**Comment by stsrki** [comment]
> It looks very promising, except the lack of activity. There has been very little activity for close to four years.

Which is a shame, really. Bulma is a great framework. And we really need more alternatives to Bootstrap, Tailwind, and others.

**Comment by jgthms** [comment]
Looking to have beta testers next month and release v1 by end of Q1.

**Comment by stsrki** [comment]
> Looking to have beta testers next month and release v1 by end of Q1.

As a vendor of a component library(https://github.com/Megabit/Blazorise), I'm more than open to being a tester. Since we heavily use Bulma, we can give excellent insight and feedback on what to fix.

**Comment by n614cd** [comment]
@jgthms 

I can also beta test. I have a small app which we are looking to go to beta testing toward the end of Q1 and launch in Q2.
So the timing works well.

Tim

**Comment by FreekyMage** [comment]
> Looking to have beta testers next month and release v1 by end of Q1.

I want to test as well. We don't use all components, but we do have custom extra colors, different media queries,... so it might be a good test to see how all of those translate to the new version. I might be able to help with making sure migration documentation is made/tested.

**Comment by ragamuf** [comment]
Same here for beta testing.

**Comment by Zubrik** [comment]
> Looking to have beta testers next month and release v1 by end of Q1.

I can help with beta testing, too.

**Comment by jgthms** [comment]
Thanks all. Let me set up a mailing list to prevent this thread from being flooded with comments.

**Comment by tsoek** [comment]
I've been using Bulma in a few projects and will be beginning a new one this month. I would love to beta test the new release as I develop the project if that is good enough to get my hands on the beta. Is there anything by way of a migration guide or breaking changes from how Bulma exists right now? I can always start with the current latest version and go from there moving to v1.

**Comment by jgthms** [comment]
There will be quite a few changes, and some breaking changes, which is inevitable. What I want though is that any customisation of v0.9* done so far can gracefully be handled by Bulma v1. Hence the need for a beta.

**Comment by n614cd** [comment]
@jgthms 

I signed up two weeks ago, since I have seen no messages from the list, I wanted to verify it was not being blocked in my spam folder (I checked but did not see it).

Tim

**Comment by gxres042** [comment]
> @jgthms
> 
> I signed up two weeks ago, since I have seen no messages from the list, I wanted to verify it was not being blocked in my spam folder (I checked but did not see it).
> 
> Tim

Wait for February coming? Only 5 days left.

**Comment by jgthms** [comment]
There are already lots of people who signed up for the beta. They will mostly be asked to provide feedback about the new version. I had to close the list because there were enough beta testers already and adding more would have had diminishing returns since I have to manually give access to each one of them. 

But fear not: this means that v1 will arrive sooner than expected.

**Comment by gxres042** [comment]
> There are already lots of people who signed up for the beta. They will mostly be asked to provide feedback about the new version. I had to close the list because there were enough beta testers already and adding more would have had diminishing returns since I have to manually give access to each one of them.
> 
> But fear not: this means that v1 will arrive sooner than expected.

That means everyone expects the new version of Bulma.

**Comment by stsrki** [comment]
Hello, sorry for posting on a closed ticket.

Are there any estimates of when we might expect the beta release?

**Comment by RobbiNespu** [comment]
![](https://i.imgur.com/04yX6FT.png)

OMG! I missed Bulma V1 beta tester. I hope it will release as soon as possible. Can’t wait for dark-mode, smart grid, skeleton loader and auto color / pallete features 😁

[](https://brid.gy/publish/github?bridgy_omit_link=false)

(Originally published at: https://journal.robbi.my/notes/240211113838/)

**Comment by JasonHK** [comment]
How breaking the changes in v1 are? I would like to wait for v1 released to start developing my new website if the changes were very breaking.

**Comment by calebhyatt** [comment]
So far it looks like it isn't breaking. Core elements have remained the same, just extra functionality and helpers.

https://bulma.io/documentation/elements/button/
https://bulma.io/documentation/components/navbar/
