### ISSUE TITLE
Still no IE11 fixes for has-text-centered?

### ISSUE THREAD

**Issue by shuffgy** [jgthms/bulma#371]
![bulma_ie11](https://cloud.githubusercontent.com/assets/17125448/19931238/09a03f72-a10c-11e6-82ce-f1ce06ee9cbf.JPG)

### Checklist

* [x] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [x] I'm using Bulma **version** [latest]
* [x] My **browser** is: **IE11**
* [x] This is a ~~**Sass**~~ **CSS** issue
* [x] I am sure this issue is **not a duplicate**?

### Description

In the docs of bulma it says "Browsersupport IE 10+". But as you can see in the screenshot, it's not really working. Same issues on my private site.

**Comment by ACITSupport** [comment]
I think I'm seeing the same issue in v0.4.4.
None of the text alignment options work in a hero box in Edge or IE 11. Text or buttons etc are always aligned left.

I found that if I disable the "display: inline flex;" option in DOM Explorer on either of these browsers the body content then uses the alignment options properly.

**Comment by ACITSupport** [comment]
This appears to be something to do with the button being an <input> rather than <a>. Switching to <a> has fixed the problem for me.

**Comment by alexdiliberto** [comment]
I'm not seeing this on IE11 now when visiting builma.io. I believe this can be closed

![image](https://user-images.githubusercontent.com/666459/35708642-09b2d71c-077d-11e8-8522-e749e3013c09.png)

**Comment by murilobd** [comment]
Not fixed yet!
See the picture below (IE11 on Win 7)
![image](https://user-images.githubusercontent.com/4275011/46546137-84184e80-c8c8-11e8-933b-494d34760c89.png)
