### ISSUE TITLE
columns gap cousing a column pushed to next line

### ISSUE THREAD

**Issue by DeveloperMajd** [jgthms/bulma#3714]
<div className="columns is-multiline">
        <div className="column is-4-desktop"></div>
        <div className="column is-4-desktop"></div>
        <div className="column is-4-desktop"></div>
      </div>
      
      in this code i should have three column in one row, but when adding a gap to the columns the therd column is pushed to the next line.
      how can i add a gab between the column and maintaining the number of divs per row ?

**Comment by Zubrik** [comment]
Hi,
Where exactly are you adding the gap? 
Besides, perhaps [one of these options](https://bulma.io/documentation/columns/gap/#variable-gap) may help you achieve what you want.
