### ISSUE TITLE
General question on further development

### ISSUE THREAD

**Issue by mispp** [jgthms/bulma#3717]
This is generic question about the project.

Since github discussions are disabled, opening an issue here.

What is planned for the future of Bulma? The question comes because there seems to be 177 pull requests, many questions unanswered in issues and so on...
- Is Bulma "finished" and only maintenance (aka bugfixes) is to be done from this point on?
- Will there be some extensions? Like switch control? There was one old issue that said toggle is opinionated and will not be included for the sake of simplicity -> https://github.com/jgthms/bulma/issues/130#issuecomment-198914772. Or some more advanced controls like in buefy?

**Comment by jgthms** [comment]
See #3708
