### ISSUE TITLE
Indeterminate Progress Bar Styles

### ISSUE THREAD

**Issue by andrewmunsell** [jgthms/bulma#372]
### Description

HTML5 progress bars can either have a value attribute associated with it, or have it omitted. If the value attribute is omitted, then the progress bar is considered indeterminate. 

It would be great if Bulma had styles for indeterminate progress bars.

An example of an indeterminate progress bar:

https://codepen.io/anon/pen/eBOjex

```
<progress></progress>
```

Versus, a determinate progress bar:

```
<progress value="10" max="100"></progress>
```

**Comment by gbritoo27** [comment]
What king of styles would you want it to have ?

**Comment by andrewmunsell** [comment]
Generally, an indeterminate progress bar is filled entirely with some sort of animation to indicate that there is activity. The Codepen I posted in the original post shows the native indeterminate progress bar, for example, which shows the basic idea of this. 

Another example of indeterminate progress bars (for inspiration, potentially) includes Jquery UI (https://jqueryui.com/progressbar/#indeterminate), which has a basic stripe animation that fills he entire progress bar.

**Comment by connectkushal** [comment]
@andrewmunsell 

I think this has been added ?
http://bulma.io/documentation/elements/progress/

Please close the issue.

**Comment by andrewmunsell** [comment]
@connectkushal No, those are not indeterminate progress indicators

**Comment by connectkushal** [comment]
Ah, my bad. At least the issue got bumped :grimacing:

**Comment by sohailalam2** [comment]
Hi @jgthms,

Whats the progress on this issue? Looks like its open since Nov 2016!! Are there any plans or workaround available currently?

Thanks

**Comment by scottwernervt** [comment]
I put together a [codepen](https://codepen.io/scottwernervt/pen/mMWQya) demonstrating indeterminate progress bars. The code was sourced from [spectre.css](https://picturepan2.github.io/spectre/experimentals.html#progress).  I am not a fan of the animation and was hoping someone could come up with a better look/feel as I am new to CSS. I can create a pull request or make it a bulma extension.

![bulma-indeterminate-progress-bar](https://user-images.githubusercontent.com/1048949/31696492-c7dbb2ce-b37f-11e7-9387-b15544a1746f.gif)
