### ISSUE TITLE
leve-right has top margin when is-mobile

### ISSUE THREAD

**Issue by sahibalejandro** [jgthms/bulma#373]
When using `level is-mobile` the child `level-right` has `margin-top: 20px` causing elements not correctly align vertically, see the attached images.

```html
<div class="level is-mobile">
    <div class="level-left">
        <div class="level-item">hello</div>
    </div>
    <div class="level-right">
        <div class="level-item">world</div>
    </div>
</div>
```

On tablet (and up) the result is what you expect:
<img width="622" alt="screen shot 2016-11-03 at 10 58 42 am" src="https://cloud.githubusercontent.com/assets/985268/19976555/ce71df14-a1b5-11e6-8acd-67172408a68f.png">

On mobile the result is a little bit "not desired":
<img width="401" alt="screen shot 2016-11-03 at 10 58 49 am" src="https://cloud.githubusercontent.com/assets/985268/19976584/ef41126e-a1b5-11e6-9aaf-ee255d6eaaf5.png">

**Comment by ryanmr** [comment]
I fixed this for my site with the following:

```css
@media screen and (max-width: 768px) {
  .level-left + .level-right {
    margin-top: 0;
  }
}
```

I did not look at the ramifications of this fix though, so ymmv.
