### ISSUE TITLE
tiles dissapeared from docs

### ISSUE THREAD

**Issue by jucajuca** [jgthms/bulma#3730]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs** 

### Description

The tiles section just vanished from the website:
https://bulma.io/tiles/

### Steps to Reproduce

Go to:
https://bulma.io/tiles/

### Expected behavior

Docs will show.

### Actual behavior

Docs are not showing

**Comment by digitigradeit** [comment]
https://bulma.io/documentation/start/migrating-to-v1/#breaking-changes indicates tiles is no more. and you should use the new grid system. 

so use grid, cell and box for ancestor, parent and child respectively.
