### ISSUE TITLE
Missing CSS helpers in No Dark Mode version

### ISSUE THREAD

**Issue by idybil** [jgthms/bulma#3736]
First of all, a big thank you for your great work! I've done tons of projects with the 0.9.4 version and your version 1.0.0 seems great. I especially appreciate the CSS variables.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma --> 1.0.0
My **browser** is: any

### Description

It seems that the "bulma-no-dark-mode.min.css" version does not contains the CSS helpers. 

### Steps to Reproduce

1. Use the "bulma-no-dark-mode.min.css" in your html  `<head>.`
2. Put any html element with a CSS help class, example `<h1 class="has-text-link mb-5">Hi!</h1>`

### Expected behavior

The `<h1>` tag from the example above should have the text-link color and have a margin-bottom.

### Actual behavior

The `<h1>` tag from the example above does not have the text-link color and have a margin-bottom.

### Question 

Is it possible to include the CSS helper in the "bulma-no-dark-mode.min.css" version or have a new version having the helpers ?

Thanks

**Comment by onli** [comment]
I also see no effect from `has-background-light` in the no dark mode version. Is that related, and maybe also  unintended?

**Comment by dbrgn** [comment]
Same here: `has-text-danger` seems to work in the regular version, but not in no-dark-mode.

A fixed no-dark-mode version would be very much appreciated, since it allows upgrade to 1.0 for sites that don't yet work properly with dark mode (or where a dark mode is simply undesired).

**Comment by wlh320** [comment]
I guess it is because a missing `@forward "helpers";` in `versions/bulma-no-dark-mode.scss`.
I use npm to install bulma, add this line referring to `sass/_index.scss`, and manually compile it using `npm run build-all` as a temporary solution.

**Comment by max-arnold** [comment]
+1

Minified CSS size went from 207kb for 0.9.4 to 647kb for 1.0.0 (more than tripled!).  How to get the same functionality with a similar CSS bundle size?

**Comment by idybil** [comment]
Thanks @jgthms
