### ISSUE TITLE
Changelog for v1.0.0

### ISSUE THREAD

**Issue by noraj** [jgthms/bulma#3741]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**, the CHANGELOG is not including the changes for v1.0.0.

### Description

CHANGELOG.md does not contain v1.0.0 changes neither on the master branch or on the bulma-v1 branch. Only the Github release contains some of the major changes. https://github.com/jgthms/bulma/releases/tag/1.0.0

**Comment by jgthms** [comment]
This has been fixed.
