### ISSUE TITLE
Unable to access to the page of positioning helpers

### ISSUE THREAD

**Issue by zhaolinlau** [jgthms/bulma#3752]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

Unable to access to the documentation of the positioning helpers when i click the "positioning"

### Steps to Reproduce

1. navigate to documentation
2. click the positioning under css helpers

### Expected behavior

redirect to the page of positioning helpers

### Actual behavior

redirect to the page of spacing helpers

**Comment by vanodevium** [comment]
As far as I understood in the past versions, there were no positional helpers there either.

I think it's an accidental typo.

> you can look at older versions yourself: [0.9.4](https://versions.bulma.io/0.9.4/documentation/), [0.9.3](https://versions.bulma.io/0.9.3/documentation/) etc.

**Comment by BeepBot99** [comment]
#3762 will fix this issue.
