### ISSUE TITLE
Documentation for navbar-burger contains error regarding number of empty `span` tags

### ISSUE THREAD

**Issue by scottmacpherson** [jgthms/bulma#3754]
This is about **the Docs**.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** 1.0.0

I am sure this issue is **not a duplicate**

### Description

https://bulma.io/documentation/components/navbar/#navbar-burger states:

> It has to contain three empty span tags…

As of 1.0.0 it has to contain *four* empty span tags though. The code examples are correct.

**Comment by JAProgramming** [comment]
I just submitted a pull request to fix the typo

**Comment by jgthms** [comment]
> I just submitted a pull request to fix the typo

I can't see it.

**Comment by shenef** [comment]
It's #3788, looks like it took 30 minutes for it to show up.

**Comment by scottmacpherson** [comment]
Resolved by commit a38cd56. Thanks everyone!
