### ISSUE TITLE
navbar-burger-color in 1.0 useless

### ISSUE THREAD

**Issue by Natureshadow** [jgthms/bulma#3757]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [1.0.0]

My **browser** is: Firefox 123

I am sure this issue is **not a duplicate**

### Description

Setting the `$navbar-burger-color` does not change the burger color. It seems this is because in the Bulma `light` theme, the burger color HSL values are reset to those of the `link` color.

### Steps to Reproduce

```
@use "bulma/sass" with {
  $navbar-burger-color: white,
} ;
```

Add a navbar burger anchor like explained in the docs

### Expected behavior

The burger spans become white.

### Actual behavior

The burger spans get the link color.

**Comment by digitigradeit** [comment]
Same with $navbar-item-color... and the docs for navbar are missing the variable references too but for other pages its fine.

Hey @jgthms The default navbar-burger-color is set to `$navbar-burger-color: cv.getVar("navbar-item-color") !default;`

But I can't find where that's specified and the closest thing is: `"navbar-item-color-l": #{$navbar-item-color-l},`

Shouldn't there also be a `$navbar-item-color-h: cv.getVar("text-h");` and `$navbar-item-color-s: cv.getVar("text-s");` and then a resulting `$navbar-item-color: (...);` referencing those 3 but I can't figure it out.

**Comment by tjwalch** [comment]
The same also goes for `$pagination-current-color` and `$pagination-current-background-color`, they always stay `$link-invert` and `$link` respectively no matter what values you specify in the `ẁith` clause.
