### ISSUE TITLE
Skeleton class is orange instead of gray

### ISSUE THREAD

**Issue by thesn10** [jgthms/bulma#3759]
https://github.com/jgthms/bulma/blob/d2687d444c907893a6feb8733404364b871a94d5/sass/base/skeleton.scss#L116-L126

![image](https://github.com/jgthms/bulma/assets/38666407/bcf931ab-f79f-48c0-b2e9-cb1d97a5f5dd)
![image](https://github.com/jgthms/bulma/assets/38666407/0a9ac42f-4431-4988-8401-dd64c56faafe)

The orange only occurrs in `skeleton` class but not in `skeleton-block` or `skeleton-lines`

**Comment by jgthms** [comment]
Actually that class shouldn't exist. I'll remove it.
