### ISSUE TITLE
fixed-grid has-auto-count not working?

### ISSUE THREAD

**Issue by leolivier** [jgthms/bulma#3763]
### Overview of the problem
I don't know if I'm missing something but I can't get fixed-grid has-auto-count working.
I am using bulma 0.9.3
I tried in Firefox and in Edge

### Description
I copy/pasted the example for "fixed-grid has-auto-count" from https://bulma.io/documentation/grid/fixed-grid/ and tried it but all cells are showing on their own line.
To make sure bulma is up and running, I used some bulma classes inside cells and it's working.

### Steps to Reproduce
Try with this piece of html copy/pasted from https://bulma.io/documentation/grid/fixed-grid/ where I just added the link to Bulma cdn and a button for the first cell to show bulma is loaded :
```html
<html>
  <head>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>
    <div class="fixed-grid has-auto-count">
      <div class="grid">
        <div class="cell"><button class="button is-primary">Cell1</button></div>
        <div class="cell">Cell 2</div>
        <div class="cell">Cell 3</div>
        <div class="cell">Cell 4</div>
        <div class="cell">Cell 5</div>
        <div class="cell">Cell 6</div>
        <div class="cell">Cell 7</div>
        <div class="cell">Cell 8</div>
        <div class="cell">Cell 9</div>
        <div class="cell">Cell 10</div>
        <div class="cell">Cell 11</div>
        <div class="cell">Cell 12</div>
        <div class="cell">Cell 13</div>
        <div class="cell">Cell 14</div>
        <div class="cell">Cell 15</div>
        <div class="cell">Cell 16</div>
      </div>
    </div>
  </body>
</html>
```

### Expected behavior
Cells should show on several columns, the number of which depending on the size of the screen

### Actual behavior
Only one column whatever the size of the screen:
![image](https://github.com/jgthms/bulma/assets/4014752/f884805d-7cb6-4cfc-b6cd-5f6a0e224e48)

**Comment by jgthms** [comment]
You're using the 0.9.3 version. You need the 1.0.0
