### ISSUE TITLE
bulma.css size almost triple from 0.9.4 to 1.0.0

### ISSUE THREAD

**Issue by dirslashls** [jgthms/bulma#3771]
This is a question about Bulma 1.0.0

### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I am currently using Bulma 0.9.4 and looking at moving to 1.0.0 as it has many desired features like css variables and prefixing. However, I see that the bulma.css file in 0.9.4 is about 245KB while 1.0.0 is 730KB (both from jsdelivr). What is the reason for such a large increase in size? Anyway to reduce that.

**Comment by kasperkamperman** [comment]
I already addressed here: https://github.com/jgthms/bulma/issues/3761
