### ISSUE TITLE
Why is there no prefixed lightmode-only version?

### ISSUE THREAD

**Issue by robertosw** [jgthms/bulma#3779]
This is about **Bulma (Feature Request / Question)**.

I feel like this would be an easy "fix" in the build pipeline

**Comment by wesdevpro** [comment]
@robertosw could you create a feature request version of this issue(that is an issue that ask for prefixed lightmode-only be implemented)? Clearly Bulma V1 was designed intentionally. Therefore, if you would like to see a particular change, just create a feature request version of this issue rather then an issues that questions the current design. Thanks ☕
