### ISSUE TITLE
Stylus source

### ISSUE THREAD

**Issue by rogervila** [jgthms/bulma#378]
* is it a bug/feature/question or do you need help? YES

### Checklist

* [ X] This is about the Bulma **CSS framework**
* [ X] I am sure this issue is **not a duplicate**?

### Description

Is it planned to have a stylus source?
If not, I'd be happy to collaborate on it.

**Comment by jgthms** [comment]
It is not planned no, as I've never used stylus. But feel free to make a version!

**Comment by groenroos** [comment]
I have translated Bulma to Stylus [over here](https://github.com/groenroos/bulma-stylus). It should have 1:1 functional parity, and the exact same documentation should apply. The only caveat is that if you want to override `$colors`, you'll need to use Stylus' hash format.

**Comment by atilkan** [comment]
@groenroos Can you update? That is good work. Should be included in Bulma.
