### ISSUE TITLE
New patch release planned?

### ISSUE THREAD

**Issue by tonprince** [jgthms/bulma#3780]
I'm a big fan of Bulma, thanks for this great piece of CSS framework. I'm wondering if there's a new patch release planned for Bulma 1.0. I've noticed a few reported major and minor issues and wasn't sure if there's any upcoming activity to address them.

**Comment by zhaolinlau** [comment]
@jgthms

**Comment by jgthms** [comment]
Probably by the end of this month.

**Comment by tonprince** [comment]
Thanks
