### ISSUE TITLE
Docs: 3 pages have different sidebar behavior

### ISSUE THREAD

**Issue by Concibar** [jgthms/bulma#3782]
This is about **the Docs**, specifically a layout bug on the website.

### Overview of the problem

My **browser** is: Brave (Chromium)

Webiste behaves inconsistently on different pages

### Description

When you Go to the [Docs website](https://bulma.io/documentation/) the left-side-menu is always visible, no matter which sub-point you navigate to.
EXCEPT the first three pages under the "Layout" tag ["container"](https://bulma.io/documentation/layout/container/), ["hero"](https://bulma.io/documentation/layout/hero/) and ["section"](https://bulma.io/documentation/layout/section/). Those three let the side-bar collapse to the left. The area to let the side-bar pop back out is incredibly narrow. I'd expect the sidebar to always collapse or never. Personally I'd prefer it to never collapse. It would be nice though if it had it's own scrolling enabled, so it would stick to the top when you scroll through a long page.

Thanks :)

**Comment by jgthms** [comment]
Yes it's on purpose for those pages because those components are better displayed on a full width page.
