### ISSUE TITLE
.content & Wordpress WYSIWYG

### ISSUE THREAD

**Issue by kennedybaird** [jgthms/bulma#379]
### Checklist

* [x] This is about the Bulma **CSS framework**
* [x] I'm using Bulma **version** [0.2.3]
* [x] My **browser** is: Chrome
* [x] I am sure this issue is **not a duplicate**?

### Description

Using HTML5 Blank theme on Wordpress with Bulma, when applying the .content style to article content.

This renders everything correctly except for the alignment of attached images, as the Wordpress WYSIWYG editor applies .alignright & .alignleft styles to the images.

There are potentially more issues, but I have only needed this so far.

### Solution

Adding the following styles to /elements/content.sass

```sass
& .alignright
  float: right
& .alignleft
  float: left
```

**Comment by jgthms** [comment]
This is too specific for a CSS framework, as it would require to support any upcoming changes done by WordPress, and would mean some people might request to support other platforms like Tumblr, Ghost, Joomla...
