### ISSUE TITLE
element input, with date attribute

### ISSUE THREAD

**Issue by ericxin1982** [jgthms/bulma#3790]
Hi @Zerquix18 

If I have input with date attribute, is it ok?
Since I saw the input css has no date attribute support.

Thanks
Eric Xin

**Comment by Ijee** [comment]
I am not the one you tagged but what do you mean exactly?

Because this works just fine (v1) but isn't explicitly mentioned in the docs:

``` html
    <input
           class="input is-primary"
           type="date"
           value="2024-04-17"
           min="2024-04-17"
           max="2024-12-31"/>
```

![image](https://github.com/jgthms/bulma/assets/15277745/19d2dc4d-7fc3-46c5-904d-1c594ca0de05)

**Comment by ericxin1982** [comment]
You are nice. Thanks!
