### ISSUE TITLE
In Bulma 1 breadcrumbs seem to be broken

### ISSUE THREAD

**Issue by mikesmartbonds** [jgthms/bulma#3796]
In bulma 0.9.4 when using breadcrumbs the active breadcrumb is a different color than the ones that are inactive. In bulma 1.0.0 they are all the same color in light theme. In the dark theme this does not seem to be an issue.

**Comment by rob-rountree-cyted** [comment]
Duplicates https://github.com/jgthms/bulma/issues/3769.

**Comment by mikesmartbonds** [comment]
Cool, I added a comment to the other issue, and am closing this one.
