### ISSUE TITLE
v1.0 breadcrumbs not alligned properly when content is parent container

### ISSUE THREAD

**Issue by bcovy** [jgthms/bulma#3798]
This is about Bulma

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 1.0.0

### Description
Using ```breadcrumbs``` within a parent element that uses ```content```, ```margin-top``` is not applied to the first list item in a ```ul``` element.

### Steps to Reproduce

```html
<div class="content">
   <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="#">Bulma</a></li>
        <li><a href="#">Documentation</a></li>
        <li><a href="#">Components</a></li>
        <li class="is-active"><a href="#" aria-current="page">Breadcrumb</a></li>
    </ul>
  </nav>
</div>
```

![image](https://github.com/jgthms/bulma/assets/26151853/2f719d31-eb17-417f-9162-0d20b2a279b0)

### Expected behavior

Using ```content``` as a container, ```breadcrumbs``` should all share the same margin top value.

**Comment by willoma** [comment]
There are multiple rules in `.content` that make other components borked, I have also seen a margin-bottom problem on another component (however I can't remember which one).

I think the point is that we should **not** put other components/elements in `.content`

**Comment by bcovy** [comment]
Thanks for your input.  After reviewing the doc a few more time, I'm going to mark this a closed as I don't think `content` was intended to include support for `breadcrumbs`.
