### ISSUE TITLE
Columns is-variable not working

### ISSUE THREAD

**Issue by JoeyRumble** [jgthms/bulma#3799]
This is about **Bulma & the Docs**.

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma & Docs
I'm using Bulma 1.0
My **browser** is: Chrome

### Description

The columns 'is-variable' class with the different column gap class modifiers are not working. Neither on the document page (https://bulma.io/documentation/columns/gap/).

**Comment by willoma** [comment]
I can confirm the behaviour.

I have tracked this down to https://github.com/jgthms/bulma/blob/72e99d1bf206e0c0a697b926282a0bea5dd23059/sass/grid/_index.scss#L4

This line imports [columns.scss](https://github.com/jgthms/bulma/blob/72e99d1bf206e0c0a697b926282a0bea5dd23059/sass/grid/columns.scss), however the `is-variable` stuff is in [columns-v2.scss](https://github.com/jgthms/bulma/blob/72e99d1bf206e0c0a697b926282a0bea5dd23059/sass/grid/columns-v2.scss).

**Comment by janosrusiczki** [comment]
OK, so I'm not the only one.

It doesn't seem to be working in their documentation either: https://bulma.io/documentation/columns/gap/#variable-gap

I'm not exactly sure what should be happening, probably one should be able to click the .is-x class names and the example below should modify accordingly, but it doesn't work.

So I guess I'll be waiting until this gets fixed.

**Comment by phil-w** [comment]
Yeah I can't get the columns to work very well at all, in general. The GRID seems more like it might be working.

**Comment by reneedraper** [comment]
I did a little investigating...it looks like 

1. it's not being forwarded in `sass/grid/_index.scss` 
2. it's not included in the parse-vars script `docs/_scripts/parse-vars.js`

There's also something with the column-gap not being overwritten by the new assigned values, I'll probably dig into this more next week.
