### ISSUE TITLE
This is a test issue

### ISSUE THREAD

**Issue by MarcusLongmuir** [jgthms/bulma#380]
### PLEASE READ THE FOLLOWING INSTRUCTIONS

Tag your issue accordingly:

* is it about Bulma or about the Docs?
* is it a bug/feature/question or do you need help?
* if it's a bug, is it a browser bug?

Thanks for helping out! 😇

Please remove any unused content (including these instructions) before submitting your issue.

### Checklist

* [ ] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [ ] I'm using Bulma **version** [x.x.x]
* [ ] My **browser** is:
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [ ] I am sure this issue is **not a duplicate**?

### Description

_[Description of the bug, enhancement, or question]_

### Steps to Reproduce

1. _[First Step]_
2. _[Second Step]_
3. _[and so on...]_

### Expected behavior

_[What you expected to happen]_

### Actual behavior

_[What actually happened]_

**Comment by kukac7** [comment]
@MarcusLongmuir 
![](http://i.giphy.com/1M9fmo1WAFVK0.gif)

**Comment by jgthms** [comment]
As the title mentions, "This is a test issue". I asked my coworker to try labeling the issue himself. But apparently, non-contributors are not allowed to label issues themselves.

Hence why this issue was opened and closed within 2 minutes. Locking the conversation now.
