### ISSUE TITLE
Tag default color is not what I thought it would be

### ISSUE THREAD

**Issue by EdJoPaTo** [jgthms/bulma#382]
### Checklist

* [ ] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [X] I'm using Bulma **version** [0.2.3]
* [X] My **browser** is: Chromium, Firefox, Safari (iOS)
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [X] I am sure this issue is **not a duplicate**?

### Description

The tag default background-color is `whitesmoke`. All other colors are hex colors so i wondered. Took a look into the `.tag` [sass code](https://github.com/jgthms/bulma/blob/master/sass/elements/other.sass#L67) and there the background-color is `$background`. `$background` is defined as `$grey-lighter` as the [variable doc page](http://bulma.io/documentation/overview/variables/) is saying. So i would expect the tag to be `#dbdbdb` instead of `whitesmoke`. (By the way, that would improve the `.tag` contrast to the background)

I don't know where the bug is in here (could be a wrong documentation or something in the sass code.

### Steps to Reproduce

```html
<span class="tag">I'm awesome!</span>
```

### Expected behavior

![shouldbe_trim](https://cloud.githubusercontent.com/assets/7953011/20217947/a5f617bc-a822-11e6-904c-080f098d9dc2.png)

### Actual behavior

![current_trim](https://cloud.githubusercontent.com/assets/7953011/20217949/aa443dc6-a822-11e6-8857-097ede50ea65.png)

**Comment by jgthms** [comment]
That's how sass compiles hex codes. It replaces them with the appropriate name color, if possible.

I agree it's not ideal. I wonder if there's a setting somewhere.

**Comment by EdJoPaTo** [comment]
That's interesting to know.
But `whitesmoke` is `#f5f5f5` and not `#dbdbdb` what i thought the `.tab` background-color would be.

**Comment by Talor-A** [comment]
I found [this](http://stackoverflow.com/questions/9611571/can-i-turn-off-sass-rgb-color-name) on stackoverflow, though I don't know how you'd go about implementing it.
