### ISSUE TITLE
Overriding $scheme-h

### ISSUE THREAD

**Issue by nioc** [jgthms/bulma#3824]
This is about **Bulma**.
It's a feature/question

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [1.0.1]

### Description
 
I would like to change easily the scheme variable and all derived variables by simply overriding `$scheme-h` and `$scheme-s` in initial variables but it is not allowed.

The only way is to create themes but this add a lot of code duplication (and maintainability issue) from original theme.

**Comment by jgthms** [comment]
That's a good point. These variables are missing the `!default` tag.
