### ISSUE TITLE
Grid cells are too small

### ISSUE THREAD

**Issue by melTr** [jgthms/bulma#3829]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [1.0.1] 
I am sure this issue is **not a duplicate** 

### Description

I tried both versions of grids but I'm not able to get what I need : a grid of pictures.
Using smart grid, even at is-col-min-12, the images are too small. I will need a 32rem. But I don't see possibility to change via sass variables?
By using fixed grid with 3 columns, I found the column gap too small. But it seems I can't use _is-column-gap-x_?

### Expected behavior

Grid with bigger images.

Thanks!

**Comment by jgthms** [comment]
I'm increasing the number to 32, which is a maximum of `768px`.
