### ISSUE TITLE
RTL Support Issues in Bulma v1

### ISSUE THREAD

**Issue by smileys53** [jgthms/bulma#3830]
I am experiencing several issues related to RTL (Right-to-Left) support in Bulma v1:

**Missing bulma-rtl files:** The bulma-rtl files are not available in the package. Additionally, these files are not accessible via the two popular CDNs, jsDelivr and cdnjs.

**SASS Compilation Issues:** I attempted to generate the RTL files using the `$rtl: true;` flag in SASS, but it did not produce the expected results.

**Lack of Documentation:** There is no documentation regarding RTL support on the Bulma website. This makes it challenging to implement and troubleshoot RTL support.

I would like to know if RTL support is still available in Bulma v1. If so, could you please provide guidance on how to properly implement it, including access to the bulma-rtl files and the correct SASS configuration? Additionally, it would be helpful to have updated documentation on the website regarding RTL support.

**Comment by jgthms** [comment]
What issues are you having? V1 makes use of logical properties such as `margin-inline-start` which are text direction agnostic.

**Comment by asmanp2012** [comment]
On the document wrote that anyone who wants to use the RTL version should load the RTL file but it does not exist.

Please remove this part of the document or add this file.
I don't know main version has any problem with RTL or not but in the first look I think have no problem.

**Comment by smileys53** [comment]
The main version is working fine so far for my RTL project. One issue I found is with the "form field with add-ons," as shared in the screenshot below.
<img width="429" alt="Screenshot 2024-05-29 at 12 53 23 PM" src="https://github.com/jgthms/bulma/assets/84571594/c037777a-feed-4908-a90b-6567226ef454">
