### ISSUE TITLE
SCSS: This variable was not declared

### ISSUE THREAD

**Issue by rhoudroge** [jgthms/bulma#3841]
This is about **Bulma**.

### Overview of the problem

This is about the Bulma **CSS framework** and compiling an SCSS file that used to work with v0.9

### Description

Hi!
Thanks for the great work maintaining Bulma! I've been very happy using this framework.
I am upgrading from 0.9 to 1.0, and it seems some customisation variables have disappeared, such as `$navbar-item-color` with SASS now showing this error: `Error: This variable was not declared with !default in the @used module.`
Could you please let me know how to deal with these variables, I have a number of them in my source file?
Thanks!

### Steps to Reproduce

1. Define the above variable in the scss file when importing navbar using the `with` directive
2. Compile the SCSS file

### Expected behavior

SCSS compiles correctly

### Actual behavior

The actual compilation results in the above error.

**Comment by ekrister** [comment]
Having the same problem, I'm missing the possibility to edit the following after updating to Bulma 1.0:

$input-border-color
$input-hover-border-color
$button-hover-border-color
$input-focus-box-shadow-size
$input-focus-box-shadow-color

By the way, the need to edit these settings is related to accessibility.

**Comment by jgthms** [comment]
`$navbar-item-color` was restored in this commit: https://github.com/jgthms/bulma/commit/66336ea4f2a9603e5f2b682e7b8180cd9be7f421

As for the `$input` ones, I'm gonna restore them now.

**Comment by rhoudroge** [comment]
Hi @jgthms , thanks a lot for your feedback! I am using a number of them that I haven't listed here. Should I raise another issue or would you rather I list them here ?

**Comment by jgthms** [comment]
Can you please raise another issue? Thank you.
