### ISSUE TITLE
Sponsorship follow up - Teravision

### ISSUE THREAD

**Issue by Teravision-Technologies** [jgthms/bulma#3843]
This is about **Bulma | the Docs**.

 X

### Actual behavior

![Image20240610170250](https://github.com/jgthms/bulma/assets/172320865/9c30797f-067e-41d5-9cff-34eefecb9ec4)

https://www.teravisiontech.com/

**Comment by Teravision-Technologies** [comment]
Hi we are still waiting for this thank you

**Comment by jgthms** [comment]
Hi, please send your details to the following address:

![image](https://github.com/jgthms/bulma/assets/1254808/4461c33c-c3ae-4512-b979-57fc2e0b928a)
