### ISSUE TITLE
Footer overlaps content on small screens / zoom

### ISSUE THREAD

**Issue by xtlc** [jgthms/bulma#3850]
This is about the Bulma **CSS framework**
I'm using Bulma **version** 1.0.0
My **browser** is: FF, Chrome, Safari on iOS

### Description

I have a straightforward page:

```
<head>
</head>
<body>
    <nav>
    </nav>
    <div id="main">
    </div>
    <footer class="footer has-background-info>
        <div class="content has-text-centered has-background-danger">
            test
            <br>
            <i>by me</i>     
        </div>
    </footer>
</body>
```

and inside the main div I use HTMX / JS to insert and switch parts of the page which works just fine. Until I use the zoom or a mobile device rotated, so that the vertial space is limited.
If I zoom in to the point where the last content from main div comes to the bottom of the page, the footer overlaps that content.

I tried

    adding a mt-1 to the footer's class
    putting a div with mt-1 between the main div and the footer

both with no effect. How can I ensure, the footer stays away from the content, preferable with some space of distance?

![image](https://github.com/jgthms/bulma/assets/14292046/eddd0efc-2eee-46a0-9970-0c8a8155af9c)

**Comment by jgthms** [comment]
It's probably coming from the rest of the CSS. Do you have it?

**Comment by xtlc** [comment]
Obvious but good thinking. I worked through the rest of the CSS and found out footer is defined as follows:

```
footer {
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 30;
  max-height: 20px;
  position: fixed;
}
```

removing `position: fixed;` seems to fix the problem.

**Comment by jgthms** [comment]
That CSS is not coming from Bulma. It's probably coming from the framework you use.
