### ISSUE TITLE
Fix SASS deprecation of the navbar.scss

### ISSUE THREAD

**Issue by sank64** [jgthms/bulma#3858]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bulma@1.0.1` for the project I'm working on.

The issue is referenced in this thread: https://github.com/jgthms/bulma/issues/3856#issuecomment-2241354306

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bulma/sass/components/navbar.scss b/node_modules/bulma/sass/components/navbar.scss
index c755aff..ea07327 100644
--- a/node_modules/bulma/sass/components/navbar.scss
+++ b/node_modules/bulma/sass/components/navbar.scss
@@ -254,9 +254,12 @@ body {
 .#{iv.$class-prefix}navbar-burger {
   @extend %reset;
   @include mx.burger(2.5rem);
-  align-self: center;
-  margin-inline-start: auto;
-  margin-inline-end: 0.375rem;
+
+  & {
+    align-self: center;
+    margin-inline-start: auto;
+    margin-inline-end: 0.375rem;
+  }
 }
 
 .#{iv.$class-prefix}navbar-menu {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jgthms** [comment]
Thanks. It's the solution for #3856
