### ISSUE TITLE
Layout now render properly . @jgthms

### ISSUE THREAD

**Issue by OmprakashR** [jgthms/bulma#3865]
This is about **Bulma | the Docs**.

### Overview of the problem
URL :https://bulma.io/documentation/sass/mixins/
URL : https://bulma.io/documentation/sass/responsive-mixins/

### Description
Observation: Layout not rendered properly   **bd-docs-lead**  layout is cut from right side data not visible.
need to modify in **.highlight**  to fix this issue .

### Steps to Reproduce
 I try his approach 
`.highlight {
    background-color: var(--hl-gray-09);
    border-radius: var(--hl-radius);
    color: var(--hl-gray-03);
    font-size: .875em;
    position: relative;
    **display: grid;**
}`

### Expected behavior
![Bulma-Sass-Responsive-Mixins-Bulma-Free-open-source-and-modern-CSS-framework-based-on-Flexbox-new](https://github.com/user-attachments/assets/effd6d74-ff77-4004-a09b-a7fc3ab90260)

### Actual behavior
![Bulma-Sass-Responsive-Mixins-Bulma-Free-open-source-and-modern-CSS-framework-based-on-Flexbox](https://github.com/user-attachments/assets/86a8119c-0afb-4aab-ac5d-0e4ab9607433)

    Hi @jgthms  Please look into this and fix. thank you!..

**Comment by Shaumik-Ashraf** [comment]
It's not just the mixins and responsive mixins pages, table page is also broken:

https://bulma.io/documentation/elements/table/#table-container

**Comment by jgthms** [comment]
This has been fixed in the latest commit and will be pushed. Thanks for reporting.
