### ISSUE TITLE
Feature request: Alternative to assign styles based on the tag name

### ISSUE THREAD

**Issue by fknipp** [jgthms/bulma#3870]
This is a feature request for Bulma.

### Overview of the problem

This is about the Bulma **CSS framework**. 
I'm using Bulma **1.0.2**

### Description

Using Bulma leads to HTML code with redundant information, e. g.

```html
<h1 class="title is-1">Header 1</h1>
<section class="section">…</section>
<table class="table">…</table>
<input class="input">…</input>
```

I really like the idea of the alternative versions like the one with the `bulma-` prefix.

So, I suggest to offer an alternative to write the above just without the `class` attributes:

```html
<h1>Header 1</h1>
<section>…</section>
<table>…</table>
<input>…</input>
```

The resulting HTML would be shorter and better readable. Furthermore, it would help to apply Bulma to an existing, unstyled HTML document.

**Comment by jgthms** [comment]
While it reduces the amount of code, it won't cover all Bulma features. For example, `<input type="checkbox">` would not work with the `.input` styles.

Other features like the pagination or the menu or the columns would not be possible with only tag names.
