### ISSUE TITLE
Importing Bulma in Create React App

### ISSUE THREAD

**Issue by hnordt** [jgthms/bulma#388]
When importing Bulma in Create React App, if you do this:

```js
import 'bulma'
```

You'll receive this error:

```
Error in ./~/bulma/bulma.sass
Module parse failed: /Users/hnordt/workspace/superlab/node_modules/bulma/bulma.sass Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
```

But, if you do this:

```js
import 'bulma/css/bulma.css'
```

It'll work as expected.

This happens because Create React App doesn't handle SASS files.

Would be nice if instead of exporting SASS file as the default module, it exports the CSS file.

**Comment by CanRau** [comment]
you saved my day :-)

**Comment by designcourse** [comment]
Strange.. I converted my Create React App to accept Sass files, and it does render custom sass files that I create.. However, when I import 'bulma', it gives me no errors, yet does not actually import / render the framework.

**Comment by tomasantonj** [comment]
This does not work for a sass-configured create-react-app app:

`import 'bulma'`

No errors but no imports either.

This works: 

`import 'bulma/css/bulma.css'`

But feels dirty. :/

**Comment by hnordt** [comment]
@tomasantonj it's not dirty, it's ok. You are just importing a file directly. It's the same as importing a CSS file locally: `./my/cool/sheet.css`.

**Comment by tomasantonj** [comment]
Dirty as opposed to elegant :)

**Comment by enzocaminos** [comment]
Thank you very much! :)

**Comment by MaxOrelus** [comment]
Using `create-react-app` has compiling issues w/this repo using `node-sass-chokidar`. I've pasted the following errors below. Also, would you be open to changing the extension to `scss` rather than `sass`?

```
{
  "status": 1,
  "file": "/Users/me/Projects/platform/node_modules/bulma/sass/elements/button.sass",
  "line": 132,
  "column": 29,
  "message": "argument `$color` of `darken($color, $amount)` must be a color\n\nBacktrace:\n\tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n\tnode_modules/bulma/sass/elements/button.sass:132",
  "formatted": "Error: argument `$color` of `darken($color, $amount)` must be a color\n\n       Backtrace:\n       \tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n       \tnode_modules/bulma/sass/elements/button.sass:132\n        on line 132 of node_modules/bulma/sass/elements/button.sass\n>>           background-color: darken($color-invert, 5%); }\n   ----------------------------^\n"
}
=> changed: /Users/me/Projects/platform/src/helpers/theme.scss
{
  "status": 1,
  "file": "/Users/me/Projects/platform/node_modules/bulma/sass/elements/button.sass",
  "line": 132,
  "column": 29,
  "message": "argument `$color` of `darken($color, $amount)` must be a color\n\nBacktrace:\n\tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n\tnode_modules/bulma/sass/elements/button.sass:132",
  "formatted": "Error: argument `$color` of `darken($color, $amount)` must be a color\n\n       Backtrace:\n       \tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n       \tnode_modules/bulma/sass/elements/button.sass:132\n        on line 132 of node_modules/bulma/sass/elements/button.sass\n>>           background-color: darken($color-invert, 5%); }\n   ----------------------------^\n"
}
=> changed: /Users/me/Projects/platform/src/helpers/theme.scss
{
  "status": 1,
  "file": "/Users/me/Projects/platform/node_modules/bulma/sass/elements/button.sass",
  "line": 132,
  "column": 29,
  "message": "argument `$color` of `darken($color, $amount)` must be a color\n\nBacktrace:\n\tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n\tnode_modules/bulma/sass/elements/button.sass:132",
  "formatted": "Error: argument `$color` of `darken($color, $amount)` must be a color\n\n       Backtrace:\n       \tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n       \tnode_modules/bulma/sass/elements/button.sass:132\n        on line 132 of node_modules/bulma/sass/elements/button.sass\n>>           background-color: darken($color-invert, 5%); }\n   ----------------------------^\n"
}
=> changed: /Users/me/Projects/platform/src/helpers/theme.scss
{
  "status": 1,
  "file": "/Users/me/Projects/platform/node_modules/bulma/sass/elements/button.sass",
  "line": 132,
  "column": 29,
  "message": "argument `$color` of `darken($color, $amount)` must be a color\n\nBacktrace:\n\tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n\tnode_modules/bulma/sass/elements/button.sass:132",
  "formatted": "Error: argument `$color` of `darken($color, $amount)` must be a color\n\n       Backtrace:\n       \tnode_modules/bulma/sass/elements/button.sass:132, in function `darken`\n       \tnode_modules/bulma/sass/elements/button.sass:132\n        on line 132 of node_modules/bulma/sass/elements/button.sass\n>>           background-color: darken($color-invert, 5%); }\n   ----------------------------^\n"
}
```

**Comment by rtmalone** [comment]
For posterity's sake, here's how you can set up a customized Bulma after configuring your `create-react-app` app using the [suggested preprocessor set up from the docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc).

```
//  src/theme.scss

@import 'bulma/sass/utilities/initial-variables.sass';

// your customization as described in the Bulma docs

@import 'bulma/bulma.sass';
```

Then import `theme.scss` somewhere at the top of your app. I put it in `index.js`.

**Comment by rluncasu** [comment]
1.@rtmalone why the first import ? bulma.sass already does @import "sass/utilities/_all" which in turn import initial-variables.sass
2.I can't get it to work after setting up [suggested preprocessor set up from the docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)
`  "status": 1,
  "file": "/Users/raduluncasu/_Projects/picturethis-theapp/src/styles/sass/base/generic.sass",
  "line": 1,
  "column": 25,
  "message": "Undefined variable: \"$white\"."`

I can understand the error, I just don't know why it's happening (as I mentioned earlier bulma.sass should import the file)

**Comment by mateioprea** [comment]
@rluncasu use this: 
```
"build-css": "node-sass-chokidar src/styles/main.scss -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/styles/main.scss -o src/ --watch --recursive",
```

**Comment by radjivC** [comment]
I don't get it, I did the tutorial with create-react-app and it looks fine but when I use bulma, its just nightmare 

```// 1. Import the initial variables
@import "bulma/sass/utilities/initial-variables";
@import "bulma/sass/utilities/functions";

// 2. Set your own initial variables
// Update blue
$blue: #72d0eb;
// Add pink and its invert
$pink: #ffb3b3;
$pink-invert: #fff;
// Add a serif family
$family-serif: "Merriweather", "Georgia", serif;

// 3. Set the derived variables
// Use the new pink as the primary color
$primary: $pink;
$primary-invert: $pink-invert;
// Use the existing orange as the danger color
$danger: $orange;
// Use the new serif family
$family-primary: $family-serif;

// 4. Setup your Custom Colors
$linkedin: #0077b5;
$linkedin-invert: findColorInvert($linkedin);
$twitter: #55acee;
$twitter-invert: findColorInvert($twitter);
$github: #333;
$github-invert: findColorInvert($github);

// 5. Add new color variables to the color map.
@import "bulma/sass/utilities/derived-variables.sass";
$addColors: (
  "twitter":($twitter, $twitter-invert),
  "linkedin": ($linkedin, $linkedin-invert),
  "github": ($github, $github-invert)
);
$colors: map-merge($colors, $addColors);

// 6. Import the rest of Bulma
@import "bulma/css/bulma.css"
```

I use the example and I have  ``` import 'mystyles.scss' ``` like this in my App files,
 I get this error

```{
  "status": 1,
  "file": "/Users/radjivcarrere/Documents/workspace/btb/invoice-customer-website/invoice-portal/client/src/containers/App/mystyles.scss",
  "line": 2,
  "column": 1,
  "message": "File to import not found or unreadable: bulma/sass/utilities/initial-variables.\nParent style sheet```

**Comment by whotemp** [comment]
Adding

```
resolve: {
  alias: {
    bulma$: path.resolve(__dirname, 'node_modules/bulma/css/bulma.css')
  }
}
```

to webpack.config.js makes it cleaner.

**Comment by mfish0005** [comment]
@whotemp I imagine you have to 'eject' for that solution?  

I'm also having trouble importing `bulma/sass/utilities/initial-variables` and my client isn't too keen on ejecting.

Seems like I can only `eject` or use a hacky solution if I want to override Bulma's initial variables =(

**Comment by whotemp** [comment]
@mfish0005 yes, needs to be ejected, sorry :/

**Comment by tatiesmars** [comment]
You don't need to ejected. As said in the ```create-react-app``` README : 
To enable importing files without using relative paths, you can add the ```--include-path``` option to the command in ```package.json```."

```
"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
```

**Comment by AndySoHotRightNow** [comment]
Just to recap what I did to make it work.

Working with **CSS**:

`import 'bulma/css/bulma.css'`

Working with **SASS**:

As described in the docs [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc), in `package.json`, add the following lines:

```
   "scripts": {
+    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
+    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
     "start": "react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test --env=jsdom",
```

Then, in the `src` directory, create a `theme.scss` file and within this file add the following line:

```
@import 'bulma/bulma.sass';
```

Import the `theme.scss` file in `index.js`:

```
// Bulma CSS:
import './theme.css'
```

Finally, build (or watch) the SASS files:

```
npm run build-css
```

**Comment by justinmpier** [comment]
If you're using @rtmalone's approach:

`
//  src/theme.scss

@import 'bulma/sass/utilities/initial-variables.sass';

// your customization as described in the Bulma docs

@import 'bulma/bulma.sass';
`

And are **not** using create react app, make sure that your webpack sass-loader can import from node_modules by setting includePaths:

`
{
    test: /\.(scss|sass)$/,
    use: [
        {
            loader: "style-loader"
        },
        {
            loader: "css-loader"
        },
        {
            loader: "sass-loader",
            options: {
                includePaths: ["node_modules"]
            }
        }
    ],
},
`

**Comment by tetreault** [comment]
New to create-react-app, mostly use vue at work. I couldn't get this working at all, so I just copied the bulma.min.css file into my src/css. ugly approach, but i just needed to get stuff done.

**Comment by HixOba** [comment]
I am just getting comfortable with React, and after sleepless hours trying to get bulma (sass) going in my CRA, i finally got it working, and here is what i did:

```
yarn add bulma
```
(which put bulma in my frontend as evidenced in my ```package.json```  (bulma + bulma-extensions)

Then, inside  ```index.js```  

```
import 'bulma/css/bulma.css
```

I then did  an ```yarn add node-sass-chokidar``` pre-processor, and then edited frontend  ```package.json``` by adding the following to the scripts:

```
"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
```

This now gave me the following in my frontend ```package.json```:

```
"scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
     "start": "react-scripts start",
     "build": "react-scripts build",
     "test": "react-scripts test --env=jsdom",
```

Then, in ```src``` (as advised by @AndySoHotRightNow) , i created ``` mystyles.scss ``` and attempted to add my custom variables etc. But here again i got stuck again,as i kept getting error messages when i imported only a few of the components which i felt i needed, node_modules obviously thought otherwise!

In the end, i hackened back to my Rails ways (i used bulma once before in a RoR project), and eventually got it working with this:

```
// Import the initial variables (only needed if you want to customise this file):
//@import "bulma/sass/utilities/initial-variables";
@import "bulma/sass/utilities/_all";
@import "bulma/sass/base/_all";

@import "bulma/sass/components/navbar";
@import "bulma/sass/components/menu";

@import "bulma/sass/elements/box";
@import "bulma/sass/elements/button";
@import "bulma/sass/elements/form";

@import "bulma/sass/layout/section"; 

// Your customisations go here...

// Set your own initial variables -  Add a serif family
$family-serif: "Merriweather", "Georgia", serif;

// Set the derived variables - Use the new serif family
$family-primary: $family-serif;

// Import the rest of Bulma:
@import "bulma/bulma.sass";
```

And then back in ```index.js``` i did an 

``` import  './mystyles.css' ``` which to be honest, i felt weird since i didnt have a ```mystyles.css``` but then, i thought - take risks, dont worry..

Then, when it came to the last step to watch, or to build, i was a bit stumped! My limited knowledge thought, build? No, way Jose! We are in development (not production, why "build" then? I thought some guys here wanna get me @AndySoHotRightNow am looking at you... Lol
But after trying  ```yarn run watch-css``` a few times and got nowt, wow! I thought, well...

Eventually, the courageous risk-taker that i am, i decided to (press the nuclear button) and used:

```yarn run build-css``` 

My plan was to uninstall the CRA app and start all over again if "ejected". 

I was therefore pleasantly surprised to see my ```mystyles.css``` file magically appear in ```src``` ! Now i have my bulma sass up and running, probably still in need of further refinement, but...

So, noobs, don your bulma hats and follw the ssteps i outlined above, and no need for a parachute vest!

**Comment by AnshulNautiyal** [comment]
Steps:

**1. npm install bulma**

Now I have Bulma in my node-modules folder. So I am assuming that if I do **import 'bulma'** in my App.js file then I will be able to access Bulma css in my project OR in my particular component. 

But I got the below error:-

Error in ./~/bulma/bulma.sass
Module parse failed: /Users/hnordt/workspace/superlab/node_modules/bulma/bulma.sass Unexpected character '@' (2:0)

The reason is that  Create React App doesn't handle SASS files. AND Bulma folder contains both SASS 
 and CSS files. 

Another option is to import like this: 

**import '../node_modules/bulma/css/bulma.css'**

This is fine but what if we want to import bulma like we import react.
Like this:
**import React from 'react'**

So How to import Bulma??

**2. npm install node-sass --save-dev**

we have node-sass folder inside node_modules folder.

Now you can import bulma in App.js file like this:

**import 'bulma';**

This way i did not get any error and i am able to quickly import bulma.

**Comment by MistyBlunch** [comment]
Thanks a lot <3

**Comment by Kaybarax** [comment]
> ```js
> import 'bulma'
> ```

UPDATE: Now it actually works, since they added support for .scss
