### ISSUE TITLE
Add container padding left and padding right

### ISSUE THREAD

**Issue by pst-82** [jgthms/bulma#3882]
Hello, I don't know if it's a bug or not, but in my opinion the left and right paddings are missing in the container class.

**Comment by Ijee** [comment]
I think it is intended to be like that because most other elements you'd put inside like columns all have gaps/paddings by default.

**Comment by jgthms** [comment]
It's not a bug. The container is simply meant to have a maximum width and be horizontally centered. 

If you require padding, you can add one of the helper classes.
