### ISSUE TITLE
[DOCS]: code snippet view of table section doesn't work

### ISSUE THREAD

**Issue by DomeT99** [jgthms/bulma#3899]
This is about Docs.
This is a bug in the table section of documentation

### Overview of the problem

I'm using Bulma version [1.0.2]
My browser is: Brave Browser

### Description
In the "table" section, the code snippet does not have the ability to be seen in full.
Section: https://bulma.io/documentation/elements/table/

![TableBug](https://github.com/user-attachments/assets/3a014c0a-fbfd-4139-9f0f-c317805725e4)

**Comment by jgthms** [comment]
I can see it here:
![image](https://github.com/user-attachments/assets/d13bb471-916e-4793-8bd4-5740f585a4be)

Do you see any error in the console?

**Comment by DomeT99** [comment]
Hi @jgthms 
The problem seems to be gone, now it works properly. 
Sorry for the useless issue

PS: obviously no error in the console.

**Comment by jgthms** [comment]
Hi @DomeT99 

Actually you were right. I was able to reproduce it and it was fixed as part of another issue.

**Comment by DomeT99** [comment]
Nice!
Thank you @jgthms :)
