### ISSUE TITLE
website css tables looks cut in half

### ISSUE THREAD

**Issue by eldemcan** [jgthms/bulma#3904]
This is about **Bulma | the Docs**.

### Overview of the problem

This is about the Bulma **Docs**

### Description

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/d774c8f5-dcfe-4771-a95a-4527ff49858c">

### Steps to Reproduce

Go to website in chrome via incognito

**Comment by jgthms** [comment]
I'm not sure what the issue is here?
