### ISSUE TITLE
Section docs update

### ISSUE THREAD

**Issue by hnordt** [jgthms/bulma#391]
In http://bulma.io/documentation/layout/section/, `.title` and `.subtitle` are wrapped in a `.heading`.

By reading `.heading` rules on https://github.com/jgthms/bulma/blob/master/sass/elements/other.sass, I think that `.title` and `.subtitle` shouldn't wrapped in a `.heading`.

If they do, would be good to have a explanation on what `.heading` does in the docs.

**Comment by AlgusDark** [comment]
@hnordt, actually, if you wrap `.heading` it's going to apply two rules `letter-spacing: 1px;` and `text-transform: uppercase;`. So... It's ok to wrap those classes.

With `.heading`:
![image](https://user-images.githubusercontent.com/818856/26889886-38caf468-4b75-11e7-9987-64ae6ec66ee9.png)

Without `.heading`:
![image](https://user-images.githubusercontent.com/818856/26889925-5753ccac-4b75-11e7-9424-c7255df9402c.png)

**Comment by AlgusDark** [comment]
@jgthms maybe this should be labeled as `is-question`.
