### ISSUE TITLE
Embedded Unsplash images are broken

### ISSUE THREAD

**Issue by theodorejb** [jgthms/bulma#3918]
This is a bug in the Bulma **Docs**, and I'm sure this issue is **not a duplicate**.

### Description

While reading https://bulma.io/documentation/sass/mixins/#center, I noticed that the `center()` mixin example has a broken image:

![broken-image](https://github.com/user-attachments/assets/d91431b3-42b3-42b7-b33e-7273422bcbd7)

The image `src` is https://source.unsplash.com/mEZ3PoFGs_k/192x192, which is a broken link.

I checked for other usages of `source.unsplash.com`, and found [there are 8 total references in the code](https://github.com/search?q=repo%3Ajgthms%2Fbulma%20source.unsplash.com&type=code), all of which are broken.

* The [`overlay()` mixin example](https://bulma.io/documentation/sass/mixins/#overlay) has a broken `background-image: url(https://source.unsplash.com/La2kOu2dmH4/640x320);`).
* The `center()` mixin example also has a broken `background-image: url(https://source.unsplash.com/xo3Bd2tYeqg/640x320);` (separate from the broken `<img>` I noticed first).
* The [`clearfix()` mixin example](https://bulma.io/documentation/sass/mixins/#clearfix) has a broken image (`src="https://source.unsplash.com/La2kOu2dmH4/160x160"`)
* The https://bulma.io/brand/ page has a bunch of broken background images on various `.bd-logos-item` divs (view page source and search for `source.unsplash.com`).
* Blog posts with a `post.image` defined display a broken image (e.g. https://versions.bulma.io/0.9.4/2018/04/13/website-redesign/)

### Steps to Reproduce

Open https://bulma.io/documentation/sass/mixins/#center, https://bulma.io/brand/, or https://versions.bulma.io/0.9.4/2018/04/13/website-redesign/ and notice the broken/missing images.

(Side note: blog posts don't seem to load at all on the latest version of the site. E.g. https://bulma.io/2018/04/13/website-redesign/ only displays "How to support Bulma". But this is a separate bug.)

### Expected behavior

Needed images should probably be hosted together with the docs rather than relying on a third-party site which can break at any time.

### Actual behavior

Images fail to load.

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
