### ISSUE TITLE
Is there an option to do something like is-small-mobile ? [is-question]

### ISSUE THREAD

**Issue by deathwebo** [jgthms/bulma#392]
### Question

I couldn't find neither on the docs or on the source code if there was the option to do something like:

`is-small-mobile`
`is-large-desktop`

Is it possible with the current options ?

This is to, for example, have a button being large on a large display or small on mobile.

Thanks!

**Comment by hnordt** [comment]
A workaround could be something like:

```html
<button class="button is-small is-mobile">Foo</button>
<button class="button is-large is-desktop">Foo</button>
```

But you'll need to repeat some code :(

**Comment by jgthms** [comment]
You can use the mixins: https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L1

I should document them. You can use them like this:

```
+mobile-only
  .your-button
    +button-small

+desktop
  .your-button
    +button-large
````

With this HTML:

```
<a class="button your-button">Click me</a>
```

**Comment by sinanerdem** [comment]
Is it possible to do that using CSS only, without SASS?

**Comment by jgthms** [comment]
Sure, just use [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries).

**Comment by RomainMazB** [comment]
Just an example in CSS-only without compilation for those who need as I did.
I needed to enlarge `hero is-medium` on mobile:
```CSS
@media screen and (max-width: 768px) {
    .hero.is-medium .hero-body {
        padding-bottom: 12rem;
        padding-top: 12rem;
    }
}
```

Don't forget to paste this script after the include of bulma.

**Comment by camillo777** [comment]
> A workaround could be something like:
> 
> ```
> <button class="button is-small is-hidden-desktop">Foo</button>
> <button class="button is-large is-hidden-touch">Foo</button>
> ```
> 
> But you'll need to repeat some code :(

And I guess the element ID (if any) would be duplicated...
I would love a "is-small-mobile" option as well!
