### ISSUE TITLE
Sass 1.80 deprecation warning of global built-in functions

### ISSUE THREAD

**Issue by olatoft** [jgthms/bulma#3920]
This is about Bulma.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 1.0.2

This is a **Sass** issue: I'm using version 1.80.2
I am sure this issue is **not a duplicate**

### Description

In Sass version 1.80 I get the following warning:

WARNING in ./<myFolder>/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./<myFolder>/style.scss)
Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 93, column 6 of file:///<path/to/my/repo>/node_modules/bulma/sass/utilities/functions.scss:93:6:
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use meta.type-of instead.

More info and automated migrator: https://sass-lang.com/d/import

93 |   @if type-of($color) != "color" {

node_modules/bulma/sass/utilities/functions.scss 94:7           bulmaColorLuminance()
node_modules/bulma/sass/utilities/functions.scss 128:7          bulmaFindColorInvert()
node_modules/bulma/sass/utilities/derived-variables.scss 16:15  @forward
node_modules/bulma/sass/utilities/_index.scss 6:1               @forward
node_modules/bulma/sass/_index.scss 1:1                         @use
node_modules/bulma/bulma.scss 4:1                               load-css()
src/Client/style.scss 40:1                                      root stylesheet

 @ ./<myFolder>/style.scss 8:6-221 20:17-24 24:7-21 50:25-39 51:36-47 51:50-64 55:6-65:7 56:54-65 56:68-82 62:42-53 62:56-70 64:21-28 75:0-191 75:0-191 76:22-29 76:33-47 76:50-64 53:4-66:5

### Steps to Reproduce

1. Start my project
2. Read output in console

### Expected behavior

No warning

### Actual behavior

Warning

**Comment by jgthms** [comment]
Duplicate

**Comment by olatoft** [comment]
Oh, sorry that I missed an issue that this is a duplicate of. Out of curiosity, what is it a duplicate of? I tried searching the existing issues, but the only half related issue I could find was #3907, which is a separate issue with a separate fix.

**Comment by jgthms** [comment]
Sorry you're right. I thought it was that same one. I'll reopen this.

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by ohabash** [comment]
`1.80.6 compiled with dart2js 3.5.4`
```
"bulma-scss": "^0.9.4",
"react": "18.3.1",
```

How do i fix?

**Comment by istudyatuni** [comment]
> How do i fix

Fix what? Warnings? dart-sass has a `quiteDeps` option to suppress them: https://stackoverflow.com/a/67836435
