### ISSUE TITLE
[SOLVED] Can "modal-content" be full page like 'modal-background' or just 640px?

### ISSUE THREAD

**Issue by tweed** [jgthms/bulma#394]
**UPDATE:** had a big personal breakthrough realizing that modals aren't needed! really great to simplify. best wishes to all.

**[FROM DOCUMENTATION]**
**modal-content:**  ... a maximum width of 640px, in which you can include any content 

**** THANK YOU -- !!**  kinda desperate as i don't want to have to add much JavaScript or modifications if possible.

ALL THREE MODAL examples are restricted in width by the bulma.css  i believe.
http://bulma.io/documentation/components/modal/

**can anyone help with getting modal-content to be full screen?**

**THIS IS THE PART OF THE BULMA CSS that affects i believe**

`.modal-content,
.modal-card {
  margin: 0 20px;
  max-height: calc(100vh - 160px);
  overflow: auto;
  position: relative;
  width: 100%;
}

@media screen and (min-width: 769px) {
  .modal-content,
  .modal-card {
    margin: 0 auto;
    max-height: calc(100vh - 40px);
    width: 640px;
  }
}`

**Comment by zeing** [comment]
i want like you

**Comment by aguirrel** [comment]
Hi @tweed could you elaborate "had a big personal breakthrough realizing that modals aren't needed!" a little? Thanks a lot!

**Comment by tweed** [comment]
NOW again using modal and have had recent help here
https://github.com/jgthms/bulma/issues/1722



Sorry **@aguirrel**   Sorry **@zeing**  -- i only found your comments this week.
"Nothing special - i just stopped trying modals)
  For months I decided to not use modals - one of the problems I have with modals (beling a begginer) is figuring out how to stop video or audio players from playing when I close modal - SO< i decided to use multiple HTML pages so then, of course, when the page is clsed the player stops.


I HAVE NOW gone back to using modals... and am hoping for more learning. (see link up top)

SO: you missed nothing - and I wish i had not said 'personal break-through' :-|

**Comment by gklijs** [comment]
I'm not really a front-ender, so I'm not sure if it's bad to keep it at max 640. But I'm creating a site to show of our cats, and the is a photo page, where you can see the picture in the 'original' size. Then it's a bit of a shame to only have them 640, but max with is also ugly, maybe something like 80%?
