### ISSUE TITLE
Stacked Font Awesome icon do not align properly

### ISSUE THREAD

**Issue by jgillich** [jgthms/bulma#395]
### Checklist

* This is about the Bulma **CSS framework**
*  I'm using Bulma **version** 0.2.3
* My **browser** is: Latest Chrome/Firefox

### Description

Stacked Font Awesome icons do not align properly in a media element.
![screenshot from 2016-11-23 21-25-07](https://cloud.githubusercontent.com/assets/347965/20577741/06b9b7c0-b1c4-11e6-8a0c-c7d8b30584bf.png)

### Steps to Reproduce

```
<article class="media">
  <div class="media-left">
    <figure class="icon is-large">
      <span class="fa-stack fa-lg">
        <i class="fa fa-credit-card fa-stack-1x"></i>
        <i class="fa fa-ban fa-stack-2x"></i>
      </span>
    </figure>
  </div>
  <div class="media-content">
    <div class="content">
      <p>
        <strong>Free</strong><br/>
        FooBarBaz
      </p>
    </div>
  </div>
</article>
```
### Expected behavior

The icon should align properly

### Actual behavior

The icon does not align properly

**Comment by tu5** [comment]
Any way to make it work in current bulma?

**Comment by tu5** [comment]
@jgthms

**Comment by snj33v** [comment]
any update?
