### ISSUE TITLE
Bulma in electron sass error

### ISSUE THREAD

**Issue by rakibtg** [jgthms/bulma#396]
I was trying to integrate bulma in electron, i did install it via npm

`npm install bulma --save`

To load bulma i simply imported the module,

`require( 'bulma' );`

But when i start the electron app in the console there is a sass compilation error(maybe)

> /home/user/Projects/camView/node_modules/bulma/bulma.sass:2 
> Uncaught SyntaxError: Invalid or unexpected token

What is the proper way to load bulma in a electron app or is it a bug?
![bulma - screenshot from 2016-11-24 21-34-03](https://cloud.githubusercontent.com/assets/5412730/20603880/c60d56c6-b28d-11e6-9e49-9e6cef6ff7fd.png)

**Comment by jgthms** [comment]
Are you compiling it as `sass` and not `scss`?

**Comment by VizuaaLOG** [comment]
I'm not familiar with electron but with NPM doesn't require expect a JS file? So that is a JavaScript syntax error? As you are trying to load bulma.sass as a JS module.

**Comment by jgillich** [comment]
Electron simply renders a web page, so open `index.html` and load `./node_modules/bulma/css/bulma.css` from there.
