### ISSUE TITLE
Coming from bootstrap, what's the main layout structural component? Columns or the Layout classes?

### ISSUE THREAD

**Issue by ryancole** [jgthms/bulma#397]
I'm just wanting to make sure that I am thinking in terms of bulma correctly.

I'm coming from bootstrap's grid system, where the main structural components were their grid (rows, columns). Basically everything else was meant to be placed somewhere inside of those. It was very easy to reason about because all you had to think in terms of was rows and columns.

Looking at bulma docs, I'm a bit confused at the moment. I see there is a grid system, but I also see that there are some additional structural styles under the Layout section (hero, section, footer). When I sit down to hammer out a layout, using bulma, should I be thinking in terms of a grid, like bootstrap? Should I be placing everything within this grid, including the Layout section styles (hero, section, etc)? Or does the grid exist inside those Layout section items?

The docs for [section](http://bulma.io/documentation/layout/section/) mention that they should be outer-most containers, which regarding HTML makes sense to me, but also makes me think the grid would exist inside sections, then?

Thanks!

**Edit**: I mostly ask because I've spent the past hour or so converting from bootstrap to bulma but haven't found myself using the grid system at all yet. I've been using sections, with containers in them, to setup my main centered page sections (mimicking what I'd get with bootstrap container and rows).

**Comment by VizuaaLOG** [comment]
@ryancole I believe the grid is to be used within the additional layout components. If you have a section with a container inside, this will centre your content, much like the row and container classes within Bootstrap. If you then need to have this section split into two, maybe with two columns of content. From my understanding, you would then use the grid to allow this. Although in most cases, from what I have seen, you don't need to use the grid too much as generally you just want a single, centred column. It would obviously vary depend on your use case.
