### ISSUE TITLE
Mobile version of nav is not working

### ISSUE THREAD

**Issue by SKyeTheMLGPro** [jgthms/bulma#400]
**Hi!** 
Got some issue with mobile navigation. Dropdown navigation or even mobile version is not working on any phone devises

[na-potrzebe-kursu-km.hol.es/o-mnie.html](url)

Feel free to take a look at the code and please help me figure it out. is-mobile isnt working

Regards

**Comment by jgthms** [comment]
You need to implement the javascript yourself, and toggle a CSS class.

**Comment by maarteNNNN** [comment]
```
this.toggleMenu = () => {
        var burger = document.querySelector('.nav-toggle');
        var menu = document.querySelector('.nav-menu');
        burger.classList.toggle('is-active');
        menu.classList.toggle('is-active');
    }
```
and in the html part in, which case I use pug(jade):

`span.nav-toggle(onClick='{toggleMenu}')`
