### ISSUE TITLE
The original arrow of the select control is not hidden in IE10+

### ISSUE THREAD

**Issue by superbull** [jgthms/bulma#401]
This is a Bulma bug.

### Checklist

* [x] This is about the Bulma **CSS framework**
* [x] I'm using Bulma **version** [0.2.3]
* [x] My **browser** is: IE11
* [x] I am sure this issue is **not a duplicate**?

### Description

The original arrow of the select control is not hidden in IE10+

![ie11-select-bug](https://cloud.githubusercontent.com/assets/455630/20788781/185ab6f8-b7ed-11e6-8a5c-4488c94b4cbf.jpg)

**Comment by superbull** [comment]
@jgthms It's just a simple fix, do you have time to merge this fix? We really need this it in IE.

**Comment by jgthms** [comment]
The PR is against the wrong repo. Also: you need to rebuild the files.

**Comment by superbull** [comment]
@jgthms My fault! I just create a new one. Thanks!

**Comment by DimitarChristoff** [comment]
:+1:
