### ISSUE TITLE
Keep mixins.sass for mixins-only

### ISSUE THREAD

**Issue by coxy** [jgthms/bulma#403]
In [mixins.sass](https://github.com/jgthms/bulma/blob/f7b2b6fc2f6768879a81cfff5292401e9dcddcde/sass/utilities/mixins.sass#L122-L126):

```sass
@keyframes spinAround
  from
    transform: rotate(0deg)
  to
    transform: rotate(359deg)
```

When requiring this file as a dependency in individual modules (using webpack etc) the above is output everywhere it's required, resulting in duplication. 

Maybe it can be moved elsewhere or wrapped in a sass mixin?

**Comment by kgdev** [comment]
Can we try to fix this ASAP?
