### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by cheykeodina** [jgthms/bulma#405]
### PLEASE READ THE FOLLOWING INSTRUCTIONS

Tag your issue accordingly:

* is it about Bulma or about the Docs?
* is it a bug/feature/question or do you need help?
* if it's a bug, is it a browser bug?

Thanks for helping out! 😇

Please remove any unused content (including these instructions) before submitting your issue.

### Checklist

* [x] This is about the Bulma **CSS framework**
* [x] I'm using Bulma **version** [0.2.3]

### Description

_[Is Bulma has dropdown menu like Bootstrap has]_

_[What you expected to happen]_

### I want any dropdown menu link bootstrap http://getbootstrap.com/components/#dropdowns

_[What actually happened]_

I spend a whole day to find is there any Bulma Dropdown Menu but I couldn't find it. I want to know that Bulma has dropdown menu component or not?

**Comment by jgthms** [comment]
It doesn't actually, because Bulma doesn't have any JS.
