### ISSUE TITLE
[Q] is there a way to vertically align an element to the bottom of the containing column?

### ISSUE THREAD

**Issue by primaveraentalca** [jgthms/bulma#407]
Hi guys, I hope someone can help me.
I have two columns like this:
```
<div class="box">
  <div class="columns">
    <div class="column is-half">
      <figure class="image is-square">
        <img src="http://placehold.it/500x500">
      </figure>
    </div>
    <div id="c2" class="column is-half">
      <div id="text" class="container">
        <p>hi, this is some text.</p>
      </div>
    </div>
  </div>
</div>
```
![columns](https://snag.gy/4Axbpz.jpg)

I need the text in the second column to be aligned to the bottom on the column.
I've tried ```
#text {
  position: relative;
  bottom: 0px;
}``` and ```#c2 {
  vertical-align: bottom !important;
}``` but it doesn't work.

Any sugestion on how to achieve this?
I've putted an [example](https://cdpn.io/e/QGJWPW) on codepen.

**Comment by ak5** [comment]
#c2 { margin-top: auto; }

**Comment by primaveraentalca** [comment]
@ak5 thanks you

**Comment by jonathanroy** [comment]
Could this solution be added as a default bulma feature?

**Comment by xiaojay** [comment]
> Could this solution be added as a default bulma feature?

+1

**Comment by asad-awadia** [comment]
@ak5 this moves everything in the column to the bottom

how do I do this for only a specific item?
