### ISSUE TITLE
Rounded Buttons

### ISSUE THREAD

**Issue by obonyojimmy** [jgthms/bulma#411]
Am having issues with creating rounded buttons : 
**Repro**
```
<button class="button is-medium is-pulled-right is-rounded">
            <span class="icon">
              <i class="fa fa-check"></i>
            </span>
 </button>

```
### Sass 
variables.sass
$radius-rounded: 50% !important

buttons.sass
```
=button-rounded
  border-radius: $radius-rounded
```
```
....
// Sizes
  &.is-rounded
    +button-rounded
...
```
**Result** 

The button becomes oval shaped , my intenntion is to make the button circle shaped

**Comment by jgthms** [comment]
Use a very high value for border-radius: `border-radius: 9999px;`

More info: http://cssreference.io/#border-radius
