### ISSUE TITLE
Bug: Table Cell .is-narrow will deform containing images

### ISSUE THREAD

**Issue by EdJoPaTo** [jgthms/bulma#412]
### Checklist

* [x] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [X] I'm using Bulma **version** [0.2.3]
* [X] My **browser** is: Chromium, Firefox, iOS Safari
* [ ] This is a **Sass** issue: I'm using version [x.x.x]
* [X] I am sure this issue is **not a duplicate**?

### Description

`td.is-narrow` should shrink the cell width to a smaller level and not deform content.

Currently `.is-narrow` will override every absolute `width` of elements below.

### Steps to Reproduce

```html
<table class="table">
  <thead>
    <tr>
      <th> Something </th>
      <th> Picture </th>
      <th> Description </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> Just some random content </td>
      <td class="is-narrow">
        <img class="image is-64x64" alt="bulma" src="https://raw.githubusercontent.com/jgthms/bulma/master/docs/images/bulma-icon.png" />
      </td>
      <td> Bulma Table </td>
    </tr>
  </tbody>
</table>
```

### Expected behavior

Image will stay at its desired size (in this example `.is-64-64`)

### Actual behavior

Image get deformed with the overridden `width: 1%;` rule:

![screenshot_trim](https://cloud.githubusercontent.com/assets/7953011/21293522/8d75d3d6-c527-11e6-84af-2a32417218d0.png)

**Comment by jgthms** [comment]
I would recommend not using `is-narrow` in this case. It's more suited for text content.
