### ISSUE TITLE
.container should have left/right margin of 20px (according to docs)

### ISSUE THREAD

**Issue by jwalton512** [jgthms/bulma#416]
From docs:

> On mobile and tablet, the container will have a margin of 20px on both the left and right sides.

This doesn't seem to occur and doesn't seem to be included in `elements/_other.sass`

I'll gladly submit a pull request, but not sure if docs are correct, or if source is correct.

**Comment by tommasosotte** [comment]
Also, on widescreen (>1180px) its max-width is `1200px`, and this is not explicitly said in the documentation, that does only says it is at most `960px` on >950px screen.

**Comment by keevitaja** [comment]
Any update on this?

I just started with bulma. Should i add side margins for container?

**Comment by jwalton512** [comment]
@jgthms are you able to provide an update -- i have no problem submitting a pull request.

**Comment by darylknight** [comment]
Just discovered this too. The stylesheet on the documentation is slightly different to the one downloaded. Docs has a max-width on the container. Neither the docs nor the download have a margin on the container.

Additionally, if you put a `.container` inside a `.section` as suggested in the docs, it's offset from the left, but falls off the page on the right. Screenshot taken with browser width at 1004px width.

![image](https://cloud.githubusercontent.com/assets/1250017/24763924/c185e4b8-1aea-11e7-8a6a-d7c9a9133277.png)

**Comment by darylknight** [comment]
Updates?

**Comment by ryanio** [comment]
+1?

**Comment by sacerdos82** [comment]
+1

**Comment by apocalyarts** [comment]
can confirm, the margins seem to be missing on mobile / tablet

**Comment by sejr** [comment]
Also having this issue.

**Comment by ryanio** [comment]
I used to believe this was an issue, but after becoming more familiar with Bulma I believe you're supposed to use sections, which have padding built into them: http://bulma.io/documentation/layout/section/

```html
<body>
  <section class="section">
    <div class="container">
      <h1 class="title">Section</h1>
      <h2 class="subtitle">
        A simple container to divide your page into <strong>sections</strong>, like the one you're currently reading
      </h2>
    </div>
  </section>
</body>
```

**Comment by jwalton512** [comment]
@ryanio that is what I end up doing.  my main reason for opening the issue was that the docs doesn't seem to match the source.  I'd be happy to submit a pull request, but not sure if it is the docs or the source that needs to be updated.

**Comment by matteomanf** [comment]
In the case of this issue added with the #1017 you have no margin on the menu in the only way it works fine.

**Comment by delphinas** [comment]
Any updates?

**Comment by jgthms** [comment]
There is a `$gap` variable now.

**Comment by vonj** [comment]
How would you use $gap variable?

**Comment by mobihack** [comment]
> How would you use $gap variable?

Using SCSS.

**Comment by wrabit** [comment]
@jgthms but there is no possibility to add it on mobile / tablet?
