### ISSUE TITLE
Using em for media queries

### ISSUE THREAD

**Issue by ThomasBracher** [jgthms/bulma#419]
This [article](https://zellwk.com/blog/media-query-units/) explains that using `em` for media queries is better in order to keep consistency across browsers if users set a custom font size.

Do you think this would be an interesting change? Being a beginner in those considerations, i do not know if working on it is relevant.

**Comment by jgthms** [comment]
It's an interesting idea but not really applicable in "real life". The thing is that screens widths are defined in pixels.

For example, if you have an ipad in portrait mode, you know it's 768px wide. Hence why one of the breakpoints in Bulma starts at 796px. Same for most laptops and mobiles.
