### ISSUE TITLE
New feature : Timeline

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#422]
### Description

I've created a new Timeline Feature to easily display a timeline like this
![Image of Timeline](http://oi66.tinypic.com/x1ni92.jpg)

**Can you add it to the repository if you like it and if it fits to Bulma coding rules ?**

### HTML Structure

```
<div class="timeline">
     <div class="time-item">
          <div class="item-content">
               <div>5 minutes ago</div>
                    <p><strong><a href="#">John Doe</a></strong> Uploaded a photo <strong>"DSC000586.jpg"</strong></p>
               </div>
          </div>

          <div class="time-item">
               <div class="item-content">
                    <div>30 minutes ago</div>
                         <p><a href="">Lorem</a> commented your post.</p>
                         <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus ut tincidunt euismod. "</em></p>
                    </div>
               </div>
          </div>
     </div>
</div>
```

### New sass rules

Find below the SASS rules I created to manage this timeline

```

.timeline
  border-left: 2px solid $grey
  position: relative

  .time-item
    border-color: #dee5e7
    padding-bottom: 1px
    position: relative
    flex-grow: 0
    flex-shrink: 0
    &:after
      background-color: #ffffff
      border-color: $grey
      border-radius: 10px
      border-style: solid
      border-width: 2px
      bottom: 0
      content: ''
      height: 14px
      left: 0
      margin-left: -8px
      position: absolute
      top: 5px
      width: 14px
    &:before
      content: " "
      display: table

    .item-content
      margin-bottom: 15px
      margin-left: 15px
```

**Comment by crodriguez1a** [comment]
+1

**Comment by dengbintao** [comment]
awesome

**Comment by jruizsulime** [comment]
Interesting +1

**Comment by pchaganti** [comment]
👍

**Comment by deletescape** [comment]
@Wikiki why don't you simply create a PR for this?

**Comment by Wikiki** [comment]
@deletescape : You're right. I don't know if there is some rules to respect and It'll be my first PR but I'll try ;-)

**Comment by Wikiki** [comment]
Can anyone explain me how to create a PR for this feature ? I've never done that.

Regards,

**Comment by paescuj** [comment]
@Wikiki 
Usually creating a PR includes the following steps:
1. [Fork the repository you want to create a pull request against](https://help.github.com/articles/fork-a-repo/)
3. Create a new branch and do your modifications inside it.
2. [Create the pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by Wikiki** [comment]
Thanks all.
The PR have been created :-)
