### ISSUE TITLE
How-to ? Hero and image background slider

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#425]
Hi,

do you have any idea how I can put in place a slider image as an hero background ?
I want to be able to have a hero component with head / body and foot and a slider as a background which change background image and hero-body content every x time. I know I'll need javascript to do it but I'm just asking how to be able to handle it on HTML structure and CSS point of view ?

Regards

**Comment by Wikiki** [comment]
Any idea ?

**Comment by jgthms** [comment]
Have an overlay as the first child of `hero`. Something like this:

```
<section class="hero">
  <div class="slider">
    <!-- Images -->
  </div>
  <div class="hero-body">
    <div class="container">
      <!-- Other content -->
    </div>
  </div>
</section>
```

**Comment by ipochi** [comment]
Hi , 

Can we have an overlay inside a container and not take up the full width of the screen ?
I have a two column layout and I only want an overlay image in one column.

Maybe i am doing things the wrong way , any guidance or suggestions , please ?
