### ISSUE TITLE
Icon only buttons

### ISSUE THREAD

**Issue by stygiansabyss** [jgthms/bulma#428]
### Description

When you create a button that is just an icon it is placed off center due to `.button .icon:last-child, .button .tag:last-child` overriding `first-child`.

### Steps to Reproduce

```
<a href="some/link" class="button is-danger is-outlined is-small">
    <span class="icon is-small">
        <i class="fa fa-power-off"></i>
    </span>
</a>
```

### Expected behavior

The icon should be centered inside the button.

### Actual behavior

The icon is pushed to the right.  Presumably because it is expecting text to follow.

**Comment by stygiansabyss** [comment]
```
&.is-icon-only {
  .icon:last-child {
    margin-left: -2px;
  }
}
```

Maybe something this simple is all that is needed?

**Comment by asvae** [comment]
There is an optimal solution I think.
```
.button .icon:first-child:last-child
  margin-right: -2px
  margin-left: -2px
```
`:only-child` is also possible. Yet it may have some issues with cascading due to lower specificity.

**Comment by stygiansabyss** [comment]
Thank you for this.  There is a minor problem that I accidentally found today.  If using the font-awesome class `fa-fw` it is still pulled to the right slightly.  Removing that class makes it look perfect though.
