### ISSUE TITLE
Change from SASS to SCSS

### ISSUE THREAD

**Issue by jaredreich** [jgthms/bulma#429]
From the official sass site:

> Sass has two syntaxes. The new main syntax (as of Sass 3) is known as “SCSS” (for “Sassy CSS”), and is a superset of CSS3’s syntax. This means that every valid CSS3 stylesheet is valid SCSS as well. SCSS files use the extension .scss.
>
> The second, older syntax is known as the indented syntax (or just “Sass”). Inspired by Haml’s terseness, it’s intended for people who prefer conciseness over similarity to CSS. Instead of brackets and semicolons, it uses the indentation of lines to specify blocks. Although no longer the primary syntax, the indented syntax will continue to be supported. Files in the indented syntax use the extension .sass.

**Comment by jacmoe** [comment]
> it’s intended for people who prefer conciseness over similarity to CSS.

It is not deprecated. It is for power users who like to be concise :)

**Comment by Prezto** [comment]
I was looking for the same. Google brought me here this morning.

Look here for a conversion script written in ruby -> https://gist.github.com/Prezto/e72e77e0f35352f5fcf5881b73b7d81b

Hope it can help others who come here to look for the Sass main syntax.

**Comment by elshaddae** [comment]
Still not considering to use SCSS up to today? Or I am missing something? The search engine results brought me here this morning.  And then I found [this](https://github.com/j1mc/bulma-scss)
