### ISSUE TITLE
[doc] nav with dropdown?

### ISSUE THREAD

**Issue by somenxavier** [jgthms/bulma#430]
Is there an equivalent in bulma of navbar dropdown menu in [bootstrap](http://v4-alpha.getbootstrap.com/components/navbar/)? If it's, please document it

**Comment by somenxavier** [comment]
Yes. It's [possible](https://github.com/jgthms/bulma/issues/192). Just put in docs

**Comment by SimpleCookie** [comment]
I would like to bump this issue.
Can this be included in the documentation?

**Comment by somenxavier** [comment]
It is cleary involved in doc issues

**Comment by evertramos** [comment]
This was a duplicate:

[https://github.com/jgthms/bulma/issues/192](https://github.com/jgthms/bulma/issues/192)

@jgthms @somenxavier I think we can close that now as of version 0.5.0:

[http://bulma.io/documentation/components/navbar/](http://bulma.io/documentation/components/navbar/)

Thanks!

**Comment by Guard13007** [comment]
This issue should be closed, shouldn't it?

**Comment by Green-Cat** [comment]
@jgthms This is already implemented. The issue should be closed.

**Comment by jgthms** [comment]
You're right. Thanks.
