### ISSUE TITLE
Horizontal form breaks if a label is long

### ISSUE THREAD

**Issue by rogervila** [jgthms/bulma#434]
* if it's a bug, is it a browser bug? YES

* [X] This is about the Bulma **CSS framework**
* [X] I'm using Bulma **version** [0.2.3]
* [X] My **browser** is: Chrome 55, Firefox 50.1
* [X] I am sure this issue is **not a duplicate**?

### Description

Horizontal form breaks if a label is long

### Steps to Reproduce

1. _[First Step]_

```html
<div class="control is-horizontal">
    <div class="control-label">
        <label class="label">
            Título
        </label>
    </div>
    <div class="control is-expanded">
        <input class="input" type="text" placeholder="">
    </div>
</div>
<div class="control is-horizontal">
    <div class="control-label">
        <label class="label">
            slug
        </label>
    </div>
    <div class="control is-expanded">
        <input class="input" type="text" placeholder="">
    </div>
</div>
<div class="control is-horizontal">
    <div class="control-label">
        <label class="label">
            Descripción
        </label>
    </div>
    <div class="control">
        <textarea class="textarea" placeholder=""></textarea>
    </div>
</div>
```

2. _[Second Step]_

The code is wrapped in a card

```html
<div class="card is-fullwidth">
    <div class="card-content">
        <div class="content">

        <div class="columns">
            <div class="column">
               <!-- the form goes here -->
```
### Expected behavior

Everything should be aligned

### Actual behavior

![breaks](https://cloud.githubusercontent.com/assets/6053012/21564112/c898518a-ce89-11e6-9b4e-1c9fff50c3d0.png)

**Comment by gmann1982** [comment]
Workaround for the time being I found:

Wrap the `control-label` element in 
```
<div class="column is-paddingless is-3">
    <div class="control-label">
        <label for="email" class="label">E-Mail</label>
    </div>
</div>
```

where `is-3` change this to your desired width.

**Comment by jgthms** [comment]
The new `field` element fixes this.
