### ISSUE TITLE
[feature request] helper to exclude content from the Bulma scope

### ISSUE THREAD

**Issue by rogervila** [jgthms/bulma#436]
* [X] This is about the Bulma **CSS framework**
* [ ] This is about the Bulma **Docs**
* [X] I'm using Bulma **version** [0.2.3]
* [X] My **browser** is: Chrome, Firefox
* [X] I am sure this issue is **not a duplicate**

### Description

I want to exclude some html content from the Bulma scope.

For example:
```html
            <div class="card is-fullwidth Editor">
                <header class="card-header">
                    <p class="card-header-title">
                        Header
                    </p>
                </header>
                <div class="card-content">
                     This part is affected by bulma styles
                     
                     <div>
                         This part should be excluded, since it has its own css
                     </div>
                    
                </div>
            </div>
```

Of course, right now all I have to do is to use `!important` and append the other css after Bulma, but it would be nice to have a helper for this.

Thank you.

**Comment by jgthms** [comment]
Mmmh that's tricky, as CSS is about "cascading".

You can either override with additional styles, or tweak the `card.sass` file to only apply to direct children, or copy only the styles you want.
