### ISSUE TITLE
Checkboxes and radio buttons broken in Firefox and IE

### ISSUE THREAD

**Issue by slavanga** [jgthms/bulma#44]
The custom styles for checkboxes and radio buttons don't work in Firefox and IE.

Firefox 44:
![firefox](https://cloud.githubusercontent.com/assets/1077807/12859215/f6301a98-cc54-11e5-84ad-d4f0b571cc2e.png)

IE Edge:
![ie](https://cloud.githubusercontent.com/assets/1077807/12859214/f5285a8e-cc54-11e5-800f-38ba85cabb96.png)

**Comment by jgthms** [comment]
I'm closing because I don't think it's possible to style them.
Plus: the styling is just an addon. As long as the controls are usable, that's fine for me.
But thanks for pointing it out. :+1:

**Comment by michael34** [comment]
I think it would be helpful to mention this in the readme. And provide some reasoning why styling for certain inputs doesn't work.
