### ISSUE TITLE
[BUG] Rem change breaks build

### ISSUE THREAD

**Issue by jeffijoe** [jgthms/bulma#441]
[This line](https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L25) breaks the build.

![image](https://cloud.githubusercontent.com/assets/2505474/21691446/dae7a00e-d378-11e6-969b-3607e9dc6582.png)

**Comment by Souldat** [comment]
+1 Getting the same issue when trying to compile.

**Comment by junyik** [comment]
+1 Getting the same issue while compiling using [Laravel Elixir](https://laravel.com/docs/5.3/elixir).

**Comment by junyik** [comment]
It happened to me while compiling. Then I found out that I have set the wrong unit (px instead of rem) for the variables $size-1 to $size-7.
