### ISSUE TITLE
[feature] Add is-selected class for table row

### ISSUE THREAD

**Issue by bogdan-zaharia-hs** [jgthms/bulma#442]
Sometimes a table has selectable rows, but there is no built-in way to emphasize the selected one. A class `is-selected` (or similar) for `tr` elements would be helpful.

**Comment by rafaelpimpa** [comment]
Something like this

```
.table {
    tr {
        &.is-selected,
        &.is-selected:hover {
            background: $primary;
            color: $primary-invert;
        }
    }
}
```

**Comment by rafaelpimpa** [comment]
If table has ``is-striped`` the strip color will override the ``is-selected`` color.

**Comment by shongololo** [comment]
The hover colour will also override the is-selected colour, which makes the text illegible per #822

**Comment by MrBrax** [comment]
What if you want to add more properties than is-selected though? !important isn't very modular.
