### ISSUE TITLE
Remove closing semicolon

### ISSUE THREAD

**Issue by pederan** [jgthms/bulma#443]
1. Can you please remove the closing semicolon on this line and the line below: https://github.com/jgthms/bulma/blob/master/sass/utilities/functions.sass#L32
It throws a compiler error.

2. Can you move the single-line comments on this line and the line below: https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L176
Single-line comments must be on their own line in the indented syntax.

Thx!

**Comment by pederan** [comment]
Can you please fix this asap, should be a quick fix. I would love to use the framework, but my automated compilation with Codeship fails because of these issues. Thx!

**Comment by pederan** [comment]
Thanks for fixing issue 1 in the list above. 

But compiling still fails because of issue 2. Can you please move the two inline comments to an own line? Single-line comments must be on their own line in the indented syntax.
https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L176
https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L177

Thanks!

**Comment by jgthms** [comment]
Ah shit, I didn't realise that was an issue as well.

**Comment by pederan** [comment]
Will you please fix this and push a new minor release? Thx

**Comment by lalwanivikas** [comment]
Shit! I thought I was doing something wrong. 

@pederan thanks for raising this issue.

**Comment by pederan** [comment]
When will you be able to fix this? I need this fixed so my automated deployment scripts doesn't break? Should be a really quick fix. You want me to make a pull request for it?

**Comment by yoostk** [comment]
It seems this was fixed in #446 and #467

**Comment by pederan** [comment]
Ok. Thx!
