### ISSUE TITLE
form .input.is-large font resizing

### ISSUE THREAD

**Issue by barohatoum** [jgthms/bulma#447]
### Checklist

* [ x ] This is about the Bulma **CSS framework**
* [ x ] I'm using Bulma **version** [0.3.0]
* [ x ] My **browser** is: Google Chrome
* [ x ] I am sure this issue is **not a duplicate**? YES

### Description

When I use the .is-large class on an .input field and want to resize the font size to 1rem, the whole input field becomes smaller

### Steps to Reproduce

1. Add class .is-large to any .input element
2. Change font-size to 1rem

### Expected behavior

I expect the input element to remain as big as it is but the font to be smaller

### Actual behavior

The whole element becomes smaller

**Comment by jgthms** [comment]
It's intentional, as the height of the input is `2.5em`. So it remains proportional to the text size. You can set a different height if you want.
