### ISSUE TITLE
BLOCKING BUG: 3.0 no longer compiles with Webpack SASS Loader

### ISSUE THREAD

**Issue by stevensacks** [jgthms/bulma#452]
```
Module build failed:
  $difference: $button-height - $button-horizontal-padding - $icon-width
              ^
      Incompatible units: 'rem' and 'px'.
in /Users/steven/projectpath/node_modules/bulma/sass/elements/button.sass (line 25, column 16)
```

**Comment by DimitarChristoff** [comment]
can confirm. 

> "node-sass": "~4.1.1"
> "sass-loader": "^4.0.2"

**Comment by Alamantus** [comment]
Compiles fine for me with 

```
"node-sass": "^4.1.0",
"sass-loader": "^4.1.0",
```

Can you try updating sass-loader and see if that helps you?

**Comment by stevensacks** [comment]
I'm using the latest of everything.

**Comment by junyik** [comment]
#441 Same issue here, but I found out that I've set the incorrect unit (px instead of rem) for the [Bulma Variables](http://bulma.io/documentation/overview/variables/) $size-1 to $size-7. Compilation works fine after updating the variables.

**Comment by jgthms** [comment]
It should handle different types of unit. I'll push a fix.

**Comment by pederan** [comment]
Please fix the issue #443 when you push the fix. It should be a quick fix.

**Comment by aareyes00** [comment]
I still experience this on 0.7.1 update from 0.5.3
It has an error on navbar
![screen shot 2018-08-02 at 4 26 51 pm](https://user-images.githubusercontent.com/6983769/43571983-ef0a4b2e-9670-11e8-9bd1-9a75570abfbc.png)

**Comment by jgthms** [comment]
Both are set to `rem` by default. You must have changed something in your setup.
