### ISSUE TITLE
Icons on documentation homepage are on top of text when viewed on mobile.

### ISSUE THREAD

**Issue by tf2manu994** [jgthms/bulma#456]
* is it about Bulma or about the Docs? Docs
* is it a bug/feature/question or do you need help? Bug
* if it's a bug, is it a browser bug? No

Thanks for helping out! 😇

### Checklist

* [X] This is about the Bulma **Docs**
* [X] My **browser** is: Chrome Mac, also tested on windows and android
* [X] I am sure this issue is **not a duplicate**?

### Description

![screen shot 2017-01-11 at 4 54 17 pm](https://cloud.githubusercontent.com/assets/7333640/21837269/dcd392c4-d81e-11e6-823e-a787e53fb001.png)

### Steps to Reproduce

1. Go to website on mobile or using the responsive preview in chrome

2. Observe the icons

### Expected behaviour

Icons to left of text

### Actual behaviour

Icons on text

**Comment by yoostk** [comment]
I don't see the problem on mobile now. Looks like the issue was fixed in the commit 37fa187ed7a677088a60116d2b371125691bba74. The icons only show up on desktop (large window size).
