### ISSUE TITLE
Label/input text color

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#457]
The text color for labels and input fields, is defined by the same variable. This introduces (in my case) some "unwanted" layout. My sites uses a dark background, and bright input fields.  

I was thinking that adding a `$label` variable, just as we have `$title $control $input` etc, and using that for setting the text color of label elements.

See attached images, for the current behavior.

I'm using bulma v0.3.0

![default text](https://cloud.githubusercontent.com/assets/3226608/21849300/4921d342-d805-11e6-9cc3-3554f9e3e452.png)
![bright text](https://cloud.githubusercontent.com/assets/3226608/21849299/4921b7b8-d805-11e6-9bba-d6b15949258a.png)

**Comment by jgthms** [comment]
You can use `has-text-white` now: https://github.com/jgthms/bulma/pull/126

**Comment by jeppech** [comment]
Thanks!

**Comment by r-pluss** [comment]
The .label class overrides the .has-text-white class, which makes it a lot less useful.
