### ISSUE TITLE
Support for a fixed header/navbar

### ISSUE THREAD

**Issue by soc** [jgthms/bulma#46]
It would be nice if Bulma would offer support for that out-of-the-box (header/navbar stays at the top when scrolling).

**Comment by benfilbey** [comment]
Yes! Would be very useful.

**Comment by joeblew99** [comment]
+1 me too.

**Comment by gbourgneuf** [comment]
+1 especially when working with Hero layout to keep navbar and site logo available after scrolling.

**Comment by MauF** [comment]
Yes would be great!

**Comment by n0daft** [comment]
+1 really need this. Until then, does someone has neat workaround?

**Comment by core01** [comment]
+1

**Comment by pchaganti** [comment]
👍

**Comment by Poliuk** [comment]
I'd love to have this. There's even a PR almost ready https://github.com/jgthms/bulma/issues/56

**Comment by carsol** [comment]
+1

**Comment by thulioph** [comment]
+1

**Comment by gcsomesz** [comment]
+1

**Comment by ImreC** [comment]
+1

**Comment by Poliuk** [comment]
@jgthms can we have an official answer about this?

**Comment by ChinuxParibus** [comment]
Perhaps [this](https://github.com/jgthms/bulma/pull/678) could help @jgthms

**Comment by Van-Vu** [comment]
+1

**Comment by Poliuk** [comment]
Thanks for trying @ChinuxParibus, I really appreciate your effort.

**Comment by jeanleonino** [comment]
👍 

Any updates on this feature?

**Comment by sunewa** [comment]
+1

**Comment by alexsandro-xpt** [comment]
+1

**Comment by jgthms** [comment]
Working on it.
