### ISSUE TITLE
[BUG] Responsive hamburger menu wont respond to clicks/touches

### ISSUE THREAD

**Issue by JamesHealdUK** [jgthms/bulma#462]
Im having an issue getting the responsive nav menu hamburger button working... Tested on both Chromium 55 and Android Firefox 50.1.0, same issues.

Nothing happens when you click the hamburger menu, have tested on the [documentation page](http://bulma.io/documentation/components/nav/) and on my own website with the same results. Any input on this would be greatly appreciated.

**Comment by RuinSain** [comment]
You need to use JavaScript for this. OR the hack with the checkbox. You may use bulma.js file. Search it in google

**Comment by JamesHealdUK** [comment]
Oh sorry, completely my bad... Totally missed that bit, thanks for the pointer!

**Comment by RuinSain** [comment]
No problem man. Enjoy. :)
