### ISSUE TITLE
select colour styling missing

### ISSUE THREAD

**Issue by DimitarChristoff** [jgthms/bulma#473]
the select border style colours inherent from `is-danger`, `is-info` etc is missing:

form.sass

```sass
  // Colors
  @each $name, $pair in $colors
    $color: nth($pair, 1)
    &.is-#{$name}
      border-color: $color
```

Only exists for inputs. Result is invalidated etc selects don't get error styling. 

Would also need a fix for the `:hover` - adding it on line 124 under the `.select select` solves the base issue. 

I can probably do a PR if it gets stable enough

**Comment by murparreira** [comment]
:+1: on this issue

**Comment by RicardoEmpre** [comment]
Today I came across this issue too.  
Too add to that, it would be great to have is-danger for `<label>`

**Comment by DimitarChristoff** [comment]
I've fixed it in my dev fork but since i've converted the project to SCSS and moved to latest node-sass, it probably won't get merged. 

Not sure what I am going to do with it but so far, I've applied a bunch of IE11 fixes as well and it's starting to diverge... https://github.com/DimitarChristoff/bulma/tree/scss

**Comment by jgthms** [comment]
This has been added https://github.com/jgthms/bulma/pull/126
