### ISSUE TITLE
Tabs Border not working right in Chromium

### ISSUE THREAD

**Issue by alexanderwe** [jgthms/bulma#474]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.3.1] 
My **browser** is:  Chromium 53.0.2785.143 (Electron)

### Description
I am using Bulma with Electron and React. When I want to use the simple horizontal tabs, a small issue is happening when I set `is-active` on the first tab. The bottom border seems to be 1px higher than the base border. When `is-active` is set on the second tab, everything is working fine.

<img width="404" alt="bildschirmfoto 2017-01-17 um 20 31 40" src="https://cloud.githubusercontent.com/assets/12934015/22037060/13ae1d92-dcf6-11e6-9642-c80b6a470c62.png">

```
<div class="tabs">
    <ul>
        <li class ="is-active"><a>Pictures</a></li>
        <li><a>Music</a></li>
        <li><a>Videos</a></li>
        <li><a>Documents</a></li>
    </ul>
</div>
```

This problem also applies to all other tab implementations. 

### Steps to Reproduce

1. Use Chromium
2. Insert example HTML from http://bulma.io/documentation/components/tabs/

### Solution

I changed the CSS for the tabs class from

`.tabs ul {
    align-items: center;
    ...
}`

to 

`.tabs ul {
    align-items: baseline;
    ...
}`

and everything is working as expected. 

Is this the expected behavior ? If this is not the case, is it possible to change the CSS according to my solution ? 

Thanks in advance. And also thanks for this great CSS framework !

**Comment by ilicmarko** [comment]
This can't be reproduced, has it been fixed?
Tested in:

- Firefox 50.1.0
- Chrome 55.0.2883.87 m
- Chrome 57.0.2984.0 canary
- Edge 38.14393.0.0
- Opera 42

**Comment by alexanderwe** [comment]
Maybe the Problem is related specific to Electron or within my Setup.

Yes, it was solved with changing the CSS to

 `.tabs ul { align-items: baseline; ... }`.

**Comment by alexanderwe** [comment]
I think because it can not be reproduced I can close this issue for now.

**Comment by Twan-Blum** [comment]
Had the same problem. Issue seems to be when you add tabs inside container with the "content" class:

bulma.css 1690:
`.content li + li {
    margin-top: 0.25em;
}`

**Comment by henriquemattos** [comment]
I've the same problem. @alexanderwe 's solution worked for me but I don't think I should overwrite Bulma's CSS. I'm using version 0.5.1.

<img width="1667" alt="screen shot 2017-08-26 at 17 29 48" src="https://user-images.githubusercontent.com/2782214/29742719-35bce698-8a84-11e7-8dbc-e4f82a55be0b.png">

**Comment by micobarac** [comment]
Actually, I am facing the same issue on Windows 10 x64 with the latest Chrome version. Aligning items to the baseline did the trick.
