### ISSUE TITLE
Integrate Bulma with Vuejs

### ISSUE THREAD

**Issue by chenz24** [jgthms/bulma#477]
Hi, recently I built a VueJs ui component library.For the css part I choose bulma([demo](https://chenz24.github.io/vue-blu/#/)). It really helps me a lot.Thanks for your great work

**Comment by flexd** [comment]
@chenz24 Nice! Looks like there is a problem with the font in your documentation. All I see are boxes, using Chrome 56 on Linux. I guess maybe the font it falls back to using does not support some of the characters used.

**Comment by chenz24** [comment]
@flexd Thx! I will check it out

**Comment by SimpleCookie** [comment]
Could you translate all of the text to English?

**Comment by chenz24** [comment]
@SimpleCookie Yes, the work is in progress
