### ISSUE TITLE
Pagination links not displaying correctly on version 0.3.0/1

### ISSUE THREAD

**Issue by RuinSain** [jgthms/bulma#485]
It is about Bulma
 It is a bug
It is not a browser bug

### Overview of the problem

 This is about the Bulma **CSS framework** 
 I'm using Bulma **0.3.1**
 My **browser** is: chrome
### Description
Pagination links are not correctly displayed.

### Steps to Reproduce

1. Be on Bulma **0.2.3**, and have pagination links.
2. Change to Bulma 0.3.0/1

### Expected behavior
I expected the links on mobile to be evenly distributed on the screen, and on desktop too.
### Actual behavior
1. On desktop, they take the full width.
2. On mobile, they are just lined up next to each other with no margin or padding.

This is what its like in **Desktop** on Bulma 0.2.3, and its very good.
![desktop0 2 3](https://cloud.githubusercontent.com/assets/11059876/22177814/566b6316-e02e-11e6-941b-c3b791667e8c.PNG)
This is what its like in **Desktop** on Bulma 0.3.1, and its too wide.
![desktop0 3 1](https://cloud.githubusercontent.com/assets/11059876/22177812/566a5ba6-e02e-11e6-85d4-41af3782a852.PNG)
This is what its like in **Mobile** on Bulma 0.2.3, once again... correct view on mobile.
![mobile0 2 3](https://cloud.githubusercontent.com/assets/11059876/22177813/566aefb2-e02e-11e6-8825-373080c17a12.PNG)
This is what its like in **Mobile** on Bulma 0.3.1, and once again... not the desired view on mobile.
![mobile0 3 1](https://cloud.githubusercontent.com/assets/11059876/22177815/566b8abc-e02e-11e6-8a17-b165e13c4519.PNG)

Is this a know issue? or what can i do to solve this on v0.3.1?

**Comment by jgthms** [comment]
What is your markup?

**Comment by RuinSain** [comment]
My markup for the pagination is this: 
```
<ul class="pagination">
<li class="disabled"><span>&laquo;</span></li>
<li class="active"><span>1</span></li>
<li><a href="https://taamtov.net?page=2">2</a></li>
<li><a href="https://taamtov.net?page=3">3</a></li>
<li><a href="https://taamtov.net?page=4">4</a></li>
<li><a href="https://taamtov.net?page=5">5</a></li>
<li><a href="https://taamtov.net?page=6">6</a></li>
<li><a href="https://taamtov.net?page=7">7</a></li>
<li><a href="https://taamtov.net?page=8">8</a></li>
<li><a href="https://taamtov.net?page=9">9</a></li>
<li><a href="https://taamtov.net?page=2" rel="next">&raquo;</a></li>
</ul>
```

**Comment by conradob** [comment]
I was facing the same issue. It was missing the `pagination-link` in the bulma module.
Upgraded to version `0.3.1` and now it's working.
