### ISSUE TITLE
Input with icons - icons not centered

### ISSUE THREAD

**Issue by jaredreich** [jgthms/bulma#489]
Check out the screenshots:

![](http://i.imgur.com/vNX1mHw.jpg) ![](http://i.imgur.com/B9Ga8mh.jpg)

**Comment by jptaylor** [comment]
Issue is compounded when working with different icon sizes (e.g. I'm using material icons over font awesome.)

Easy fix was to tweak how the icons are positioned, but this meant adding `position:relative` to the `.control` class which is probably breaking other things.
