### ISSUE TITLE
Question: how to do smooth progress bar animations

### ISSUE THREAD

**Issue by julianfresco** [jgthms/bulma#491]
Normally, I would add a CSS3 transition to ease changes into a smooth animation, but even a `transition: all 0.5s ease` didn't do the trick on the progress element... I do not know which style to animate for the progress element.

For illustration, here's a snippet you can enter into the JS console on the [Progress bar docs page](http://bulma.io/documentation/elements/progress/)

``` javascript
// Paste into JS console on Progress bar docs page
(function(){
  let target = document.querySelector('.progress.is-success'),
      value = 0,
      step = 6,
      interval = setInterval(function(){
        value = (value > 100) ? 0 : step+value
        target.value = value
      }, 700),
      timeout = setTimeout(function(){
        clearInterval(interval)
      }, 30*1000)
})()
```

To get around this, I can do a hack/workaround in JS by slicing my updates by a desired frames-per-second, like below, but **I'd prefer if there was a way to do this in CSS only.**

``` javascript
// A hack / workaround for animations. Note: the fps variable
// Paste into JS console on Progress bar docs page
(function(){
  let target = document.querySelector('.progress.is-success'),
      fps = 60,
      value = 0,
      step = 6,
      interval = setInterval(function(){
        value = (value > 100) ? 0 : (step/fps)+value
        target.value = value
      }, 1000/fps),
      timeout = setTimeout(function(){
        clearInterval(interval)
      }, 30*1000)
})()
```

**Comment by fmoliveira** [comment]
Try styling this selector:

```css
.progress::-webkit-progress-value {
  transition: width 0.5s ease;
}
```

**Comment by fmoliveira** [comment]
Which selector have you tried styling? Show us the CSS you've tried too.

Anyway, try styling this selector:

```css
.progress::-webkit-progress-value {
  transition: width 0.5s ease;
}
```

**Comment by julianfresco** [comment]
Given the description, "even a `transition: all 0.5s ease` didn't do the trick *on the progress element*", I imagine this was the CSS I used previously:

``` css
progress {
  transition: all 0.5s ease;
}
```

Thank you. The snippet you provided does indeed work (I'm using Chrome). So, I imagine there's no CSS selector to do this CSS3 transition in non-webkit browsers then?

**Comment by jgthms** [comment]
I feel this issue has been fixed (and goes beyond the scope of Bulma itself). 😉

**Comment by henryfw** [comment]
`.progress::-webkit-progress-value {
  transition: width 0.5s ease;
}`
Seems to work for all except Firefox. https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-progress-value

**Comment by grobiwebdesign** [comment]
Hi everyone, it's not working for me and I'm using Chrome. Have there been any recent updates? Kind regards
