### ISSUE TITLE
Class to adjust width Bulma Table Column 

### ISSUE THREAD

**Issue by SDJeff** [jgthms/bulma#492]
How to adjust the table column width. Knows anybody a class definition or have i to use the grid definition like it is in bootstrap?

**Comment by jgthms** [comment]
You need to set the width of each column manually, since table can contain any type of data. It would be too bloated to have 100 classes for each possible width.

**Comment by swalker2** [comment]
It woul be nice to write on the header for example `<th class="is-2">...</th> `

**Comment by sangdth** [comment]
I agree. It would be nice if we can add `columns` in to table, and use `is-2`, `is-half` to customize the width of columns.

**Comment by focussing** [comment]
Beautiful!! Same approach as working with 'normal' columns

**Comment by Fsarmento** [comment]
+1

**Comment by andonovn** [comment]
+1

**Comment by pgangidi** [comment]
+1

**Comment by Grovkillen** [comment]
+1

**Comment by LucasRosa90** [comment]
+1

**Comment by brakkum** [comment]
Might as well, +1

**Comment by murilobd** [comment]
+1

**Comment by alalfakawma** [comment]
Hi guys, I just wrote a small scss mixin to be able to do this as @swalker2 has suggested above. It works like a charm.

[https://gist.github.com/alalfakawma/b94de00f31895b91077a2e3f71ace1fe](link)

**Comment by molcik** [comment]
You can also use `colspan` property. To create proportional layout. E.g. 

``` html
<tr>
    <td colspan="2"></td>
    <td></td>
</tr>

```

**Comment by fakhrulhilal** [comment]
Why not reuse [this](https://bulma.io/documentation/columns/sizes/)? For consistency reason, I suggest to reuse same naming.

**Comment by antoniputra** [comment]
Just want to share how I did for this case

```
<div class="table-container">
    <table class="table is-bordered is-fullwidth is-hoverable">
        <thead>
            <tr>
                <th>No</th>
                <th><div style="width: 200px;">Name</div></th>
                <th>Price</th>
                <th>Type</th>
                <th><div style="width: 120px;">Action</div></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>...</th>
                <th>...</th>
                <th>...</th>
                <th>...</th>
                <th>...</th>
            </tr>
        </tbody>
    </table>
</div>
```

**Result:**

What you see in desktop, is what you get on mobile (with scroll)

**Comment by noraj** [comment]
Example to set the size of the columns using `colgroup` + `col` (SLIM template):

```slim
      table.table.is-fullwidth
        colgroup
          col span="1" style="width: 27%"
          col span="1" style="width: 73%"
        tbody
          tr
            th = labels[:x]
            td = details[:y]
          tr
            th = labels[:x]
            td = details[:y]
          tr
            th = labels[:x]
            td = details[:y]
```

It's possible to replace `style="width: 73%"` with `width="73%"` but `width` is officially deprecated since HTML 5 so it won't work in the future.
It's not possible to put a `class` attribute on a `col` of `colgroup`, the browser is not using it, so you have to manually set `is-size-4` on each `th` manually, it would be nice if Bulma was supporting the is-size-x class on a `col` to apply it on al cells.
Also align attribute were deprecated inside colgroup so having a support for it would be awesome.

**Comment by mohapsat** [comment]
> Just want to share how I did for this case
> 
> ```
> <div class="table-container">
>     <table class="table is-bordered is-fullwidth is-hoverable">
>         <thead>
>             <tr>
>                 <th>No</th>
>                 <th><div style="width: 200px;">Name</div></th>
>                 <th>Price</th>
>                 <th>Type</th>
>                 <th><div style="width: 120px;">Action</div></th>
>             </tr>
>         </thead>
>         <tbody>
>             <tr>
>                 <th>...</th>
>                 <th>...</th>
>                 <th>...</th>
>                 <th>...</th>
>                 <th>...</th>
>             </tr>
>             ....
>         </tbody>
>     </table>
> </div>
> ```
> 
> **Result:**
> 
> What you see in desktop, is what you get on mobile (with scroll)

worked like a charm, thanks!
