### ISSUE TITLE
When style conflicts with another library. Who should care, Bulma or said library?

### ISSUE THREAD

**Issue by jpmurray** [jgthms/bulma#496]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.1]

### Description

I never collaborated with CSS frameworks before, and while I *do* have some frontend design/css knowledge, I'm kind of lost on this matter, so consider me a newbie on this, and please, bear with me ;-)

So I'm using SweetAlert 2 in conjuncture with Bulma. Everything works perfectly fine except for a small `<hr>` matter. As you can see in screenshot below, Sweet Alert uses an HR tag, called as such: `<hr class="swal2-spacer" style="display: block;">`, and the styling is:

```
.swal2-modal .swal2-spacer {
    height: 10px;
    color: transparent;
    border: 0;
}
```

Coming from Bootstrap, I've used SweetAlert before and never experienced that, so I checked the default Bulma style for HRs and I fond that there is a `background-color: $border` set to it that is interfering with SweetAlert's HR.

Now, like I asked in the title: who should bear responsibility on this one? Personnally, I'd expect the framework not to interfere with other external libraries, but I might be mistaken. If it's Bulma, let's consider this a call for a discussion on how to manage this. If it should be the external library (in this case, SweetAlert), I'll just close this and go open an issue up there. 

### Steps to Reproduce

1. Use Bulma
2. Use SweetAlert2
3. Make an alert.

### Expected behavior

Not a styled HR.

### Actual behavior

<img width="509" alt="screen shot 2017-01-28 at 11 54 37 am" src="https://cloud.githubusercontent.com/assets/1550428/22398168/ae0629b8-e550-11e6-9506-88e451e22347.png">

**Comment by jgthms** [comment]
It has been suggested to prefix all the classes: #444 

There is a PR open for that. I just need to check that it works correctly.

**Comment by jpmurray** [comment]
@jgthms thanks for the clarification. Do you want me to close the issue?
