### ISSUE TITLE
Issue with delete button when setting '$size' variables to rem values

### ISSUE THREAD

**Issue by jgerbes** [jgthms/bulma#502]
### Overview of the problem

This is about the Bulma **CSS framework**
This is a **Sass** issue: I'm using version [0.3.1]

### Description

Setting the relevant `$size` variables (e.g. `size-6`) to a rem value sets the delete button element's dimensions to 0px by 0px.

### Steps to Reproduce

1. Set the `$size` variables to rem values. E.G:
`$size-1: 1.9rem;
$size-2: 1.7rem;
$size-3: 1.2rem;
$size-4: 1.2rem;
$size-5: 1rem;
$size-6: 1rem;`

2. Import Bulma (`@import "node_modules/bulma/bulma";`)

3. Compile Sass 

### Expected behavior

The delete button element should show on the page.

### Actual behavior

The delete button is invisible as it's dimensions are 0px by 0px.

**Comment by cmoad** [comment]
Seeing this as well. Additionally, setting the width and height manually requires playing a game to get the ratio just right to make it square. Setting the width == height causes the delete icon to appear skewed.

**Comment by robin900** [comment]
@jgerbes You can reproduce just by changing `$size-6` to use a unit other than `px` and have a low numeric value before the unit. the `=delete` sass mixin assumes `px` as the unit, does `removeUnit($size-6)` and uses it to compute the width and height of the delete cross (also modal-close I think). Default `$size-6` is `16px`; with a value like `1.5rem` it becomes `1.5` and effectively reduces the width to something that rounds down to zero, thus `0px`.

I've created another issue, #556, that describes the more general problem with the code: unit arithmetic in sass cannot just strip the unit and then hope that the stripped unit was a particular unit in order for the arithmetic to work.
