### ISSUE TITLE
Wrap $colors in map merge

### ISSUE THREAD

**Issue by jptaylor** [jgthms/bulma#503]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

It would be great to be able to add more colours to the `$colors` map. A simple way to allow this is to wrap it in a `map-merge` function:

`$colors: map-merge($colors, (...))`

This allows you to create your own map in an override before importing Bulma:

`$colors: map-merge($colors, (secondary: ($secondary, $secondary-invert))) !default`

**Comment by jgthms** [comment]
`$colors` is not defined at that point. And I can't initialise an empty map just in case someone wants to add some colors. I believe it's a case-by-case issue, where people can create their own `$colors` map.
