### ISSUE TITLE
Most elements not using $background (or other variables)

### ISSUE THREAD

**Issue by ForsakenHarmony** [jgthms/bulma#504]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.1]
My **browser** is: Chrome

### Description

Why is it that so many elements directly use a colour instead of the other variables ([example](https://github.com/jgthms/bulma/blob/master/sass/layout/section.sass#L2))

This forces one to override the colours as well

### Steps to Reproduce

1. Override the background variable

```
$background: $grey-darker;
$body-background: $grey-dark;
```

2. Background of sections, navs, ... stays the same

### Expected behavior

Background of all elements change

### Actual behavior

A lot of elements still have a white background

**Comment by jgthms** [comment]
The `$background` is actually the light grey background. There is no variable for the white color. There could be one, but I'm not sure how to call it.

**Comment by ForsakenHarmony** [comment]
What?

**Comment by ForsakenHarmony** [comment]
Should I make a pr for this?

**Comment by jgthms** [comment]
There is `$background` for the light grey background, and `$body-background` for the page background. They're not related.

**Comment by ForsakenHarmony** [comment]
Take a look at step 2

**Comment by SoerenTerh** [comment]
I would assume, that this is the expected behaviour. 
I think, it's easier to go this way of defining the color this way and changing it up accordingly to your needs is the better way - the way it is solved in the current version. You suggest not differentiating between components/elements, which would make defining background colors even harder due to it being tied so closely to every single element. That would also result in more work than changing up the background color now, since white is more often used than specific, other colors.

**Comment by ForsakenHarmony** [comment]
so one should overwrite white to set the background?

**Comment by SoerenTerh** [comment]
No. You would set background-color to your personal variable. Simply make sure, that you import bulma before you define yours in order for bulma to not override declarations.

**Comment by SoerenTerh** [comment]
But sure. You are free to set white to whatever you want, if everything should blend into each other. Didn't check it, but I am quite sure that $white is used more than simply setting background colors.

**Comment by ForsakenHarmony** [comment]
the problem is the inconsistency, some elements use `$background`, others just `$white`

`background-color` doesn't exist btw

**Comment by SoerenTerh** [comment]
Well. I was talking about setting the background attribute to whatever personal variable you might want to use. Sure - you are right in a sense of making it consistent - though if you check closely, the $background doesn't share the same type of white as $white. Those nuances are measured to be different in a nuance. And what I meant about overriding background-color is simply checking up on which background attributes you might want to change and have a code block to simply redeclare those ones with your personal variable.
