### ISSUE TITLE
SASS error "invalid CSS in utilities/mixins.sass"

### ISSUE THREAD

**Issue by mirokk** [jgthms/bulma#505]
### Overview of the problem

I'm using Bulma **version** 0.3.1
This is a **Sass** issue: I'm using version 3.4.23 

### Description

when i'm running the basic example of your website, i'm getting the following error:

error node_modules/bulma/sass/utilities/mixins.sass (Line 176: Invalid CSS after "1000px ": expected expression (e.g. 1px, bold), was "!default // 960...")

### Steps to Reproduce

1. npm install bulma
2. created a file style.sass
```
$blue: #72d0eb // Update blue
@import "../../node_modules/bulma/bulma" 
```
3. `sass --watch style.sass:style.css`

### Expected behavior

style.sass compiled into style.css

### Actual behavior

error message
```
error node_modules/bulma/sass/utilities/mixins.sass (Line 176: Invalid CSS after "1000px ": expected expression (e.g. 1px, bold), was "!default // 960...")
```

**Comment by mirokk** [comment]
when i remove the comments in line 176 and 177 in utilities/mixins.sass it all works fine..

**Comment by jgthms** [comment]
So this was fixed on `master` https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass

But 0.3.2 is not released on npm yet.
