### ISSUE TITLE
Body not using $background color in v0.3.1

### ISSUE THREAD

**Issue by reustonium** [jgthms/bulma#508]
The html body doesn't seem to be setting the background-color: $background in version 0.3.1

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.1]
My **browser** is: Chrome Version 55.0.2883.87

I am sure this issue is **not a duplicate** but it might be related to #504 

### Description

I'm not sure if this is supposed to be a feature or if it's a bug.

### Steps to Reproduce

1. Create an html page using Bulma version 0.2.3
2. Observe that the `background-color: whitesmoke;`

![image](https://cloud.githubusercontent.com/assets/1432186/22712491/f3762b74-ed52-11e6-9d3f-6afd91815ce8.png)

3. Create an html page using Bulma version 0.3.1
4. Observe that the `background-color: white;`

![image](https://cloud.githubusercontent.com/assets/1432186/22712295/483cb142-ed52-11e6-94ab-c4e2b513f53d.png)

### Expected behavior

I would expect the `<html>` background-color should be equal to `$background` which defaults to whitesmoke.

### Actual behavior

The `<html>` background-color equals white.

**Comment by yoostk** [comment]
The `<html>` background-color is defined as `$body-background` variable, which is white color. I think this is supposed to be a future. The `$background` variable is used for other elements.

https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L5

**Comment by ForsakenHarmony** [comment]
yeah, some of the other elements are not using $background though, which I find really annoying

**Comment by jgthms** [comment]
`$body-background` is for the page background.
`$background` is the light grey background used for some elements.

**Comment by cyrilchapon** [comment]
And $body-background is not in derived-variables.scss 😋
