### ISSUE TITLE
[Feature] Add a dropdown

### ISSUE THREAD

**Issue by gaillota** [jgthms/bulma#519]
Hi there,

Do you think it's possible to consider adding a dropdown menu in the near future ?
I'm not an expert in sass development, but I think it's an important feature that should be a part of this amazing framework.

Thank you.

PS: Feel free to delete this issue if you find it inappropriate. Cause it's actually not an issue, I just didn't know where to put this request.

**Comment by jruizsulime** [comment]
dropdown menu will be cool +1

**Comment by rajibahmed** [comment]
Bulma won't add any javascript dependencies. @jgthms said it several times. 
My idea would be, 
-- create a plugin, ie -- bulma-js-dropdown like project. Add bulma and bulma-js-dropdown should handle your needs. Also you can do is with your preferences like, css or less or stylus whatever you feel like.

IMO If the core library is small and clean, it would good for its lifespan and adaptation.

:)

**Comment by gaillota** [comment]
Yes, I know Bulma doen't have any javascript integrated, but it could be like the modals, with the `is-active` class. You don't need javascript to make the dropdown menu appears. Just to handle the class toggle

**Comment by RicardoEmpre** [comment]
It's asked also in #192

**Comment by gaillota** [comment]
#192

**Comment by Donkfather** [comment]
so.. what's happening with that dropdown .. i mean i get it.. use just css .. but please provide a way to create  a dropdown in the nav.. i've searched all over the web and couldn't find a good solution .. it is just a deal breaker .. :(

**Comment by xlcrr** [comment]
+1 for dropdown

**Comment by sldobri** [comment]
try spectre.css

**Comment by gaillota** [comment]
@Donkfather I made a PR (#546), waiting to be merged...
@sldobri I don't see any dropdown in your framework.

**Comment by sldobri** [comment]
https://picturepan2.github.io/spectre/components.html#menus

**Comment by gaillota** [comment]
My bad, I thought it would have a dedicated section.

**Comment by rafialikhan** [comment]
@sldobri are you suggesting adding spectre.css along with bulma or using spectre instead?
