### ISSUE TITLE
make the title design variation

### ISSUE THREAD

**Issue by sottar** [jgthms/bulma#52]
I am trying to make title design variation.
Adding contents `.is-bar-left` and `.is-bar-bottom` elements to the `titles.sass`

**Comment by jgthms** [comment]
You can use `.is-left` or `.is-right` to align the text accordingly.

**Comment by sottar** [comment]
I’d like to make not align the text but title design.
Like these :)
<img width="500" alt="screenshot_2016-02-10 8 49 49" src="https://cloud.githubusercontent.com/assets/8223003/12934699/dbcaaeb6-cfd3-11e5-9162-d09bd469fdfe.png">
