### ISSUE TITLE
Datatables Styles

### ISSUE THREAD

**Issue by alejnik-sergey** [jgthms/bulma#521]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

It will be good, If you create styles for Datatables.

**Comment by imranismail** [comment]
i don' think it's wise to make it part of bulma, I liked the NOJS mantra

**Comment by barohatoum** [comment]
@imranismail me too i like the no JS mantra but its not about the js part. its about adding the styling of the datatables without the js part. all the popular frameworks have them: Bootstrap, Foundation, Semantic UI, MDL by Google and UIKit

**Comment by JDilleen** [comment]
Not everyone uses DataTables so implementing it into Bulma seems trivial, that said I went ahead and had a bash at implementing the Bulma style into DataTables, let me know if this works for you! 😄 

https://github.com/JDilleen/datatables-bulma

![DataTables Bulma](https://jdilleen.me/includes/img/bulma.png)

**Comment by alejnik-sergey** [comment]
@JDilleen Oh, thank you so much, man! It works perfect! 😸

**Comment by jericopulvera** [comment]
This works but it's not responsive in my project.

**Comment by barohatoum** [comment]
perfect thank you very much

**Comment by andyyatma** [comment]
What version of font awesome does it use ? cs i did not see any arrows in my data table.
or maybe i must change the script manually ?

**Comment by rosiecakes** [comment]
@andyyatma it uses 5 Free. works for me with 5.9 using [this](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself)
