### ISSUE TITLE
Full width/height divs or elements

### ISSUE THREAD

**Issue by dangus21** [jgthms/bulma#525]
Is it possible to have a main `.container` to be 100% width and height and to have an element be vertically and horizontally aligned to it or does this feature have to be done by hand (not supported by bulma)?

**Comment by dangus21** [comment]
also, there is no real proper way, that i found, to align elements inside elements, vertically or horizontally:
```
<div class="container">
	<div class="columns ">
		<div class="column is-centered">
			<p class="notification" id="primeira"></p>
			<span class="tag">#2c3643</span>
		</div>
	</div>
</div>
```

the [PEN](http://codepen.io/angus/pen/XMrrpN) i'm working this into.

i couldnt center the `.tag` in the `column` for example.

**Comment by Wikiki** [comment]
Hi, 

Everytime I want to achieve this I use the Hero layout but I agree it could be great to have this behavior with a small class to add.

**Comment by Wikiki** [comment]
Have you tried with class has-text-centered ? Instead of is-centered.

**Comment by jgthms** [comment]
`.column` is not a flexbox container, hence why you can't center its content easily. You have to do it manuallly.
