### ISSUE TITLE
input overflows flex container

### ISSUE THREAD

**Issue by jeppech** [jgthms/bulma#530]
In **firefox**, serveral inputs within a `has-addons` flex container, will overflow the container.

This is due to the input element, not having `min-width: 0` set.

With min-width:
<img width="486" alt="ech4vdnp" src="https://cloud.githubusercontent.com/assets/3226608/23334421/7e5f3c22-fb9e-11e6-9d17-5cfa661e1e47.png">
Without min-width:
<img width="486" alt="yvdyjh14" src="https://cloud.githubusercontent.com/assets/3226608/23334420/7ab42b50-fb9e-11e6-8008-dc9ba6117867.png">

**Comment by kixortillan** [comment]
+1 to this.
For now I am sticking with @jeppech recommendation. Also when adding 'is-expanded' class to an input element, it also comes out of the container when resized (particularly IPhone 5 screensize using developer tool Chrome). Workaround is do not use 'is-expanded' and use 'width: 100%' instead.

**Comment by jgthms** [comment]
This should be fixed with the new `field` element.
