### ISSUE TITLE
Columns class fullwidth

### ISSUE THREAD

**Issue by Global990** [jgthms/bulma#534]
### Overview of the problem

I have an issue with the .columns class, i need it to go 100% width in order to fill a .panel-block, but it seems that the class .is-fullwidth doesn't work. It only works if I hard code style="width:100%" on the div that has the .columns class.
I don't know if this is an issue, or I'm just not using it right.

I'm using columns to put two elements on separate rows, one is a title and the other one is a progress bar:

```
                <div class="panel">
                    <div class="panel-block">
                        <div class="columns is-multiline">
                            <div class="column is-full">
                                <span class="title">Building database...</span>
                            </div>
                            <div class="column is-full">
                            <progress class="progress is-primary"
                                          value="30"
                                          max="100">
                                    30%
                                </progress>
                            </div>
                        </div>
                    </div>
                  </div>
```

### Expected behavior

![expected](https://cloud.githubusercontent.com/assets/5485205/23340946/d0a72bb2-fc47-11e6-9b32-ebd101994b81.PNG)

### Actual behavior

![actual](https://cloud.githubusercontent.com/assets/5485205/23340950/e352fb06-fc47-11e6-89a2-1ac3bc94b7aa.PNG)

**Comment by jgthms** [comment]
> columns to put two elements on separate rows

There's your problem. 😉  `rows !== columns`

You don't need columns if you put them one above the other. Just use `div`s.
