### ISSUE TITLE
Button .is-outlined does not work without a color declaration.

### ISSUE THREAD

**Issue by sjclark** [jgthms/bulma#535]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.3.2]
My **browser** is: Chrome 55

### Description

Assigning an element the class .button.is-outlined does not work for the default button - it remains with a white background. It requires a colour class in order to be applied.

Find below an image from the Bulma documentation but with the background changed to black.

![screenshot 2017-02-27 at 11 40 43 am](https://cloud.githubusercontent.com/assets/4531017/23344478/0a30f580-fce2-11e6-8ced-dad372baca06.png)

### Steps to Reproduce

1. Create a link element
2. Assign the class .button & .is-outlined
3. Use a coloured background

### Expected behavior

Like all other .is-outlined elements this should have a transparent background

### Actual behavior

The element has a non-transparent background

**Comment by robin900** [comment]
@sjclark The PR #555 addresses your concern. It describes in the documentation and provides examples of just what `is-outlined`, `is-inverted`, and the combination of the two mean for button styling. The PR makes the default button have a transparent background when `is-outlined`, and also more to match the newly-documented styling behavior.
