### ISSUE TITLE
Fix: make .help spans work with .control.has-addons

### ISSUE THREAD

**Issue by Youdaman** [jgthms/bulma#536]
Add the following to make .help spans sit below inputs with addons:
```
.control.has-addons {
  flex-wrap: wrap;
}
.help {
  min-width: 100%;
}
```
An example where this is needed:
```
<p class="control has-addons">
  <input class="input is-expanded" type="text">
  <a class="button">
    <i class="fa fa-times"></i>
  </a>
  <span class="help is-danger">Required</span>
</p>
```
Otherwise "Required" sits to the right of the input/button on the same line.

Hopefully this helps anyone having the same issue :)

(not sure if you also need `flex-grow: 1` for the .help as mentioned here http://stackoverflow.com/a/41838097)

**Comment by jgthms** [comment]
You can do it with the new `.field` element: http://bulma.io/2017/03/10/new-field-element/

**Comment by brunsten** [comment]
Is it broken? 

The margin between a `.help` and `.control` is larger then you expect
