### ISSUE TITLE
dropdown has two arrows.

### ISSUE THREAD

**Issue by tadko** [jgthms/bulma#537]
This is about the Bulma **CSS framework** 
My **browser** is:  IE11

### Description

In IE11, dropdown shows two arrow.

![2017-03-02_17h45_33](https://cloud.githubusercontent.com/assets/1215684/23499820/025a6d64-ff71-11e6-84d0-c465d3e4f290.png)

**Comment by jruizsulime** [comment]
You can fix this issue adding this to your .css

`select::-ms-expand {
    display: none;
}`

**Comment by jaredreich** [comment]
That's a good temp fix, but this should also be applied to Bulma.

**Comment by jgthms** [comment]
It's in there: https://github.com/jgthms/bulma/blob/master/sass/elements/form.sass#L126

**Comment by jaredreich** [comment]
Unfortunately the issue still exists as @tadko mentioned. Any thoughts?

**Comment by wolfgang42** [comment]
This will be fixed by #573. The line that @jgthms  references was added by #15, but has a typo: the value should be `-ms-expand` with a leading dash.
