### ISSUE TITLE
New Feature : Switch style for Checkbox

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#538]
### Description

I've created a new Switch style to easily display checkboxes like this
<img width="800" alt="screen shot 2017-03-03 at 10 37 57" src="https://cloud.githubusercontent.com/assets/24766179/23545939/bfddaa0e-fffd-11e6-8e7e-35723c7737ad.png">

HTML code:
```
<label class="switch">
    <input type="checkbox">
    <span>Label</span>
</label>
```

```
input[type="checkbox"]
  &.switch
    display: none
    + label
      position: relative
      display: inline-block
      cursor: pointer
      font-weight: 500
      text-align: left
      margin: 0px
      padding: 0px 44px
      &:before, &:after
        content: ""
        position: absolute
        margin: 0
        outline: 0
        top: 50%
        transform: translate( 0, -50% )
        transition: all .3s ease
      &:before
        left: 1px
        width: 34px
        height: 14px
        background-color: rgba( $grey, 0.5 )
        border-radius: 8px
      &:after
        left: 0
        width: 20px
        height: 20px
        background-color: $grey
        border-radius: 50%
        box-shadow: 0 3px 1px -2px rgba(0,0,0,.14), 0 2px 2px 0 rgba(0,0,0,.098), 0 1px 5px 0 rgba(0,0,0,.084)
  &:checked
    + label
      &:after
        transform: translate( 80%, -50% )
  @each $name, $pair in $colors
    $color: nth($pair, 1)
    $color-invert: nth($pair, 2)
    &.is-#{$name}
      display: none
      &:checked
        + label
          &:before
            background-color: rgba( $color, 0.5 )
          &:after
            background-color: $color
            transform: translate( 80%, -50% )

```

If someone can help me to understand how to create a PR I'll be able to submit it (and I'll be able to submit the code for the timeline [New feature : Timeline #422](https://github.com/jgthms/bulma/issues/422)

**Comment by PierBover** [comment]
Hey @Wikiki first you have to fork this repo. Then clone and modify your fork. Then go to the pull requests tab from your repo and create a PR.

**Comment by rafaelpimpa** [comment]
How is the HTML structure for that switch?

**Comment by Wikiki** [comment]
Hi,

the HML code is the basic one:

<input name="maintenance" class="switch is-danger" type="checkbox">
<label class="label" for="">Maintenance mode</label>

You don't have to encapsulate the input inside the Label.

I'll change the transition to use the variable. Thankls for the hint ;-)

**Comment by jgthms** [comment]
Great initiative 👍 

I feel this style is too opinionated to add it to the core Bulma styles but you should create a separate repo and we can link it in the Readme.

**Comment by hunzaboy** [comment]
I also did a similar thing with the checkboxes. 

Will appreciate if @jgthms  can put it in the readme.
https://github.com/hunzaboy/Cool-Checkboxes-for-Bulma.io

**Comment by SaphiLC** [comment]
is not working, you updated the markup but not the sass code
