### ISSUE TITLE
checkbox and radio button not styled

### ISSUE THREAD

**Issue by bvanrijn** [jgthms/bulma#54]
The `<input type="checkbox">` and `<input type="radio">` are not properly styled.
Screenshot:
![screenshot from 2016-02-08 13 51 18](https://cloud.githubusercontent.com/assets/11941174/12886090/5213ddaa-ce6b-11e5-8352-06b07c2c2989.png)

They appear to be default style.

My browser:
* **Application Name:** Netscape
* **Code Name:** Mozilla
* **Version:** 5.0 (X11)
* **User Agent:** Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:44.0) Gecko/20100101 Firefox/

**Comment by uknick** [comment]
I think this is a Firefox bug - https://bugzilla.mozilla.org/show_bug.cgi?id=605985

**Comment by ash0080** [comment]
same in chrome now, but the style on official website is correct
