### ISSUE TITLE
Question: Changing color of select carat/arrow?

### ISSUE THREAD

**Issue by woat** [jgthms/bulma#545]
Is it a bug/feature/question or **do you need help**?
This is about the Bulma **CSS framework**.
I'm using Bulma **version** [0.3.2].
My **browser** is: Chrome.

What css property do I need to change in order to change the coloring of the select carat/arrow?

![d01cfaa7c6ff4798ac2015c18ccac5e6](https://cloud.githubusercontent.com/assets/21204849/23594374/85a68888-01e7-11e7-8b9c-a92fb0366c52.png)

I have successfully been able to change the outline, but I am not sure where to look for the carat/arrow.

**Comment by jenil** [comment]
You need to change the `.select:after` selector and adjust the `border-color`
