### ISSUE TITLE
When retrieving Bulma from npm, docs are not included

### ISSUE THREAD

**Issue by Bondifrench** [jgthms/bulma#548]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.3.2]

 I am sure this issue is **not a duplicate**: I verified in the issues I could not find `npm run docs`

### Description

After installing `Bulma` with `npm install bulma`
I can not build the docs

### Steps to Reproduce
Both:
1. npm run docs 
2. npm run test-sass

give me errors
### Expected behavior

I expect the docs to be built
### Actual behavior

npm gives me errors:
````
Failed at the bulma@0.3.2 test-sass script `node-sass --output-style expanded docs/bulma-test.sass docs/css/bulma-test.css`
````
similar error for `npm run docs`

I suspect it is because when I `npm install bulma` no `docs` folder is retrieved

**Comment by Bondifrench** [comment]
I found the culprit, in `package.json` you need to modify
````
"files": [
    "css",
    "sass",
    "bulma.sass",
    "LICENSE",
    "README.md"
  ]
````
so the folder `docs` is included otherwise when we `npm install bulma` this folder is not included and
`npm run docs` and `npm run test-sass` won't work.

**Comment by jgthms** [comment]
It's deliberate. The docs are too large to be included in the package. Plus, most users want the Bulma styles, not the documentation.

You can clone the repo to get the docs though.
