### ISSUE TITLE
dropdown shows dots when clicked

### ISSUE THREAD

**Issue by bvanrijn** [jgthms/bulma#55]
In additon to #54 (on not/incorrectly styled checkbox and radio input), the dropdown appears beautifully, but shows dots around the word "Dropdown" when clicked. 
![screenshot from 2016-02-08 13 58 28](https://cloud.githubusercontent.com/assets/11941174/12886272/518d73fe-ce6c-11e5-896a-95226691355a.png)

My browser is:

* **Application Name:** Netscape
* **Code Name:** Mozilla
* **Version:** 5.0 (X11)
* **User Agent:** Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:44.0) Gecko/20100101 Firefox/

**Comment by ncksllvn** [comment]
That is a property of the Firefox browser to indicate the element is focused in case the user does not have a mouse and is using the tab key. It is recommended you don't override that but [you can](http://stackoverflow.com/questions/71074/how-to-remove-firefoxs-dotted-outline-on-buttons-as-well-as-links). I imagine this CSS would do the trick:

```css
select::-moz-focus-inner {
  border: 0;
}
```

**Comment by jgthms** [comment]
Thanks @ncksllvn for resolving this.

I won't include that trick in Bulma because it's too specific, but anyone can resolve it themselves with this piece of code.
