### ISSUE TITLE
Question: Which CSS philosophy does Bulma follow?

### ISSUE THREAD

**Issue by minthemiddle** [jgthms/bulma#550]
I love the simplicity and explicity of Bulma. Reading out `<a class="button is-primary is-large">Black</a>` is very intuitive and easy to expand on.

I would love to learn more about this approach.

So: What is the philosophy of the CSS architecture behind Bulma?

**Comment by jgthms** [comment]
Thanks!

There is no philosophy really. Just common sense. If it's easy to read, it's easy to use.  
And nothing is set in stone. If there's a better approach, it will be adopted. But only if it makes sense.

I guess that's the keyword: sense.

**Comment by minthemiddle** [comment]
Thanks for the quick reply. Yes, I also think that it makes sense. Question answered.
