### ISSUE TITLE
Titles documentation uses h1/h2 in example code, "p" in source

### ISSUE THREAD

**Issue by viveleroi** [jgthms/bulma#553]
### Overview of the problem

This is about the Bulma **Docs**

I am sure this issue is **not a duplicate**

### Description

The "titles" section of the docs shows examples all using `h1` and `h2` elements, while the source code uses `p`

**Comment by Technologeek** [comment]
Don't think that should be a problem as the<p> element is just an example of how the "title" class can be applied.I will create a PR if this issue is  approved by @jgthms

**Comment by viveleroi** [comment]
It's an issue because the using the example code provided won't give the expected result. Using those classes on header elements won't look the same as when used on `p`.

**Comment by Technologeek** [comment]
What results are you expecting ? Mind posting an image ? I've created a pen with h1 elements using the title class,the results are no different than what's in the documentation using p .
[Check the Pen here](http://codepen.io/Technologeek/pen/qrrrjG)

**Comment by viveleroi** [comment]
Ok, so the difference I saw was the h1/h2, but *only* when they're inside `content`:

http://codepen.io/helion3/pen/xqqmmo

When not inside `.content` the `h1/h2` and `p/span` elements are styled the same.
