### ISSUE TITLE
How to compile the Bulma website/docs locally to test new features

### ISSUE THREAD

**Issue by git-toni** [jgthms/bulma#560]
### Overview of the problem
This is about the Bulma **Docs**

### Description

I'm adding a small feature to Bulma, together with its own sub-menu item in *Elements* menu, I would like to compile it all and test it on the website locally. So the question is:

How do you compile the Bulma docs/website to test my changes locally on the website itself?

**Comment by robin900** [comment]
It's not documented, but the docs site is produced with the Ruby-based `jekyll` tool.
1. Make sure Ruby 2.x is installed.
2. `gem install jekyll`

Then to view the documentation in your local checkout:
1. In a separate shell session, `cd` to the `docs/` directory, and do `jekyll serve _site`. This will start an HTTP server at http://localhost:4000/ that serves the docs built in the `_site` directory; and anytime the docs are rebuilt by you, it will serve the docs site on the fly.
2. In your main shell session where you develop, if you change anything in `docs/` the jekyll server will rebuild those on the fly. But if you change anything about the Bulma SASS or CSS, you need to do `npm run deploy` to build Bulma and the docs' CSS before you will see it in the browser.

**Comment by robin900** [comment]
@jgthms I've added a PR (#561) that adds how-to README.md to the docs/ directory.

**Comment by git-toni** [comment]
@robin900 that was so easy, thanks!

**Comment by imakatman** [comment]
FYI, the README.md says to run `npm run start-docs`
