### ISSUE TITLE
level class unresponsive

### ISSUE THREAD

**Issue by jericopulvera** [jgthms/bulma#563]
.level-left becomes a list in mobile mode is it normal?

Toggle Iphone 5 version of this.
https://dansup.github.io/bulma-templates/templates/timeline.html

Compare to this 
http://bulma.io/documentation/elements/box/

**Comment by Technologeek** [comment]
If you read the documentation,
>In a level-item, you can then insert almost anything you want: a title, a button, a text input, or just simple text. No matter what elements you put inside a Bulma level, they will always be **vertically centered**.

>By default, for space concerns, the level is vertical on mobile. If you want the level to be horizontal on mobile as well, add the **is-mobile** modifier on the level container.

You need to add `<nav class="level is-mobile">` to your main container.

**Comment by jgthms** [comment]
This is indeed the intended behaviour.
