### ISSUE TITLE
Style for <dl> in content element

### ISSUE THREAD

**Issue by mightyiam** [jgthms/bulma#565]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma 0.3.2

### Description

The content element does not include style for the [dl](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) element.

### Steps to Reproduce

Try a `dl` element.

### Expected behavior

I'd like some reasonable style for it.

### Actual behavior

Bulma resets it but Bulma does not style it.

**Comment by Technologeek** [comment]
This is more like a Feature Request.The default styles are working as it should be but I do agree the dl element could have it's own style.Any suggestions how you want it to look ?

**Comment by mightyiam** [comment]
I saw it as a bug because there are resets for this element. So it effectively just broke a browser feature.

I don't have valuable input, other than what Chrome does seems conceptually reasonable. I'm sure there are awesome examples out there. Perhaps in API documentations.
