### ISSUE TITLE
0.4.0 - fullheight hero padding is missing

### ISSUE THREAD

**Issue by jaredreich** [jgthms/bulma#568]
Great work on 0.4.0 - just went through the changes and I like them, just one thing I've noticed:
**fullheight hero padding is missing**

![image](https://cloud.githubusercontent.com/assets/8563847/23973723/0353e0fc-099d-11e7-9ee9-2a5ccd7a91e2.png)

http://bulma.io/documentation/layout/hero/

**Comment by sausin** [comment]
Strangely enough, if the center content is only a button it aligns perfectly in the middle for eg
```
<div>
<a class="button is-primary is-large">
	Click me to begin!
</a>
</div>
```
the above comes in the center, but other things don't

**Comment by psycokenisis** [comment]
I inspected the computed styles in 0.3.2 and compared to the 0.4.0. 
It looks like the `max-width` property changed in 0.3.2 into `width`, for this class selector; 
`.hero .hero-body .container`

The effects of this are much more apparent when using `<container is-fluid>`

Here's an example fiddle to compare the two versions
0.3.2: https://jsfiddle.net/kz11j7em/
0.4.0: https://jsfiddle.net/u3nmsjax/1/

Hope this helps :)

**Comment by jaredreich** [comment]
Upon further inspection, this is exactly the issue:

```sass
.hero.is-fullheight .hero-body>.container {
    flex-grow: 1;
    flex-shrink: 1;
}
```

Both `flex-grow` and `flex-shrink` should either be set to initial/0 or have these rules removed altogether.

**Comment by sausin** [comment]
For those looking for a temporary fix, you can use
```
<div class="columns">
    <div class="column is-half is-offset-one-quarter-tablet">
        <!-- content goes here -->
    </div>
</div>
```
inside the container of the hero-body

the column width can be changed as desired and 'has-text-centered' can be used on the container
