### ISSUE TITLE
0.4.0 - Horizontal form radios not aligned with label

### ISSUE THREAD

**Issue by worldspawn** [jgthms/bulma#569]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.0]
My **browser** is: Chrome
I am sure this issue is **not a duplicate**

In a horizontal form a label used to label a set of radios does not line up. 

![image](https://cloud.githubusercontent.com/assets/819581/23978419/05c3bd02-0a48-11e7-9508-8c3eaa583e94.png)

![alignment](https://cloud.githubusercontent.com/assets/819581/23978549/b761a538-0a48-11e7-8fb9-53b6e825f130.gif)

Markup used:
``` html
<div class="field is-horizontal" ng-init="vm.customType = null; vm.customKey = null; vm.customValue = [null];">
        <div class="field-label">
            <label class="label">Type</label>
        </div>
        <div class="field-body">
            <div class="field">
                <p class="control">
                    <label class="radio">
                        <input type="radio" name="customtype" ng-model="vm.customType" value="simple" ng-required="true" />
                        Simple
                    </label>
                    <label class="radio">
                        <input type="radio" name="customtype" ng-model="vm.customType" value="complex" ng-required="true" />
                        Complex
                    </label>
                </p>
            </div>
        </div>
    </div>
```

**Comment by OnrCan** [comment]
I think your problem occurs because of your using way. Maybe it would help you to check the document `https://github.com/jgthms/bulma/blob/master/docs/documentation/elements/form.html`

and look the way how field element is used :)

**Comment by jgthms** [comment]
This is indeed a bug. The `.label` has a padding-top to align with the `.input` (which is 2.25em high). But this doesn't work with smaller elements (radio buttons, checkboxes), or larger ones (is-medium, is-large inputs, textareas...).

I will create classes for the label alignment.
