### ISSUE TITLE
0.4.0 Nav menu has some problem

### ISSUE THREAD

**Issue by sausin** [jgthms/bulma#570]
### Overview of the problem

The nav bar is behaving strangely now. 

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]
My **browser** is: Chromium 56

### Description

The right menu ends up closer to the center screen when resizing and there is a scrollbar that appears on the left menu

### Steps to Reproduce

1. Go to http://bulma.io/documentation/components/nav/
2. Resize the browser window
3. See the issue where 'is-tab' modifier is used in the nav

### Expected behavior

In the previous versions, this aligned correctly

### Actual behavior

It's aligning incorrectly

**Comment by jgthms** [comment]
Probably dupe of #581
