### ISSUE TITLE
Uncaught ReferenceError: Clipboard is not defined

### ISSUE THREAD

**Issue by bgarrant** [jgthms/bulma#574]
Is it a bug/feature/question or do you need help? 

Uncaught ReferenceError: Clipboard is not defined

### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.4.0]

### Description

When I include bulma.js to make the navigation work I get this error:

Uncaught ReferenceError: Clipboard is not defined
    at HTMLDocument.<anonymous> (bulma.js:59)
    at i (jquery-2.2.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.0.min.js:2)
    at Function.ready (jquery-2.2.0.min.js:2)
    at HTMLDocument.J (jquery-2.2.0.min.js:2)

If I add the clipboard.min.js to my layout it resolves the issue, but I assume we do not need that file for a normal website correct?

### Steps to Reproduce

Add this to footer or your page:
```
<script src="/js/jquery-2.2.0.min.js"></script>
<script src="/js/bulma.js"></script>
```

If you include the clipboard.min.js file the error goes away.

```
<script src="/js/jquery-2.2.0.min.js"></script>
<script src="/js/clipboard.min.js"></script>
<script src="/js/bulma.js"></script>
```
### Expected behavior

No errors

### Actual behavior

Uncaught ReferenceError: Clipboard is not defined
    at HTMLDocument.<anonymous> (bulma.js:59)
    at i (jquery-2.2.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.0.min.js:2)
    at Function.ready (jquery-2.2.0.min.js:2)
    at HTMLDocument.J (jquery-2.2.0.min.js:2)

Can we safely remove this code from the bulma.js file to remove the issue or is that clipboard.min.js file needed for any funstions?

```
  new Clipboard('.copy', {
    target: function(trigger) {
      return trigger.previousSibling;
    }
  });
```

**Comment by bgarrant** [comment]
Commenting out these lines in the bumla.js seems to fix the issue but will there be any other components affected?

```
/*
  new Clipboard('.copy', {
    target: function(trigger) {
      return trigger.previousSibling;
    }
  });
*/
```

**Comment by jgthms** [comment]
`bulma.js` is only meant for the documentation. It's not part for the framework.

**Comment by bgarrant** [comment]
The navbar component does not work without it?  What should I use then?

**Comment by bgarrant** [comment]
this part is needed for the navbar to toggle open/closed correct?
```
jQuery(document).ready(function ($) {

  var $toggle = $('#nav-toggle');
  var $menu = $('#nav-menu');

  $toggle.click(function() {
    $(this).toggleClass('is-active');
    $menu.toggleClass('is-active');
  });
```

**Comment by bgarrant** [comment]
So what do we need to use to get the nav component to work?
```
  <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
  <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
```
I included this and it still does not work
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
```
```
    <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
    <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
    <span id="nav-toggle" class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>

    <!-- This "nav-menu" is hidden on mobile -->
    <!-- Add the modifier "is-active" to display it on mobile -->
    <div id="nav-menu" class="nav-right nav-menu">
```

**Comment by bgarrant** [comment]
Is this all I need?
```
    <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  {# <script src="/js/clipboard.min.js"></script> #}
  {# <script src="/js/bulma.js"></script> #}
  <script>
    var $toggle = $('#nav-toggle');
    var $menu = $('#nav-menu');

    $toggle.click(function() {
      $(this).toggleClass('is-active');
      $menu.toggleClass('is-active');
    });
  </script>
```

**Comment by jgthms** [comment]
Bulma does not include any JavaScript. So you have to implement the class toggle yourself.
