### ISSUE TITLE
Extra mobile breakpoint

### ISSUE THREAD

**Issue by imade-nl** [jgthms/bulma#577]
I would love to see an extra mobile breakpoint for larger or landscape phones. 
For example `@media (min-width: 576px) { ... }`

**Comment by jgthms** [comment]
As there are 4 breakpoints, another one would be too much I believe for now. But feel free to add it as an extension!

**Comment by nicoladl** [comment]
For me this works
`@include mobile {
	@media (orientation: landscape) {
		....
	}
}`
