### ISSUE TITLE
Offsets

### ISSUE THREAD

**Issue by maestromutenrroy** [jgthms/bulma#58]
Hello, your framework it's fine, but I need offsets columns in my grid... this is possible?
I would like use in a grid in first row two columns width photos and in the next row only one column (is-8) in center without others columns by example.. 

Example bootstrap:
```
<div class="row">
    <div class="col-md-2 col-md-offset-5"></div>
</div>
```

Thanks!

**Comment by jgthms** [comment]
Yes, offsets are not implement _yet_.

One way to do it right now is to add empty `column` elements, like:

```
<div class="column is-5"></div>
<div class="column is-2">
  Your actual content
</div>
```

I'm trying to figure out an elegant way to have offset classes.

**Comment by jgthms** [comment]
This has been added.
