### ISSUE TITLE
Consider making previous docs of bulma available in the website.

### ISSUE THREAD

**Issue by guillecro** [jgthms/bulma#582]
The title says it all.

It would be nice to have previous versions of bulma docs when radical changes like the ones in v.0.4.0 are available.

I went back to 0.3.2 due to bugs from v0.4.0 (which, is understandable) and the docs for v0.3.2 would've come handy at that moment.

Thanks~

**Comment by Technologeek** [comment]
Wouldn't it be redundant to maintain two different versions of docs for the same project on the same repo ? Just download the old version and run the documentation locally [as described here](https://github.com/jgthms/bulma/tree/master/docs).

**Comment by yoostk** [comment]
I like the idea to have multiple versions' docs. It's just inconvenient to run server every time you see older docs. Namespace docs with its versions, like `http://bulma.io/documentation/v1.0/` would be nice. I hope this will be on the roadmap to v1.

**Comment by guillecro** [comment]
Sometimes updating my crode from one version to another is not an easy thing to do, I lost a lot of time rolling back my code from v0.4.0 to v0.3.x due to some missing components in the code.. I did what @Technologeek suggested and it was a pain in the place where the sun doesn't shine
**And this is nothing urgent, of course!** It's just a improvement! (Or not(??))
