### ISSUE TITLE
-fullhd breakpoint doesn't seem to work

### ISSUE THREAD

**Issue by sunabozu** [jgthms/bulma#583]
Hi.

This is about the Bulma **CSS framework** or, possibly, Bulma docs, I'm not quite sure. In your [docs]() you mention the new -fullhd breakpoint. I tried to use it, but it didn't seem to work. So I checked the (sources](https://github.com/jgthms/bulma/blob/master/css/bulma.css) and didn't find it there.
Can you please clarify if this is a bug or this breakpoint is supposed to be present in some other version?

I'm using Bulma **version** 0.4.0. I tried to import both css and scss files with the same result.

**Comment by jgthms** [comment]
The only instance for now is for the `.container`: https://github.com/jgthms/bulma/blob/master/css/bulma.css#L2786
