### ISSUE TITLE
0.4.0 - Select `is-fullwidth` does not work

### ISSUE THREAD

**Issue by jaredreich** [jgthms/bulma#585]
Bug about Bulma, found in the docs.

### Overview of the problem

This is about the Bulma **CSS framework** -->
This is about the Bulma **Docs** -->
I'm using Bulma **0.4.0**
My **browser** is: Chrome 56
I am sure this issue is **not a duplicate**

### Description

`is-fullwidth` class does not work for select:
```html
<div class="select is-fullwidth">
  <select>
    <option>Business development</option>
    <option>Marketing</option>
    <option>Sales</option>
  </select>
</div>
```

### Steps to Reproduce

Go to http://bulma.io/documentation/elements/form/
then scroll to Horizontal Form section
See that the "Department" Select is not full width, even though the class selector is applied

### Expected behavior

Select to be full width

### Actual behavior

Select is not full width

**Comment by jaredreich** [comment]
## CORRECTION

The `is-fullwidth` does work on the `<div class="select is-fullwidth">...` but it is not working in the docs.

**Comment by jgthms** [comment]
Oh yeah it's because there is `field is-narrow`, so the `select is-fullwidth` is not applied.
