### ISSUE TITLE
0.4.0 - Select `is-*` does not apply border style

### ISSUE THREAD

**Issue by jaredreich** [jgthms/bulma#586]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **0.4.0**
My **browser** is: Chrome 56
I am sure this issue is **not a duplicate**

### Description

Select element should have coloured border for `is-success`, `is-danger`, etc. classes, as the input elements do.

### Steps to Reproduce

Apply class `is-danger` to Select, and see that it has no coloured border.

### Expected behavior

For coloured status borders to be applied to Select elements just like they are for Input elements

### Actual behavior

Coloured status borders are not applied to Select elements

### Fix

```sass
select.is-danger {
  border: 1px solid $danger;
}
// etc...
```

**Comment by jgthms** [comment]
Done in https://github.com/jgthms/bulma/pull/619
