### ISSUE TITLE
Delete button of tag within a notification attaches to the notification

### ISSUE THREAD

**Issue by R13N** [jgthms/bulma#589]
### Overview of the problem
When placing a `delete` button in a `tag` which is inside a `notification`, it attaches to the notification.

This is about the Bulma **CSS framework**

I'm using Bulma **v0.4.0**
My **browser** is: Chromium, but this also happens on Firefox (I did not test it on other browsers).

I am sure this issue is **not a duplicate**? [I did not find a similar issue.](https://github.com/jgthms/bulma/issues?q=is%3Aissue%20delete%20)

### Steps to Reproduce
I created a [codepen]( https://codepen.io/anon/pen/RpMLNL) to demonstrate this issue.

### Expected behavior
The `delete` button should be inside the `tag`.
![2017-03-21-220906_492x179_escrotum](https://cloud.githubusercontent.com/assets/3226995/24170991/0837be78-0e83-11e7-8969-8918d43e527d.png)

### Actual behavior
The `delete` button attaches to the notification.
![2017-03-21-215616_521x217_escrotum](https://cloud.githubusercontent.com/assets/3226995/24170496/516b6984-0e81-11e7-8931-b7cae83dd112.png)

### My own _hacky_ fix
I fixed this by adding the following CSS:
```CSS
.notification .delete{
  position: relative;
  top: unset;
  right: unset;
}
```
As you can see in [this codepen](https://codepen.io/anon/pen/vxReKW).

**Comment by jgthms** [comment]
This has been fixed: https://github.com/jgthms/bulma/blob/master/sass/elements/notification.sass#L15
