### ISSUE TITLE
Icons in front of other elements

### ISSUE THREAD

**Issue by xereda** [jgthms/bulma#590]
### Overview of the problem

This is about the Bulma **CSS framework** 

### Description

Icons are getting in front of other elements. I need to leave them with a lower z-index.

Icons always behind other elements.

### Actual behavior

Icons in front of other screen elements.

Look at this:

![icones_bulma](https://cloud.githubusercontent.com/assets/14337850/24179186/5718a6e8-0e8c-11e7-9baa-d50acfd6bd4e.gif)

**Comment by jgthms** [comment]
Where does that dropdown come from? Can you set a higher `z-index` for that?

**Comment by xereda** [comment]
I can, but as I have 3 elements of this on the screen, when I report a zindex to him, one ends up getting over the other. The question of my select is that it opens up or down depending on the position of the screen scroll. So it gets difficult to set a zindex for them. The easiest thing would be to define a zindex for the icons. They are the only ones who get on top.

Can you help me do that? Thank you.

**Comment by Technologeek** [comment]
@xereda Mind linking to your code either on codepen or just post here ? I think I can help you out.

**Comment by jgthms** [comment]
The icons have a `z-index` of `1` or `2` I believe. It is required for them to show up above the input next to them. It's not possible to remove it.

But `z-index` is a relative property. You need to set a higher one on your custom dropdowns.

**Comment by xereda** [comment]
But note that only with the native classes of the Bulma Framework, the order of presentation of the icons is already incorrect.

![bulma_css](https://cloud.githubusercontent.com/assets/14337850/24638633/7912fe54-18c0-11e7-82b0-a1e86da3676c.gif)

JSBIN: https://jsbin.com/zipuboj/15/edit?html,js,console,output

**Comment by xereda** [comment]
It should not be z-index 1 or 2. It should be larger...

**Comment by jgthms** [comment]
Mmmh fair enough. LMHAL

**Comment by jgthms** [comment]
#636

**Comment by mtrabelsi** [comment]
they advertise it as the new generation of css framework, but if you start using it you see alot of hacks and anti patterns, sorry but it is true!
