### ISSUE TITLE
Vertically stacked buttons have no spacing between them

### ISSUE THREAD

**Issue by Acidic9** [jgthms/bulma#594]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.0]
My **browser** is: Chrome

### Description
When buttons are stacked on top of each other due to a mobile screen size, the buttons have no vertical spacing between them. I think some spacing between vertically stacked buttons would be nice to see.

### Steps to Reproduce
1. Create several buttons anywhere on the website with the same parent.
`<a class="button">Button 1</a><a class="button">Button 2</a>`

2. Shrink your browser to cause the buttons to vertically stack.

### Expected behavior
I expected some vertical spacing between the buttons.

### Actual behavior
The buttons were completely touching with no spacing between them.
[![https://gyazo.com/8a376f226c36737c353a1679323bb5b1](https://i.gyazo.com/8a376f226c36737c353a1679323bb5b1.png)](https://gyazo.com/8a376f226c36737c353a1679323bb5b1)

**Comment by jgthms** [comment]
That is the normal behavior. You can use the `field` class to add vertical spacing.
