### ISSUE TITLE
Bulma accordion component

### ISSUE THREAD

**Issue by bovisp** [jgthms/bulma#597]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I am creating a Vuejs accordion component. I use Bulma as the CSS framework, but there is no accordion component at the moment. To remedy this, I'm building my own based off of the Tabs component. Is there a desire for an accordion component in Bulma. If so, I would be happy to submit my code to you via this issue when I'm done. Thoughts?

**Comment by jgthms** [comment]
You can probably use the card component: http://bulma.io/documentation/components/card/

Use the `card-header` as the toggle for the `card-content`.

**Comment by guruas3** [comment]
@bovisp 
There is already one: https://github.com/vue-bulma/collapse
You can install it also from npm as vue-bulma-collapse

**Comment by bovisp** [comment]
@guruas3 nice! Thanks!
