### ISSUE TITLE
Sizing issue

### ISSUE THREAD

**Issue by niallobrien** [jgthms/bulma#602]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

It seems that the sizing variables are backwards. See https://github.com/jgthms/bulma/blob/master/sass/utilities/variables.sass#L33-L39

### Expected behavior

I expect the sizes to increase with the sizing numbers

### Actual behavior

The sizes get smaller the larger numbered classes you use.

**Comment by jgthms** [comment]
It's meant to replicate the HTML headings, from `h1` to `h6`. I agree that the `size-7` might be confusing, but it's meant as the "small" size.
