### ISSUE TITLE
Nav-menu with Nav-center means display: flex instead of none

### ISSUE THREAD

**Issue by RichardOutram** [jgthms/bulma#603]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]
My **browser** is: Latest chrome

### Description
The display: flex styling within nav-center is overwriting the display: none inside nav-menu on mobile. This causes it to be displayed when it should be hidden.

### Steps to Reproduce

1. Setup a navigation, like the example. Use nav-menu within nav-center instead of nav-right

### Expected behavior

On the mobile breakpoint the nav menu is hidden

### Actual behavior

The nav menu is visible
![screen shot 2017-03-27 at 13 23 30](https://cloud.githubusercontent.com/assets/25500835/24338407/df2df50c-12f0-11e7-9c89-0b7fcb72d369.png)
![screen shot 2017-03-27 at 13 23 20](https://cloud.githubusercontent.com/assets/25500835/24338408/df324558-12f0-11e7-9687-baee18a9d580.png)

**Comment by jgthms** [comment]
It's because `nav-menu` can only be paired with `nav-right`.
