### ISSUE TITLE
Buttons with addons overlap borders when is-active

### ISSUE THREAD

**Issue by dmackca** [jgthms/bulma#607]
### Overview of the problem

 This is about the Bulma **CSS framework** 

 I'm using Bulma **version** 0.4.0
 My **browser** is: Firefox 52 (Windows 10 & OSX El Capitan) / Chrome 57 (El Capitan)

 I am sure this issue is **not a duplicate**

### Description

When buttons with `.is-active` are grouped with `.field.has-addons`, any button to the right overlaps, hiding its 1px right border. They appear to rely on the z-index from the `:hover` to avoid this overlap, but `.is-active` might not be hovered.

### Steps to Reproduce

Create a group of default buttons and make one `is-active`:

``` html
<div class="field has-addons">
    <p class="control">
      <a class="button is-active">
        <span>Foo</span>
      </a>
    </p>
    <p class="control">
      <a class="button">
        <span>Bar</span>
      </a>
    </p>
</div>
```

[Codepen example](http://codepen.io/anon/pen/YZOOdg) 
(Note how the border shows correctly only on hover.)

### Expected behavior

The 1px black border should show on all 4 sides of the buttons with `is-active`

### Actual behavior

The black border only shows on 3 sides, with the right side overlapped by adjacent buttons.

**Comment by jgthms** [comment]
Ah yes a z-index issue. LMFT.
