### ISSUE TITLE
Different versions of 0.4.0 are available

### ISSUE THREAD

**Issue by cvenzin** [jgthms/bulma#609]
### Overview of the problem

CDN, NPM, github and http://bulma.io/css/bulma-docs.css do not have the same content even though all are taged as version 0.4.0.

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.4.0] 
My **browser** is: Firefox 52.0.2 (32-Bit)

### Description

The CDN and npm version is broken for Inputs or Selects on Firefox 52.0.2 (32-Bit) -> padding-top and padding-bottom are too high and the text is cut off.
http://bulma.io/css/bulma-docs.css is fine.

### Steps to Reproduce

Use Firefox on http://bulma.io/ -> selects with "ggggg" as value look fine.

.select select {
  ...
padding-bottom: 0.375em;
  padding-left: 0.625em;
  padding-right: 0.625em;
  padding-top: 0.375em;
 ...
}

Use Firefox on a own page with the npm or CDN version of bulma. The "ggggg" is cut of in select fields.

.select select {
  ...
  padding-bottom: 0.5em;
  padding-left: 0.625em;
  padding-right: 0.625em;
  padding-top: 0.5em;
 ...
}

### Expected behavior

All bulma.css files with the same version should be equal. Preferably the http://bulma.io/css/bulma-docs.css version as it is the one that works correctly.

**Comment by cvenzin** [comment]
Realted to #571

**Comment by jgthms** [comment]
Yes it's because I was asking to rebuild the CSS files for each PR. That was a mistake. I updated the [guidelines](https://raw.githubusercontent.com/jgthms/bulma/master/.github/PULL_REQUEST_TEMPLATE.md).
