### ISSUE TITLE
Bulma form alignment

### ISSUE THREAD

**Issue by MagoDev** [jgthms/bulma#611]
I copied and pasted some code from the official Bulma.io website but the results are not the same.
Field has-addons, is-grouped and is-horizontal do not work.

What will be the problem?

**Comment by jgthms** [comment]
What version do you have?

**Comment by MagoDev** [comment]
i use CDN

**Comment by chafreaky** [comment]
Yes, I have the same issue. One of the problem happens here:

In the documentation, for grouped elements, we are to use `.field.is-grouped` however the compiled CSS has `.control.is-grouped`. There actually is no permutation that uses the class `.field`.

**Comment by jgthms** [comment]
The 0.4.0 version on the CDN includes `.field.is-grouped`: https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.css
