### ISSUE TITLE
Button not visible if used in coloured hero section

### ISSUE THREAD

**Issue by introwit** [jgthms/bulma#616]
- Using the following code the button isn't visible and just a white block appears

```html
<body>
 <section class="hero is-medium is-info is-bold">
  <div class="hero-body">
   <div class="container">
    <p class="title is-spaced">
     Some Title
    </p>
    <p class="subtitle">
     Some subtitle
    </p>
    <a class="button">Button</a>
   </div>
  </div>
 </section>
</body>
```
Output :
![b1](https://cloud.githubusercontent.com/assets/11228182/24579024/d4bac564-170a-11e7-9039-7c277267c352.png)

- If I remove the `is-info` class from the section like as follows then the button is visible

```html
<body>
 <section class="hero is-medium is-bold">
  <div class="hero-body">
   <div class="container">
    <p class="title is-spaced">
     Some Title
    </p>
    <p class="subtitle">
     Some subtitle
    </p>
    <a class="button">Button</a>
   </div>
  </div>
 </section>
</body>
```

Output: 
![b2](https://cloud.githubusercontent.com/assets/11228182/24579036/18a2ac9c-170b-11e7-836f-359a3d4e559f.png)

**Comment by introwit** [comment]
@jgthms Also if I make any word from the subtitle a link, like for example if in the above code I do this:

```html
<p class="subtitle">
     Some <a href="#">subtitle</a>
</p>
```
Then no color properties work on it. Suppose I do:

```css
a:hover {
    color: red;
}
```
That doesn't works as well

**Comment by jgthms** [comment]
Fixed by https://github.com/jgthms/bulma/pull/617
