### ISSUE TITLE
Color properties don't work if I make the text/word a link in title or subtitle of hero layout

### ISSUE THREAD

**Issue by introwit** [jgthms/bulma#622]
Thank you for fixing the [earlier issue](https://github.com/jgthms/bulma/issues/616), but there was one more problem I faced and commented but seems like it got missed. The issue is as already said in this [comment](https://github.com/jgthms/bulma/issues/616#issuecomment-290921236)

**Comment by jgthms** [comment]
Probably a priority issue: http://marksheet.io/css-priority.html

It's hard to tell without the context.
