### ISSUE TITLE
Text doesn't fit (vertically) within dropdown button

### ISSUE THREAD

**Issue by Heliosmaster** [jgthms/bulma#624]
### Overview of the problem

Text doesn't fit vertically within the dropdown. No custom styling is applied to the provided screenshot.

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]

I am sure this issue is **not a duplicate**?

### Description

![img](https://puu.sh/v6TUs/325846a999.png)

### Steps to Reproduce

1. Have text like "Maggio" within the dropdown.

### Expected behavior

The text is not vertically cut.

### Actual behavior

Text is cut.

**Comment by jgthms** [comment]
Dupe #571
