### ISSUE TITLE
Notification and is-pulled don't work together

### ISSUE THREAD

**Issue by sausin** [jgthms/bulma#635]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]
My **browser** is: Chromium 56.0.2924.76

I am sure this issue is **not a duplicate**?

### Description

When using a notification div with is-pulled-left and is-pulled-right modifiers inside, the padding / margin breaks

### Steps to Reproduce

1. Create a notification div like so:
```
<div class="notification is-info">
</div>
```
2. Create is-pulled elements inside:
```
<div class="is-pulled-left"><p>I am left</p></div>
<div class="is-pulled-right"><button class="button">Right button</button></div>
```
3. See the result in browser as

### Expected behavior

The result can be achieved correctly by using columns and having has-text-* modifiers

![image](https://cloud.githubusercontent.com/assets/11542923/24634071/292c0bc2-18cc-11e7-963d-9c20ebf86916.png)

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/11542923/24634010/e8f58f2e-18cb-11e7-9ae5-34b984a0c879.png)

**Comment by jgthms** [comment]
`is-pulled` is for floats. You should use the level component instead: http://bulma.io/documentation/components/level/

**Comment by lukepighetti** [comment]
Level example pasted inside a navbar does not pull level-right to the right it seems.
