### ISSUE TITLE
Sidemenu without priority for presentation.

### ISSUE THREAD

**Issue by xereda** [jgthms/bulma#636]
First of all, congratulations to all involved for the excellent work with the Framework. You guys are awesome!

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]

My **browser** is: Chrome, Safari and Firefox

### Description

The sidemenu offered by the Framework does not have presentation priority.

### Steps to Reproduce

JSBin: https://jsbin.com/zipuboj/15/edit?html,js,console,output

### Expected behavior

The sidemenu needs to stay above any other screen element, without requiring custom classes.

### Actual behavior

Icons, for example, stand over the sidemenu.

Another question: at the bottom, should have a background to hide the elements of the screen. The user experience would be better.

![bulma_css](https://cloud.githubusercontent.com/assets/14337850/24639086/ac7e7b12-18c3-11e7-953b-aabe749b8019.gif)

How it works:
![como_fica](https://cloud.githubusercontent.com/assets/14337850/24639005/36aad8ae-18c3-11e7-89df-57e15b841d24.png)

How it should really stay:
![como_deveria_ficar](https://cloud.githubusercontent.com/assets/14337850/24639014/44570f72-18c3-11e7-90b6-9c8c771a8ee6.jpg)

**Comment by uilianmengue** [comment]
I solved my problem changing "z-index" element in css file.
