### ISSUE TITLE
[Bug] Medium expanded input with left icon and attached controls

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#638]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [x.x.x] -->  0.40
My **browser** is: --> Chrome, Firefox - both mobile

### Description

Medium expanded input with left icon and attached controls.
1) it is not responsive
2) icon appears above mobile menu

### Steps to Reproduce

1. 
```
<div class="field has-addons">
  <p class="control has-icon is-expanded">
    <input class="input is-medium" type="email" placeholder="Email">
    <span class="icon is-medium">
      <i class="fa fa-envelope"></i>
    </span>
  </p>
  <p class="control">
    <a class="button is-info is-medium">
      Search
    </a>
  </p>
</div>
```
2. or download whole sample template here https://github.com/tu5/somestuff/archive/master.zip

### Actual behavior

![-home-jan-desktop-bulma-templates-master-templates-skeleton html iphone 6 3](https://cloud.githubusercontent.com/assets/18059922/24660958/403c9496-1951-11e7-9c6b-d5e660c7e777.png)
![-home-jan-desktop-bulma-templates-master-templates-skeleton html iphone 6 2](https://cloud.githubusercontent.com/assets/18059922/24660960/43367112-1951-11e7-94ff-83202f78419c.png)

**Comment by jgthms** [comment]
#636

**Comment by xereda** [comment]
How did this happen?
