### ISSUE TITLE
[Question] Is there a Bulma-way to write text on images?

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#639]
### Overview of the problem

This is about the Bulma **CSS framework** --> Is there a Bulma-way to write text on images?

I'm using Bulma **version** [x.x.x] --> 0.4.0

**Comment by jgthms** [comment]
Just use background images? http://marksheet.io/css-background.html#background-image

**Comment by iacobson** [comment]
@tu5 I'm using `class "is-overlay "`
https://bulma.io/documentation/modifiers/helpers/

**Comment by dharmveer97** [comment]
Is there a Bulma-way to write text on image
is-overlay not working it is working on card class....xx

**Comment by chandra05ar** [comment]
@dharmveer97 I think u r missing some syntax in the class definition, `"is-overlay"` works on any`<div>` element the CSS that defines it is``` .is-overlay{ bottom: 0; left: 0; position: absolute; right: 0; top: 0;}``` .

**Comment by ombudev** [comment]
> @dharmveer97 I think u r missing some syntax in the class definition, `"is-overlay"` works on any`<div>` element the CSS that defines it is` .is-overlay{ bottom: 0; left: 0; position: absolute; right: 0; top: 0;}` .

How did you implement this cause I've been looking for a solution to place text and a button over an image
