### ISSUE TITLE
Specified different columns for different viewport sizes doesn't seem to work

### ISSUE THREAD

**Issue by akshaybharwani** [jgthms/bulma#64]
How do I go about having a grid where I have one column on mobile, two columns on a tablet and four columns on a desktop?
Because I tried <code>is-tablet-half</code> and <code>is-desktop-quarter</code> and that doesn't seem to work. Maybe I'm missing some CSS modifications.

**Comment by jgthms** [comment]
It's `is-half-tablet` and `is-quarter-desktop`.
