### ISSUE TITLE
[Feature] Ears

### ISSUE THREAD

**Issue by mightyiam** [jgthms/bulma#641]
### Overview of the problem

This is about the Bulma **CSS framework**

I hope this issue is **not a duplicate**

### Description

"Ears". Like this example, from your docs:

![screenshot_2017-04-05_12-20-11](https://cloud.githubusercontent.com/assets/635591/24698768/7b698232-19fa-11e7-8803-bcfd991860e7.png)

In the docs they are implemented with pseudo selector `::before`. I think that as a feature of Bulma, they could not be implemented this way, because the `content` would always be hard-coded.

So, I don't know how they could be implemented. Perhaps as elements that don't have any bottom margin, so they stick to the top of the element below them? I'll leave it to the pros.

**Comment by jgthms** [comment]
Not sure how needed this feature is. It's easy to add but I question its popularity.

**Comment by mightyiam** [comment]
I'd take it as practice, if you'd like it in.

**Comment by gustojs** [comment]
A nice way to have a button / menu / tag with name for a box or a workspace to drag panels from place to place.

**Comment by dmyca** [comment]
I want that.

**Comment by ajitid** [comment]
I too want that!

**Comment by jgthms** [comment]
I believe this could work as an extension, but not necessarily as part of Bulma.

**Comment by ctolkien** [comment]
Yeah Bulma is already reeeaally heavy. Would prefer these be kept as extensions.

**Comment by mightyiam** [comment]
Non-the-less @jgthms's opinion, @ctolkien, Bulma is modular, so one can import the parts one uses.

**Comment by ctolkien** [comment]
>Bulma is modular, so one can import the parts one uses.

Sure, but there is overhead in doing so. I've saved about 5% in CSS size by doing it in the past with some sites I'm working on, and deemed that saving not to be worth the trouble and having to keep track of which elements you have available, etc.
