### ISSUE TITLE
Ship Minified to Packagers

### ISSUE THREAD

**Issue by jhabdas** [jgthms/bulma#642]
Please ship `bulma.min.css` to NPM and Bower in addition to CDN.

**Comment by jgthms** [comment]
There were issues with the minification process, hence why it was removed. I believe the minification process should be part of each user's custom build, not the library (until I found a better minifier).

**Comment by jhabdas** [comment]
@jgthms Thanks for the quick response and fair enough. When I saw the minified build on the CDN I incorrectly assumed you were already cleaning the CSS in your build. Upon closer inspection I was wrong. Which minifier were you having issues with? Perhaps I can send in a pull.
