### ISSUE TITLE
container.sass is missing

### ISSUE THREAD

**Issue by seifsay3d** [jgthms/bulma#644]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I cannot seem to find container.sass in the modules.

### Expected behavior
Just like the docs, layout includes hero, section, footer, it should also include container

### Actual behavior

Missing file.

**Comment by jgthms** [comment]
It's in https://github.com/jgthms/bulma/blob/master/sass/elements/other.sass#L4

**Comment by LasseRafn** [comment]
I'd argue that this should be moved to `sass/layouts`, or that the docs should be updated to reflect that its an element.
