### ISSUE TITLE
[support] card columns?

### ISSUE THREAD

**Issue by somenxavier** [jgthms/bulma#645]
Can we emulate card columns like in [bootstrap](http://v4-alpha.getbootstrap.com/components/card/#card-columns). That is a cards grid placed in columns which number of columns changes with resolution of the device.

Thanks,

**Comment by SoerenTerh** [comment]
If I am not mistaken, you can simply achieve that by nesting those cards into tiles. Tiles are comparable on what Bootstrap achieved with their implementation of a card grid.

**Comment by somenxavier** [comment]
@SoerenTerh Tiles are good but are structured. I need a non-structured ones because I want that tiles (or whatever) redistribute them automatically depending on screen resolution. Ideally I want something like this:

```
<div class="grid">
<div class="grid-element">Foo</div>
<div class="grid-element">Foo</div>
<div class="grid-element">Foo</div>
<div class="grid-element">Foo</div>
...
</div>
```

`grid-elements` put them in columns, which dynamically changes.

**Comment by somenxavier** [comment]
Something like [this](http://somenxavier.xyz) with this [behaviour](https://somenxavier.github.io) (resize screen)

**Comment by dbehterev** [comment]
You  need to use media queries. Something like that:
```
.module-card-wrap {
  display: flex;
  flex-wrap: wrap;
}

.module-card {
  min-width: 100%;
  display: flex;
  flex-direction: column;

  @media (min-width: $screen-md) {
    width: 48%;
    min-width: 0;
  }

  @media (min-width: $screen-lg){
    width: 30%;
    min-width: 0;
  }

  @media (min-width: $screen-xl){
    width: 25%;
    min-width: 0;
  }

  @media (min-width: $screen-xxl){
    width: 20%;
    min-width: 0;
  }
}
```
After that you should nest bulma card into .module-card:
```
<div class="columns">
  <div class="column">
    <div class="module-card-wrap">
      <div class="module-card">
          <div class="card"></div>
          <div class="card"></div>
          ...
      </div>
     </div>
  </div>
</div>
```

**Comment by somenxavier** [comment]
Thanks a lot.

**Comment by somenxavier** [comment]
Perhaps they could incorporate in mainstream

**Comment by kaymas** [comment]
@dbehterev I think that in the nesting part the class of **module-card** should come along with the the div that has the class of card like `<div class="module-card card"></div>`
