### ISSUE TITLE
container not working (to me)

### ISSUE THREAD

**Issue by fbrau** [jgthms/bulma#648]
Hi, I'm making an app with bulma and wanted a "container" but the result is not different than with no "container". It doesnt look centered as in the examples in the docs

code in here: http://linkode.org/ajYZXhe1G0v4Nc7E5RkrD2

**Comment by SoerenTerh** [comment]
In the documentation, they refer to the container as an element, that

> can be used in any context, but mostly as a direct child of either:
> 
> .nav
> .hero
> .section
> .footer

So the effect you are trying to achieve is done by nesting the container in f.e. a section with the class section: https://jsfiddle.net/4w6jLw2L/4/

**Comment by fbrau** [comment]
Thats it.. I thought "any context" meant "anywhere"... thnks
