### ISSUE TITLE
Nav-left items are scrollable

### ISSUE THREAD

**Issue by noleafclover614** [jgthms/bulma#649]
![773x434](https://cloud.githubusercontent.com/assets/8203609/24815597/b2f4a1dc-1ba3-11e7-813f-15c6c5a20300.PNG)

### Overview of the problem

I'm using Bulma **version** 0.4.0
My **browser** is: Google Chrome 57.0.2987.133

### Description

Using the stock **nav has-shadow** nav-bar, nav-left items become scrollable left and right on certain screen sizes.

### Steps to Reproduce

1. Create a new *.html file and include the Bulma css.
2. Copy/pase the **nav has-shadow** code snippet from the Bulma docs into an HTML file.
3. Shrink screen size to 773px width.
4. Observe scrollable **nav-left** items.

### Expected behavior

The **nav-left** items are hidden/shown based on the responsive helpers.

### Actual behavior

The **nav-left** items appear scrollable.

**Comment by jgthms** [comment]
Will be fixed in 0.4.1, or if you build from `master`.

**Comment by noleafclover614** [comment]
Thanks @jgthms

**Comment by xamists** [comment]
@jgthms Still seeing this issue in 0.4.1 - which commit was this fixed in? The issue seems related to the number of nav-items being pulled left or more specifically the combined length of text in the nav-left labels.

**Comment by rbluethl** [comment]
I'm also seeing this issue with 0.4.2. Any updates?
