### ISSUE TITLE
Bug: navbar hamburger menu dropdown is behind secondary tab menu

### ISSUE THREAD

**Issue by C14L** [jgthms/bulma#65]
Just noticed this bug on Bulma.io when switching to narrow screen, the dropdown of the right side hamburger menu is rendered *behind* the secondary tab menu. Expected: it should cover any other element.

Screenshots: On the second image, I extended the length of the menu to see what the problem is.

http://imgur.com/a/DJND7

**Comment by jgthms** [comment]
This has been fixed.

**Comment by Grelek** [comment]
Hi, I use Bulma 0.1.2 and Chromium 52.0.2743.116 (64-bit) and I experience the exact same issue.

First screen:
![1](https://cloud.githubusercontent.com/assets/2447438/17817815/c5aa0222-6640-11e6-8659-45cf3578531d.png)

Second screen:
![2](https://cloud.githubusercontent.com/assets/2447438/17817816/c5c4726a-6640-11e6-89fc-c5c3796e16f6.png)
