### ISSUE TITLE
"missing label sizes" AKA avoid publishing live documentation

### ISSUE THREAD

**Issue by igorsantos07** [jgthms/bulma#654]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** 0.4.0

### Description
I was creating a small, side-column form, and tried to use `.field-label.is-small` just like the docs tell me so. But after some fidding with yarn and some git blames I noticed the documentation is about something not yet released :(

### Questions
1. Does it make sense to release documentation on the main site about something only available in `master`? That causes confusion, to say the least.
2. Would that "new" tag mean "not yet released"? To me, that means "something you may have not seen since the last time you visited this page". If the first, please change it to something more obvious (like "new in beta")
3. What about adding even more specific tags to such cases, such as "since 0.4.1"?

**Comment by jgthms** [comment]
That's a good shout.

Problem is that I can't release after every bugfix. And when I push a bugfix to `master`, it includes both the _code_ and the _documentation_. So the code ends up on Github, but not on npm or bower. And the documentation is published.

I believe I'm gonna create a `release/0.4.1` branch which will be the default on Github. But the documentation will only be published from `master`. When `release/0.4.1` is ready, I'll merge to `master`, and the docs will be live.

**Comment by igorsantos07** [comment]
Sounds doable!

Another idea, if you want to leave master as main branch, is to tag
versions on the doc, so we know if that has landed on our current version
or not.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by jgthms** [comment]
I'll start doing that for `0.4.2`
