### ISSUE TITLE
Bottom of Select element text gets cut off

### ISSUE THREAD

**Issue by mirshko** [jgthms/bulma#657]
### Overview of the problem

<img width="647" alt="screenshot 2017-04-09 15 48 35" src="https://cloud.githubusercontent.com/assets/8116716/24840499/196303d4-1d3c-11e7-9211-92645ce5879f.png">

- This is about the Bulma **CSS framework**
- I'm using Bulma **version** 0.4.0
- My **browser** is: macOS 10.12.4 (16E195) - Chrome Version 57.0.2987.110 (64-bit)

### Description

The bottom of select elements inside of the Bulma framework has its inside text cut off. This is present both in the docs and on my own site.

### Steps to Reproduce

1. Go to http://bulma.io/documentation/elements/form/
2. Scroll down to section on full-width select dropdowns
3. Look closely at bottom of Argentina's g. It is cut off

### Expected behavior

This should not be cut off.

### Actual behavior

The bottom of the g is cut off.

**Comment by jgthms** [comment]
Dupe.

**Comment by mirshko** [comment]
@jgthms Dupe of what issue? I can't find it.
