### ISSUE TITLE
is-mobile fails in chrome extension with .min.css from CDN

### ISSUE THREAD

**Issue by kasbah** [jgthms/bulma#66]
Switching to the min css on the CDN causes the `is-mobile` class to fail in the popup of this chrome extension i set up as a test

https://github.com/kasbah/bulma-chrome-test/commit/25599ee6556d9887d08a1989070eeae6d97cb344

![](https://i.imgur.com/yI1S9DP.png)

**Comment by kasbah** [comment]
Viewing the popup.html in a browser actually displays the same issue.

**Comment by jgthms** [comment]
I have no real control over the CDN, and not much over the minified version either.
Use the main css I guess?

**Comment by kasbah** [comment]
Sure thing, I will switch to the npm version anyway if I decide to stick with it after my experiments. Just reporting in case you did have control and it was an oversight, or if other people run into the same issue.
