### ISSUE TITLE
Intergrate Font Awesome 5 when released

### ISSUE THREAD

**Issue by SomethingNew71** [jgthms/bulma#662]
### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Font Awesome 5 **Font Icons**

### Description

Please integrate Font Awesome 5 into the framework when they release it.

**Comment by jgthms** [comment]
It's not out yet.

**Comment by SomethingNew71** [comment]
Sorry thought it could be tracked as a feature request.  Do you have plans to integrate it when it comes out?

**Comment by mbarwick83** [comment]
There's 100,000+ people using FA 5, myself included. Not compatible with Bulma in the slightest. Can't use `span.icon`. Also have t fix alignment issues (for some reason Bulma uses `vertical-align: top` a lot, when most use `middle` for properly alignment.). Def something you're going to want to scoop I think. Beta up! :)

**Comment by jgthms** [comment]
You're right @mbarwick83. I need to get a hold of FA 5. I'm gonna reopen this.

**Comment by chrislentz** [comment]
Font Awesome 5 was released today.

**Comment by stevensacks** [comment]
Font Awesome 5 is incompatible right now because Bulma references `.fa` at many places, but the new FontAwesome removes `.fa` when they replace the icon.

I think that's their issue to fix, though.

**Comment by mbarwick83** [comment]
@stevesacks nah man. Not too difficult at all. It’s more of an alignment issue. I did it now using vertical-align with a few lines of css.

**Comment by janva255** [comment]
+1

**Comment by jgthms** [comment]
Font Awesome already works with Bulma, since it works with any icon font.

I've updated the documentation: https://bulma.io/documentation/elements/icon/

Only Font Awesome 5 is present on the website now!
