### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by 0x263b** [jgthms/bulma#663]
### Description

Running `npm run build` does not work on Windows due to not being able to execute `"build-clean": "rm -rf css"`. (It would need to be `rmdir css`) And making a Windows specific script is [not an option](https://github.com/npm/npm/issues/2006).

### Steps to Reproduce

`npm run build` in Windows

### Expected behavior

Generates `css/bulma.css`

### Actual behavior

```
> bulma@0.4.0 build-clean D:\Code\bulma-0.4.0
> rm -rf css

'rm' is not recognized as an internal or external command,
operable program or batch file.
```

### Possible solution

As far as I can tell it's unnecessary to delete the `css` directory before hand. Removing `npm run build-clean` from the `build` script fixes the issue.

**Comment by jgthms** [comment]
Try the master branch. It uses rimraf now.
