### ISSUE TITLE
"button is-link" with icon underlines the icon

### ISSUE THREAD

**Issue by jmfederico** [jgthms/bulma#664]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.0]
I am sure this issue is **not a duplicate**?

### Description

Since commit [6ac14c3](https://github.com/jgthms/bulma/commit/6ac14c316fce12319b4fa20b7e0b522fa44c819e#diff-e2deac9dccc4a485fe137283757fe585) where `.icon` was given a `display: inline-flex` property, links with `button is-link` classes and an icon inside them get the icon underlined.

### Steps to Reproduce

Use this markup:
```html
  <a class="button is-link">
    <span class="icon is-small">
      <i class="fa fa-github"></i>
    </span>
    <span>GitHub</span>
  </a>
```

### Expected behavior

No undeline on the icon

### Actual behavior

<img width="110" alt="screen shot 2017-04-10 at 19 02 43" src="https://cloud.githubusercontent.com/assets/237977/24887295/4db2f308-1e20-11e7-80cb-633f6514a94a.png">

**Comment by jgthms** [comment]
It's tricky because `text-decoration: none` doesn't do anything on `.icon`. I can't find an easy solution.

**Comment by jmfederico** [comment]
Adding `display: inline-block;` seems to work:

````css
.fa::before {
  display: inline-block;
}
````
