### ISSUE TITLE
Bulma in wordpress themes

### ISSUE THREAD

**Issue by saqibrauf** [jgthms/bulma#665]
I am a big fan of BULMA and is using it in my themes.

You are using a class named ".tag" in (sass/elements/tag.sass) which is causing problem when we need to generate WORDPRESS TAG ARCHIVE.

kindly replace .tag class to something like .tags or any name you like.

Thanks

**Comment by jgthms** [comment]
You can import only the files you need, and not include tags.sass if you want.

**Comment by Log1x** [comment]
https://github.com/jgthms/bulma/blob/master/sass/elements/tag.sass#L41

I fixed this a few months ago.
