### ISSUE TITLE
Mobile version isn't showed on mobile, only with console

### ISSUE THREAD

**Issue by SacredArrow** [jgthms/bulma#667]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

So I tried to make a navbar for mobile, but it isn't working at all. I open Chrome console(F12), and if i choose "mobile" version, it shows desktop version. If I choose "desktop" it shows mobile version. When I close F12, I see normal(the one, that is "mobile", but actually is for the desktop. When I open site on mobile phone, I see the same, like on desktop. I even tried to copy an example from the documentation, but it also works that way - shows a desktop version, and shows mobile version only when I choose "desktop" in F12 device view. But on Bulma's site it works fine, when I turn device view to "mobile" in F12.

**Comment by jgthms** [comment]
This is very confusing. Gonna need some code and screenshots.

**Comment by SacredArrow** [comment]
@jgthms Okay, I'm going to show it with example from site.
This is what the code looks like(I'm not very good at posting code or screenshots, and github's tools don't work fine, so i'm going to use pastebin): https://pastebin.com/B0ENDBhP
So now I'm running it and this is what I get: ![ScreenShot](http://i66.tinypic.com/30cqa7p.jpg)
Opening F12: ![ScreenShot](http://i66.tinypic.com/2ngttep.png)
Changing to device view: ![ScreenShot](http://i68.tinypic.com/2w3ng1z.png)
Changening to desktop: ![ScreenShot](http://i64.tinypic.com/29dcwn7.png)

**Comment by jgthms** [comment]
It's not valid HTML5. Read this first: http://marksheet.io/html-valid-document.html

**Comment by SacredArrow** [comment]
@jgthms But I have this HTML markup, just in other file, index.html
I'm using Vue components, that's why this file only includes template, not all the html.
It's seen on screenshots 2-4.
