### ISSUE TITLE
Unacceptable

### ISSUE THREAD

**Issue by rhazor** [jgthms/bulma#668]
![asd](https://cloud.githubusercontent.com/assets/22996586/24925959/a66cdd6e-1f02-11e7-9bef-cee480cf4775.png)

**Comment by mightyiam** [comment]
I have never seen a comment like this in open source and I hope I never will again. Sorry, @jgthms. I'd close it for you if I could.

**Comment by rhazor** [comment]
it's a meme you pleb. My point was that it's unaligned 2px on top, while equal at the bottom. Jesus Christ you must be sad at parties.

**Comment by mightyiam** [comment]
I don't go out much.
