### ISSUE TITLE
Meteor can't import sass files.

### ISSUE THREAD

**Issue by ediopia** [jgthms/bulma#669]
### Overview of the problem

Meteor can not import sass syntax

### Description

I currently use meteor and[ fourseven/meteor-scss](https://github.com/fourseven/meteor-scss).

I had to use bulma-scss or bulma_scss because meteor can not import sass syntax.

(issue is hear https://github.com/fourseven/meteor-scss/issues/120)

I want to use the latest version of bulma but the version of scss packages are too old.

I do not think it is only my issue because fourseven/meteor-scss package is the most known package for sass for meteor.

Can you provide scss files or is there any way I can solve this problem?

**Comment by jgthms** [comment]
Bulma will always remain in `.sass`, which should work with https://github.com/fourseven/meteor-scss

Alternatively, you can use `sass-convert` in your CLI.

**Comment by ediopia** [comment]
Sadly  https://github.com/fourseven/meteor-scss package which is the main sass compiler for meteor, does not support sass indented syntax. That is why people have been making scss versions. like bulma-scss. Those packages can not cover current bugs.
