### ISSUE TITLE
input type="range"

### ISSUE THREAD

**Issue by benjick** [jgthms/bulma#67]
Is this planned for 1.0? Do you have any roadmap to read?

Cheers

**Comment by jgthms** [comment]
Is it possible to style it?

**Comment by gignar** [comment]
Ana Tudor has a pretty cool collection of range input styles [on Codepen](http://codepen.io/collection/DgYaMj/), if that helps.

**Comment by julisse** [comment]
Yes, would be great to style range, used own styling [here](http://imagec1s.bget.ru/new/9.html)

**Comment by jgthms** [comment]
Very nice @gignar. I'll probably implement something like @julisse, just very simple.

**Comment by Swizz** [comment]
@julisse [Those](http://codepen.io/thebabydino/pen/RNEEZP) are particularly awesome

**Comment by djyde** [comment]
Any progression for this issue?

**Comment by acidjazz** [comment]
would love to see this under form options as well!

**Comment by Acidic9** [comment]
+1 for this, it's a missing feature from Bulma

**Comment by acidjazz** [comment]
I'm working on a version I think would fit the bulma framework, would you like a PR @jgthms ?

**Comment by Swizz** [comment]
Would love to see any screenshot, to raise the hype !

**Comment by acidjazz** [comment]
![image](https://cloud.githubusercontent.com/assets/967369/24780716/705aa386-1aee-11e7-9d52-cb8d66d49a0c.png)

![image](https://cloud.githubusercontent.com/assets/967369/24780718/7799a3fe-1aee-11e7-8060-ce9c033ebb78.png)

**Comment by acidjazz** [comment]
![image](https://cloud.githubusercontent.com/assets/967369/24785355/0ae26604-1b0e-11e7-80f3-bd682bf527b7.png)

**Comment by acidjazz** [comment]
@Swizz @jgthms hows this?
![image](https://cloud.githubusercontent.com/assets/967369/24785359/16cd97d6-1b0e-11e7-9b03-9d9d0695f8a5.png)

**Comment by Acidic9** [comment]
I really like that @acidjazz. What if you put a white fill in the circle (leaving a border around the edge)?

**Comment by acidjazz** [comment]
@Acidic9 something like this?
![image](https://cloud.githubusercontent.com/assets/967369/24786052/5cbd6f00-1b13-11e7-9c20-fc28ce72a952.png)

**Comment by Acidic9** [comment]
@acidjazz the shadow around the circle, the colors and everything looks perfect like that in my opinion. Really hope this gets added really soon.

**Comment by acidjazz** [comment]
![image](https://cloud.githubusercontent.com/assets/967369/24786149/ff1319b2-1b13-11e7-8a3f-7adf80d7426b.png)

There is only one downside so far, I cannot through CSS alone control which the progress on the left , so without that it looks like this (for now)

**Comment by acidjazz** [comment]
`is-small` `is-medium` `is-large`

![image](https://cloud.githubusercontent.com/assets/967369/24786480/aa31b07c-1b16-11e7-8ac6-5d95b9fef90e.png)

**Comment by Acidic9** [comment]
Damn, Bulma is a CSS only framework which is one of it's features. Maybe in the documentation it can just show the javascript code you can use to get sliders to work.

**Comment by acidjazz** [comment]
![image](https://cloud.githubusercontent.com/assets/967369/24786619/c2f442a4-1b17-11e7-8548-cef249867cfc.png)
@Acidic9 yes I can provide some sample JS

**Comment by acidjazz** [comment]
@jgthms is there anything else you'd like for this PR?

**Comment by michaelReyder** [comment]
@acidjazz This range input looks great. I'm wondering when this PR will be submitted for a merge? In the meanwhile, is there any ways your could provide the css you created?

**Comment by acidjazz** [comment]
@michaelReyder unfortunately he denied the PR https://github.com/jgthms/bulma/pull/647 . i've since then pinged him multiple times about it on Gitter and other areas with no response.

When I get some time later this week I'll try and whip this up as an add-on of some sort.

**Comment by ruchern** [comment]
How is the progression of this?
