### ISSUE TITLE
[Help] Button question

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#672]
It is possible to set an available button that would not be hoverable and won't be a link?

**Comment by jgthms** [comment]
Just use a `<span>`.

**Comment by tu5** [comment]
@jgthms Trying with something like this, but button is still clickable and hoverable.
```
<span class="button is-small">
    <span class="icon is-small">
      <i class="fa fa-paypal"></i>
    </span>
    <span>PayPal</span>
  </span>
```
