### ISSUE TITLE
Button in card footer

### ISSUE THREAD

**Issue by KKSzymanowski** [jgthms/bulma#673]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.3.2
My **browser** is: Google Chrome 57.0.2987.133
I am **pretty** sure this issue is **not a duplicate**.

### Description

I want to create a login form in a card component and everything is fine if my footer is like this:
```html
<footer class="card-footer">
    <a class="card-footer-item" @click="login">Zaloguj</a>
</footer>
```
![image](https://cloud.githubusercontent.com/assets/13980973/25000524/ed4b6ada-2041-11e7-868f-803d608c0f4b.png)
However users could not login by hitting `enter` in any of the text inputs, so I thought I'll wrap the form in a `<form @submit.prevent="login">` tag(I'm using VueJs). This changed nothing because the form did not have a `submit` button.
If I change the link in the footer to a submit button it has the default browser look:
```html
<footer class="card-footer">
    <button type="submit" class="card-footer-item">Zaloguj</button>
</footer>
```
![image](https://cloud.githubusercontent.com/assets/13980973/25000624/5230c67a-2042-11e7-9c4d-4c7a0047640a.png)

### Steps to Reproduce

[See JSFiddle](https://jsfiddle.net/7rxyw6nj/)

### Expected behavior

Button still looks like in the first screenshot.

### Actual behavior

Button doesn't look like in the first screenshot at all.

### Possible fix

If I reset the button styling:
```scss
button.card-footer-item {
  background-color: transparent;
  cursor: pointer;
  color: $link;
  border: 0;
  font-size: 1rem;
  line-height: 1.5;
}
```
it looks exactly like in the first screenshot.

**Comment by jgthms** [comment]
You can include the `appearance: none` styles: https://github.com/jgthms/bulma/blob/master/sass/utilities/controls.sass#L8

**Comment by KKSzymanowski** [comment]
I'm sorry, but I'm not sure I understand.
If I add `style="-webkit-appearance: none"` to the button, it looks like this:
![image](https://cloud.githubusercontent.com/assets/13980973/25001693/f891a260-2046-11e7-8a28-7e1231dd2d8a.png)
If I include the `control` mixin
```scss
button.card-footer-item {
  @include control();
}
```
it looks like this:
![image](https://cloud.githubusercontent.com/assets/13980973/25001783/5e483d58-2047-11e7-9bf4-4c74bff1e929.png)

Could you please elaborate on how should I proceed?

**Comment by AhmedMKamal** [comment]
https://github.com/jgthms/bulma/pull/1637#issuecomment-558281747
