### ISSUE TITLE
Bulma icon align bug with line-height

### ISSUE THREAD

**Issue by darkylmnx** [jgthms/bulma#674]
### Overview of the problem

This is about the Bulma **CSS framework**
My **browser** is: lastest chrome

### Description

When i use icons, it seems to always be at the top, while this doesn't cause any problem most of the time, i think it should just have it's initial vertical-align because, for exemple, when i use a line-height on the parent, the icon isn't affected, while... it should be, as the icon is part of the "text"

http://bulma.io/documentation/elements/icon/

### Expected behavior
https://jsfiddle.net/uf3k5z44/1/

### Actual behavior
https://jsfiddle.net/uf3k5z44

**Comment by jgthms** [comment]
Yeah it's the `vertical-align: top`. Gotta remove that.

**Comment by jgthms** [comment]
Oh wait, it's been fixed in 0.4.1 (soon to be published).
