### ISSUE TITLE
Fullscreen vertical centering is broken in IE

### ISSUE THREAD

**Issue by YazeedAlsaif** [jgthms/bulma#68]
Hello

I just noticed that the fullscreen vertical centring is broken in IE.

From Bluma.io:
![capture](https://cloud.githubusercontent.com/assets/3579831/12959626/57b8636e-d048-11e5-9038-e75832734b63.PNG)

Thanks

**Comment by artyomtrityak** [comment]
@YazeedAlsaif IE version? Flexbox does not work in IE < 10

**Comment by jgthms** [comment]
I need to add autoprefixer as well.

**Comment by artyomtrityak** [comment]
@jgthms i can do this, is it okay if i would add gulp build?

**Comment by jgthms** [comment]
Haha no gulp please =)

@YazeedAlsaif I just added autoprefixer. Can you try again?

**Comment by jgthms** [comment]
Should be fixed.
