### ISSUE TITLE
[Bug] Hero in-primary text color

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#680]
Font color of the box is wrong while hero is-primary.
Bulma: 0.4.0

```
  <section class="hero is-fullheight is-primary is-bold">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-vcentered">
          <div class="column is-4 is-offset-4">
            <div class="box">
             I'm white
             <p>I'm white too</p>
            </div>
            <p class="has-text-centered">
              <a href="#">I'm barly visible</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
```

**Comment by AlgusDark** [comment]
This is still happening in `0.4.1`. The colors affected are:

`.is-dark` `.is-black` `.is-primary` `.is-info` `is-success` `.is-danger`

A proposed solution could be add `color: #0a0a0a;` to `.box` or write rules like:
```css
.hero.is-black .box {
    color: #0a0a0a;
}
```

for the 5 color modifiers.

**Comment by sean-lynch** [comment]
Appears to still be in an issue as of v0.7.1 (at least in the hero->navbar->dropdown case)

**Comment by Sharparam** [comment]
Still an issue in v0.7.5 for the hero -> navbar -> dropdown case. Can this be re-opened?
