### ISSUE TITLE
[Docs] Modal - example javascript toggle

### ISSUE THREAD

**Issue by ghost** [jgthms/bulma#683]
It's about docs -> http://bulma.io/documentation/components/modal/
I think that it should contain example javascript toggle.

**Comment by AntonyGarand** [comment]
`Bulma does not include any JavaScript interaction. You will have to implement the class toggle yourself`

As bulma does not include js, I believe adding javascript code to the docs would be more confusing than helping.

**Comment by tu5** [comment]
I think that it is already confusing when framework calls itself "without javascript" but includes elements that won't work without javascript!

**Comment by AntonyGarand** [comment]
It does work without javascript, but it is static: You can add the is-active class at load time and the modal window will indeed work.

**Comment by airblade** [comment]
It's easy enough to toggle the `is-active` class on the modal div.

But – and I only found this out after reading the source of the JavaScript bundle on the docs site – you also need to toggle the `is-clipped` class on the `<html>` element to stop the page underneath scrolling when you try to scroll in the modal.

It would be great to add that to the docs.

**Comment by iamromanh** [comment]
@airblade Do you mind providing a code sample? I am actually trying to accomplish the same thing you and other are explaining. Having a little trouble.

**Comment by airblade** [comment]
@iamromanh Assuming you have a link which opens your modal, e.g.:

```html
<a id="open-modal" href="">Open modal</a>
```

This ES5 JavaScript (or similar, I just typed it out without testing) should open it:

```js
document.querySelector('a#open-modal').addEventListener('click', function(event) {
  event.preventDefault();
  var modal = document.querySelector('.modal');  // assuming you have only 1
  var html = document.querySelector('html');
  modal.classList.add('is-active');
  html.classList.add('is-clipped');

  modal.querySelector('.modal-background').addEventListener('click', function(e) {
    e.preventDefault();
    modal.classList.remove('is-active');
    html.classList.remove('is-clipped');
  });
});

**Comment by nqthqn** [comment]
I really appreciate the design decision to keep this a javascript-free framework.

Here's how you might toggle classes in [Elm](http://elm-lang.org/),

In the **View**...
```
navToggler : Bool -> Html Msg
navToggler activeMenu =
    span
        [ class <| "nav-toggle" ++ (isActive activeMenu), onClick MainMenuToggle ]
        [ span [] []
        , span [] []
        , span [] []
        ]

isActive : Bool -> String
isActive active =
    if active then
        " is-active"
    else
        ""
```

And then in the **Update**...
```
MainMenuToggle ->
    ( { model | isMenuActive = not model.isMenuActive }, Cmd.none )
```

**Comment by mclassdesigns** [comment]
Does anyone know how to toggle the is-clipped class in vue.js? Any help would be appreciated!

**Comment by raman162** [comment]
My Implmentation using html5 data-attributes and jquery.

Html
`
<a class="open-modal" data-modal-id="#my-modal">Open My Modal</a>

```
<div aria-hidden="" class="modal" id="my-modal">
  <div class="modal-background close-modal" data-modal-id="#my-modal"></div>
  <div class="modal-content">

   </div>
   <button aria-label="close" class="delete close-modal" data-modal-id="#my-modal"></button>
</div>
```

Javascript
```
function toggleModalClasses(event) {
    var modalId = event.currentTarget.dataset.modalId;
    var modal = $(modalId);
    modal.toggleClass('is-active');
    $('html').toggleClass('is-clipped');
  };

  $('.open-modal').click(toggleModalClasses);

  $('.close-modal').click(toggleModalClasses);
```

**Comment by Ickorus** [comment]
**Also, In looking for the same thing you were. I found this:**
[1st Page on Google Search](
https://siongui.github.io/2018/02/11/bulma-modal-with-javascript/)

**Comment by jeturcotte** [comment]
re: @aligoren ... nice!  and on my birthday, too.  A great present =)

**Comment by GuyDoodlesDev** [comment]
The navbar page in the documentation has a JavaScript example, why can't this? I don't want to spend my time learning JavaScript (I already know how, but as an example) just to get a modal working! What if I'm just building a simple single-page blog, and don't know any JS?

**Comment by IlanVivanco** [comment]
Based on @aligoren's script I changed it to automount every modal instance.

`index.html`
```html
<button class="modal-button" data-toggle="modal" data-target="#video">Open modal</button>

<div class="modal" id="video">
  <div class="modal-background"></div>
  <div class="modal-content">
    Lorem ipsum dolor sit amet
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>
```
`BulmaModal.js`
```js
class BulmaModal {
  constructor(modalButton) {
    const target = modalButton.dataset.target;
    
    if (target) {
      this.button = modalButton;
      this.modal = document.querySelector(target);
      this.html = document.querySelector("html");
      
      this.openEvent();
      this.closeEvents();
    }
  }
  
  show() {
    this.modal.classList.toggle("is-active");
    this.html.classList.add("is-clipped");
    
    this.onShow();
  }
  
  close() {
    this.modal.classList.toggle("is-active");
    this.html.classList.toggle("is-clipped");
    
    this.onClose();
  }
  
  openEvent() {
    this.button.addEventListener("click", (e) => {
      e.preventDefault();
      this.show();
    });
  }
  
  closeEvents() {
    const closeElements = this.modal.querySelectorAll(".modal-background, .modal-close");
    
    closeElements.forEach((element) => {
      element.addEventListener("click", (e) => {
        e.preventDefault();
        this.close();
      });
    });
  }
  
  onShow() {
    const event = new Event("modal:show");
    this.modal.dispatchEvent(event);
  }
  
  onClose() {
    const event = new Event("modal:close");
    this.modal.dispatchEvent(event);
  }
}

export default BulmaModal;
```

`main.js`
```js
import BulmaModal from 'BulmaModal.js'

const modals = document.querySelectorAll("[data-toggle='modal']");
modals.forEach((modal) => new BulmaModal(modal));
```

If needed you can add event too:
`main.js`
```js
document.querySelector(".modal").addEventListener("modal:show", (event) =>{ console.log(event) });
```

**Comment by aligoren** [comment]
> Based on @aligoren's script I changed it to automount every modal instance.
> 
> `index.html`
> 
> ```
> <button class="modal-button" data-toggle="modal" data-target="#video">Open modal</button>
> 
> <div class="modal" id="video">
>   <div class="modal-background"></div>
>   <div class="modal-content">
>     Lorem ipsum dolor sit amet
>   </div>
>   <button class="modal-close is-large" aria-label="close"></button>
> </div>
> ```
> 
> `BulmaModal.js`
> 
> ```js
> class BulmaModal {
>   constructor(modalButton) {
>     const target = modalButton.dataset.target;
>     
>     if (target) {
>       this.button = modalButton;
>       this.modal = document.querySelector(target);
>       this.html = document.querySelector("html");
>       
>       this.openEvent();
>       this.closeEvents();
>     }
>   }
>   
>   show() {
>     this.modal.classList.toggle("is-active");
>     this.html.classList.add("is-clipped");
>     
>     this.onShow();
>   }
>   
>   close() {
>     this.modal.classList.toggle("is-active");
>     this.html.classList.toggle("is-clipped");
>     
>     this.onClose();
>   }
>   
>   openEvent() {
>     this.button.addEventListener("click", (e) => {
>       e.preventDefault();
>       this.show();
>     });
>   }
>   
>   closeEvents() {
>     const closeElements = this.modal.querySelectorAll(".modal-background, .modal-close");
>     
>     closeElements.forEach((element) => {
>       element.addEventListener("click", (e) => {
>         e.preventDefault();
>         this.close();
>       });
>     });
>   }
>   
>   onShow() {
>     const event = new Event("modal:show");
>     this.modal.dispatchEvent(event);
>   }
>   
>   onClose() {
>     const event = new Event("modal:close");
>     this.modal.dispatchEvent(event);
>   }
> }
> 
> export default BulmaModal;
> ```
> 
> `main.js`
> 
> ```js
> import BulmaModal from 'BulmaModal.js'
> 
> const modals = document.querySelectorAll("[data-toggle='modal']");
> modals.forEach((modal) => new BulmaModal(modal));
> ```
> 
> If needed you can add event too:
> `main.js`
> 
> ```js
> document.querySelector(".modal").addEventListener("modal:show", (event) =>{ console.log(event) });
> ```

Almos 3 years ago, I wrote this simple script. It still works and you made it amazing. Thanks <3
