### ISSUE TITLE
.container class doesn't have max-width from since 0.4.0.

### ISSUE THREAD

**Issue by jesprider** [jgthms/bulma#686]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.0]

### Description

Bulma release version 0.4.0 is missing a max-width property for .container:
https://github.com/jgthms/bulma/blob/0.4.0/css/bulma.css#L2753

### Expected behavior

max-width: 960px;

**Comment by jgthms** [comment]
Dupe
