### ISSUE TITLE
v0.4.0 different files when installed with NPM/Yarn

### ISSUE THREAD

**Issue by alexbet** [jgthms/bulma#687]
This is a **Sass** issue: I'm using version [0.4.0] 
I am sure this issue is **not a duplicate**?

### Description

When installing Bulma with NPM or Yarn, it pulls some other version of the SASS files. You can compare for example the 'sass/elements/form.sass' file with the same file that you have on Github. As you will see, the one installed with NPM or Yarn is a smaller and is missing some classes. For example, the ".has-icons-left" class is missing from the NPM/Yarn version of the before mentioned file. I am not sure what happened there, so you may want to check it out. 

### Steps to Reproduce
npm install bulma
yarn add bulma

**Comment by rosswilson252** [comment]
I've just come across the exact same issue. 

As a work around I've just used:

```
yarn add https://github.com/jgthms/bulma.git
```

**Comment by alexbet** [comment]
@rosswilson252 - That is what I did too, but I don't like the solution. I hope this will be fixed.

**Comment by shirohana** [comment]
Bump.

I got some trouble when using `.nav`s and I found there's a lot of differences since `0.4.0` to `master`

When would you publish the next patch of bulma (ノω・。)
