### ISSUE TITLE
has-icons-left Not working when using bootstrap together

### ISSUE THREAD

**Issue by maverickchangithub** [jgthms/bulma#689]
### Overview of the problem
I am trying to use both icons in a input field , but it fails
i am using sass version, customized some part off to avoid conflict with bootstrap

### Description

seems like has-icons-right and has-icons-left not working .
has-icon right is fine.

### Steps to Reproduce

i copy exactly the same code from bulma site.

```html
<div class="field">
  <label class="label">Username</label>
  <p class="control has-icons-left has-icons-right">
    <input class="input is-success" type="text" placeholder="Text input" value="bulma">
    <span class="icon is-small is-left">
      <i class="fa fa-user"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fa fa-check"></i>
    </span>
  </p>
  <p class="help is-success">This username is available</p>
</div>
```

### Expected behavior
it should appear the same on the bulma site

### Actual behavior

the icons are stacked together in the next line outside the input field

**Comment by jgthms** [comment]
It's coming in `0.4.1`. Release is soon. In the meantime, you can fork the repo.
