### ISSUE TITLE
.has-icon-left class is missing

### ISSUE THREAD

**Issue by intermundos** [jgthms/bulma#694]
### Overview of the problem

This is about the Bulma **CSS framework** 

 I'm using Bulma **version** [0.4.0] 

### Description

.has-icon-left class is missing. 

In general, .has-icons does not work properly, all the icons are placed below element i.e. input.

**Comment by MikeRalphson** [comment]
Works ok if you include http://bulma.io/css/bulma-docs.css instead.

**Comment by tu5** [comment]
Has icons does works, though not like described in the documentation. That's sucks but here's an example of my working search box:
```
<div class="field has-addons">
  <p class="control has-icon is-expanded">
    <input class="input is-medium" type="text" name="q" value="{{ query }}">
        <span class="icon is-medium">
      <i class="fa fa-search"></i>
    </span>
  </p>
  <input type="submit" value="Search" class="button is-medium is-primary">
  </p>
</div>
```

**Comment by tu5** [comment]
Nevermind, just download bulma-master from github. Version from NPM is old.

**Comment by intermundos** [comment]
Neither bulma from master, nor npm version has no **.has-icons-***** class. 

bulma-docs.css works fine and has these classes.

**Comment by jjojohjohn** [comment]
will master get fixed?
