### ISSUE TITLE
How to do 'is-fullwidth' on mobile only?

### ISSUE THREAD

**Issue by weavermedia** [jgthms/bulma#695]
### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.4.0]

### Description

I'd like to use `is-fullwidth` on some tabs but only for mobile. There are only 3 small tabs and on desktop `is-fullwidth` spaces them too far apart. On mobile they feel a lot nicer evenly spaced.

So my question is how do I do something like `is-fullwidth-mobile`?

**Comment by jgthms** [comment]
You can put `flex-grow: 1` on `.tabs li` but only on mobile with your own media query.

**Comment by kleberksms** [comment]
@media screen and (max-width: 768px), print {
  .button.is-fullwidth-mobile {
    display: flex;
    width: 100%;
  }
}

**Comment by niclaswue** [comment]
Maybe also try out `is-flex-mobile`. This is the cleanest solution and worked for me. Additional useful helpers can be found [here](https://bulma.io/documentation/helpers/visibility-helpers/) and [here](https://bulma.io/documentation/helpers/flexbox-helpers/).
