### ISSUE TITLE
Edit Suggestions : Enhancements

### ISSUE THREAD

**Issue by melriksdesign** [jgthms/bulma#699]
- This is about the Bulma **CSS framework**
-  I'm using Bulma **version** [0.4.0]
- My **browser** is: primarily FireFox for dev work.

### Description

I'm integrating Bulma into my WordPress theme (replacing Get Skeleton 2.0) and thought I'd use this area to record odds and ends that I bump into.

Default Styles --------------------------

menu and nav have a background-color set on them (white).  My menu and nav were on a blue background.  

Helpers -------------------------------

I didn't see a way to vertically align the contents of a column so I built some helper classes to be used like .has-text-centered.

.is-valigned-top { display:flex; flex-direction: column; justify-content: flex-start; overflow:auto;  }
.is-valigned-center { display:flex; flex-direction: column; justify-content: center; overflow:auto;  }
.is-valigned-bottom { display:flex; flex-direction: column; justify-content: flex-end; overflow:auto; }

**Comment by jgthms** [comment]
That can be helpful. But it can also break quite a few things, since `flex-direction: column` can be tricky.

Anyway, you could build an extension and link it in the Readme.
