### ISSUE TITLE
Add ability to use different number of columns on different breakpoints

### ISSUE THREAD

**Issue by daralthus** [jgthms/bulma#7]
Similarly to `col-sm-4` vs. `col-xl-4` in bootstrap.

**Comment by jgthms** [comment]
Yes, this is somewhat planned. Not sure how though.

**Comment by eko24** [comment]
@jgthms you can take a look at bootsrap source files regarding this feature:
[Scaffold gird by 'make-grid' method](https://github.com/twbs/bootstrap/blob/master/less/grid.less)
[itself 'make-grid' method](https://github.com/twbs/bootstrap/blob/master/less/mixins/grid-framework.less)

**Comment by darol100** [comment]
Here is a grid system base on Flexbox http://flexboxgrid.com/. Something that we might be able to integrate into into this framework or do something similar.

**Comment by ivanistheone** [comment]
For reference, http://flexboxgrid.com/ uses the syntax `col-[xs|sm|md|lg]-nn` where nn is out of 12. 

    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4"> ... 

This feels comfortable coming from bootstrap so +1 for implementing similar API.

**Comment by PhillippOhlandt** [comment]
I am for something like

`<div class="column is-6-mobile is-2-tablet is-2-desktop"></div>`

It fits better into the naming conventions of bulma.

**Comment by nathanjessen** [comment]
I don't really like the idea of saying flex: none on every instance of a column modifier but here is a good example of the mixin. The you just say `+make-grid` at the top of grid.sass below the initial .column styles
`
=make-grid
  .column
    @for $i from 1 through 11
      &.is-#{$i}
        flex: none
        width: ($i / 12) * 100%
    +tablet
      @for $i from 1 through 11
        &.is-#{$i}-tablet
          flex: none
          width: ($i / 12) * 100%
    +desktop
      @for $i from 1 through 11
        &.is-#{$i}-desktop
          flex: none
          width: ($i / 12) * 100%
`

**Comment by nathanjessen** [comment]
Here is a sample mixin. Just use the mixin under .column in grid.sass

```
=make-grid
  @for $i from 1 through 11
    &.is-#{$i}
      flex: none
      width: ($i / 12) * 100%
  +tablet
    @for $i from 1 through 11
      &.is-#{$i}-tablet
        flex: none
        width: ($i / 12) * 100%
  +desktop
    @for $i from 1 through 11
      &.is-#{$i}-desktop
        flex: none
        width: ($i / 12) * 100%
```

```
.column
  +make-grid
```

**Comment by PhillippOhlandt** [comment]
Disabling flexbox on a flexbox grid is not a good solution IMO.

**Comment by JustSteveKing** [comment]
+1 @PhillippOhlandt - the reason people are looking at Bulma is because of the Flexbox capabilities. Removing this we may as well give up and go back to Bootstrap ...

**Comment by nathanjessen** [comment]
@PhillippOhlandt that should be opened as a separate issue. Doesn't directly relate to adding responsive column classes. In my example, my mixin takes preexisting code to create responsive classes. But yes, I agree we shouldn't be setting flex: none; for the same reason plus it creates a lot of unnecessary output

**Comment by jgthms** [comment]
This has been implemented: http://bulma.io/documentation/grid/

**Comment by PhillippOhlandt** [comment]
@jgthms The solution with `half` `third` `quarter` isn't very flexible because you can't use the 12 column grid.

**Comment by psi-4ward** [comment]
Solution is not flexible enough. Or how can i switch from 3-3-3-3 to 4-4-4 and then to 6-6 on defined breakpoints?

**Comment by nathanjessen** [comment]
@psi-4ward Did you look at the "Different sizes per breakpoint" section? I think you would want columns defined as `<div class="column is-half-mobile is-one-third-tablet is-one-quarter-desktop">`

**Comment by wing5wong** [comment]
Room for improvement here.
not possible to implement, for example, 
for desktop
```<div class="column is-7"></div><div class="column is-5"></div>```
for tablet
```<div class="column is-9"></div><div class="column is-3"></div>```

**Comment by wing5wong** [comment]
this solution misses some required column configurations.
How can we have, say a grid of 2/12 columns (one-sixth)
```<div class="is-half-mobile is-one-third-tablet is-one-sixth-desktop column">1</div>```

**Comment by frederikhors** [comment]
@wing5wong, @psi-4ward Any news on this? @jgthms, can we have a `is-one-sixth-`? Does it make sense?

**Comment by ibnuh** [comment]
> @wing5wong, @psi-4ward Any news on this? @jgthms, can we have a `is-one-sixth-`? Does it make sense?

You can use `is-1-mobile` ... `is-12-mobile`

https://bulma.io/documentation/columns/sizes/#12-columns-system
