### ISSUE TITLE
The horizontal form docs differ from sample

### ISSUE THREAD

**Issue by roosmaa** [jgthms/bulma#701]
### Overview of the problem

This is about the Bulma **Docs**

### Description

The text for the horizontal form seem to widely differ from the working example afterwards.

<img width="724" alt="screenshot 2017-04-24 10 36 30" src="https://cloud.githubusercontent.com/assets/65596/25328935/f887180e-28d9-11e7-8fc1-00b74a5b6fab.png">

The `is-horizontal` class only applies as a modified for the `field` container. The `control-label` doesn't exist, `field-label` is the one that exists.

**Comment by AlgusDark** [comment]
@roosmaa this was Fixed today by  #767

**Comment by jgthms** [comment]
Indeed.
