### ISSUE TITLE
Styles for date/time picker?

### ISSUE THREAD

**Issue by KaRkY** [jgthms/bulma#703]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Would it be posible to add styles for date picker? It would be nice to have styles for Year, Month and Time pickers too.

Something similar to [this](https://jsfiddle.net/qyfoxh7d/1/)

P.S. I know this is CSS only framework so I don't expect the dynamic functionality I would like to have similar support for this as it is for Modals.

**Comment by jgthms** [comment]
I believe it's a too specific UI component to be part of a framework. But it could exist as an extension to Bulma, and be linked to in the Readme.
