### ISSUE TITLE
node-sass v4 compat

### ISSUE THREAD

**Issue by jeffijoe** [jgthms/bulma#704]
### Overview of the problem

This is about the Bulma **CSS framework**

This is a **Sass** issue: I'm using version [4.x.x]
I am sure this issue is **not a duplicate**

### Description

Compiling with `node-sass` 4.x in compressed-output mode results in `.is-#fff` modifiers because you are not using quotes in the `$colors`  map.

### Steps to Reproduce

1. Build Bulma with node-sass 4 in compressed-output mode
2. grep for `is-#`

### Expected behavior

Output to be `.is-white`

### Actual behavior

Output is `.is-#fff`

See https://github.com/sass/node-sass/issues/1654 for details.

**Comment by jgthms** [comment]
They are using quotes now: https://github.com/jgthms/bulma/blob/master/sass/utilities/derived-variables.sass#L78
