### ISSUE TITLE
Inverted primary color not updating

### ISSUE THREAD

**Issue by rafaelpimpa** [jgthms/bulma#706]
First I want to thank you for the great framework! Love to use Bulma and I'm currently using it as a base for my [Vuejs library](https://github.com/rafaelpimpa/buefy).

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.1]
I am sure this issue is **not a duplicate**

### Description

When customizing Bulma following the docs, if you change primary color for a light one (like ``#efecf4``), the inverted color will not update to black.

Shouldn't [these variables](https://github.com/jgthms/bulma/blob/master/sass/utilities/derived-variables.sass#L21) be like this (?):

```sass
$primary-invert: findColorInvert($primary) !default
$info-invert: findColorInvert($info) !default
$success-invert: findColorInvert($success) !default
$warning-invert: findColorInvert($warning) !default
$danger-invert: findColorInvert($danger) !default
```

Right now we have to import the entire ``bulma/sass/utilities/_all``, get the inverted colors and put inside the ``$colors`` list.

### Steps to Reproduce

```sass
@import "../sass/utilities/initial-variables"
$primary: #efecf4
@import "../bulma"
```

### Expected behavior

![](http://imgur.com/0yPXoNZ.png)

### Actual behavior

![](http://imgur.com/hzURDaj.png)

**Comment by herrmannplatz** [comment]
Run into the same issue. Definitely agree with @rafaelpimpa that the inverted color should be derived from the actual primary color and not from the default. 

@rafaelpimpa would you like to create a PR? Otherwise a can do it.

And yeah great framework 🙌

**Comment by rafaelpimpa** [comment]
Go ahead :)

**Comment by balalaXD** [comment]
set `$turquoise: #efecf4` will work.
