### ISSUE TITLE
elements.sass: border-radius on line 15.

### ISSUE THREAD

**Issue by gabsprates** [jgthms/bulma#71]
In [elements.sass](https://github.com/jgthms/bulma/blob/master/bulma/elements/elements.sass), line 15, you use "border-radius: 290486px".
Why?
Can replace for "100%", no?

**Comment by jgthms** [comment]
100% only works when height and width are equal.
The trick is to use pixels with a very huge amount.
Because it can be anything, I just use my birth date.

**Comment by gabsprates** [comment]
hehe nice.
