### ISSUE TITLE
Columns `.is-multiline` not taking 100% width of parent

### ISSUE THREAD

**Issue by Jak893** [jgthms/bulma#717]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.1]
My **browser** is: Chrome

I am sure this issue is **not a duplicate**? Yes

### Description

When a `.columns` container has the additional class of `.is-multiline` it does not fill 100% of the parent container.

### Steps to Reproduce

1. Create a containing element, in my instance I am using an `article` with the `.message` classes applied
2. Add a child div with `.columns .is-multiline` classes
3. Add child columns with specified spacing i.e. `.column .is-3`

![is-multiline-html](https://cloud.githubusercontent.com/assets/664193/25447129/f4d86ba8-2aab-11e7-998d-3cd766254e9a.PNG)

### Expected behavior

Div with `.is-multiline` would fill 100% of the parent container. I have been able to achieve this by adding `flex-grow: 1` on the div and it doesn't seem to have any adverse effect on the column wrapping or responsiveness of the layout.

![is-multiline-flex-grow](https://cloud.githubusercontent.com/assets/664193/25447286/7bfc4e1a-2aac-11e7-9991-3ef11738ff46.png)

### Actual behavior

The div only seems to take up a certain amount of the parent element.

![is-multiline](https://cloud.githubusercontent.com/assets/664193/25446987/44f1a5a6-2aab-11e7-9b02-18a5ba6fdff4.png)

**Comment by Jak893** [comment]
Forgot to add, the second, larger box in the two screenshots acts as intended, whereby it takes up 100% width of the parent element, it is only the first box where this issue occurs

**Comment by sempixel** [comment]
Similar behaviour here. Bulma v0.6.2

Two-or-more vs One

```
<div class="columns is-multiline">
  <div class="column is-full">
    <article class="message is-dark">
...
```
![capture d ecran 2018-01-16 a 14 21 46](https://user-images.githubusercontent.com/1658628/34991089-a3e95f52-fac8-11e7-818d-00c30267cf16.png)

**Comment by joseph-shinaberry** [comment]
This is still an issue.

**Comment by noraj** [comment]
> This is still an issue.

Yes, stale bots are more a nuisance than an help.

I fixed it that way:

1. Create a class `.no-flex`
2. Add the class `.no-flex` on the `.columns`

SASS

```sass
.no-flex
  flex: none
  width: 100%
```

HTML

```html
            .columns.is-vcentered.no-flex
              .column.is-three-quarters
                span example
              .column.is-one-quarter
                span.icon
                  i.fas.fa-home
```

My issue was that the parent element of `.columns` introduced some flex that was 1) not needed 2) was breaking the spacing.
