### ISSUE TITLE
is-offset-X-tablet adds additional code

### ISSUE THREAD

**Issue by dacodekid** [jgthms/bulma#718]
Is it about Bulma or about the Docs? **Yes**
Is it a bug/feature/question or do you need help? **Possible Bug**
If it's a bug, is it a browser bug? **No**

### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.4.1]

I am sure this issue is **not a duplicate**

### Description

Description of the bug, enhancement, or question

The lines [124](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L124) & [128](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L128) that only exists in `tablet`, takes precedence on `tablet` mode.

### Steps to Reproduce
```html
<div class="columns">
    <div class="column is-10-tablet is-offset-1-tablet is-8 is-offset-2">
    </div>
</div>
```

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/10047844/25480148/8c497748-2b15-11e7-9d57-1c7e3ca035a3.png)

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/10047844/25480124/7070290e-2b15-11e7-804f-18f409d940f4.png)

**Comment by dacodekid** [comment]
On following note, commenting the above line also removes all `is-[1-12]` classes.

**Comment by jgthms** [comment]
`+tablet` means "for tablets and upwards", not "tablet only".

So `is-8` is like `is-8-tablet`. If you want that on tablet only, you can override on desktop with `is-10-desktop`.

**Comment by amfische** [comment]
I have an issue where I want offset on tablet, and no offset on desktop but `is-offset-0-desktop` doesn't seem to be a rule, so the tablet rule `is-offset-3-tablet` is active on tablet and upwards. 

Is there a way to apply offset on only certain sizes?
