### ISSUE TITLE
issue with mapbox/leaflet tiles

### ISSUE THREAD

**Issue by mtimofiiv** [jgthms/bulma#72]
This causes issues with Leaflet/Mapbox maps in Chrome:
https://github.com/jgthms/bulma/blob/master/bulma/base/generic.sass#L49

```sass
img
  max-height: 100%
```

I have a feeling it's a bug in Chrome/webkit more than Bulma, but I am just reporting it here anyways.

What happens is that the tiles that are loaded by Leaflet (and Mapbox) have a height set and everything, like normal. But if one looks in the Computed styles, the height is still 0. No where in my test did I set the height to 0.

I tried this in Safari as well, and the problem was not there.

Commenting those rules out in the `generic.sass` monkey patched my problem for the time being.

**Comment by mtimofiiv** [comment]
Here's a screenshot of the computed properties in the Chrome dev tools:

<img width="254" alt="height" src="https://cloud.githubusercontent.com/assets/428948/13028638/f7d040dc-d274-11e5-8c2e-c194806bc7f1.png">

Weird, right?

And here's one where I explicitly set the height of the elements (with an `!important` flag, even):

<img width="327" alt="height2" src="https://cloud.githubusercontent.com/assets/428948/13028642/0fc829d4-d275-11e5-8367-de81fe0fcfd2.png">

Seems Chrome just chokes on that `min-height: 100%;` for some reason.

**Comment by timwis** [comment]
Wow, some timing, I just ran into this issue too @mtimofiiv, thanks for diagnosing. I put together [a demo](http://codepen.io/timwis/pen/OMdEaB) for illustrative purposes. If you go to the _Settings_ button at the top and remove bulma from the _CSS_ tab, you'll see the tiles render just fine.

**Comment by jgthms** [comment]
Oh that's an interesting one. To be honest, I don't remember the exact purpose for adding `max-height: 100%`. I guess I should remove it.

**Comment by mtimofiiv** [comment]
Thanks @timwis for the workaround - it solved my issue!

**Comment by mtimofiiv** [comment]
@jgthms thanks!

I would imagine its for the sake of responsive images, but then the width is usually the desired constraint, and considering how the height of a parent container will a lot of times not be set, I guess it should probably indeed be removed as you say.

**Comment by jgthms** [comment]
Yeah I think I'm just gonna remove it. I just don't remember why I set that max-height for.

**Comment by jgthms** [comment]
Should be fixed now.
