### ISSUE TITLE
.section background color is set to $white instead of $background

### ISSUE THREAD

**Issue by bathyscaaf** [jgthms/bulma#720]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.1] 

### Description

The .section class, found in sass/layout/section.sass, has a set background color of $white.
As this is a layout class I would expect there to be no background color set -- or if necessary (for some reason), that the background color be set to $background from the initial variables.

### Steps to Reproduce

Add a section class to div on a page with a non-white background.

### Expected behavior

As this is a layout class I would expect there to be no background color set -- or if necessary (for some reason), that the background color be set to $background from the initial variables.

### Actual behavior

The background of the div is white and must be overridden

EDIT:  I removed the !important override in the ###Actual behavior; turns out I had the minireset compiling into my project twice by accident.  I still believe a layout class shouldn't have a background.

**Comment by hummal** [comment]
Totally agree. Had the same problem and need to overwrite section class.

**Comment by Log1x** [comment]
+1

**Comment by CaitlinWeb** [comment]
This is actually a problem on a number of components as well. Card, code/pre, modal, nav, box... I'd like to see each component and layout class have their own variables with a white default, like how inputs and buttons have `$input-background` and `$button-background`.

**Comment by neilcarpenter1** [comment]
I dont think the .section class should have any background color set. Just have it transparent.

**Comment by hummal** [comment]
If this would be configurable through $background whatever, you could easily set it to transparent. ...

**Comment by neilcarpenter1** [comment]
Yes true. I would expect $background to be used for body - as well as being available in your own sass to use on whichever elements you like.

But for .section I dont see how setting a background of $background by default is neccessary. By having it set to transparent, it would automatically show the background colour of body through. Which is what i'd expect to happen. If I wanted to set a different background color for a particular section then I would just create some custom class to do so.

By default though there's no point in setting a background color for .section.

**Comment by hummal** [comment]
You are right.

**Comment by stefanoruth** [comment]
Maybe we should just make the hero element "is-primary", "is-info" available as global modifiers for background?

**Comment by jgthms** [comment]
The section has no background now.

**Comment by captDaylight** [comment]
@jgthms could you elaborate on this? I'm trying to figure out the correct way to set the background color of a section with Bulma.

**Comment by neilcarpenter1** [comment]
I would imagine you set a background colour with your own css. @captDaylight
