### ISSUE TITLE
[Bug] Input field doesn't expand fully

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#723]
It's a bug in Bulma 0.4.1.
When there is hidden button next to the field - it doesn't expand fully.

```
 <div class="field is-grouped">
  <p class="control is-expanded">
    <input class="input" type="text">
  </p>
  <p class="control is-hidden">
    <input type="submit" class="button is-primary">
  </p>
</div>
	
<div class="field">
  <p class="control is-expanded">
    <input class="input" type="text">
  </p>
</div>
```

https://codepen.io/anon/pen/OmgXrR
![selection_056](https://cloud.githubusercontent.com/assets/18059922/25609552/f44edce4-2f1f-11e7-980e-3a46bfe667ad.png)

**Comment by jgthms** [comment]
Remove the hidden control.

**Comment by tu5** [comment]
@jgthms i'm using it with is-hidden-mobile

**Comment by jgthms** [comment]
Yeah but you have the `control` class. Remove that.

**Comment by tu5** [comment]
@jgthms Tried it too, no effect, as you can see on https://codepen.io/anon/pen/qmjqeY

**Comment by jgthms** [comment]
```
<div class="box">
	
 <div class="field is-grouped">
  <p class="control is-expanded">
    <input class="input" type="text">
  </p>
</div>
	
<div class="field">
  <p class="control is-expanded">
    <input class="input" type="text">
  </p>
</div>
	
  <p class="is-hidden">
    <input type="submit" class="button is-primary">
  </p>
</div>
```

**Comment by tu5** [comment]
@jgthms Maybe I not explained it clearly what I mean, but see a live example on my site. First search button is `is-hidden-mobile` and second `is-hidden-tablet`.
desktop:
![selection_057](https://cloud.githubusercontent.com/assets/18059922/25621051/83400678-2f50-11e7-90ee-6d0394d28a34.png)
mobile:
![selection_058](https://cloud.githubusercontent.com/assets/18059922/25621060/89baa846-2f50-11e7-932a-7acb4f261efc.png)
