### ISSUE TITLE
Button text not centered safari

### ISSUE THREAD

**Issue by robertmylne** [jgthms/bulma#727]
When adding the `is-fullwidth` to a `button` it does not `center the text` on `safari ios`. To center the text I need to add `'display: inline-block;' ` to the button.

**Comment by jgthms** [comment]
It's weird because there is a `justify-content: center`: https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L32

**Comment by jjojohjohn** [comment]
why was this issue closed @jgthms ? was this resolved? I have the same issue as well

**Comment by tu5** [comment]
@jjojohjohn he just loves to close every issue without even giving change for discussion. It won't help to build community.

**Comment by jjojohjohn** [comment]
To expand on the issue, this isn't just safari, it just happens on iOS chrome as well (probably has to do with webkit)

**Comment by kwando** [comment]
I noticed this issue as well.

**Comment by jgthms** [comment]
It is a browser bug. There's nothing I can do to fix it. The `.button` already has `justify-content: center` _and_ `text-align: center`.

**Comment by anulamatamang** [comment]
There is a default uneven top and bottom padding from the user agent stylesheet. In my case, even when I've removed this padding, the text seems to appear slightly above the dead center.

**Comment by zacharytyhacz** [comment]
This worked for me:

```css
.button {
    display: inline-flex;
    justify-content: center;
    align-items: center;
}
```

**Comment by Wish-wakanda** [comment]
> It's weird because there is a `justify-content: center`: https://github.com/jgthms/bulma/blob/master/sass/elements/button.sass#L32





https://stylesheets.space/questions/what-is-the-best-way-to-center-a-button-element-horizontally-within-a-div-element
