### ISSUE TITLE
Built-in column centering.

### ISSUE THREAD

**Issue by SupaHam** [jgthms/bulma#73]
As you know `.is-centered` is used for centering text, but at first I expected `.is-centered` alongside `.columns` to make the columns centered. Although it isn't a big deal to write out the following code it could be seen as a major convenience for some people making Bulma smooth to write content with:
```css
.columns.is-centered {
    justify-content: center;
}
```

One possible issue with this is still having text aligned to center, my fix for this was to set `text-align: inherit;` but I'm not entirely sure if this is considered bad practice.

Thanks

**Comment by jgthms** [comment]
Yeah there should be something to center columns.

I guess I should rename the text alignment modifiers to `is-text-centered`, `is-text-left`, and `is-text-right`.

**Comment by jgthms** [comment]
This has been added.

**Comment by wolfbyteio** [comment]
Hi, the documentation is still referencing `is-centered` instead of `is-text-centered`, at least in the [footer](http://bulma.io/documentation/layout/footer/) section.

**Comment by Rainbowlemon** [comment]
+1, I didn't know `is-centered` existed until coming to Github. Perhaps another section to add to the 'grid' documentation area?

**Comment by LiamDotPro** [comment]
If your wondering how to centre text inside a div you'll want to use `has-text-centered`.

**Comment by umanga907** [comment]
is-centered-mobile ?
