### ISSUE TITLE
Oversized card content doesn't respect the grid [bug]

### ISSUE THREAD

**Issue by alexeypetrushin** [jgthms/bulma#730]
### Overview of the problem

This is a **bug**
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.4.1
My **browser** is: Chrome

### Description

Card Component doesn't respect the grid size and makes size of the cell bigger than it should be

Demo http://codepen.io/anon/pen/qmPKRO?editors=1100

<img width="1009" alt="screen shot 2017-05-05 at 11 31 02 pm" src="https://cloud.githubusercontent.com/assets/94196/25747472/f4bd0aca-31ea-11e7-9bbe-ccff2d4de1dd.png">

### Expected behavior

All cells should be the same width

### Actual behavior

Cell with the card is bigger

**Comment by jgthms** [comment]
You've got a `.notworking{ white-space: nowrap;}`. Just remove that.

**Comment by alexeypetrushin** [comment]
That's part of the the issue, I've included nowrap on a purpose. There's no way to limit the text to be just one line inside of the card in the grid.

**Comment by jgthms** [comment]
Add `overflow: auto;` on that column.

**Comment by alexeypetrushin** [comment]
Works, thanks. 

Although I still don't understand why not add `.column { overflow: auto; }` by default.

**Comment by jgthms** [comment]
Because that's not the browser's default behaviour, and I don't want to break that?
