### ISSUE TITLE
nav-menu NOT hiding itself when using nav-center.

### ISSUE THREAD

**Issue by Jamerrone** [jgthms/bulma#732]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.1]
My **browser** is: Safari
I am sure this issue is **not a duplicate**

### Description

Not all navigations are aligned to the right, my current design has a centered navigation, and I am sure I am not the only one that ever did this. nav-menu does not seem to hide itself on mobile when combined with nav-center.

### Expected behavior

Element to hide itself on mobile.

### Actual behavior

It does not hide on mobile.

**Comment by xJoeyv** [comment]
My whole navbar doens't work and doesn't have the usual 'dropdown' on mobile devices.
It does show the Hamburger menu but it doesnt do anything.

This is using the latest chrome.

**Comment by Jamerrone** [comment]
@xJoeyv I don't think the burger-menu is supposed to work anyway, just add some js and you are good to go.

**Comment by SoerenTerh** [comment]
Yeah. Bulma is not meant to contain js functionalities / libraries like f.e. Bootstrap does. Though Bulma has the css parts of the mobile navbar built in. So you simply have to use js to append an 'active' class in order for it to work as expected.

**Comment by SoerenTerh** [comment]
@Jamerrone nav-menu is not meant to be mixed with nav-left. Only nav-right is supported and kind of makes sense from a usability view.

> [nav-menu for menu that is collapsable on mobile (you can combine it with nav-right)](http://bulma.io/documentation/components/nav/)

**Comment by Jamerrone** [comment]
@SoerenTerh I don't think such limitations are a health thing. I mean It is not that hard to do what I want using custom css, but I should prefer if bulimia supported more then 1 single style. I don't want bulimia websites to look like bootstrap websites, all the same.

**Comment by kgoedecke** [comment]
@Jamerrone +1 here from me! why can't I put the menu in the center for example? I don't even think thats necessarily bad UI/UX.

**Comment by atomi** [comment]
Is there a workaround with css to have `nav-center` and `nav-menu` work with the hamburger dropdown while we wait for a fix?

Am I going to need to add a fixed width and margin 0 auto?
