### ISSUE TITLE
Font awesome font-size scales overwritten

### ISSUE THREAD

**Issue by alexolder** [jgthms/bulma#735]
Bulma has a specific rule to set font-size on .fa to 21px, this breaks functionality provided by font awesome to have icon sizes such as fa-5x. 

Can it be removed to allow font awesome to function as expected?

**Comment by leDebutant** [comment]
I agree. This is totally random. Also it is impossible to use other features like the putting an icon in another to make it looks like it is in a box.

**Comment by morph85** [comment]
I managed to re-override it after include it using sass Bulma with codes below:

```
@import "~bulma/sass/utilities/initial-variables";
// ... your custom Bulma settings here ...
@import "~bulma";

// override font-awesome here so fa-#x works
$fa-font-path: "~font-awesome/fonts";
@import '~font-awesome/scss/font-awesome';
```

**Comment by MrBrax** [comment]
Was this really a proper fix? Now the icons are way too big in titles
