### ISSUE TITLE
[Help] Creating dynamic table of content

### ISSUE THREAD

**Issue by tu5** [jgthms/bulma#736]
It's a **help** request about **Bulma** 0.4.1.

Hey,
I'm looking for hints for creating a dynamic table of content with Bulma.
This is what I want to achieve: https://afeld.github.io/bootstrap-toc/

Maybe any of you already implemented it into Bulma? Thanks.

**Comment by jgthms** [comment]
I believe you could tweak the Menu: http://bulma.io/documentation/components/menu/
