### ISSUE TITLE
Conflict on using Swiper

### ISSUE THREAD

**Issue by hansthinhle** [jgthms/bulma#741]
I need a help with using Bulma and Swiper together.

### Overview of the problem

I'm using Bulma **version** [0.4.1] 
My **browser** is: Newest Chrome

### Description

The [Swiper](http://idangero.us/swiper/) and Bulma CSS Framework have a conflict on working together. Every time I place the Swiper content in div with `column` class, the layout of Swiper is broken.

### Steps to Reproduce

Should be ok like this:
[http://idangero.us/swiper/demos/#.WRQTE7yGOgA](http://idangero.us/swiper/demos/#.WRQTE7yGOgA)

### Actual behavior

But it turned out like this

https://codepen.io/x1angel/pen/rmdeor

*Remove the columns and column wrappers, you will see it's fine at all.

**Comment by jgthms** [comment]
The `.swiper-container` has a `height: 100%`. This doesn't do anything, unless you use some absolute positioning.

It works without the columns because the `body` is fullheight. Try searching on Google: https://www.google.co.uk/search?q=css+height+100
