### ISSUE TITLE
Incomplete docs

### ISSUE THREAD

**Issue by dariusgarza** [jgthms/bulma#743]
This is about the Bulma **Docs**
### Description
The "online" [documentation](http://bulma.io/documentation/overview/start/) doesn't mention the crucial step of having to use Jekyll to get started with Bulma which I finally found buried in the docs [README](https://github.com/jgthms/bulma/tree/master/docs). This was extremely frustrating and I wasted 45 mins trying to understand what's going on. 

The Instructions on how to modify the Jekyll config file were also confusing. Perhaps Jeckyll users are familiar with that, but an out of the box setup would have been appreciated.

**Comment by jgthms** [comment]
The documentation is for the Bulma CSS framework. People _can_ run the documentation offline, but is not recommended, since the online one is updated constantly.

**Comment by faststare** [comment]
maybe provide a markdown docs for offline. because not all developers have access to a internet connection all the time.
