### ISSUE TITLE
Typos in elements/title.sass

### ISSUE THREAD

**Issue by shirohana** [jgthms/bulma#744]
### Overview of the problem

Just some simple typos in source code.

This is about the Bulma **CSS framework**
I'm using Bulma **version** [master]

### Description

There's some typos in L34 and L49 of

https://github.com/jgthms/bulma/blob/master/sass/elements/title.sass#L34

**Comment by jgthms** [comment]
Bulma uses the American spelling of "colors".

**Comment by shirohana** [comment]
Isn't it "sizes"?

**Comment by jgthms** [comment]
So sorry. You're right! Let me fix that. 👍
