### ISSUE TITLE
 Errors with npm install:

### ISSUE THREAD

**Issue by dariusgarza** [jgthms/bulma#746]
### Errors with npm install:
`npm install`  gives errors without first doing `npm init -f`

Is `npm init -f` an implied first step, or is something wrong here? node version 7.5

### Steps to Reproduce

1. npm install

### Expected behavior
To not get errors

### Actual behavior

I get errors and nothing downloads

**Comment by clickbox** [comment]
npm install works for me using node version 6.10.3. node version 7.5 is not fully supported yet so I suspect that may be the issue?

**Comment by stoqe** [comment]
'npm install bulma' errors out for me with Node v6.10.2.

> ➜  ~ node -v
v6.10.2
➜  ~ npm install bulma
/Users/stoqe
└── bulma@0.4.1 

npm WARN enoent ENOENT: no such file or directory, open '/Users/stoqe/package.json'
npm WARN life No description
npm WARN life No repository field.
npm WARN life No README data
npm WARN life No license field.

**Comment by stoqe** [comment]
Update: 'npm install bulma' also errors out for me with Node v6.10.3.

**Comment by clickbox** [comment]
I get the same error with 'npm install bulma'
`yarn add bulma` works better for me however

**Comment by dariusgarza** [comment]
Didnt you say it worked for you before? Seems like there may be some
confusion. I was referring to 'npm install bulma' not just 'npm install'

**Comment by clickbox** [comment]
I thought you were trying to clone the repo and run `npm install`

**Comment by gabe3886** [comment]
I had the same issue on Ubuntu 16.04.  Needed to install nodejs-legacy package for it to work.  Once that was installed it was fine.

**Comment by jgthms** [comment]
I've updated all packages. It should work with `node v6.11.0`.
