### ISSUE TITLE
Feature: Drand and Drop on Tiles/Cards.

### ISSUE THREAD

**Issue by GinoHereIam** [jgthms/bulma#749]
Feature request:

### Overview of the problem

There is no **Drag and Drop support** :(
 
### Description

It would be a nice feature to have a **Drag and Drop** on **Tiles / Cards**
Is it possible?

**Comment by kwando** [comment]
Bulma does not provide any Javascript at all, you will have to implement that yourself.

**Comment by scottwernervt** [comment]
Check out the `Boards` template at https://dansup.github.io/bulma-templates/ for an example of tile / cards using Bulma. As mentioned above, you would have to implement the JS for drag and drop functionality.

**Comment by GinoHereIam** [comment]
I guess we can close this ticket then. :) Thanks nice templates!
