### ISSUE TITLE
Image inside td is not showing

### ISSUE THREAD

**Issue by jruizsulime** [jgthms/bulma#752]
This is a **bug** about **Bulma** in **0.4.1**.

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.1]
My **browser** is: Firefox 53.0.2 (latest x64)

### Description

When I put a `<img src=""/>` inside a td, the image is not showing in browser. When I show the console, the html code is correct.

**Comment by jgthms** [comment]
Show some code please.

**Comment by jruizsulime** [comment]
Some code:

`<table>
<tr>
<td><img src="route/to/my/image.png/></td>
</tr>
</table>`

**Comment by shankariyerr** [comment]
@jruizsulime can you check if this is working for you? https://jsfiddle.net/uus22kwe/

**Comment by jruizsulime** [comment]
@shankariyerr yes, your example is working for me. I've make more tests in my code and i'm attaching a screenshot

![bulma](https://cloud.githubusercontent.com/assets/22749661/26319979/7b023126-3f21-11e7-8e3f-a6a83a1606a0.png)

1. The image is not showing.
2. The code is correct, when i place mouse in url, the pic is showing in inspector.
3. When i deselect the max-width:100% css code, image is showing in td. I don't know where and why is generic.sass placing in my code ¿?

**Comment by mkoflerAT** [comment]
Have you tried closing the img-tag with /> ?

**Comment by jgthms** [comment]
What happens when you open `http://localhost/bonos/images/user/1.png`? Also, open your network tab and show us a screenshot.

**Comment by jruizsulime** [comment]
Dear @jgthms , when i clic on the url in the inspector, the url is opened correctly.

**Comment by shankariyerr** [comment]
@jruizsulime can you take a screenshot of your networks tab and share here?
