### ISSUE TITLE
Template links are broken on the website

### ISSUE THREAD

**Issue by alex996** [jgthms/bulma#756]
### Overview of the problem

This is about the Bulma **Docs**

### Description

I noticed that bulma.io website has a [section for templates](http://bulma.io/templates/); however, none of the links are working at the moment. Are the templates still in progress and when are they expected to be published? On a side note, it would be extremely useful to have a very basic starter template outlining the proper html structure and layout.

**Comment by jgthms** [comment]
It's not ready yet.
