### ISSUE TITLE
Static form input addons

### ISSUE THREAD

**Issue by Korijn** [jgthms/bulma#759]
### Overview of the problem

This is about the Bulma **CSS framework** & **docs** as well
I'm using Bulma **version** [0.4.1]
My **browser** is: Chrome 58
I am sure this issue is **not a duplicate**

### Description

Is it possible to make static form input addons with Bulma? I'm not sure if I'm overlooking something in the docs or if it is really a new feature for Bulma.

### Expected behavior

With something like this:

```html
<div class="field has-addons has-addons-right">
  <p class="control">
    <input class="input" type="text" placeholder="Recipient's username">
  </p>
  <p class="control">
    <span class="static">
      @example.com
    </span>
  </p>
</div>
```

I would expect to get something like this (taken from Bootstrap docs):

![image](https://cloud.githubusercontent.com/assets/1882046/26354093/7964d470-3fc3-11e7-8e9f-765781223f18.png)

**Comment by jgthms** [comment]
You _could_ do it with a `button`, since it has the same height as an input:

```
<div class="section">
  <div class="field has-addons has-addons-right">
    <p class="control">
      <input class="input" type="text" placeholder="Recipient's username">
    </p>
    <p class="control">
      <span class="button is-light" disabled>
        @example.com
      </span>
    </p>
  </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/1254808/26472628/e7ce260a-419e-11e7-9ea3-57f2310d20c9.png)

https://codepen.io/jgthms/pen/ybwmQY

It's not ideal, but I believe I could add a `is-static` modifier.

**Comment by Korijn** [comment]
Awesome, thanks a lot!
