### ISSUE TITLE
missing styling and layout for .nav-left.is-active on mobile, only .nav-right works

### ISSUE THREAD

**Issue by DimitarChristoff** [jgthms/bulma#764]
### Overview of the problem

This is about the Bulma **CSS framework**

 I'm using Bulma **version** [0.4.1]

### Description

https://github.com/jgthms/bulma/blob/0.4.1/sass/components/nav.sass#L94

if you use collapsible menus and nav-left, on mobile there is no background colour anymore 

this used to be applied to `.nav-menu` and is now only on `.nav-right`

old code where it worked:
https://github.com/jgthms/bulma/blob/0.4.0/sass/components/nav.sass#L68

**Comment by kyranb** [comment]
I believe `flex-basis: 0` is what's causing this.
