### ISSUE TITLE
What's the purpose of sass/utilities/variables.sass

### ISSUE THREAD

**Issue by pixelpeter** [jgthms/bulma#769]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.2]
My **browser** is: browser unrelated

### Description

I was wondering what the purpose of the file `sass/utilities/variables.sass` is because I couldn't find any `@import` or usage for this file in the source code.

Is it deprecated?

### Actual behavior
I got aware of this issue because I wanted to overwrite variable like it's defined in the documentation
```
// Import the initial variables
@import "../sass/utilities/initial-variables"

// Set your own initial variables
$blue: #72d0eb

//  Import the rest of Bulma
@import "../bulma"
```

Generally this is working fine and as expected.

But when I want to do this for a component from vue-bulma like e.g. https://github.com/vue-bulma/tooltip it will fail because the components will include `sass/utilities/variables.sass`.

Example:  https://raw.githubusercontent.com/vue-bulma/tooltip/master/src/style.scss

### Solution
If you tell me that this file is deprecated I can let the developers of vue-bulma @fundon know that they're including the wrong file.

Otherwise can you please let me know what I'm missing!?

Thanks for your help and thanks for this great framwork
Peter

**Comment by jgthms** [comment]
Hi @pixelpeter 

Yes the file `variables.sass` is **deprecated**. I felt that removing it would break most builds, so I left it there for now, and planning to remove it in `0.5.0`.

I'm not sure what the best strategy is here tbh.
