### ISSUE TITLE
React.js components for Bulma

### ISSUE THREAD

**Issue by kulakowka** [jgthms/bulma#771]
I started working on a library of react.js components for Bulma.

https://kulakowka.github.io/react-bulma/

![2017-05-31 2 26 06](https://cloud.githubusercontent.com/assets/557190/26609192/8bc00208-45a8-11e7-94ba-638622983c38.png)

This is current progress (**updated: June 19**)

| Docs | Code | Component    |
|:-----|:-----|:-------------|
| [x]  | [x]  | Box          |
| [x]  | [x]  | Button       |
| [x]  | [x]  | Card         |
| [ ]  | [x]  | Checkbox     |
| [x]  | [x]  | Container    |
| [x]  | [x]  | Content      |
| [ ]  | [x]  | Control      |
| [x]  | [x]  | Delete       |
| [ ]  | [x]  | Field        |
| [ ]  | [x]  | Heading      |
| [x]  | [x]  | Hero         |
| [x]  | [x]  | Icon         |
| [x]  | [x]  | Image        |
| [ ]  | [x]  | Input        |
| [x]  | [x]  | Level        |
| [ ]  | [x]  | Link         |
| [x]  | [x]  | Media        |
| [x]  | [x]  | Message      |
| [x]  | [x]  | Nav          |
| [x]  | [x]  | Notification |
| [x]  | [x]  | Panel        |
| [x]  | [x]  | Progress     |
| [x]  | [x]  | Section      |
| [x]  | [x]  | Table        |
| [x]  | [x]  | Tabs         |
| [x]  | [x]  | Tag          |
| [ ]  | [x]  | Textarea     |
| [x]  | [x]  | Title        |

I will be glad to your help and advice.

**Comment by jgthms** [comment]
Amazing! Could you add it to the README?

**Comment by kulakowka** [comment]
Yes, I will add as soon as I finish all the components.

**Comment by bsfair** [comment]
@kulakowka Any updates on this?

**Comment by kulakowka** [comment]
Yes, I made almost all the components. I need some more time. 

This is current progress:

#### Progress

| Docs | Code | Component    |
|:-----|:-----|:-------------|
| [x]  | [x]  | Box          |
| [x]  | [x]  | Button       |
| [x]  | [x]  | Card         |
| [ ]  | [x]  | Checkbox     |
| [x]  | [x]  | Container    |
| [x]  | [x]  | Content      |
| [ ]  | [x]  | Control      |
| [x]  | [x]  | Delete       |
| [ ]  | [x]  | Field        |
| [ ]  | [x]  | Heading      |
| [x]  | [x]  | Hero         |
| [x]  | [x]  | Icon         |
| [x]  | [x]  | Image        |
| [ ]  | [x]  | Input        |
| [x]  | [x]  | Level        |
| [ ]  | [x]  | Link         |
| [x]  | [x]  | Media        |
| [ ]  | [x]  | Message      |
| [x]  | [x]  | Nav          |
| [x]  | [x]  | Notification |
| [x]  | [x]  | Panel        |
| [x]  | [x]  | Progress     |
| [x]  | [x]  | Table        |
| [x]  | [x]  | Tabs         |
| [x]  | [x]  | Tag          |
| [ ]  | [x]  | Textarea     |
| [x]  | [x]  | Title        |

**Comment by bsfair** [comment]
Nice! I',m excited to see the final product.

**Comment by kulakowka** [comment]
Thanks for your support. This motivates me to move faster.

**Comment by bsfair** [comment]
@kulakowka No rush at all, thank *you* for helping out the Bulma community. :smile:

**Comment by jgthms** [comment]
It's been merged.

**Comment by stonewjr** [comment]
good job
