### ISSUE TITLE
[Feature request] List group

### ISSUE THREAD

**Issue by KKSzymanowski** [jgthms/bulma#772]
I haven't found anything similar to Bootstrap 4's `list-group`.
![image](https://cloud.githubusercontent.com/assets/13980973/26619287/0cdbc7ca-45de-11e7-92b4-17575c87e250.png)

Are you interested in this feature? If so, I can make a PR.

**Comment by KKSzymanowski** [comment]
@jgthms Should I assume, you'll be working on it since you assigned yourself?

**Comment by IamManchanda** [comment]
Hey @jgthms 
This is harry from [zurb/foundation-sites](https://github.com/zurb/foundation-sites/) and i think this is a very cool component... have used it a lot and i think you guys should definitely have this. :+1: 

Thanks and best of luck :wink:
Harry Manchanda, Yetinaut

**Comment by dumptyd** [comment]
Even though this feature isn't available yet, you can put together something using `panel-block` class. It doesn't support bg/color modifier classes, so you can add that with some CSS. I created a demo fiddle here https://jsfiddle.net/dumptyd/vztuv1g5/ .

**Comment by danieldaeschle** [comment]
Why isn't it already added to bulma?

**Comment by jgthms** [comment]
Because it hasn’t been implemented yet. Want to have a go?

**Comment by danieldaeschle** [comment]
I will try it ;)

**Comment by danieldaeschle** [comment]
https://github.com/jgthms/bulma/pull/1720
