### ISSUE TITLE
Flexbox positioning classes

### ISSUE THREAD

**Issue by whnunlife** [jgthms/bulma#773]
This is about the Bulma **CSS framework
This is about the Bulma **Docs

Just checking out Bulma right now, been playing around with for a week or so. My question is, is there any support via classes to do various flexbox positioning?

Such as center all items in the container, or space them equally, etc.

I went thru the docs and didn't find any references.

**Comment by jgthms** [comment]
Not really. I don't want users to style their page with CSS classes _only_, when writing CSS is the better option.
