### ISSUE TITLE
Bulma has problem with Chrome for mobile

### ISSUE THREAD

**Issue by thanhngch** [jgthms/bulma#776]
### Overview of the problem
This maybe a bug with mobile
This is about the Bulma **CSS framework**
I'm using Bulma **version** v0.4.2
Bulma don't work ok on mobile with Chrome. FireFox work, but chrome not.

### Steps to Reproduce
1. In body tag, I add
```
    <div class="container">
      <div class="columns">
        <div class="column"> <p>Some long text</p>
        </div>
      </div>
    </div>
```
2. It have a scoll horizontal in chrome for mobile
(Go to https://dansup.github.io/bulma-templates/templates/blog.html to see same problem)
![image](https://cloud.githubusercontent.com/assets/6634690/26710002/168bdd88-4781-11e7-9c66-a32a35699444.png)

### Expected behavior
I don't want this scoll horizontal

**Comment by shaun-sweet** [comment]
This isn't a bulma thing, look at any webpage on mobile that is capable of vertical scrolling.  

```
::-webkit-scrollbar {
display: none;
}
```

Try that

**Comment by xlcrr** [comment]
Same problem here 

div class="container" also not working on mobile

**Comment by philippeluickx** [comment]
I'm using 0.6.1 and I can confirm that Bulma has issues on mobile.
In my case it is caused by the -0.75rem margins on the columns div. When I reset those to 0, I don't have a horizontal scroll anymore.

**Comment by frederikhors** [comment]
Any news on this?

**Comment by rayhaanq** [comment]
I've got the same problem on mobile for chrome and the above fix doesn't work

**Comment by jgrandar** [comment]
For me, this is what I get on Android by adding next tags to the head:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
Chorme mobile: gap at right and bottom.
Firefox mobile: double gap at right, one of them horizontal scrollable.

With:
```
<meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no">
```
Chrome mobile: no gaps.
Firefox mobile: gap at right.

**Comment by erquhart** [comment]
@jgrandar unfortunately that solution is not great for accessibility: https://a11yproject.com/posts/never-use-maximum-scale/

**Comment by abdullahe** [comment]
So is there any solution to this without messing up with accessibility?
