### ISSUE TITLE
Addons field and label

### ISSUE THREAD

**Issue by rafaelpimpa** [jgthms/bulma#777]
### Overview of the problem

 This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.2]
My **browser** is: Firefox/Chrome
I am sure this issue is **not a duplicate** (at least I couldn't find)

### Description

When using label in a has-addons field, the label position is not set correctly.

### Steps to Reproduce

Create a field like this
```html
<div class="field has-addons">
    <label class="label">Label</label>
    <p class="control">
        <input class="input" type="text" placeholder="Find a repository">
    </p>
    <p class="control">
        <a class="button is-info">
            Search
        </a>
    </p>
</div>
```

A **workaround** for this is wrapping the ``.has-addons`` on a ``.field`` with the label:

```html
<div class="field">
    <label class="label">Label</label>
    <div class="field has-addons">
        <p class="control">
            <input class="input" placeholder="Find a repository" type="text">
        </p>
        <p class="control">
            <a class="button is-info">
                Search
            </a>
        </p>
    </div>
</div>
```

### Expected behavior

![expected](https://cloud.githubusercontent.com/assets/18370605/26723945/51948164-476d-11e7-8832-e252de626e01.PNG)

### Actual behavior

![current](https://cloud.githubusercontent.com/assets/18370605/26723948/577ead0c-476d-11e7-8346-e3b8b25095b3.PNG)

**Comment by jgthms** [comment]
```
<div class="field">
    <label class="label">Label</label>
</div>

<div class="field has-addons">
    <p class="control">
        <input class="input" type="text" placeholder="Find a repository">
    </p>
    <p class="control">
        <a class="button is-info">
            Search
        </a>
    </p>
</div>
```

**Comment by cloud-tribal** [comment]
margin-bottom is not the same though. With additional field div it's 0.75rem instead of 0.5rem when the label is within the field div

**Comment by gdereese** [comment]
If you think in terms of your field with addons being a composite control, this approach makes loads of sense: wrap the addons field into another field that holds the label.  This approach also allows the proper margin/padding/positioning of the label above the addon field, as well as any `<p class="help">` elements you might have directly under the top-level control container, etc.

```
<div class="field">
  <label class="label">Label</label>
  <p class="control">
    <div class="field has-addons"/>
      <p class="control">
        <input ... />
      </p>
      <p class="control">
        <a class="button" ... ></a>
      </p>
    </div>
  </p>
</div>
```

**Comment by hiagorios** [comment]
> 
> 
> For those looking for a solution, try this:
> 
> ```
> <div class="field">
>   <label class="label">Label</label>
>   <p class="control">
>     <div class="field has-addons"/>
>       <p class="control">
>         <input ... />
>       </p>
>       <p class="control">
>         <a class="button" ... ></a>
>       </p>
>     </div>
>   </p>
> </div>
> ```
> 
> If you think in terms of your field with addons being a composite control, this approach makes loads of sense: wrap the addons field into another field that holds the label. This approach also allows the proper margin/padding/positioning of the label above the addon field, as well as any `<p class="help">` elements you might have directly under the top-level control container, etc.

Thanks for the solution!
I had problem with the input width not taking all the space available but fixed adding `is-expanded` to it.

**Comment by codeofsumit** [comment]
> For those looking for a solution, try this:
> 
> ```
> <div class="field">
>   <label class="label">Label</label>
>   <p class="control">
>     <div class="field has-addons"/>
>       <p class="control">
>         <input ... />
>       </p>
>       <p class="control">
>         <a class="button" ... ></a>
>       </p>
>     </div>
>   </p>
> </div>
> ```
> 
> If you think in terms of your field with addons being a composite control, this approach makes loads of sense: wrap the addons field into another field that holds the label. This approach also allows the proper margin/padding/positioning of the label above the addon field, as well as any `<p class="help">` elements you might have directly under the top-level control container, etc.

Awesome, thanks. Would change the first `p.control` to a `div` though as a `div` should not be inside a `p`

**Comment by peabnuts123** [comment]
This is a bug. No discussion has been had and only hacky workarounds with poor html semantics have been provided. I think this warrants more discussion. If this is a limitation then it should be documented, otherwise the bug should be resolved.

**Comment by mtlynch** [comment]
Thanks for the example, @gdereese!

Just to echo what @codeofsumit mentioned, it's invalid to have `div` inside a `p`, so here's a revised version that uses `div` elements instead of `p`:

```html
<div class="field">
  <label class="label">Label</label>
  <div class="control">
    <div class="field has-addons"/>
      <div class="control">
        <input ... />
      </div>
      <div class="control">
        <a class="button" ... ></a>
      </div>
    </div>
  </div>
</div>
```

**Comment by fmarz96** [comment]
> > Thanks for the example, @gdereese!
> > Just to echo what @codeofsumit mentioned, it's invalid to have `div` inside a `p`, so here's a revised version that uses `div` elements instead of `p`:
> > ```
> > <div class="field">
> >   <label class="label">Label</label>
> >   <div class="control">
> >     <div class="field has-addons">
> >       <div class="control">
> >         <input type="text">
> >       </div>
> >       <div class="control">
> >         <a class="button">Send</a>
> >       </div>
> >     </div>
> >   </div>
> > </div>
> > ```
> 
> Thanks for refining my example @mtlynch!

According to your example, I need a form with 5 input type text, one button and 4 labels. Do you think this is possible?
And each label should be on top of an input.
For example, the first label should be on top of the first input, the second label on top of the second input, etc etc, until the fourth label on top of fourth input.
It should appear like this:
1st label ---- 2nd label ---- 3rd label ---- 4th label
1st input ---- 2nd input ---- 3rd input ---- 4th input ---- 5 input ---- Button

**Comment by BeepBot99** [comment]
This is a bug. I agree with @peabnuts123.
