### ISSUE TITLE
Horizontal and vertical divider

### ISSUE THREAD

**Issue by 4goodapp** [jgthms/bulma#779]
Just like like in [Semantic-UI](https://semantic-ui.com/elements/divider.html) or [UIkit](https://getuikit.com/docs/divider)

![image](https://cloud.githubusercontent.com/assets/6249230/26745893/4bcceb58-47dc-11e7-8272-d501bcdc33e8.png)

[Demo](jsfiddle.net/xox5kt31/2/)

**Comment by jgthms** [comment]
I feel it's too specific for Bulma, but could be added as an extension.
