### ISSUE TITLE
No flexbox on breakpoints

### ISSUE THREAD

**Issue by PhillippOhlandt** [jgthms/bulma#78]
Hey,

recently Bulma got support for different mobile, tablet and desktop grids. But why is flexbox disabled?

Instead of 
```
.column.is-6-mobile {
    -webkit-box-flex: 0;
    -webkit-flex: none;
        -ms-flex: none;
            flex: none;
    width: 50%;
  }
```

You could do
```
.column.is-6-mobile {
    -webkit-box-flex: 6;
    -webkit-flex: 6;
        -ms-flex: 6;
            flex: 6;
  }
```

As said in earlier issues, disabling flexbox on a flexbox grid is not a good solution.

**Comment by jgthms** [comment]
The two are not equivalent.

`is-6` is to take up **half** of the width, like this

![right](https://cloud.githubusercontent.com/assets/1254808/13035663/4db7a048-d34d-11e5-8221-1914ba086a55.png)

What you're suggesting would have the wrong result:

![wrong](https://cloud.githubusercontent.com/assets/1254808/13035668/5ae38dfe-d34d-11e5-9a58-0fb3ca9c2f91.png)

`is-6` doesn't mean `flex: 6`. That's not how flexbox works.

**Comment by PhillippOhlandt** [comment]
It think it will work when you use `is-1` for the other ones, or?

But my point is, you say it's a flexbox powered framework and a few days later (after I discovered it), you disable flexbox.

**Comment by jgthms** [comment]
I don't think you understand how the `flex` property works.

Flexbox is **mainly** powered by `display: flex`, which is still present on the `columns` container.
Having `flex: none` on the `column` elements doesn't "remove" flexbox. The `flex` property is for **resizing** each _individual_ element _relative_ to one another, **when** the size available **within the parent** varies.
