### ISSUE TITLE
Increase documentation transparency regarding modifier classes

### ISSUE THREAD

**Issue by natecox** [jgthms/bulma#785]
### Overview of the problem
This is about the Bulma **Docs**
I'm using Bulma **version** 0.4.2

### Description

It would be nice if the docs indicated exactly which components support which modifier classes (e.g., `is-primary`). Currently, the only way to know for sure which components support a modifier is to jump into the code base and look for the modifier loop, or code it out and try it manually.

Additionally, components which are hard coded to values should be denoted as well; such as `nav` having a hard background color of `$white`, unless it's inside of a hero where it takes the background of `none`.

As it stands, it's difficult to plan the structure of a page, because you're guessing at what you're going to be able to configure and what you aren't.

**Comment by AlgusDark** [comment]
That's a good idea. I did a research on that, maybe I can create a that kind of Info from my definition files from TypeScript. 

https://github.com/AlgusDark/bloomer

I'll try it this week

**Comment by VizuaaLOG** [comment]
This is kind of being implemented now through the tags on the docs. For example the button docs now has a `colors: yes` and `sizes: yes` tag.

**Comment by natecox** [comment]
I noticed this yesterday, definitely a step in the right direction.
