### ISSUE TITLE
[Question] A naming convention to differentiate components and elements

### ISSUE THREAD

**Issue by joaoeduardo** [jgthms/bulma#788]
In the documentation is show that modifiers has a naming convention that makes easy to distinguish them. Why do not have the same for components and elements, like rscss do.

http://rscss.io/

**Comment by jgthms** [comment]
Elements are usually a **single** elements, like `button` or `title`.

Components require **nested** elements too, like `card`, `card-header`, `card-header-title`, `card-image`...

That's pretty much it.
