### ISSUE TITLE
Media Object image not displayed

### ISSUE THREAD

**Issue by petarov** [jgthms/bulma#79]
Hi!

I'm playing around with the MO component and I can't get to display the `media-left` positioned image. It just doen't work, unless I remove CSS  `position` from the `img` element, i.e.,

```css
.image img {
    bottom: 0;
    left: 0;
    /* position: absolute; */
    right: 0;
    top: 0;
    display: block;
    width: 100%;
}
```

Here's what I'm trying to do:

```html
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <img src="http://placehold.it/128x128">
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong> <small>@johnsmith</small> <small>31m</small>
              <br>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
            </p>
          </div>
          <nav class="navbar">
            <div class="navbar-left">
              <a class="navbar-item">
                <span class="icon is-small"><i class="fa fa-reply"></i></span>
              </a>
              <a class="navbar-item">
                <span class="icon is-small"><i class="fa fa-retweet"></i></span>
              </a>
              <a class="navbar-item">
                <span class="icon is-small"><i class="fa fa-heart"></i></span>
              </a>
            </div>
          </nav>
        </div>
      </article>
```

**Comment by Reflow1319** [comment]
i had the same issue, i was pulling the css form RawGit CDN, so when i remove the .min and use the non minify version it work without issue. if your using the RawGit CDN jsut remove .min. and it should work

**Comment by petarov** [comment]
@Reflow1319  Good info, thx! I believe whatever it was, it seems fixed in version `0.0.13+`. I was using `0.0.12`.

**Comment by juanmnl** [comment]
I'm starting with this framework (awesome btw) but i had this problem yesterday with the 0.0.13 minified downloadable version. 
The fixed scale helpers worked (ex:`is-128x128`) but the ratio one's (`is-square`) made the image disappear on the media object.
My image was 256x256, so i created, which fixed the issue.
```css
.image.is-256x256 {
  height: 256px;
  width: 256px;
}
```

**Comment by sanzexstha** [comment]
asdf asdfasd asdf asdf

**Comment by sanzexstha** [comment]
fg sdfgsdfg sdfg fdg
