### ISSUE TITLE
`container` make `column` not working properly in widescreen.

### ISSUE THREAD

**Issue by bigZ-again** [jgthms/bulma#791]
`container` make `column` not working properly in widescreen.

[Reproduce demo](https://fiddle.jshell.net/gqon4rnq/)

If remove `container` class, anything is OK.

**Comment by joaomarcuslf** [comment]
If you add is-fluid it will work

**Comment by jgthms** [comment]
And put the container outside the columns.

**Comment by bigZ-again** [comment]
> The  `.container` class can be used in any context

A caveat should be added to the document:
DO NOT USE `.container` CLASS in `.columns` CLASS.

@jgthms
