### ISSUE TITLE
Adobe XD Grid and UI kit

### ISSUE THREAD

**Issue by danilo-drs** [jgthms/bulma#792]
Hi, i'm trying to build an design documentation for our new front-end and I'm strongly inclined to use Bulma for this insted of botswhatever. 

But i'm missing some UI kits and grid definition to use with Adobe XD. 

Do you have this? I just can't found on documentation.

TKS.

**Comment by jgthms** [comment]
I'm not sure I understand what you're looking for? I've never used Adobe XD.

**Comment by xSilverdroid** [comment]
Adobe XD has premade UI Kits for Windows/Mac/Android application design - and I think that he's asking for a UI kit resembling the elements of Bulma to use for Adobe XD.

**Comment by bsfair** [comment]
I agree this is would be a nice feature, but is not within the scope of the project. Maybe a fan could make one.

**Comment by jgthms** [comment]
I agree with @bsfair

**Comment by HZooly** [comment]
Hey guys, some advance about this one? I've made some search, found nothing

**Comment by railhead** [comment]
@HZooly 
Here it is. 
https://tonyo.design/program/bulma/bulma-ui-kit_adobexd/
This is Japanese article. So please translate English. or press "Bukma-UIキットをダウンロードする" (blue button)

**Comment by juan-db** [comment]
The above seems to link to a 404.

I believe this is the updated link:
https://tonyo.design/posts/bulma-ui-kit-adobexd/
