### ISSUE TITLE
'has-addons' breaks help text positioning

### ISSUE THREAD

**Issue by cl0ne** [jgthms/bulma#793]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.4.2
My **browser** is: Firefox 53

I am sure this issue is **not a duplicate**? Mostly

### Description
Adding `has-addons` class to `field` places `help` elements in the same row with `control`s. Probably I'm using things in a wrong way, if so - correct me, please.

### Steps to Reproduce
Run [JSFiddle](https://jsfiddle.net/n6Lg6czL/1/) and compare positions of help texts

### Expected behavior
Element `.field.has-addons .help` is on a separate row (same as `.field .help`)

### Actual behavior
Element `.field.has-addons .help` is on the same row with sibling `control`s

**Comment by Kayyow** [comment]
I have almost the same problem with a `<label>` tag which isn't positionned above the form `<input>` but inlined.

**Comment by jgthms** [comment]
#640

**Comment by cl0ne** [comment]
Oops, sorry.
