### ISSUE TITLE
Responsive not working

### ISSUE THREAD

**Issue by JacobGunther12** [jgthms/bulma#795]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.2]
My **browser** is: Google Chrome

I am sure this issue is **not a duplicate**? Sort of a duplicate, but not fixed in other issues

### Description

My code is not responsive. I've followed the code on the docs. I don't know what the issue is, but I've included the viewport meta tag but it just makes it look like this:

![image](https://user-images.githubusercontent.com/16949253/27015415-f10edb1a-4ed2-11e7-81cc-8160fc58ab78.png)

Here's my code:

https://hastebin.com/qayotewosi.xml

### Expected behavior

The entire website to be fully responsive.

### Actual behavior

Seems to look half desktop, half mobile.

**Comment by jmoont** [comment]
You need to check how you've coded the nav section. Take a look [here](http://bulma.io/documentation/components/nav/) for an example.

Mistakes I can see are:
- `nav-toggle` class shouldn't be on the `nav` element
- no need for the `<div class="container">` wrapper inside the `nav` element
