### ISSUE TITLE
Do you have a CDN?

### ISSUE THREAD

**Issue by yanisurbis** [jgthms/bulma#8]
I opened an issue cdnjs/cdnjs#6837

**Comment by yanisurbis** [comment]
I opened an issue https://github.com/cdnjs/cdnjs/issues/6837

**Comment by wyze** [comment]
Since Bulma is published to CDN there is this as an alternative: https://npmcdn.com/bulma@0.0.4/css/bulma.min.css

**Comment by jgthms** [comment]
Great idea. I've never heard of npmcdn before.

I'll close this issue when cdnjs implements it as well.

**Comment by inexist3nce** [comment]
There's also [RawGit](https://rawgit.com/):
https://cdn.rawgit.com/jgthms/bulma/master/css/bulma.min.css

**Comment by Kwal** [comment]
Looks like it's up on cdnjs now 👍

https://cdnjs.com/libraries/bulma

**Comment by jgthms** [comment]
Cool. Closing then.

**Comment by dumptyd** [comment]
There's no js file(s) in the cdn. Intentional?

**Comment by jartaud** [comment]
@dumptyd You'll hace to implement your own js. Bulma is css only.

**Comment by dumptyd** [comment]
Okay. Coming from bootstrap, I was trying to get the navbar hamburger work and landed on [this SO answer](https://stackoverflow.com/questions/41137114/im-trying-to-use-hamburger-menu-on-bulma-css-but-it-doesnt-work-what-is-wron) and someone there mentioned about bulma.js, so I thought I was missing something. 😐

**Comment by jartaud** [comment]
Yeah! the SO answer is confusing you. Just toggle is-active class.

**Comment by inexist3nce** [comment]
document.querySelector('.nav-toggle').addEventListener('click', function() {
        document.getElementById('nav-menu').classList.toggle('is-active');
    });

**Comment by amandeepmittal** [comment]
@inexist3nce Raw Git version you mentioned earlier is not working. Any update(s)?

**Comment by inexist3nce** [comment]
@amandeepmittal looks like pointing to the master branch doesn't work anymore

Updated link: https://cdn.rawgit.com/jgthms/bulma/9e1752b5/css/bulma.css

**Comment by amandeepmittal** [comment]
@inexist3nce Thanks! :)
