### ISSUE TITLE
is-grouped is-withicon (disappears)

### ISSUE THREAD

**Issue by brycematheson** [jgthms/bulma#80]
It may very well be because I don't full understand the framework (which I'm absolutely LOVING, btw. Great job), but when I use the following code the font-awesome icon will disappear on hover. Maybe this is by design, but if so, please disregard this. This is just a minor issue.

```
<div class="column is-third">
	  	<p class="control is-withicon is-grouped">
	  	<input class="input" data-validation="time" placeholder="End Time">
	  	<i class="fa fa-clock-o"></i>
	  	<span class="select is-inline">
	  		<select>
	  			<option>AM</option>
	  			<option>PM</option>
	  		</select>
	  	</span>
	  	<i class="fa fa-clock-o"></i>
	  	</p>
	  </div>
```

**Comment by jgthms** [comment]
Sorry, the `is-withicon` has been renamed to `has-icon`.
