### ISSUE TITLE
Help container text length change size of input in horizontal form

### ISSUE THREAD

**Issue by FrancoisH** [jgthms/bulma#800]
Pursuing the issue we got in #715 , I can add this lead to another bug.

Trying to show dynamically my errors into my form, with VeeValidate, I ran into an issue. Depending on the error message, my input field get its width changed by the "help" container.

Here's an example showing the bug... notice I can't use the "is-grouped" on the left field because it put the help on the same line, despite it's what is suggeted by the documentation.

https://codepen.io/francoish/pen/yXJZBW

**Comment by laszlofarkas** [comment]
I ran into the same issue, however the fix is quite simply.
Just adding the following css rule can fix it.
```
.field {
  flex-basis: 0;
}
```
Here is my example:
https://plnkr.co/edit/uGc2nOYNUjoYb5EpN2fD?p=preview
