### ISSUE TITLE
is-selected on bordered table should have border as well

### ISSUE THREAD

**Issue by coussej** [jgthms/bulma#803]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.2]

### Description

The **is-selected** class that was recently introduced for table rows should have a border when the containing table has the **is-bordered** class, otherwise this looks a bit 'off':

![image](https://user-images.githubusercontent.com/9944663/27218735-7f8b58fa-527f-11e7-98e3-b98447e3bbb0.png)

**Comment by jgthms** [comment]
Do you mean on the edges?

**Comment by coussej** [comment]
Yes, sorry if that wasn't clear :-)
