### ISSUE TITLE
Responsive helpers leave a residue inside buttons

### ISSUE THREAD

**Issue by draio** [jgthms/bulma#805]
**Overview of the problem**

This is about the Bulma **CSS framework**
I'm using Bulma version **[0.4.2]**
My **browser** is:  Google Chrome 58 - Microsoft Edge 40

**Description**

Normally with "is-hidden-mobile" (or any other responsive helper) resizing the page the "object" disappears. Instead, inside a button remains a residue space (margin, padding?)

Check it here: https://jsfiddle.net/draio/dk5aq3wt/

**Steps to Reproduce**

```
<a class="button">
  <span class="icon">
    <i class="fa fa-github"></i>
  </span>
 <span class="is-hidden-mobile">GitHub</span>
</a>
```
**Expected behavior**
I expect a square button 

**Actual behavior**
A rectangular button with a non-centered icon

**Comment by jgthms** [comment]
This is expected, as `.icon` here is not the last child, which it needs to remove that margin.

I'd rather do:

```
<a class="button is-hidden-tablet">
  <span class="icon">
    <i class="fa fa-github"></i>
  </span>
</a>

<a class="button is-hidden-mobile">
  <span class="icon">
    <i class="fa fa-github"></i>
  </span>
 <span>GitHub</span>
</a>
```
