### ISSUE TITLE
Ratio classes on media object image, makes the image disappear

### ISSUE THREAD

**Issue by juanmnl** [jgthms/bulma#81]
Hi! *There was a similar issue, but it was closed and the problem persists.*
I'm starting with this framework (awesome btw, and will try to contribute a lot) but i had this problem yesterday with the 0.0.13 minified and no min. downloadable versions. 
The fixed scale helpers worked (ex:`is-128x128`) but the ratio one's (ex:`is-square`) makes the image disappear on the media object.
My image was 256x256, so i created the class which fixed the issue.
```css
.image.is-256x256 {
  height: 256px;
  width: 256px;
}
```
I'll keep digging while exploring the framework :)

**Comment by juanmnl** [comment]
tested 0.0.14 min and non min, the issue persists.

**Comment by rohannair** [comment]
This seems to be an issue with flexbox, where absolutely positioned images within an flexbox layout have a height and width of 0px: http://codepen.io/rohan10/pen/xZBYBO

**Comment by jgthms** [comment]
Nice catch @rohannair. It's a weird bug really.

**Comment by ChuckJHardy** [comment]
It appears this issue continues within [media objects](http://bulma.io/documentation/components/media-object).

![screenshot 2016-07-17 16 45 21](https://cloud.githubusercontent.com/assets/391016/16901506/ef8a0a96-4c3d-11e6-986f-e38bde41f16c.png)

**Comment by Francismori7** [comment]
Still present as of now.

**Comment by zanematthew** [comment]
Any reason why we can't re-open this issue?

**Comment by cryoten** [comment]
Still present when using responsive ratios such as `is-2by3`, but I've only found it in media objects.

**Comment by freitzzz** [comment]
Any update on this?

**Comment by rafed123** [comment]
Come on... this needs to be fixed

**Comment by PsychoCalpis** [comment]
Can confirm the bug is still here.
My fix is to add `width: 100%` on the `.media-left or .media-right` class.

**Comment by philippeluickx** [comment]
Had the same issue with a simple <figure> and <img> object inside flex. Adding has-fullwidth class solves the issue.
