### ISSUE TITLE
Issues with `findColorInvert` and `$color-invert`

### ISSUE THREAD

**Issue by stentas** [jgthms/bulma#810]
### Overview of the problem

This is about the Bulma **CSS framework

### Description
I keep getting the errors:
```
Error: Undefined variable: "$color-invert".
        on line 99 of elements/button.sass
        from line 35 of bulma.sass
```

and 

```
Error: $color: "findColorInvert(#00d1b2)" is not a color for `rgba'
        on line 77 of layout/hero.sass
        from line 52 of bulma.sass
```

I've replaced minireset.sass with the latest version of Normalize. 
But that shouldn't affect anything.

### Steps to Reproduce

1. Download and unpack Bulma into a WP project
2. Save outputfile.

### Expected behavior

No errors

### Actual behavior

Getting errors as stated above

**Comment by samayo** [comment]
I just installed a fresh copy of bulma and not even 5 minutes into it, I got the same error. It seems with every release there is a regression of some kind. This lib has more holes than a Swiss cheese

**Comment by samayo** [comment]
@stentas I found the issue. I reverted back to 4.1 and I found the same error, so after some tinkering I was able to make it work by adding `@import "sass/utilities/functions.sass"` as do: 
```
@import "sass/utilities/functions.sass"
@import "sass/utilities/variables.sass"
@import "sass/utilities/mixins.sass"
@import "sass/grid/columns.sass"
@import "sass/layout/hero.sass"
@import "sass/layout/section.sass"
@import "sass/layout/footer.sass" 
```

And I was able to compiles the sass file into css via 
```bash
sass ./bulma/bulma.sass ./css/bulma.css
```

So you have to add `functions.sass` file which upon inspecting contains the function `findColorInvert()` which is causing the error: 

```
@function findColorInvert($color)
  @if (colorLuminance($color) > 0.55)
    @return rgba(#000, 0.7)
  @else
    @return #fff
```

**Comment by kyotoprotokollet** [comment]
I got this problem as well. @samayo suggestion works well. The problem is of course that you can't follow the docs and just set the variables before importing Bulma, since some variables use functions that are not available until importing Bulma.
