### ISSUE TITLE
Columns do not work inside panel-block

### ISSUE THREAD

**Issue by igorsantos07** [jgthms/bulma#812]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.2]
My **browser** is: Chrome 59
I am sure this issue is **not a duplicate**

### Description
As `.panel-block` is `flex`, we're not allowed to add a `.columns` child, as the `.column` elements would get funky.

### Steps to Reproduce
```html
<div class="panel-block">
    <div class="columns is-mobile">
        <div class="column">first column</div>
        <div class="column is-narrow">narrow second column</div>
    </div>
</div>
```
### Expected behavior
![screenshot_012](https://user-images.githubusercontent.com/532299/27297777-a13b21ea-54fc-11e7-89bf-7e68c18c1cef.png)
Achieved by adding a custom class to that `.panel-block` and setting it to `display: block`

### Actual behavior
![screenshot_011](https://user-images.githubusercontent.com/532299/27297754-8e9d4ee6-54fc-11e7-95eb-5e67499841c2.png)

**Comment by tjad** [comment]
Bump!

This is quite a limitation. - or what are the alternatives for  creating layouts within `.panel-block`s?

**Comment by tjad** [comment]
I see.. Working with columns inside the panel-block require explicit sizes to be set 
e.g  `is-1`, `is-2` etc

**Comment by tjad** [comment]
Further looked at this, it can be reopened, I reproduce the @igorsantos07's result with different classes. 
I was experiencing symptoms of my content not being restricted to the column width and stretching them.

The following `slim` reproduces problem when placed in `.panel-block`.

.columns
  .column.is-6
     p Hello 
  .column.is-6
     p World
