### ISSUE TITLE
Missing -fullhd version of column widths

### ISSUE THREAD

**Issue by Saboteur777** [jgthms/bulma#814]
### Overview of the problem

This is about the Bulma **CSS framework** **and** Bulma **Docs**
I'm using Bulma **version** 0.4.2

### Description

According to the [documentation](http://bulma.io/documentation/overview/responsiveness/) there is a **fullhd** modifier, but there are no .is-X-fullhd classes. Is that intentional? 

### Expected behavior

Just like there are classes for -mobile, -tablet, -desktop and -widescreen - according to this logic - there should be -fullhd equivalents of these, like e.g.: is-6-fullhd, which kicks in from 1384px.

**Comment by jgthms** [comment]
Merged, thanks!
