### ISSUE TITLE
delete modifiers do not work

### ISSUE THREAD

**Issue by PaddyMurphy** [jgthms/bulma#816]
### Overview of the problem

This is about the Bulma **CSS framework** and the documentation

I'm using Bulma **version** [0.4.2]
My **browser** is: latest versions of chrome, safari, and firefox (tested in all 3)

I am sure this issue is **not a duplicate**? I searched the existing issues and PRs 

### Description

The delete modifiers .is-small, .is-medium, .is-large do not work. All display in the default size.

### Steps to Reproduce

Look at the documentation page http://bulma.io/documentation/elements/delete/

I first noticed on a personal project and fixed as shown in the screenshots below

### Actual behavior

<img width="594" alt="bulma delete before" src="https://user-images.githubusercontent.com/699732/27404764-d813f43c-5694-11e7-8aea-4fcb723d5dce.png">

### Expected behavior

<img width="570" alt="bulma delete after" src="https://user-images.githubusercontent.com/699732/27404775-e228dfa0-5694-11e7-8c39-c7d542789294.png">

**Comment by rafaelpimpa** [comment]
Duplicate: https://github.com/jgthms/bulma/issues/781
