### ISSUE TITLE
"height: auto" overrides default height for audio elements, setting it to zero

### ISSUE THREAD

**Issue by DAreRodz** [jgthms/bulma#819]
### Overview of the problem

I'm using Bulma **version** 0.3.0
My **browser** is: Google Chrome Version 59.0.3071.109 (Official Build) (64-bit)

### Description

When the property height is set to auto for an audio element, the height of that element becomes zero while browser renders it with a default height, so that it appears cut or above other html elements. Removing "height: auto;" for audio tags solves the problem.

### Steps to Reproduce

1. Add an audio element inside a bulma content element.

### Expected behavior

The audio element should have the height assigned by default (user agent stylesheet).

### Actual behavior

The audio element appears cut or above other html elements.

**Image 1:**

![screen shot 2017-06-27 at 12 14 07](https://user-images.githubusercontent.com/6917969/27585547-15b29ab2-5b3d-11e7-977b-67eda00daa34.png)

**Image 2:**

![screen shot 2017-06-27 at 13 30 42](https://user-images.githubusercontent.com/6917969/27585548-15c8961e-5b3d-11e7-9941-0068449fae99.png)

**Comment by dancollins84** [comment]
This issue does not appear to be fixed.  The CSS still sets `height: auto;` for the `audio` tag.  As I understand it, this is a problem because `audio` has no height property.  For some reason, this doesn't make a difference in Firefox or Safari, but it breaks in Chrome.

**Comment by mcade** [comment]
Are you going to merge this fix anytime soon @jgthms ?
