### ISSUE TITLE
New classes for dropdown with bulma?

### ISSUE THREAD

**Issue by RuinSain** [jgthms/bulma#829]
This is about the Bulma **CSS framework** 

### Overview of the Question

I saw on the site (bulma.io), a new design in the layout of the site, and i noticed 3 new(at least for me) classes. **has-dropdown**, **navbar-dropdown** and **is-hoverable**. are they going to be added as an official classes to the framework in the next release?

Thanks.

**Comment by jgthms** [comment]
Coming in `0.5.0`. Preview the docs here: http://bulma.io/documentation/components/navbar/

**Comment by RuinSain** [comment]
Thanks bro!
