### ISSUE TITLE
.is-offset-x does not work using RawGit CDN

### ISSUE THREAD

**Issue by SantiGraviano** [jgthms/bulma#83]
The .is-offset-x does not work using the CDN that is offered in the documentation site.

RawGit CDN: https://cdn.rawgit.com/jgthms/bulma/master/css/bulma.min.css

I have tested using my own /css/bulma.css link, and works

**Comment by jgthms** [comment]
Yeah, the RawGit minified CSS seems to have issues. I might remove that CDN link, or use an alternative.

**Comment by juanmnl** [comment]
Haven't played with it yet, but maybe take a look at [npmcdn](https://npmcdn.com/) for a cdn alternative @jgthms

**Comment by SantiGraviano** [comment]
Thanks guys I'll use an alternative.
