### ISSUE TITLE
label and is-hidden-mobile clasess bug

### ISSUE THREAD

**Issue by winuxue** [jgthms/bulma#831]
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.4.2
My **browser** is: Firefox

### Description
If you add the clases **label** and **is-hidden-mobile** to the same <label> the css rule **display:block;** from **label** overrides the **display: none** from **is-hidden-mobile** when you are in a mobile browser or resize your desktop one.
See:
![bulma](https://user-images.githubusercontent.com/15930014/27811786-5fb744ea-602f-11e7-93b3-4db64f350a5a.PNG)

**Comment by jgthms** [comment]
That's not possible. Hiding helpers have always had `!important` to get priority. See: https://github.com/jgthms/bulma/blob/master/sass/base/helpers.sass#L76
