### ISSUE TITLE
The recommended way of modifying default styles without overriding on updates

### ISSUE THREAD

**Issue by dikaio** [jgthms/bulma#834]
Is there a recommended way of changing the default styles other than modifying the **_variables.scss** file? I'm trying to avoid overwriting modified styles on each Bulma update.

Thanks.

**Comment by skbolton** [comment]
It's mentioned in the docs here http://bulma.io/documentation/overview/customize/ you pretty much import the variables into your CSS and change them. Then import Vilma. Since it's your own sass file it will overwrite the Vilma supplied colors

**Comment by dikaio** [comment]
perfect thanks @skbolton.
