### ISSUE TITLE
Image overflowing tile in Docs

### ISSUE THREAD

**Issue by tjkohli** [jgthms/bulma#836]
I found a Bug in the Docs.
It is on this page:
http://bulma.io/documentation/grid/tiles/
It seems to happen only in Safari desktop, 10.1.1.

### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.4.3]
My **browser** is: Safari Mac 10.1.1 on macOS Sierra
_Edit: @SkaterDad reports it happens in IE11 as well_

I am sure this issue is **not a duplicate**

### Description

The image in the blue sample overflows the tile. Here is a screenshot:

![screenshot of Bulma docs bug](http://tjkoh.li/mC6b4/5Vh6elJQ+)

**Comment by SkaterDad** [comment]
This also happens in IE11.

**Comment by alqu** [comment]
Same here. IE11 - overflow.

**Comment by rafaelpimpa** [comment]
I think it's because he removed the ``img { height: auto }`` from minireset.sass

**Comment by pimmey** [comment]
+1
