### ISSUE TITLE
Meteor

### ISSUE THREAD

**Issue by infacq** [jgthms/bulma#84]
this is great plugin but can make it available as `meteor` package?

**Comment by arthurkirsz** [comment]
You can simply import the npm package and use it inside your meteor app.
I suggest you check https://github.com/meteorhacks/npm for easy import of you npm package, or wait for the Meteor 1.3 Realase from MDG that will rely on npm modules rather than meteor packages :)

**Comment by rclai** [comment]
Actually, in Meteor 1.2 and below using `meteorhacks:npm` is not enough because it only makes NPMs work on the server only.

**Comment by arthurkirsz** [comment]
Arf... I guess the only simple alternative at the moment is  to use the CDN ?

**Comment by jgthms** [comment]
Bulma is just one CSS file really (unless you want to customise the variables).

**Comment by rclai** [comment]
Yea or just copy and paste it.

**Comment by infacq** [comment]
thanks
