### ISSUE TITLE
Responsive images with ratios is not working

### ISSUE THREAD

**Issue by pritam1605** [jgthms/bulma#840]
<div class="media-left">
      <figure class="image is-2by1">
	   <img src="http://bulma.io/images/placeholders/128x128.png" alt="Image">
     </figure>
</div>
As per the docs http://bulma.io/documentation/elements/image/, image is-2by1 shoud display a 640X320 image. It isn't dsplaying any image.

**Comment by raulfdm** [comment]
The problem here is by add a container/wrapper.

Did some tests [here](https://codepen.io/anon/pen/KbEqOK) an as you can see at, when we wrap and define into a div (or whatever container), it'll fit.
