### ISSUE TITLE
Container as direct child of navbar moves navbar-menu below navbar-brand

### ISSUE THREAD

**Issue by czamp** [jgthms/bulma#841]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.3]

My **browser** is: Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0.1 (64-bit)

I am sure this issue is **not a duplicate**

### Description

Placing `container`  as a direct child of `navbar` and the parent of `navbar-brand` and `navbar-menu` causes  `navbar-menu` to appear below `navbar-brand`.

### Steps to Reproduce

[See Codepen](https://codepen.io/czamp/pen/bRxmjE)

#### No Container
![navbar-no-container](https://user-images.githubusercontent.com/26906182/27971394-6a5bf2ee-6307-11e7-97f4-44b8d8bac680.png)
```
<nav class="navbar">
    <div class="navbar-brand">
        ...
    </div>
    <div class="navbar-menu">
        ...
    </div>
</nav>
```
---

#### Container
![navbar-with-container](https://user-images.githubusercontent.com/26906182/27971402-704c507c-6307-11e7-88b0-977c931559d1.png)
```
<nav class="navbar">
    <div class="container">
        <div class="navbar-brand">
            ...
        </div>
        <div class="navbar-menu">
          ...
        </div>
    </div>
</nav>
```
---

#### Container is-fluid
![navbar-with-container-is-fluid](https://user-images.githubusercontent.com/26906182/27975812-c34ec884-6318-11e7-8270-1829a98eccb6.png)

```
<nav class="navbar">
    <div class="container is-fluid">
        <div class="navbar-brand">
            ...
        </div>
        <div class="navbar-menu">
          ...
        </div>
    </div>
</nav>
```

### Expected behavior

`navbar-brand` and `navbar-menu` are displayed left to right in a `container`

### Actual behavior

`navbar-menu` is displayed below `navbar-brand`  in a `container`

**Comment by koddr** [comment]
+1 after update bulma to 0.4.3 version `.container` in `<nav>` behaves strangely.

**Comment by lent** [comment]
maybe nav.navbar>.container needs another display: flex?

**Comment by VizuaaLOG** [comment]
The navbar on the docs puts the container on the outside. Maybe the navbar no longer supports a container inside?

```html
<div class="container">
    <nav class="navbar">
        ...
    </nav>
</div>
```

**Comment by de-raaf-media** [comment]
Changing class="navbar" to class="nav" fixed it for me. But nav will be deprecated.

**Comment by rafaelpimpa** [comment]
Using ``is-flex`` on the ``.container`` will have the mobile menu button to keep in the left side.
Adding the ``.container`` to the ``.navbar`` itself works good apparently:

```html
<header class="navbar container"></header>
```

**Comment by almasaeed2010** [comment]
Not the ideal solution but it works if you are using sass:

html
```html
<nav class="navbar">
  <div class="container">
     <!-- reset of navbar here -->
  </div>
</nav>
```

scss
```sass
@import "node_modules/bulma/bulma"
.navbar > .container { @extends .navabr }
```

There is probably a simpler and more eloquent solution but I'll wait on the maintainers to support `.container` before I write too many unnecessary lines.

Great framework by the way! Love it <3

Thanks!
