### ISSUE TITLE
Adding modifiers in navbar

### ISSUE THREAD

**Issue by ajitid** [jgthms/bulma#842]
It is about the docs.
I need help; this is a question.
Bulma: 0.4.3

I'm new to CSS frameworks maybe that is the reason, but I was able to use modifiers in `nav` (`is-tab` to be specific) but I'm not able to figure out how to use it in new `navbar` introduced in 0.4.3.

**Comment by czamp** [comment]
Poking through [navbar.sass](https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass), it appears that the two modifiers for `nav`, including `is-tab` and `has-shadow`, do not modify any element of the `navbar`.

You're not using the modifiers wrong, they just don't exist for `navbar`.

**Comment by connectkushal** [comment]
thnx !

**Comment by ajitid** [comment]
@jgthms please add these modifiers into docs too
