### ISSUE TITLE
Navbar dropdown : how to hide arrow ?

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#848]
Hi,

thank you to dropdown menu addition.
I have a question: how to hide the arrow in case I just want an icon as dropdown label ?

Regards,

**Comment by moalazzam** [comment]
just use navbar-item class instead of navbar-link

**Comment by Wikiki** [comment]
Perfect !

Thank you

**Comment by acidjazz** [comment]
I actually found that changing it from link to item messes with a bunch of other stuff like hover/etc.

I noticed [this](https://github.com/jgthms/bulma/blob/ceae8a675edad50591fc0ad62db1278286d8d6aa/sass/components/navbar.sass#L201
), but it doesn't seem to work:

```sass
.navbar-link:not(.is-arrowless)
```

**Comment by acidjazz** [comment]
Never-mind, I noticed from the PR date compared to the last release that this doesn't exist yet. Much better solution though!

**Comment by acidjazz** [comment]
temporary solution until `.is-arrowless` pr #1919 is gets in a release!

```stylus
.navbar-link.is-arrowless
  padding-right 0.75rem
  &::after
    border 0px solid transparent
```
