### ISSUE TITLE
Mix and Match

### ISSUE THREAD

**Issue by datwheat** [jgthms/bulma#85]
Hello,

As we all love bulma for its beautiful components, It's grid system is lacking. With nesting quirks and lack of offsets it makes it hard to build a great ui. I'm not sure how long it'll take to develop the system, but in the mean time could bulma decouple its grid in hopes for switching another grid like Jeet or Milligram'
s sass grid? That would be awesome. Let's say I were to swap out the grid sass files from milligram's to bulma's and built a version from that. Do you think it would work well at this point?

Thanks

**Comment by jgthms** [comment]
What nesting quirks are you encountering?

Also: there are column offsets already.

**Comment by datwheat** [comment]
oh wow I must've just missed the offset update! Sweet!
