### ISSUE TITLE
Incorrect Container Sizing Just Before Breakpoints

### ISSUE THREAD

**Issue by matthewpull** [jgthms/bulma#851]
I believe that this is a bug with Bulma, the CSS framework, although it is also present on the Bulma Docs site (as this uses the Bulma CSS framework).

### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.3]
My **browser** is: Chrome (also tested on Firefox)
I am sure this issue is **not a duplicate** (I have looked and cannot find it mentioned)

### Description

This issue causes the width of a container to be incorrect at values just before each breakpoint. I believe that this is due to the presence of the scrollbar, as the issue does not appear to happen on Chrome Canary with the Overlay Scrollbars flag enabled. The easiest way to describe this issue is to show it you you:

![bulma io-documentation-overview-start-](https://user-images.githubusercontent.com/13154300/27998520-cb3abfd4-6508-11e7-9d44-17618f82ba95.png)
Notice the margin either side of the containers (in particular with the Carbon ad). In this first image everything is working as intended, with equal space on each side. However, as we reduce the width closer to the breakpoint...

![bulma io-documentation-overview-start- 1](https://user-images.githubusercontent.com/13154300/27998535-005f0d0a-6509-11e7-8410-448a776bc8aa.png)
The margin is now much greater on the left than the right. At a certain point (when the margin either side is approximately one scrollbar width wide), the margin stops decreasing on the left side but keeps decreasing on the right side.

It is worth noting the top menu decreases equally on each side as normal and is not affected by this issue. I have played around with the CSS but am not skilled enough to work out why this is.

When the margin reaches zero on the right size (e.g. in the example above, when the scrollbar touches the Carbon ad with zero gap) that is when the breakpoint occurs.

### Steps to Reproduce (only works on platforms with scrollbars enabled)

1. Go the to any Bulma site (e.g. the [Bulma docs site](http://bulma.io/documentation/overview/start/))
2. Reduce the width slowly until just before you reach a breakpoint (e.g. reduce slowly from 1230px until 1192px)
3. At approximately 24 pixels before the breakpoint (e.g. 1216px in this example) notice that the left margin stops decreasing while the right margin continues to decrease.

### Expected behavior

Both margins should be equal at all times

### Actual behavior

The left margin stops decreasing just before the breakpoint, meaning that container content is not horizontally aligned.

**Comment by delphinas** [comment]
Anyone fixed it yet? I have similar issue

**Comment by davidrthorn** [comment]
I'm having this issue with a container for my app
