### ISSUE TITLE
comment is still 0.4.2, @charset should be very first line

### ISSUE THREAD

**Issue by rowild** [jgthms/bulma#852]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.3]

The comment in bulma.sass is still "0.4.2", even though it should be "0.4.3" according to package.json and your website :-)

Also, a "@charset "utf-8" should always be the very first line, even before a comment...

**Comment by suth** [comment]
If you look at the Deploy 0.4.2 commit there are a few other files that need to be updated as well, but the comment in bulma.sass was especially annoying as I was trying to debug an issue related to #837 when I had to go on a rabbit trail of why it looked like my Bulma version wasn't up to date.
