### ISSUE TITLE
progress element inside level component not visible

### ISSUE THREAD

**Issue by bluematt** [jgthms/bulma#853]
### Overview of the problem

- Bulma **CSS framework**
- Bulma **version** [0.4.3]
- Observed in: Safari (10.1.1), Chrome (59.0.3071.115)

### Description

When placing a `progress` element inside a `level` component, the `progress` element disappears on larger screen sizes (>768px).

### Steps to Reproduce

https://jsfiddle.net/bluematt/62gt1v6d/

### Expected behaviour

The `progress` element to display.

### Actual behaviour

The `progress` element does not display.

**Comment by rafa-acioly** [comment]
somehow the `width` property on larger screen are been ignored, if you remove the `width` property the progress show up again.

![print](http://www.putimg.net/pictures/1499714344.png)

**Comment by sarneeh** [comment]
Just stumbled upon this issue. Fixed it customly with columns. It would be cool to fix this issue tho :)

**Comment by mostafa-asg** [comment]
I encountered the same problem :-(
Bulma version: v0.9.0

**Comment by miloszkozlowski** [comment]
Same issue here. Still not fixed

**Comment by Hungnguyen720** [comment]
just encountered this problem.
