### ISSUE TITLE
Button states loading and inverted are not readable

### ISSUE THREAD

**Issue by cesasol** [jgthms/bulma#854]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.3]

I am sure this issue is **not a duplicate**

### Description

When combining the `is-loading` whith `is-inverted` the color buttons are not readable 

### Steps to Reproduce

Using a combination of `button is-[color] is-loading is-inverted`

### Expected behavior

Readable buttons using `button is-[color] is-loading is-inverted`

### Actual behavior

![screenshot-2017-7-10 starter](https://user-images.githubusercontent.com/3846473/28035323-dddc8638-6579-11e7-8b62-8f4ef8f6cb18.png)

**Comment by jwahdatehagh** [comment]
+1 May i  write a PR?
