### ISSUE TITLE
Suggestion: Vertical Rhythm

### ISSUE THREAD

**Issue by cesasol** [jgthms/bulma#855]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Right now my friends and I are working on a fork of bulma with Vertical Rhythm across all the framework, we are using strict rules from editorial design, the [ritmo](https://ritmo.marzeelabs.org/) framework and [modular scale](https://github.com/modularscale/modularscale-sass) function to accomplish this.

Knowing that bulma does not depend on any other framework I want to know if this fork that we are working on could be merged inside bulma itself or keep it as a related project.

**Comment by jgthms** [comment]
While I like the idea of vertical rhythm, I believe it's too restrictive to be merged into the Bulma core. Feel free to add it to the Readme as a related project though.

**Comment by cmer** [comment]
@cesasol was there ever progress made on this? Curious how I could implement it on my Bulma site.

**Comment by cesasol** [comment]
It was to difficult to maintain with any change done upstream. I ended up dropping bulma all together and go for tailwind.

Bulma it's great but does not follow the idea of vertical rhythm in the mathematical sense and trying to impose it was a fool's errand.
