### ISSUE TITLE
Burger doesn't dropdown as expected, and docs don't explain any necessary javascript

### ISSUE THREAD

**Issue by jondoesntgit** [jgthms/bulma#856]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** [0.4.3]
My **browser** is: Firefox

### Description

I'm building a website using Bulma, and I haven't included any javascript files. I'm loading Bulma using cdnjs. I'm having trouble getting the burger icon to expand the target `navbar-menu`. 

The docs mention that you can expand by adding or removing the `is-active` attribute. I can do this using jQuery, but I'm wondering what the "Bulmanic" way of achieving this. The docs are a bit silent in this regard.

### Steps to Reproduce

Check out [this codepen](https://codepen.io/jamwheeler/pen/LLXMLV). 

### Expected behavior

When I copy the example code provided by the `navbar` docs, the burger icon does nothing when clicked. In the example code on the Bulma website for the `navbar`, the burger icon expands the associated data-target.

### Actual behavior

I'm expecting the burger icon to expand the associated data-target when clicked. Just like the website.

**Comment by inseldesign** [comment]
Maybe you will find your answer in here: https://github.com/jgthms/bulma/issues/238

There is a "js-way" or a "css-way" I guess.

**Comment by jgthms** [comment]
Yes this has already been discussed. Bulma doesn't provide any Javascript, since it's CSS only. I could add a JS snippet as an example of how to toggle the nav-menu.

**Comment by RuinSain** [comment]
Look at this, i made it now to let you see how it works. copy it.
[Bulma hamburger](https://jsbin.com/harafeluhe/edit?html,output)

**Comment by cyprusglobe** [comment]
@igthms You might look at this way too.

https://jsbin.com/yetuwaloki/edit?html,css,js,output

**Comment by mekkli** [comment]
If you are using JQuery try this
```javascript
  // Close mobile & tablet menu on item click
  $('.navbar-item').each(function(e) {
    $(this).click(function(){
      if($('#navbar-burger-id').hasClass('is-active')){
        $('#navbar-burger-id').removeClass('is-active');
        $('#navbar-menu-id').removeClass('is-active');
      }
    });
  });

  // Open or Close mobile & tablet menu
  $('#navbar-burger-id').click(function () {
    if($('#navbar-burger-id').hasClass('is-active')){
      $('#navbar-burger-id').removeClass('is-active');
      $('#navbar-menu-id').removeClass('is-active');
    }else {
      $('#navbar-burger-id').addClass('is-active');
      $('#navbar-menu-id').addClass('is-active');
    }
  });
```
With the following HTML (Using https://fontawesome.com/ like `<i class="fa [...]`)
```html
  <nav id="navMenu" class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="#"><i class="fas fa-home fa-lg"></i></a>
        <a class="navbar-item is-hidden-desktop" href="#where-hours"><i class="far fa-clock fa-lg"></i></a>

        <div id="navbar-burger-id" class="navbar-burger">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id="navbar-menu-id" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="#section-1">First Section</a>
          <a class="navbar-item" href="#section-2">Second Section</a>
          <a class="navbar-item" href="#section-3">Third Section</a>
        </div>
        <div class="navbar-end">
          <a class="navbar-item is-hidden-touch" href="#where-section"><i class="far fa-clock fa-lg"></i></a>
        </div>
      </div>
    </div>
  </nav>
```
Hope it'll help :smile: 
Peace

**Comment by knowfahad** [comment]
This works like a charm. Thank you.
It's a bummer that bulma doesn't provide any documentation on this navbar burger issue

> Look at this, i made it now to let you see how it works. copy it.
> [Bulma hamburger](https://jsbin.com/harafeluhe/edit?html,output)

adding this to the navbar burger div makes it work

`onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');"`

**Comment by white-gecko** [comment]
> Maybe you will find your answer in here: #238
> 
> There is a "js-way" or a "css-way" I guess.

Is there really a css-way for the bulma nav menu that wokrs on mobile? So far I couldn't find one. In general I know about the CSS only drop down checkbox trick/hack (https://tutorialzine.com/2015/08/quick-tip-css-only-dropdowns-with-the-checkbox-hack) but so far I did not manage to use it with the bulma nav.

**Comment by Chompas** [comment]
Is there a way to make the burger menu to close after clicking on an item inside of it?

**Comment by lastraj** [comment]
Using Vue you can initialize a data variable "isOpen" default to false
```javascript
data(){  
    return {
        isOpen: false
    }
}
```
 then modify isOpen on a @click method like this 
```html
<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" @click="isOpen = !isOpen">

```
So now you can use class bindings to set a class based on the value of isOpen, you need to do this in the burger and menu.

 ```html
<div id="navbarMenuHeroC" class="navbar-menu" @click="isOpen = !isOpen">
```
  
burger
 ```html
<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" v-bind:class="{ is-active: isOpen }">
 ```

menu
 ```html
<div id="navbarBasicExample" class="navbar-menu" v-bind:class="{ is-active: isOpen }">
 ```
I haven't tested the code but you can get the idea @Chompas

**Comment by rogeriodeoliveira** [comment]
@lastraj It work fine with NuxtJs

**Comment by xenoterracide** [comment]
I missed is-active entirely, and then that it has to be on both navbar-burger and navbar-menu. I actually would speculate that it would be better to have the example code in a perma-state of `is-active`, because then resizing your window will make the burger in an open or not open state, and comment (inline in the code) that it needs to be toggled via javascript.

**Comment by vanucci** [comment]
@Chompas Did you manage to get it to close if clicking on another item?
I tried @lastrafda solution but was unable to achieve the desired effect

**Comment by smusman437** [comment]
for reactjs it's work fine
import React, { useState } from "react";

export default function Navbarr() {
  const [isActive, setisActive] = useState(false);
  return (
    <div>
      <nav
        className="navbar is-primary"
        role="navigation"
        aria-label="main navigation"
      >
        <div className="navbar-brand">
          <a className="navbar-item" href="https://bulma.io">
            <i
              class="fas fa-address-card is-size-1"
              width="112"
              height="28"
            ></i>
          </a>

          <a
            role="button"
            className={`navbar-burger burger${isActive ? "is-active" : ""}`}
            aria-label="menu"
            aria-expanded="false"
            data-target="navbarBasicExample"
            onClick={() => setisActive(!isActive)}
          >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div
          id="navbarBasicExample"
          className={`navbar-menu${isActive ? "is-active" : ""}`}
        >
          <div className="navbar-start">
            <a className="navbar-item">Home</a>

            <a className="navbar-item">Documentation</a>
          </div>
        </div>
      </nav>
    </div>
  );
}

**Comment by samg11** [comment]
> This works like a charm. Thank you.
> It's a bummer that bulma doesn't provide any documentation on this navbar burger issue
> 
> > Look at this, i made it now to let you see how it works. copy it.
> > [Bulma hamburger](https://jsbin.com/harafeluhe/edit?html,output)
> 
> adding this to the navbar burger div makes it work
> 
> `onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');"`

Thanks you so much, very helpful
