### ISSUE TITLE
New navbar dropdown is not working

### ISSUE THREAD

**Issue by jSayal** [jgthms/bulma#857]
Is it a bug/feature/question or do you need help?

### Overview of the problem
New navbar dropdown is not working

 This is about the Bulma 0..4.3 CSS framework**
 I'm using Bulma **version0.4.3** [x.x.x] -->
My **browser** is: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### Description

Description of the bug, enhancement, or question
I copy pasted the code from bulma docs for new navbar and it does not seem to work. Please see code below

Check the following jsbin for reproducing error
[https://jsbin.com/lamavipiwe/edit?html,output]

**Comment by jSayal** [comment]
I figured it out 
html {width: 100%; height: 100%}
body {width: 100%; height: 100%}

and it will work.

**Comment by cringer** [comment]
You have to make sure to have some page content.  If your adding to a page with content then you'd likely never run into this.  If just testing use the hero element as it shows in the docs.

```
<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      Documentation
    </p>
    <p class="subtitle">
      Everything you need to <strong>create a website</strong> with Bulma
    </p>
  </div>
</section>
```
