### ISSUE TITLE
JavaScript plugins 

### ISSUE THREAD

**Issue by iiivanm** [jgthms/bulma#86]
Are there plans to adding some js plugins? that would be really awesome.

**Comment by 3noch** [comment]
As long as they totally optional.

**Comment by mschinis** [comment]
Short answer, yes! I'm working on creating a set of es6 add-ons for bulma with zero dependencies so that they're lightweight. Feel free to get in touch if you want to contribute!

**Comment by mschinis** [comment]
And, yes they will be totally optional. Don't want to force users to add extra dependencies unless they want to

**Comment by joaoBeno** [comment]
Hello, I want to help with the plugins!

**Comment by mtt87** [comment]
+1 @mschinis happy to help!

**Comment by mschinis** [comment]
Cool. Anyone interested, feel free to email me through my public profile email and I'll get back to you super soon!

**Comment by tychota** [comment]
I'm working on a react version of bulma here. It would be self sufficient (a css for typography and reset and a group of react component with Radium inline style).
No ETA for now.

https://github.com/tychota/yamcha
Hope it can interest someone else.

**Comment by jgthms** [comment]
@tychota :joy: Love the project name!

**Comment by tychota** [comment]
@jgthms I tried to keep on the dragon balls theme !

**Comment by fabriciointerama** [comment]
This was a request from Feb.. is there any news about this at this time?

**Comment by KhaledElAnsari** [comment]
@mschinis I'd like to help :D, and what you want to call the plugin? I bit it's Vegeta.js :D

**Comment by AlgusDark** [comment]
I started a react components for Bulma: http://bloomer.js.org 
The docs are made with bloomer,  docs aren't finished, but library is.
