### ISSUE TITLE
Fullheight layout with navbar and side menu

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#860]
Hi,

What is the best way to create a fullheight layout including :

```

- top navbar
- Side menu with vertical scroll
- Right page content with independent scroll

```

I try ta get something like this:
![Fullheight Layout](https://img15.hostingpics.net/pics/184254ScreenShot20170712at171043.png)

**How to manage it ?**
- Using a fullheight Hero with head containing navbar and body containing 2 columns ? (I tried but columns are not well sized)
- Using multiline columns ?

**How can I fix the navbar always on top ?**

**How to manage side menu on desktop ?**
The burger icon is linked to menu into navbar by default
I would like to have an "off-screen" like menu on mobile.

Regards

**Comment by rafaelpimpa** [comment]
Take a look https://jsfiddle.net/rafaelpimpa/uq2pkb0r/

**Comment by Wikiki** [comment]
Hi @rafaelpimpa ,

thanks for your proposal. But this solution is not responsive.
How can I use bulma elements, components, layouts to manage it keeping in mind the flexbox approach and responsiveness ?

**Comment by rafaelpimpa** [comment]
Why isn't that responsive? You just have to hide the sidebar when it's < tablet and add a button to show it (probably use the same burger in the nav).

**Comment by Wikiki** [comment]
Hi @rafaelpimpa 

I mean it's not using defined helpers provided by Bulma for responsiveness.
I would like to avoid defining new behavior, styles, and use if possible existing bulma's helpers
(is-hidden-mobile, columns, navbar, is-fullheight, ...)

Regards

**Comment by ckizer** [comment]
I'd love the see a working JS Fiddle link for this example.

**Comment by pankajsanam** [comment]
This is something that I need as well.

**Comment by Wikiki** [comment]
Hi,

find here a basic layout. It's not fully tested (especially for mobile display) but it's a start if someone wants to improve it.

https://codepen.io/wikiki/pen/OjdNKM

Regards

**Comment by khaledh** [comment]
I think this is such a common layout for web apps that it's worth adding some support for it out of the box. The main missing piece is `is-fullheight` for columns (which currently works only for hero). Adding ability to invert colors of menus (and other components) would be nice.

**Comment by wjbeckett** [comment]
I'd love this. Also the ability to move elements to the right and pin them at the top.
I have created a Bulma Blog but I like my sidebar on the right. I used the menu class but had to wrap it in multiple columns to keep it on the right which adds margins to the page.

**Comment by vbugarsk** [comment]
@Wikiki : your codepen sidebar works great, but unfortunatelly not on IE11 (no scrolling), Anyone has idea how to make it work on IE11 ?

**Comment by zekedran** [comment]
@Wikiki can we have this integrated into bulma?

**Comment by frederikhors** [comment]
@Wikiki can I ask you why `.75rem` in the code you posted?

> ```css
> .is-fullheight.columns {
>     height: calc(100vh - ( 3.25rem - .75rem ) );
> }
> ```

**Comment by jorgepinon** [comment]
Inspired by @Wikiki's solution, I came up with what I think is a simpler flexbox-y way with just a couple of extra utility classes. No need to set height. 
[jsfiddle example](https://jsfiddle.net/jorgeluis/ysxeLrjk/)

Haven't tested IE.

**Comment by Sogl** [comment]
@Wikiki How to make sidebar always equal the content height? I don't need vertical scroll, but `height: 100vh` for sidebar works only when content is smaller then viewport height. 😞

**Comment by dustinmichels** [comment]
@Wikiki 's solution is just what I needed!

`styles.scss`
```
$navbar-height: 3.25rem;

.columns {
  &.is-fullheight {
    min-height: calc(100vh - (#{$navbar-height} - 0.75rem));
    max-height: calc(100vh - (#{$navbar-height} - 0.75rem));
    height: calc(100vh - (#{$navbar-height} - 0.75rem));
    display: flex;
    flex-direction: row;
    justify-content: stretch;
    .column {
      overflow-y: auto;
    }
  }
}
```

HTML:

```
<section class="columns is-fullheight">
    ...
</section>
```

Thanks! I think this would be a nice thing to build into Bulma!

**Comment by adharshmk96** [comment]
It's a very common usecase, only hero section has is-fullheight.
would love it to get it in bulma directly.
