### ISSUE TITLE
Customize Bulma request

### ISSUE THREAD

**Issue by nicolasvahidzein** [jgthms/bulma#864]
First off, let me say Bulma is AMAZING, i love it so much. Everyone speaks of bootstrap but i prefer your design hands down.

In any event, thank you for contributing such a wonderful tool for all of us to use.

I have been relearning web programming as i was a HUGE flash and AS3 coder, it was actually an easy transition considering how familiar js is.

On to my question, i'm ruining your framework with all my edits because i need some colors that i cannot change easily so i was wondering, are you available to chat at all to see if you could customize bulma for me once i am closer to a finished product?

I'm thinking who else but the creator could do a better job. I'm on skype or email to discuss this with you. I would need a site wise redesign and fix. Somethings don't line up nicely etc.. and i butchered your code so sorry in advance :).

Cheers, speak soon.

**Comment by jgthms** [comment]
Hey, thanks for the kind words.

I don't do any freelance, but Bulma should be easy enough to customize if you follow this guide: http://bulma.io/documentation/overview/customize/

**Comment by nicolasvahidzein** [comment]
Je savais pas que vous etiez francais, j'en ai profité pour jeter un coup d'oeil sur votre site il est vraiment beau. Felicitations.
