### ISSUE TITLE
No replacement for <nav-item is-tab> and <nav has-shadow> ?

### ISSUE THREAD

**Issue by connectkushal** [jgthms/bulma#865]
Since nav component is being deprecated, i couldn't find the alternative for `<class="nav-item is-tab is-active">` which gives a nice colored link text and border at the bottom, nor did i find anything for `<class="nav has-shadow">` in the new `navbar` component.

Are these features dropped in the upcoming release ?

**Comment by jgthms** [comment]
Dupe
