### ISSUE TITLE
navbar-dropdown disappearing on hover

### ISSUE THREAD

**Issue by Husky110** [jgthms/bulma#866]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.4.3] 
My **browser** is: Chrome Version 59.0.3071.115 (official Build) (64-Bit Linux Mint)
This is a **Sass** issue: I'm using version [0.4.3]
I am sure this issue is **not a duplicate**.

### Description

Hey folks. I'm builing a laravel-app with bulma and wanted to use the new navbar-component.
My html is in the attached screenshoot (github won't let me...).
![image](https://user-images.githubusercontent.com/13180625/28215701-2d8059ac-68af-11e7-8aa8-dd555027a180.png)

Now everytime I hover over the "Somewhat" the dropdown pops open (yay!) but as soon as I move my mouse down to the Dropdown-content -> it disappears.

### Steps to Reproduce

- Create a new laravel-app
- install bulma via npm
- set a new view
- set the navbar inside the app-layout, outside of the view-content
- add a nav with navbar-brand + navbar-burger
- add the above code after the closed navbar-brand
- Error!

### Expected behavior

That the dropdown-content stayes visible while I'm inside the dropdown-area with my mouse.

### Actual behavior

Is disappeared. Bad dropdown!
![output](https://user-images.githubusercontent.com/13180625/28215589-d350eece-68ae-11e7-8cb5-5448011049ec.gif)

**Comment by PanArnaud** [comment]
I have the same issue on Firefox 54

**Comment by Husky110** [comment]
Plus personally I don't think it's a browser-issue, since Google are the most upfront when it comes to new standards and stuff...

**Comment by jgthms** [comment]
I haven't been able to reproduce it. I'll have to investigate.

**Comment by brenouchoa** [comment]
Have the same problem here. Seem like if there is a container underneath the list, the container get the focus and not the dropdown.

**Comment by brenouchoa** [comment]
As I expected, if i put a breadcrum right under the navbar i don't have the problem.

**Comment by PanArnaud** [comment]
@brenouchoa Can you share the code please ? Thank you

**Comment by suchmaske** [comment]
I could reproduce the problem. I fixed it by increasing the `z-index` value of my navbar. Apply the following in your stylesheets:

```scss

#my-navbar-selector {
    z-index: 1000;
}

```

**Comment by livingos** [comment]
Same issue here. Only when navbar is inside a container. 

Increasing z-index fixes it.

**Comment by sidaurukfreddy** [comment]
this is should me merge for upgrading i guess, thanks for @suchmaske

**Comment by drriguz** [comment]
Same issue, a dropdown inside container , solved by the workaround by  @suchmaske
