### ISSUE TITLE
 container doesn't work the same way in [0.4.3] as in [0.4.2]

### ISSUE THREAD

**Issue by roennow** [jgthms/bulma#867]
In 0.4.2 you could use .container the same way as all other frameworks fx. as a direct child of body or inside a main element.

If you try to do that in 0.4.3 without using .section, .nav, .footer etc and have a couple of columns inside then the container will not extend to show all but instead have a second scrollbar.

Is this by design? If I put another element or pure text after the columns the scrollbar disappears and the container works as it used to.

### Examples
0.4.2 https://codepen.io/roennow/pen/EXMoVQ
0.4.3 https://codepen.io/roennow/pen/XgGVmz

**Comment by Husky110** [comment]
As a quick workarround I used overflow: initial; on the parent of the container. Hope that helps a bit.

**Comment by jgthms** [comment]
This has been fixed in `0.4.4`.
