### ISSUE TITLE
'is-active' styling missing from menu block

### ISSUE THREAD

**Issue by 0x7b1** [jgthms/bulma#87]
Hey there, I just noticed that the attribute `is-active` applied to a `menu-block` doesn't  do anything. It is expected paint the row. It'd be good to add that missing feature. 
http://bulma.io/documentation/components/menu/
Cheers

**Comment by jgthms** [comment]
Yeah, the menu component needs some work.

**Comment by julianorafael** [comment]
Hi, I'm interested on working on this feature but I'm new to github so I need some guidance. Should I start a branch and work on the feature and then make a PR?
