### ISSUE TITLE
Icon on small select is too big

### ISSUE THREAD

**Issue by etiennecrb** [jgthms/bulma#870]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** 0.4.3
My **browser** is: Chrome 59.

### Description
When using an icon on a small select, layout is disturb because icon is too big.

### Steps to Reproduce

```html
<p class="control has-icons-left">
  <span class="select is-small">
    <select>
      <option value="" disabled selected>Filter by table</option>
      <option>Table 1</option>
      <option>Table 2</option>
   </select>
  </span>
  <span class="icon is-small is-left">
     <i class="fa fa-filter"></i>
  </span>
</p>
```

### Expected behavior

![capture du 2017-07-15 00-39-21](https://user-images.githubusercontent.com/12871063/28233300-1d5c6fc4-68f6-11e7-95d3-3305956f57aa.png)

### Actual behavior

![capture du 2017-07-15 00-39-30](https://user-images.githubusercontent.com/12871063/28233301-1d5c78de-68f6-11e7-99c1-7c5d43e8dc25.png)

**Comment by jgthms** [comment]
This has been fixed. http://localhost:4000/documentation/form/select/
