### ISSUE TITLE
Navbar do not align elements within container

### ISSUE THREAD

**Issue by rafa-acioly** [jgthms/bulma#871]
This is about the Bulma **CSS framework**

### Description

`navbar` do not place the `navbar-end` aligned in the "same line" when its a `container` inside of it.

### Steps to Reproduce

```html
<header class="navbar">
  <div class="container"> <!-- broke the navbar -->
    <div class="navbar-brand">
      <div class="navbar-item">
        <img src="http://placehold.it/150x150" alt="">
      </div>
    </div>
    <div class="navbar-end">
      <a href="" class="navbar-item">Item</a>
    </div>
  </div>
</header>
```
https://codepen.io/r_acioly/pen/KqExBv

### Expected behavior

do not put the `navbar-end` in a new line, keep the align as `flex-row`

### Actual behavior

move the `navbar-end` to a new line above of  `navbar-brand`

**Comment by jgthms** [comment]
Dupe

**Comment by rafa-acioly** [comment]
@jgthms what? :|

**Comment by jgthms** [comment]
It's a duplicate.
