### ISSUE TITLE
is-tab modifier not present in new navbar

### ISSUE THREAD

**Issue by timcosta** [jgthms/bulma#873]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.3]
My **browser** is: Chrome 59
I am sure this issue is **not a duplicate**

### Description

The `is-tab` `navbar-item` modifier is not preset anymore with the change from `nav` to `navbar` as far as i can tell. A search for `is-tab` on the `navbar` page yields no results.

**Comment by timcosta** [comment]
Hi @jgthms, does you closing this issue mean it has been resolved, this feature was dropped, or something else? Confused by the close with no comment.

**Comment by jgthms** [comment]
It's the 3rd duplicate for this issue within a few days. And it has been solved.
