### ISSUE TITLE
 The Bulma package does not come with any JavaScript. WHY????

### ISSUE THREAD

**Issue by ivanhuay** [jgthms/bulma#874]
### Overview of the problem
feature
This is about the Bulma Javascript

### Description
Most frameworks come with some built-in javascript. Implementing javascript for bulma in each project is uncomfortable and slow. There should be a bulma.js file with what is needed for the framework.

### Steps to Reproduce
1. Try to make a navbar and navbar-burger without writing javascript

### Expected behavior

Bulma should include bulma.js

### Actual behavior

Bulma.js file does not exist

**Comment by kevinvdburgt** [comment]
This is a css framework only, and it is the reason why i love this project ❤️ 

There are some javascript snippets documented [here, check the Javascript toggle](http://bulma.io/documentation/components/navbar/).

**Comment by ekid** [comment]
$("#showModal").click(function() {
  $(".modal").addClass("is-active");  
});

$(".modal-close").click(function() {
   $(".modal").removeClass("is-active");
});

**Comment by InstanceOfMichael** [comment]
Although some small/simple tutorials on how to use with common frameworks would be nice. Some new users may need them to understand how to use a JS-agnostic framework.

**Comment by micah1701** [comment]
Nothing fancy, but a simple example of some JS I made turns a menu into an expandable/collapsible menu https://gist.github.com/micah1701/a8cd47df56985a61e91a9d46c91d4df2  a dozen or so lines each of JS and additional CSS

**Comment by VizuaaLOG** [comment]
Bit of shameless promotion here ;)

I created and maintain a vanilla JS package for Bulma.

It has some common JS integration along with some other extensions. While I wouldn't recommend using it in any major production environment, I am using it in production without issues.

[BulmaJS docs](Https://vizuaalog.github.com/BulmaJS)

If you have any questions or issues. Please feel free to open an issue on that repo.

End of shameless promotion ;)

**Comment by ta32** [comment]
This css framework is being used in pure rust webassembly SPA apps 
https://github.com/yewstack/yew/tree/master/examples/router
I guess why they choose bulma because there is no jquery dependency

**Comment by dartie** [comment]
I totally agree with the request.
I expect to copy and paste components and get it working, but it doesn't work because of the missing javascript. 
You can add as many thumb down as you want to the request, you will still need javascript to have a dropdown working or a modal to be displayed. 
If you really wish bulma to become adopted:

- Include the javascript in the example.
- Specify requirements (a dropdown needs fontawasome to get the arrow displayed)
- Include a javascript to be included which makes all components working out-of-box.

**Comment by digitigradeit** [comment]
> I totally agree with the request. I expect to copy and paste components and get it working, but it doesn't work because of the missing javascript. You can add as many thumb down as you want to the request, you will still need javascript to have a dropdown working or a modal to be displayed. If you really wish bulma to become adopted:
> 
> * Include the javascript in the example.
> * Specify requirements (a dropdown needs fontawasome to get the arrow displayed)
> * Include a javascript to be included which makes all components working out-of-box.

Did you actually read the docs? there's plenty of javascript examples to get bulma working. Bulma does not include JavaScript in the sense that the framework itself, in release form, does not have a javascript file that you need to place in your site's <head> or somewhere on your site. I'm sure you have heard the saying there's 99 ways to skin a cat?

With that said, to address each point you listed:

> Include the javascript in the example.

https://bulma.io/documentation/components/navbar/

It literally indicates: 

> The Bulma package does not come with any JavaScript.
> **Here is however an implementation example, which toggles the class is-active on both the navbar-burger and the targeted navbar-menu, in Vanilla Javascript.**

> Specify requirements (a dropdown needs fontawasome to get the arrow displayed)

icons are optional with any element or component. but that doc, should you want to learn more is here: https://bulma.io/documentation/elements/icon/ in which it clearly indicates that the .icon element, is independent of any icon package and provides three different examples of icon packages (FontAwesome, Material Design icons, and Ionicons).

> you will still need javascript to have a dropdown working or a modal to be displayed.

There is a provided implementation example (JavaScript) very clearly indicated in the docs: https://bulma.io/documentation/components/modal/#javascript-implementation-example

Lastly. Dropdown does not require JavaScript to function.

If you're going to dig up and comment on an already closed issue like this with some false sense of moral superiority "If you really wish bulma to become adopted" which triggers a notification to anyone who is watching this repository. I would highly suggest you learn the framework in its entirety before posting baseless claims. Is your comment a request for help? You might have better luck opening a new issue in that case. :)
