### ISSUE TITLE
Modules documentation

### ISSUE THREAD

**Issue by pascalheraud** [jgthms/bulma#876]
### Overview of the problem

This is about the Bulma **Docs**
I'm using Bulma **version** latest from git

### Description

Docs says that bulma is modular but there is no documentation about what file is needed to be included for each feature. It could be nice, to have for each example, the modules needed.

I just discovered by searching into sources that .container are located into elements/other.sass ...

### Steps to Reproduce

N/A

### Expected behavior

Each module like one of "Box,Button,Content,Delete,Icon,Image,Notification,Progress,Table,Tag,Title" may have corresponding modules.

### Actual behavior

N/A

**Comment by jgthms** [comment]
There is a section about it already: http://bulma.io/documentation/overview/modular/

It could definitely be enhanced though.
