### ISSUE TITLE
Dropdown menu of a navbar component is not visible

### ISSUE THREAD

**Issue by tanmay-das** [jgthms/bulma#878]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.4.3]
My **browsers** are: Mozilla Firefox 52, Chrome Beta

### Description

The dropdown menu of the navbar component is not visible unless a css rule {overflow: visible;} is applied directly on **body** tag.
### Steps to Reproduce

1. Copy the [navbar example](http://bulma.io/documentation/components/navbar/)
2. Nest it within the **body** tag
3. Preview on browser
4. Hover over to a dropdown menu, and a scrollbar shall appear, indicating that the overflow is messing with the navbar

### Expected behavior

Expected the dropdown menu to work without having to apply overflow:visible to body tag

### Actual behavior

Dropdown is not visible

**Comment by Wavum** [comment]
#857

**Comment by jgthms** [comment]
@cringer is right.
