### ISSUE TITLE
Bug: overflow-x on body will hide bottom line of .box class "box-shadow" style

### ISSUE THREAD

**Issue by Dahje** [jgthms/bulma#879]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **version** [0.4.3] 
My **browser** is: Google Chrome, Firefox, Edge
This is a **Sass** issue: I'm using version [0.4.3] 

### Description
When upgrading from version 0.4.2->0.4.3 a change was made in the the generic.sass stylesheet to add "overflow-x:hidden" onto the styling for "body" (line 33). With this new style the bottom line of a border on the .box class will be hidden if it is the only visible element in the body.

### Steps to Reproduce
Recreated here https://jsfiddle.net/m8Lq1525/ for ease.

### Expected behavior

Show a border (as a "box-shadow") around the entire element.

### Actual behavior

Shows a border (as a "box-shadow") around the entire element, but the bottom line of the shadow is hidden so it appears the border is incomplete.

Edit: Removed "I'm sure this is not a duplicate", since it has similar characteristics to issue # 878.

**Comment by HJain13** [comment]
A simpler solution is mentioned in #857 but if for some reason you don't wanna do that.

**A Verbose Solution for your exact problem:**

```
<body>
  <div class="box" style="margin-top: 20px; margin-left: auto; margin-right: auto; width: 200px;">
    This is a simple box
  </div>
</body>
```
Problem according to me: Whats happening in your original code is that you are over riding the default bottom-margins provided in the CSS, which originally caused the page to be little longer than the element now in your implementation it's exactly equal and is not showing the border.

**Comment by Dahje** [comment]
Good Point! Thank you for the suggestion.

**Comment by nicolasluishuber** [comment]
In version 0.4.4 this issues was fixed.

**Comment by Dahje** [comment]
Yes, this does indeed appear to be fixed. Thank you!
