### ISSUE TITLE
Change text size in input.is-large

### ISSUE THREAD

**Issue by barohatoum** [jgthms/bulma#880]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.3]
My **browser** is: Google Chrome

I am sure this issue is **not a duplicate**?

### Description
When using the input.is-large modifier for input elements, the text size gets bigger, and if i change the size of the text, the input element gets smaller. If there could be a way of using **is-text-small** to resize the text like when using the **is-small** for icons to resize the text without resizing the element itself

### Steps to Reproduce
```
<div class="field">
  <label class="label is-large">Large input</label>
  <div class="control has-icons-left has-icons-right">
    <input class="input is-large" type="email" placeholder="Email" style="font-size:12px;">
    <span class="icon is-small is-left">
      <i class="fa fa-envelope"></i>
    </span>
    <span class="icon is-small is-right">
      <i class="fa fa-check"></i>
    </span>
  </div>
</div>
```

**Comment by jgthms** [comment]
You can play with the height and padding:

```
.input {
  height: 3em;
  padding: calc(0.875em - 1px) calc(1em - 1px);
}
```

https://codepen.io/jgthms/pen/zzQgad

**Comment by barohatoum** [comment]
Perfect.. thanks so much and love your work

Keep it up



Ibrahim Hatoum / Web developer
ibrahim.hatoum@gmail.com / (514) 717-9828

**Comment by dylzeee** [comment]
I would love this to be implemented somehow with sass variables. The is-medium, is-large, modifiers should only apply to the size of the input and not the size of the text inside.
