### ISSUE TITLE
Feature : Make title & subtitle more control for all sizes (Responsive helpers)

### ISSUE THREAD

**Issue by l2aelba** [jgthms/bulma#884]
### Overview of the problem

Problem is we should make **title & subtitle** more responsive controls (example if ` touch` so make text smaller)

Because such as `is-1` is too large for mobile devices.

I know we have  something like `.is-hidden-mobile` but it does not good for SEO and content sizes.

### Description
**I have an idea**. Just add something like : `.is-5-touch`classes

**Example :**
```html
<h2 class="title is-2 is-4-touch">Hello world</h2>
```

So that means default size is `2` but when `touch` is `4`

**What do you think ?**

### Sass example
```sass
+touch
  .title,
  .subtitle
    @each $size in $sizes
      $i: index($sizes, $size)
      &.is-#{$i}-touch
        font-size: $size
```

_(Just an example in my custom build, You guys can do it better)_

**Just an idea sorry for your time.** 😄

**Comment by jgthms** [comment]
It's in `0.4.4`.

**Comment by l2aelba** [comment]
Any doc or source ? I dont see any changes ? @jgthms

**Comment by l2aelba** [comment]
**Good work !** 

Ref : http://bulma.io/documentation/modifiers/typography-helpers/
