### ISSUE TITLE
Button examples should use button element

### ISSUE THREAD

**Issue by kblcuk** [jgthms/bulma#885]
### Overview of the problem

 This is about the Bulma **Docs**

### Description

\<a> element doesn't have `disabled` attribute (at least as far as I can understand from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), so setting it doesn't really disable it)
### Steps to Reproduce

```
<a class="button is-success" title="Disabled button" disabled href="http://bulma/io">Disabled</a>
```
clicking the above will take you to bulma.io, whereas I'd expect it not to; can't think of simpler example, but also attaching any events to \<a> still works.

So I would _think_ examples really should use `button` instead of `a` at least for these cases.

Also, from MDN:
> Accessibility recommendations
> Anchor tags are often abused with the onclick event to create pseudo-buttons by setting href to "#" or "javascript:void(0)" to prevent the page from refreshing. These values cause unexpected behavior when copying/dragging links, opening links in a new tabs/windows, bookmarking, and when JavaScript is still downloading, errors out, or is disabled. This also conveys incorrect semantics to assistive technologies (e.g., screen readers). In these cases, it is recommended to use a <button> instead. In general you should only use an anchor for navigation using a proper URL.

**Comment by raberana** [comment]
any news on this?

**Comment by kblcuk** [comment]
I checked [the docs](https://bulma.io/documentation/elements/button/), and this seems to be fixed already 🎉
