### ISSUE TITLE
Vertical scrollbar with very simple column structure

### ISSUE THREAD

**Issue by rikvanderkemp** [jgthms/bulma#887]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.3]
My **browser** is:  Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

I am sure this issue is **not a duplicate**? Yes, well sort of.

### Description

A (second/extra) vertical scrollbar appears when using a simple two column structure. This seems to be caused by the selector:

`
.columns:last-child {
    margin-bottom: -0.75rem;
}
`

### Steps to Reproduce

1. Create a container div
2. Create a columns div 
3. Create 2 columns, one with is-one-third, let the other one be automatic.
4. Fill the big column with enough content so it forces a scroll

### Expected behavior

I expect a single scrollbar.

### Actual behavior

I get two!

I have create a Pen with a very simple example: https://codepen.io/kdvr/pen/awgMWe included are two solutions. Why is this behavior like this? And which solution would be best. It seems odd that this happens and there is a need for a 'hack' of some sorts to get rid of the second scrollbar. If I have to manually correct this, which of the solutions provided would be best?

There have been more issues reported regarding scrollbars, but they seem to have involved more complex layouts.

**Comment by Klian** [comment]
This is not fixed... I'm getting the same error with the latest Bulma version.

Thanks!
