### ISSUE TITLE
tag pointing to wrong commit

### ISSUE THREAD

**Issue by lu32** [jgthms/bulma#888]
### Overview of the problem

This is about the Bulma **CSS framework**  
The tag 0.4.3 is pointing to the same commit as 0.4.2,  so when someone install it via npm they are getting the wrong version, 243880f instead of fb87d85

**Comment by jgthms** [comment]
Thanks, good catch. Yeah I forgot to push the version number before publishing to npm. But codewise, they are similar, as in, they both include the new navbar anyway.

I'll be more careful next time.
