### ISSUE TITLE
Jekyll-Assets Imports

### ISSUE THREAD

**Issue by HaoZeke** [jgthms/bulma#890]
**Is it about Bulma or about the Docs?**
Bulma

**Is it a bug/feature/question or do you need help?**
Probably some sort of bug.

**If it's a bug, is it a browser bug?**
It's a _docker_ bug I guess.

### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [master branch]

I am sure this issue is **not a duplicate**.

### Steps to Reproduce

1.  Run the jekyll/jekyll docker file.
2. Keep bulma (along with bulma/sass etc) in the _assets/css or whereever.
3. Write a main.scss and use a bunch of .scss files.
4. Watch the docker build fail spectacularly with the following:
Error in _assets/styles/bulma/bulma.sass:6 File to import not found or unreadable: sass/components/all.

### Expected behavior

It runs fine on my local machine. No errors.

### Actual behavior

Errors out on every dockerfile for jekyll I can find.

**Comment by jgthms** [comment]
Jekyll does not include files starting with an underscore `_`, so `_all.sass` is ignored.

You can explicitly include them: https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
