### ISSUE TITLE
Trying to override nav-item color leads to specitificy problems and !important usage.

### ISSUE THREAD

**Issue by DamianPereira** [jgthms/bulma#891]
### Overview of the problem

This is about the Bulma **CSS framework

I'm using Bulma **version** [0.4.3]
My **browser** is: Chrome 59.0.3071.115
This is a **Sass** issue: I'm using version [x.x.x]

### Description

I'm trying to change the color of nav-bar's nav-items. I include bulma/bulma.sass from my base.sass which I compile with node-sass. This is my HTML

```
  <nav class="nav">
    <div class="container">
      <div class="menu nav-center nav-menu">
        <a class="menu__item nav-item">
          Text1
        </a>
        <a class="menu__item nav-item">
          Text2
        </a>
        <a class="menu__item nav-item">
          Text3
        </a>
      </div>
    </div>
  </nav>

```
### Expected behavior

There is some way of changing it that does not lead to specificity wars. I'd consider

### Actual behavior

Only solution I found was forcing it. I also tried reading navbar.sass inside bulma folder, and discovered on the line 4

`$navbar-item: $grey-dark !default`

This controls what I want to change, and the !default thing indicates that it should be possible to override it in sass. But I could not do it, even placing it between lines 6 and 7 of bulma.sass has no effect. Shouldn't I be able to override this?

If I can't override it, then I guess it's a bug, cause using !important seems like a mistake. If I can override it and I'm doing it wrong then I think it should be better documented.

**Comment by jgthms** [comment]
You're confusing the `.nav` and the `.navbar`.

Here's the correct documentation for the **navbar**: http://localhost:4000/documentation/components/navbar/
