### ISSUE TITLE
has-shadow doesn't work as in the past or expected

### ISSUE THREAD

**Issue by roni-estein** [jgthms/bulma#892]
### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs** (possibly)
I'm using Bulma **version** 0.4.3
My **browser** is: chrome Version 59.0.3071.115 (Official Build) (64-bit) On MacOS Sierra

I am sure this issue is **not a duplicate**?

### Description

On both nav.nav and nav.navbar has-shadow produces nothing. If you add the css manually nothing happens either.

### Steps to Reproduce

.1 take an example bulma menu, add class has-shadow

<nav class="navbar has-shadow">
  <div class="navbar-brand">
    <a class="navbar-item" href="http://bulma.io">
      <img src="http://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>

    <a class="navbar-item is-hidden-desktop" href="https://github.com/jgthms/bulma" target="_blank">
      <span class="icon" style="color: #333;">
        <i class="fa fa-github"></i>
      </span>
    </a>

    <a class="navbar-item is-hidden-desktop" href="https://twitter.com/jgthms" target="_blank">
      <span class="icon" style="color: #55acee;">
        <i class="fa fa-twitter"></i>
      </span>
    </a>

    <div class="navbar-burger burger" data-target="navMenuExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navMenuExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item " href="http://bulma.io/">
        Home
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link  is-active" href="/documentation/overview/start/">
          Docs
        </a>
        <div class="navbar-dropdown ">
          <a class="navbar-item " href="/documentation/overview/start/">
            Overview
          </a>
          <a class="navbar-item " href="http://bulma.io/documentation/modifiers/syntax/">
            Modifiers
          </a>
          <a class="navbar-item " href="http://bulma.io/documentation/grid/columns/">
            Grid
          </a>
          <a class="navbar-item " href="http://bulma.io/documentation/form/general/">
            Form
          </a>
          <a class="navbar-item " href="http://bulma.io/documentation/elements/box/">
            Elements
          </a>
          
            <a class="navbar-item is-active" href="http://bulma.io/documentation/components/breadcrumb/">
              Components
            </a>
          
          <a class="navbar-item " href="http://bulma.io/documentation/layout/container/">
            Layout
          </a>
          <hr class="navbar-divider">
          <div class="navbar-item">
            <div>version <p class="has-text-info is-size-6-desktop">0.4.3</p></div>
          </div>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link " href="http://bulma.io/blog/">
          Blog
        </a>
        <div id="blogDropdown" class="navbar-dropdown " data-style="width: 18rem;">
          
            <a class="navbar-item" href="/2017/03/10/new-field-element/">
              <div class="navbar-content">
                <p>
                  <small class="has-text-info">10 Mar 2017</small>
                </p>
                <p>New field element (for better controls)</p>
              </div>
            </a>
          
            <a class="navbar-item" href="/2016/04/11/metro-ui-css-grid-with-bulma-tiles/">
              <div class="navbar-content">
                <p>
                  <small class="has-text-info">11 Apr 2016</small>
                </p>
                <p>Metro UI CSS grid with Bulma tiles</p>
              </div>
            </a>
          
            <a class="navbar-item" href="/2016/02/09/blog-launched-new-responsive-columns-new-helpers/">
              <div class="navbar-content">
                <p>
                  <small class="has-text-info">09 Feb 2016</small>
                </p>
                <p>Blog launched, new responsive columns, new helpers</p>
              </div>
            </a>
          
          <a class="navbar-item" href="http://bulma.io/blog/">
            More posts
          </a>
          <hr class="navbar-divider">
          <div class="navbar-item">
            <div class="navbar-content">
              <div class="level is-mobile">
                <div class="level-left">
                  <div class="level-item">
                    <strong>Stay up to date!</strong>
                  </div>
                </div>
                <div class="level-right">
                  <div class="level-item">
                    <a class="button is-rss is-small" href="http://bulma.io/atom.xml">
                      <span class="icon is-small">
                        <i class="fa fa-rss"></i>
                      </span>
                      <span>Subscribe</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-link">
          More
        </div>
        <div id="moreDropdown" class="navbar-dropdown ">
          <a class="navbar-item " href="http://bulma.io/extensions/">
            <div class="level is-mobile">
              <div class="level-left">
                <div class="level-item">
                  <p>
                    <strong>Extensions</strong>
                    <br>
                    <small>Side projects to enhance Bulma</small>
                  </p>
                </div>
              </div>
              <div class="level-right">
                <div class="level-item">
                  <span class="icon has-text-info">
                    <i class="fa fa-plug"></i>
                  </span>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <a class="navbar-item" href="https://github.com/jgthms/bulma" target="_blank">
        Github
      </a>
      <a class="navbar-item" href="https://twitter.com/jgthms" target="_blank">
        Twitter
      </a>
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a id="twitter"
              class="button"
              data-social-network="Twitter"
              data-social-action="tweet"
              data-social-target="http://bulma.io"
              target="_blank"
              href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&url=http://bulma.io&via=jgthms">
              <span class="icon">
                <i class="fa fa-twitter"></i>
              </span>
              <span>Tweet</span>
            </a>
          </p>
          <p class="control">
            <a class="button is-primary" href="https://github.com/jgthms/bulma/archive/0.4.3.zip">
              <span class="icon">
                <i class="fa fa-download"></i>
              </span>
              <span>Download</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>

here is a fiddle
https://jsfiddle.net/roni_estein/y3Lvwbz0/12/

### Expected behavior

I'd expect it to continue to work as in earlier versions. A shadow separator under the nav element

### Actual behavior

No shadow under the nav element

**Comment by jgthms** [comment]
#879

**Comment by roni-estein** [comment]
I don't know enough to tell you if this is the same issue or not. But the use case is different. This isn't being adapted into a site or template. This is me getting to know bulma and using an example right out of your docs with no other CSS in play and the result is different than the expected or displayed result.

Rather than saying there is a work around, I'd update the docs or fix the issue. If this IS expected behaviour deprecate has-shadow. I'd venture that not being able to use box-shadow on a  nav or div is pretty odd for an expected behavior.

Adding 

html {width: 100%; height: 100%}
body {width: 100%; height: 100%}

Is not a hard fix, but maybe add that to the docs. Does it impact anything else? If not why not adapt it into the bulma base CSS?
