### ISSUE TITLE
Tab control within close button

### ISSUE THREAD

**Issue by alexsandro-xpt** [jgthms/bulma#893]
I request a new feature, I would like to change tab control to put a close button.

Is this easy?

**Comment by jgthms** [comment]
Can you explain what a tab control is?

**Comment by alexsandro-xpt** [comment]
@jgthms that component http://bulma.io/documentation/components/tabs/ with a close button into the tab, like tab within close button in the web browser like Chrome, Firefox, Opera...

**Comment by jgthms** [comment]
Can't you use a Font Awesome icon?

**Comment by alexsandro-xpt** [comment]
May be, I could try with Font Awesome icon. I don't know how click event will work after that.

**Comment by alexsandro-xpt** [comment]
@jgthms I would like to add a close button at tabs in Hero Tab layout http://bulma.io/documentation/layout/hero/ on :hover event, I have try it with Font Awesome icon but not success. Any tip?
