### ISSUE TITLE
Navbar center?

### ISSUE THREAD

**Issue by joncorrin** [jgthms/bulma#894]
Is it about Bulma or about the Docs?
Yes

No

### Overview of the problem

This is about the Bulma **CSS framework**
This is about the Bulma **Docs**
I'm using Bulma **version** [0.4.3]
 My **browser** is: Chrome

### Steps to Reproduce
N/A

### Actual behavior

My issue is I used nav-center in previous versions of bulma and loved it for logo use cases as well as content display. Is there an equivalent in the newest version of bulma with the new navbar?

**Comment by jgthms** [comment]
#839
