### ISSUE TITLE
[Q] How to vertically align Tile contents?

### ISSUE THREAD

**Issue by mixdev** [jgthms/bulma#897]
When you use tiles, the contents are aligned top (top:0, vertical-align:top). Why is it so? Is there a native way to keep it vertically align to middle? 

 I'm using Bulma 0.4.3 on Safari macOS Sierra. Hopefully not a duplicate as there are no answers related to vertical align.

**Comment by jgthms** [comment]
Unfortunately it's not possible with the tiles. But the CSS Grid features might change that.
