### ISSUE TITLE
Add variable for navbar-item padding?

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#899]
Any potential conflicts w/ adding a variable for navbar-item padding?

e.g. https://github.com/jgthms/bulma/blob/3f8c12bfbbcbfcddfe71c87d9c76e8ea3462b886/sass/components/navbar.sass#L62

on bulma 0.4.3

**Comment by jgthms** [comment]
This value is selected for visual balance. Can't you override it?

**Comment by tony** [comment]
@jgthms 

I'm closing, because I'm slowly being swayed by your visual / spatial taste on the navbar.

default (what I'm going back to)
<img width="1192" alt="screen shot 2017-07-23 at 3 04 53 pm" src="https://user-images.githubusercontent.com/26336/28502461-9fd413a8-6fb8-11e7-8350-62bd2a33eafe.png">

my override:

<img width="1172" alt="screen shot 2017-07-23 at 3 04 41 pm" src="https://user-images.githubusercontent.com/26336/28502466-aed3b656-6fb8-11e7-9acc-da9941ea63f3.png">
