### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by peteringram0** [jgthms/bulma#9]
Loving the framework. What is the browser support please? I take it it is IE10+ ?

Thanks

**Comment by jgthms** [comment]
So technically, it would be IE10+ yes. But there are no vendor prefixes implemented yet. So for now, it's only Edge really :-/

I don't have a Windows machine but I'd be glad if someone could try it out, and maybe submit a PR that would add `-ms-` where needed?

**Comment by peteringram0** [comment]
This repo is really good to get all the IE VM's

https://github.com/xdissent/ievms

You could just run the css though an autoprefixer: https://www.npmjs.com/package/gulp-autoprefixer
then it should work back to 10 in that case :+1:

**Comment by p2kmgcl** [comment]
I´ve had a look of the project with IE10 and almost everything seems to be fine, flexboxes work perfectly (even adding/removing columns and resizing the browser):

> ![image](https://cloud.githubusercontent.com/assets/800645/12912101/bf79aed2-cf16-11e5-938d-2410c2dd20cb.png)

The only issue I´ve found is in the vertical centering, where the central and bottom text stays on top:

> ![image](https://cloud.githubusercontent.com/assets/800645/12912064/a2fd29d2-cf16-11e5-81d9-d6ca70190858.png)

The rest of the elements are working.

**Comment by ndimatteo** [comment]
Is there any fallback in place so things aren't totally jacked on older browsers? Nothing fancy, just something so that it's still readable.

**Comment by timwis** [comment]
Hey guys, might I suggest adding a note about browser support to the docs somewhere? I looked through each page trying to find it and ended up here after googling. Looking forward to using it, but wanted to know what mobile browser support it has, etc.

**Comment by BenjaminBeck** [comment]
Yes - got here by googling : "bulma browser support"

**Comment by madjake45** [comment]
pretty much your main issue would be flexbox support as far as I'm aware so
check on mobile for flexbox support

On Tue, Mar 1, 2016 at 7:43 PM, Benjamin <notifications@github.com> wrote:

> Yes - got here by googling : "bulma browser support"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgthms/bulma/issues/9#issuecomment-190869927>.
>



-- 
-------
Jake

**Comment by ellerbrock** [comment]
hi there,

first at all thanks for your great work on the bulma framework!
i played with it in the past and just come back to use it for my next project.
since i need to tell my client whats the matter with the browser support i came via googling around to this page :) 

oh while writing i just wanted to point to http://caniuse.com/#feat=flexbox and found out that this information is now on the bulma github page anyway: https://github.com/jgthms/bulma#browser-support :D 

cheers maik
