### ISSUE TITLE
Variable for hover+active background/color?

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#900]
0.4.3

On my main navbar, ``is-active`` links have a background override. I don't want them to change on hover.

https://github.com/jgthms/bulma/blob/0.4.3/sass/components/navbar.sass#L49

I think it'd be nice to see a variable for:

```sass
// default to current behavior
$navbar-item-active-hover: $navbar-item-hover !default
$navbar-item-active-hover-background: $navbar-item-hover-background !default

a.navbar-item,
.navbar-link
  &.is-active:hover
    background-color: $navbar-item-active-hover-background
    color: $navbar-item-active-hover
```

**Comment by jgthms** [comment]
Added!

**Comment by jwjcmw** [comment]
Was this feature actually implemented?  I don't see it in the current version or in 0.5.0.

**Comment by shelru** [comment]
@jgthms doesn't work :/

**Comment by dustinmichels** [comment]
I'm having trouble setting this, too.

**Comment by oz-** [comment]
Stiil unable to change the behavior on hover (darken...) Any way to avoid this?
