### ISSUE TITLE
dropdown navbar-item color overrides

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#902]
In my situation, I'm customizing the main navbar-item's to be white, but I don't want dropdown navbar-item's to be white.

<img width="506" alt="screen shot 2017-07-23 at 1 54 33 pm" src="https://user-images.githubusercontent.com/26336/28502005-7ad7c6bc-6fae-11e7-9f5d-9e434a3f13f9.png">
Bulma version 0.4.3 + master

https://github.com/jgthms/bulma/blob/3506d964ecd11e21f5e23536d1426fa9949db7ad/sass/components/navbar.sass#L145

In the spirit of the current variables:

```sass
$navbar-item: $grey-dark !default
$navbar-item-hover: $black !default
$navbar-item-hover-background: $background !default
$navbar-item-active: $black !default
$navbar-item-active-background: transparent !default
```

It could be consistent for reciprocal variables for ``$navbar-dropdown``.

```sass
// add + preserve current defaults
$navbar-dropdown-item: $navbar-item !default
$navbar-dropdown-item-background: $navbar-item-background !default

// already here
$navbar-dropdown-item-hover: $black !default
$navbar-dropdown-item-hover-background: $background !default
$navbar-dropdown-item-active: $primary !default
$navbar-dropdown-item-active-background: $background !default
```

In the SASS:

```sass
+desktop
      // snip
      .navbar-dropdown
        a.navbar-item
          color: $navbar-dropdown-item
          background-color: $navbar-dropdown-item-background
          &:hover
            background-color: $navbar-dropdown-item-hover-background
            color: $navbar-dropdown-item-hover
          &.is-active
            background-color: $navbar-dropdown-item-active-background
            color: $navbar-dropdown-item-active
```

(Chesterton's fence: I don't know the ramification of the prefix/colors on responsiveness yet. Not sure why colors aren't at https://github.com/jgthms/bulma/blob/3506d964ecd11e21f5e23536d1426fa9949db7ad/sass/components/navbar.sass#L103 yet)

**Comment by marovargovcik** [comment]
Hey,

is this fixed? I want to do the same as OP but I don't see $navbar-dropdown-item variable as it was suggested. 

Bulma verson:  ^0.7.2

**Comment by arnoutj** [comment]
It seems that this still is not fixed. I would expect to find a variable `$navbar-item-hover-color` but it is not there in the docs: https://bulma.io/documentation/components/navbar/

**Comment by dboekhout** [comment]
+1 for having $navbar-dropdown-item-color available. I'm in the same situation as OP. Have transparent navbar with white navbar items, but my dropdown items are now invisible on a white dropdown background.
