### ISSUE TITLE
Dropdowns from nav are getting shrunk if a container/section beneath nav is small.

### ISSUE THREAD

**Issue by kirqe** [jgthms/bulma#904]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.3]
My **browser** is:  chrome 59.0.3071.115

### Description

Dropdowns from nav are getting shrunk if a container/section beneath nav is small.

### Steps to Reproduce
<img width="250" alt="screen shot 2017-07-24 at 02 00 50" src="https://user-images.githubusercontent.com/5272402/28503678-f564d2b6-7013-11e7-8d02-d75f449a9114.png">

<img src="http://i.imgur.com/8C6luFq.gif">

**Comment by nicolasluishuber** [comment]
Try:

```css
body {
  overflow-y: auto;
}
```

Just for curiosity, what you use for template?

**Comment by kirqe** [comment]
@nicolasluishuber 
Thanks
looks like the following css solves the problem.
```
html, body {
  height: 100%;
  overflow-y: auto;
}
```

but ` body { overflow-y: auto; }` didn't work.

I had also tried the following before opening the issue`html, body { height: 100%; }`, it kinda fixed the problem but added not scrollable scroll on the right.

**Comment by nicolasluishuber** [comment]
I guess this issue is related to #895

**Comment by kirqe** [comment]
@nicolasluishuber, you're right. But I couldn't find that issue because I was searching for a different problem at first :)

**Comment by nicolasluishuber** [comment]
If you switch to version 0.4.2, without you solutions the issue still remaining?

**Comment by kirqe** [comment]
0.4.2 breaks my nav completly
<img width="870" alt="screen shot 2017-07-24 at 02 43 06" src="https://user-images.githubusercontent.com/5272402/28504116-eeb3fe3c-7019-11e7-96a5-d5af0b91a370.png">

**Comment by jgthms** [comment]
The `overflow: hidden` has been removed in `0.5.1`
