### ISSUE TITLE
Feature request: adding a well-positioned search bar to the table

### ISSUE THREAD

**Issue by ImreC** [jgthms/bulma#907]
Hi, 

Short request. I am using Bulma in combination with VueJS. So far it works awesome. However, there is one thing that I am really missing. With Vue it is possible to create filterable data tables using simple filters. It's nicer to program this yourself because most data table implementations for Vue are bad and it's not hard. What I am missing for this is a well-positioned search field in the Bulma table. I already tried to do something myself, but if I was any good at this, I would probably not need the power and simplicity of Bulma. I can't imagine I am the only one with this problem, but maybe I am mistaken. In that case sorry for wasting time. 

Best regards,
Imre

**Comment by jgthms** [comment]
Do you have an example of what you're looking for?

**Comment by ImreC** [comment]
I have done some combining and came up with this:
![image](https://user-images.githubusercontent.com/9742684/28528891-50ceaea8-708f-11e7-801c-04f67c2d16cd.png)

However, I do not think this looks great. It would be better if it was cleaner. Adding a level looks like this:
![image](https://user-images.githubusercontent.com/9742684/28529213-45b35194-7090-11e7-9717-f1846c433042.png)

But it still looks incoherent somehow. Maybe something like this:
![image](https://user-images.githubusercontent.com/9742684/28529525-1213f14e-7091-11e7-8f34-3426bb5660b9.png)

**Comment by ImreC** [comment]
Did some more tweaking on the "message" approach. Sort of works. Still seems off somehow. A good way to add titles in the original style (white background and fonts like in my second example, but coherent with the table) would still be nice. Obviously not a high prio thing.
