### ISSUE TITLE
Hamburger icon is not aligned right on using container as first child of navbar

### ISSUE THREAD

**Issue by connectkushal** [jgthms/bulma#910]
### Overview of the problem

Tried this fix #896 which brought out this issue.  The hamburger menu icon which appears in the mobile view is not aligned to the right when using a container inside a navbar and it looks odd.

Check this https://codepen.io/connectkushal/pen/prodge?editors=1100

This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.4.4]

I am sure this issue is **not a duplicate** 

### Steps to Reproduce

1. Copy the navbar example code as in docs
2. Wrap everything in the parent nav in a container div
3. See mobile view

**Comment by Come2Daddy** [comment]
Haven't noticed any bad behavior so far, thinking of a PR anytime soon.
