### ISSUE TITLE
bulma.styl

### ISSUE THREAD

**Issue by Log1x** [jgthms/bulma#911]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Hi. I just wanted to make light on my 1:1 fork of Bulma for Stylus. It will keep 1:1 with dev-master and npm. There are similar projects to mine (of which this is even forked from)-- but they are not being maintained to keep parity with the official repository.

I'm not sure your take on Stylus, but feel free to add it to the related projects if you'd like.  :)

[Bulma.styl](https://github.com/log1x/bulma.styl)

It will be updated daily with any changes done to the master Bulma repo.

-Brandon

**Comment by jgthms** [comment]
Hey thanks. Could you add it to the related projects?
