### ISSUE TITLE
.tag breaks WordPress

### ISSUE THREAD

**Issue by Log1x** [jgthms/bulma#912]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.4]

### Description

I'm sure this issue will cause some face-palming (as it should)-- but I feel like it should be brought up.

When viewing a tag archive on WordPress, it adds `tag` into the body class. This causes the layout to break with Bulma.

This was also an [issue](https://github.com/twbs/bootstrap/issues/20542) on Bootstrap.

Their fix was to rename `.tag` to `.badge`-- but I think a more Bulma-like approach would be something like:

`.tag:not(body)`

I'd love a fix on this at a Bulma level, but if you're not interested in compatibility, there is WordPress-specific approaches such as modifying `body_class` filter to swap class names, but this is quite a messy fix for something that should be able to solved with minimal conflict and without changing `.tag` as a whole by utilizing `:not`.

### Steps to Reproduce

1. Use Bulma in your WordPress theme
2. Visit `site.com/tag/example`
3. Be sad.

**Comment by LZDevs** [comment]
The issue is there in v1.0.2.
