### ISSUE TITLE
Safari .button Text Centering

### ISSUE THREAD

**Issue by ellisio** [jgthms/bulma#913]
### Overview of the problem

This is about the Bulma **CSS framework**
 I'm using Bulma **version** [0.4.4]
My **browser** is: Safari
Related: #727 

### Description

The following CSS breaks `<button>` text alignment in Safari _only_.

```
.modal-card-foot .button {
    width: 50%;
}
```

Here is an example Codepen showing this behavior (view in Safari): https://codepen.io/ellisthedev/pen/dzPbbv

### Expected behavior

Both `<button>` and `<a>` should center the text.

### Actual behavior

`<button>` text is left aligned, `<a>` text is centered.

**Comment by tjkohli** [comment]
I proposed a solution that works. Add `display: table-cell;` to `.button`

**Comment by kirqe** [comment]
still got this issue. `display: table-cell; to .button` doesn't solve the problem

safari
<img width="274" alt="screen shot 2017-08-18 at 23 44 09" src="https://user-images.githubusercontent.com/5272402/29477062-6a7b5cae-846f-11e7-88f1-c980d1c2addc.png">

chrome
<img width="250" alt="screen shot 2017-08-18 at 23 44 02" src="https://user-images.githubusercontent.com/5272402/29477063-6a9beaaa-846f-11e7-91f7-43cb041bb98b.png">

**Comment by tjkohli** [comment]
@kirqe It works for me. Share a Codepen and we can investigate.

**Comment by JessieAMorris** [comment]
I've found changing `display: inline-flex` to `display: inline-block` for buttons works. For some reason Safari barfs with centering text inside the flex box.

**Comment by fundon** [comment]
Mark!

**Comment by erikdahlstrand** [comment]
I had the same problem but it seems to be fixed in Safari 11. Maybe this issue can be closed now @ellisio ?

**Comment by lukecwilliams** [comment]
A fix would still be very nice b/c not all users are on the new Safari 11.

@jgthms This is a duplicate of https://github.com/jgthms/bulma/issues/292
