### ISSUE TITLE
hamburger defaulting to $text and $background

### ISSUE THREAD

**Issue by Log1x** [jgthms/bulma#914]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

Thanks a lot for the release of `.navbar`-- it is a lot more sane than the previous `.nav`.

With the release of `.navbar`-- I think it's time to update the `hamburger()` mixin to allow passing colors.

With my navbar being a dark color and my `$background` being light, my navbar toggle looks a little silly on hover right now.

Perhaps we allow `hamburger()` to accept a `$color` and `$background` variable and then update `navbar.styl` to have a `$navbar-hamburger-color` and `$navbar-hamburger-background` that we pass to the mixin?

Let me know if this sounds good and I can throw out a PR if need be.

**Comment by jgthms** [comment]
#844
