### ISSUE TITLE
New extension : Pageloader

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#915]
Hi,

a new element called pageloader is available here: https://github.com/Wikiki/bulma-pageloader
This element is used to display a pageloader overlay.

Regards

**Comment by jgthms** [comment]
Very nice! Can you make a PR to add to the docs?

**Comment by Wikiki** [comment]
PR created [New extensions : Pageloader & Ribbon](https://github.com/jgthms/bulma/pull/917) #917
