### ISSUE TITLE
Font-size for .content and the rest of bulma font-sizes

### ISSUE THREAD

**Issue by teleyinex** [jgthms/bulma#916]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **0.4.4** [
My **browser** is: Chrome
This is a **Sass** issue: I'm using version [0.4.4]

### Description

It looks like you can tune the font-size of most of the elements, except for .container headings like h1, h2, etc. I can see it uses REM, but wouldn't follow the same rules as the rest of the title font sizes?

I expected that if I changed size-1, size-2, ..., it will change also .container h1, .container h2, etc. but it's not. I guess there is a good reason for this, but I would like to know if having the same font-sizes would be nice.

### Steps to Reproduce

1. Set body-size: 18px;
2. Recompile sasss
3. title is-1 has a different font size than .content h1.

### Expected behavior

To have the same font size.

### Actual behavior

h1, h2, h3... within .content have a different font size.

**Comment by jgthms** [comment]
So you can modify the font-size of `.content` with modifiers, and all the text will remain balanced.

**Comment by teleyinex** [comment]
That's what I have done at the end. This was more a question about design :D Just in case, thanks.
