### ISSUE TITLE
Ease the way to change global font size

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#921]
Hi,

why not defining a $html-size variable in order to define a global html text size and then all body text will depend on  it. 

for example:
$html-size : 10px
$body-size: 1.4rem

```
html
  background-color: $body-background
  font-size: $html-size
  -moz-osx-font-smoothing: grayscale
  -webkit-font-smoothing: antialiased
  min-width: 300px
  overflow-x: hidden
  overflow-y: scroll
  text-rendering: $render-mode
```

Regards

**Comment by Ra1d3n** [comment]
The rem unit is automatically relative to the root element (html). Simply setting body {1.4rem} is automatically `$html-size * 1.4`.

**Comment by jgthms** [comment]
@Ra1d3n is correct.

**Comment by Wikiki** [comment]
@Ra1d3n  : I agree with you. But you base your reflexion on my update of generic.sass (my proposal in my first post). So actually $html-size variable does not exists. I added it into generic.sass file to manage it.
So I'll make a PR for it.

**Comment by Ra1d3n** [comment]
Actually there is a variable, its just named differently.
    /base/generic.sass
    html
      background-color: $body-background
      font-size: $body-size

I think the name is fine, because `html` does not have any visible elements outside of `body`. An option would be to call it `$base-size`  or `$root-size` but it works fine as it is. You should really read more code before making requests.

**Comment by Wikiki** [comment]
yes you're right. but $body-size is used for html font-size and body font-size. So without splitting those variables I can't manage it like exposed on my first post.

**Comment by Ra1d3n** [comment]
@Wikiki give ma an example where that makes sense, please.

**Comment by Wikiki** [comment]
Honestly I don't have one in mind. It's the way I use to define font sizes in my websites.
Is it the same to set:
$body-size: 14px

than

$html-size: 10px
$body-size: 1.4rem

?

**Comment by Ra1d3n** [comment]
@Wikiki No, because the variable `$html-size` is not used anywhere.

But you can just do `$body-size: 10px * 1.4` and SASS will do the calculation for you. Or you can do `$html-size: 10px; $body-size: $html-size * 1.4`.

**Comment by Wikiki** [comment]
Thanks for the explanation.
So why don't update generic.sass to manage $html-size and $body-size directly ?
So we'll have this behavior natively.

**Comment by Ra1d3n** [comment]
Because i'm just explaining to you how to get the setup that fits your preferences. It makes no sense to have two variables for those two sizes except that you may like the name better. There are no visible elements in html that are not in body. But all elements refer per definition of rem to the root element, which is `html`, so the rem font size reference has to be set on `html`.

**Comment by Wikiki** [comment]
Ok.
Thank you very much for your time to give me explanation.

**Comment by Ra1d3n** [comment]
You are welcome 👍

**Comment by Ra1d3n** [comment]
See, the difference is, that the proposed solution *actually* increases all sizes. Your old solution only increased the sizes that had no explicit size set in rem. The size rem ignores parent size and is only relative to the html element. If you want parent-relative (scope sensitive) sizes you should use em, not rem.

**Comment by Wikiki** [comment]
But I did not defined rem when declaring $body-size: 10px * 1.4
and the size I want to have is the one resulting of html { font-size: 10px } body { font-size: 1.4rem }

**Comment by Ra1d3n** [comment]
So just do `$body-size: 10px` and then `body { font-size: 1.4rem }`.

**Comment by Wikiki** [comment]
this is the solution I proposed by creating a new variable $html-size and using $body-size for body rules only. So we'll have
html { font-size: $html-size; } body { font-size: $body-size; }
and be able to do:
$html-size: 10px
$body-size: 1.4rem

**Comment by Ra1d3n** [comment]
It makes no sense. I am sorry if I am not able to explain the technical background of this adequately. You will just have to believe me.

**Comment by Ra1d3n** [comment]
Why would you use a variable when you can just use CSS? the body size is never used by any other element that uses rem units. It can't. It's not the root element.

**Comment by Wikiki** [comment]
So I Just believe you ;-)

I just don't understand why I have to set $body-size: 10px; and modify body { font-size: 1.4rem } instead of using variables like anywhere else in bulma.

**Comment by Ra1d3n** [comment]
Its because then you would have to replace all references to sizes in Bulma with variables and just use pixels. Rem is basically css-native relative sizing that can be scaled directly at the root element.

You can just use: `$html-size: 10px;` and `$body-size: $html-size * 1.4;` but you would have to replace every rem size in bulma to refer to your variable instead of being automatically relative to the root through rem sizing.

I think you are confused about em and rem. If you use em instead of rem, your issues make more sense in some ways.

**Comment by Wikiki** [comment]
Ok.
But if I put $body-size: 10px then all element are good except: navbar, box, medias, table, card that are too small (but buttons and titles for example are good). So are they use the right value based on the em / rem difference you explained to me ?

So in bulma the default font size of buttons is not the same as default font size ? or box default font size ?
![Overview](https://img15.hostingpics.net/pics/803739ScreenShot20170726at193713.png)

**Comment by Ra1d3n** [comment]
All font sizes in bulma are defined as rem sizes (relative to the font-size of the html element):

    $size-1: 3rem !default
    $size-2: 2.5rem !default
    $size-3: 2rem !default
    $size-4: 1.5rem !default
    $size-5: 1.25rem !default
    $size-6: 1rem !default
    $size-7: 0.75rem !default

I have looked at the navbar.sass and all the sizes there are also rem (and some em for scoped sizing), so everything should scale correctly. I cant say why you have problems, i would have to check your complete code.

I can not debug your code for free, and this discussion does nothing to fix a problem with Bulma. If you need assistance with your stylesheets, you can contact me per direct message or over e-mail for a quote.

**Comment by Wikiki** [comment]
Ok. Thanks

**Comment by Ra1d3n** [comment]
You are welcome. :-)
