### ISSUE TITLE
Box: add border

### ISSUE THREAD

**Issue by Wikiki** [jgthms/bulma#929]
Hi,

could you please add box border management.
Currently box have shadow but we can't have a box with border without shadow.

Regards

**Comment by Wikiki** [comment]
Same for Card component

**Comment by jgthms** [comment]
Why not simply override the styles, since it's only specific to some use cases? Having `box-border: none !default` is not really useful.

**Comment by Wikiki** [comment]
I agree ```box-border: none !default```is not really useful. But why not setting a default border ```box-border: $grey-light !default```then we'll be able to customize it without overriding

**Comment by jgthms** [comment]
The problem is that box has a shadow, not a border. It's simpler for the padding.
