### ISSUE TITLE
Double check vertical-align: top in font awesome icons

### ISSUE THREAD

**Issue by tony** [jgthms/bulma#930]
https://github.com/jgthms/bulma/blob/8b0b9d76/sass/elements/other.sass#L36

Need to figure out if we want top alignment everywhere by default. In ``.content`` and ``.menu-list`` areas, it may not help.

<img width="881" alt="screen shot 2017-07-26 at 12 32 17 pm" src="https://user-images.githubusercontent.com/26336/28634962-8139788c-71fe-11e7-848f-328c4e5d29ba.png">
<img width="289" alt="screen shot 2017-07-26 at 12 32 26 pm" src="https://user-images.githubusercontent.com/26336/28634965-82cd2e3c-71fe-11e7-8b05-52bcd8c9dcea.png">

Seems to work well in navbar though:

<img width="879" alt="screen shot 2017-07-26 at 12 33 10 pm" src="https://user-images.githubusercontent.com/26336/28634987-9f58b0b2-71fe-11e7-9d65-72ea1354ee51.png">

**Comment by jgthms** [comment]
Good shout. I removed it for `.tag` recently.
