### ISSUE TITLE
Suggestion: remove overflow from html and margin from columns

### ISSUE THREAD

**Issue by nicolashuber** [jgthms/bulma#931]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.4.4]
My **browser** is: Google Chrome 59

I am sure this issue is **not a duplicate**

### Description

Currently, in version 0.4.4 the tag `html` and `columns` has:

```css
html {
  overflow-x: hidden;
  overflow-y: scroll;
}
.columns {
  margin-left: -0.75rem;
  margin-right: -0.75rem;
  margin-top: -0.75rem;
}
```
On `html` the property `overflow-x` prevents horizontal scroll, but ends up hiding the content and avoiding the user to see it. The property `overflow-y` always ends up showing a scrollbar. But if I set `overflow:visible`, the default value, the `.columns` create a horizontal scroll because it has a negative margin.

**Why `.columns` need a margin?
Is it similiar to `.row` on Bootstrap?**

```html
<body>
  <div class="columns">
    <div class="column">
      <div class="notification is-warning">Auto</div>
    </div>
    <div class="column">
      <div class="notification is-warning">Auto</div>
    </div>
  </div>
</body>
```
I'm using in the correct way? If yes, the `.column` padding it should appears on body like `.col-xx` on Bootstrap?

![example](https://user-images.githubusercontent.com/7015206/28635192-18776572-7210-11e7-947e-1e6ab55b49dc.jpg)

On Bootstrap the column has a padding of 15px that doesn't appears outside the `body`

I'm creating a suggestion pull-request to adjust this, but first I need to check if I'm not using it wrongly or maybe it's just how Bulma works.

**Comment by jgthms** [comment]
See https://github.com/jgthms/bulma/pull/932

**Comment by jgthms** [comment]
See https://github.com/jgthms/bulma/pull/932

**Comment by FaezehZamiri** [comment]
thanks, it is worked for my issue
