### ISSUE TITLE
Bug dropdown in hero (primary) menu items not visible

### ISSUE THREAD

**Issue by jeroenrinzema** [jgthms/bulma#935]
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.4]
My **browser** is: Chrome 59
I am sure this issue is **not a duplicate**?

### Description

When a dropdown button is placed inside a hero container are the colors of the dropdown items being inherited.

### Steps to Reproduce

Place a dropdown button in a hero container that is primary (is-primary).

### Expected behavior

An exception should be made for the menu items in the button to not override their color.
`.hero.is-primary a:not(.button), .hero.is-primary strong {
    color: inherit;
}`

### Actual behavior

Menu dropdown items color are being inherited.

**Comment by ankitrg** [comment]
This happens for me too

**Comment by connectkushal** [comment]
@jgthms  please add label `combination`
