### ISSUE TITLE
.is-fullwidth does not exist

### ISSUE THREAD

**Issue by aurigadl** [jgthms/bulma#938]
Is it about Bulma
Is it a bug

This is about the Bulma **CSS framework** 
I'm using Bulma **version**  0.4.3 
https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.3/css/bulma.css

I am sure this issue is **not a duplicate**

### Description

The class is-fullwidth does not exist

### Steps to Reproduce

Search .is-fullwidth alone in the code.
You find the class with other elements button.is-fullwidth select.is-fullwidth etc ...

**Comment by jgthms** [comment]
Fixed!

**Comment by Valar103769** [comment]
English is not my native language; please excuse typing errors.

[.section.is-fullwidth] There is in the official website code, and there is no source code on github.
