### ISSUE TITLE
Add .is-vertically-paddingless (and others) helpers

### ISSUE THREAD

**Issue by Kayyow** [jgthms/bulma#942]
### Overview of the problem

This is about the Bulma **CSS framework**

### Description

I propose simply to add 4 helpers classes to use with multiple elements or components :
- .is-vertically-paddingless
- .is-horizontally-paddingless
- .is-vertically-marginless
- .is-horizontally-marginless

I currently use `.is-vertically-paddingless` for sections I don't want the vertical padding. I think the others (margin and horizontally) could be useful for different cases.

### Code

```SASS
.is-vertically-marginless
  margin-bottom: 0 !important
  margin-top: 0 !important

.is-horizontally-marginless
  margin-left: 0 !important
  margin-right: 0 !important

.is-vertically-paddingless
  padding-bottom: 0 !important
  padding-top: 0 !important

.is-horizontally-paddingless
  padding-left: 0 !important
  padding-right: 0 !important
```

**Comment by jgthms** [comment]
Merged! Thanks.
