### ISSUE TITLE
.is-size-7 helper is not present

### ISSUE THREAD

**Issue by saintplay** [jgthms/bulma#949]
The docs says you can use the 7 sizes for typography helpers,
but actually, I only get classes from `is-size-1` to `is-size-6`

![image](https://user-images.githubusercontent.com/9372893/28741639-71359bda-73e0-11e7-83d7-407c6b62282f.png)

**Comment by shirohana** [comment]
Has it been fixed in previous commits?

I need `is-size-7`, too <3 

https://github.com/jgthms/bulma/blob/master/sass/utilities/variables.sass#L150
