### ISSUE TITLE
Icon with is-danger

### ISSUE THREAD

**Issue by Zabanya** [jgthms/bulma#95]
```
      <nav class="navbar">
        <div class="navbar-left">
          <a class="navbar-item">
            <p class="control is-grouped">
              <span class="icon is-small"><i class="fa fa-minus"></i></span>
              <input type="text" class="input is-small" value="1">
              <span class="icon is-small"><i class="fa fa-plus"></i></span>
            </p>
          </a>
          <a class="navbar-item is-danger">
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
          </a>
        </div>
      </nav>
```

result it's still blue.
![nav](https://cloud.githubusercontent.com/assets/1352081/13201687/c139a014-d8ae-11e5-90a3-3f215a269a57.png)

am I missing something?.

Regards.

**Comment by PanArnaud** [comment]
`<a class="button is-danger is-outlined"> 
  <i class="fa fa-times"></i>  
</a>`

Seems that you need the `button` class ?

**Comment by jgthms** [comment]
`is-danger` is only available for `.button`, `.input`, `.message`, `.notification`, `.hero` etc. but **not** everything.
