### ISSUE TITLE
Request - Justifying is-narrow columns for centering

### ISSUE THREAD

**Issue by kennedybaird** [jgthms/bulma#950]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.4.4]
My **browser** is: Chrome 59

### Description

Something I repeatedly want to do is center a range of columns when having only a few columns that are all is-narrow (or when having lots of columns multiline)

I solve this by adding my own .is-justified css class for justify-content: center (or manually hacking it in)

### Steps to Reproduce
```
<div class="columns is-vcentered is-multiline is-mobile" style="justify-content: center;">
<div class="column is-narrow"><span class="button">orchard maintenance</span></div>
<div class="column is-narrow"><span class="button">herbal product making</span></div>
<div class="column is-narrow"><span class="button">cooking</span></div>
<div class="column is-narrow"><span class="button">preparing firewood</span></div>
<div class="column is-narrow"><span class="button">weed management</span></div>
<div class="column is-narrow"><span class="button">beekeeping</span></div>
<div class="column is-narrow"><span class="button">housekeeping</span></div>
<div class="column is-narrow"><span class="button">compost preparation</span></div>
<div class="column is-narrow"><span class="button">seedling propagation</span></div>
<div class="column is-narrow"><span class="button">land stewardship</span></div>
</div>
```

**Comment by jgthms** [comment]
There's already `.columns.is-centered`: https://github.com/jgthms/bulma/blob/2e08a844d7b38d57c82edccce54805d56059a439/sass/grid/columns.sass#L289
