### ISSUE TITLE
[Question] How to add columns dynamically and make them wrap?

### ISSUE THREAD

**Issue by TheBlueSky** [jgthms/bulma#952]
### Overview

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.4.4
My **browser** is: Chrome (I'm using it in Electron)
It is **not a duplicate** AFAIK.

### Description

I'm adding a `div` with `column` class inside a parent `div` with `columns` class, based on a user's action. The parent `div` is:

```html
    <div id="parent" class="columns">
```

and each child is something like

```html
    <div class="box column is-one-quarter">...</div>
````

What I'm trying to achieve is to have 4 columns in each line; then, whenever I add the 5th, it I want it to go to the next line.

I'm not sure if `columns` and `column` are the right choice here and didn't find my answer here or in the documentation.

Is what I'm trying to achieve possible? If yes, how?

**Comment by jgthms** [comment]
Use `is-multiline`.

https://codepen.io/jgthms/pen/Bdjzmv

**Comment by TheBlueSky** [comment]
Oh, thanks :)

**Comment by otabekgh** [comment]
thanks)))

**Comment by prash212** [comment]
Thanks

**Comment by forgetz** [comment]
thanks

**Comment by kchetan92** [comment]
> Thanks, In Bulma did they missed to mention it?

It's available here: https://bulma.io/documentation/columns/options/#multiline , 

I wish they had a single page to showcase all the features. It is difficult to navigate the documentation.

**Comment by WalkerWalker** [comment]
@TheBlueSky  I'm quite new to frontend.  Is it possible for you to share some code snippet of adding columns and/or rows according to users action? Thanks!

**Comment by aarhatiserv** [comment]
it's not working for dynamic data when i am pushing multiple columns using javasctipt
