### ISSUE TITLE
Navbar is not centralized on components docs

### ISSUE THREAD

**Issue by nicolashuber** [jgthms/bulma#957]
This is about the Bulma **Docs** 
I'm using Bulma **version** [0.5.0] 
I am sure this issue is **not a duplicate**?

### Description

In components docs, the navbar is not centralized and the menu links are align to left.

### Expected behavior

Centralized navbar, same as other pages.

### Actual behavior

![uncentralized_navbar](https://user-images.githubusercontent.com/7015206/28749170-37153680-7495-11e7-979e-49a250289e3d.png)

**Comment by jgthms** [comment]
Yeah it's on purpose, to prevent having a scrollbar that doesn't go across the whole width of the screen.
