### ISSUE TITLE
is-outlined, is-inverted modifiers for tags list

### ISSUE THREAD

**Issue by kmare** [jgthms/bulma#959]
### Overview of the problem

This is about the Bulma **CSS framework** 

I'm using Bulma **0.5.0** 

### Description

Would be nice to have the "is-outlined" and "is-inverted" modifiers for the new tags list feature in 0.5.0 (just like in the button class).
PS: Thank you for this awesome framework!

**Comment by jimblue** [comment]
Bump !

**Comment by jgthms** [comment]
You can use the buttons class for that in 0.6.1
