### ISSUE TITLE
Delete Button Bug in iOS Safari (inside Tags, Messages and Notifications)

### ISSUE THREAD

**Issue by inseldesign** [jgthms/bulma#963]
![img_0156](https://user-images.githubusercontent.com/5708900/28753761-96aaf428-7539-11e7-8277-1e8cbf7f786f.PNG)

### Overview of the problem

Delete button with messages on ios safari. Happens only inside tag, messages and notifications.

**Comment by ialhashim** [comment]
I found a hack by setting padding to zero

**Comment by alcovegan** [comment]
Looks like same as #514 and proposed solution in #549, but not merged.

**Comment by johan13** [comment]
I think it's also the same as #490. Both #514 and #490 have been closed without fixing the problem. I hope this issue doesn't face the same fate.

**Comment by mdavid88** [comment]
It needs font-size: 0.

https://stackoverflow.com/questions/3777494/is-it-possible-to-override-the-minimum-width-of-a-button-in-safari-on-ipad
