### ISSUE TITLE
Issue on the main website

### ISSUE THREAD

**Issue by r0st1kuzh** [jgthms/bulma#97]
Hello guys! 
Here is error on main website: http://screencast.com/t/ovrzQhmyot 
I've tied from different browsers and it was the same.

Hope would be helpful!

**Comment by vasifnawaz** [comment]
I would say, it is probably better to track this issue in the website repository. https://github.com/jgthms/bulma-website/issues

**Comment by jgthms** [comment]
Thanks @r0st1kuzh ! As @vasifnawaz said, can you raise an issue here: https://github.com/jgthms/bulma-website/issues
