### ISSUE TITLE
Bulma columns don't wrap?

### ISSUE THREAD

**Issue by sigil88** [jgthms/bulma#972]
### Overview of the problem
When using Bulma's cards, they do not wrap by default and overflow horizontally so that any columns that do not fit are hidden. This might be intentional and therefore not a bug but I expected flex items to wrap rather than become hidden?

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.0]
My **browser** is: Chrome 60.0.3112.78 (Official Build) (64-bit)

### Steps to Reproduce
Here's a codepen below, but essentially this happens to all `<div class="column">` if they add up to more than 12 within a "columns" container.
https://codepen.io/sigil/full/dzGQQJ

### Expected behavior
I thought that they should automatically wrap, rather than have the overflow become hidden?
I get around this behaviour by just adding: `flex-wrap: wrap` to the "columns" div.

A screenshot of my workaround:
![with-wrap](https://user-images.githubusercontent.com/8853855/28757565-b73690b4-757d-11e7-8023-a7de135bd854.jpg)

### Actual behavior
The divs that "overflow" are hidden.
https://codepen.io/sigil/full/dzGQQJ

A screenshot from my project:
![no-wrap](https://user-images.githubusercontent.com/8853855/28757563-a4595f1c-757d-11e7-9025-51fbbbe64c91.jpg)

**Comment by VizuaaLOG** [comment]
If you add `is-multiline` to your `.columns` element it should wrap automagically.

**Comment by sigil88** [comment]
Ah that does it. Thanks - I must have missed that in the docs.

**Comment by VizuaaLOG** [comment]
No worries. Have fun!
