### ISSUE TITLE
[Request] Snackbar / Toast component

### ISSUE THREAD

**Issue by hdl-helsinki** [jgthms/bulma#976]
Is it a bug/feature/question or do you need help?  **It is a feature**

### Overview of the problem

This is about the Bulma **CSS framework**

I am sure this issue is **not a duplicate**

### Description
I'd like to have a Snackbar / Toast component so I can show a 'success' message after sending a form.

Thank you very much.

**Comment by jgthms** [comment]
You can probably use http://bulma.io/documentation/elements/notification/

**Comment by paper777** [comment]
+1

**Comment by rfoel** [comment]
I made a simple plugin for that: https://www.npmjs.com/package/bulma-toast

**Comment by rfoel** [comment]
I made a simple plugin for that [https://rafaelfran.co/bulma-toast/](https://rafaelfran.co/bulma-toast/)
