### ISSUE TITLE
Some bugs in Documentation page?

### ISSUE THREAD

**Issue by Ferrmolina** [jgthms/bulma#98]
Hello.
I don't know if its me or what appened but, I see some errores with HERO colored headers.
Look at the pics: [Link to imgur](http://i.imgur.com/vBecvlA.png)

Using **Google Chrome Versión 48.0.2564.116 m**
I never used this framework, but, its really cool, while reading all the documentation I'm surprised that and decided to publish it here.

Thanks.

**Comment by PanArnaud** [comment]
Same here

**Comment by shubhambeck1995** [comment]
Yes.  Hero colors on the documentation page aren't  working. Its completely white.

**Comment by Ferrmolina** [comment]
Now looks great. Amazing job, i'll use this to my website :)
Thanks. :+1:
