### ISSUE TITLE
Cannot add is-$color to div or section

### ISSUE THREAD

**Issue by ankitrg** [jgthms/bulma#980]
I think I am missing something very basic here. Am I not supposed to add is-color to any div or section cause it doesn't seem to work, what is the right way to achieve this? Can you please help me with this?

**Comment by VizuaaLOG** [comment]
the `is-*` color modifiers can only be applied to elements that support it. Such as `buttons`, `notifications` and `heros`. The documentation now contains tags at the top to let you know if colors are supported.

For example, [box](http://bulma.io/documentation/elements/box/) has `colors: no` where as [button](http://bulma.io/documentation/elements/button/) has `colors: yes`.

**Comment by jgthms** [comment]
For simple text color, you can use `has-text-primary`. See http://bulma.io/documentation/modifiers/typography-helpers/
