### ISSUE TITLE
Input form fields have negative left padding value

### ISSUE THREAD

**Issue by zachleigh** [jgthms/bulma#981]
### Overview of the problem

This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.5.0
My **browser** is: Firefox, Chrome on Linux

### Description

Input fields do not have left padding. Textareas are fine, but all inputs and selects have left padding values of calc(-0.375em).
![screenshot_20170801_060452](https://user-images.githubusercontent.com/5616626/28798399-5ed3a6de-767f-11e7-8906-6c875f6187d3.png)

### Steps to Reproduce

My markup for the above form:
```html
<form method="POST" action="login">
    <div class="field">
        <label class="label">Username</label>
        <div class="control">
            <input
                name="username"
                id="username"
                class="input"
                type="text"
                placeholder="Username"
            >
        </div>
        @if ($errors->has('username'))
            <ul>
                @foreach ($errors->get('username') as $error)
                    <p class="help is-danger">{{ $error }}</p>
                @endforeach
            </ul>
        @endif
    </div>
    <div class="field">
        <label class="label">Password</label>
        <div class="control">
            <input
                name="password"
                id="password"
                class="input"
                type="password"
                placeholder="Password"
            >
        </div>
        @if ($errors->has('password'))
            <ul>
                @foreach ($errors->get('password') as $error)
                    <p class="help is-danger">{{ $error }}</p>
                @endforeach
            </ul>
        @endif
    </div>
    <div class="field">
        <div class="control">
            <button
                id="loginButton"
                class="button is-primary"
            >
                Login
            </button>
        </div>
    </div>
</form>
```

### Expected behavior

There should be some left padding in the input fields.

### Actual behavior

Left padding has a negative value.

**Comment by jgthms** [comment]
Huh, it should be `calc(0.625em - 1px)`. Can you post a screenshot of the Chrome inspector?

**Comment by zachleigh** [comment]
The documentation page is working fine for me and shows the correct value, calc(0.625em - 1px). Only my project seems to be messed up. There is no other CSS in the project at this time.

![screenshot_20170801_061843](https://user-images.githubusercontent.com/5616626/28798966-70feeeac-7681-11e7-844b-be76dd05bae1.png)

**Comment by jgthms** [comment]
What are you using to compile the Sass? It must be a plugin that tries to optimise your CSS but fails to do it correctly.

**Comment by zachleigh** [comment]
Yeah, that was it. Not sure which one did it, but using the css from the Bulma project directly (no optimizers/preprocessors) works fine. Closing this. Thanks for the help and for making Bulma. Loving it so far!
