### ISSUE TITLE
.is-size-n classes  do not work inside tables

### ISSUE THREAD

**Issue by andreimoment** [jgthms/bulma#986]
### Overview of the problem
This is about the Bulma **CSS framework**
I'm using Bulma **version** [0.5.0]
My **browser** is: Chrome 60

### Description

Bug: .is-size-n classes do not work inside tables

### Steps to Reproduce

Create a table:

    <table class="table">
        <tbody>
            <tr>
                <td>
                  Table default font size <br>
                  <span class="is-size-7">Small font</span>
                </td>
            </tr>
        </tbody>
    </table>

### Expected behavior

The line containing the words "Small font" should have a smaller font size

### Actual behavior

It has the same font size as the line above it.

**Comment by jgthms** [comment]
This is a dupe for the is-size-7 bug.
