### ISSUE TITLE
Bug: using is-shadowless gives a borderless box or card component

### ISSUE THREAD

**Issue by connectkushal** [jgthms/bulma#988]
### Overview of the problem

The new `is-shadowless` modifier(#934) when used in `box` or `card` gives no borders at all. Possibly due to this issue #929. 

----
This is about the Bulma **CSS framework**
I'm using Bulma **version** 0.5.0

**Comment by jgthms** [comment]
That's normal since it's a shadow, not a border. You can customise the shadow if you want with the `$box-shadow` variable.

**Comment by connectkushal** [comment]
ok. Thanks for the info
