### ISSUE TITLE
Mobile menu new behaviour

### ISSUE THREAD

**Issue by arthurkirsz** [jgthms/bulma#99]
Hi,

I was wonderring why has the mobile menu behaviour changed ?

It used to be a fixed width, in overlay of the content. 
Now when you open it, it looks more like bootstrap mobile nav.
It pushed the content down, and it is full-width.

I prefered the previous behaviour :( 
Is there a way to use it the old way ? Is there a particular reason you choosed this new behaviour ?

Thank you for your time.

**Comment by tomeglenn** [comment]
Hi, are you talking about the header mobile menu?

I may be missing something but how do I get the header-toggle to actually work? It doesn't do anything when clicked. Is there some missing js?

**Comment by arthurkirsz** [comment]
@tomeglenn Exactly. I speak about the header mobile menu.

Btw, you have to toggle the class with JS to make it work. Here is a snippet from the bulma website : 
```

    var $toggle = $('.header-toggle');
    var $menu = $('.header-menu');

    $toggle.click(function() {
      $(this).toggleClass('is-active');
      $menu.toggleClass('is-active');
    });
```

**Comment by tomeglenn** [comment]
Perfect thank you, I didn't think to check the source of the site :)

**Comment by jgthms** [comment]
Hey @arthurkirsz 

Yeah I changed the behavior because having a dropdown menu in `position: absolute` could lead to some issues, where the menu would appear behind another element, especially another header.

Also, the tap area was a bit small, you couldn't click "outside" to close the menu (which is the preferred behavior), the menu wasn't expandable for more items, the height of the header had to be fixed...

Anyway, I can tell you how to apply the previous style.

**Comment by arthurkirsz** [comment]
@jgthms Your arguments seem reasonable, I think you convinced me :) 

Also for learning and curiosity purpose, I'd love it if you could write me a code snippet to get the previous behaviour (only if you have a couple minutes to spare :p ).

Anyway, thank you for making Bulma !

**Comment by jgthms** [comment]
@arthurkirsz This is the commit where it changed: https://github.com/jgthms/bulma/commit/354cecb05ff9da4db36ab483e54c710153d8c644

You need to add back the red stuff and remove the green stuff :smile: 

Basically the `.header-menu` needs to have something like this:

```
min-width: 120px
position: absolute
right: 0
top: 50px
z-index: 100
```

Something like that.
