### ISSUE TITLE
Error when converting bulma sass to css

### ISSUE THREAD

**Issue by Acidic9** [jgthms/bulma#997]
### Overview of the problem

This is about the Bulma **CSS framework**

I'm using Bulma **version** [0.5.0]
This is a **Sass** issue: I'm using version [0.5.0]

### Description

I am using the sass ruby command line tool to convert my styles.sass file to css but I recieve the following error:

```bash
$ sass sass/styles.sass css/styles.css
Error: Invalid flag "!important".
        on line 17 of sass/lib/bulma/components/tabs.sass
        from line 15 of sass/lib/bulma/components/_all.sass
        from line 6 of sass/lib/bulma/bulma.sass
        from line 1 of sass/styles.sass
  Use --trace for backtrace.
```

My file structure:

 ```
.
|
+---css
|   |   styles.css
|
\---sass
    |   styles.sass
    |
    \---lib
        \---bulma
            |   bulma.sass
            |
            ----base
            ----components
            ----elements
            ----grid
            ----layout
            \---utilities
```

### Steps to Reproduce

1. Install bulma in `sass/lib/bulma/..`
2. Create a file called `sass/styles.sass` containing the following text:
    `@import "lib/bulma/bulma"`
3. Run `sass sass/styles.sass css/styles.css`

### Expected behavior

styles.css should have been generated with the bulma css within the file.

### Actual behavior

Recieved the following output after running `sass sass/styles.sass css/styles.css`

```
$ sass sass/styles.sass css/styles.css
Error: Invalid flag "!important".
        on line 17 of sass/lib/bulma/components/tabs.sass
        from line 15 of sass/lib/bulma/components/_all.sass
        from line 6 of sass/lib/bulma/bulma.sass
        from line 1 of sass/styles.sass
  Use --trace for backtrace.
```

**Comment by jgthms** [comment]
Dupe, fixed in `0.5.1`

**Comment by Acidic9** [comment]
And how do I install 0.5.1?

**Comment by tudoanh** [comment]
But where is the `0.5.1`?
