### ISSUE TITLE
User avatar in navbar-item

### ISSUE THREAD

**Issue by r0v** [jgthms/bulma#998]
### Overview of the problem

Hi!

Today I started using Bulma framework to create a new forum template (for Mybb engine).
And I thinking how to add user avatar to navbar menu?

This is about the Bulma **CSS framework** 
I'm using Bulma **version** [0.5.0]

### Description
I tried to add .media derective and combination with dropdown/navbar elements because allways when I use .navbar-item and add img object inside I have a max-height properties which limits avatar height (it looks weak).
Additionally when I use std navbar conception (from bulma docs) a dropdown menu is out browser:

![one](https://user-images.githubusercontent.com/17937613/28876352-3012ea38-7799-11e7-9dca-6a80ad40b96b.png)

When I add .media and replace navbar-dropdown to the dropdown:

![two](https://user-images.githubusercontent.com/17937613/28876373-43b9bf6c-7799-11e7-817a-9cd5b6467729.png)

Of course, I could override some styles to add a new class, but I wonder if it would be possible to do it exclusively with bulma alone.

I do not know whether to call it a bug or not.

### Expected behavior

Navbar will be fine if it will have .is-right like dropdown and will not be limited to img.

PS. Sry for my english...

**Comment by jgthms** [comment]
You will have `.navbar-dropdown.is-right` in `0.5.1`.
