### ISSUE TITLE
Navbar hover background colour

### ISSUE THREAD

**Issue by danjharrin** [jgthms/bulma#999]
I see on the navbar docs page that the examples have a grey background on hover. How can I implement this on my website?

This needs to be added to the documentation.

**Comment by r0v** [comment]
Just add an item with class .navbar-item to your navbar menu, something like this:
`<nav class="navbar">
	<div class="navbar-brand">
		
		
		<a class="navbar-item" href="http://bulma.io">
                    <img src="" alt="Bulma: a modern CSS framework based on Flexbox">
                </a>
	</div>
	<div class="navbar-menu">
		

		
		<div class="navbar-start">
			<a href="#" class="navbar-item">First menu item</a>
		</div>

		
		<div class="navbar-end">
		</div>
	</div>
</nav>`
Everything is explained very well in the docs examples. Anyone who knows the basics of html / css should be able to use it even this without reading full docs
